### ISSUE TITLE
[TODO] - Animate entry doors

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#100]
### Describe the bug

Entry doors for both exterior, interior, PAX, and Cargo variants of the aircraft are not animated.

### Steps to reproduce

N/A

### Expected behaviour

Doors are supposed to animate.

### Simulator

P3Dv4, Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
@arwasairl Isn't this already done? The EFB has control of 1L-4R on the PAX and also the cargo doors for cargo.
