### ISSUE TITLE
[BUG] - TCAS target altitude filter

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1001]
### Describe the bug

TCAS is currently showing all the planes regardless of their altitude relative to own aircraft. 

### Steps to reproduce

Fly with traffic and observe the TCAS targets

### Expected behaviour

Now we can see planes with 35000ft altitude difference. Talking with few pilots I've been told that the max altitude difference is usually 9900ft to either direction and another one has said 6000ft. I did not find the correct altitude filter from the manuals to back up the claim, however.

### Evidence

The altitude is usually shown with 2 digits so that would back up the claim for +99/-99 filter.
![image](https://github.com/invernyx/md11-bugs/assets/102414406/65398b2a-8203-4d53-bafc-3f368ccead18)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by MikeA34** [comment]
I cannot find anything from the manuals but according to [this](https://www.airteamimages.com/mcdonnell-douglas-md-11_D-ALCR_lufthansa-cargo_205836) picture the maximum difference is more than 6000ft

**Comment by GenericNerd** [comment]
> I cannot find anything from the manuals but according to [this](https://www.airteamimages.com/mcdonnell-douglas-md-11_D-ALCR_lufthansa-cargo_205836) picture the maximum difference is more than 6000ft

There's a +80 on the display, so I will work with this assumption instead.

**Comment by GenericNerd** [comment]
This will be resolved in the next version
