### ISSUE TITLE
[BUG] - Incessant clicking (FMS keypad sounds?) throughour

### ISSUE THREAD

**Issue by plhought** [invernyx/md11-bugs#1002]
### Describe the bug

After booting aircraft, incessant clicking sound similar to MCDU keypad sound continually runs

### Steps to reproduce

Boot aircraft. Stops when using right-click freelook (controls inhibited).
I have the following peripherals connected:
 - two TCA Throttle w/ associated spoiler/flap modules
 - one t16000m stick
 - Saitek pro-flight rudder pedals
 - Xbox 3360 controller.

### Expected behaviour

Not to have clicking?

### Evidence

https://discord.com/channels/589851727373795331/1047626446480351242/1226198992703193188

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
If you disconnect the peripherals, does this clicking stop?
