### ISSUE TITLE
[BUG] - APU Starts instantaneously

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1003]
### Describe the bug

The APU start within 2 seconds after pressing the button on the electrical panel

### Expected behaviour

The APU normally, upon pressing the start button, take a couple of minutes to start. After revision 41.01 it starts within 2 seconds. The light flashes while starting and goes steady when started. The "AVAIL" light appears when the volts are at 115V and the Freq is 400 HZ. 

### Evidence

n

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Repeat of #115 
Which was closed but never corrected.

**Comment by uwiuke** [comment]
Another issue which still exists since month. Correct the major issues which are important first.
Not possible to sold this product with this major bugs.

**Comment by JeffRichard1958** [comment]
Understood. Thank you for your reply.

**Comment by GenericNerd** [comment]
I'm not able to replicate this in P3D. It is possible this is MSFS specific only. I am still investigating this further.

**Comment by JeffRichard1958** [comment]
Probably just MSFS. I just flew and it was still an instant start.Sent from my iPadOn Apr 9, 2024, at 1:33 PM, GenericNerd ***@***.***> wrote:﻿
I'm not able to replicate this in P3D. It is possible this is MSFS specific only. I am still investigating this further.
