### ISSUE TITLE
Unusual advisories on the EAD after initial power-up

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1004]
### Describe the bug

After initial power up of the electrical system, there were several advisories not normally present. 

### Expected behaviour

With full AC and DC power, and with ALL packs operating, I had the EAD messages below. I have bracketed the inaccurate messages.  In addition, all of these messages remained on for the duration of the flight, but all systems operated normally.

### Evidence

![Screenshot 2024-04-06 131724](https://github.com/invernyx/md11-bugs/assets/148719444/bcd20694-ad67-4aff-98d5-fc58c0ec5348)
![Screenshot 2024-04-06 131756](https://github.com/invernyx/md11-bugs/assets/148719444/1edc2cee-22c7-4e40-8ce1-d7fc2ee22e88)
![Screenshot 2024-04-06 131812](https://github.com/invernyx/md11-bugs/assets/148719444/3f47260f-2a9e-41c9-b150-e204950bf144)
![Screenshot 2024-04-06 131812](https://github.com/invernyx/md11-bugs/assets/148719444/722abce0-8593-4c04-bbee-a1087d6ff167)
![Screenshot 2024-04-06 133123](https://github.com/invernyx/md11-bugs/assets/148719444/b36e6956-3369-4425-a498-15f24f117ff9)
![Screenshot 2024-04-06 133530](https://github.com/invernyx/md11-bugs/assets/148719444/a9b65bf7-8555-4586-bc2a-2be49ebccaa3)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by MikeA34** [comment]
Already reported

**Comment by turbofandude** [comment]
Should be resolved in 0.41+
