### ISSUE TITLE
[BUG] - ELEC panel, SYSTEM SELECT/MANUAL Switch must flash

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1005]
### Describe the bug

MANUAL flashes amber if the system is in auto and a switch on the ELEC control panel has been pushed that has no effect in auto.

### Steps to reproduce

Set ELEC system in auto.
Press any Switch that has no effect if system is in auto mode:
- GEN 1/2/3 ARM/OFF Switch
- AC TIE 1/2/3 ARM/OFF Switch
- DC TIE 1/3 OFF Switch

### Expected behaviour

MANUAL flashes amber if the system is in auto and a switch on the ELEC control panel has been pushed that has no effect in auto.

### Evidence

https://github.com/invernyx/md11-bugs/assets/153389460/c848afb6-6a09-4141-94fd-a11d814ccb32

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

-

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
As you described, this is correct behaviour. The switches do not have any effect during AUTO, therefore the manual light will flash amber. Please refile with correct bug and expected behaviour descriptors if this is not what you meant.

**Comment by Dimples82** [comment]
When you press AC TIE 3 ARM/OFF Switch and DC TIE 1/3 OFF Switch noting happens...
Its supposed to flash amber,

**Comment by GenericNerd** [comment]
The specificity of the buttons that weren't working as expected helped identify the issue. This will be resolved in the next version.
