### ISSUE TITLE
[SUGGESTION] - ANNUN LT TEST should illuminate Service Interphone Call Panel switches

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1006]
### Is your feature request related to a problem? Please describe.

Even though the Service Interphone Call Panel is not modeled, the switches could be illuminate when performing a ANNUN LT TEST.

### Describe the solution you'd like

When performing a ANNUN LT TEST, the Service Interphone Call Panel switches should illuminate.

### Describe alternatives you've considered

-

### Additional context

https://github.com/invernyx/md11-bugs/assets/153389460/99390b28-be16-4972-9f44-55133a7f5def

**Comment by turbofandude** [comment]
Should be resolved in 0.59+
