### ISSUE TITLE
[BUG] - AIR & EVAC Panel backlights not working (Freighter)

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#1009]
### Describe the bug

AIR & EVAC Panel backlights not working (Freighter)

### Expected behaviour

See #553. This has been reported and even marked as completed previously. 

AIR & EVAC Panel backlights should work

For reference here is PAX OVHD panel:
![Näyttökuva 2024-04-06 234322](https://github.com/invernyx/md11-bugs/assets/150369113/ff4c9a2f-2188-46cb-bdba-d613b6dccc0b)

### Evidence

This is how it currently is on the Freighter:
![Näyttökuva 2024-04-07 014358](https://github.com/invernyx/md11-bugs/assets/150369113/b4d8a4dd-9daa-409a-8afa-ddfa3dd2ad56)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
This has been resolved for quite some time
