### ISSUE TITLE
[BUG] - NOT POSSIBLE TO LAND WITH FLAPS 50 !!!!!

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#1010]
### Describe the bug

Wrong pitch during landing with Flaps 50

### Steps to reproduce

I'm very disappointed and very unsatisfied. I report this issue now the third or fourth time (since month).
Every report has to be approved and this issue is still existing.

### Expected behaviour

Solve the problems which are important and not a lot of minor and abosultely unnecessary issues at this stage of the product development.

### Evidence

It's timelost to report this issue every time with evidence - see the evidence pictures the couple of issue reports in the last months.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by joon44** [comment]
You dont have to report it every time :)
