### ISSUE TITLE
[BUG] - SYSTEMS CRASH DESCENDING ON PROF

### ISSUE THREAD

**Issue by OD-Emperor** [invernyx/md11-bugs#1011]
### Describe the bug

Doing a short flight from Memphis to Rockford and have experienced twice now where the sim will crash and stop responding. It will not crash to desktop, but it will freeze the sim with sound still running.

### Steps to reproduce

Routing: KMEM/18R JTEEE5 ODATE DCT MAW DCT ENL DCT HAAYQ SOSSO KRFD/07 at FL350.

Fly the route as normal. Descend at the calculated TOD in PROF. At about FL260 the sim will freeze as described. I've been able to recreate this twice now. I was using the default (non-updated) navdata which did not have a selectable STAR into KRFD, so I just went via the SOSSO transition point for the approach to give a few more track miles and a shallower turn into the ILS.

However I did not do this the first time around, so this does not seem to affect it. 

I'm going to fly this routing again at FL250 to see if anything changes, with the proper navdata updated.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by OD-Emperor** [comment]
Just redid this flight with navdata updated, a STAR, and below FL260 and no crash. So maybe it's a navdata issue?

**Comment by turbofandude** [comment]
We resolved a scenario in 0.41 that could cause this sort of behavior. Please let us know if it reoccurs with 0.41 or above.

**Comment by OD-Emperor** [comment]
> We resolved a scenario in 0.41 that could cause this sort of behavior. Please let us know if it reoccurs with 0.41 or above.

I think you are right, this is resolved. I just flew the same routing from KMEM/KRFD from FL370 with no STAR on approach, just the SOSSO transition and there was no issues with freezes.
