### ISSUE TITLE
[BUG] MSFS vs P3D Wing textures

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#1013]
### Describe the bug

bottom wing textures in MSFS metallic

### Expected behaviour

The wing textures should be duller and not metallic on the bottom side in MSFS. This affects both Freighter and Pax version. In P3D the wing is fine on both sides. See screenshots below (for the purpose of comparison I have flipped the P3D textures to match the MSFS one)
It should look like this:
![image](https://github.com/invernyx/md11-bugs/assets/150608109/cd97cb3f-f92f-4724-889f-8cb3bc12626e)

### Evidence

![Unbenannt](https://github.com/invernyx/md11-bugs/assets/150608109/a96939b1-9b8c-4f10-9db3-33cf62317de0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This is totally dependent on the livery and thus it will not be changed. The picture below has a very reflective wing undersurface. That said, when the paintkit is available, painters can have the ability to choose.
![image](https://github.com/invernyx/md11-bugs/assets/48654776/9b6066c3-9e6d-4eb9-8cfa-9c3e3882c800)
