### ISSUE TITLE
[BUG] - Hydraulic quantity line missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1015]
### Describe the bug

Hydraulic quantity line missing 

### Expected behaviour

Hydraulic quantity line should appear for each resevoir when applicable engine has reached idle 

### Evidence

![Schermopname (451)](https://github.com/invernyx/md11-bugs/assets/150957609/2d1a97af-1f8b-419c-a4d4-e3891a5c759d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Added in 0.42+
