### ISSUE TITLE
[BUG] - EAD green box shown before landing flaps set

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#1016]
### Describe the bug

EAD green box shown before landing flaps set

### Steps to reproduce

During approach the EAD green box is shown when flaps are still set to 28. The EAD green box should become visible when flaps are set to 35, considering that landing gear down and spoilers armed.

### Expected behaviour

![Näyttökuva 2024-04-09 001107](https://github.com/invernyx/md11-bugs/assets/150369113/2e7b1712-80b7-4937-b111-ba24ae00cabe)
![Näyttökuva 2024-04-09 001117](https://github.com/invernyx/md11-bugs/assets/150369113/89fe2852-83a2-4cdf-ba6a-7b43012b87fe)

### Evidence

![Näyttökuva 2024-04-08 234014](https://github.com/invernyx/md11-bugs/assets/150369113/5f406a2f-e043-4528-952b-1a8d69f0f9a9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.42+
