### ISSUE TITLE
[BUG] - MSFS FREEZE

### ISSUE THREAD

**Issue by skipz3r** [invernyx/md11-bugs#1017]
### Describe the bug

MSFS Freeze

### Steps to reproduce

Flying the departure out of Toronto to Memphis  
Route (manually imputted to MCDU)
CYYZ/23 MIXUT7 GNTRY DCT WOOST DCT ROD DCT PXV BLUZZ4 KMEM/18L
ZFW 171700 
TOW 198266

Conducted departure NAV and PROF Armed , 2500ft engauged AP, Imputted a Direct to: MIXUT.  Set ALT FL360 on MCP.
At approx 12.4nm towards WP PEMBA System freezed up @ FL325.  No interaction with the sim when the freeze occured.  

Unsure if MSFS was in focus ATM, but believe it was. Onlt way to exit was the end process on MSFS.

Background APPS: FSUIPC, FSCREW RAAS Pro Coualt (GSX)

### Expected behaviour

This was the same freeze occured with 0.39.0A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by shinkicker444** [comment]
**Steps to reproduce**
Entered route into MCDU (KSDF/17L STREP5 STREP DCT ROD DCT QWERI NUBER6 CYYZ/23)
Loaded weights, changed the Lower Weights around based on feedback seen in Discord about them causing an issue for CG.
Departed as expected, armed Nav and Prof, climbed to 350 until just passing ROD.
Was tabbed out of MSFS reading Discord(watching sim in the background), opened link to Crash Bug report and Sim immediately froze.

GSX, Maddog client, Aerosoft vdgs and volanta running attached to Sim... otherwise just Steam, Chrome (15 tabs) and Discord open.

**Comment by LandoT7** [comment]
Encountered the same issue.

Route: KDFW/18L N0469F400 HRPER3 HULZE DCT TXO J72 GUP DCT HAHAA RKSTR3 KLAS/01L

I took off with NAV/PROF Armed. MCP altitude was set at FL400 prior to takeoff. Hand flew the departure to 8000 then armed autoflight. From that point I turned off the landing lights and logo lights at 10,000 and set baro to STD at FL180. After that I had been switching between an Edge window and MSFS to pan around. I believe I had Edge in focus when the freeze happened this time. The freeze occurred at FL394. I had to end the MSFS process through task manager to fix it.

I had MSFS running in high priority in task manager. Realturb, Couatl, and AIG Traffic Manager were also running.

**Comment by Mulder884** [comment]
The Same

Route: KMEM/18R N0479F350 GOETZ7 DIYAB DCT BNA DCT SWAPP Q34 RBV Q419 JFK ROBUC3 KBOS/33L

After the start, at an altitude of 8000 feet, I switched on the autopilot and autoflight. 
At 9000 feet I erased the landing lights. 
At 12000 feet I zoomed in Volanta (second screen). Directly a freeze from the MSFS and only through the task manager the Sim was to close.

MSFS Settings: Real Weather and Time

 Programs used: Volanta, FSLTL, APL2, Navigraph, Internet-Explorer, GSX

**Comment by Mulder884** [comment]
I had exactly the same freze again on the same flight at an altitude of 12000 feet. However, without Volanta, Navigraph and Internet Explorer

**Comment by JohnWilkins82** [comment]
Same issue. Flight from RCTP to KLNK with 4x compression. ~3.5 hour real flight time. No issues until passing KLNK (using rwy 36 approach so had to fly past the airport) Took a screenshot and the clipping tool with windows 11 home opened. shortly after returning to sim the sim froze.  

 Run SPAD.ext and Volanta on a second screen. FSUIPC and SIMLINK also running in the background. 
Will try to recreate tomorrow.  
![N724NA](https://github.com/invernyx/md11-bugs/assets/58406371/5d03f0df-655d-4244-a24d-7885893ccd5e)

**Comment by FoxxenD** [comment]
**Flight :** KORD - HAAB
**Aircraft :** MD11ER F, with the FedEx livery (the TFDi one)
**Route :** DCT EBAKE DCT WISMO DCT POSTS DCT PADDE DCT SVM DCT WOZEE DCT GONZZ DCT EBONY/N0486F330 N125A RELIC/M084F330 DCT 46N050W 47N040W 47N030W 45N020W DCT ARMED/N0486F350 DCT BARDI/N0486F360 M191 DIPOL M871 NANDO T257 LASPO Z224 NINES/N0489F370 DCT OLMIR DCT XARON DCT GENIO DCT LUXUR UM134 ANB UA411 MORJA DCT SONAK DCT DINUX DCT ARLOS/N0486F390 UN4 SALUN N705 BOPIX N710 TAKRI P751 LXR/N0485F410 M999 JDW G650 RASKA/N0489F400 UG650 KONET/N0485F410 DCT EKBOB/N0489F400 T114 MEKEL MEKEL1A
**Runways :** 10L KORD | 07R HAAB
**Simbrief OFP :** [https://www.simbrief.com/ofp/flightplans/KORDHAAB_PDF_1712865815.pdf](https://www.simbrief.com/ofp/flightplans/KORDHAAB_PDF_1712865815.pdf)

I've entered the full route and arrival from the beginning. Added altitude constraint while still on the ground
Took off with NAV and PROF armed. Switched to HDG for 2 minutes and back to NAV and PROF
The sim froze while I was at FL310, and 0.8NM before waypoint PADDE at 305kts (Mach .819)
I was editing some text with the notepad, having brave (30 tabs, not all active), discord, Navigraph charts, my VA tracker, and some other software running in the background when the sim froze

It's my second attempt to do this flight. First was the 7th April (last Sunday). The sim had also frozen but less time after takeoff, at like FL195. Route was practically the same, and I've done the same startup of the aircraft, minus the altitude restrictions
![image](https://github.com/invernyx/md11-bugs/assets/32935159/8cabd540-446a-4502-a49f-0b678e6fa82e)

**Comment by l33ch86** [comment]
Same issue, on my flight from KMCO to CYYZ at around half way I experienced a freeze.
route: KMCO/18R N0499F310 FATHE3 VIYAP Q69 RICCS DCT OXMAN LINNG3 CYYZ/23 
version 0.41.0.1, volanta and fsuipc running in the background

**Comment by joon44** [comment]
I had a freeze on the 0.44 version. 

Route DCT ASUKA DCT SHTLE Y71 XAC XACN
Background running VAS Acars, Volanta, Spad.Next, vpilot

I was testing the enroute winds and adding multiple different wind directions/speed at FL290. When I added winds for FL150, meaning I have wind data for two different levels, the sim froze instantly when clicking INSERT
![FlightSimulator_Zy0pQKxzqj](https://github.com/invernyx/md11-bugs/assets/102414406/e6d0e8ec-76e5-4bb7-be1a-762c4bd62906)

**Comment by turbofandude** [comment]
Should now be resolved.
