### ISSUE TITLE
[SUGGESTION] - Barometer LVARs

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1018]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

LVARs for the barometer pressures for the PFD and standby altimeters

### Describe alternatives you've considered

-

### Additional context

-

**Comment by turbofandude** [comment]
Added as MD11_CAP_ALTIMETER, MD11_FO_ALTIMETER, and MD11_STBY_ALTIMETER.
