### ISSUE TITLE
[BUG] - Flight director lateral guidance

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1019]
### Describe the bug

The lateral guidance bar is offset most of the time while doing turns on autopilot when off the track. 

### Steps to reproduce

Fly normally on autopilot and observe the FD guidance

### Expected behaviour

Keep the bars centered while turning

### Evidence

Apparently the FD thinks the plane is on track and commands wings level already but the plane is 0.1 LEFT of the track so it continues to turn right to get back on track but the FD does not see this.
![FlightSimulator_38G8QxTmrJ](https://github.com/invernyx/md11-bugs/assets/102414406/73396fcf-d1a2-4fe7-ae8b-d788b4c1736b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

OPKC

### Arrival

OTHH

### Cruise level

FL300

### ZFW

209.2tn

### CG

27.1

### Fuel

17700kg

### Cost index

200

### Route

OPKC/25L N0504F300 MELO1F MELOM A325 PUNEL J167 OREMU J169 PI J120 BIVIN A791 KUSEN M677 TUKSI P699 IVOXI N571 TUDIS P699 ALKAN ALKA1V OTHH/34R

### Location

At NABIX

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Following a conversation with real MD-11 pilots, the current behaviour is correct. The guidance is ahead before/after a turn, but once they are tucked in, they should be correct.
