### ISSUE TITLE
[BUG] - Baro Ref on PFD doesn't update when using B key

### ISSUE THREAD

**Issue by opticalgenesis** [invernyx/md11-bugs#102]
### Describe the bug

When using the magic baro ref key (B by default) the value on the PFD doesn't update, but the altitude tape shows the altimeter change

### Steps to reproduce

- Press B key to automatically update the baro ref to the one in sim

### Expected behaviour

- The PFD baro ref value to change to reflect the in sim one

### Evidence

NA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Added as of 0.9
