### ISSUE TITLE
****No longer a Bug*********Unable to get a green box for takeoff due to "flaps" 

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1020]
### Describe the bug

"Flaps" in a white box after flaps set to 15 for takeoff******update- this bug is no longer present and can eliminated

### Expected behaviour

When the flaps are set to 15 and the "dial-a-flap" is set to 15, the "flaps" message in a white box should disappear, and the "green box" should appear. The green box actually flickered when the flaps reached 15, but then turned to white with a "flaps" message in the white box. CONFIG page confirmed that the flaps were set to 15 and the PFD had a "flaps 15" message.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
You can close the issue yourself from below this comment

**Comment by JeffRichard1958** [comment]
No longer a bug
