### ISSUE TITLE
[BUG] - Oscillations during climb

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#1021]
### Describe the bug

Airplane oscillates to maintain speed and heavily pitches up and down all the way up to FL210 after which it stabilizes

### Steps to reproduce

Depart from EBLG 22L LNO7E departure.
Observe pitch oscillating.

### Expected behaviour

Aircraft is able to maintain a stable pitch up to cruise level.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/6001596/f758047a-e3db-4a4b-90e6-bd78287daabe)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Pitch

n/a

### Bank

N/A

### Heading

N/A

### Altitude

600ft - 21000ft

### Departure

EBLG

### Arrival

LMML

### Cruise level

FL350

### ZFW

190000kg

### CG

26.2

### Fuel

32950kg

### Cost index

200

### Route

BLG/22L N0485F350 LNO7E LNO DCT GTQ DCT ODINA DCT PAL/N0425F190 L12 GZO DCT LMML/13

### Location

Climb out from EBLG up to approx. FL210 between LNO and GTQ

### Agreement

- [X] Yes

**Comment by kdries** [comment]
Another case of pitch oscillations during climb.
![image](https://github.com/invernyx/md11-bugs/assets/6001596/8e33e328-8e2d-4200-8f44-aaac89f43adf)
![image](https://github.com/invernyx/md11-bugs/assets/6001596/1b6df429-7f84-4cef-aed2-9476e1654a2d)
![image](https://github.com/invernyx/md11-bugs/assets/6001596/51fcbe01-8e0a-477b-8eeb-d4a46810939e)
EHAM/18L N0486F320 BERG4E BERGI L602 SUPUR L60 PENIL M144 BAGSO DCT NEBIN/M084F320 DCT 53N020W 50N030W 44N040W 38N045W 33N050W 27N055W DCT RKDIA M576 OBIKE/N0502F320 M576 MNOLO ULUBA1 TNCM/10

**Comment by Leemazz** [comment]
Also this happens for me only on longhaul when the plane is heavy on take-off

**Comment by TheFightingRaven** [comment]
when flight model is final autopilot will be retuned, this will fix this, not a seperate bug in that sense
