### ISSUE TITLE
[BUG] - VOR data decimals still missing

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#1022]
### Describe the bug

VOR data decimals still missing in version 0.41.0

### Expected behaviour

(#947)
The distance should include decimals
![205836_big](https://github.com/invernyx/md11-bugs/assets/150369113/cd9f3b36-6e39-4977-9d5c-25e8de3daa9f)

### Evidence

![Näyttökuva 2024-04-09 161031](https://github.com/invernyx/md11-bugs/assets/150369113/d301d2fd-9359-4163-be58-a21ef56c7047)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Also the left side isnt fully aligned. It is 1 digit offset from the left and the vertical line is pointing towards the decimal instead of the period ".". Right side looks good.

![image](https://github.com/invernyx/md11-bugs/assets/102414406/83b6a09f-d407-4c79-9a09-e4d1e1616f2e)

**Comment by turbofandude** [comment]
Resolved in 0.42+
