### ISSUE TITLE
P3dv5 FPS Drop When Passing FL270 

### ISSUE THREAD

**Issue by Mike230296** [invernyx/md11-bugs#1023]
### Describe the bug

FPS Drop When Passing FL270  then when dropping below FL270 FPS returns 

### Steps to reproduce

IDK

### Expected behaviour

Keep FPS Maybe Contrail Related

### Evidence

https://medal.tv/games/prepar3d/clips/26kcrrHE_IiRbr/d1337549kvQs?invite=cr-MSwzRUIsMjI1NDYzNzI2LA

### Simulator

P3Dv5

### Crash

Yes

### Phase of flight

Climb

### Altitude

270

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
The steps to reproduce must be written to the best of your ability. Please ensure the issue is reproducible. You indicated that the simulator crashed, this was not the case from your recording.

**Comment by Mike230296** [comment]
Found the reason missing effects required for p3d -

contrail = fx_MD-11_tail
startup = MD-11_start
WetEngineWash= fx_MD-11_nowash
SnowEngineWash= fx_MD-11_nowash
