### ISSUE TITLE
[BUG] - GSX Detects the wrong aircraft

### ISSUE THREAD

**Issue by slowreload** [invernyx/md11-bugs#1025]
### Describe the bug

GSX sees the MD11F as just MD11

### Steps to reproduce

Create MD11F flight plan in simbrief. click reload simbrief in gsx. Get error that the aircraft is MD11 not md11f

### Expected behaviour

GSX picks up aircraft as MD11F

### Evidence

![2024-04-09 10_26_35-Microsoft Flight Simulator - 1 36 2 0](https://github.com/invernyx/md11-bugs/assets/5056361/cab21cba-f495-47e4-aeaa-5ec497d0dedb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Seems like something that would be resolved through #887

**Comment by slowreload** [comment]
Just fyi  it Worked before 0.39.1

**Comment by joon44** [comment]
MD11 is the correct code for both freighter and passenger planes. You need to edit the simbrief profile and/or GSX profile so both say MD11

**Comment by slowreload** [comment]
Thank you for the workaround @joon44

**Comment by GenericNerd** [comment]
Will be resolved in the next version
