### ISSUE TITLE
[BUG] - External Lighting

### ISSUE THREAD

**Issue by Mets747** [invernyx/md11-bugs#1028]
### Describe the bug

Strobe Lights

### Expected behaviour

Will the Double flashing strobes in the front and one single flash in the rear be implemented soon?

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by ihulsbus** [comment]
this one was also reported in #448, which is closed with the message it will be pushed in the next artwork update

**Comment by TheFightingRaven** [comment]
@arwasairl https://www.youtube.com/watch?v=FVMKCUbpZ7c
see this vid, can we make the Hi-intesitity lights do the fron to rear flash? Low priority

**Comment by arwasairl** [comment]
Resolved

**Comment by Mets747** [comment]
I don't think this was resolved yet in the latest build?
