### ISSUE TITLE
[BUG] - Does Not Go Into Prof Mode When Hitting TOD

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#103]
### Describe the bug

WHEN HITTING TOD AUTOPILOT DOESNT GO INTO PROF MODE STAYS IN HOLD. HAVE TO MANUALLY PULL ALT KNOB TO GET THE PLANE TO DESCEND. 

### Steps to reproduce

I FLEW KONT TO KOAK SNSHN5 COREZ DCT RGOOD EMZOH3 FL360. WHEN I REACHED TOD IT STAYED IN HOLD MODE AND DIDNT GO TO PROF MODE AND DIDNT START TO DESCEND. 

### Expected behaviour

WHEN REACHING TOD PLANE SHOULD GO OUT OF HOLD MODE AND INTO PROF MODE AND START TO DESCEND. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

36000

### Departure

KONT

### Arrival

KOAK

### Cruise level

FL360

### ZFW

337.3

### CG

20

### Fuel

30.7

### Cost index

20

### Route

SNSHN5 COREZ DCT RGOOD EMZOH3

### Location

AT TOD

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Has this been resolved in the most recent build?

**Comment by MountainManB** [comment]
I believe so but the calculations for where T/D are off. Which I believe the team know about already. Waiting to confirm if it goes into PROF mode when hitting T/D on our next build.

**Comment by GenericNerd** [comment]
@MountainManB Glad to hear, we’re aware of the calculations with issue #88, which we’re actively working on!
