### ISSUE TITLE
[BUG] - AUX tank fuel transfer doesn't shut off by itself

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#1030]
### Describe the bug

AUX tank fuel transfer doesn't shut off by itself when fuel system is on auto. Shows AUX UPR PUMPS LO fault. Clears itself and overhead transfer pump state when cycling fuel system to manual and back to auto.

### Steps to reproduce

- Load aircraft with fuel in aux tanks
- Fly
- When aux tank nearly empty, fault appears
- Cycle fuel system to manual and back to clear fault and overhead aux tank pump remaining on.

### Expected behaviour

Aux transfer tanks turn off automatically without faults.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/6001596/ce562fc0-4f3a-464c-ab58-c2d5e443148d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL320

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.54+
