### ISSUE TITLE
[BUG] - COM1 not updating

### ISSUE THREAD

**Issue by Mike230296** [invernyx/md11-bugs#1031]
### Describe the bug

P3dV5 Comms Wont change in vatsim even tho changes in to comms in plane

### Steps to reproduce

did flight kmem-kind had atc on 125.8 changed it to freq in plane but didnt change in vpilot did have both p3d and vpilot as ran as admin

### Expected behaviour

changed freq changes in vpilot

### Evidence

![vatsim](https://github.com/invernyx/md11-bugs/assets/148866383/68becede-6fd0-4cb5-8053-2e1b39b53eea)

### Simulator

P3Dv5

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
have you tested this again, does it never work, did it work before.

**Comment by Mike230296** [comment]
tested again the sqark updates but not the comms

**Comment by turbofandude** [comment]
Resolved in 0.45+
