### ISSUE TITLE
[BUG] - P3Dv4 Missing Thunderstorm Lights and Dome Lights

### ISSUE THREAD

**Issue by Douglas-McCormick** [invernyx/md11-bugs#1033]
### Describe the bug

The thunderstorm lights and dome lights are not functioning in P3Dv4 platform

### Expected behaviour

Only the Flood lights and panel instrument lights in P3Dv4 is functioning. The thunderstorm lights, which was mentioned in 0.40 changelog, as still not functioning in P3Dv4

### Evidence

![2024-4-10_19-58-46-450](https://github.com/invernyx/md11-bugs/assets/104307400/483a8668-f24e-445f-a5b3-9df8f0ec3f1d)

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#400
