### ISSUE TITLE
[BUG] - Screen brightness knob to 0 briefly turns off other screens

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#1035]
### Describe the bug

Turning the brightness of 1 screen to 0 briefly turns all other screens off.

### Expected behaviour

Turning off a display does not impact ther displays.

### Evidence

https://youtu.be/H7ziTIKeF_w

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This is intentional behaviour as the DEU decides which screens need to go where, it takes some time to reallocate. The text and geometries being missing will need to be logged in a different bug.
