### ISSUE TITLE
Logo light on when switch is off

### ISSUE THREAD

**Issue by Mike230296** [invernyx/md11-bugs#1039]
### Describe the bug

Logo light on when switch is off

### Expected behaviour

Logo light to be off when swich is off

### Evidence

![2024-4-11_10-20-9-368](https://github.com/invernyx/md11-bugs/assets/148866383/55f352ef-084c-4e79-bc6b-ce509d64b7dd)
![2024-4-11_10-20-30-599](https://github.com/invernyx/md11-bugs/assets/148866383/49a2a684-78ae-4604-a718-e06a658a4452)

### Simulator

P3Dv5

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by MikeA34** [comment]
That isn't a logo light; it's a navigation light illuminating the rear of the aircraft

**Comment by MikeA34** [comment]
![Näyttökuva 2024-04-11 161117](https://github.com/invernyx/md11-bugs/assets/150369113/be209551-4946-4a53-a505-cbdb9508fc14)
This is how the logo light is in MSFS
