### ISSUE TITLE
[BUG] - T/C and T/D Keep Moving Around In FMS

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#104]
### Describe the bug

After completing a flight and loading another flight for a second leg the T/C and T/D kept moving around in the FMS and switching places.

### Steps to reproduce

Complete a flight taxi to gate shut off engines stay on ground power or apu power try loading another flight plan into FMS the T/C and T/D keep moving up and down in the flight plan. 

### Expected behaviour

To be able to load a flight plan after first flight for a second leg for another flight and not have the T/C and T/D move around in the LEGS page. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

KONT

### Arrival

KOAK

### Cruise level

13

### ZFW

337.3

### CG

20

### Fuel

30.7

### Cost index

20

### Route

First route was SNSHN5 COREZ DCT RGOOD EMZOH3 finished that flight then tried to load KOAK/30 CNDEL5 KAYEX DCT LOSHN DCT EHF ZIGGY7 KONT/26L. 

### Location

sitting at the UPS ramp at KOAK 

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This should be fixed. If it isn't, please refile and refer to this bug.
