### ISSUE TITLE
[BUG] - AA livery, issue with metallic door frames

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#1042]
### Describe the bug

On the American Airlines livery, the metallic door frames are covered by the livery.

### Expected behaviour

The metallic door frames should be entirely visible. At the moment only L3 & R3 doors are correct.
![n1757a-american-airlines-mcdonnell-douglas-md-11_PlanespottersNet_224254_9bfbfeaefa_o](https://github.com/invernyx/md11-bugs/assets/150369113/601c3cd7-e7b2-4491-90a2-c3a62ad88f85)

### Evidence

![Näyttökuva 2024-04-11 155739](https://github.com/invernyx/md11-bugs/assets/150369113/fc099b52-0eac-4219-a922-2ae4cdf996b1)
![Näyttökuva 2024-04-11 155718](https://github.com/invernyx/md11-bugs/assets/150369113/bfe71b3b-07dd-4290-9526-12732bf9385f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by ElMikey70** [comment]
Fixed!
