### ISSUE TITLE
[BUG] - In Multiplayer On Vatsim The Landing Gears Missing

### ISSUE THREAD

**Issue by bassplane** [invernyx/md11-bugs#1043]
### Describe the bug

When on Vatsim with a custom .vmr file, the landing gear of the MD-11 are not present for the other person.

### Expected behaviour

The gears should be present. To be clear, this is occurring for the other person flying along. So the one in the .vmr file, not for myself as the 1st person flying. In the attached image, I am flying the Kuro B788 and my buddy the TFDi MD-11.

### Evidence

![Screenshot 2024-04-11 131140](https://github.com/invernyx/md11-bugs/assets/150367558/53fa3be1-ea6c-4f53-b7a2-9c5578180efb)
![Screenshot 2024-04-11 133805](https://github.com/invernyx/md11-bugs/assets/150367558/04dd5616-9e49-421c-a3b2-2238ffd3e9a4)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is a problem of the model matching, not us
