### ISSUE TITLE
[BUG] - Analogue Standby Altimeter animation wrapping

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1048]
### Describe the bug

When wrapping from 999 to zero on the 1000ft hand, the animation wraps around backwards instead of staying at 0 and restarting. The same happens on all the drums within the unit (switch from 0 to 9 or 0 to 9, visible on the INHG drum)

### Expected behaviour

Smoothe transition without it reversing the needle.

### Evidence

https://github.com/invernyx/md11-bugs/assets/2170028/ea3e1574-6e76-413a-b98a-5e40d37de271

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by GR1MMly** [comment]
Believe this is a duplicate bug entry:
#798 
#938

**Comment by KJA1582** [comment]
And you'd be correct.
Different spellings and search do not get along.
