### ISSUE TITLE
[BUG] - CPT FLT DIR OFF doesn't work

### ISSUE THREAD

**Issue by JF1997** [invernyx/md11-bugs#1049]
### Describe the bug

Pressing the FLT DIR OFF button on the CPT side does not turn off the FD

### Expected behaviour

Similar to the FO side the FLT DIR OFF button would turn off the Flight Director, this does not happen on the CPT side.

Questioning it in general would turning only one FD off turn off the autopilot modes? This does not happen on the Airbus or Boeing so was surprised to see FMA modes removed on the FO side when I turned it off.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
are you sure you are up to date, this was fixed some time ago

**Comment by JF1997** [comment]
Yes, this was flying v0.41.0.1. Should be an easy check during a test flight.
