### ISSUE TITLE
[BUG] - IRS Not Aligning at Correct Position

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#105]
### Describe the bug

WHEN IRS IS ALIGNED ITS PUTTING ME MORE THAN 160NM AWAY FROM THE AIRPORT. NAVIGRAPH SHOWS ME AT THE AIRPORT 

### Steps to reproduce

ALIGN IRS AFTER A FLIGHT OR TWO AND IT ALIGNS YOU NOT IN THE CORRECT POSITION 

### Expected behaviour

TO ALIGN AT CORRECT POSITION 

### Evidence

![irs PROBLEM](https://github.com/invernyx/md11-bugs/assets/148557328/5aa92f31-1b75-4082-b7d4-66a0bfa7b6a0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by 017941** [comment]
Had the same thing. It is coming from the "work foler". The TFDI app remembers your last flight. I clear irt after each flight and the IRS no longer flash on startup.
C:\Users\jeffr\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalState\packages\tfdidesign-aircraft-md11\work

**Comment by GenericNerd** [comment]
Should be resolved
