### ISSUE TITLE
[BUG] - RA/DH Set Altitude Amber Box

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#1051]
### Describe the bug

RA/DH Set Altitude has an amber box around it on the ground - this should not be present.

### Expected behaviour

While the RA numbers should be amber, there should not be an amber box present around the RA/DH set numbers in the PFD.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/138527559/3113bb50-bb90-4c28-92b8-854a00741246)
the manual agrees

**Comment by turbofandude** [comment]
Resolved in 0.48+
