### ISSUE TITLE
[BUG] - ARPT Displays Too Many Airports

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#1052]
### Describe the bug

Selecting ARPT data on the ND displays airports with runways <5000ft

### Expected behaviour

ARPT should only display airports with 5000ft of stopping distance.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
