### ISSUE TITLE
[BUG] - CG out of Limits

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1053]
### Describe the bug

Upon rotation and gear retraction, CG OUT OF LIMIT appeared on the displays. CG was good on takeoff and was well within limits, 38.9 but the aircraft disagrees. Aircraft is flying as it should.

### Expected behaviour

If CG is out of limit, it would tell you, or not even let you put it into the MCDU.

### Evidence

https://imgur.com/a/F5toREB

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Daniz010** [comment]
Having the same issue. Hope this will be fixed!

**Comment by TheFightingRaven** [comment]
known issue, new cg loading will fix. Side not 38.9& TOWCG is well beyond the aft limit. The warning function correctly

**Comment by CptUnicorn** [comment]
> known issue, new cg loading will fix. Side not 38.9& TOWCG is well beyond the aft limit. The warning function correctly

So if 38.9 is beyond the aft limits, why would the aircraft fly normally or not give a warning when setting up the FMC?
