### ISSUE TITLE
[BUG] - Two fer! F/D lateral bar may not appear on multi-sector days. FO FD commanding nose down.

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1055]
### Describe the bug

First one the FD lateral command bar may no show up when doing a multi sector flights. I just took off form SDF and there is no lateral command bar. Second is the FO Vertical Command Bar showing a nose down command when the CPT side is showing normal level.

### Steps to reproduce

Fly one leg, then take off again in the same simulator session.

### Expected behaviour

Full Flight Director functionality.

### Evidence

![20240413180133_1](https://github.com/invernyx/md11-bugs/assets/150947401/2ccbd977-d0bc-4ad1-ae9c-2395c052adf9)
![20240413182840_1](https://github.com/invernyx/md11-bugs/assets/150947401/4361b1ad-6124-4523-885b-89705818bc47)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

N/A

### Bank

N/A

### Heading

N/A

### Altitude

N/A

### Departure

KSDF

### Arrival

KPHX

### Cruise level

N/A

### ZFW

457.0

### CG

38

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Are these repeatable? I did have issues with this at one point but I was under the impression that they resolved.

**Comment by turbofandude** [comment]
These should have long since been resolved
