### ISSUE TITLE
[BUG] - FMS Flight Complete Phase

### ISSUE THREAD

**Issue by MD-82** [invernyx/md11-bugs#1056]
### Describe the bug

Flight-Complete Phase not sequenced

### Steps to reproduce

After a flight and engine shutdown, the FMS keeps the route as is. Nothing happens. Even if completely de-powering the airplane.

### Expected behaviour

After landing and engine shut-down, the FMS should sequence the flight-complete phase and clear the active flight plan in
preparation for re-initializing. Some data fields then also revert to default data. Completely de-powering the airplane should have the same effect.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Post-flight

### Altitude

Airport Elevation

### Departure

TNCB

### Arrival

TNCA

### Cruise level

FL200

### ZFW

156.5 Tons

### CG

33%

### Fuel

10.9 Tons

### Cost index

50

### Route

TNCB/10 N0403F200 ARUB1R ELUMO DCT DAVLA DCT TNCA/11

### Location

TNCA Gate 2

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The FMS does not immediately reset upon power loss (it takes time). That said, the FMC reset occurs when accessing the INIT page after landing.

**Comment by MD-82** [comment]
No problem, this is what I got directly from the KLM FCOM 

"After landing and engine shutdown, the FMC goes through a flight-complete phase, clearing the active flight plan in preparation for re initializing. In addition, some of the data entry fields reinstalled to default data."
