### ISSUE TITLE
[BUG] - Pylon #1 & #3 pre cooler vents on left hand side should not be there 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1057]
### Describe the bug

Pylon #1 & #3 pre cooler vents on left hand side should not be there 

### Expected behaviour

To have vents only on the right hand side of both pylons

### Evidence

PW
![Schermopname (461)](https://github.com/invernyx/md11-bugs/assets/150957609/e1c43d3c-6522-4c9c-91f2-67fffb262967)
![ph-mcy-martinair-mcdonnell-douglas-md-11f_PlanespottersNet_103900_80af52aaee_o](https://github.com/invernyx/md11-bugs/assets/150957609/1a4787e6-95e6-4095-aa95-617fdecfa94c)
![0226728](https://github.com/invernyx/md11-bugs/assets/150957609/16df9ceb-55c2-4a6a-90e5-170d84cc8b10)

GE
![Schermopname (462)](https://github.com/invernyx/md11-bugs/assets/150957609/b51e2a06-c107-4f6c-8ac8-ffa08d0ea080)
![Schermopname (463)](https://github.com/invernyx/md11-bugs/assets/150957609/0cf07332-8243-44fe-9bfe-6a9fdbf8b349)
![63222_1561360132](https://github.com/invernyx/md11-bugs/assets/150957609/8726b317-87b8-467d-8cdc-ba2fca42ddca)
![1a0edafdb4296a87497af42272ce9eab](https://github.com/invernyx/md11-bugs/assets/150957609/691dbe66-7770-48cb-b351-bc668b55cd2b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Resolved
