### ISSUE TITLE
[BUG] - Missing flap handle and some other mechanical sounds

### ISSUE THREAD

**Issue by Leemazz** [invernyx/md11-bugs#1058]
### Is your feature request related to a problem? Please describe.

Sound suggestion for cockpit rattles on take-off and landing , also wind noise in flight . Missing flap handle sounds in cockpit and various other 

### Describe the solution you'd like

more immersion from sounds 

### Describe alternatives you've considered

no alternatives , hopefully this is planned 

### Additional context

Also click sounds quiet

**Comment by TheFightingRaven** [comment]
some of the missing sounds are known and planned for improvement. The rattle could be added possibly

**Comment by turbofandude** [comment]
Resolved in 0.59+
