### ISSUE TITLE
[BUG] - Hold exit text misaligned 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1059]
### Describe the bug

Hold exit text misaligned 

### Steps to reproduce

Enter a hold in the FMS 

### Expected behaviour

Be readable 

### Evidence

![Schermopname (466)](https://github.com/invernyx/md11-bugs/assets/150957609/bd2d15ef-473e-4851-ac09-2d2d6687af4e)
![Schermopname (464)](https://github.com/invernyx/md11-bugs/assets/150957609/c92c0d1e-4104-4c71-88e5-5d549c50f87d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

TNCA

### Arrival

TNCB

### Cruise level

FL120

### ZFW

61LB

### CG

34%

### Fuel

20000KG

### Cost index

80

### Route

TNCA DCT MEMRU RNV10 TNCB

### Location

MEMRU

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Although the FCOM's pictured layout is impossible given the width of the MCDU screen, obviously overlapping text is wrong. I've removed the "SPD" label when the EXIT AT is displayed
