### ISSUE TITLE
[BUG] - Windshield Wiper Knobs Flipped

### ISSUE THREAD

**Issue by AKSledhead** [invernyx/md11-bugs#106]
### Describe the bug

Windshield Wiper Knob Flipped

### Steps to reproduce

Right click on windshield wiper knob.

### Expected behaviour

Knob should be facing up (toward rear of aircraft) and it is facing down instead.

### Evidence

![tempsnip](https://github.com/invernyx/md11-bugs/assets/148526838/8b77bc4e-f66a-45cc-bc76-bc7d16cd716d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Since been fixed
