### ISSUE TITLE
[BUG] - A/C departs hold on it's own after one trip

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1063]
### Describe the bug

A/C departs hold on it's own after one trip 

### Steps to reproduce

Enter a hold and don't arm the exit, see plane depart the hold on it's own after one full patern 

### Expected behaviour

To stay in the hold 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

TNCA

### Arrival

TNCB

### Cruise level

FL200

### ZFW

61LB

### CG

34%

### Fuel

20000KG

### Cost index

80

### Route

TNCA ARUBA1N RNV10 TNCB

### Location

ELOTU hold 

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
can you specify which hold this happened at?

**Comment by turbofandude** [comment]
Resolved in 1.0.25+
