### ISSUE TITLE
[BUG] - Autobrake message on EAD is not accurated

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1065]
### Describe the bug

Autobrake message illuminate on the EAD as "Autobrake off" but it isn`t in the "off" position

### Steps to reproduce

When this message illuminate on the EAD and when I switch off the Autobrake, the message is duplicated and when I turn it to for example to RTO it only shows one in yellow message and 1 in blue message that says "Autobrake T.O"

### Expected behaviour

-

### Evidence

![Screenshot 2024-04-14 151308](https://github.com/invernyx/md11-bugs/assets/71586114/434c4802-aa91-4fe0-98e9-f34c92173157)
![Screenshot 2024-04-14 151305](https://github.com/invernyx/md11-bugs/assets/71586114/68f8b402-d8f4-47d9-b3b8-0f8fa9595db1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed with the warnings bug
