### ISSUE TITLE
[BUG] - Parking brake message illuminate on EAD in mid-flight

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1067]
### Describe the bug

Parking brake message bug (EAD)

### Steps to reproduce

The message 'parking brake on" is showing on the EAD in blue text when mid-air and the handle is in the off/release position. When trying to toggle the message by turning on and off the parking brake, the message is duplicating when teh parking brake is turned on, when turning off the parking brake it only shows once (blue)

### Expected behaviour

![Screenshot 2024-04-14 203300](https://github.com/invernyx/md11-bugs/assets/71586114/15bba6c0-2edf-4708-ad9b-e3d2c666df42)
![Screenshot 2024-04-14 203311](https://github.com/invernyx/md11-bugs/assets/71586114/805ef9f2-dfa3-43e1-93a1-2e76630939ed)

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

-

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed with the warnings bug
