### ISSUE TITLE
[BUG] - FCP Fuel Quantity Digits Cutoff

### ISSUE THREAD

**Issue by AKSledhead** [invernyx/md11-bugs#107]
### Describe the bug

The fuel quantity indications on the FCP are cutoff.

### Steps to reproduce

Look at FCP on overhead.

### Expected behaviour

Fuel quantity should be centered within the display.

### Evidence

![cap2](https://github.com/invernyx/md11-bugs/assets/148526838/8fe8fdfe-107c-4f20-bcd0-e6e48c6239d7)
![Capture](https://github.com/invernyx/md11-bugs/assets/148526838/afead4b9-0556-4c9b-b73d-88a23f188230)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Duplicate of #18
