### ISSUE TITLE
[BUG] -  Wind indicator on ND doesn`t dissapear underneath 100KTS

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1070]
### Describe the bug

The wind indicator is still on the ND when parked at the gate and is not removing from the ND during passing 100kts

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
