### ISSUE TITLE
Takeoff Warning System

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1073]
### Describe the bug

When conducting the takeoff warning system test prior to engine start, on advancing throttle lever #1, all the level Alerts on the EAD disappear and eventually the Bleeds All Off cyan message appears. On testing throttle lever #2 the same behaviour as before is not exhibited. The voice warnings are the same both times.

### Steps to reproduce

Prior to engine start, do a takeoff warning system test with throttle #1 advanced to full power and then idle and then throttle #2/3 to full power and idle and note the difference.

### Expected behaviour

I cannot find which is the correct behaviour but I'd expect that there would be no difference in the ALERT messages disappearing / the Cyan Bleeds All Off message appearing whether you were testing throttle lever #1 or throttle lever #2/3. I think the correct behaviour is that the ALERT messages remain and the aircraft doesn't turn off the bleeds but I may be mistaken.

### Evidence

![20240415115034_1](https://github.com/invernyx/md11-bugs/assets/152972533/3322cfd5-09d6-4551-a939-ff1850427a7d)
![20240415115040_1](https://github.com/invernyx/md11-bugs/assets/152972533/8ad25524-54cb-4643-be90-d153bc14bf8f)
![20240415115055_1](https://github.com/invernyx/md11-bugs/assets/152972533/b5ac5392-98bc-4870-8c66-dbff823e3c49)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.56+
