### ISSUE TITLE
Engines still running on Cold and Start default load

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1074]
### Describe the bug

When loading the aircraft from a cold and dark scenario engines 1 and 2 are still running (visually outside / audibly and showing engine oil pressure). There are no N1 / EGT or FF indications.

### Steps to reproduce

Load the aircraft into the sim with a cold and dark setting (from a previous load) and monitor the sound / engine instruments and the visual model and you should see that engine 1 + 2 are running. 

### Expected behaviour

That all engines should be off and the engine indications represent that along with the visual and sound models.

### Evidence

![20240416094527_1](https://github.com/invernyx/md11-bugs/assets/152972533/8af932dd-4a4d-4333-b9a7-0d5d8f85ea2b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
describe the steps better. Are you in sim with engine started, going to the menu, then loading cold and dark? or something else?

**Comment by omega892** [comment]
So having loaded the sim, I select an MD-11 and load it into a flight starting on the ground. Once loaded, the aircraft appears as can be seen in the picture. I have to select cold and dark from the EFB menu multiple times to be able to make the engines completely shut down.

**Comment by joon44** [comment]
I also get this occasionally. Usually it works after pressing esc and choosing restart and sometimes have to go back to world map and reload the whole flight for it to work.

**Comment by omega892** [comment]
So it keeps happening with Cold and Dark as the default load, but if I then load Ready to Fly and then load Cold and Dark, it then loads the Cold and Dark setup correctly

**Comment by TheFightingRaven** [comment]
Are you spawning on the runway? The sim forces the engines to run and overwrites our panel state. We're looking into how to bypass this behaviour. If you're spawning on a stand with cold and dark as the default state but are still have the engines running upon loadup please reopen the ticket with title "engines running on loading cold and dark on stand" The other issue is known and reported
