### ISSUE TITLE
[BUG] - Tail tank transfer

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1075]
### Describe the bug

Fuel in the tail tank should be transfered forward in decent

### Steps to reproduce

Start a decent with fuel in auto mode and fuel in the tail tank.

### Expected behaviour

When main tank quantities are at 11500 lbs, or the aircraft decends below 19750ft the fuel should be transfered forward, out of the tail tank.

### Evidence

![0IXY7ks](https://github.com/invernyx/md11-bugs/assets/95483637/ab7af4e8-4111-458b-b158-c1199cd26027)

![FlightSimulator_lBUqJUGm1n](https://github.com/invernyx/md11-bugs/assets/95483637/c7993019-115c-4c10-815f-b5ca6d3ff41b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

19750

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved as of 0.46+
