### ISSUE TITLE
[BUG] - Incorrect VOR/NDB data on ND

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1076]
### Describe the bug

VOR/NDB option shows all the ILS localizers on the ND

### Expected behaviour

Show only VOR/NDB beacons

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/52d26690-a1c5-46a5-8166-d93cafc590c9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+
