### ISSUE TITLE
[BUG] - Minimums Knob Turns but Does Not Change on PFD

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#108]
### Describe the bug

Turned the Minimums knobs from ra to baro and knobs turns but RA remains on the PFD.

### Steps to reproduce

Turn the minimums knob from ra to baro and on the pfd ra remains. 

### Expected behaviour

for the pfd to display baro when switched to baro and not stuck on RA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Departure

KONT

### Arrival

KOAK

### Cruise level

360

### ZFW

356.8

### CG

25

### Fuel

31.6

### Cost index

20

### Route

KONT SNSHN5 COREZ DCT RGOOD EMZOH3 KOAK

### Location

Flying 

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.13+
