### ISSUE TITLE
[SUGGESTION] - Add option that links altimeters together 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1081]
### Is your feature request related to a problem? Please describe.

Not really I'm to lazy to do it for both, on a serious note it's rather annoying to set it for both when I'm on vatsim for instance 

### Describe the solution you'd like

Option in the EFB that link them 

### Describe alternatives you've considered

-

### Additional context

-

**Comment by turbofandude** [comment]
Since implemented
