### ISSUE TITLE
[BUG] - Front landing gear floating

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1082]
### Describe the bug

Front landing gear floats above the field elevation

### Expected behaviour

![Screenshot 2024-04-18 212844](https://github.com/invernyx/md11-bugs/assets/71586114/ea7305e1-6074-42f5-bdf9-4a833d895d03)

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Resolved
