### ISSUE TITLE
[BUG] - STAB MODE Not in Amber mode or in the green on the ground with engines off

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1084]
### Describe the bug

According to the MD11 FCOM the STAB MODE should be in "Amber mode" or in the "greens" (also in the engine page). It s only in the white position during the flight and not on the ground

### Expected behaviour

![Screenshot 2024-04-18 225210](https://github.com/invernyx/md11-bugs/assets/71586114/c6fe4998-4dad-4877-aa85-5b34eda012ef)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1062
