### ISSUE TITLE
[SUGGESTION] - Click and drag bug manipulation

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1085]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Able to spin bugs/dials with click and hold and drag.  All other aircraft in MSFS that I've flown have this ability.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by TheFightingRaven** [comment]
click and drag will not be implemented but the interaction will be revised to be in line with the MSFS standard

**Comment by TheFightingRaven** [comment]
#825
