### ISSUE TITLE
[BUG] - Flight Controls feel heavy and sluggish

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#109]
### Describe the bug

On rotation and manual flight controls feels heavy and sluggish almost having to use full movement of controls

### Steps to reproduce

Take off and fly 

### Expected behaviour

Not to feel so heavy or needing a lot of control input. Almost had to pull full back on controls.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by 017941** [comment]
Same here. I am going to try and use the MSFS weight and balance. I guess Roanne put out a way to get you CG n order via that page instead of the FMC. Definitely have an extremely high AOA on takeoff and approach indicating we are either much heavier than we think or our CG is way, way aft.

**Comment by GenericNerd** [comment]
Is there any reference you have for how it is meant to feel and fly? Although I agree with you, it's also hard to judge from videos alone so we're trying to find the best reference we can for this.

**Comment by 017941** [comment]
This is no longer an issue. Somewhere after 7.0 the controls were no longer
sluggish .

**Comment by GenericNerd** [comment]
Thanks!
