### ISSUE TITLE
Altitudes on Flight Plan are way off leading to strange PROG page readings.

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1091]
### Describe the bug

The uplaoded altitudes on the flight plan are crazy high.

### Steps to reproduce

Load the flight plan and check the altitudes. Some are way off, and consequently the PROG page is unable to compute, leading to negative fuel and infinite miles. After clearing out the crazy altitudes the flight plan makes sense and the PROG works normally.

### Expected behaviour

Correct altitudes and accurate PROG page.

### Evidence

![Screenshot 2024-04-21 231014](https://github.com/invernyx/md11-bugs/assets/148719444/e753c515-7ecc-4806-893a-ae0b2ff09491)

![Screenshot 2024-04-21 231035](https://github.com/invernyx/md11-bugs/assets/148719444/1ffff910-31c0-4a85-9f26-7b6e0fb1093f)

![Screenshot 2024-04-21 195837](https://github.com/invernyx/md11-bugs/assets/148719444/5f834575-4ac0-43ba-9baf-f2c45a7820c9)

![Screenshot 2024-04-21 231929](https://github.com/invernyx/md11-bugs/assets/148719444/a2c46b29-fd9a-4e26-a421-3d064fbf254d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

39000

### Departure

kjfk

### Arrival

egll

### Cruise level

390

### ZFW

370.6

### CG

23.9

### Fuel

79.9

### Cost index

181

### Route

KJFK/22R N0484F350 DCT BETTE DCT ACK DCT TUSKY N177E ACADN N203B NICSO/M084F370 NATU BEXET/N0476F390 DCT ENJEX DCT AVZAC DCT INFEC DCT JETZI DCT AMFUL DCT OCTIZ/N0441F230 P2 SIRIC SIRI1H EGLL/09L

### Location

I noticed at cruise

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
symptom of the memory bug, no longer present
