### ISSUE TITLE
[BUG] - Flight Director overhaul

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1093]
### Describe the bug

F/D lateral guidance will always drive rapidly to the side of the PFD even with a small course change requiring a small bank. Autopilot does not follow this guidance leading the AP bank command and FD lateral guidance to mismatch even with the correct bank angle. This happens when beginning the turn and when ending the turn. FD pitch guidance will command large pitch changes with only a few knots speed difference. Both lateral and vertical guidances are too abrupt and incorrect. They point to the correct result but the overall behavior is wrong. Vertical guidance bar looks too shortas the black wings are spread too far out.

### Steps to reproduce

1) Monitor FD guidance during the flight. Pay attention to commanded bank angle enroute when the bank angle is smaller and turns are smoother. This is easiest to do with the AP controlling the plane with NAV or HDG mode.

2) Fly a climb/descend manually. Change pitch a little and hold it steady and let the speed bleed off or increase a little. With a few knot speed difference, try to follow the FD again. 

### Expected behaviour

1) FD lateral guidance to correspond with the autopilot commanded bank angle
2) Desensitize FD lateral guidance so that the lateral bar isnt always driven to the edge of the PFD when turning and also adjust the movement speed to slower. The bar should start moving slowly so that the pilot can smoothly follow the turn with slowly increasing bank and holding the FD bar nearly centered.
3) Desensitize FD pitch guidance to smoothly command corrections for the small difference between the actual and target speed. If the speed increases/decreases slowly, the corrective command doesnt need to be abrupt.
4) Move the black wings a bit closer to barely overlap the pitch digits.
5) Of this I am not entirely sure but the FD bars seem a bit thicker in the real plane. Same as the pitch and horizon lines.
### Evidence

AP/FD guidance mismatch. In this case, the AP is still following the track and turning but FD is already commanding to reduce the bank. Still need to turn 10 degrees to the right. AP is correctly banking almost at the bank angle limit and despite the plane already being L 0.1 of the track, FD is commanding to reduce the bank. If you turn off AP and follow the FD, it will lead even further left from the track. Important note that in this picture, FD has been in this position for a longer time already and the autopilot does NOT follow FD guidance. Hard to capture this in still image
![FlightSimulator_kfYxUyRXAT](https://github.com/invernyx/md11-bugs/assets/102414406/a8770d33-eb0e-4778-a12f-007a458451a2)

FD pitch command doing rapid changes with small difference between commanded and actual speed
First flying correctly
![image](https://github.com/invernyx/md11-bugs/assets/102414406/9549b421-da43-442e-a3fa-fdda98f2bddc)

Lower the nose a little to gain extra knots. FD increases immediately 5 degrees when basically 1-2 degrees nose up is enough to return to correct speed. If you then let the speed bleed off few knots below the target, FD does the same downwards commanding large pitch changes. 
![image](https://github.com/invernyx/md11-bugs/assets/102414406/a2f5de07-9631-4f0d-840e-d68e39281f11)

A good video showing a 90 degree turn done by hand. Notice the FD lateral guidance does not drive instantly to the edge of the PFD but slowly start commanding to the right and also the command to wings level is smooth. The pilot is able to hold FD centered all the time even with rolling against the bank angle limit. Also the FD commands wings level shortly before the correct track. This whole correct behavior is currently missing from TFDi.
https://www.youtube.com/watch?v=pCiO8qdc1rE&t=980s

Here another example. 20 degree turn to the right. Again a small smooth FD lateral command leading all the way to the bank angle limit and return to wings level command coming 5 degrees before the track.
https://www.youtube.com/watch?v=4AUMSymvsyw&t=2184s

Here we see the autopilot and FD working together with a 90 degree turn, FD nicely centered and perfectly synced throughout the whole turn
https://youtu.be/bzsGG-SPkVs?si=_LDmfZt1pnf7-Scw&t=5310

The black wings should barely overlap the pitch digit numbers. 
Real
![image](https://github.com/invernyx/md11-bugs/assets/102414406/04748497-c0e8-41b5-9e47-05d9bd028211)

TFDi
![image](https://github.com/invernyx/md11-bugs/assets/102414406/395abe1f-b022-491a-b6ac-26e27a0f7de9)

Comparison
![image](https://github.com/invernyx/md11-bugs/assets/102414406/3fffd69f-8e83-4894-9907-87c60b8016ec)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

RKSI

### Arrival

VHHH

### Cruise level

FL320

### ZFW

204tn

### CG

28%

### Fuel

41tn

### Cost index

200

### Route

BOPTA2A BOPTA Z51 BEDES Y711 MUGUS Y742 SALMI Q11 DRAKE A1 ELATO V522 ABBEY ABBEY3A

### Location

BEDES

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.61+
