### ISSUE TITLE
[BUG] - Barberpoles visually incorrect and misaligned 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1095]
### Describe the bug

Barberpoles visually incorrect and misaligned 

### Expected behaviour

Barberpoles should look like this minus the horizontal stripe for the stall speed 

![Schermopname (474)](https://github.com/invernyx/md11-bugs/assets/150957609/cde888b1-bd87-43f4-bb73-2bb8dd714c9d)

![Schermopname (477)](https://github.com/invernyx/md11-bugs/assets/150957609/dbd30b12-9850-4bc2-806d-548b2b82b36d)

![image](https://github.com/invernyx/md11-bugs/assets/150957609/703ef57a-ec08-4067-ab88-6e1f0c540eea)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
![image](https://github.com/invernyx/md11-bugs/assets/3858710/7002bad9-71ff-4ead-8c87-aa3a091c8fe0)
