### ISSUE TITLE
[BUG] - Barberpoles only appear when gear is up during take off

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1096]
### Describe the bug

Barberpoles only appear when gear is up during take off

### Expected behaviour

To appear on it's own after around 40ft RA 

### Evidence

https://youtu.be/3wzS6fn8BA8?si=VQZvaQjKKf8fB5TW&t=3047

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
