### ISSUE TITLE
[BUG] - Fuel turning off 

### ISSUE THREAD

**Issue by Mike230296** [invernyx/md11-bugs#1097]
### Describe the bug

Fuel randomly turning off shows has fuel but will just randomly turn off and no i dont have things rigged to mixter / prop axis

### Steps to reproduce

in cruise or desent it will just randomly do it shutting down all engine all i was doing was a flight from ksea - ellx

### Expected behaviour

engines not turning off due to fuel shutting down 

### Simulator

P3Dv5

### Crash

No

### Phase of flight

Descent

### Altitude

15000

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
We need steps to reproduce, if you can find them, even if it's just a flight it commonly happens on, please open a new issue.
