### ISSUE TITLE
[BUG] - Major performance issues (fps)

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1099]
### Describe the bug

The MD11 is currently performing very badly. It wasnt this bad before. I cant tell what has changed.

### Steps to reproduce

Monitor the fps during the flight

### Expected behaviour

Perform much better

My PC is as follows: AMD 5800x3D CPU, 32gb DDR4 @ 3200MHz, Zotac 3080 10GB GPU, Windows 11 and SU14. I am running the sim at 4K resolution. During the testing there is no spad.next, volanta or any other external application running that would be connected to the sim. Only Discord besides the sim has been running at the same time.

I have been doing multiple tests now with lots of mods and with empty community folder. Other mods dont seem to affect the performance as the values are same with and without mods. Mostly I've done the tests at MXI Design Doha OTHH, BMSim Miami KMIA and Aerosoft Tel Aviv LLBG. I have tested the MD11 against the default Asobo/WT B747, freeware FBW A32NX and also the PMDG 737-600.

I have also tested at default OTHH and KMIA and in various randomly chosen default airports around the globe to rule out the scenery causing issues.

I have noticed that there is a clear 20% performance lose against the 747 and A32NX and a general 25-35% and in some cases even up to 50% against the 737.

Perormance as such is unacceptable 

### Evidence

First I will post all my graphic settings here. Changing them makes no effect on the MD-11. Anisotropic Filtering is set to OFF from MSFS and 16x from Nvidia Control Panel. Otherwise at NCP I have default settings.
![image](https://github.com/invernyx/md11-bugs/assets/102414406/b8c1815f-83a5-4ace-b53f-b2f02b3e4cf0)
![image](https://github.com/invernyx/md11-bugs/assets/102414406/41a0abef-2e44-4498-af56-626231033798)

The biggest fps difference is seen here at LLBG rwy 12. PMDG being 68fps and TFDi 46fps. That is nearly 50% better fps achieved in the PMDG
![FlightSimulator_uZsYqa00eE](https://github.com/invernyx/md11-bugs/assets/102414406/d6edbe5e-a4c3-43a4-9b03-cf64c997dc70)
![FlightSimulator_RbgZgGxGks](https://github.com/invernyx/md11-bugs/assets/102414406/3ba1c935-acd9-4377-84c6-dff6acf41ee1)

At KMIA here the PMDG runs at 46fps and the TFDi at 35fps being 31% better for PMDG. The default 747 (in a different time of day) achieved 47fps
![zdi5CbZoj8](https://github.com/invernyx/md11-bugs/assets/102414406/f3856006-357b-42fb-90f7-79bd12209ffd)
![FlightSimulator_rVzmEFgoQv](https://github.com/invernyx/md11-bugs/assets/102414406/718e6d4a-c64e-49a8-b594-fda34ad25407)
![FlightSimulator_s0bSe97ver](https://github.com/invernyx/md11-bugs/assets/102414406/ec2c48d2-b7d9-43d5-ba6d-d1761d4d5395)

At OTHH TFDi runs at 43fps, 747 51fps, A32NX 54fps and the PMDG at 65fps
![FlightSimulator_7w9ht0KPgK](https://github.com/invernyx/md11-bugs/assets/102414406/95bc293a-1def-468e-8d19-8c16d65bea17)
![FlightSimulator_dzoNGB2He0](https://github.com/invernyx/md11-bugs/assets/102414406/a9896cc7-745a-4895-b966-5e1fa92993a9)
![FlightSimulator_HvAL9lWLhi](https://github.com/invernyx/md11-bugs/assets/102414406/2a5ae07e-8b8b-42ed-ace2-fe61289e72fe)
![FlightSimulator_DRitK01Ywh](https://github.com/invernyx/md11-bugs/assets/102414406/793a2624-e884-4370-96a2-18602644aeb9)

Same can be seen in the outside views also. These tests were done in clear weather and no AI/Vatsim traffic or basically anything happening around. With these added and other varying conditions, the fps in the MD11 drops to 20-25 and the CPU seems to be choking under the load. With the initial performance in light conditions being so much worse, any extra burden on the sim will totally kill it and its not sustainable performance anymore.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
From your own feedback on the Discord, it seems like this has mostly gone away with the new build

**Comment by joon44** [comment]
> From your own feedback on the Discord, it seems like this has mostly gone away with the new build

I agree. Major performance increase with 0.44. Very well done, thank you ❤️
