### ISSUE TITLE
[TODO] - FMS/MCDU Pages

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#11]
### Describe the bug

Missing FMS/MCDU Pages

### Expected behaviour

- [x] THRUST LIMITS
- [x] CLIMB
- [x] DESCENT
- [x] NAV RADIO
- [x] ACARS
- [ ] DESCENT FORECAST
- [ ] CLIMB FORECAST

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Added in 0.45+
