### ISSUE TITLE
[BUG] - Reference points circle too big 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1100]
### Describe the bug

Reference points circle too big 

### Expected behaviour

To be smaller 

### Evidence

![Schermopname (482)](https://github.com/invernyx/md11-bugs/assets/150957609/77b52b47-8c9f-4a07-b0ea-717f21662b9a)
![Schermopname (485)](https://github.com/invernyx/md11-bugs/assets/150957609/5a7806ce-f39e-4bae-a874-11d4f6ec3611)
![Schermopname (480)](https://github.com/invernyx/md11-bugs/assets/150957609/a0275ad7-1068-491c-b753-3b637a8fc229)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+
