### ISSUE TITLE
[BUG] - Tuned VOR symbol - Circle missing and not in cyan/magenta 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1103]
### Describe the bug

Tuned VOR symbol - Circle missing and not in cyan/magenta 

### Expected behaviour

To have the circle and have the symbol in the right color including the text in cyan

### Evidence

![Schermopname (482)](https://github.com/invernyx/md11-bugs/assets/150957609/24516df4-c89d-434f-abac-d1f34cac41d6)

![Schermopname (489)](https://github.com/invernyx/md11-bugs/assets/150957609/c04ff898-fab8-4b7e-88ae-00682982d51c)

![Schermopname (488)](https://github.com/invernyx/md11-bugs/assets/150957609/dfcab6f9-277f-441f-ab23-062c4b02ac24)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
I reported this earlier with a different source saying the tuned VORs are white. They seem to have multiple options then?

**Comment by fugotaro** [comment]
My best guess is that manually tuned VOR's have a white ring around them instead of a magenta one for the auto ones but nothing except this screenshot seems to back it up

![Schermopname (498)](https://github.com/invernyx/md11-bugs/assets/150957609/fc4885c8-f198-488a-8e36-c28f5835fe47)

**Comment by turbofandude** [comment]
Resolved in 0.63+
