### ISSUE TITLE
[BUG] - Glareshield texture not level

### ISSUE THREAD

**Issue by SunKing135** [invernyx/md11-bugs#1104]
### Describe the bug

Texture on glareshield not level as that paints get distorted 

### Expected behaviour

While using a new repaint with painted glareshield me and the artist noticed that the glareshield on the MD-11 F/CF is not level, although it appears so, which goes to the extent that a painted glareshield is distorted. Hence the screenshot sent.
![MD-11CF](https://github.com/invernyx/md11-bugs/assets/152623434/9face1e4-18c1-491d-859d-4939f1b2aed5)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
I cannot reproduce this issue on my end. It seems like you are using 3d projection mapping for texturing this surface, which may produce oddities. Please familiarize yourself with the UV.
![image](https://github.com/invernyx/md11-bugs/assets/48654776/f7c0691a-236c-44d2-88d7-e3822f10fd08)

**Comment by alxcpt** [comment]
I am the artist who found this. The proably easiest way for you to reproduce is to compare the UV of the left side nose affected on the passenger version with the cargo version. I have attached a comparison using the newest available model for me (0.44.0.1) imported into blender, showing a discrepancy on the UVs for cargo and passenger version. You can even see it on the screenshot you attached. The gap between the main fuselage and the nose part is smaller on the left side than on the right side. 

Here are the steps I used to run into this. (I obviously don't know if the nose part on the freighter is made like this intentionally, the rest of the UV/textures for both pax and freighter are quite consistent, so it's a bit weird, the nose isn't)
1. Apply a texture to the left side glareshield nose according to the UV. 
2. Apply the same texture (same location/dimension) on one of the freighter textures ( F or BCF). (kind of ignoring the freighter UV here)
3. Save the textures for both, and create a seperate livery for pax and freighter. Voila!

![327913588-f7c0691a-236c-44d2-88d7-e3822f10fd081](https://github.com/invernyx/md11-bugs/assets/150608109/628bccce-9da7-481e-95c2-459f1b7e256b)
![TFDi MD-11 Nose discrepancy](https://github.com/invernyx/md11-bugs/assets/150608109/11dbff8a-9906-450b-80d2-a4786dd4ca52)
![TFDi MD-11 Nose discrepancy UV](https://github.com/invernyx/md11-bugs/assets/150608109/172bf5d2-fdab-451f-9435-10fb062ba4d6)

**Comment by arwasairl** [comment]
I've checked the Tu value of the top island and it is indeed offset by a couple of millimeters. This has been reversed.

**Comment by arwasairl** [comment]
Upon further inspection, it appears that this may have been intentional. Our current liveries and substance painter project had this Tu offset, and thus by reverting it to the PAX layout, it will cause current liveries for the F variant to be offset.

For now, I will keep the offset Tu value, and to resolve this, just use the UV layout from the F model. This does mean that textures from PAX cannot be used with F.

**Comment by alxcpt** [comment]
Thank you for looking into this. The idea behind this report, was to make the pax and cargo UV consistent. It's probably easier to fix it now, as your artist hasn't done a huge amount of liveries even affected by this offset and community liveries are rare as well. If you don't intent to adjust it, I for myself can live with it, it's just a small shift and no distorsion or so. (I can add it to my quirky painting area list on the MD-11)
