### ISSUE TITLE
[BUG] - Dashed V1 Vr box missing before speeds are entered 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1105]
### Describe the bug

Dashed V1 Vr box missing before speeds are entered 

### Expected behaviour

To also have the white box for V1 and Vr 

### Evidence

![Schermopname (486)](https://github.com/invernyx/md11-bugs/assets/150957609/b25c583c-5443-4fa7-8a95-d6afafe07349)
![Schermopname (487)](https://github.com/invernyx/md11-bugs/assets/150957609/2c72d9ec-5275-4886-a07c-7f73a58678ac)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
