### ISSUE TITLE
[SUGGESTION] - There should be a clickspot for Go around mode

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1106]
### Is your feature request related to a problem? Please describe.

There should be an easy clickspot for go around mode in the cockpit VC to prevent having the click the (potentially moving) button on the physical throttles or setup a bind.

### Describe the solution you'd like

A popular choice is to put it on a screw on an unused part of the MCP/GCP

### Describe alternatives you've considered

N/A

### Additional context

N/A

This ticket was created on request from Triple7guy in the discord.

**Comment by TheFightingRaven** [comment]
@jhattermann I'd suggest the screw in the lower left corner of the FCP for the clickspot

**Comment by jhattermann** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/105667840/0a2d2912-898f-4601-8f74-1658ae880668)

This screw directly above the master warning light has been given a clickspot linked to the GA button
