### ISSUE TITLE
[BUG] - EMER PWR light

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1107]
### Describe the bug

When moving the EMER PWR selector from OFF to ARM the EMER POWER ON light does not illuminate for 30 seconds. When moving the EMER PWR selector from ON to ARM the ON light should extinguishes.

### Steps to reproduce

- Power the aircraft.
- Check SMOKE ELEC/AIR is in NORM.
- Move EMER PWR selector.

### Expected behaviour

- When moving the EMER PWR selector from OFF to ARM the EMER POWER ON light should illuminate for 30 seconds.
- When moving the EMER PWR selector from ON to ARM the EMER POWER ON light should extinguishes.

### Evidence

Correct procedure:

![EMER PWR ON](https://github.com/invernyx/md11-bugs/assets/153389460/80869850-4239-4d89-905a-be74c926a181)

Current bug:

https://github.com/invernyx/md11-bugs/assets/153389460/7f227d49-9110-47a6-bb75-d4f5950d5a42

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Duplicate
