### ISSUE TITLE
[SUGGESTION] - The default mode should be rounded gauges, not tape

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1108]
### Is your feature request related to a problem? Please describe.

The default mode should be rounded gauges, not tape.

### Describe the solution you'd like

Make tape gauges disabled by default.

### Describe alternatives you've considered

Not doing this

### Additional context

The rounded gauges are the vastly more popular option and this could lead to confusion with new users.

**Comment by TheFightingRaven** [comment]
already done, will not be effective backwards into old liveries
