### ISSUE TITLE
[SUGGESTION] - Ability to interrupt opening/closing of doors

### ISSUE THREAD

**Issue by crazyforiphone** [invernyx/md11-bugs#1109]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

When a door is opening clicking the opening text should close it, and when it is closing clicking the closing text should open it. This will prevent delays in the event of a misclick.

### Describe alternatives you've considered

n/a

### Additional context

Most other addons include this feature.

**Comment by turbofandude** [comment]
Resolved as of 0.48+
