### ISSUE TITLE
[BUG] - Anti-ICE Syustem Manual light does not move with button

### ISSUE THREAD

**Issue by crazyforiphone** [invernyx/md11-bugs#1110]
### Describe the bug

when pressing the button, the Manual text stays in place

### Expected behaviour

Mnaual text should move with the button

### Evidence

https://youtu.be/uT6PN0TT5zw

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1034
