### ISSUE TITLE
[BUG] - ASU ties to wheel chocks

### ISSUE THREAD

**Issue by crazyforiphone** [invernyx/md11-bugs#1111]
### Describe the bug

When enabling wheel chocks, ASU should not automatically connect, when enabling the ASU, it should show

### Steps to reproduce

Enable wheel chocks in EFB

### Expected behaviour

ASU should only connect when selected in EFB

### Evidence

https://youtu.be/wnzmIpqMqCs

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Resolved
