### ISSUE TITLE
[BUG] - Beacon reflection "weak" + shown inside

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1114]
### Describe the bug

Beacon reflection looks a bit weird on the airframe. Like the reflection is partly missing.  It is also shown inside the plane.

### Expected behaviour

1) I would expect to see wider and more shiny reflection like in this video here https://www.youtube.com/watch?v=FVMKCUbpZ7c Notice the beacon reflecting on large areas on the airfplane surfaces

2) Beacon shown only outside the plane

### Evidence

The "reflection" looks just like a red small area around the beacon. Looks like a red ball instead of the light reflecting off the plane
![FlightSimulator_8iZhmrziwr](https://github.com/invernyx/md11-bugs/assets/102414406/feee2dc9-2a00-4731-a812-7f7f5aaf67d0)

Beacon is also shown inside the plane, where the reflection is bigger and looks much better
![FlightSimulator_WSc7X2Tmge](https://github.com/invernyx/md11-bugs/assets/102414406/8cc23446-2683-478b-ab73-92dcc016b1f6)

The same is seen below the plane. Here the reflection looks a bit better than above the plane
![FlightSimulator_31VF0F5cfQ](https://github.com/invernyx/md11-bugs/assets/102414406/265a9604-ad87-40a0-a960-376b65ead314)
![FlightSimulator_eaNXzVCGxe](https://github.com/invernyx/md11-bugs/assets/102414406/c0cb7d00-c3b5-482f-bf8e-11f6b96fbf50)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by Mets747** [comment]
Definitely needs to be fixed

**Comment by arwasairl** [comment]
This has been fixed in a previous version.
