### ISSUE TITLE
[BUG] - VORDME's shown as DME's 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1115]
### Describe the bug

VORDME's shown as DME's 

### Expected behaviour

To have the VORTAC symbol instead of the DME one for the VORDME's 

### Evidence

![Schermopname (499)](https://github.com/invernyx/md11-bugs/assets/150957609/f8c42d20-b267-4285-8f27-376b410c4f37)

![Schermopname (500)](https://github.com/invernyx/md11-bugs/assets/150957609/a2a2357f-c8b7-48aa-966a-fdfd21a8ff7f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.11+
