### ISSUE TITLE
[BUG] - Heading BUG displaying on PFD while in NAV mode 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1117]
### Describe the bug

Heading BUG displaying on PFD while in NAV mode 

### Expected behaviour

To not show while in NAV 

### Evidence

![Schermopname (503)](https://github.com/invernyx/md11-bugs/assets/150957609/966625f5-5dcd-42d1-b9b3-13aaa7b2de88)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
