### ISSUE TITLE
[BUG] - ELEC panel - ARM lights should illuminate

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1118]
### Describe the bug

In normal operations, GEN 1, 2 & 3 ARM lights, AC TIE 1, 2, & 3 ARM lights will illuminate

### Steps to reproduce

-

### Expected behaviour

![1](https://github.com/invernyx/md11-bugs/assets/153389460/615a0594-9314-483d-bac9-8e59859dc662)

![2](https://github.com/invernyx/md11-bugs/assets/153389460/b42195a4-adfd-4bd7-a68d-689f61e3e0ed)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

ground

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
UV error on the ARM light mesh, now fixed

**Comment by Dimples82** [comment]
the GEN 1/2/3 ARM still not illuminate.
