### ISSUE TITLE
[BUG] - values cutting off

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#112]
### Describe the bug

values on the autopilot and fuel panel are being cut off

### Steps to reproduce

always

### Expected behaviour

not to do this

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/77b8cd67-ac7d-4d3f-9904-2edc7efba2cc)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/d9bf5f86-4fca-4724-8f32-87866c7abd82)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Duplicate of #18
