### ISSUE TITLE
[BUG] - CAWS std all altitude callouts off & should not be able to turn off 50 to 10ft callouts

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1120]
### Describe the bug

CAWS std all altitude callouts off & should not be able to turn off 50 to 10ft callouts 

### Steps to reproduce

Land the plane 

### Expected behaviour

To hear the 50 to 10ft callouts atleast as they came standard 

### Evidence

![Schermopname (512)](https://github.com/invernyx/md11-bugs/assets/150957609/e35885c7-a49d-4684-a1e0-ac1768862106)
![Schermopname (511)](https://github.com/invernyx/md11-bugs/assets/150957609/23d92c2b-b6ca-4efc-92e0-608795e915e5)
![Schermopname (510)](https://github.com/invernyx/md11-bugs/assets/150957609/f3b52ba6-98a5-42ce-88d8-b5e2452fc0a1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
We do not see an issue in giving the user more choice in this scenario

**Comment by fugotaro** [comment]
Where did I say that? 

Said that by default they're all off which is annoying especially when you haven't noticed it yet until landing when you don't hear anything and the 50 to 10ft callout was non removable as the images say

**Comment by turbofandude** [comment]
We have reference that directly contradicts the statement that the 50-10 callouts were not-removable. It does seem like they are on by default, however. There is nothing in the code that indicates they should all be off by default, though I will double check again.
