### ISSUE TITLE
V-speed callouts 

### ISSUE THREAD

**Issue by espn74** [invernyx/md11-bugs#1122]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It would be nice to have callouts on take-off. 

### Describe alternatives you've considered

None

### Additional context

None

**Comment by slowreload** [comment]
Second this

**Comment by Dimples82** [comment]
IMO, if that is not an real life aircraft feature, no thanks.

**Comment by joon44** [comment]
It could be an option in the efb

**Comment by espn74** [comment]
> IMO, if that is not an real life aircraft feature, no thanks.

In the absence of a FO, is it more realistic to have a captain taking his eyes of the runway?

I think it is better to improve the experience for single pilot flights.

**Comment by TheFightingRaven** [comment]
already planned

**Comment by GenericNerd** [comment]
Duplicate of #598
