### ISSUE TITLE
[BUG] - Wheels animating in the opposite direction 

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1123]
### Describe the bug

-

### Expected behaviour

Looks like the front landinggear wheel (idk about the rears one) they animation in the wrong direction

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Same with the left main gear.

**Comment by arwasairl** [comment]
This has already been reported: https://github.com/invernyx/md11-bugs/issues/746
