### ISSUE TITLE
[BUG] - TAS Display on ND

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#1124]
### Describe the bug

TAS on the top left of the ND shouldnt be displayed until 100 kts

### Expected behaviour

TAS and wind vector on the top left of the ND shouldnt be displayed until 100 kts and should not display below 100 kts.

### Evidence

https://www.youtube.com/watch?v=jKKkOHAYiQI

Watch from 6:15.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next version

**Comment by AllanBurek** [comment]
TAS still displays below 100 kias

**Comment by turbofandude** [comment]
Resolved in 0.48+
