### ISSUE TITLE
TO FLEX doesn't show up on engine display 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1125]
### Describe the bug

See above 

### Expected behaviour

Show TO FLEX when flex is entered 

### Evidence

![FlightSimulator 2024-04-27 20-39-21](https://github.com/invernyx/md11-bugs/assets/70169249/1f977bd0-5c28-4e4f-9b8f-ff71d21ca77e)
![Screenshot_20240427_223903_Drive](https://github.com/invernyx/md11-bugs/assets/70169249/69401b9c-1f59-4a62-a513-039f3b5abf7d)
![Screenshot_20240427_225430_Drive](https://github.com/invernyx/md11-bugs/assets/70169249/4f874d53-0413-4bce-95b4-55b7b70c1ecd)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.48+
