### ISSUE TITLE
Weird split texture on display

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1126]
### Describe the bug

Weird line on glass

### Expected behaviour

No line 

### Evidence

![FlightSimulator 2024-04-27 21-20-36](https://github.com/invernyx/md11-bugs/assets/70169249/81a1abde-0e6c-4d82-a176-645499280ef5)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Are you on the latest version? I am and I cannot see the same split line you see
