### ISSUE TITLE
[BUG] - TOC circle in cyan instead of magenta 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1127]
### Describe the bug

TOC circle in cyan instead of magenta 

### Expected behaviour

To have the circle in magenta 

### Evidence

![Schermopname (513)](https://github.com/invernyx/md11-bugs/assets/150957609/f8c0a3c0-6f37-4874-aaad-a3039559ee2a)
![Schermopname (482)](https://github.com/invernyx/md11-bugs/assets/150957609/8ae5a9d5-6e17-4c55-a34f-6708eed1f700)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Fixed in the next version
