### ISSUE TITLE
[BUG] - Left Wing - Missing Navigation Light Protection

### ISSUE THREAD

**Issue by timv217** [invernyx/md11-bugs#1128]
### Describe the bug

The external clear glass/plastic whatever it is is missing from the left hand wing - red nav light.

### Expected behaviour

Expect to see some covering like the right hand wing light. It looks like something is there but more like a ghost effect my end. 

*please note the colours are off as I have an HDR monitor

### Evidence

![Microsoft Flight Simulator 28_04_2024 19_08_01](https://github.com/invernyx/md11-bugs/assets/33424163/598c590e-987c-4adf-8434-f45a09c53fa4)
![right hand nav light](https://github.com/invernyx/md11-bugs/assets/33424163/dcd3df97-e98c-4f61-acca-36729d6914d2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
It is there, however the material's settings dont reflect enough of it. Regardless, this has already been fixed.
