### ISSUE TITLE
[BUG] - Fuel fill arm light not illuminating 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1130]
### Describe the bug

Fuel fill arm light not illuminating 

### Expected behaviour

To illuminate blue when holding the annunciator test switch or when the fill valve is armed 

### Evidence

![Schermopname (515)](https://github.com/invernyx/md11-bugs/assets/150957609/f25365d5-1a0e-466f-a05f-f0b5e26299a0)
![Schermopname (517)](https://github.com/invernyx/md11-bugs/assets/150957609/56693f41-d3fb-4342-8b30-7bee22fb012d)
![Schermopname (518)](https://github.com/invernyx/md11-bugs/assets/150957609/c14dd056-b953-451d-bf0f-221944c6b6ce)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
I'm not quite sure if I understand. I see the fill being illuminated on your screenshot. Is this not what you mean?

**Comment by joon44** [comment]
> I'm not quite sure if I understand. I see the fill being illuminated on your screenshot. Is this not what you mean?

The arm above fill doesnt illuminate. The switch has 2 lights.

**Comment by GenericNerd** [comment]
Oh I see!

**Comment by arwasairl** [comment]
@jhattermann Very tags are present, if they are, most likely a code issue.

**Comment by TheFightingRaven** [comment]
fixed in .50
