### ISSUE TITLE
[BUG] - Level arrow for climb and descent not showing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1131]
### Describe the bug

Level arrow for climb and descent not showing 

### Expected behaviour

To have the blue arrow pop up when the FCP altitude coincides with the predicted FMS climb or descent profile 

### Evidence

![Schermopname (521)](https://github.com/invernyx/md11-bugs/assets/150957609/8b769a1d-d1b3-4479-ad41-fc317c669e6d)
![Schermopname (519)](https://github.com/invernyx/md11-bugs/assets/150957609/2b6406f9-2de2-43ce-9ae7-fa99faa345e7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.47+
