### ISSUE TITLE
[BUG] - FGS/OVHD PNL FLOOD knob should make FCP displays & fuel displays brown/yellowish 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1132]
### Describe the bug

FGS/OVHD PNL FLOOD knob should make FCP displays & fuel displays brown/yellowish 

### Expected behaviour

To have the displays becoming brown/yellowish when you move FGS/OVHD PNL FLOOD knob

### Evidence
![43553_800](https://github.com/invernyx/md11-bugs/assets/150957609/9f1c89d6-c969-4409-8e16-8430f4a1d605)

![25062694344_30eeb0569b_b](https://github.com/invernyx/md11-bugs/assets/150957609/9cf890da-ffc6-421f-9dd7-c9362ab36aaf)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.46+
