### ISSUE TITLE
On PW Engines, the Start Valve light does not illuminate

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1137]
### Describe the bug

On PW Engines, the Start Valve light does not illuminate

### Expected behaviour

The start valve light should illuminate when pulled and extinguish when the rpm reaches 45% and the start valve closes.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This may be a visual issue but on my current build, it works as expected
