### ISSUE TITLE
PW engines surge back and forth during all phases of flight.

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1138]
### Describe the bug

PW engines surge back and forth during all phases of flight.

### Steps to reproduce

Monitor surging engines from crusie to lnding and watch them surge.

### Expected behaviour

relatively steady power settings during all phases of flight.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed in next version
