### ISSUE TITLE
[BUG] - EVAC control panel - evacuation signal switch is in the OFF position.

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1139]
### Describe the bug

Even though the EVAC control panel is not simulated, the evacuation signal switch should be in the ARM position.

### Steps to reproduce

-

### Expected behaviour

The evacuation signal switch should be in the ARM position.

### Evidence

![Screenshot 2024-05-01 132217](https://github.com/invernyx/md11-bugs/assets/153389460/000f37d8-ee69-4ebb-8b46-83d0c0c5bfe4)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#718
