### ISSUE TITLE
[BUG] - APU can not be started while engines are running.

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#114]
### Describe the bug

Apu can not be started after engines are running

### Steps to reproduce

Start engines and try and start the apu. APU will not start with the engines running. 

### Expected behaviour

To be able to start the apu while engines are running. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Post-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
While on a flight, I could start the APU and it remained available. Can you provide further information?

**Comment by MountainManB** [comment]
Yeah after I landed and was taxing off the runway to the gates i tried to start apu and it wouldnt turn on.

**Comment by GenericNerd** [comment]
We're seeking further clarification from pilots and engineers of the aircraft (as you are aware :P)

**Comment by bassplane** [comment]
To add to this for help:
Please see the video from 737NG Driver: https://www.youtube.com/watch?v=gatWKu27gB0
At 1:36:53, while taxiing in, he switches on the APU. At 1:44:19 he discovers that the APU isn't running and has to start it again.

Exactly the same has also happened today (NOV 10th) on LondonController's stream upon landing/taxi-in at Kai Tak.
