### ISSUE TITLE
[SUGGESTION] - EVAC control panel - implement the EVAC control panel.

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1140]
### Is your feature request related to a problem? Please describe.

The evacuation signal switch is not simulated.
Several Normal Operations Procedures require to ARM the evacuation signal switch during cockpit preparation and set to OFF during securing phase.

### Describe the solution you'd like

**Implement a togglable evacuation signal switch (OFF/ARM/ON)**
Selecting ON the evacuation signal switch should: 
- Flash the EVAC light.
- Sound the evacuation horn.

**Implement the Evacuation Horn Shutoff Switch**
Evacuation warning horn may be silenced by pulling switch out from panel. 
EVAC lights continue to flash.

### Describe alternatives you've considered

It would be a amazing and distinctive feature if after commanding the evacuation:
- All doors opened;
- The inflatable evacuation slides were deployed.

### Additional context

-

**Comment by TheFightingRaven** [comment]
#718
