### ISSUE TITLE
[BUG] - Unable to Load F-Pln

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1141]
### Describe the bug

Not sure if it has been fully implanted, but the 'Send Flight Plan To FMC' button in the EFB doesn't work, or I am missing something. The FMC says 'UNABLE TO LOAD F-PLN'

### Steps to reproduce

Using the SimBrief import feature, import a flight plan.

### Expected behaviour

To have the flight plan import

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Departure

EHAM

### Arrival

KLAX

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

BERGI2Z BERGI M90 LONAM L7 TIMUP DCT OSLEL DCT ADASI DCT LUSEN/M083F320 DCT RUMUX DCT EPENI DCT LODNO/M083F340 DCT AGUMI DCT 6555N/N0481F340 DCT DUTUM DCT ARVEE/N0472F360 DCT RONPU DCT 5890N DCT KIROD DCT LEATS DCT GORAK DCT CHMNY/N0484F380 DCT COLMN DCT NORDK DCT GDGET DCT FANLO DCT OTOOL ANJLL4

### Location

EHAM Stand E24

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed in next version
