### ISSUE TITLE
[BUG] - EFB may cause a total simulator freeze if brought back out from the "flight bag"

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1142]
### Describe the bug

Upon landing in LAX, I clicked the hotspot to open up the EFB and a few seconds later, the entire simulator froze and didn't recover.

### Expected behaviour

Not have a total sim freeze.

### Evidence

Not sure if this is related, but it's from the Event Viewer around the time of the crash.

Faulting application name: couatl64_MSFS.exe, version: 4.8.0.5381, time stamp: 0x65de2a30
Faulting module name: ntdll.dll, version: 10.0.19041.4239, time stamp: 0xad5435e9
Exception code: 0xc0000374
Fault offset: 0x00000000000ff349
Faulting process id: 0xacc84
Faulting application start time: 0x01da9c46a7ec6a47
Faulting application path: C:\Program Files (x86)\Addon Manager\couatl64\couatl64_MSFS.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: d40bd05c-61b1-44b4-ab03-765f8ab820d8
Faulting package full name: 
Faulting package-relative application ID: 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by joon44** [comment]
The event viewer is just showing that GSX crashed at the same time because the sim crashed.

**Comment by TheFightingRaven** [comment]
used this hundreds of times haven't been able to reproduce. Likely a coincidence unfortunately

**Comment by CptUnicorn** [comment]
> used this hundreds of times haven't been able to reproduce. Likely a coincidence unfortunately

I think it very well may be. Though I have had CTDs with other aircraft where GSX isn't even active.
