### ISSUE TITLE
[BUG] - EFB does not save brightness setting.

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1143]
### Describe the bug

Even if you click save, the brightness does not save.

### Expected behaviour

To not get flashbanged when opening the EFB at night.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
@GenericNerd can we make this happen?

**Comment by GenericNerd** [comment]
This will be fixed through the initial state load (as if the EFB is booting up for the first time and using auto-brightness to adjust to the current conditions).
The screen (only on first load) will automatically be at the highest brightness during the day, the darkest during the night, and in-between during dusk and dawn.
