### ISSUE TITLE
[BUG] - ATS override

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1144]
### Describe the bug

My physical throttle axis overrides the ATS in normal modes. This happened when the sim was loaded with the "last state" panel state. I noticed on descend that I can control the thrust even I was not on clamp mode. Moving the physical throttle levers on my Honeycomb Bravo moved the thrust to match with the Bravo and ATS then moved them back to the ATS commanded thrust. This worked all the way until landing. It was the first time it has ever happened. On the next flight, when I restarted the sim and loaded with the cold and dark panel state, the issue didnt happen anymore so I suspect it might be due to the panel state.

### Steps to reproduce

1) Load the plane in the last state flight
2) Do a normal flight
3) Observe if you are able to override the ATS

Attached is a json file saved through the MCDU by Raven's request.
[THROTTLEOVERRIDE.json](https://github.com/invernyx/md11-bugs/files/15186953/THROTTLEOVERRIDE.json)

### Expected behaviour

Allow thrust control only in clamp mode

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Departure

LOWI

### Arrival

LFMN

### Cruise level

FL350

### ZFW

181tn

### CG

28

### Fuel

18000kg

### Cost index

69

### Route

LOWI/08 BRENO2J BRENO M726 NAXAV/N0475F350 DCT LUSIL DCT EVANO DCT ENOBA Z185 BORDI BORDI7R LFMN/04R

### Location

I guess it was shortly before BORDI

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Is this still happening with recent versions?

**Comment by joon44** [comment]
> Is this still happening with recent versions?

I will test tomorrow with the last state panel state.

**Comment by joon44** [comment]
I was not able to reproduce this. I'll try to test one more time and then close the issue if it doesnt happen. I suspect it was related to the panel state.

**Comment by joon44** [comment]
I could not reproduce this anymore.

**Comment by joon44** [comment]
I could not reproduce this.
