### ISSUE TITLE
[BUG] - FUEL SYSTEM - XFEED DISAG light doesn´t illuminate

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1145]
### Describe the bug

DISAG light should illuminate momentarily as valve transitions to on or off.

### Steps to reproduce

- Select MANUAL operation of the fuel system.
- Push each XFEED switch.

### Expected behaviour

FCOM
NORMAL OPERATIONS

![1](https://github.com/invernyx/md11-bugs/assets/153389460/29a72c54-d5be-47f5-8c60-91ce3ec6c7de)

### Evidence

https://github.com/invernyx/md11-bugs/assets/153389460/6f29decd-5f37-4d18-86b6-735503ea3a4a

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.47+
