### ISSUE TITLE
[BUG] - DAF static in C&D state

### ISSUE THREAD

**Issue by Swagger897** [invernyx/md11-bugs#1147]
### Describe the bug

When loaded in the C&D panel state, scrolling the DAF thumbwheel has no effect on the indication.

### Expected behaviour

Scrolling the thumbwheel should result in a corresponding change to the flap indication. The system is mechanical and requires no power.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.47+
