### ISSUE TITLE
[SUGGESTION] - Tail design

### ISSUE THREAD

**Issue by SunKing135** [invernyx/md11-bugs#1148]
### Is your feature request related to a problem? Please describe.

Your in house liveries for Lufthansa,  Sabena and Citybird have some issues with the tail engine. These aircraft, as the ER, had a different tail engine inlet design, which was implemented with KLM PH-KCE. The bulge was extended to follow the forward most banjo frame. It is obvious,  that at this stage it is very difficult to implement it straight away, but many liveries would not be authentic, since this very clear visual difference is visible.

Looking at Lufthansa Cargo, one feature from LH went amiss. The last two letters of the registration, in this case CM are painted on the tail as well.

Lufthansa Cargo
MSFS
![fsscr008](https://github.com/invernyx/md11-bugs/assets/152623434/65de3870-1d1e-49df-a9fd-58916e2be05a)

Real aircraft
https://www.flugzeug-bild.de/bild/flughaefen~deutschland~frankfurt-am-main-fra/73140/lufthansa-cargo-d-alcm-mcdonnell-douglas-md-11.html

Citybird
MSFS 
![fsscr003](https://github.com/invernyx/md11-bugs/assets/152623434/5c77e867-8e35-49a1-9514-cbf5cf51bf1a)

Real aircraft:
https://www.airliners.net/photo/CityBird/McDonnell-Douglas-MD-11/214638/L?qsp=eJwtjDEKAkEMRe%2BSWgsRLLbTC6yFF4jJRxdXZ0gCOix7d%2BNg93gP3kJSXoFPXFoFDeRgkzttqLLx02lY6IH2LqbJNJatxDWrF4tTS6McOIqgBvTvR1PYL8Glj2453iXAzp1pf0ivk9eZ%2BwPB00zr%2BgVHuS6/

Sabena
MSFS
![fsscr006](https://github.com/invernyx/md11-bugs/assets/152623434/da67ed1f-aaa2-4b8c-ad64-2f42291c1fe1)

Real aircraft
https://www.airliners.net/photo/Finnair/McDonnell-Douglas-MD-11/322584/L?qsp=eJwtjEEKwkAMRe%2BStS5EcNGdXqAuvEBIPrVYnSEJ6FB6d%2BPg7vEevJWkvAKfuLUKGsjBJnfaUWXjp9Ow0gPtXUyTaSx7CcnqxeLS0igHziKoAf370RT2S3DpoynHhwTYtTMdT%2Bl19rpwfyB4XmjbvkgTLsA%3D

As you can see with this examples, the engine number two bulge is different from the early one, as depicted with your model and it should be very noticeable. 

As this feature is also a feature from the ER, it can be checked with all ER ever built, they all feature this modified bulge as it is more aerodynamic.

ER tail 
https://www.airliners.net/photo/Philippine-Airlines-World-Airways/McDonnell-Douglas-MD-11-ER/18240/L?qsp=eJwtjbsOwjAMRX8FeYahIDFkZEd0YGG0YqupKCSyLZWo6r/jPrb70rkTxPw1/tmzFoYAyigxwREKCn4UwgRvrmMWcg13OjXNgcV7zWK36hmhcZuy5U6wJKaXE/b%2BIeTbAKhxJXbLw3mRLO3mLle31GsZcIWxYT/APP8BUEoyDA%3D%3D

This are the sources:

1. https://airlinercafe.com/aviation-articles/ultimate-dc-10-md-11-guide-178410/
2. https://www.flightglobal.com/more-md-11-improvements-revealed/15878.article

### Describe the solution you'd like

Please implement the modified bulge with a later post-release Service Pack 1 at a later date, as this feature is very obvious. 

### Describe alternatives you've considered

Alternatively, the promoted ER is not an ER, but much more a so called PIP (Performance Improvement Package) and should be named that way.

### Additional context

Feel free to contact me for more information. I have gotten this confirmed from the official Boeing page via social media contact and former Lufthansa Technik employees.

**Comment by SunKing135** [comment]
I edited two images to show what I mean on OO-CTB 

MSFS
![20240502_223645](https://github.com/invernyx/md11-bugs/assets/152623434/987bc991-3329-4565-93cb-c0dff1481b27)

Real aircraft 
![Screenshot_20240502_223230_Chrome](https://github.com/invernyx/md11-bugs/assets/152623434/cce60550-c3ca-4c65-bcd9-af73c75ad015)

**Comment by arwasairl** [comment]
These modifications require extensive changes to the model which also requires another set of textures to be created. While we won't fix this for the time being, it may be revisited in the future. But this fix is currently not planned.
