### ISSUE TITLE
[BUG] - Number 1 engine thrust reverser animation PW (MD-ENG-8)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1149]
### Describe the bug

When activating reverse thrust, there is no animation of the #1 TR (PW engines).  Engine 2 and 3 show correctly.

### Steps to reproduce

With engines running, engage reverse thrust

### Expected behaviour

TR animation shows correctly with TR deployed

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Resolved
