### ISSUE TITLE
[BUG] - APU Start Timing (MD-APU-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#115]
### Describe the bug

Using APU START/STOP button on ground at 2k ft altitude, APU start and APU GEN AVAIL in 25 seconds

### Steps to reproduce

On ground
OAT 59F
2k ft altitude (07MT Glasgow)
BAT ON
Ground PWR ON
Push APU START/STOP button
Begin stop watch
End stop watch when APU GEN AVAIL illuminates

### Expected behaviour

Should take between 45 and 60 seconds for APU to reach 95% N2 and APU GEN AVAIL illuminates.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
The APU start timing has been updated to take longer to start in the next build

**Comment by FreakyD777** [comment]
Not fixed in V0.37.  Now only takes 5 seconds for APU GEN AVAIL light to illuminate and N2 speed to reach 100%

**Comment by Dimples82** [comment]
Not fixed in V0.40
