### ISSUE TITLE
[BUG] - FCP displays don't show 8s during ANNUN LT TEST

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1151]
### Describe the bug

FCP displays don't show 8s during ANNUN LT TEST

### Expected behaviour

To show 8's, IAS, MACH, HDG, TRK FT, M, V/S +,- in the FCP displays during ANNUN LT TEST 

### Evidence

![Schermopname (523)](https://github.com/invernyx/md11-bugs/assets/150957609/67205a5e-2faf-4af1-9339-fbb46fb83ddb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
