### ISSUE TITLE
[BUG] - Fuel page 'FUEL' header missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1152]
### Describe the bug

Fuel page 'FUEL' header missing 

### Expected behaviour

To show FUEL on the top 

### Evidence

![Schermopname (524)](https://github.com/invernyx/md11-bugs/assets/150957609/e11ee0cb-73b3-4059-9ef9-c23ce2ef33dd)
![Schermopname (525)](https://github.com/invernyx/md11-bugs/assets/150957609/b6cdc981-adef-4753-ba37-b3bccb3c50a1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
