### ISSUE TITLE
[BUG] - Wind direction arrow point filled in instead of striped

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1153]
### Describe the bug

Wind direction arrow point filled in instead of striped

### Expected behaviour

To have an arrow consisting of three stripes 

### Evidence

![Schermopname (527)](https://github.com/invernyx/md11-bugs/assets/150957609/66493675-637f-4179-8bc1-700ba4213204)
![Schermopname (528)](https://github.com/invernyx/md11-bugs/assets/150957609/f7b2ddc7-9678-4be0-85a7-4b81bf0a8f0f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
