### ISSUE TITLE
[BUG] - FUEL SYSTEM - FUEL PUMPS  Switch "OFF" light doesn´t reflect the status of boost pumps (ON vs OFF)

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1154]
### Describe the bug

FUEL PUMPS  Switch "OFF" light doesn´t reflect the status of boost pumps (ON vs OFF)

### Steps to reproduce

Case 1 - Using EXT PWR
- Connect EXT PWR.

Case 2 - Using APU PWR
- Set BAT switch ON;
- Start APU PWR.

### Expected behaviour

Case 1
After pressing the EXT PWR switch, the aircraft will be AC powered.
All AC fuel boost pumps will be off (up to APU/ENGINE start).
All FUEL PUMPS  Switch "OFF" light should agree with the status of boost pumps and the "OFF" should be illuminate.

Case 2
After setting BAT switch ON, all FUEL PUMPS  Switch "OFF" lights should remain NOT illuminated, inspire of all AC fuel boost pumps are off.
When APU PWR is available, the aircraft will be AC powered.
Tank 2 AC fuel boost pump will start, while Tank 1/3 will remain OFF.
All FUEL PUMPS  Switch "OFF" light should agree with the status of boost pumps.

### Evidence

Case 1BUG

https://github.com/invernyx/md11-bugs/assets/153389460/0cf08ed1-d02f-4913-bc9c-72393d4ec5d8

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.47+
