### ISSUE TITLE
[BUG] - FUEL SYSTEM - wrong tank 2 AFT mounted boost pump fueling the APU

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1155]
### Describe the bug

The SD FUEL Synoptic shows the wrong tank 2 AFT mounted boost pump fueling the APU

### Steps to reproduce

- On ground;
- Power the aircraft with the APU;
- Wait until AC power is available.

### Expected behaviour

When APU is running and AC power is available, the SD FUEL Synoptic should show like this:
![AFT fuel pump 2 fueling APU](https://github.com/invernyx/md11-bugs/assets/153389460/cdbb3503-7354-479b-b7c1-32e2659f22a1)

(notice: left side fuel pump ON)

instead of this:

![Screenshot 2024-05-03 121056](https://github.com/invernyx/md11-bugs/assets/153389460/14f61768-b179-43d3-8906-c284b85fbf1c)

(notice: right side fuel pump ON)

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
