### ISSUE TITLE
[BUG] - Radio frequency panels don't show 8s during ANNUN LT TEST 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1156]
### Describe the bug

Radio frequency panels don't show 8s during ANNUN LT TEST 

### Expected behaviour

To show 8s during ANNUN LT TEST 

### Evidence

![Schermopname (523)](https://github.com/invernyx/md11-bugs/assets/150957609/dc40e895-e508-490b-8fe8-cf728b8257f8)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
