### ISSUE TITLE
[BUG] - MCDUs - DSPY, FAIL, MSG and OFST lights not on during ANNUN LT TEST 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1157]
### Describe the bug

MCDUs - DSPY, FAIL, MSG and OFST lights not on during ANNUN LT TEST 

### Expected behaviour

To have those bits of text on during the annun lt test 

### Evidence

![Schermopname (523)](https://github.com/invernyx/md11-bugs/assets/150957609/b03542c4-221d-46c8-bb82-e0db86b2f506)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
