### ISSUE TITLE
[BUG] - Marker beacons not displaying on PFD 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1158]
### Describe the bug

Marker beacons not displaying on PFD 

### Expected behaviour

To display on the PFD when passing over marker beacons, for instance EBBR RWY25R 

### Evidence

![Schermopname (530)](https://github.com/invernyx/md11-bugs/assets/150957609/7765fe5c-24c2-44b1-8181-a1ae16e3ff73)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next version
