### ISSUE TITLE
[BUG] - Glideslope slash missing

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1159]
### Describe the bug

Glideslope slash missing

### Expected behaviour

To have a cyan or amber slash for the third circle 

Also to me the circle seems a bit on the thick side as the inside is rather small comparing it to the irl screenshot 

### Evidence

![Schermopname (531)](https://github.com/invernyx/md11-bugs/assets/150957609/07d89476-27ed-4d7d-9328-dea213b14fd5)
![Schermopname (486)](https://github.com/invernyx/md11-bugs/assets/150957609/5c23c3ec-a54c-4cd4-aa55-5a407ae3aa42)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
