### ISSUE TITLE
[BUG] - APU ON & APU PWR AVAIL cyan messages not posting (MD-APU-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#116]
### Describe the bug

APU running after using APU START/STOP button, no APU ON or APU PWR AVAIL cyan messages posted

### Steps to reproduce

On ground
Push APU START/STOP button
Allow APU to reach 100% N2

### Expected behaviour

Once 100% N2 is achieved, APU ON and APU PWR AVAIL cyan messages should be posted.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.25+
