### ISSUE TITLE
[BUG] - Backlighting of AC Panel not working

### ISSUE THREAD

**Issue by firefighter1990** [invernyx/md11-bugs#1161]
### Describe the bug

Backlight of Airconditioning Panel not working

### Expected behaviour

When turning on Backlight for the Overhead Panel, every Panel should illuminate.

### Evidence

![FlightSimulator_40d8llcghG](https://github.com/invernyx/md11-bugs/assets/75794827/f3c187a5-e903-4820-a182-b5d0a1652717)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#553
