### ISSUE TITLE
[BUG] - TCAS displays missing on PFD 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1162]
### Describe the bug

TCAS displays missing on PFD 

### Expected behaviour

To have TCAS display messages on the PFD 

### Evidence

![Schermopname (534)](https://github.com/invernyx/md11-bugs/assets/150957609/5766d59b-b79a-41ec-a8fa-f074fb68eb9f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+

**Comment by turbofandude** [comment]
Resolved in 0.47+
