### ISSUE TITLE
[BUG] - V/S tape present/red cross missing on PFD when IRS's are off 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1163]
### Describe the bug

V/S tape present/red cross missing on PFD when IRS's are off 

### Expected behaviour

To have V/S tape blanked out and have a red cross in front of it. 

The V/S bar should reappear when IRS's are fully aligned 

### Evidence

https://youtu.be/rjf9sMh-GDY?si=wzpjobXV44xh7EG4&t=205
![ph-kcd-klm-royal-dutch-airlines-mcdonnell-douglas-md-11_PlanespottersNet_346056_e9248d3399_o](https://github.com/invernyx/md11-bugs/assets/150957609/97b62d85-b8db-4c64-ba69-6b58d51afa4f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
