### ISSUE TITLE
[BUG] - TCAS test passes while IRS's are off 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1164]
### Describe the bug

TCAS test passes while IRS's are off 

### Steps to reproduce

Push the tcas test button 

### Expected behaviour

To have it fail because none of the IRS's are aligned 

### Evidence

https://youtu.be/rjf9sMh-GDY?si=Bim-jChSwAGJdfat&t=700

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+

**Comment by turbofandude** [comment]
Resolved in 0.47+
