### ISSUE TITLE
[BUG] - ANNUN LT TEST missing messages/crosses for PFD and ND 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1166]
### Describe the bug

ANNUN LT TEST missing messages/crosses for PFD and ND 

### Expected behaviour

To show more that what we have now 

### Evidence

![Schermopname (538)](https://github.com/invernyx/md11-bugs/assets/150957609/af19b6f4-0afc-4fd6-b808-d58336b68b6b)
![Schermopname (539)](https://github.com/invernyx/md11-bugs/assets/150957609/3a3dc03c-aeb7-4cb2-a1d1-f7100bcaeb89)
![Schermopname (536)](https://github.com/invernyx/md11-bugs/assets/150957609/8e901f0d-006c-4ceb-b813-c397e8053066)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
