### ISSUE TITLE
[BUG] - Analouge guage has no balance ball

### ISSUE THREAD

**Issue by lscott122** [invernyx/md11-bugs#1167]
### Describe the bug

 Analouge guage has no balance ball

### Expected behaviour

There should be a ball indicating slip in the turn

### Evidence

![fjUC7fH](https://github.com/invernyx/md11-bugs/assets/41208924/a1bd9669-60fe-48c2-826c-55a9aa9674c7)
![cae_airside_LegendaryMD11_1200x675](https://github.com/invernyx/md11-bugs/assets/41208924/0b9ee885-cd4b-4e08-93a4-e5866ad40da8)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
@jhattermann The tag for this is MD11_MIP_STBY_AI_SLIP_RNG

**Comment by jhattermann** [comment]
Fixed this--It was there, it just blended in with the occlusion geometry behind it
