### ISSUE TITLE
[BUG] - MISC page yellow boxes

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1168]
### Describe the bug

The yellow boxes surrounding cargo door texts are way too big

### Expected behaviour

1) Boxes correct size
2) Boxes stay on the left column

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/87d49c68-5373-4f95-9a03-38626bef7b0f)
![image](https://github.com/invernyx/md11-bugs/assets/102414406/13b3ecab-9c92-47d2-929d-19ec315f7382)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
