### ISSUE TITLE
[BUG] - ANNUN LT test displays ENG + secondary ENG

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1169]
### Describe the bug

When ANNUN LT is pressed, ENG page is missing amber Xs over the thrust limit and fuel flows. Secondary ENG display is missing amber Xs over the oil press, temp and qty dials.

### Expected behaviour

Show all amber Xs correctly

### Evidence

![FlightSimulator_LneT71OL9R](https://github.com/invernyx/md11-bugs/assets/102414406/08c7916c-0ab8-4a90-8abd-7972e66711bc)
![image](https://github.com/invernyx/md11-bugs/assets/102414406/cef4fc04-0497-45ff-ab14-ac6089ab3c37)

I checked if fuel flow Xs are shown with fuel flow shown. Are not.
![image](https://github.com/invernyx/md11-bugs/assets/102414406/b4508f5a-5dc6-4f37-9bfc-b9d1adbc14cc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.45+
