### ISSUE TITLE
[BUG] - deflected ailerons reverses animation and deflects too little

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#1170]
### Describe the bug

With the deflected ailerons enabled the outboard aileron reverses it's animation and the deflection is too small

### Steps to reproduce

enable the deflected ailerons option in the mcdu
while on the ground set flaps to the dial a flap range
move yoke, observe the outboard ailerons moving mirrored to the rest of the roll control surfaces on the wing
observe neutral yoke deflection is very small

### Expected behaviour

with the option enabled the deflection direction shouldn't change and the neutral yoke deflection should be consistent with the real plane

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/d9963567-fd77-413f-b1c2-49f599de14e9)

### Simulator

P3Dv4, P3Dv5, P3Dv6, Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

n/a

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
