### ISSUE TITLE
[BUG] - Solid heading bug missing on the ground 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1172]
### Describe the bug

Solid heading bug missing on the ground

### Expected behaviour

To have a solid heading bug on the ND and PFD after allignment of the IRS's with the bug following the direction of the AC during taxi 

The open heading bug should be for the selected heading on the FCP, if there's no heading selected on the FCP no open heading bug should display and the heading line should stay with the solid heading bug following the AC on the ground 

### Evidence

https://youtu.be/bzsGG-SPkVs?si=b1Oikxd31S7CUeA3&t=2440
https://youtu.be/jKKkOHAYiQI?si=0kfMXU0eIewhdyqr&t=124

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
line should always be dashed (hard to make out in the above videos) but present on the ground

**Comment by turbofandude** [comment]
Resolved in 0.48+

**Comment by fugotaro** [comment]
Solid heading bug doesn't stay with AC position on the ground
