### ISSUE TITLE
[BUG] - A/T Surging While Maintaining Altitude

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#1173]
### Describe the bug

During intermediate level-off in climb phase, autothrottles surge between max and idle to maintain airspeed.

### Steps to reproduce

A/P and A/T engaged during KONT-RAJEE4 SID. There is an intermediate level-off at 7000ft.
To maintain 250kts and 7000ft, throttles surged between max and idle.

### Expected behaviour

A/T should make smaller adjustments

### Evidence

https://github.com/invernyx/md11-bugs/assets/123108304/6e3f8526-c2de-40f9-b1f7-92dcd8cde06f

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

7000

### Departure

KONT

### Arrival

--

### Cruise level

070

### ZFW

332.7

### CG

24.3

### Fuel

78.0

### Cost index

60

### Route

RAJEE4 MTBAL....

### Location

7000ft on RAJEE4 SID from KONT

### Agreement

- [X] Yes

**Comment by JeffRichard1958** [comment]
Were you using the PW engines? If so, then there is already a GITHUB and they are aware.

**Comment by GR1MMly** [comment]
> Were you using the PW engines? If so, then there is already a GITHUB and they are aware.

Yes, I clearly didnt search well enough. Thanks!
