### ISSUE TITLE
[BUG] - P3D5.4  I collapsed on loading

### ISSUE THREAD

**Issue by ZZZXR200** [invernyx/md11-bugs#1174]
### Describe the bug

I am using p3d v5.4 and I crashed after loading

### Steps to reproduce

Normal loading TFDI MD11

### Expected behaviour

Fixed and I want fly md11

### Evidence

[TFDI MD11 CRASH VIDEO.zip](https://github.com/invernyx/md11-bugs/files/15285329/TFDI.MD11.CRASH.VIDEO.zip)

### Simulator

P3Dv5

### Crash

Yes

### Agreement

- [X] Yes

**Comment by Douglas-McCormick** [comment]
How did you fix it？Mine is still CTDing at the very beginning of the scenario loading.
