### ISSUE TITLE
[BUG] - Takeoff Perf calc

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#1178]
### Describe the bug

multiple bugs seen in the takeoff perf page

### Steps to reproduce

spawn at RCTP use runway 05R get a 9% slope (obviously incorrectly), can't override the runway after fetching it. when pressing "get tow" got 141k kgs instead of the 210k kgs loaded, observed multiple impossible combinations of Vspeeds.
Runway length should be able to be overridden to be longer than database, database sometimes ignores displaced threshold that can be used for takeoff

### Expected behaviour

runway is overwritable, distance is overwritable to increase, fetch correct TOW, have correct vspeeds have correct runway slope

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/e8c2623a-c235-4d62-a51d-39fc9ab7943f)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/c470a9bd-ce60-48c0-ba2a-b2f7ea4ded3e)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/fdc07a55-5ede-4b2a-bc90-66b1d0bc72d5)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/4d6d617a-918a-471f-be06-bba5ea1f3627)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/bfa37ce4-b521-4b42-8042-1df8a38403df)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/87b67497-9774-476e-8263-227104fb654b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
slope and TOW are since fixed

**Comment by turbofandude** [comment]
0.62+ should resolve the remaining issues
