### ISSUE TITLE
[BUG] - HYD Pressure Transient Timing (MD-HYD-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#118]
### Describe the bug

When energizing and de-energizing a HYD system, the pressure reaches 3000 and 0 psi too quickly (~3 sec)

### Steps to reproduce

On Ground
Ground PWR ON
AUX PUMP 1 ON
Start timer
AUX PUMP 1 OFF
Start timer

### Expected behaviour

S/B approimately 5 to 7 seconds to energize, and 15-20 seconds to de-energize (when not inputting any flight control inputs)  NOTE: When inputting flight control inputs, time to de-energize decreases to <10 seconds

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This has been partially implemented. The time to energise and de-energise has been changed to reflect what you've sent through. The system is not yet affected by the flight control surfaces moving.

**Comment by FreakyD777** [comment]
verified less FC inputs

**Comment by GenericNerd** [comment]
This will be fixed in the next version
