### ISSUE TITLE
[BUG] - with AIR auto engine 2 and 3 won't spool up

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#1180]
### Describe the bug

when starting engines 3-1-2 as prescribed air system fails to accomodate enough pressure to start engine

### Steps to reproduce

set apu air on and air auto try to start engine 3 observe max n2 of 3% (when starting engine 1 and similar duct pressure it starts fine)

### Expected behaviour

all engines being able to be started in any order without air system problems

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved in 0.47+
