### ISSUE TITLE
[BUG] - no step when next alt it optimum

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#1181]
### Describe the bug

no step climb was inserted when next alt was the optimum alt

### Steps to reproduce

fly below listed route with FL340/FL350/FL360 entered in FPLAN init when opt alt was FL350 no step occured

### Expected behaviour

a step being inserted in the FPLAN at the weight where this is expected to happen

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/cb7d79f0-ac4d-450e-9e7a-21c3aacdfc6e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL340

### Departure

rctp

### Arrival

wmsa

### Cruise level

FL340/FL350/FL360

### ZFW

170k kgs

### CG

30%

### Fuel

27k kgs

### Cost index

108

### Route

RCTP/05R DCT TP240 DCT SUMER DCT CHALI T3 AJENT T5 PARPA
A577 KABAM N892 MIGUG N892 MONBO N892 MESOX Q15 CRA W2 PTH L642 CN
M765 BITOD M765 IGARI R208 VKR Y346 PULIP DCT VB22A DCT VB15A DCT
VB11A DCT VBA05 DCT VBA DCT CE DCT FI15 DCT WMSA/33

### Location

MESOX waypoint

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
