### ISSUE TITLE
[BUG] - turn arc ballooning full circle

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#1182]
### Describe the bug

the green turn prediction arc balloons to full circle at FL340

### Expected behaviour

it to stay an arc

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/d118eaa8-e9a2-4b77-a0c9-55bf53ff52dc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
