### ISSUE TITLE
[BUG] - SD Secondary Engine Display wrong values (GE engine)

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1185]
### Describe the bug

OIL PRESS and OIL QTY values are off normal operations values

### Steps to reproduce

- Start the Engines
- Let the engine parameters stabilize
- Check engine parameters

### Expected behaviour

OIL PRESS Display: Normal ranges are 10 to 120 psi for GE.
OIL QTY Display: Minimum before engine start: 14 qts. Maximum after engine start: 20 qts.

### Evidence

![Screenshot 2024-05-15 125634](https://github.com/invernyx/md11-bugs/assets/153389460/4c87455b-e69a-44a3-aa0f-dd6c06053688)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
already fixed, you seem to be on an outdated version
