### ISSUE TITLE
Texture mismapping/missing on fuselage

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#1186]
### Describe the bug

Some texture are mismapped/missing on fuselage

### Expected behaviour

Nose texture should be flipped
Miss aligned textures on left side fuselage (this wasn't present on pre 0.39 release) shouldn't be present (example of a KLM Farewell livery included)
Air condition intakes should appear less black (more gradient from white to black)
To show the textures glitches I have applied a green-black stripe pattern to the right side, a red-black stripe pattern to the left side

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150608109/e66518cf-7da1-4094-852c-89f6f6cabfed)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/e94bc092-8662-43fd-803e-65d0b594fc4f)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/ac0c659c-0823-4669-b968-daa652ffb892)

![image](https://github.com/invernyx/md11-bugs/assets/150608109/5edb464c-cf38-47cf-9aa8-91086492be25)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
The nose cone UV island arrangement will not change. Because it is separate from the fuselage, it's position in 2D space doesn't really matter. Use planar projection or tri-planar projection to match surfaces on the UV, as islands are not scaled or arranged in 2D space, only projected in 3D space.

The distortions along the left side have been fixed.
The air intakes do not have that issue on my side.

**Comment by alxcpt** [comment]
Well that's rather disappointing for such a high-quality/priced product. I would expect texture mirroring/mismatches on MS default planes but not here. The rest of the plane is awesome textured/mapped. Just to be clear I meant the actual nose not the part under the cockpit windows. The nose is connected to the fuselage (at least in my current version 0.44.0.1) which makes straight lines on the nose part harder than it should be, considering the left and the right side aren't completely equal (probably a 2D to 3D transition problem you can't solve). 
![Screenshot 2024-05-18 075627](https://github.com/invernyx/md11-bugs/assets/150608109/9a694075-9b1f-401d-b243-b77e3c6b75f4)

As for the intakes: I reinstalled the MD to make sure I didn't accidentally messed with the textures, They appear for me on every livery even TFDi House. But they may be fixed in the QA version. 
![image](https://github.com/invernyx/md11-bugs/assets/150608109/1efc7986-3604-4df4-8a64-8b8846041319)
