### ISSUE TITLE
[BUG] - REPLACE ME

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#1187]
### Describe the bug

Air System Hot in Farenheit

### Steps to reproduce

Select F as the temp unit in the EFB settings

### Expected behaviour

Temps in C match selected.   When in F, they seem to double.  Looks like a computation error.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

ANY

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#157
