### ISSUE TITLE
[BUG] - FPA changeover button enables the horizontal FPA lines 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1189]
### Describe the bug

FPA changeover button enbles the horizontal FPA lines

### Expected behaviour

To only have the circle appear on the PFD

The horizontal FPA lines should only appear when the pitch wheel is active 

### Evidence

![Schermopname (556)](https://github.com/invernyx/md11-bugs/assets/150957609/81f9fe7c-e599-4bfb-a690-fc9902a3f985)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
