### ISSUE TITLE
[BUG] - Horizontal FPA lines too short & lower vertical line missing

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1190]
### Describe the bug

Horizontal FPA lines too short & lower vertical line missing

### Expected behaviour

To have longer horizontal FPA lines and to have a lower vertical line

### Evidence

![Schermopname (556)](https://github.com/invernyx/md11-bugs/assets/150957609/0d92a57e-6c0b-4a45-9ea6-bbf86b91c222)
![Schermopname (552)](https://github.com/invernyx/md11-bugs/assets/150957609/9230824d-1696-40d0-b037-2e7f21de470e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Dimples82** [comment]
the circle also looks smaller

**Comment by joon44** [comment]
FPA symbols are also disabled now if the FD is turned off.

**Comment by turbofandude** [comment]
Resolved in 0.48+
