### ISSUE TITLE
[BUG] - Standby attitude indicator erect in C&D state 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1192]
### Describe the bug

Standby attitude indicator erect in C&D state 

### Steps to reproduce

Load in C&D

### Expected behaviour

To have it upside down for instance, not wings level 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version

**Comment by turbofandude** [comment]
Will be resolved in 0.67+
