### ISSUE TITLE
[BUG] - ANNUN LT TEST - Electrical page crosses missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1194]
### Describe the bug

ANNUN LT TEST - Electrical page crosses missing 

### Expected behaviour

To show more crosses 

### Evidence

![Schermopname (565)](https://github.com/invernyx/md11-bugs/assets/150957609/67bef40e-d9af-4cc1-85d9-fcd3ff5c2a3c)
![Schermopname (561)](https://github.com/invernyx/md11-bugs/assets/150957609/ddfa0398-270b-40e3-b688-7e6c84a8ad2d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
