### ISSUE TITLE
[BUG] - ANNUN LT TEST - Config page stab trim cross missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1195]
### Describe the bug

ANNUN LT TEST - Config page stab trim cross missing 

### Expected behaviour

To show a cross by the stab trim number 

### Evidence

![Schermopname (559)](https://github.com/invernyx/md11-bugs/assets/150957609/7a94ddb2-78b6-43d1-82ad-cf32e041d323)
![Schermopname (566)](https://github.com/invernyx/md11-bugs/assets/150957609/6f7ee5f3-95da-4208-ace6-1be290f55037)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
