### ISSUE TITLE
[BUG] - tail fuel management should empty tail before T/D

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#1197]
### Describe the bug

the tail fuel management doesn't empty the tail before T/D

### Steps to reproduce

fly a logn flight with more than 28k kgs at the start. Observe tail fuel management in action. Observe fuel still in tail at T/D and "tail fuel FWD" alert at ~19k feet

### Expected behaviour

![image](https://github.com/invernyx/md11-bugs/assets/138527559/d10e8b54-e8b7-4d2d-9c19-c53f83c45d8c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

n/a

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fuel transfer should also be around 500-700 lbs/min from the tail tank to the mains

**Comment by JeffRichard1958** [comment]
I don't think that the Tail Tank fuel should necessarily be empty prior to descent. I'm reading the manual as the tail tank fuel will be transferred back and forth for CG control and fuel temp within 3 degrees of freezing. However, when any main tank reaches 11,500 lb. the tail fuel will transfer forward, regardless of CG to maintain 11,500 lb in each main. The other trigger is 19,500 feet. At that point CG and temp control is ignored and all tail fuel is transferred forward. It takes 17-20 minutes to land after 19,500 feet, so, at 500 lbs/min, that 8,500-10,000 lbs. can be transferred forward.

**Comment by KJA1582** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/2170028/66ab97f0-31dc-4bd7-8627-bbc9d2a2aefc)

To add, the transfer at 11500lbs (about 5200kg) does not work either

**Comment by turbofandude** [comment]
Resolved in 0.54+
