### ISSUE TITLE
[BUG] - Rudder pedal brakes should move in Cold and Dark state

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1199]
### Describe the bug

In cold and dark state, while braking with external rudder pedals, the sim Rudder pedal brakes don´t move but should.

### Steps to reproduce

Set the aircraft in cold and dark state.
Brake with external rudder pedals.

### Expected behaviour

In Cold and Dark (as any other state) while applying brakes with external rudder pedals, the sim Rudder pedal brakes should move.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
In current builds, they work as expected in C&D
