### ISSUE TITLE
[BUG] - Display information disappears when turning displays on and off

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1201]
### Describe the bug

Some information on the displays disappear when turning displays on and off.

### Expected behaviour

For all information to remain.

### Evidence

https://www.youtube.com/watch?v=t7c9RE4RhTU

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Duplicate of #931
