### ISSUE TITLE
3RD MCDU for ACARS

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1202]
### Describe the bug

See above 

### Expected behaviour

Modelled 3rd MCDU

### Evidence

Fabio wanted it in github lol

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Added as of 0.49+
