### ISSUE TITLE
[BUG] - Third MCDU ACARS ATIS WASM crash

### ISSUE THREAD

**Issue by Swagger897** [invernyx/md11-bugs#1204]
### Describe the bug

Per title, selecting the third MCDU's ACARS ATIS LSK causes a WASM crash.

### Steps to reproduce

ref description
PW -F variant

### Expected behaviour

n/a

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

SL

### Departure

PHNL

### Arrival

PHKO

### Cruise level

270

### ZFW

338.5

### CG

n/a

### Fuel

45350

### Cost index

5

### Route

Dep via RWY8R PIPLN1 ENSKY DCT FIRES KAYAK6 ILS RWY17

### Location

211909N
1575456W

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.52+
