### ISSUE TITLE
[BUG] - Prepar3D CTD when loading the model 

### ISSUE THREAD

**Issue by Douglas-McCormick** [invernyx/md11-bugs#1205]
### Describe the bug

CTD when loading the model and start the flight 

### Steps to reproduce

Select the model, load into the flight, and Crash to the Desk. The MD-11 never worked scince the V0.51 update.

### Expected behaviour

A working beta on P3D

### Evidence

Recorded event on windows event book
 Prepar3D.exe 
   4.5.14.34698 
   5e94b5c2 
   KERNELBASE.dll 
   10.0.19041.4355 
   d7762934 
   c0020001 
   000000000002ba99 
   439c 
   01daae4ddc778fd9 
   F:\001Prepar3D\Prepar3D.exe 
   C:\Windows\System32\KERNELBASE.dll 
   ed03aa8a-5354-468d-8b43-aa6007a2c61c 
I also recorded several event with Process Monitor seeing Prepar3D trying to read several strange files which does not exist :
[Logfiles using PML Format.zip](https://github.com/invernyx/md11-bugs/files/15453975/Logfiles.using.PML.Format.zip)
![image](https://github.com/invernyx/md11-bugs/assets/104307400/cbf67591-045f-46f4-81af-be004784889f)

### Simulator

P3Dv4

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

When loading 

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I cannot reproduce this. Please try deleting all JSON files in %localappdata%\TFDi Design MD-11 and try again.

**Comment by Douglas-McCormick** [comment]
> I cannot reproduce this. Please try deleting all JSON files in %localappdata%\TFDi Design MD-11 and try again.

That does not work, the result is the same:
Prepar3D.exe 
   4.5.14.34698 
   5e94b5c2 
   KERNELBASE.dll 
   10.0.19041.4355 
   d7762934 
   c0020001 
   000000000002ba99 
   1368 
   01daae76d50acc8f 
   F:\001Prepar3D\Prepar3D.exe 
   C:\Windows\System32\KERNELBASE.dll 
   6be99887-e61a-4df2-ba9f-881c2ba63738

**Comment by Douglas-McCormick** [comment]
> I cannot reproduce this. Please try deleting all JSON files in %localappdata%\TFDi Design MD-11 and try again.

**Comment by Douglas-McCormick** [comment]
> I cannot reproduce this. Please try deleting all JSON files in %localappdata%\TFDi Design MD-11 and try again.

I did deleted all Json files, but without results. However I do got some clues, I load the TFDI MD-11 without internet connection, receiving an warning of the "Activation Error", I successfully load the plane into the flight scenario with all system blackout, thus I can basicly exclude my P3D environment's role in CTDs. But when load with the internet the CTD happened without any warning sign. I doubt that some of the Dependencies in the development teams' computer is not included in the installation or some error happens in the activation process.

**Comment by turbofandude** [comment]
Did you have it working previously and it worked or was this a new install?

**Comment by Douglas-McCormick** [comment]
> Did you have it working previously and it worked or was this a new install?

It worked previously and I'm sure the update of 0.50 causing the CTD

**Comment by Douglas-McCormick** [comment]
> Did you have it working previously and it worked or was this a new install?

May I have an option drawing back to V0.44 trying to figure out whether it still works？

**Comment by turbofandude** [comment]
We just picked up a license to P3Dv4 to try it

**Comment by GenericNerd** [comment]
PDK2D2D

**Comment by Douglas-McCormick** [comment]
I guess the BUG was located and could be fixed？

**Comment by turbofandude** [comment]
I just tested in P3Dv4 myself and it installs and runs as expected.

**Comment by turbofandude** [comment]
We have been unable to reproduce this to this point. Please re-open if it re-occurs.

**Comment by Douglas-McCormick** [comment]
> We have been unable to reproduce this to this point. Please re-open if it re-occurs.

Actually the MD-11 has never got worked again since update 0.50 on my PC, and I am also unable to reproduce the bug on my friend's PC. I doubt that something may have conflict with the MD-11. Maybe I should wait till the public release of the MD-11 to see whether it still occur.
