### ISSUE TITLE
Gear up on loading screen (loaded at a gate) and inside the hangar

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#1207]
### Describe the bug

Nose and main gear are shown in up position when viewing the plane inside the hangar and loading at a gate

### Expected behaviour

The gear should be down both inside the hangar and when loading at a gate. (loading directly on a runway is fine) 
Note: The gear appears in up position only before hitting 'start the flight', once inside the cockpit it is shown properly

This is valid for all versions  (passenger and cargo with both engine variants)
and also happens if you take thumbnail pictures via SDK Hangar camera

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150608109/9e41f14a-c72b-4882-849a-cef3adb43d21)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/01397560-e00a-4999-813d-b2aafc43b4f0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Not particularly a bug here. The variables are yet to be initialised and this does not affect flight.
