### ISSUE TITLE
[BUG] - Cannot clear ZFW for data entry in EFB

### ISSUE THREAD

**Issue by falcon71** [invernyx/md11-bugs#1208]
### Describe the bug

Trying to clear ZFW in the EFB for data entry is not possible

### Steps to reproduce

Go to the payload tab in the EFB and switch to the ZFW tab. Use backspace or DEL to clear all digits in order to enter your value. Once the last digit is removed, all digits reappear

### Expected behaviour

I would have expected an empty field, that allows me to enter my desired ZFW. Right now it is very difficult to leave at least on digit, change the first digit, try to click into the field to move the cursor to remove the other digits and leaving the first digit. Please allow an empty field for easy entry of the whole number.
The fuel quantity field is a lot easier in this regard. It leaves a 0, but can be overwritten when the cursor is at the end.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
