### ISSUE TITLE
Negative load percentage + 0 ZFW when entering zero pax and zero cargo into payload menu

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#1209]
### Describe the bug

Negative load percentage + 0 ZFW when entering zero pax and zero cargo into perf calc

### Steps to reproduce

Within the performance calculator (EFB).
Set the passenger amount to 0, set cargo to 0, set fuel to any amount. (Image 1)
Hit Set amount
The 'Passenger and Cargo' page shows negative load percentage and 0 ZFW (image 2) although a value is entered (image 3)

This can be resolved by clicking into the ZFW and hit 'Set amount' again. (image 4)
This doesn't happen if you enter any number for passenger and cargo.

### Expected behaviour

The load percentage should be 0% when loading no pax and cargo. The ZFW should be shown as set. 

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150608109/7f94a9eb-2970-4910-ae2b-28cc6ecdc622)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/5d7c9b32-82bc-47af-8c45-7198bbe48dee)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/bed574a8-725f-4358-80af-baed4394de0a)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/c3236123-8580-49d1-8d30-c889cc03cc27)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
