### ISSUE TITLE
[BUG] - PERF calc looses Airport on NAvigation

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1210]
### Describe the bug

When navigatin away from the Perf calc page and back, the Airport ICAO is lost. All other data is reatined

### Steps to reproduce

Enter PERF calc data and calculate
Switch to any other EFB page
Switch back and observe Airport ICAO is blank

### Expected behaviour

The data to be retained.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/507bbade-98a8-4ccb-9700-dd7ceeda39fc)
![image](https://github.com/invernyx/md11-bugs/assets/2170028/ad6e85cf-7093-4894-b3d0-b9e4e59f1565)
![image](https://github.com/invernyx/md11-bugs/assets/2170028/cd3d9b19-e47d-4019-bd13-75330c072581)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
From what I can tell, this seems purely visual since the runways are still filled in. We'll investigate the problem and see if we can recreate it at all

**Comment by KJA1582** [comment]
It is indeed visual.
If the EFB uses React, this smells like the state uf the TextField not being 1:1 with the state of the component. The Component has the code, works with it and uses it, but the TextField uses it's internal state (i.e. you only used the `onChange `but not the `value` prop)

**Comment by GenericNerd** [comment]
The weird thing is, the `value` field is set directly to the state of the departure ICAO. The component is still aware of this since it is providing the runway fields. It works for us locally, it's just not working correctly in the sim

**Comment by GenericNerd** [comment]
This will be fixed in the next build
