### ISSUE TITLE
Thumbnail showing the complete aircraft on the ground

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#1211]
### Is your feature request related to a problem? Please describe.

may be related to #1207

### Describe the solution you'd like

I would like to get a thumbnail, showing the complete aircraft (the new update shows only part of the fuselage and tail)

Also a version where the gear is in down position standing on MSFS default thumbnail ground.

I know there is no real standard for MSFS thumbnails and every developers chooses own settings. Most of them however show their aircraft in its full glory from side or front view standing on the ground. 
Attached a comparison between TFDi MD-11 and Leonardos MD-80
![image](https://github.com/invernyx/md11-bugs/assets/150608109/24228e70-5879-4daa-b17a-416add19345d)

This was the thumbnail on previous version, looked much more professional
![thumbnail](https://github.com/invernyx/md11-bugs/assets/150608109/774b8b9f-222a-4350-988b-4b263e773ac7)

### Describe alternatives you've considered

see pictures above

### Additional context

see pictures above

**Comment by GenericNerd** [comment]
We do not plan to change the thumbnails at this time.
