### ISSUE TITLE
[BUG] - V speeds

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1212]
### Describe the bug

On a second consecutive flight without restarting the flight/sim, FMC calculated V speeds as Vr being greater than V2.  I was able to input my own values but these were soon overridden back to 169/163 and amber V speed boxes showed up on PFD. After maybe 10 times inputting new values, the speeds stayed.

### Steps to reproduce

Fly multiple flights. Hope to encounter the bug

### Expected behaviour

1. V2 to be higher than Vr
2. Able to input own values
3. FMC to NOT override the inputted speeds
4. Not delete the V speeds from speedtape.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/fbcb70dd-a86c-4941-ae12-6ecb9ae2d0e0)
![image](https://github.com/invernyx/md11-bugs/assets/102414406/0cc0b240-ec79-4dae-8392-5491d7337c16)
![FlightSimulator_IF1pxj83vc](https://github.com/invernyx/md11-bugs/assets/102414406/171a4972-208b-4aeb-9913-bd3bcea3c0ac)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

EDDM

### Arrival

ENGM

### Cruise level

FL320

### ZFW

209.2tn

### CG

30%

### Fuel

23600kg

### Cost index

20

### Route

EDDM/26L N0476F320 INPU2S INPUD Y102 UPALA M726 LASGA DCT EMBOX DCT BUMIL DCT GIMRU DCT SABAK L997 LUNIP LUNI4M ENGM/19R

### Location

EDDM

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Was this PW or GE and was this with deflected ailerons?

**Comment by joon44** [comment]
> Was this PW or GE and was this with deflected ailerons?

GE and deflected ailerons enabled from efb

**Comment by GenericNerd** [comment]
> Was this PW or GE and was this with deflected ailerons?

I had this with GE without deflected ailerons during my test flight and so did Luke.

**Comment by FoxxenD** [comment]
Hi, had this issue on two flights (started from C&D), GE with and without ER, without deflected ailerons too

**Comment by turbofandude** [comment]
Should be resolved in 0.61+

**Comment by joon44** [comment]
Still happens in v1.0
