### ISSUE TITLE
[BUG] - AC model doesn't change on FMC when selecting deflected ailerons 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1214]
### Describe the bug

AC model doesn't change on FMC when selecting deflected ailerons 

### Expected behaviour

To show on the FMC AC model MD11 DEF AIL 

### Evidence

https://youtu.be/gsSdTLp1nVI?si=IS32irCIz6QoPvtv&t=7

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.56+
