### ISSUE TITLE
[BUG] - Nose Steering/Rudder Issue

### ISSUE THREAD

**Issue by GaryC76** [invernyx/md11-bugs#1219]
### Describe the bug

Nose Gear steers when rudder weather vanes

### Expected behaviour

Nose steering should not move when hyd system is depressurized.

### Evidence

![MD-11 NLG](https://github.com/invernyx/md11-bugs/assets/170817156/8df1725a-5418-4510-b957-04e418ea19a7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.61+
