### ISSUE TITLE
[BUG] - autobrake medium/low landing distance

### ISSUE THREAD

**Issue by Evatg04** [invernyx/md11-bugs#1220]
### Describe the bug

When selecting autobreak medium, it is giving a higher expected landing distance than on low

### Steps to reproduce

RWY 24L at LEPA
weather was: winds 240/15, 23c, QNH 1017
Landing Weight: 195500

### Expected behaviour

With autobrake medium it should take less distance than autobreak low to stop.

### Evidence

![FlightSimulator_FaLTFfDXCT](https://github.com/invernyx/md11-bugs/assets/157237717/b97b9f8e-f458-4544-823c-cd5f0d9b0a38)
![FlightSimulator_qUoImcJGNr](https://github.com/invernyx/md11-bugs/assets/157237717/a027bbdf-819d-4587-9128-ccd2327eaa34)
![FlightSimulator_Z9G8wIPHFg](https://github.com/invernyx/md11-bugs/assets/157237717/cc752cb2-18e3-460d-8014-4f16dc6cd386)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by bgiorgio0506** [comment]
@Evatg04 can you provide your VAPP and VREF please ?
