### ISSUE TITLE
[BUG] - Alieron Trim

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#1222]
### Describe the bug

The Aileron Trim indicator is not working, shows LWD8 all the time 

### Expected behaviour

Working indicator

### Evidence

![Screenshot 2024-05-26 001740](https://github.com/invernyx/md11-bugs/assets/143886762/9f02c5cb-deeb-4a3d-a26b-cf154ad9b111)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by JeffRichard1958** [comment]
![Screenshot 2024-05-25 212003](https://github.com/invernyx/md11-bugs/assets/148719444/4724bf6b-f75e-44fd-994c-2caa9e213100)
![Screenshot 2024-05-25 212020](https://github.com/invernyx/md11-bugs/assets/148719444/f7b60d50-545b-4bc5-b024-829e78654ae9)
I had the same issue, and the exterior spoilers and ailerons were in this position as well.

**Comment by GenericNerd** [comment]
This will be resolved in the next version
