### ISSUE TITLE
[BUG] - auto step climb not working with custom constraints

### ISSUE THREAD

**Issue by APJR1994** [invernyx/md11-bugs#1223]
### Describe the bug

The automatic step climb is not working when trying to define which waypoint to climb at

### Steps to reproduce

Enter the steps (in this case, 300, 340 and 360) into the INIT page
Enter /S340 and /S360 into the right lsk next to the desired waypoint
Dial the top altitude (36000 feet) into the MCP

### Expected behaviour

For the aircraft to climb via the constraints, as described in the tfdi discord by staff

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

30000`

### Departure

EHAM

### Arrival

TJBQ

### Cruise level

FL340

### ZFW

177058

### CG

27.4

### Fuel

109.4 kgs

### Cost index

200

### Route

 IDRI2N IDRID L980 MANGO L620 SAM N19 ADKIK DCT JOZMA DCT BEDRA DCT 48N020W DCT 45N030W DCT 40N040W DCT 34N050W DCT 27N058W DCT FIVZE M597 PUYYA DCT IDAHO 

### Location

climb waypoints were 4820N and 2758N

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/2170028/24b0210b-a510-4b82-8830-608634b4dafe)

Apparently also affects automatically calculated S/C points

**Comment by turbofandude** [comment]
I just tested this and it did indeed work correctly. Please re-test with 0.56.

**Comment by KJA1582** [comment]
Wilco once .56 is out for us

**Comment by turbofandude** [comment]
This should be resolved for real as of 0.62+
