### ISSUE TITLE
[BUG] - Selected heading not showing on ND when value is outside of heading scale 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1224]
### Describe the bug

Selected heading not showing on ND when value is outside of heading scale 

### Expected behaviour

To show the selected heading to the right or left of the heading scale when the selected heading is out of range 

### Evidence

![Schermopname (568)](https://github.com/invernyx/md11-bugs/assets/150957609/b4162065-a5ea-45e8-9365-7264fea2ccb4)
![Schermopname (569)](https://github.com/invernyx/md11-bugs/assets/150957609/7ebe4cd6-4531-42db-b589-7b63da53efc2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.53+
