### ISSUE TITLE
Pratt textures look low res & blurry 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1226]
### Describe the bug

See above 

### Expected behaviour

Clean, sharp texturing 

### Evidence

![FlightSimulator 2024-05-25 20-57-03](https://github.com/invernyx/md11-bugs/assets/70169249/000ef862-72d1-48f5-ace6-9b89b5595801)
![FlightSimulator 2024-05-25 20-57-14](https://github.com/invernyx/md11-bugs/assets/70169249/ba2b10e0-8809-4790-a8d5-b8a1db2a4845)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter PW

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This is not a bug. It is feedback. Provide a suggestion if you wish, but this is an invalid bug report.
