### ISSUE TITLE
[BUG] - Cyan level arrow showing for TOC 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1228]
### Describe the bug

Cyan level arrow showing for TOC

### Expected behaviour

To have a magenta circle and magenta cruise level  

### Evidence

![Schermopname (573)](https://github.com/invernyx/md11-bugs/assets/150957609/5a9e83fb-8b57-474d-a2e6-a3d2e5e1ef46)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Page 68 - Displays Holy Grail

**Comment by turbofandude** [comment]
Resolved
