### ISSUE TITLE
[BUG] - Engine FAIL light goes on during landing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1229]
### Describe the bug

Engine FAIL light goes on during landing when reverse thrust differs between engines

### Steps to reproduce

Land and use reverse 

### Expected behaviour

Not go on during landing as it's only for take off 

### Evidence

![Schermopname (583)](https://github.com/invernyx/md11-bugs/assets/150957609/11e43b34-a144-4f79-9c08-8ee50d1f4f94)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Landing

### Altitude

0

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
I could not reproduce this issue. Can you provide an exact step by step or video evidence of this issue?

**Comment by JeffRichard1958** [comment]
1:30:15 Mark of this video, the ENF FAIL Light Illuminated 

https://www.youtube.com/watch?v=e8vp7J1aEFE

**Comment by JeffRichard1958** [comment]
I had not noticed that the reverser did not reply. Great catch. However, a
reverser not deploying would not cause an engine fail. They don’t deploy
all the time in the real aircraft, and it doesn’t cause a Eng fail
annunciation.
