### ISSUE TITLE
[BUG] - Beyond ATC not able to autotune ACP

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1230]
### Describe the bug

With BATC in AUTO TUNE RADIO mode, the app is not able to change frequences  Similar to #31 

### Steps to reproduce

With BATC working, select AUTO TUNE RADIO to ON
After ATC switches you to next freq, monitor ACP

### Expected behaviour

Integration between BATC and MD11 ACP

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Duplicate of #547
