### ISSUE TITLE
Nosewheel cocked 90 degrees on power-up

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1232]
### Describe the bug

Nosewheel cocked 90 degrees on power-up

### Expected behaviour

Nose wheel should always be centered at the gate.

### Evidence

![Screenshot 2024-05-24 181405](https://github.com/invernyx/md11-bugs/assets/148719444/b01aed6e-e6b9-4b94-b71f-b6f332152433)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by Mets747** [comment]
+1

**Comment by FelixFeltersnatch** [comment]
+1

**Comment by GenericNerd** [comment]
Duplicate of #1219
