### ISSUE TITLE
[BUG] - Fuel Burn at Increased Sim Rate remains locked at 1x

### ISSUE THREAD

**Issue by atcogl** [invernyx/md11-bugs#1238]
### Describe the bug

When using increased Sim Rate, the fuel continues to burn in real time causing not enough fuel to be burned during flight

### Steps to reproduce

The airplane is rock solid at 2x and 4x sim rate which is amazing. However the fuel only burns in real time at 1x sim rate regardless. This means on any long haul flight if you use a higher sim rate in cruise you are way above MLW on arrival.
Can be reproduced in any flight by increasing sim rate and watching fuel burn accordingly. EFOB on arrival starts increasing etc

### Expected behaviour

Please tie the rate of fuel burn to the sim rate being used, so at 4x sim rate for example the fuel will burn at 4x the normal rate as well.
I saw there was an earlier report of this which Collin stated that support for Sim Rate above 4X was not planned and that up to 4x was already factored in but that is not the case. At 2 or 4x sim rate the fuel still only burns at 1x

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL370

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.53+
