### ISSUE TITLE
Unable to enable 400ft callout on CAWS in EFB

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1239]
### Describe the bug

Unable to enable 400ft callout on CAWS in EFB

### Expected behaviour

You should be able to enable the 400ft callout on the EFB CAWS page

### Evidence

![400 feet](https://github.com/invernyx/md11-bugs/assets/148719444/b9716e1b-55a2-4a30-8c32-55a1e8d79197)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I do not have this issue. I just tested it here and it works. The view/click system is finicky in MSFS, please try moving the few around and clicking again.

**Comment by KJA1582** [comment]
> I do not have this issue. I just tested it here and it works. The view/click system is finicky in MSFS, please try moving the few around and clicking again.

I noticed that too, sometimes you click through the EFB (the PTT button is right behind the 400 IIRC)
