### ISSUE TITLE
The EFB "Pressure" (altimeter) is missing the last digit when it is a zero

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1240]
### Describe the bug

When using the "Get weather information" tab, the altimeter was missing the last digit. However, this  was when the last digit was zero

### Expected behaviour

When using the "get weather information" tab on the EFB PERF page, the last digit should always be visible, even when it is a zero.
![Screenshot 2024-05-24 185323](https://github.com/invernyx/md11-bugs/assets/148719444/131efcf2-ece0-4a79-b899-9c21c0b9171f)

### Evidence

![Screenshot 2024-05-24 185323](https://github.com/invernyx/md11-bugs/assets/148719444/131efcf2-ece0-4a79-b899-9c21c0b9171f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
