### ISSUE TITLE
Yoke uncommanded displacement full-right on flight control check

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1241]
### Describe the bug

Yoke uncommanded displacement full-right on flight control check

### Expected behaviour

the yoke should be centered, see YouTube video in "evidence"

### Evidence

https://youtu.be/uPcVhSi08A4

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Is this repeatable?
