### ISSUE TITLE
[BUG] - Vertical rudder

### ISSUE THREAD

**Issue by SunKing135** [invernyx/md11-bugs#1242]
### Describe the bug

Rudder is missing some parts so that one can look through.

### Expected behaviour

Not sure if it is intended, but shouldn´t it be normal to not to be able to look through the gap between rudder and vertical stab. I can also imagine that this may be fixed with the next art/model update.

![fsscr009](https://github.com/invernyx/md11-bugs/assets/152623434/2604715b-bd41-4dbd-91d7-1afac574e78d)
![fsscr011](https://github.com/invernyx/md11-bugs/assets/152623434/3ee70d15-01a5-4915-a84d-b2539ddaccc7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by SunKing135** [comment]
![fsscr011a](https://github.com/invernyx/md11-bugs/assets/152623434/9ce6d2e0-1b5f-4d68-a4fe-2f7b5c9779e8)

One more image with rudder not slanted. It is very obvious in the red circled that one can look through.

**Comment by SunKing135** [comment]
On the real aircraft it is not as obvious. Hence the images
![1899010](https://github.com/invernyx/md11-bugs/assets/152623434/7d2ae041-3211-4277-867b-ea09fb3d0102)
![2548459](https://github.com/invernyx/md11-bugs/assets/152623434/ad4dbeb9-3b6e-406d-99f6-82ff0d8d502a)
![4259253](https://github.com/invernyx/md11-bugs/assets/152623434/6c3b00cd-7a58-49b4-b845-76c466e70e77)

**Comment by arwasairl** [comment]
This will not be fixed at the moment as it will require stretching the UV which will affect all liveries currently made. It may be updated in the future but at the moment no suitable timeframe allows us to do this.

**Comment by alxcpt** [comment]
Well I hope this got fixed before the official paintkit is released, as even more liveries will show up afterwards. I have done some liveries as well (the Lufthansa Cargo ones are mine) and the tail part is the most annoying one on this addon. The left and right side UV doesn't fully match, logos put onto the individual rudder parts are misaligned/or have an offset, and the parts between both sides is split in multiple individual parts and needs a lot of adjustments to be made. If you could adjust the UV there and close those huge gaps this would improve the already pretty good model. And please also remember, people pay/paid for your addon. They/We deserve the best MD-11 possible. But I understand @arwasairls point, system fixed have definitely priority.
