### ISSUE TITLE
External Lights Are Not Correct and in wrong positons

### ISSUE THREAD

**Issue by Mets747** [invernyx/md11-bugs#1243]
### Describe the bug

The Nav and Strobe Lights are Not in the correct locations and flashing pattern is wrong. There is also no Beacon lights that flash.

### Expected behaviour

The white nav lights on the trailing edge are the two small bulbs on each side of the housing. The rear facing strobe light is positioned in between both nav lights. 

Also, the front facing strobe lights are a double flash and the rear strobe is a single flash timed to match the first flash of the front strobe.

### Evidence

![11](https://github.com/invernyx/md11-bugs/assets/150335154/24475eaa-09e3-4de0-a285-bdf5e7b7a601)
![main-qimg-7737f6b81d9cc00c205072ad3607b20a](https://github.com/invernyx/md11-bugs/assets/150335154/097f7116-150d-4bbd-9c56-45ff41dd7911)

This is showing the incorrect flash of the front strobes, It should be a double flash
https://imgur.com/RazfVN6

The lights that are flashing are NOT the strobe lights, they are supposed to be the white nav lights. The strobe should be in between both of them.
https://imgur.com/k6ULyAI

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by Mets747** [comment]
You can definitely do the double flash with effects only. I did a very popular light mod for the ini A300 and had no issue doing it. They are basically the same strobe pattern on both A300 and MD11

**Comment by arwasairl** [comment]
> You can definitely do the double flash with effects only. I did a very popular light mod for the ini A300 and had no issue doing it. They are basically the same strobe pattern on both A300 and MD11

The light source is a mesh, which is controlled via a vis-tag. Vis-tags cannot be controlled via effects.

**Comment by Mets747** [comment]
> > You can definitely do the double flash with effects only. I did a very popular light mod for the ini A300 and had no issue doing it. They are basically the same strobe pattern on both A300 and MD11
> 
> The light source is a mesh, which is controlled via a vis-tag. Vis-tags cannot be controlled via effects.

Ahh ok. Excuse my ignorance. That is a little too advanced for me lol. But thanks. Hopefully this can be figured out!

**Comment by Mets747** [comment]
Here is a video showcasing what I'am talking about. Double flash front with a single flash in the with the rear flash in sync with the first flash in the front

https://youtu.be/EaTrvSF5dGU?t=944

**Comment by turbofandude** [comment]
Will be resolved with the art update

**Comment by arwasairl** [comment]
This has been fixed in an indev version.

**Comment by Mets747** [comment]
Not sure how the external lights made it through the QA for v1.0 art update? The strobe lights in the front of the wingtip are facing and flashing backwards, the rear strobe light doesn't even flash. They also have no textures assigned to them so you don't see any light orbs. there are multiple topics about the lighting which each one responded to as "solved in art update" to me they are no where close to being done how they are on the real MD-11. I really hope this will be addressed in another future update. Other than that, it's looking really good!

**Comment by Mets747** [comment]
![strobe light](https://github.com/invernyx/md11-bugs/assets/150335154/f5e56f9a-7599-4bda-ba52-9f867435700d)

**Comment by arwasairl** [comment]
> ![strobe light](https://private-user-images.githubusercontent.com/150335154/343646403-f5e56f9a-7599-4bda-ba52-9f867435700d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzI1NTUsIm5iZiI6MTcxOTQ3MjI1NSwicGF0aCI6Ii8xNTAzMzUxNTQvMzQzNjQ2NDAzLWY1ZTU2ZjlhLTc1OTktNGJkYS1iYTUyLTlmODY3NDM1NzAwZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwNzEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWNlN2Q3NzU3M2MxN2IwODBlMGFhOGRhYjMxMTM3MDE4MjcwNGYyZjYwY2U3ZmQxYzE5ZjQ5MGRmZWI4NmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GUk4aB70zOMOikFfmn0uNxwYc4LVYJT1UstLrawc3Iw)

This is an incorrect statement according to this image we got from mechanics. 
![IMG_5953](https://github.com/invernyx/md11-bugs/assets/48654776/d1b1cb37-2b08-4536-afcf-6b48a480f086)
![IMG_5954](https://github.com/invernyx/md11-bugs/assets/48654776/b1c3e046-4363-45d4-a01a-af5e46c2c189)

**Comment by Mets747** [comment]
Hmm, alright then...I sincerely apologize and stand corrected. Well then on another note, that rear strobe is only supposed to flash once and the front flash twice. Also there is no NavWhite.fx file for the two bulbs on the rear. The lights also do not have a texture assigned to them (FX_0.PNG.DDS)
