### ISSUE TITLE
[BUG] - Some Settings not restored properly

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1245]
### Describe the bug

Some Settings in the EFB are not restored properly
Known to me are:
- CASW Altitude callouts
- Standby Instrument Selection

### Steps to reproduce

All done in C/D as default startup state

Enable all CAWS callouts for Altitudes
Hit save
Observe values in the options JSON are set to true
Reload Simulator
Observe settings page CAWS callouts are all disabled (I haven't looked into the files after noticing, but I did test whether savin even works by disabling the 2500FT callout, it did correctly set the value to fals in the jSON)

### Expected behaviour

It not doing that

### Evidence

Sadly no pics since I noticed too late.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by PointBlank66** [comment]
I can confirm that there is no persistency in regards to state saving.
In my case, this applies to all the settings in the options page of the efb, not just CAWS and the standby instrument.

**Comment by turbofandude** [comment]
> I can confirm that there is no persistency in regards to state saving. In my case, this applies to all the settings in the options page of the efb, not just CAWS and the standby instrument.

This is simply not true. The settings are stored on a per-livery basis, however, and that may lead to this confusion.

**Comment by KJA1582** [comment]
Me saving CAWS
![image](https://github.com/invernyx/md11-bugs/assets/2170028/3469c9ed-5944-42f1-890c-a3ab57b6c680)
Me using ESC > Restart.
![image](https://github.com/invernyx/md11-bugs/assets/2170028/00a0c7d2-a846-42a4-a435-db96e1a59b75)

Something iwthin the loading is not honouring the file, it affects some settings but not others (SB username is saved and recalled correctly for example)

> > I can confirm that there is no persistency in regards to state saving. In my case, this applies to all the settings in the options page of the efb, not just CAWS and the standby instrument.
> 
> This is simply not true. The settings are stored on a per-livery basis, however, and that may lead to this confusion.

**Comment by joon44** [comment]
I concur. I also have this issue.

**Comment by KJA1582** [comment]
Further investigation
All tests done with D-ALCC

Sim closed
![image](https://github.com/invernyx/md11-bugs/assets/2170028/e845339c-d7d6-46e0-8585-31ef09699ff8)

MD-11 loaded into EDDM
![image](https://github.com/invernyx/md11-bugs/assets/2170028/d6443a87-ec36-4956-a806-923cd59da9b4)

After sim exit, closed via the Main Menu Quit
![image](https://github.com/invernyx/md11-bugs/assets/2170028/16ca8308-2bf1-492b-9152-3165a272cf18)

**Comment by joon44** [comment]
Still the same issue in .54. Its getting frustrating going through settings on every flight.

**Comment by TheFightingRaven** [comment]
@turbofandude sorry but this is really a thing, might be EFB side

**Comment by KJA1582** [comment]
> @turbofandude sorry but this is really a thing, might be EFB side

It might be on both sides, EFB and WASM.
The issue is somewhat surprised when using last state as the default load state, however that still leads to the Nav’s blinking even after alignment is complete. Somewhere within the loading system is a bug that doesn’t quite load things in the order it should (best guess).

**Comment by turbofandude** [comment]
Found and fixed. This was a combination of three separate issues. One (the CAWS) was resolved a few builds ago and the other two are resolved as of 0.64+.
