### ISSUE TITLE
[BUG] - 3rd CDU missing backlighting

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1247]
### Describe the bug

3rd CDU in the rear pedestal doesnt have backlighting in the buttons

### Expected behaviour

Have lights

### Evidence

![FlightSimulator_YJ5jbhazQL](https://github.com/invernyx/md11-bugs/assets/102414406/c917f2b5-ec2d-4b7b-b8e6-514190f4e494)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.55+
