### ISSUE TITLE
[BUG] - FCU display lighting

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1248]
### Describe the bug

FCU displays still show the red backlight when the aircraft is fully unpowered in cold & dark state and it can be adjusted normally.

### Expected behaviour

Not have backlighting

### Evidence

![FlightSimulator_t8Rvfns2C5](https://github.com/invernyx/md11-bugs/assets/102414406/abce8c2f-13a3-4cc0-97ec-b301f7d0c0f0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/2170028/e91f519d-bed4-4a45-ae17-95e09d497e1d)

Also affecting the Fuel Readout on the OVHD

**Comment by turbofandude** [comment]
Resolved in 0.57+
