### ISSUE TITLE
[BUG] - SimBrief import failed

### ISSUE THREAD

**Issue by wagoozen1** [invernyx/md11-bugs#1249]
### Describe the bug

Unable to load F-PLN using NAT routes

### Steps to reproduce

1. In simbrief create a flight from EHAM-CYYZ, use the suggested route contain NATX..
2. Continue create the flight plan and generate the flight.
3. In the EFB load flightplan and send FLight plan to FMC
4. The FMC output an error 'Unable to load F-PLN'
5

### Expected behaviour

Route importe working including nat tracks

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/114499693/2a0804b1-33f3-4d1f-b189-64c56979b89d)
I used reload flight plan in this example as i was testing the steps, and i didnt want to reload MSFS. 
when starting the plane for the first time and you press load into fmc, you only geet the error message no date

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

EHAM

### Arrival

CYYZ

### Cruise level

0

### ZFW

n.a.

### CG

n.a.

### Fuel

n.a.

### Cost index

n.a.

### Route

EHAM/18L N0490F340 BERG4E BERGI L602 SUPUR L60 PENIL M144 BAGSO DCT DOGAL/M084F360 NATE TUDEP/N0491F380 DCT MIILS DCT VILRO DCT SAVEX Q806 TUKIR IMEBA9 CYYZ/15L

### Location

EHAM

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
NAT tracks is not the problem here. I will need your SimBrief username or the .json of the flight plan from this url: https://www.simbrief.com/api/xml.fetcher.php?username={YOUR USERNAME HERE}&json=1

**Comment by wagoozen1** [comment]
Hi Colin,

This one should work:
simbrief.com/api/xml.fetcher.php?username=wagoozen&json=1
<https://www.simbrief.com/api/xml.fetcher.php?username=wagoozen&json=1>

Also, before i report this one are you planning to change the rotate knobs
sounds? its very unrealistic and it sounds like one speed of turn while
when turning left fast or slow it still is the same ticking sounds. and if
you do for example
from heading 100 to 095 once done the sounds is still playing.

I know the plane is still in development but wanted to know if i should
report it or if this is being polished before going RTM.


Thanks Colin

Andres van Goozen






Op ma 27 mei 2024 om 18:50 schreef Collin Biedenkapp <
***@***.***>:

**Comment by GenericNerd** [comment]
> Also, before i report this one are you planning to change the rotate knobs sounds? its very unrealistic and it sounds like one speed of turn while when turning left fast or slow it still is the same ticking sounds. and if you do for example
These are not related to this issue. Please submit new issues for these items.

**Comment by wagoozen1** [comment]
I know that was just checking, will report :)

Op ma 27 mei 2024 23:28 schreef GenericNerd ***@***.***>:

**Comment by turbofandude** [comment]
Resolved in 0.55+. Also, I stand corrected, it was indeed NAT tracks breaking the import. That has since been resolved.
