### ISSUE TITLE
[BUG] - Step Climb Drawn at wrong point

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1250]
### Describe the bug

Step climb magenta arrow is shown on the wrong waypoint

### Steps to reproduce

Add a /S constrain to a waypoint
Sometimes, the magenta arrow is drawn at the preceeding wapoint instead of the one with the constraint

### Expected behaviour

Magenta arrow at correct Waypoint

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/a18f244f-5a71-48e0-a9cb-6d914b83dfa1)

Route in question:
[WSSSOMDB_PDF_1716746959.pdf](https://github.com/invernyx/md11-bugs/files/15449328/WSSSOMDB_PDF_1716746959.pdf)

I preset both 340 and 360 /S constraints at the departure gate. Only the first S/C was subsequently displayed, drawn at the correct waypoint. After stepping, the next S/C was displayed, with the above seen result.

State:
[SCWRONG.json](https://github.com/invernyx/md11-bugs/files/15449337/SCWRONG.json)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

34000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
As far as I know, only one is drawn at a time. Additionally, the S/C point I see drawn in your picture matches the sequence in the FMC. What exactly is the issue?

**Comment by KJA1582** [comment]
I put the /S on DOGET.
Sequencing shows S/C and DOGET both have the same ETO (" at DOGET)
Drawn arrow is at SUGID, the wpt berfor DOGET

**Comment by turbofandude** [comment]
Resolved in 0.56+
