### ISSUE TITLE
[BUG] - Wing leading edge light leaks (MD-GEN-9)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1252]
### Describe the bug

Wingtip NAV lights leak through the leading edge wing structure (similar to #583 )

### Expected behaviour

No bleed through

### Evidence

![FlightSimulator_2024_05_25_18_26_47_290](https://github.com/invernyx/md11-bugs/assets/148836830/3e7457c7-c415-49b2-8809-da8c120482fb)
![FlightSimulator_2024_05_25_18_27_05_144](https://github.com/invernyx/md11-bugs/assets/148836830/f99a3737-474a-4f87-9a1f-9f56b7e98150)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
I'm unable to recreate this.
![image](https://github.com/invernyx/md11-bugs/assets/48654776/c8ba6091-ad9a-465e-8f08-e362f163e579)
![image](https://github.com/invernyx/md11-bugs/assets/48654776/d4ebccf4-dd05-48c6-ad73-c99dfebf1b71)

It very well could be that either CE or QA has an older version of the effects.
