### ISSUE TITLE
[BUG] - PACKS do not cool cabin

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1253]
### Describe the bug

The PACKS do not cool the cabin, either with APU BLEED or ENGINE BLEED.

### Steps to reproduce

Start the APU and turn ON APU AIR. Notice that the cabin temperature will increase to around 135F.
Start the engines normally, and notice that cabin will still not cool down with engines running and packs on.
In flight the cabin is not cooled either.

### Expected behaviour

PACKS able to cool cabin.

### Evidence

![FlightSimulator_ZvXFnbolGu](https://github.com/invernyx/md11-bugs/assets/95483637/a92eb75f-cbb3-417a-a7f4-faa5d5c3f7b0)
![FlightSimulator_apkK65OVRE](https://github.com/invernyx/md11-bugs/assets/95483637/d820db70-bb9d-4ce9-b66b-0740a523e527)
![FlightSimulator_Sjvdb0xeoo](https://github.com/invernyx/md11-bugs/assets/95483637/4cfa83fe-bf64-460b-b19c-afd355359ab4)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by 09tir98** [comment]
They don't seem to cool the cabin in the air either. All systems are in auto.
![image](https://github.com/invernyx/md11-bugs/assets/95483637/f39e86c2-17a2-4af6-8f08-261e7e3ac26f)

**Comment by turbofandude** [comment]
Resolved in 0.55+
