### ISSUE TITLE
[BUG] - Yaw Damp and LSAS lights should illuminate FAIL

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1254]
### Describe the bug

When the aircraft is AC powered the Yaw Damp and LSAS lights should illuminate FAIL

### Steps to reproduce

Power the aircraft
Check Yaw Damp and LSAS lights status

### Expected behaviour

When the aircraft is AC powered the Yaw Damp and LSAS lights should illuminate FAIL.
The FAIL light should be extinguish some time after the IRU align start. (approximately 30 seconds after the IRU are set to NAV)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Duplicate as part of secondary flight controls
