### ISSUE TITLE
[BUG] - ACARS ignore autofilled callsign entry

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#1256]
### Describe the bug

ACARS ignore autofilled callsign entry

### Steps to reproduce

have hoppies code entered
fill out the init page
observe acars requests don't work
ref -> atc comm page see data link says "no comm"
enter callsign manually
onbserve data link "ready" after a few seconds

### Expected behaviour

after the callsign is entered in the init page and thus autofilled in the atc-comm page the acars systems should start working

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

n/a

### Departure

n/a

### Arrival

n/a

### Cruise level

n/a

### ZFW

n/a

### CG

n/a

### Fuel

n/a

### Cost index

n/a

### Route

n/a

### Location

n/a

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
The behavior is a feature. That is, the callsign entered in the INIT page is prefilled in the ATC LOGON page. Subsequently, a crew member will need to head over to the ATC LOGON page and line select the prefilled callsign to `confirm` that it is the correct callsign to be used for datalink communications.

In essence, it is not harmful to fly with the wrong callsign in the INIT page but it is vital that you have the correct callsign for datalink communications. Thus, the feature provides the means for confirmation unless you directly enter the callsign in the ATC LOGON page.

**Comment by turbofandude** [comment]
Behavior changed in 0.56+
