### ISSUE TITLE
[SUGGESTION] - EFB text fields should auto-hightlight entire value on first click

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1260]
### Is your feature request related to a problem? Please describe.

When clicking in a text field, your cursor position is set to either the front or the back of that field, it doesn't seem to be consistent which one, but either way, it's odd to type in this manner when there's already a value in the field, for example when typing ZFW I found my cursor when to in front of the number, but there's no logical reason why I would type a number in front of the existing value, so I am forced to backspace the number anyway.

### Describe the solution you'd like

When you click in a text field on the EFB, by default the entire value in that field should be highlighted, such that if you pressed backspace or began typing you would overwrite the entire value.

### Describe alternatives you've considered

N/A

### Additional context

The ZFW number is where I found this, but there are a lot of locations all over the EFB I noticed where text handling is awkward or cumbersome.

**Comment by GenericNerd** [comment]
This will be done in the next version

**Comment by Alex6511** [comment]
@GenericNerd I can confirm that this isn't working, Falcon is correct.
