### ISSUE TITLE
[BUG] - Gear handle release button non-functional

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1261]
### Describe the bug

Clicking the gear handle release button does nothing.

### Steps to reproduce

Click the gear handle, and observe nothing happens.

### Expected behaviour

This should unlock the gear lever, allowing it to be put to the up position, even when the ground detection system has determined the aircraft is on the ground. For the purposes pre-extended sim, this shouldn't actually do anything, the gear should remain down, but the button should at least depress. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved
