### ISSUE TITLE
[BUG] - FO EIS source knob scroll direction reversed

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1262]
### Describe the bug

The EIS source knob on the FO side has its scroll direction set illogically

### Steps to reproduce

Scroll on the FO EIS source knob. Notice that scrolling "up" rotates the button to the left, which is different from other knobs like the flap limit, EMR PWR, all temperature knobs, and the SMOKE/AIR NORM switch. 

### Expected behaviour

Scrolling down should rotate the knob to the left and up to the right.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved by closing #1085 and #825
