### ISSUE TITLE
[SUGGESTION] - The IRS panel knobs should be knobs and therefore be controlled by scroll instead of clicking

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1264]
### Is your feature request related to a problem? Please describe.

Currently, if you scroll on the IRS knobs, nothing happens, this is different from almost every other knob in the cockpit that is instead controlled by scrolling.

### Describe the solution you'd like

You should be able to scroll to control these buttons, as given most knobs in the cockpit are controlled by scrolling, it's inconsistent with the cockpit usage methodology. 

### Describe alternatives you've considered

Perhaps just allow both?

### Additional context

N/A

**Comment by GenericNerd** [comment]
They are two position knobs, therefore, this is correct behaviour. All two position switches are clicks.

**Comment by Alex6511** [comment]
Same.
