### ISSUE TITLE
[BUG] - Flap Retraction Timing (MD-FC-7)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#127]
### Describe the bug

With both AUX HYD PUMPS ON, RMP 1-3 ON and RMP 2-3 ON, setting dial a flap to 25 and setting flaps 25 from 50, flaps reach flaps 25 in 10 seconds, flaps 25 to flaps 0 in 10 seconds

### Steps to reproduce

Ground
Ground PWR ON
AUX PUMP 1 and 2 ON
RMP 1-3/2-3 ON
Set Dial-a-flap to 25
Set flaps 50
Set flaps 25
Start timer
End timer once flaps reach 25 on the CONFIG SYN page
Start timer
Set flaps 0
End timer once flaps reach 0 on the CONFIG SYN page

### Expected behaviour

S/B 13-19 seconds to reach flaps 25, 7.5 to 11.5 seconds to reach flaps 0 from flaps 25

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Still not fixed in V0.42.01

**Comment by GenericNerd** [comment]
This will be resolved in the next version
