### ISSUE TITLE
[SUGGESTION] - Create an systems option to use the number 3 MCDU for digital VHF, SQK tuning.

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1270]
### Is your feature request related to a problem? Please describe.

iNiBuilds recently added digital comm tuning panels for their A300-600. It is a huge help when using VATSIM, avsim.com, vattastic.com, simaware.ca, ivao.aero

### Describe the solution you'd like

Use the #3 MCDU to act as a digital VHF, SQK tuning panel similar to the new feature on the iNiBuilds A300-600. This would either replace or supplement the manual tuning panels.

### Describe alternatives you've considered

See above

### Additional context

![Screen Shot 2024-05-28 at 12 57 38 AM](https://github.com/invernyx/md11-bugs/assets/148719444/b1b76909-6cd3-4b9c-a3ca-9be0cbf18615)

**Comment by GenericNerd** [comment]
We won't be adding this feature
