### ISSUE TITLE
[BUG] - N1 not displayed on TAKEOFF page

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1271]
### Describe the bug

N1 is not displayed on the TAKEOFF page

### Steps to reproduce

Fill out the WEIGHT INIT page and the TAKEOFF page and note that N1 is not displayed on the TAKEOFF page.

### Expected behaviour

N1 displayed on the TAKEOFF page.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/95483637/2766faf7-b338-46b5-9ff2-644f1be15030)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

VHHH

### Arrival

OMDB

### Cruise level

FL300

### ZFW

414.2 LBS

### CG

18.3

### Fuel

179.3 LBS

### Cost index

100

### Route

VHHH/07R N0509F300 PECA2A PECAN V10 SIKOU/K0943S0920 A202 ASSAD/K0933F320 A206 NALAO/N0504F320 A206 LPB B465 CEA A791 SEBMA/N0500F340 A791 BPL L639 MILUP/N0493F360 L639 RASKI L301 RAGMA N571 VUSET A454 PASOV B540 KUPMA/N0446F240 B540 MIVEK P574 IMPED IMPE3C OMDB/30L

### Location

On ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.54+
