### ISSUE TITLE
[BUG] - Plane is too slippery

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1272]
### Describe the bug

After the .52 update, the plane is very slippery. Its going overspeed even on a slight descend and at least 1/3 spoilers is required most of the descend. Plane cannot hold the required speed.

### Steps to reproduce

Have a normal flight and observe speed going up.

### Expected behaviour

Able to descend without speed brakes all the time

### Evidence

Here the speed is 358kts and with -1600ft/min, as shown, it is barely holding. -2000ft/min its already going overspeed.

![FlightSimulator_W7yrv693it](https://github.com/invernyx/md11-bugs/assets/102414406/55e3833d-34c2-4815-9959-e7d9a5a137e4)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by Dimples82** [comment]
I feel the same, after the .52 version the aircraft became very slippery, comparing with previous version. Don´t know how real aircraft behaves.
