### ISSUE TITLE
[BUG] - ND & PFD heading scale numbers missaligned 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1273]
### Describe the bug

ND & PFD heading scale numbers missaligned 

### Expected behaviour

To have the second digit behind the vertical stripe instead of under it, could do by making the vertical stripes longer as well 

### Evidence

![Schermopname (589)](https://github.com/invernyx/md11-bugs/assets/150957609/e757939b-a418-406e-ad2d-36d6277859da)
![Schermopname (582)](https://github.com/invernyx/md11-bugs/assets/150957609/24bbe611-df74-4703-a6cb-586ff45d8932)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.54+
