### ISSUE TITLE
[BUG] - GW still shows in KG when Tape Displays enabled

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#1274]
### Describe the bug

GW still shows in KG when Tape Displays enabled

### Expected behaviour

GW should show in MT, regardless of whether Tapes are enabled or not

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/a1f4a3a8-b4df-4306-92f8-2dce564d59c6)
![image](https://github.com/invernyx/md11-bugs/assets/150094502/3707816d-fcd8-4579-b9bf-960b8a3efd26)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.54+
