### ISSUE TITLE
Fuel Quantity Test should read 52,400 lb., not 63,000 lb.

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#1275]
### Describe the bug

Fuel Quantity Test should read 52,400 lb., not 63,000 lb.

### Expected behaviour

See the FOM guidance below. The fuel quantity test starts with all 188880 displays and the goes to five tanks with 10,500 lb. At this point the totalizer should read 52,400, but it reads 63,000. It was reading 52,400 until a couple of revisions ago.

### Evidence

![Screen Shot 2024-05-28 at 8 53 55 AM](https://github.com/invernyx/md11-bugs/assets/148719444/92dd2a51-d06e-40eb-b4d0-50d6073e747d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by moosestaffa83** [comment]
According to the FCOM 63000 is correct for the ER

**Comment by JeffRichard1958** [comment]
I was not aware that the fuel test was different on the ER.
