### ISSUE TITLE
[BUG] - Top of Climb not pushed forward

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1276]
### Describe the bug

Top of climb is not pushed forward along the route

### Steps to reproduce

Climb out normally
Observe T/C cyan arrow not being pushed forward to the new expected T/C if climb is flatter than assumed by PROF

### Expected behaviour

T/C cyan arrow getting pushed forward

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/0f3bf7b4-83c5-46b1-b315-61794a46b29d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

FL300

### Departure

OMDB

### Arrival

EDDF

### Cruise level

FL320

### ZFW

199848 kgs

### CG

18.7

### Fuel

60850 kgs

### Cost index

80

### Route

[OMDBEDDF_PDF_1716904292.pdf](https://github.com/invernyx/md11-bugs/files/15471837/OMDBEDDF_PDF_1716904292.pdf)

### Location

Shortly after RALMI

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/2170028/68c1244e-7c80-4eff-ba05-a6c024abadb0)

Same for S/C, my assumption is it will also occur on T/D

**Comment by turbofandude** [comment]
Resolved in 0.54+

**Comment by KJA1582** [comment]
@turbofandude Not resolved in .54
![image](https://github.com/invernyx/md11-bugs/assets/2170028/dc6df686-a950-4ba8-a8d1-361161aa9016)

AC Version
![image](https://github.com/invernyx/md11-bugs/assets/2170028/a93c7b1b-6162-4c63-b70d-2c35b4a9cf83)
