### ISSUE TITLE
[BUG] - Flight Control Surface Relaxation Position (MD-FC-8)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#128]
### Describe the bug

With both AUX HYD PUMPS OFF, RMP 1-3 OFF and RMP 2-3 OFF (all 3 HYD sys press 0) the INBD AIL, flaps and INBD 	elevator do not droop

### Steps to reproduce

asd

### Expected behaviour

S/B INBD AIL and INBD elevator droop to max down deflection over 75 seconds.  Flaps should droop approximately 6 degrees down in 75 seconds

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Still not fixed on v0.42

**Comment by GenericNerd** [comment]
This will be resolved in the next version
