### ISSUE TITLE
[BUG] - FUEL SYSTEM IMBALANCE ISSUES

### ISSUE THREAD

**Issue by OD-Emperor** [invernyx/md11-bugs#1280]
### Describe the bug

Fuel Systems dont seem to balance properly

### Steps to reproduce

On several flights I've noticed that using the EFB to load fuel doesn't seem to load it evenly/how the plane would like. On takeoff/climb out this causes the plane to pitch unnecessarily far forward to maintain an acceptable rate of climb. Unsure if this is a trim issue or a fuel balance issue. 

In the provided video you can see that fuel system had zero fuel in the tail tank on departure which seemed to cause the issue. During the flight it filled the rear tank to 4.9 tons. On descent it needed to then shove a about 700kg of that fuel forward to maintain a neutral position on the tailplane during descent. 

It seemed at one point in the descent to not even be able to keep the path because of the fuel balance. It lost the VNAV path before regaining it later once fuel had balanced.

### Expected behaviour

For the plane to properly balance fuel before descent so that it does not have to maintain this weird pitch behavior.

### Evidence

Google drive with video/pictures of tail behaving weird:
https://drive.google.com/drive/folders/1dDAdT9Kcm3MtzwfrwoJs6xy1C295pIXD?usp=sharing

This Google Drive also includes the route I witnessed this on with simbrief weights though I'm sure if there is more I havent noticed.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

FL030 to FL280 and on descent from roughly the same points just in reverse

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The MD-11's fuel balancing/CG management is a very complex system. The CG seemed within range in both videos you sent and having weight in the tail move around during the flight is expected. The fuel loading system is according the loading schedule we have access to and is correct.
