### ISSUE TITLE
[BUG] - PAX LOAD number not aligned with slot opening

### ISSUE THREAD

**Issue by PointBlank66** [invernyx/md11-bugs#1283]
### Describe the bug

The numbers on of the PAX LOAD wheels do not seem to align with the slot openings. This happens both on the GE and PW variant of the MD-11 (see first image)

### Expected behaviour

The numbers should align in the middle with slot opening (see second image)

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/4239471/4f2b10fd-05f5-4328-9ca6-007b6c0f0d32)
![image](https://github.com/invernyx/md11-bugs/assets/4239471/14a65a28-00c0-4f30-b367-95c4106550e0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Fixed frame numbers, now displays normally
