### ISSUE TITLE
[BUG] - Manual Fuel transfer is evaporating fuel

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1284]
### Describe the bug

Manual fuel transfer is not keeping the fuel level static.
I noticed this during several flight pre 0.54 when having to manually transfer the fuel fwd from the tail.
The fuel would be removed from the tail, but not added to the main/uppr aux (my procedure for this was transfer aux both on, tail transfer on, main 1,2,3 fill on)

### Steps to reproduce

On Ground power
FILL on MAIN 1 & 3
X-FEED MAIN 2 on

### Expected behaviour

Fuel shifting but total fuel remains stable

### Evidence

https://github.com/invernyx/md11-bugs/assets/2170028/e01a8956-ca48-4904-9a72-497f07d470cb

Some time later

![image](https://github.com/invernyx/md11-bugs/assets/2170028/10577f92-a8f4-47b6-94f4-9a29f5c02139)

Also not the green lines on the FUEL SYN are not indicative of how the fuel flows.
### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Post-flight

### Altitude

30ft

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should now be resolved
