### ISSUE TITLE
[BUG] - Deformed Cabin Interior

### ISSUE THREAD

**Issue by captJojo11** [invernyx/md11-bugs#1286]
### Describe the bug

Cabin looks like a roblox airplane cabin

### Expected behaviour

![20231109180616_1](https://github.com/invernyx/md11-bugs/assets/150375285/c3676c7f-043a-4278-b289-3027d957544a)
![20231109180620_1](https://github.com/invernyx/md11-bugs/assets/150375285/f8a02850-7bd9-4fc0-88bb-e61fdf067838)
![20231109180625_1](https://github.com/invernyx/md11-bugs/assets/150375285/5d577018-b458-4c79-8600-bf999497e42a)

### Evidence

![20240529235557_1](https://github.com/invernyx/md11-bugs/assets/150375285/87f66cb1-396b-4d71-8db0-78730776f12a)
![20240529235805_1](https://github.com/invernyx/md11-bugs/assets/150375285/04bccf83-f2d5-4aaf-bddc-818bac6fec53)
![20240529235839_1](https://github.com/invernyx/md11-bugs/assets/150375285/25c214a9-b1f7-43a5-bfb2-8ec760176da8)
![20240529235859_1](https://github.com/invernyx/md11-bugs/assets/150375285/54b984c8-fed4-4048-8f93-d1d7ff4c146f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This is a temporary placeholder while the cabin has work done to improve it.

**Comment by captJojo11** [comment]
Alright thanks
