### ISSUE TITLE
[BUG] - Active waypoint in white on ND, T/D arrow in magenta instead

### ISSUE THREAD

**Issue by 717driver** [invernyx/md11-bugs#1287]
### Describe the bug

When flying to a waypoint where the T/D arrow is between your position and the current waypoint it is navigating to, it will display the waypoint on the ND in white and the T/D arrow in magenta.  Both should be in magenta in this case, as your current waypoint will ALWAYS be in magenta. 

### Steps to reproduce

Fly to a waypoint where the T/D is located before you reach the waypoint and it will have the T/D in magenta and the waypoint in white text color. 

### Expected behaviour

Active waypoint will always be in magenta and the t/d arrow should also be in magenta.

### Evidence

![waypoint](https://github.com/invernyx/md11-bugs/assets/49132291/799ba294-4b80-44f9-a5b3-704a9984f34f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL340

### Departure

NZQN

### Arrival

YWLM

### Cruise level

FL340

### ZFW

444.4k lbs

### CG

23.7

### Fuel

32000lbs

### Cost index

150

### Route

BRG1 QN P753 ADKOS P766 TONIM DCT RIKNI DCT SUMSA IVTA1V

### Location

120nm prior to RIKNI, TOD was located just prior to RIKNI

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+
