### ISSUE TITLE
[BUG] - FUEL SYSTEM MANUAL messages does not post (MD-FUEL-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#129]
### Describe the bug

When selecting MANUAL FUEL mode, no FUEL SYS MANUAL amber message posts

### Steps to reproduce

Press fuel system manual button on overhead

### Expected behaviour

S/B FUEL SYS MANUAL amber message posts after selecting manual mode

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37
