### ISSUE TITLE
[BUG] - Symbols drawing below white line on the ND

### ISSUE THREAD

**Issue by ElPadre85** [invernyx/md11-bugs#1291]
### Describe the bug

When increasing the range on the ND, symbols appear below the white line on the bottom of the ND. Boxes left and right are good.

### Expected behaviour

No data shown below the white line

### Evidence

![afbeelding](https://github.com/invernyx/md11-bugs/assets/150356530/119303d7-93c4-4281-bf3a-3eabcc8a03ca)
![afbeelding](https://github.com/invernyx/md11-bugs/assets/150356530/ff9e3682-9c35-4855-a9ac-34ba126317a2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+
