### ISSUE TITLE
[BUG] - Ground pneumatic supply hose misplaced connection

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1292]
### Describe the bug

The ground pneumatic supply hose is not connected at the MD-11 ground pneumatic connection receptacles.

### Expected behaviour

The ground pneumatic supply hose should be connected at the MD-11 ground pneumatic connection receptacles.

### Evidence

![Screenshot 2024-05-29 184424](https://github.com/invernyx/md11-bugs/assets/153389460/26ec9f0a-a489-4ee9-8c18-a227ed2aaf99)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been fixed in an indev version.
