### ISSUE TITLE
FMC incorrectly showing MAX LW 195.0

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1294]
### Describe the bug

FMC displays MAX LW 195.0 in scratchpad when in ER version.

### Steps to reproduce

Load an ER version of the aircraft and fuel above MLW. On entering ZFW in WEIGHT INIT page, MAX LW 195.0 will display in scratchpad.

### Expected behaviour

MAX LW 195.0 will not display due to higher MLW of ER version - instead, if weight was above the MLW of the ER version then the scratchpad would display MAX LW 207.8.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed .56
