### ISSUE TITLE
[BUG] - ELEC PAGE - ADG symbol missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1295]
### Describe the bug

ELEC PAGE - ADG symbol missing 

### Expected behaviour

To have the adg symbol on the elec page 

### Evidence

![Schermopname (600)](https://github.com/invernyx/md11-bugs/assets/150957609/1b1b87c9-4234-4129-8b25-e6a2ce3d67c1)
![Schermopname (561)](https://github.com/invernyx/md11-bugs/assets/150957609/62db9492-a767-412d-9ed5-b880725d990b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.57+
