### ISSUE TITLE
[BUG] - Anti-Ice Manual floating

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1297]
### Describe the bug

Anti-Ice manual light floating above depressed switch

### Expected behaviour

Manual light on switch akin to other manual lights

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/794b0f2d-dfc5-4c81-a69d-48211fb5177a)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this has been fixed, make sure to update

**Comment by KJA1582** [comment]
Yep, .55 did indeed solve that
