### ISSUE TITLE
[BUG] - Waypoint EFOB wrong

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1298]
### Describe the bug

EFOB at Waypoint is calculated higher than it can be

### Steps to reproduce

Fly

### Expected behaviour

EFOB to be at FOb value when passing

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/1981fdc8-e289-4e49-abdc-ee67f51893d1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL380

### Departure

KBOS

### Arrival

KDTW

### Cruise level

FL380

### ZFW

178948 kg

### CG

28.1

### Fuel

20350 kg

### Cost index

80

### Route

[KBOSKDTW_PDF_1717068547.pdf](https://github.com/invernyx/md11-bugs/files/15499955/KBOSKDTW_PDF_1717068547.pdf)

### Location

At CAM

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
We are aware the fuel predictions aren't perfect and will be improved.

**Comment by KJA1582** [comment]
The issue here is more profound, I do know the overall predictions are wonk.
But even then, how can it predict I should have 4t _more_ than I have on bord while being on top of the waypoint?

**Comment by GenericNerd** [comment]
Agreed

**Comment by TheFightingRaven** [comment]
Fuel predicitions update when passing a waypoint. Predicted number is calculated at beginning of leg, because the predictions are off number is too high and above actual fuel weight at the end of the leg. THis is however as designed (we have no reason currently to recalculate before the next leg) with improved predictions this should fully disappear

**Comment by KJA1582** [comment]
@TheFightingRaven 
![image](https://github.com/invernyx/md11-bugs/assets/2170028/1b943de3-e0cd-45da-ae4b-233a160c7b5b)
Great example. No prediction logic ever would be able to hold up on an 1:16 leg without adjustments in between.

**Comment by KJA1582** [comment]
@TheFightingRaven Update it did.
Before passing
![image](https://github.com/invernyx/md11-bugs/assets/2170028/a18da3f7-3ea7-44a1-8336-1de72b9cdeec)
After passing
![image](https://github.com/invernyx/md11-bugs/assets/2170028/0921a5f3-26b0-498f-bcd9-c06124dc4ff1)
Without a pass
![image](https://github.com/invernyx/md11-bugs/assets/2170028/acdd7174-b1ef-4c7c-b606-632cb600dab5)

I encourage to keep this open and in view, even with better predictions coming, something is considerably off.

**Comment by KJA1582** [comment]
@TheFightingRaven Newest version (0.59) with the improved predictions.
I am stationary on Ground at my departure

That is the first waypoint which would open the VERT REF page. The issue at hand is **not** fixed (it seem worse).
![image](https://github.com/invernyx/md11-bugs/assets/2170028/a544a4d4-6208-4d66-9f7d-5b6f6fc07026)

The new fuels and times on the init page suffer the same issue
![image](https://github.com/invernyx/md11-bugs/assets/2170028/9767cc90-113c-4694-9357-e4a3fc8f5af6)

**Comment by KJA1582** [comment]
And now on climbout, 3nmi before passign that waypoint having just passed the one before
![image](https://github.com/invernyx/md11-bugs/assets/2170028/0eb7606d-f799-4eb6-8656-bdf2418421c0)


Please, revisit this.

**Comment by KJA1582** [comment]
@TheFightingRaven I think I found at least part of the issue

![image](https://github.com/invernyx/md11-bugs/assets/2170028/c76fc6c0-3630-48fb-aa52-369b571bd87b)
It displays in LBS, not KG.

**Comment by GenericNerd** [comment]
Open a new issue @KJA1582

**Comment by KJA1582** [comment]
https://github.com/invernyx/md11-bugs/issues/1368 Done
