### ISSUE TITLE
[BUG] - Tail Tank low pressure message does not post (MD-FUEL-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#130]
### Describe the bug

With zero lbs fuel in tail tank and selecting ALT PUMP ON, no message posts

### Steps to reproduce

Ground
Ground PWR ON
Set zero lbs fuel in tail tank
Activate ALT TANK PUMP

### Expected behaviour

S/B TAIL ALT PUMP LO and TAIL L/R PUMP LO in amber messages post

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37
