### ISSUE TITLE
[BUG] - Path Deviation on DES PERF MCDU page

### ISSUE THREAD

**Issue by 717driver** [invernyx/md11-bugs#1300]
### Describe the bug

vertical path error shows 0 HI and 0 LONG when the path is way below the airplane.  I am full deviation above the PROF path and it is showing 0 hi and 0 long still.  

### Steps to reproduce

Overfly TOD, path shows zero error above path when full deflection above PROF path.  

### Expected behaviour

Should show correct deviation from the path whether it's HI or LO, and LONG or SHORT

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/49132291/699c0a24-b792-4d70-ba2d-079fd778324b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

18000

### Departure

ywlm

### Arrival

ypqm

### Cruise level

FL190

### ZFW

383.8k lbs

### CG

27.9

### Fuel

28000lbs

### Cost index

75

### Route

UBSON V535 NICLA V652 PMQ

### Location

60nm south of PMQ VOR

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Confirmed, but duplicate
