### ISSUE TITLE
[BUG] - AC and GEN ARM lights illuminated with engines running (MD-EPS-25)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1306]
### Describe the bug

With engines running and ELEC SYS in AUTO, the blue ARM lights illuminate on AC TIE 1, 2 & 3 and GEN 1, 2 &3.

### Steps to reproduce

Engines running
ELEC SYS AUTO
Observe overhead panel

### Expected behaviour

S/B blank... ARM light illuminates when on APU and ground power only.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by Dimples82** [comment]
That is correct.
On the Ground there are still several bugs at the ELEC Panel. #1118

**Comment by turbofandude** [comment]
Resolved as of 0.61+
