### ISSUE TITLE
[BUG] - Electrical System staying operational without any power sources

### ISSUE THREAD

**Issue by Leonsgame** [invernyx/md11-bugs#1309]
### Describe the bug

The electrical systems remain operational without anything powering it

### Steps to reproduce

Disable all 3 generators
Disable all AC / DC bus ties
Disable emergency power
Switch off the battery

### Expected behaviour

All systems powered by electrcity should shut off due to not getting any power

### Evidence

![Microsoft Flight Simulator - 1 37 19 0 31 05 2024 18_47_09](https://github.com/invernyx/md11-bugs/assets/150516020/74a26421-b02e-4b1c-aef4-8033d8bf9d90)
![Microsoft Flight Simulator - 1 37 19 0 31 05 2024 18_47_16](https://github.com/invernyx/md11-bugs/assets/150516020/b365edaf-a915-4453-874b-eb913d748da9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

33000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.61+
