### ISSUE TITLE
[BUG] - AUX Tank low pressure message does not post (MD-FUEL-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#131]
### Describe the bug

With zero lbs in AUX TANKS and selecting AUX XFER PUMP ON, no messages post

### Steps to reproduce

Ground
Ground PWR ON
Set zero lbs fuel in tail tank
Activate AUX TANK PUMP

### Expected behaviour

S/B AUX LWR L/R PMP LO, AUX UPR L/R PUMP LO, AUX LWR PUMPS LO and AUX UPR PUMPS LO amber messages post

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
partially verified v0.37.  Still no AUX LWR L/R PMP LO, AUX UPR L/R PUMP LO messages post.
