### ISSUE TITLE
[BUG] - Lateral control authority with AFS engaged (MD-AFS-12)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1315]
### Describe the bug

With AP ON, the airplane will not roll more then 10 degrees (usually only 5) when commanding changes in heading or selecting NAV (selecing bank angle limit to any setting makes no difference)

### Steps to reproduce

AP ON
Select heading bug +/- 45 degrees from current heading
Select HDG SEL
Observe AP commanded bank angle

### Expected behaviour

AP commands bank to match FD bars per whatever bank angle limit is selected on the MCP

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

10k

### Agreement

- [X] Yes

**Comment by scotsgod** [comment]
Can confirm this happened to me today

**Comment by turbofandude** [comment]
Resolved

**Comment by FreakyD777** [comment]
verified
