### ISSUE TITLE
[SUGGESTION] - Add left/right MCP interaction similar to push/pull

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#1316]
### Is your feature request related to a problem? Please describe.

Current clunky and unweildy cockpit interaction model.

### Describe the solution you'd like

Add cockpit interaction for turning dials left/right similar to the recently added push/pull interaction.
A single click turns the dial 1 unit left/right whereas a click and hold turns the dial continuously until no longer holding the left mouse button.
Scrolling for rotating dail should also still be possible but have scroll accelleration added.

This will greatly improve cockpit interaction and bring it on par with other addons.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by GenericNerd** [comment]
This can already be achieved through scrolling the mouse wheel on the wheel itself you wish to modify. Doing this would add development time for little to no gain.
