### ISSUE TITLE
[BUG] - Button/light too many on the glareshield 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1317]
### Describe the bug

Button/light too many on the glareshield 

### Expected behaviour

To not have that rectangle button on the left and right hand side of the glareshield 

Lufty however did have another button in that area but was sized like the abs disarm and engine fail button but I have no idea what it's for 

### Evidence

![Schermopname (606)](https://github.com/invernyx/md11-bugs/assets/150957609/85ea162b-c2f7-4061-8df0-c6f42492f396)
KLM
![image](https://github.com/invernyx/md11-bugs/assets/150957609/4fc4ad1e-a63a-4822-ab47-63f1fd5e5b1f)
Lufthansa
![image](https://github.com/invernyx/md11-bugs/assets/150957609/15ef8e92-2805-461c-88b9-e6907062fd04)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
@jhattermann what reference was used for this button?

**Comment by jhattermann** [comment]
Check "needed info 6-xx-2x" (I forget the date) in the reference folder for glareshield photos, these lights are present in that aircraft

**Comment by TheFightingRaven** [comment]
how much of a pain is it to remove it, given it has no function? @jhattermann

**Comment by jhattermann** [comment]
It wouldn't be a pain, but what if we used that for an alternate "go around" button rather than an arbitrary mouse rectangle on the glareshield?

**Comment by TheFightingRaven** [comment]
if it isn't a pain I'd prefer to have it look right and have the arbitrary clickspot tbh

**Comment by jhattermann** [comment]
We can do that then if everyone else agrees

**Comment by turbofandude** [comment]
Resolved
