### ISSUE TITLE
[BUG] - Missing spoiler/speedbrake animation sounds

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1318]
### Describe the bug

When moving the speedbrake handle there is no sounds

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.59+
