### ISSUE TITLE
[BUG] - No gpu transfer sounds when switching to the GPU

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1319]
### Describe the bug

When turning on the battery and turning on the GPU, there is no sounds difference. Is this normal?

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I don't believe the busses can be heared closing in the cockpit
