### ISSUE TITLE
[BUG] - Fuel temp incorrect (MD-FUEL-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#132]
### Describe the bug

Fuel temp shows 5C (cannot change it to F), OAT 14C

### Steps to reproduce

Ground
Ground PWR ON
OAT 14C

### Expected behaviour

S/B fuel temps equal to OAT when starting flight on ground

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37.... and the temp slowly changes over time if you change OAT in situ... nice!
