### ISSUE TITLE
[BUG] - Autopilot disconnect warning missing when powering up

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1321]
### Describe the bug

Autopilot disconnect warning missing when powering up

### Steps to reproduce

Put battery to on, use ground power or start up APU 

### Expected behaviour

When either APU or GPU bus is put to on the autopilot disconnect warning should sound 

https://youtu.be/rjf9sMh-GDY?si=AVLS7AM6Db1UwcgI&t=93

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version

**Comment by turbofandude** [comment]
Resolved
