### ISSUE TITLE
Will not push flightplan from EFB to CDU with a SID at OERK/RUH

### ISSUE THREAD

**Issue by FelixFeltersnatch** [invernyx/md11-bugs#1324]
### Describe the bug

I was unable to push a flightplan that had a SID while in Riyadh. However, removing the SID allowed the flightplan to be pushed from the EFB to the CDU

### Steps to reproduce

Program the RESA1K SID for RWY33R at OERK/RUH.

### Expected behaviour

The flightplan should be SID/STAR agnostic and push from the EFB to the CDU regardless.

### Evidence

![Screenshot 2024-06-01 093605](https://github.com/invernyx/md11-bugs/assets/50430284/4edc483f-56f8-4c86-a7f6-693cec29539f)
![Screenshot 2024-06-01 093824](https://github.com/invernyx/md11-bugs/assets/50430284/265701f9-73e1-4ae9-84d6-4cdb3afc61cb)
![Screenshot 2024-06-01 094038](https://github.com/invernyx/md11-bugs/assets/50430284/64bf3c85-a19a-4130-a6b8-985e910ba4bc)
![Screenshot 2024-06-01 095127](https://github.com/invernyx/md11-bugs/assets/50430284/1bd0e0f5-f8de-4a46-8aae-3d633db68d9e)
![Screenshot 2024-06-01 142711](https://github.com/invernyx/md11-bugs/assets/50430284/86673db1-e3b8-41ff-a7c7-d4efe2cc1110)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

2053' agl

### Departure

OERK

### Arrival

ZSPD

### Cruise level

FL310

### ZFW

183989kg

### CG

15.7% MAC

### Fuel

96750kg

### Cost index

200

### Route

RESA1K RESAL T533 RAPMA/N0510F290 Y214 KUTNA M440 MIDGU/N0506F310 M440 TULBU N881 RASKI L639 AAE/N0506F330 L639 BPL A791 CEA B465 CTG A599 CHILA/N0503F350 A599 LINSO/K0932S1070 A599 SGM A581 WHA R343 SASAN SAS91A ZSPD/35R

### Location

OERK, Cargo Stand #4

### Agreement

- [X] Yes

**Comment by FelixFeltersnatch** [comment]
> What is your simBrief username?

JailbaitAJ

The FPLN worked when I took away the SID and went DCT KIA (rest of route unchanged).

**Comment by GenericNerd** [comment]
Have you updated your flight plan on simBrief to get it to work?

**Comment by FelixFeltersnatch** [comment]
> Have you updated your flight plan on simBrief to get it to work?

Fabio, I've said it twice already. A. this flight was on Saturday and b. I did get it to fly correct when I got rid of the RESA1K SID.

**Comment by GenericNerd** [comment]
If you didn't save a state and have since changed the flight plan, it will be extremely difficult to replicate.

**Comment by FelixFeltersnatch** [comment]
D

> If you didn't save a state and have since changed the flight plan, it will be extremely difficult to replicate.

I do not use the save state, so what is the course of action then?

**Comment by GenericNerd** [comment]
We'll attempt to recreate it, but if we're unable, we may close the bug.
