### ISSUE TITLE
[BUG] - Box Rising runway threshold

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1328]
### Describe the bug

Box rising runway should start at 430ft to 500ft

### Expected behaviour

Box starting rising at 430ft to 500ft to meet FD at 0ft RA instead of starting at 100ft

### Evidence

Wolrd Vol 3, AUTO-30.23
![image](https://github.com/invernyx/md11-bugs/assets/2170028/9dbe30e4-665c-4bae-96b0-7f82cb89e8e9)

Saudi Vol 3, Section INST Page 24
![image](https://github.com/invernyx/md11-bugs/assets/2170028/03eaf743-4ff5-4af2-a8a9-f70f8110bd3b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Octal450** [comment]
Checked more FCOM's. 430ft is correct. Second screenshot looks like an older copy of the manual.

**Comment by turbofandude** [comment]
Resolved in 0.63+
