### ISSUE TITLE
[BUG] - Emergency Light message does not post (MD-LIGHTS-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#133]
### Describe the bug

With EMER LT switch in the OFF position, no message posts

### Steps to reproduce

Ground
Ground PWR ON
Set EMER LT switch to OFF position

### Expected behaviour

S/B EMER LTS DISARM in amber message posts when EMER LT switch is in the OFF position

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by 017941** [comment]
> ### Describe the bug
> 
> With EMER LT switch in the OFF position, no message posts
> 
> ### Steps to reproduce
> 
> Ground
> 
> Ground PWR ON
> 
> Set EMER LT switch to OFF position
> 
> ### Expected behaviour
> 
> S/B EMER LTS DISARM in amber message posts when EMER LT switch is in the OFF position
> 
> ### Evidence
> 
> _No response_
> 
> ### Simulator
> 
> Microsoft Flight Simulator 2020 (MSFS)
> 
> ### Crash
> 
> No
> 
> ### Phase of flight
> 
> Pre-flight
> 
> ### Altitude
> 
> Ground
> 
> ### Agreement
> 
> - [X] Yes

November 27, still there is no associated message when the emergency light switch is in the off position.

**Comment by joon44** [comment]
I recall theres also EMER LT ON message with the switch in the ON position?

**Comment by 017941** [comment]
Yes, the message is for “emer light on” and “emer light off”, but no
message when armed. Thank you.

**Comment by 017941** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/148719444/04de8722-9b67-4a84-a34e-80e46e95245c)

**Comment by 017941** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/148719444/887b1210-7bad-47ab-a6b6-394726edce11)

**Comment by GenericNerd** [comment]
This will be added in the next systems release

**Comment by FreakyD777** [comment]
Verified
