### ISSUE TITLE
[BUG] - Gear Warning System Test not possible

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1330]
### Describe the bug

It is not possible to perform the GEAR WARNING SYSTEM TEST as there is no clickspot to pull the gear handle down and out of the detent.

### Steps to reproduce

Try pulling gear handle down and out when on ground. Notice there is no clickspot to do so.

### Expected behaviour

A clickspot to perform the gear warning test.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.59+
