### ISSUE TITLE
[BUG] - Can't tune ADF

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1332]
### Describe the bug

It is not possible to tune and ADF on the NAV RAD page. 

### Steps to reproduce

Press NAV RAD in the FMS and try to enter either an ADF frequency or identifier. 

### Expected behaviour

To be able to tune an ADF. The page is also supposed to say ADF1/FREQ for ADF 1 instead of ADF 1 and ADF2/FREQ for ADF 2 instead of RV.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/95483637/87d49ddb-0d40-47e7-98c4-0f95e049cdc6)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

35000

### Departure

KORD

### Arrival

EBBR

### Cruise level

FL350

### ZFW

436.9 LB

### CG

31%

### Fuel

47.5 LB

### Cost index

100

### Route

EBAKE DCT WISMO DCT POSTS DCT PADDE DCT SVM Q907 SIKBO DCT MIVOK DCT IPTOS DCT BAREE N687A JANJO/M083F330 NATX SOVED/N0480F350 DCT MORAG DCT NUCHU L607 BIG/N0495F290 Q70 VABIK/N0435F230 Q70 KOK

### Location

ITVIP

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+

**Comment by 09tir98** [comment]
This does not seem to be fixed in 0.62. Nothing happens when trying to tune an ADF on the NAV RAD page in 0.62.

**Comment by turbofandude** [comment]
Apologies, you're correct - it's fixed in 0.63+
