### ISSUE TITLE
[BUG] - Minimum maneuvering speeds missing on APPROACH page

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#1333]
### Describe the bug

The minimum maneuvering speeds are blank on the APPROACH page

### Steps to reproduce

Look at the APPROACH page in flight, with all init pages filled. 

### Expected behaviour

Minimum maneuvering on the APPROACH page.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/95483637/10844e9f-30a9-4bab-9f42-2a30948c9bd7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

7000

### Departure

KORD

### Arrival

EBBR

### Cruise level

FL350

### ZFW

436.9 LB

### CG

28.3%

### Fuel

31.6 LB

### Cost index

100

### Route

EBAKE DCT WISMO DCT POSTS DCT PADDE DCT SVM Q907 SIKBO DCT MIVOK DCT IPTOS DCT BAREE N687A JANJO/M083F330 NATX SOVED/N0480F350 DCT MORAG DCT NUCHU L607 BIG/N0495F290 Q70 VABIK/N0435F230 Q70 KOK

### Location

Approach

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
resolved
