### ISSUE TITLE
[BUG] - Apparent dependency between several cockpit lights

### ISSUE THREAD

**Issue by jhattermann** [invernyx/md11-bugs#1334]
### Describe the bug

FCP flood light does not turn on unless integral lighting is also on; overhead flood knob appears to control MIP flood; no overhead flood

### Steps to reproduce

Scenario 1:

Load aircraft with electrical power supplied and all cockpit lighting off
Rotate FCP flood knob to full brightness without touching integral knob (the base)
Observe no lighting until knob base is rotated past 0

Scenario 2:

Load aircraft with electrical power supplied and all cockpit lighting off
Rotate MIP/PED flood knob to full brightness
Observe no lighting until overhead flood light is rotated past 0

### Expected behaviour

FCP flood should work regardless of the state of its integral lighting; MIP/PED flood knob should control lighting on the main panel and pedestal; OVHD flood knob should illuminate the overhead panel from bulbs above each clearview window. 

### Evidence

Will try to upload a screen capture later

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#400

**Comment by turbofandude** [comment]
Resolved as of 0.60+
