### ISSUE TITLE
[BUG] - Exterior back cockpit windows

### ISSUE THREAD

**Issue by DylanisMaybeRad** [invernyx/md11-bugs#1336]
### Describe the bug

The framing around the cockpit windows shouldn't have sharp corners on them. Rather they should be rounded corners

### Expected behaviour

As a clairification, I am not a CE Customer and I do not have any immediate access to the MD-11 until the official launch.

The framing on the large back windows on the MD-11 have rounded corners, not the sharp ones currently present in the exterior model

### Evidence

Credit to mikko34 (Mikko) on the discord server for the in sim close up shot
![DALCN_5mikko](https://github.com/invernyx/md11-bugs/assets/171629167/d23339d7-e504-4449-89ca-2f4096fec4ab)
 
 they should have more of a rounded corner
![1](https://github.com/invernyx/md11-bugs/assets/171629167/04131a2a-7792-4710-bc80-eb84fc8133f1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by DylanisMaybeRad** [comment]
I now realize that this really isn't a bug, more of a suggestion. I do apologize,

**Comment by FreakyD777** [comment]
good catch

**Comment by jhattermann** [comment]
I am planning to replace the entire cockpit window frame area with a high detail version

**Comment by DylanisMaybeRad** [comment]
> I am planning to replace the entire cockpit window frame area with a high detail version, and will kindly ask Aaron merge it into the exterior model

Beautiful, cannot wait to see it! best of luck,

**Comment by jhattermann** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/105667840/5a3a3d46-c2fa-4b91-a027-814fbfcc8282)

New windshield, wipers and glass will be included with the next art update
