### ISSUE TITLE
[BUG] - MCP/FGS flood light only illuminates MCP panel with backlight ON (MD-LIGHTS-11)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1338]
### Describe the bug

The MCP/FGS flood light does not cast any light onto the MCP surface until the MCP backlight it turned ON.  NOTE: the flood light bar illuminates, but does not cast any light)

### Steps to reproduce

Set sim to night
Turn MCP/FGS flood light full on
Observe light bar illuminate, no light cast on MCP panel
Turn MCP/FGS PNL light ON
Observe flood light visible

### Expected behaviour

Flood light and panel light work independantly

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.60+
