### ISSUE TITLE
[BUG] - Emergency Power Message does not post (MD-EPS-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#134]
### Describe the bug

After arming EMER PWR, EMERG PWR ON EICAS message does not display

### Steps to reproduce

Ground
BAT ON
EMER PWR switch to ARM

### Expected behaviour

S/B EMER PWR ON amber

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This is in the current build :)

**Comment by FreakyD777** [comment]
verified
