### ISSUE TITLE
[BUG] - WX/T Panel Light Missing

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#1341]
### Describe the bug

WX/T Panel Light Missing

### Expected behaviour

Working

### Evidence

![Microsoft Flight Simulator Screenshot 2024 06 05 - 00 04 28 77](https://github.com/invernyx/md11-bugs/assets/143886762/7f5fc8f9-5e7d-4187-a305-68749e8499fe)
![Microsoft Flight Simulator Screenshot 2024 06 05 - 00 04 57 46](https://github.com/invernyx/md11-bugs/assets/143886762/5e4bd9dd-7753-499b-a869-b93999539396)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Good eye, I had to look back and forth between these images about 30 times before I noticed
