### ISSUE TITLE
[BUG] - A line on capt. side ND

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#1342]
### Describe the bug

A line on capt. side ND

### Expected behaviour

No line

### Evidence

![Microsoft Flight Simulator Screenshot 2024 06 05 - 00 23 44 59](https://github.com/invernyx/md11-bugs/assets/143886762/ea2722b8-2fe8-4312-bd09-781422039897)
![Microsoft Flight Simulator Screenshot 2024 06 05 - 00 23 41 69](https://github.com/invernyx/md11-bugs/assets/143886762/9ed9786b-48e2-40fa-9f23-9c55b489e344)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#620
