### ISSUE TITLE
[SUGGESTION] - Details on fuselage not crisp

### ISSUE THREAD

**Issue by SunKing135** [invernyx/md11-bugs#1344]
### Is your feature request related to a problem? Please describe.

Compared to other aircraft in the hangar the textures on the present MD-11 appear very blur and smushed. It affects fonts, sticker as well as other details such as rivets or overlaps of metal structures

### Describe the solution you'd like

It should be more crisp as is standard for 4k textures in 2024

### Describe alternatives you've considered

If texture quality remains like this, other products with less inner values/quality will have a benefit as users tend to go for eye candy as well as flight physics. It´s both together that make a good product.
![fsscr012](https://github.com/invernyx/md11-bugs/assets/152623434/790e37a0-331c-4404-913e-df783c6309f2)
![fsscr013](https://github.com/invernyx/md11-bugs/assets/152623434/eb1848b7-4466-4efb-91e1-107abf1291ba)
![fsscr014a](https://github.com/invernyx/md11-bugs/assets/152623434/ed3cc602-62ed-45d8-b254-36f97a100220)

### Additional context

I am very sure this will eventually get fixed, but wanted to highlight it nevertheless.

**Comment by arwasairl** [comment]
The rivets will be on a separate texture. However, the texture is already at 4K. The only way to improve clarity the each of the fuselage sections is to go to 8K or split each UV section into more parts, as the texel density of each section is already too high to expand into the sheet. The first option will require all liveries to be redone (an estimated 4 months of extra time is required to do that) and the second option also requires liveries to be redone as well as making the repainting process much more difficult.

We will be improving panel line and screws as they will be separated textures but the fuselage itself will not have 8K textures for the moment. It is simply too much of a time commitment to do such a comprehensive re-work.
