### ISSUE TITLE
Speed restrictions not adhered to.

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1346]
### Describe the bug

On climb out, when levelling off below 10000ft in PROF mode at a FMS cruise altitude of 8000ft, the aircraft doesn’t adhere to the 250kts below 10000ft speed restriction and accelerates to cruise ECON speed.

### Steps to reproduce

Setup a flight that levels off at a FMS cruise altitude below 10000ft, with 250kt restriction below 10000ft checked on the F-PLN page. Takeoff and see the aircraft accelerate to cruise speed in PROF mode rather than restrict itself to 250kts. Of note, on descent the aircraft doesn’t restrict itself to the descent restriction of 245kts below 10000ft.

### Expected behaviour

Aircraft adheres to speed restrictions using PROF mode.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

N/A

### Arrival

N/A

### Cruise level

FL080

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
insufficient information to reproduce, if it happens again please open another report with screenshots, flightplan etc
