### ISSUE TITLE
[BUG] - cockpit clipping through outside

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#135]
### Describe the bug

on the outside view an object is clipping through the external model

### Steps to reproduce

look at the left side of the cockpit from the outside

### Expected behaviour

.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/65e84436-417c-4d58-8698-aabe137c670b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Reportedly fixed in the next update
