### ISSUE TITLE
[BUG] - Unable to edit trans alt

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#1351]
### Describe the bug

Unable to edit trans alt in perf page 

### Steps to reproduce

.

### Expected behaviour

Ability to edit 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

.

### Arrival

.

### Cruise level

.

### ZFW

.

### CG

.

### Fuel

.

### Cost index

.

### Route

.

### Location

.

### Agreement

- [X] Yes

**Comment by joon44** [comment]
![Screenshot_20240605_160304_Drive](https://github.com/invernyx/md11-bugs/assets/102414406/e685f3d9-7c44-48e3-91aa-3254dade6bad)
![Screenshot_20240605_160237_Drive](https://github.com/invernyx/md11-bugs/assets/102414406/c6d195bc-3615-47c8-95aa-841b35fff895)

**Comment by Riiiiin3180** [comment]
ohhh 
I see
But the trans alt in China has a bit wrong so is it a problem of navigraph?
