### ISSUE TITLE
GEN 1,2 and 3 ARM lights do not illuminate post APU start

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1353]
### Describe the bug

After APU start on ground from cold and dark load, the GEN 1,2 and 3 ARM lights do not illuminate

### Steps to reproduce

Start from a cold and dark load and do the cockpit preparation. After APU start the GEN 1,2 and 3 ARM lights will be observed to illuminate.

### Expected behaviour

The GEN 1,2 and 3 ARM lights should illuminate post APU start.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

on ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved
