### ISSUE TITLE
[BUG] - TCAS traffic relative altitude uses wrong altimeter data to determine traffic altitude

### ISSUE THREAD

**Issue by MD-82** [invernyx/md11-bugs#1354]
### Describe the bug

TCAS traffic is read from MSFS true altitude and compared to own ship indicated altitude. Creating error.

### Expected behaviour

If two aircraft at the same FL or altitude, the TCAS should reflect this. It is the age-old problem of MSFS's new altimeter reporting issue. The MD-11 is comparing my own ship indicated altitude with the traffic's MSFS reported true altitude. I have a friend flying the MD-11 behind me at the same FL340 on VATSIM. However, he shows as +15 as in FL355. When looking at Volanta Statistics Data, both him and me have a true altitude of 35,500 feet. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by MD-82** [comment]
![V8jq4zxmbp](https://github.com/invernyx/md11-bugs/assets/166976015/25ededba-0646-4556-b8bc-b596911d9470)
![WhatsApp Image 2024-06-05 at 19 48 40_6092a081](https://github.com/invernyx/md11-bugs/assets/166976015/9347adce-37ba-4193-880e-cc894d00684c)

**Comment by turbofandude** [comment]
https://github.com/invernyx/md11-bugs/issues/1496
