### ISSUE TITLE
[BUG] - Engine sounds should filter with increasing TAS

### ISSUE THREAD

**Issue by turbodeas** [invernyx/md11-bugs#1355]
### Describe the bug

Due to the change in air density, the sound of the engines should change as the plane gains altitude and speed. TAS (being a function of alt and speed) can be used to modulate a low pass filter - as the plane climbs, the filter should close, and at altitudes >20k or so, all that should be heard is a bass rumble of the engines.

### Steps to reproduce

Perform flight, climb to cruising altitude. Note that the engine sounds do not change.

### Expected behaviour

The engine sounds should gradually and smoothly have a filter applied with increasing TAS, so that at cruise all you can hear is a bass rumble - this is the vibrations being transmitted through the fuselage.

this effect should be present throughout the cabin.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
improved in the next version
