### ISSUE TITLE
[BUG] - cockpit hole

### ISSUE THREAD

**Issue by mrdyer10** [invernyx/md11-bugs#1356]
### Describe the bug

hole in cockpit ceiling when cockpit door is open 

### Expected behaviour

expect not to see this

### Evidence

![issue-3](https://github.com/invernyx/md11-bugs/assets/152104889/109ef85c-55fd-4158-bc2e-9c917050fd75)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Edit your title

**Comment by jhattermann** [comment]
See #1302
