### ISSUE TITLE
[BUG] - potential duplicate waypoint drawing on ND

### ISSUE THREAD

**Issue by mrdyer10** [invernyx/md11-bugs#1358]
### Describe the bug

duplicate waypoint drawing in ND

### Expected behaviour

zooming in or out one can see some waypoints show as duplicates on top of each other

### Evidence

![issue-1](https://github.com/invernyx/md11-bugs/assets/152104889/577e129e-7ea9-4e5c-b6d1-1a43ea54e804)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by MD-82** [comment]
Not sure, however from the pic it seems that one is the waypoint and the other is the autotuned VOR. They are not duplicate waypoints as I see only one star.

**Comment by GenericNerd** [comment]
Edit your title

**Comment by TheFightingRaven** [comment]
as the user discribed above, this is an autotuned VOR and waypoint over eachother
