### ISSUE TITLE
[BUG] - UNABLE TO LOAD FLIGHTPLAN

### ISSUE THREAD

**Issue by Nekulturny** [invernyx/md11-bugs#1359]
### Describe the bug

Simbrief import failed

### Steps to reproduce

Simbrief ofp_id=1717640890_4F3E8565A3
Route LFMN BODR7A BODRU UM616 NOQAS DCT LERGA DCT FOUCO DCT MANAK UT183 BAGAD DCT LARLA DCT RATKA DCT LEKVA DCT ADARA DCT 51N020W 51N030W 49N040W 48N050W DCT NICSO N209D TAGRA DCT MIILS Q907 ATENE DCT OBTAX Q824 YUL DCT CYMX

### Expected behaviour

Flightplan imported succesfully.

### Evidence

![failed](https://github.com/invernyx/md11-bugs/assets/89014862/26898110-9ccc-4015-8f5d-95a89b2620e6)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

LFMN

### Arrival

cymx

### Cruise level

320

### ZFW

186,986 kgs

### CG

Unknown

### Fuel

74,704 kgs

### Cost index

20

### Route

LFMN BODR7A BODRU UM616 NOQAS DCT LERGA DCT FOUCO DCT MANAK UT183 BAGAD DCT LARLA DCT RATKA DCT LEKVA DCT ADARA DCT 51N020W 51N030W 49N040W 48N050W DCT NICSO N209D TAGRA DCT MIILS Q907 ATENE DCT OBTAX Q824 YUL DCT CYMX

### Location

LFMN ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
@turbofandude is this the issue you resolved yesterday?
