### ISSUE TITLE
[BUG] - EVAC Guard prevents turning system OFF instead of ON

### ISSUE THREAD

**Issue by MD-82** [invernyx/md11-bugs#1360]
### Describe the bug

EVAC system panel red guard has a slot, that when down, allows the switch to be moved only to OFF or ARM. In the SIM, setting the guard prevents the movement to OFF. Instead, you can move the switch to ON. The switch moves through the guard switch texture to ON.

### Expected behaviour

The logic should be reversed. Activating the guard should allow OFF or ARM instead of ON or ARM. Also, if possible, instead of blocking guard movement in the ON position as it is now, closing the guard switch with the switch ON should mechanically move the switch from ON back to ARM.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#718 #710 #1009 #1140
