### ISSUE TITLE
[BUG] - Sudden Performance Drop

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1362]
### Describe the bug

Sudden inexplicable drop in Performance.

### Steps to reproduce

Setup Flight
[EDDHKORD_PDF_1717663010.pdf](https://github.com/user-attachments/files/15612750/EDDHKORD_PDF_1717663010.pdf)

Setup INIT page by replacing all init values with those from the flightplan

### Expected behaviour

Not that drop

### Evidence

[PERFISSUE.json](https://github.com/user-attachments/files/15612745/PERFISSUE.json)

![image](https://github.com/invernyx/md11-bugs/assets/2170028/80518191-9701-4dab-82e6-c6281b8367db)

Shortly after takeoff, performance restored
![image](https://github.com/invernyx/md11-bugs/assets/2170028/48bca0d2-7c01-4b8e-bc20-af89e7cbab1e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
@turbofandude can't recreate this myself. Any idea?

**Comment by KJA1582** [comment]
@TheFightingRaven this might be irrelevant by now.
The Manipulators was most likely my machine since it never came back up.

the high execution time (relative to before) is something I had spoken about with Collin directly.
