### ISSUE TITLE
[BUG] - S/C constraint at wrong place

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1363]
### Describe the bug

S/C constraint at wrong place, both visually and logically

### Steps to reproduce

Setup route as in the PDF
/S320 on EMLON

### Expected behaviour

S/C Arrow should be on ELMON
S/C Pseudowaypoint should  be scheduled with the satem ETO as ELMON since the points coincide

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/1ff52cab-40f8-41b8-8ebd-08cf89f3fb51)
[SCPOS.json](https://github.com/user-attachments/files/15614295/SCPOS.json)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL300

### Departure

EDDH

### Arrival

KORD

### Cruise level

FL300

### ZFW

183464 kg

### CG

20.3

### Fuel

85450 kg

### Cost index

80

### Route

[EDDHKORD_PDF_1717663010.pdf](https://github.com/user-attachments/files/15613072/EDDHKORD_PDF_1717663010.pdf)

### Location

WPT OLGER

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
it is wrong but not in the way you describe, entering a /s999 as a vert ref functions as a restriction, the up arrow should be before the entered waypoint so that the new waypoint is reached at the constrained waypoint

**Comment by KJA1582** [comment]
Hm.
![image](https://github.com/invernyx/md11-bugs/assets/2170028/d7781db8-6025-4289-8d0b-4965574dcca8)

Reads differently but I suppose from a logical view it would make sense.
IIRC, every other aircraft has the S/C coincide with thewaypoint the constraint was set upon

**Comment by turbofandude** [comment]
Should be resolved as of 0.62+
