### ISSUE TITLE
[BUG] - S/C not pushed along with aircraft

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1364]
### Describe the bug

S/C does not get pushed along with the aircraft

### Expected behaviour

S/C to be pushed along

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/06b79c55-d8f4-4dc2-b997-006000b29c56)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/2170028/d335130f-831a-48a5-9afc-9bf47d5105f4)

**Comment by turbofandude** [comment]
Should be resolved in 0.62+
