### ISSUE TITLE
[BUG] - S/C not auto climbing when overflown before dialing up the altitude

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1365]
### Describe the bug

S/C is not pushed with the aircraft (see https://github.com/invernyx/md11-bugs/issues/1364), S/C is not automatically executed after dialing up the altitude after having overflown

### Steps to reproduce

Plan S/C with /S constraint
Overfly WPT without dialing up altitude
Overfly more waypoints afterwards (see https://github.com/invernyx/md11-bugs/issues/1364)
Dial up altitude

Following FCOM guidance:
Pull ALT knob, AC climbs
Reengage PROF, AC descends due to not having reorderd the INIT levels
Re cruise manually triggers https://github.com/invernyx/md11-bugs/issues/1277

### Expected behaviour

![image](https://github.com/invernyx/md11-bugs/assets/2170028/d27b192a-f0b1-4b06-a442-88f4a4fce980)

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/0c41ea42-986d-4660-8273-6d3e7916dcc2)
![image](https://github.com/invernyx/md11-bugs/assets/2170028/37f23302-b0f2-4eba-9b84-366601fd778a)

Pulling knob does not set INIT page CRZ levels accordingly
![image](https://github.com/invernyx/md11-bugs/assets/2170028/a7c81b68-533b-49c3-b763-23473125cd80)

Subsequent press of PROF
![image](https://github.com/invernyx/md11-bugs/assets/2170028/5fb377a2-8220-4ec0-bc4c-6de05283702d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL300

### Departure

EDDh

### Arrival

KORD

### Cruise level

FL300

### ZFW

183464 kg

### CG

25.1

### Fuel

80650 kg

### Cost index

80

### Route

[EDDHKORD_PDF_1717663010.pdf](https://github.com/user-attachments/files/15613613/EDDHKORD_PDF_1717663010.pdf)

### Location

WPT ODNEK

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved in 0.62+
