### ISSUE TITLE
[BUG] - WPT EFOB in lbs

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1368]
### Describe the bug

WPT EFOB displayed in LBS with aircraft in KGS

### Steps to reproduce

See https://github.com/invernyx/md11-bugs/issues/1298

### Expected behaviour

Units matching

### Evidence

![337252774-c76fc6c0-3630-48fb-aa52-369b571bd87b](https://github.com/invernyx/md11-bugs/assets/2170028/8cd9a290-e4fb-49ce-850f-4a35c6079fdd)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL320

### Departure

EDDH

### Arrival

KORD

### Cruise level

FL320

### ZFW

183464 kg

### CG

29

### Fuel

663000 kg

### Cost index

80

### Route

[EDDHKORD_PDF_1717663010.pdf](https://github.com/user-attachments/files/15637976/EDDHKORD_PDF_1717663010.pdf)

### Location

WPT 5520N

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved
