### ISSUE TITLE
[BUG] - Gear warning horn off button inoperative 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1369]
### Describe the bug

Gear warning horn off button inoperative 

### Steps to reproduce

Land without gear down 

### Expected behaviour

To silence the horn by pressing the button 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
in which circomstance is this, because the gear warning button can't silence the horn if flaps are in landing but gear is not down

**Comment by fugotaro** [comment]
You're correct my bad
