### ISSUE TITLE
[BUG] - Battery Discharge Message (MD-EPS-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#137]
### Describe the bug

After engaging GROUND PWR, BAT DISCHARGE message remains

### Steps to reproduce

Ground
BAT ON
Ground PWR ON

### Expected behaviour

S/B BAT CHARGING message and BAT synoptic graphic in yellow

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by uwiuke** [comment]
turn off and turn on the switch again or twice than the message go away

**Comment by turbofandude** [comment]
This is likely due to EMER PWR remaining on.
