### ISSUE TITLE
[BUG] - Stab trim not in amber on the ground

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1372]
### Describe the bug

Stab trim not in amber on the ground

### Expected behaviour

#1062 As the ticket got closed without it being fixed see comments 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1062 reopened
