### ISSUE TITLE
[BUG] - IRU IN ALIGN - Cyan Alerts (Level 0) missing on the EAD Alert Display

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1373]
### Describe the bug

It's missing the IRU IN ALIGN - Cyan Alerts (Level 0) on the EAD Alert Display when one or more IRU is in alignment mode.

### Steps to reproduce

Start IRU alignment.
Check the EAD Alert Display missing.

### Expected behaviour

The IRU IN ALIGN - Cyan Alerts (Level 0) should appear on the EAD Alert Display when one or more IRU is in alignment mode.

### Evidence

![IRU IN ALIGN](https://github.com/invernyx/md11-bugs/assets/153389460/7ac58f12-65a0-46cb-aedd-27fb8737c8cf)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+
