### ISSUE TITLE
[BUG] - aircraft is unstable at max weights takeoff

### ISSUE THREAD

**Issue by APJR1994** [invernyx/md11-bugs#1375]
### Describe the bug

The aircraft is unstable during takeoff at/near max tow. It porpoises, struggles to get airborne and has crashed on me.

### Steps to reproduce

Taking off from FAOR 03L, full length
TOW 271414
Flaps 19
Sel temp 19 
Trim 9.9 ANU
All speeds and flex supplied by the perf calculator
Packs off takeoff

### Expected behaviour

The aircraft to be somewhat sluggish due to performance but to be able to climb out with porpoising.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150309420/e9bb3213-25fd-4f2d-b7bb-1c0fa3f7f237)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by FelixFeltersnatch** [comment]
Add in the cG bud.

**Comment by TheFightingRaven** [comment]
Identified issue with the stab trim with the new FDE,. solution pending

**Comment by turbofandude** [comment]
Should be resolved in 0.62+
