### ISSUE TITLE
[BUG] - Flight Deck windshields do not allow sun rays to penetrate

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1379]
### Describe the bug

With direct sunlight shining into the F/D, no sun ray is cast on F/D surfaces

### Expected behaviour

Sun ray cast on F/D surfaces, with shadows cast of objects in the ray's path

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/148836830/b525b9c5-8fbc-4f88-b5b5-16c099742170)
![image](https://github.com/invernyx/md11-bugs/assets/148836830/9f103a63-c7da-475f-80bb-dd82345f1f02)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
This appears to be an issue with the exterior model glass material having shadows enabled since it's being rendered on top of the VC. Aaron has been informed of it

**Comment by arwasairl** [comment]
Glass no longer has shadow casts enabled. This has been fixed.
