### ISSUE TITLE
[BUG] - GEN 1/2/3 ARM indication does not illuminate (MD-EPS-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#138]
### Describe the bug

After engaging GROUND PWR, GEN 1/2/3 OVRHD buttons remain blank

### Steps to reproduce

Ground
Ground PWR ON

### Expected behaviour

S/B ARM in blue

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in v0.42.01

**Comment by turbofandude** [comment]
Since resolved

**Comment by FreakyD777** [comment]
This hasn't been corrected yet.
