### ISSUE TITLE
[BUG] - Locked up when programing computer

### ISSUE THREAD

**Issue by FarmerJon1066** [invernyx/md11-bugs#1380]
### Describe the bug

The plane locked up when programing the approach into an airport

### Steps to reproduce

I had external power on, APU firing up, emergency lights armed, beacon on, gps aligning. Imported a flight from simberif, set payload.  Under INIT had everything programed, under TO/APPR had take off programed. In F-Plan got the departure airport programed leaning on rwy 24. On the arrival airport got the pattern of entry selected, hit insert and the game stopped responding to input. 

### Expected behaviour

To insert the approach into the flight computer

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/33970596/226f53f3-e5b2-4a69-963b-d4f5eae075e7)
![image](https://github.com/invernyx/md11-bugs/assets/33970596/5351a98b-56b3-4ff9-9fd2-c6bcfd00ef35)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Departure

MUHA

### Arrival

KIAG

### Cruise level

FL280

### ZFW

402,116LBs

### CG

23% I think

### Fuel

85000LBs

### Cost index

200

### Route

ABAN4A UHA J1 FARKO UL471 IKBIX/N0501F330 Y183 PEAKY Q87 TIRCO/N0500F340 Q87 ZERBO/N0500F330 Q87 VIYAP Q69 RICCS Q103 EMNEM Q71 PSB J59 EXTOL/N0499F340 Q140 HANKK Q935 WOZEE Q917 HOZIR DCT

### Location

MUHA at the gat close to RWNY 24

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
not able to reproduce this, is this once or happening often?

**Comment by FarmerJon1066** [comment]
No, I only notice it "lag" a little on flight planes that are really long when doing the approach side. When I redid that flight plane on the next reload it worked that time. Could of bene a one off thing.
