### ISSUE TITLE
[BUG] - CARGO FIRE TEST - wrong lights illuminate

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1383]
### Describe the bug

when performing the CARGO FIRE TEST there are some wrong lights illuminated at the Cargo Fire Panel

### Steps to reproduce

Power the aircraft.

Set the IRS Mode Selectors to NAV
or
PUSH and HOLD the CARGO FIRE MANUAL TEST Switch 

### Expected behaviour

 HEAT/SMOKE, FLOW DISAG, **_AGENT DISCH LOW_**, and MANUAL TEST lights illuminate.

![IMG_0558](https://github.com/invernyx/md11-bugs/assets/153389460/e85261a0-e17a-4920-a5a4-f4bddd98c289)

### Evidence

As per manual

![Cargo Fire test manual](https://github.com/invernyx/md11-bugs/assets/153389460/16b2722d-4c90-41d4-81ae-a4d85e371d6d)

Current situation (Bug)

https://github.com/invernyx/md11-bugs/assets/153389460/c30d531b-0091-411f-ae77-b4e3a2bef1f7

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+
