### ISSUE TITLE
Possible Power Production Issue (Aircraft thrust output doesn't seem to be correct, underpowered)

### ISSUE THREAD

**Issue by FelixFeltersnatch** [invernyx/md11-bugs#1388]
### Describe the bug

Aircraft unable to takeoff, despite using the calculated Perf figures for the given conditions. The aircraft actually began to rotate about 10kts prior to Vr, eventhough I actually used less ANUs than the CDU suggested (8.1ANU versus the CDU's 8.6). The aircraft, even with full aft column, would not fully rotate.

### Steps to reproduce

Spawn in at HKJK runway 24 (Elevation 5330'), set OAT to 25C and Winds to 170 @ 9kts
Takeoff GW was around 265t
Do not use a Derate
T/O Flap Selector to 21
You can either use 8.1ANU or 8.6ANU, either way, the aircraft will start rotating early, even possibly before V1.

### Expected behaviour

Aircraft should be able to rotate and leave the ground at Vr and have an initial climbout speed of V2+15 or so.

### Evidence

![Screenshot 2024-06-07 093126](https://github.com/invernyx/md11-bugs/assets/50430284/283edfab-12cb-4743-b224-0c3cced9bec4)
![Screenshot 2024-06-07 100802](https://github.com/invernyx/md11-bugs/assets/50430284/62cae352-1e79-4f89-84b9-79acaef04614)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
PW's or GE's?

**Comment by FelixFeltersnatch** [comment]
> PW's or GE's?

PW

**Comment by TheFightingRaven** [comment]
symptom of EPR tuning, not a seperate issue. Will be fixed
