### ISSUE TITLE
[BUG] - Cockpit door from cabin to cockpit missing textures

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1390]
### Describe the bug

The cockpit door from the outside of the cockpit hasn`t have any textures and the cockpit is still visible 

### Expected behaviour

![image](https://github.com/invernyx/md11-bugs/assets/71586114/ae45fda3-af58-48d9-b089-92e61fb16b2a)

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter PW

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved
