### ISSUE TITLE
[BUG] - Flaps sounds missing

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1391]
### Describe the bug

There are no sounds when the flaps is animating

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Duplicate https://github.com/invernyx/md11-bugs/issues/976
