### ISSUE TITLE
[BUG] - Model issue above the cockpit door 

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1393]
### Describe the bug

See pic 

### Expected behaviour

![image](https://github.com/invernyx/md11-bugs/assets/71586114/24303224-b8a2-4a04-85ad-107b5a69d9ab)

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter PW

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Duplicate of https://github.com/invernyx/md11-bugs/issues/1302
