### ISSUE TITLE
[BUG] - Using Direct to stops all animations 

### ISSUE THREAD

**Issue by jim123A** [invernyx/md11-bugs#1396]
### Describe the bug

I was on descent in KJFK needing to take a longer route, since I started my descent a little late and once I got back where I should have been I used the Direct to feature on the FMS and everything just stopped. All the instruments all the switch's, flags, rudder, gear, etc anything that had animations stopped working. The plane still flew and when landing the gear were down just not seen.

### Steps to reproduce

1. Pressed Direct to on the FMS
2. Used arrow keys to find the right wave point
3. Had about a 5-10 sec pause to make sure I would be selecting the right one
4. Used the arrow keys again and before I could do anything else the bug took effect

### Expected behaviour

No animations, PFDs frozen, both in the cockpit and outside, plane still fly's,  

### Evidence

I have a video I took of my attempting to land the plane and as you can see the PFDs are bugged, and when I switch to the outside camera it shows no gear and the plane appears to be hovering.

https://github.com/invernyx/md11-bugs/assets/22551266/d5319b3f-92e4-4104-963c-5c5922c7f4f6

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

13300

### Departure

KLAX

### Arrival

KJFK

### Cruise level

370

### ZFW

Don't remember

### CG

Don't remember

### Fuel

108.6

### Cost index

189

### Route

KLAX/25R N0488F370 DOTSS2 CLEEE DCT PKE DCT DRK J96 SLN J24 MCI/N0486F390 J80 SPI DCT WWODD DCT RINTE DCT KLYNE Q29 WWSHR DCT JHW J70 LVZ LENDY8 KJFK/22L

Using NaviGraph Current AIRAC Cycle at the time 2405

### Location

On the PFD shows roughly where if you compare it to the KJFK ILS 22L Via LENDY8, with a transition of LVZ

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Looks like WASM crash

**Comment by TheFightingRaven** [comment]
that is a wasm crash, what version are you running?
