### ISSUE TITLE
[BUG] - Potentially wrong ILS Identifier and interception behavior

### ISSUE THREAD

**Issue by jyoonPro** [invernyx/md11-bugs#1398]
### Describe the bug

Wrong ILS identifier when entering frequency manually in RADNAV page

### Steps to reproduce

Flight from Newark to Memphis:

1. Enter 111.15/180 for ILS runway 18L approach in RADNAV page when in cruise (possibly closer to Indianapolis)
2. Identifier is shown as IFVJ (Indianapolis)
3. Identifier does not change even when approaching runway 18L but localizer and glideslope shows up normally
4. Plane turns left when capturing localizer

### Expected behaviour

ILS label should be displaye as IEXS (Memphis) when the signal is picked up.

Localizer capture should happen normally.

### Evidence

https://github.com/invernyx/md11-bugs/assets/7097891/fd417c61-8c3d-46c1-a01b-4d8bd944d7b0

(Ignore incorrect values due to this being a replay)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

KEWR

### Arrival

KMEM

### Cruise level

FL360

### ZFW

183,589 kg

### CG

31%

### Fuel

28,631 kg

### Cost index

114

### Route

KEWR/22R DCT PARKE J6 HVQ Q68 RAMRD BLUZZ4 KMEM/18L

Arrival: BLUZZ4 (Transition: RAMRD)
Approach: ILS RWY 18L (Final)

### Location

Entered ILS frequency prior to TOD, around YOCKY and RYANS

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#891
