### ISSUE TITLE
[BUG] - Master warning & master caution lights on when on battery 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1400]
### Describe the bug

Master warning & master caution lights on when on battery 

### Expected behaviour

To stay off 

### Evidence

![Schermopname (624)](https://github.com/invernyx/md11-bugs/assets/150957609/ceb4f522-2b17-422b-8dfe-a73740d9ef96)
https://youtu.be/rjf9sMh-GDY?si=pFLKulqyDJg52ZSP&t=80

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.6+
