### ISSUE TITLE
[BUG] - Slat/Flap sound duration/sync

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1401]
### Describe the bug

When deploying slats/flaps, the associated sound does not match/sync with the slat/flap movement... ie the sound plays for a shorter time then the actual animation

### Steps to reproduce

Extend flaps
Observe sounds vs animation

### Expected behaviour

High Lift sounds should sync/match the surface animation.

Also note, at least on Boeing airplanes, the slat has a different sound then the flaps.  I wasn't able to find any YT vids showing this.  But the slats have a more "wooshy" sound compared to the flaps.  Flaps sound much more mechanical.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
Flaps sound more mechanical on most planes because of the torque tubes that are driving the flaps, can be heard quite well in this: https://youtu.be/3wzS6fn8BA8?si=skbVDxibbcNpFhrT&t=1317

Slats are deployed by cables if memory serves rights on the md

**Comment by turbofandude** [comment]
Should be resolved in 1.0.14+
