### ISSUE TITLE
[BUG] - No firebell during ENG/APU FIRE TEST with emergency power in on 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1402]
### Describe the bug

No firebell during ENG/APU FIRE TEST with emergency power in on 

### Steps to reproduce

Push and hold ENG/APU FIRE TEST switch while only having the battery and emergency power in on 

### Expected behaviour

To hear the firebell go on  

### Evidence

![Schermopname (624)](https://github.com/invernyx/md11-bugs/assets/150957609/96622260-2cac-445d-bbdf-3fdbbdbe4f7b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This was actually due to the right emergency power system not receiving power properly - now resolved
