### ISSUE TITLE
[BUG] - ANNUN LT TEST - Red & amber crosses showing while in flight

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1404]
### Describe the bug

ANNUN LT TEST - Red & amber crosses showing while in flight

### Expected behaviour

To have no crosses while in flight over the PFD, ND, ENG page, etc  

### Evidence

![Schermopname (626)](https://github.com/invernyx/md11-bugs/assets/150957609/09fa6cba-0817-445b-98b9-461ef66c3679)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.6+
