### ISSUE TITLE
[BUG] - ANNUN LT TEST - Operating on only battery power 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1405]
### Describe the bug

ANNUN LT TEST - Operating on only battery power 

### Steps to reproduce

Push annun lt switch 

### Expected behaviour

To not operate due to aircraft not being operational, in my mind only running on battery power is not operational  

### Evidence

![Schermopname (626)](https://github.com/invernyx/md11-bugs/assets/150957609/5a0e6e70-10cb-46c4-b2b0-f9cc7072f3e2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
if the displays are shown, it's operational, optherwise it would say specifically like the others
