### ISSUE TITLE
[BUG] - Cabin altitude warning graphic (MD-ECS-25)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#1406]
### Describe the bug

When above 10k cabin altitude, the red box warning around the altitude is not sized correctly

### Steps to reproduce

At altitude, open OFV
Allow cabin altitude warning to alert
Observe ALT display on the ECS SYN page

### Expected behaviour

Red box should encompass the ALT number completely

### Evidence

![FlightSimulator_2024_06_08_08_48_42_029](https://github.com/invernyx/md11-bugs/assets/148836830/170f4787-8186-421d-af26-a37226f2563e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

FL350

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This has been since resolved
