### ISSUE TITLE
[BUG] - Navdata Restrictions Issue

### ISSUE THREAD

**Issue by OD-Emperor** [invernyx/md11-bugs#1411]
### Describe the bug

Does not seem to be flying the restrictions properly. On two flights now into KMEM and into SBGR the plane was having a lot of difficulty properly flying altitude and speed restrictions.

### Steps to reproduce

KMEM - PXV BLUZZ4 KMEM/18L
 - Did not follow path directly, after passing some waypoints aircraft would believe it's far below correct path, only to pass the next waypoint and think it's above the path.
 - ![KMEM arrival](https://github.com/invernyx/md11-bugs/assets/151532577/b31a775a-0229-4f41-8a7b-f2b2a9cfc9bf)

SBGR - EDMUS EDMUS1A SBGR/10R
- Did not follow path correctly, passed waypoint 2000+ ft above where it should be (below waypoint), passed next waypoint correctly, then commanded speed increase to 330kts mid-STAR at about FL100.
![SBGR arrival](https://github.com/invernyx/md11-bugs/assets/151532577/a213f84b-3a4f-41eb-9946-18a254f6bd31)

### Expected behaviour

Below waypoints should be adhered to correctly, large speed increases should not happen within a STAR.

### Evidence

- ![KMEM arrival](https://github.com/invernyx/md11-bugs/assets/151532577/b31a775a-0229-4f41-8a7b-f2b2a9cfc9bf)
- ![SBGR arrival](https://github.com/invernyx/md11-bugs/assets/151532577/a213f84b-3a4f-41eb-9946-18a254f6bd31)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

FL200 to FL100

### Departure

All happened on arrivals.

### Arrival

KMEM - PXV BLUZZ4 KMEM/18L + SBGR - EDMUS EDMUS1A SBGR/10R

### Cruise level

FL360

### ZFW

Unknown

### CG

Unknown

### Fuel

Unknown

### Cost index

CI 20 into KMEM - CI 171 into SBGR

### Route

KMEM/18R JTEEE5 ODATE DCT MAW DCT ENL DCT HAAYQ QUOTE1 KRFD/07

LIRF/25 ESINO7H ESINO DCT GITRI DCT SUPUX DCT REQIN UM986 BRENA
UA854 ARDAR UR975 ANITI UA302 TURUP DCT 11N020W DCT SEROD DCT ASOBU
DCT 03N025W DCT KODOS UL206 VRI UN401 SIDUR UZ10 EDMUS EDMUS1A
SBGR/10R

### Location

Described above with pictures/diagrams.

### Agreement

- [X] Yes

**Comment by atcogl** [comment]
Also had this with 2 flights with the new build.
PROF doing very odd things.
Vdev scale is all over the place, fully top then fully bottom.
On both flights aircraft was descending to meet profile then started climbing!
After passing a waypoint it seems to get confused as to its path, had lots of rapid descent, then into a shallow climb then shallow descent, then pass another waypoint and the cycle would repeat and end up way too high for the next restriction.

On flight into LFPG on the BIBAX9W STAR the aircraft blew all the restrictions high. The first was a restriction of FL130 or below and it crossed it at FL150, the next waypoint was below FL120 and above FL110 and it crossed it at FL135.
Was using speedbrakes the whole way down as I've grown accustomed to!
Also it was commanding 330kts to FL100 and only set 245kts right at FL100 so was comfortably going much faster than 250 below 10.

Next flight EDDK-EGSS on the HEMEL1E STAR, FMS was predicting crossing LAM at FL265 (not a restriction) but it crossed at FL340 descending at 200fpm.

![20240609_141221](https://github.com/invernyx/md11-bugs/assets/170876718/668729f4-8b67-4b48-a651-acd0a46574bc)


11NM before HEMEL with a crossing restriction of FL220 it was still at FL305 doing 200fpm with the Vdev scale pinned to the top of the scale showing as too low. Had to pull ALT and go full speedbrake to descend at 6000fpm to make it even close to the restriction.

![20240609_141453](https://github.com/invernyx/md11-bugs/assets/170876718/f9e551ca-756e-4764-954c-fede80e802de)


Vdev scale showed as max low all the way until intercepting localiser. At no point in the descent was it accurate.

Had a 220kts speed restriction at UPDUK. Aircraft was at 250kts in FMS Speed and did not command speed reduction to 220 until 1.3NM before UPDUK.

![20240609_142548](https://github.com/invernyx/md11-bugs/assets/170876718/645306ba-1e1d-4516-b4ae-ff996d0bd708)


For me these are all new issues with the latest build that I have not encountered before. PROF was pretty reliable at making restrictions, just needed help with the speedbrakes to keep the speed under control.

**Comment by TheFightingRaven** [comment]
fixed in 0.61
