### ISSUE TITLE
[FEATURE req] - Link CPT and FO EFIS panel with the BARO/RADIO and ALTIMETERS

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1412]
### Describe the bug

-

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
use the proper form for suggestions
