### ISSUE TITLE
[BUG] - Request additional EXT/APU in cockpit sounds

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1413]
### Describe the bug

Hope the sounds of the GPU/APU will improve and be hearable inside the cockpit since there is no busses sounds when switching from EXT to APU power or when startin up the plane from cold and dark when clicking the battery power and then EXT power. Sounds keeps the same

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
from what we know, the busses connecting isn't audible from the cockpit, other ambiance is present(avionics fan etc)
