### ISSUE TITLE
[BUG] - Cockpit sounds like the standby gauges can be heard onthe wingview

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1414]
### Describe the bug

-

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
redundant to #1350

**Comment by arwasairl** [comment]
This is a duplicate as FreakyD777 has mentioned.
