### ISSUE TITLE
[BUG] - PW F  and ERF Simbrief Profiles wong a/c type

### ISSUE THREAD

**Issue by atcogl** [invernyx/md11-bugs#1417]
### Describe the bug

PW F Simbrief profile is MD11 not MD11F

### Steps to reproduce

The Official Simbrief profiles for the PW F  and PW ERF versions seem to be listed as a pax aircraft and thus throws up a "Simbrief aircraft doesn't match MSFS aircraft" error in GSX.
Happens with TFDI house livery and 3rd party liveries.
No issues with the GE profiles.

![20240609_184348](https://github.com/invernyx/md11-bugs/assets/170876718/c250e3fd-75f2-42b2-8946-710d7a001d34)

### Expected behaviour

Aircraft types should match. GE profiles are correct

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the icao code MD11F doesn't exist, both pax and freighters are "MD11", this should however be reflected in the aircraft.cfg
