### ISSUE TITLE
[BUG] - DEF AIL: EFB PERF calc OPT FLAPS

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1421]
### Describe the bug

PERF calc gave OPT FLAPS of 26.1, with 25 being the DIAL-A-FLAP limit

### Steps to reproduce

[KORDKCLT_PDF_1718020334.pdf](https://github.com/user-attachments/files/15766100/KORDKCLT_PDF_1718020334.pdf)

Use this route and weights
Use RWY 10C

### Expected behaviour

Stay within Limits

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/297e7a1c-31fc-4781-a058-9d49865d9889)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
@turbofandude this would be solved by rounding to whole numbers and snapping to 25 or 28 as spoken about before

**Comment by turbofandude** [comment]
Should be resolved
