### ISSUE TITLE
[BUG] - DIR TO triggred DES phase

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1422]
### Describe the bug

DIR TO after takeoff triggered DES pahse. Re-Cruise did not re-engage CLB or CRZ phase

### Steps to reproduce

Takeoff on route, on Manual legt DIR TO LACHN

### Expected behaviour

To stay in CLB phase
PREDs to not get lost

### Evidence

![Screenshot (773)](https://github.com/invernyx/md11-bugs/assets/2170028/323d5c2a-c77b-4469-9095-f8f048a828a7)
![Screenshot (774)](https://github.com/invernyx/md11-bugs/assets/2170028/dd70c321-ef9c-451b-85a5-fdcca48d1756)
![Screenshot (775)](https://github.com/invernyx/md11-bugs/assets/2170028/54765d04-ce8b-4944-a574-707d4ecc8168)
[DIRDES.json](https://github.com/user-attachments/files/15775165/DIRDES.json)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

17000

### Departure

KCLT

### Arrival

KATL

### Cruise level

FL360

### ZFW

167548 KGS

### CG

28.7

### Fuel

15000 KGS

### Cost index

80

### Route

[KCLTKATL_PDF_1718029125.pdf](https://github.com/user-attachments/files/15775116/KCLTKATL_PDF_1718029125.pdf)

### Location

WPT LACHN

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
Upon reaching FL360, the aircraft did switch to CRZ mode.
Only to immediatley draw the T/D 5nmi in front, and switch to DES phase upon overflight of the T/D

**Comment by TheFightingRaven** [comment]
@turbofandude related to disapearing predictions? possibly fixed in 0.62?

**Comment by turbofandude** [comment]
Please retry and re-submit with 0.62+. We fixed several issues surrounding this system.
