### ISSUE TITLE
[BUG] - COCKPIT WINDSHIELD AND WINDOWS FRAMES DETAILS

### ISSUE THREAD

**Issue by PANAM741** [invernyx/md11-bugs#1428]
### Describe the bug

I noticed that the cockpit front windshield frames and side windows frames doesn’t have rivets

### Expected behaviour

Add more detalles like rivets. ALL AIRCRAFT  TYPES

### Evidence

![IMG_5164](https://github.com/invernyx/md11-bugs/assets/71863590/a26e5537-5500-47c9-8580-77b7b4295636)
![cachedImage](https://github.com/invernyx/md11-bugs/assets/71863590/d9cf4c02-a6e7-4f0f-ac6c-2bc79528fdd4)
![IMG_5145](https://github.com/invernyx/md11-bugs/assets/71863590/9ab6a6b5-db04-45cc-84be-1ef39672805a)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1336
