### ISSUE TITLE
[BUG] - NAVIGATION LIGHTS 

### ISSUE THREAD

**Issue by PANAM741** [invernyx/md11-bugs#1430]
### Describe the bug

I noticed that there’re excessive reflections on green and red wing nav lights and under the wings.  White or yellowish nav lights are missing

### Expected behaviour

No excessive reflections on green and red wing nav lights.

White or yellowish nav lights must appear.

ALL AIRCRAFT TYPES.

### Evidence

![IMG_5034](https://github.com/invernyx/md11-bugs/assets/71863590/318d0329-6adf-4a08-aa81-ec73e38a52c1)
![IMG_5163](https://github.com/invernyx/md11-bugs/assets/71863590/b4c304f5-1ba2-46a1-bf47-d62d0e1d149b)
![IMG_5143](https://github.com/invernyx/md11-bugs/assets/71863590/87db8b35-77d4-4f24-8088-58ca0ca93e97)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Should search the open issues first. This been known like since beginning

**Comment by Mets747** [comment]
I really hope the lights are fixed soon, I posted another thread about it too

https://github.com/invernyx/md11-bugs/issues/1243

**Comment by arwasairl** [comment]
As stated, this is a duplicate. It will be fixed but please be patient as I am working on more pertinent issues such as low resolution textures.

**Comment by PANAM741** [comment]
> As stated, this is a duplicate. It will be fixed but please be patient as I am working on more pertinent issues such as low resolution textures.

Thanks!!!

**Comment by Mets747** [comment]
Please add emmisives with textures for the white rear nav lights, beacons, strobes, and navs....the external lighting still needs a lot of work
