### ISSUE TITLE
[BUG] - Horizontal Stabilizer Trim should not move without HYD power

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1431]
### Describe the bug

The Horizontal Stabilizer Trim is hydraulically powered. Without HYD power it should not move.

### Steps to reproduce

Power the aircraft.
All HDY pumps off and all ENG off.
Operate the Control Wheel Trim Switches or the LONG TRIM Handles.

### Expected behaviour

Without HYD power the Horizontal Stabilizer Trim should not move.

### Evidence

Longitudinal Trim System
Longitudinal trim is provided by a two-speed, hydraulically powered adjustable stabilizer. The stabilizer is actuated by two hydraulic motors powered independently by hydraulic systems 1 and 3. Hydraulic system 2 provides backup hydraulic power to the stabilizer through the 2-1 NRMP.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.31+
