### ISSUE TITLE
Aircraft doesn't follow magenta route on SID

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1435]
### Describe the bug

Approaching the last waypoint on the TIARA 1C SID off 34R at RJTT, the aircraft turned the wrong way whilst in NAV mode when the route sequenced to the next waypoint.

### Steps to reproduce

Fly the TIARA 1C RNAV SID from RJTT off runway 34R with an approach programmed to rwy22 back at RJTT via the DATUM transition.

### Expected behaviour

The aircraft should follow the magenta line to the next waypoint.

### Evidence

![20240611125643_1](https://github.com/invernyx/md11-bugs/assets/152972533/2c5420e0-1682-4983-bf33-a7217e544262)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Climb

### Altitude

24000

### Departure

RJTT

### Arrival

RJTT

### Cruise level

FL310

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

0

### Route

RJTT RWY34R TIARA1C then LDA X RWY22 at RJTT via the DATUM transition.

### Location

N/A

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Tested in 0.62, not an issue I could reproduce

**Comment by omega892** [comment]
Just tested again in 0.62 and the exact same issue has happened again - see attached screenshot - shows aircraft turning left instead of following the displayed magenta line.
![20240613094111_1](https://github.com/invernyx/md11-bugs/assets/152972533/cd351279-639f-4748-89f0-0382fc440b21)
