### ISSUE TITLE
ND displays landing runway in wrong location

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1436]
### Describe the bug

The landing runway displayed on the ND is not coincident with the actual runway location.

### Steps to reproduce

Programme a flight from RJTT to RJTT departing RWY34R and arriving RWY22 via the LDA X approach.

### Expected behaviour

The ND to show the correct runway location. The scenario has been tested in other aircraft which display the correct runway location.

### Evidence

![20240607155327_1](https://github.com/invernyx/md11-bugs/assets/152972533/88b630c4-bec5-46c5-8fec-9a8cb291c2c7)
![20240607153411_1](https://github.com/invernyx/md11-bugs/assets/152972533/21b4ace0-c10e-4edb-8862-bc1ef064a09f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Departure

RJTT

### Arrival

RJTT

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

0

### Route

RJTT 34R TIARA 1C to RJTT LDA X RWY22 via DATUM transition.

### Location

On ground and air.

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Just tested in 0.62, did not have this. It is possible that if you were flying for a long time with the same IRU, they have potentially drifted.

**Comment by omega892** [comment]
Have just tested this again in 0.62 and the same thing has happened again - both times this has been on initial load of the aircraft with engines running on the runway so don't think its the IRU thats drifted as RWY34R would also be off. See attached screenshot.
![20240613092759_1](https://github.com/invernyx/md11-bugs/assets/152972533/feccbe94-2d8f-4c73-821c-79d1b46e0615)
