### ISSUE TITLE
[BUG] - APU shuts off after engine shutdown

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1437]
### Describe the bug

See above 

### Steps to reproduce

Taxi in after a flight, Start APU via APU panel, arrive at gate. Hit APU PWR then APU. Shut down engines 

### Expected behaviour

Not to switch off 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Post-flight

### Altitude

0FT

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+

**Comment by turbofandude** [comment]
Resolved in 0.62+
