### ISSUE TITLE
[BUG] -  ATC MESSAGE doesn't go away after reading message

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1440]
### Describe the bug

See above 

### Steps to reproduce

Receive CPDLC message. Read it, 

### Expected behaviour

ATC message to clear after reading it 

### Evidence

![FlightSimulator 2024-06-12 19-47-27](https://github.com/invernyx/md11-bugs/assets/70169249/6198e35a-83ab-49af-8b38-625ad8a75073)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0FT

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
The `ATC MESSAGE` alert will remain on screen so long as there are CPDLC messages that have not yet been viewed / read. Hence, it is likely that you still had at least one outstanding `incoming` CPDLC message (that had not been viewed / read). This applies to logon / logoff / handover incoming messages.

**Comment by TheFightingRaven** [comment]
as Pedro said, likely not a bug, not been reported before
