### ISSUE TITLE
[SUGGESTION] - External Model - Leading Edge 

### ISSUE THREAD

**Issue by PANAM741** [invernyx/md11-bugs#1441]
### Is your feature request related to a problem? Please describe.

All MD-11s have a very small leading edge strake very close to the wingtip, just inboard of the nav light. The TFDI model is missing it.

![IMG_5272](https://github.com/invernyx/md11-bugs/assets/71863590/50603d63-151f-4b75-8b9e-3224a2a0becf)

### Describe the solution you'd like

I suggest to add that leading edge strake for the current model.

### Describe alternatives you've considered

N/A

### Additional context

![IMG_1212](https://github.com/invernyx/md11-bugs/assets/71863590/c2347218-522c-403f-a70a-5deccfb7a76b)

**Comment by jhattermann** [comment]
Uh, this was there originally

**Comment by arwasairl** [comment]
Resolved

**Comment by PANAM741** [comment]
Thank you!
