### ISSUE TITLE
[BUG] - GE & PW ENGINES SPINNER

### ISSUE THREAD

**Issue by PANAM741** [invernyx/md11-bugs#1442]
### Describe the bug

The engine spinner texture for General Electric and Pratt & Whitney engines looks too shiny on the white draw.

### Expected behaviour

Please improve the texture.

### Evidence

![IMG_5271](https://github.com/invernyx/md11-bugs/assets/71863590/95ee0974-43c6-4bd6-a05a-83ef3cfd92c9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This is fixed in an indev version and our liveries will be updated to reflect this soon. Please note that 3rd party liveries will have to be updated manually.

**Comment by PANAM741** [comment]
Thanks
