### ISSUE TITLE
[BUG] - Rudder static dischargers 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1449]
### Describe the bug

Static dischargers on the top part of rudder doesn't move with inputs and lower static discharger doesn't move with lower rudder 

### Expected behaviour

Move with the bit of rudder that they're part of 

### Evidence

![Schermopname (628)](https://github.com/invernyx/md11-bugs/assets/150957609/435ecddb-01bd-4800-a66f-f90426f7554e)
![Schermopname (629)](https://github.com/invernyx/md11-bugs/assets/150957609/c92cc18b-2c59-4bb2-9b39-148424587da7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
They were animated in the model but were not tagged, this may have caused it to not move. In any case, this may have been fixed but some additional testing may be required. Please open a new bug report if this occurs again once the next version goes out to CE.
