### ISSUE TITLE
[BUG] - Engine 2 exhaust louvres missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1451]
### Describe the bug

Engine 2 exhaust louvres missing 

### Expected behaviour

On the left hand side of the the ac there should be an exhaust louvre at the 8 o'clock position on the nose cowl of engine number 2  
(GE & PW) 

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150957609/ab980656-bc97-4664-a4a4-e13478732e9e)
![image](https://github.com/invernyx/md11-bugs/assets/150957609/0f0ca164-8add-4947-a483-efb1dbedc5c0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Fixed for GE, will be fixed on PW at a later time
