### ISSUE TITLE
[BUG] - Missing wheel sounds when operating

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1452]
### Describe the bug

Missing the sounds of the wheels when operating inside the cockpit

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
expert tell me it's not audible from the cockpit
