### ISSUE TITLE
[BUG] - Cockpit from cabin visuals broken

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#1456]
### Describe the bug

From the cabin looking to the cabin the cockpit model is glitchy (F variant with GE engines is this shot taken)

### Expected behaviour

![image](https://github.com/invernyx/md11-bugs/assets/71586114/335ba860-ced9-479b-9917-65fc70b7a49e)

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Fixed in an indev version

**Comment by arwasairl** [comment]
Also, please refrain from opening the same bug report more than once.
