### ISSUE TITLE
[BUG] - Stuck at ”checking for updates” screen after updating Navigraph navdata to 2406

### ISSUE THREAD

**Issue by tomkaare** [invernyx/md11-bugs#1457]
### Describe the bug

After installing 2406 from Navigraph MSFS Stuck at ”checking for updates”. When removing the navdata for MD11 only, MSFS loads normal. 

### Steps to reproduce

Install Navigraph AIRAC 2406 and load MSFS. 

### Expected behaviour

MSFS loading normal after updating navigraph nav data. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
not our issue, I had the same error without updating the navdata
