### ISSUE TITLE
[SUGGESTION] - Add cargo lighting

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1459]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

Add lighting to the cargo hold & possibly make it togglable via the EFB  

### Describe alternatives you've considered

.

### Additional context

.

**Comment by arwasairl** [comment]
This is a duplicate of another report: https://github.com/invernyx/md11-bugs/issues/287
