### ISSUE TITLE
[BUG] - Analog Standby Attitude Indicator Pitch Animation Reversed

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#1460]
### Describe the bug

Using the analog standby indicator, the pitch axis is inverted. Ie pitching the aircraft nose up, the standby attitude indicator will indicate nose down.

### Expected behaviour

Normal ADI behavior

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
This is an odd one, as the ADI animation has not been touched since January-February and it seemed to work normally until recently

**Comment by TheFightingRaven** [comment]
fixed 0.66
