### ISSUE TITLE
[BUG] - FMC Freeze

### ISSUE THREAD

**Issue by HV7572KC** [invernyx/md11-bugs#1468]
### Describe the bug

FMC Freezes in flightprogramming

### Steps to reproduce

Started 5 times now, FMC Freezes on selecting ZWFCG a few times, but now it freezed on selecting POS REF. I wanted to avoid ZWFCG but didnt get there. The first time it froze was on selecting R6 on the FMC so FMC could auto fill the value. This just happened after the latest update.

### Expected behaviour

FMC Freezes, cant push any button anymore. Also all the other systems freeze, cannot change any button, leveler, knob etc. The EFB is usable, but I cannot change the aircraft state also. I can still look around the interior and exterior, FS continues, but most of this precious lady freezes

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

EDDL

### Arrival

KEWR

### Cruise level

FL0

### ZFW

149700 KGS

### CG

31%

### Fuel

64740KGS

### Cost index

88

### Route

not entered yet

### Location

Gate B6 EDDL

### Agreement

- [X] Yes

**Comment by HV7572KC** [comment]
now enroute on a flight out of EIDW to KEWR, tried another airport, and now doing the PW variant on the TFDI house livery instead of the GE variant. I got airborne, and just passed the south of Iceland, but after changing something in the FMC during flight... everything got frozen again. The plane keeps on flying, probably flying the route in FMC, but the FMC and everything else is not usable anymore. I took it manual now, its responding, but dont even here the sound "autopilot" so its probably disengaged now without noticing me. All screens are frozen so I cant notice anyting like speed direction altitude other then which it was before it started to freeze

**Comment by aurumusagi** [comment]
Same problem here. It also froze the entire aircraft, and inserting S/Cs also caused the FMC to freeze.

**Comment by HV7572KC** [comment]
Currently deleted all TFDI stuff, and reinstalled. I'll try another flight. ZWFCG working for the first time. Get back with an update

**Comment by HV7572KC** [comment]
still the same, after takeoff trying to make a change in flightplan, a freezing MD11, This after a fresh install of the MD11

**Comment by TheFightingRaven** [comment]
#1469
