### ISSUE TITLE
[BUG] - WASM crash

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1469]
### Describe the bug

WASM crash on /S constraint entry

### Steps to reproduce

1. Load [FREEZE.json](https://github.com/user-attachments/files/15849478/FREEZE.json)
2. Enter /S350 on YUL
3. INCR range on ND

### Expected behaviour

No crash

### Evidence

StackTrace
![image](https://github.com/invernyx/md11-bugs/assets/2170028/08a1c2df-7c96-417f-ab41-75058187d92a)

Potentially coupled issue: https://github.com/invernyx/md11-bugs/issues/1468

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next build
