### ISSUE TITLE
[BUG] - CTD shortly after departure in P3D

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#1470]
### Describe the bug

P3D freezes shortly after departure

### Steps to reproduce

Spawn onto the runway (pax or freighter), i used P3Ds default KRND, default weather only FSUIPC running for controls
set up weights (I set them to 0) and basic takeoff data (I didn't even input a route), 
configure for departure (v speeds 158, 158, 163; stab trim 6.7, flaps 15)
set speed to 250, heading to runway heading, altitude 12000ft
takeoff and rotate per vspeeds, raise gear and flaps, manual flight
my sim crashed at some 1000ish feet, no button pressed except controls/trim

Happens to freighter and pax with default or custom livery. I have used trim down via yoke switch just prior to the crash.

### Expected behaviour

the plane should depart and fly without crashing the sim (just like it used to before CE update 0.64.0 with the same configuration)

### Evidence

![MD-11 P3D crash](https://github.com/invernyx/md11-bugs/assets/150608109/d7fe9477-5fbc-409c-a703-05ed586bf2f1)

### Simulator

P3Dv5

### Crash

Yes

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
did this happen once, or is it consistent?

**Comment by alxcpt** [comment]
> did this happen once, or is it consistent?

unfortunately consistent. I have tested it with serveral different airports, default and third party (eddm, eddh, egll). Sometimes it crashes shortly after takeoff, sometimes shortly after spawning onto the runway. Until now I could use the MD there.

**Comment by turbofandude** [comment]
Should be resolved in 0.65+
