### ISSUE TITLE
[BUG] - ATS Issue at low speed cruise

### ISSUE THREAD

**Issue by henkhugo** [invernyx/md11-bugs#1477]
### Describe the bug

Auto throttle hunting GE

### Steps to reproduce

select cruise

### Expected behaviour

not hunting

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

FACT

### Arrival

FAOR

### Cruise level

FL360

### ZFW

192286kg

### CG

27.1%

### Fuel

23309

### Cost index

20

### Route

FACT/01 N0476F390 DCT TETAN UZ2 NIBEX NIBE1B FAOR/03L

### Location

at level cruise 

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
during cruise this happens below speeds of M.81, so a workaround for now is to fly faster

**Comment by henkhugo** [comment]
> during cruise this happens below speeds of M.81, so a workaround for now is to fly faster

Then faster it shall be!

**Comment by joon44** [comment]
I also confirm that above M.81 the throttles stabilize.

**Comment by turbofandude** [comment]
I've taken some steps to potentially improve this in 0.66+

**Comment by joon44** [comment]
Still the same on 0.66.
