### ISSUE TITLE
[BUG] - Leave holding without pressing exit on fms

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#1478]
### Describe the bug

The plane only do holding for one time then exist automatically without pressing exit on fms 

### Steps to reproduce

Let it fly a holding and wait

### Expected behaviour

Fly holding continuously until press exit 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

/

### Arrival

/

### Cruise level

/

### ZFW

/

### CG

/

### Fuel

/

### Cost index

/

### Route

/

### Location

/

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1063
