### ISSUE TITLE
[BUG] - V speeds reset

### ISSUE THREAD

**Issue by FoxxenD** [invernyx/md11-bugs#1481]
### Describe the bug

When manually entering takeoff speed in the FMS, they get reset after some time

### Steps to reproduce

Calculate takeoff speeds with the EFB
Enter them in the FMS
Wait until they are reset

### Expected behaviour

Entered speeds should not be reset

### Evidence

Information entered with info from the EFB
![Screenshot_4](https://github.com/invernyx/md11-bugs/assets/32935159/d8e5f868-fee4-4266-9108-7d933d19437f)

After some times, the speeds get reset
![Screenshot_5](https://github.com/invernyx/md11-bugs/assets/32935159/685409d1-0066-4877-b2e1-475241392afe)
![Screenshot_2](https://github.com/invernyx/md11-bugs/assets/32935159/6b399cfa-a164-43a2-b6e9-31d135859e37)

A similar bug has happened before #1212 I haven't flown the version in between so I don't know if the bug was fix

Here is the airplane state after entering the speed again (they have been reset twice after I saved the state)
[VSPEED.json](https://github.com/user-attachments/files/15898816/VSPEED.json)

And the simbrief PDF if needed
[Simbrief PDF](https://www.simbrief.com/ofp/flightplans/UUWWKONT_PDF_1718781326.pdf)

I'm flying in MD-11F, GE engines, with ER and without deflected ailerons
Version : 0.65.0-beta

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

UUWW

### Arrival

KONT

### Cruise level

FL300

### ZFW

167 tn

### CG

Don't know

### Fuel

119.4 tn

### Cost index

200

### Route

UUWW/24 SUNU3D SUNUN M869 RAVKA N50 NUDKO T561 INBAP L263 BESNO T693 TOBMA N87 KOMEK DCT UGMOR T95 EVSET Y86 UPEDU DCT TETNI DCT UVSAS DCT PITOL DCT ATSOT DCT 78N010E DCT 79N000E DCT 80N010W DCT 81N020W DCT 81N030W DCT 81N040W DCT 81N050W DCT 80N060W DCT 79N070W DCT 77N080W DCT 74N090W DCT 68N100W DCT 58N110W DCT WAINN DCT YQL DCT KINZE DCT TWF DCT LAS DCT NATEE JCKIE2 KONT/RUMBL.R26RZ

### Location

Taxiing at the departure airport
![Screenshot_6](https://github.com/invernyx/md11-bugs/assets/32935159/f430c0ab-661f-429c-bff7-522f2599f231)

The aircraft state has been saved while on taxiway M4

### Agreement

- [X] Yes

**Comment by CptUnicorn** [comment]
I think this may have something to do with the Packs Off setting. I just did a Packs On departure and my speeds didn't reset.

**Comment by joon44** [comment]
Hasnt happened anymore with the recent updates

**Comment by turbofandude** [comment]
Should be fixed in new updates
