### ISSUE TITLE
[SUGGESTION] -  Pls add MD11 poster in crew rest or something ty 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1482]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

Add poster pls

### Describe alternatives you've considered

.

### Additional context

![IMG_0597](https://github.com/invernyx/md11-bugs/assets/70169249/6a9e38ce-419d-4100-b334-50a5aaad048b)

**Comment by arwasairl** [comment]
No
