### ISSUE TITLE
[BUG] - Amber stab trim box missaligned

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1486]
### Describe the bug

Amber stab trim box missaligned

### Expected behaviour

Number to stay within the amber box when trimming above 10 units.

The number should be offset right of amber box so when you trim above 10 units it just adds the 1 in the empty left hand half of the amber box, instead moving the whole value 

### Evidence

![Schermopname (638)](https://github.com/invernyx/md11-bugs/assets/150957609/40cc94ec-4e8f-4725-a48a-f5b9f7ce2675)
![ecam_91216](https://github.com/invernyx/md11-bugs/assets/150957609/430b005c-a657-4913-8216-650bece244d1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.67+
