### ISSUE TITLE
[BUG] - DC TIE 3 does not cycle correctly (MD-EPS-15)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#149]
### Describe the bug

In MANUAL ELEC mode, when pushing DC TIE 3 button ON, DC 3 remains OFF and requires setting system to AUTO mode to recover

### Steps to reproduce

Ground
BAT ON
Ground PWR ON
ELEC SYS MANUAL
DC TIE 3 OPEN
DC TIE 3 CLOSED (no change)
Cycle system to AUTO

### Expected behaviour

S/B DC 3 recovers after pusging DC TIE 3 to ON in MAN

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in v0.42.01

**Comment by turbofandude** [comment]
Just tested with other elec changes in 0.61+ and this no longer occurs. Please re-submit if it reoccurs.
