### ISSUE TITLE
[BUG] - TCAS Altitude Incorrect

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#1496]
### Describe the bug

TCAS altitude incorrect - either shows as +xx while aircraft is clearly below, or shows the difference as too little

### Expected behaviour

Difference of altitude is accurate

### Evidence

![afbeelding](https://github.com/invernyx/md11-bugs/assets/150094502/256416fa-0f1f-4394-9335-416271e6775d)
![afbeelding](https://github.com/invernyx/md11-bugs/assets/150094502/6373888f-3381-45fe-b19f-d654808700f1)
![afbeelding](https://github.com/invernyx/md11-bugs/assets/150094502/86618570-b353-4556-95a0-edfbc8fef5b7)
![afbeelding](https://github.com/invernyx/md11-bugs/assets/150094502/35faf3e9-51eb-4a44-9e38-ceca2e4d7e5c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Also note that it gave me an inaccurate RA too

**Comment by turbofandude** [comment]
At attempted solution for this has been implemented in 1.0.6+. Please re-submit if required.
