### ISSUE TITLE
[BUG] - Mode C

### ISSUE THREAD

**Issue by captJojo11** [invernyx/md11-bugs#1500]
### Describe the bug

Transponder Mode C not working on VATSIM

### Steps to reproduce

Checklist Startup, out of EDDB 25R LURO1A Dep
ATC couldn't establish radar contact

### Expected behaviour

Radar Contact with ATC

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by joon44** [comment]
You need to have ALT RPTG turned on also. I'm on .66 now and works fine.

**Comment by TheFightingRaven** [comment]
as stated by joona, alt reporting needs to be turned on
