### ISSUE TITLE
[BUG] - Standby Horizon doing the exact opposite 

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#1506]
### Describe the bug

The standby horizon in analog will turn in an opposite way than the actual flight path

### Expected behaviour

show me the horizon 

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150386027/94671374-9b9d-4070-a743-b55a47bb043e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This was fixed in v0.66 which was released one hour after this bug report was opened.
