### ISSUE TITLE
[BUG] - LOSS CONTROL IN FLIGHT

### ISSUE THREAD

**Issue by CSN328LAX** [invernyx/md11-bugs#1509]
### Describe the bug

AP could not control the aircraft

### Steps to reproduce

At cruising altitude, use MSFS real-time weather and ACTIVE SKY FS.
AP was on, the aircraft swaying violently, and AP disconnect when the plane was out of limit.
<img width="1610" alt="屏幕截图 2024-06-23 232343" src="https://github.com/invernyx/md11-bugs/assets/173620180/c9f5f77c-d1cb-47b3-9436-0c0f3955d603">
![FlightSimulator_2024_06_23_23_12_31_586](https://github.com/invernyx/md11-bugs/assets/173620180/54e4974b-2f41-4ef5-9f07-d96c9ada52dd)
![FlightSimulator_2024_06_23_23_13_04_780](https://github.com/invernyx/md11-bugs/assets/173620180/f497db85-5ff8-4d5a-ba8e-ae5d51edde88)
![FlightSimulator_2024_06_23_23_14_17_240](https://github.com/invernyx/md11-bugs/assets/173620180/fcebe125-56e6-4904-b86a-84ae2d99e0a0)
![FlightSimulator_2024_06_23_23_14_58_235](https://github.com/invernyx/md11-bugs/assets/173620180/d9c9496c-d84c-441c-951c-0b9da925675a)

### Expected behaviour

Airplane shouldn't be like this

### Evidence

N/A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
were the PFD's running at a very low FPS?
