### ISSUE TITLE
[BUG] - BAT indication when emergency power is ON (MD-EPS-17)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#151]
### Describe the bug

In MANUAL & AUTO ELEC mode, when selecting EMERG PWR ON, BAT power remains off and white on ELEC SYN

### Steps to reproduce

Ground
BAT ON
Ground PWR ON
ELEC SYS MANUAL
EMER PWR ON

### Expected behaviour

S/B battery graphic shows green

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in v0.42.01

**Comment by turbofandude** [comment]
Resolved in 0.53+
