### ISSUE TITLE
[BUG] - CTD on exit

### ISSUE THREAD

**Issue by henkhugo** [invernyx/md11-bugs#1515]
### Describe the bug

CTD when exiting to the main MSFS menu

### Steps to reproduce

press ESC, select main menu then crash

### Expected behaviour

Exit to main menu 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
done this countless times, can;t reproduce this behaviour

**Comment by henkhugo** [comment]
Still happening intermittently. Better with RC1.01
