### ISSUE TITLE
[BUG] - GSX Auto door commands

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1516]
### Describe the bug

GSX does not command doors as stated in the 0.66 changelog

### Steps to reproduce

Grab profile from [need-to-know channel ](https://discord.com/channels/589851727373795331/1171980388189618229/1254470388562526332) (23.06.24, 18:16)

### Expected behaviour

Doors to open

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/d40c1b6d-286b-4c86-851d-f9c01b84737d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed, error in gsx profile
