### ISSUE TITLE
[BUG] - Plane banks hard right being perfectly on localizer when arming Approach / Land Mode

### ISSUE THREAD

**Issue by roesti** [invernyx/md11-bugs#1523]
### Describe the bug

When trying to perfom a landing on LEGE RWY19, the plane banks hard right and tries to fly a 360° turn when activating Land / Approach Mode. The plane was perfectly on track / extended centerline. Even after manually taking over, then trying to intercept the Localizer again on a 30° angle and trying to activate approach, it happens again.

### Steps to reproduce

Route: EDDS/25 ROTW5B ROTWE Y126 TUBLO N850 NATOR N869 NINTU UN869 REPSI DCT KANIG KANI2F LEGE/BANOL.I19-Z

Autoflight in NAV and PROF mode until 2500' feet. Airport is MK-Studios LEGE.

Plane was behaving fine until it wants to fly the FMS. On this route, the plane is basically on extended centerline almost 100nm out. Upon activating LAND 10nm out and on 2500ft altitude (speed 180kts), the plane banks 30° degree to the right, trying to fly a 360° though already perfectly aligned on centerline / localizer diamond centered.

### Expected behaviour

Correctly capturing and following the localizer.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

2500

### Departure

EDDS

### Arrival

LEGE

### Cruise level

FL390

### ZFW

345.5 LBS

### CG

28

### Fuel

41800

### Cost index

20

### Route

EDDS/25 ROTW5B ROTWE Y126 TUBLO N850 NATOR N869 NINTU UN869 REPSI DCT KANIG KANI2F LEGE/BANOL.I19-Z

### Location

NASGO Waypoint.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
was the ILS manually tuned?
