### ISSUE TITLE
V1.0 Autothrottle ocillation

### ISSUE THREAD

**Issue by Topofdescent5** [invernyx/md11-bugs#1526]
### Describe the bug

In Autoflight the N1 spools up and down constantly from 26%-109%

### Steps to reproduce

Fly

### Expected behaviour

N1 spools up and down non stop

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

Lsgg

### Arrival

Lszh

### Cruise level

Fl170

### ZFW

167kgs

### CG

31

### Fuel

181kgs

### Cost index

100

### Route

Lsgg-lszh

### Location

Cruise

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1489
