### ISSUE TITLE
[BUG] - low speed protection triggering on final approach

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#153]
### Describe the bug

low speed protection triggering on final approach

### Steps to reproduce

sometimes on approach low speed protection get triggered and it sends it into a nosedive

### Expected behaviour

no attempted murder

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Landing

### Pitch

-

### Bank

-

### Heading

-

### Altitude

-

### Departure

-

### Arrival

-

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

stansted final for 22

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This has been resolved with a rewrite of the speed protection logic, a reduction in general sensitivity, and removal of the ability for it to interfere with autoland. Resolved as of 0.12+
