### ISSUE TITLE
Custom waypoint with dupe name failed to create

### ISSUE THREAD

**Issue by GPUthesteve** [invernyx/md11-bugs#1535]
### Describe the bug

name suggests itself, failure to create custom waypoint when referenced with duplicated navaid such as VORs or NDBs. no matter what direction or distance inserted, the FMS gone blank,

### Steps to reproduce

this video explains it all
https://github.com/invernyx/md11-bugs/assets/89721316/cee8ccba-2224-4f4d-8f97-f8c517311509

### Expected behaviour

the created waypoint from "selected from duped" should just be like "non-duped" one (also included in reproduce video section)

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Pre-flight

### Altitude

77ft MSL

### Departure

KLGB

### Arrival

RJCC

### Cruise level

FL380

### ZFW

129 MT

### CG

20

### Fuel

78.4 KG

### Cost index

44

### Route

KLGB12 HAWWC3 IKAYE DCT RZS DCT BEBOP DCT DACEM DCT 40N130W 46N140W 50N150W DCT DUT G215 NRKEY R220 NANNO OTR1 OBE V6 CHE CHE1 RJCC19L

### Location

KLGB

### Agreement

- [X] Yes

**Comment by GPUthesteve** [comment]
also i see that exact same problem with MSFS version of that also

https://github.com/invernyx/md11-bugs/assets/89721316/e6e5d0fa-6aa7-490b-af77-aba6d7227541

**Comment by turbofandude** [comment]
Since resolved
