### ISSUE TITLE
[BUG] - Cargo doors do not reopen after flight.

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1537]
### Describe the bug

This may be an GSX issue, but on the freighter version at least the upper and lower cargo doors except for the bulk cargo door will not open from the EFB unless I am missing something

### Expected behaviour

After shutdown the doors should all open when commanded to open.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by NightstalkerNOR** [comment]
I am having the same issue. Completed a flight, and after shutdown, with wheel chocks and GPU on the doors will not open. I am able to press the relevant buttons and the immediately respond, but return to "closed" state.

**Comment by JustARaceThing** [comment]
Was able to reproduce this. Something definitely to do with GSX and this plane. First leg I was able to open the door after landing. Deboarded using GSX. GSX shut the door automatically after completing deboarding. Was not able to re open the board for boarding

On the second leg without a sim restart, After landing I was able to open the door again, shut and reopened the door, still worked. Deboarded via GSX and now i can not reopen.

**Comment by CptUnicorn** [comment]
> Was able to reproduce this. Something definitely to do with GSX and this plane. First leg I was able to open the door after landing. Deboarded using GSX. GSX shut the door automatically after completing deboarding. Was not able to re open the board for boarding
> 
> On the second leg without a sim restart, After landing I was able to open the door again, shut and reopened the door, still worked. Deboarded via GSX and now i can not reopen.

Interesting. For me, after one flight I can't open the doors again. Are opening the doors via the EFB on first start, or allowing GSX to do it?

**Comment by TheFightingRaven** [comment]
#1531
