### ISSUE TITLE
[SUGGESTION] - Move "hardwareOverforce" to global options.json file

### ISSUE THREAD

**Issue by richcam427** [invernyx/md11-bugs#1539]
### Is your feature request related to a problem? Please describe.

hardwareOverforce toggling is something that users probably would want to set and forget once, so moving it from the 'livery.options.json' file to the global 'options.json' file would achieve this.

### Describe the solution you'd like

hardwareOverforce to not be a livery-dependent option.

### Describe alternatives you've considered

N/A

### Additional context

This is a global setting in PMDG (+ other) aircraft.

**Comment by turbofandude** [comment]
The hardwareOverforce is in the personal options file.
