### ISSUE TITLE
[BUG] - heading line is not dashed

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#154]
### Describe the bug

the heading line is not dashed

### Steps to reproduce

be in heading mode, always present

### Expected behaviour

the line should be dashed

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/75686e39-abb9-41a0-a3df-0ee6e115aebf)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/31c510a4-a4e4-4523-b8a2-053cfa7d8b1c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next version
