### ISSUE TITLE
[SUGGESTION] - Dual or Single BaroSet selection option in EFB

### ISSUE THREAD

**Issue by Drmartin18** [invernyx/md11-bugs#1546]
### Is your feature request related to a problem? Please describe.

Currently while it is realistic to have the Baro Set knobs be independent in a dual pilot cockpit, it makes it a bit of a challenge when the single flight sim pilot has to change one knob, then move the camera to the other knob to change it to the appropriate setting.

### Describe the solution you'd like

A setting in the EFB to tie the two knobs together so that when one knob is turned the other knob moves would make it much easier for the single captain to match the Baro's. this would also cut the issue of having the engines not throttle down when TOC is reached because one baro is set differently than the other.

### Describe alternatives you've considered

By default, the "B" button in the sim is logged as the "Baro Set" keybind, so pressing it in-flight or on the ground would match both baro's to the current Bero setting at the time of the button press.

### Additional context

I have seen this setting as an option in other airplanes (fenix A320, etc) for the sim

**Comment by turbofandude** [comment]
Baro sync is an option in 1.0.5+
