### ISSUE TITLE
[SUGGESTION] - Provide FLAPS HANDLE INDEX simvar

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#1548]
### Is your feature request related to a problem? Please describe.

This variable is not provided

### Describe the solution you'd like

Provide FLAPS HANDLE INDEX and FLAPS NUM HANDLE POSITIONS variables to the simvar

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by TheEvilToaster** [comment]
Similar issue,  Flap position is not detectable by FSUIPC.   Apps like APL use FSUIPC for scoring flights.
