### ISSUE TITLE
[BUG] - Incorrect initial ECS EICAS messages (MD-ECS-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#155]
### Describe the bug

In MANUAL AIR mode, no APU, AIR SYS 1/2/3 PRES LO and BLEED AIR 1/2/3 OFF messages post

### Steps to reproduce

Ground
AIR SYS MANUAL

### Expected behaviour

S/B AIR SYS 1/2/3 OFF in amber only
BLEED AIR 1/2/3 OFF message only posts when the bleed valve is commanded closed but the associated air system is pressurized by an alternate source (APU or ground air)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This should be fixed :)

**Comment by FreakyD777** [comment]
Not correct in V0.37
