### ISSUE TITLE
[BUG] - PFD ISSUE SIGNIFICANT FPS DROP ON SCREEN

### ISSUE THREAD

**Issue by Viralwhite** [invernyx/md11-bugs#1551]
### Describe the bug

While using the AP, the PFD and other screens appear to have a significant FPS drop. When this happens, the autopilot goes absolutely nuts and manual control is required. This will sometimes last seconds, and other times last minutes. I can seem to consistently reproduce it when flying into KSDF on the MAUDD6 arrival for 17R. In this case, I was parallel to the numbers when it happened and it lasted for approximately 60 seconds and then resolved. I was able to land the aircraft. I'm getting this on almost every flight, but I've been consistently flying into SDF or ATL. Both airports I seem to have the issue. Not sure if this is a conflict with something or another issue. The sim was running at 100fps in this instance and everything else performed fine, just not the screens.

### Expected behaviour

The PFD and other screens should never have this issue. Expected behavior is that it'll always work.

### Evidence

https://streamable.com/qe7pe0

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by 09tir98** [comment]
I have experienced the same thing twice. Both on approach to Dubai. Performance in sim was fine, 30+ fps. But the displays were suttering and the plane was pitching up and down a lot, both with autoflight on, and in manual flight. Resolved itself after 20 seconds or so both times.

**Comment by ValkyPouet** [comment]
Same issue here, it randomly occures during flight for no reasons the displays starts to stutter and the plane become crazy for less than a minute

**Comment by joon44** [comment]
Apparently a Simconnect issue and it happens in other addons too.

**Comment by Viralwhite** [comment]
What I’m struggling with is we have plenty of people in our VA who are not seeing this issue at all and haven’t seen it through the entire CE launch. Me on the other hand, I’ve seen it since day 1, but only now getting around to really doing anything about it because of my schedule. My question is, why is my simconnect causing an issue and not for others? I’ve got a beefy system with plenty of overhead, so I know it’s not that. I’m swine who likes to compare issues like this and I try to use process of elimination. If I can do 10 flights and have the issue on every flight, but my buddy can do 20 flights and never have it, that tells me we have some sort of configuration difference that’s causing it, but correct me if I’m wrong, simconnect can’t be updated in any way?

**Comment by Viralwhite** [comment]
I just want to point out that anytime I fly into KSDF, at some point on the arrival this bug seems to happen. I've tried multiple arrivals and every time this seems to happen into SDF. Did a flight from SDF-MKE and everything was fine.

**Comment by Yttrium89** [comment]
Reported the same issue in TFDi discord and was told it was Asobo's fault and that the issue affects other aircraft, which I honestly struggle to believe based on my own experience. I have had WASM crashes in other aircraft, but never this type of (apparently simconnect) issue -  only with the TFDi MD-11. Honestly this aircraft should not be taken on VATSIM with this issue. I have reproduced this issue on approach to ILS 20R into PAFA (Fairbanks). It always seems to occur when on HDG SEL and near the approach phase of flight. I highly suspect it is dependent on the airport you fly into.

**Comment by Viralwhite** [comment]
I was able to reproduce this error twice this evening. Both times flying from KMKE-KSDF. The issue occurred in the same location both times as well which was between FRIZN and ONCOD on the FRIZN5 arrival, 35L transition. The first flight I did online and the first flight I did offline. Below I've pasted all the information I can provide. I also recorded the second flight from start to finish. In the video, you'll be able to see at the 59m 03s mark, the aircraft begins to oscillate up and down and then it becomes obvious what's going on. I'm only seeing this bug on arrival/departure as it was said above.

**1st Flight**
KMKE-KSDF: UECKR6 DELHI/N0503F290 RAMSE FRIZN5 / 35L Transition / BRBON IAF
Apps being used: vpilot client, TFDI smartcars, FS2FF, FSUIPC and GSX Pro
Issue started after FRIZN but before ONCOD on the arrival

**2nd Flight**
KMKE-KSDF: UECKR6 DELHI/N0503F290 RAMSE FRIZN5 / 35L Transition / BRBON IAF
Apps being used: FSUIPC
Issue also started after FRIZN but before ONCOD on the arrival. 
See video here (Still uploading as of 2244 est 7/5) - You can see the issue at the 59m 03s mark: https://www.youtube.com/watch?v=coSM0lf72vo

**Here is a list of every mod in my community folder - Just in case anyone sees something that's a conflict or can compare to what they have that might be causing the issue.**
aerosoft-airport-edlp-paderborn
aerosoft-crj
Axonos KJAC Jackson Hole
axoonos-kric-richmond-airport
bmworldamsim-koak-oakland
carenado-aircraft-ct182t-skylane-g1000
carenado-aircraft-ct182-skyland-g1000_CVT_
cj4-livery_N171CN
dominicdesignteam-kaus-airport
dominicdesignteam-kindairport
doublet-kphf-airport
drzewieckidesign-chicagomidway
drzewieckidesign-kbfi
drzewieckidesign-kdca
drzewieckidesign-kewr
drzewieckidesign-krnt
ffx-airport-kdpa-chicago
ffx-hjet
flightbeam-airport-kmsp
flightbeam-airport-ksfo-san-francisco
flightbeam-airport-nzaa-auckland
flightbeam-kiad
flyhigh-airport-kisp-islip
flyhigh-airport-kjax-jacksonville
flytampa-amsterdam
flytampagg-boston
flytampa-toronta
fsdreamteam-airport-kclt-charlotte
fsdreamteam-airport-keyw-keywest
fsdreamteam-airport-kiah-houston
fsdreamteam-airport-ksdf-louisville
fsdreamteam-airport-gsx-pro
fsdreamteam-airport-gsx-world-of-jetways
fsltl-traffic-base
fsreborn-fsr500-livery-N27KGDynamic
fsuipc-lvar-module
iblueyonder-airport-kdal-dallas-love-field
inibuilds-a300-f-GE-UPS-149
inibuilds-a300-f-UPS-173
inibuilds-aircraft-a300-600
inibuilds-airport-egkk-gatwick
inibuilds-airport-egll-heathrow
inibuilds-airport-kbuf-buffalo
inibuilds-airport-kdtw-detroit
inibuilds-airport-kjfk-newyork
inibuilds-airport-klax-losangeles
inibuilds-airport-kmke-milwaukee
inibuilds-airport-kokc-oklahomacity
inibuilds-airport-kpsp-palmsprings
inibuilds-airport-ksat-san-antonio
inibuilds-airport-omdb-dubai
inibuilds-airport-omdu-skydrive-dubai
inibuilds-airport-phnl-honolulu
Ither-NoHandleBar
livery-carenado-t182t-n203db
livery-fsr500-n392ma
livery-fsr500-piper-branding
lvfr-kbdl
lvfr-kbwi
lvfr-kfll
lvfr-kmsy
lvfr-ksan
lvfr-kmia
maccosim-mmun
mkstudios-airport-eidw-dublin
mkstudios-airport-klga-laguardia
mkstudios-airport-kphl-Philadelphia
navigraph-navdata
navigraph-navdata-base
noolaero-module-vdgs
orbx-airport-kbur-holywood-burbank
orbx-airport-kcrw-yeager
orbx-pakt-ketchikan
pacsim-kgsp-greer
pacsim-saltlakecity
pmdg-aircraft-77w
pmdg-aircraft-77w-liveries
pmdg-aircraft-737
pmdg-aircraft-737-liveries
pmdg-aircraft-738
pmdg-aircraft-738-liveries
pmdg-aircraft-739
pmdg-aircraft-739-liveries
pyreegue-airport-egph-edinburgh
rwprofiles-airport-ksgf-springfield
simwings-airport-panc-anchorage
skyward-aircraft-da50
stealthyduck-airport-kafw-ft-worth
tfdidesign-aircraft-efb
tfdidesign-aircraft-md11-tfdidesign-aircraft-md11-N260UP
txnsim-airport-khou-houston
verticalsim-airport-kboi-boise
verticalsim-airport-kmyr-myrtle-beach
verticalsim-airport--koma-omaha
verticalsim-airport-kont-ontario
verticalsim-airport-kpie-st-petersburg-clearwater
verticalsim-airport-kpvu-provo
verticalsim-airport-ksyr-syracuse
verticalsim-airport--ktpa-tampa
xbaw-soundset-152
xbaw-soundset-crj
xometry-airport-kmdt-harrisburg
xometry-eaglecounty
xwindstuios-airport-krfd-rockford

**Comment by zazaboeing** [comment]
Same here, on every flight. Multiple times when approaching complex airport sceneries, even with a very decent hardware. Plane is unusable right now.

**Comment by zazaboeing** [comment]
> Apparently a Simconnect issue and it happens in other addons too.

Not on my system, and with hundreds of addons. Only with the md11

**Comment by joon44** [comment]
> > Apparently a Simconnect issue and it happens in other addons too.
> 
> Not on my system, and with hundreds of addons. Only with the md11

Not on YOUR system. Luckily not on my system either. I've had it total of 2 times in over 400 hours of flying it so its very rare to me. BUT I had it many many times with the Leonardo MD82 with only quarter of the time. It has also been reported with the PMDG 737 and 777. Why it happens so much to some people, I dont know.

**Comment by Viralwhite** [comment]
> > > Apparently a Simconnect issue and it happens in other addons too.
> > 
> > 
> > Not on my system, and with hundreds of addons. Only with the md11
> 
> Not on YOUR system. Luckily not on my system either. I've had it total of 2 times in over 400 hours of flying it so its very rare to me. BUT I had it many many times with the Leonardo MD82 with only quarter of the time. It has also been reported with the PMDG 737 and 777. Why it happens so much to some people, I dont know.

What’s strange for me is I have hundreds of hours with the 737 and I’ve never had this issue with it. I just got done doing about 30+ hours of flying with the 777 doing long hauls and also never saw it there. But yet on almost every MD11 flight I have this occur. Not sure if it’s because of different coding or what. I’m also using a high end pc - 13900k with a 4090. Very strange for sure, but it’s good to see more people are having this issue.

**Comment by Yttrium89** [comment]
Btw it would be nice if you could redo that flight you did to reproduce the issue but this time without KSDF scenery and see if that makes a difference. I wonder if this is kinda like how on xbox, WASM aircraft screens go black on approach into heavy third party airports. Considering that this issue seems to be restricted to certain airports, I think its worth a try to see if the scenery mods themselves are causing the issue with the MD-11

**Comment by Viralwhite** [comment]
So I completed another flight and this time without FSUIPC. I was able to reproduce the issue again and in the same location! KMKE-KSDF: UECKR6 DELHI/N0503F290 RAMSE FRIZN5 / 35L Transition / BRBON IAF
Apps being used: FSUIPC
Issue also started after FRIZN but before ONCOD on the arrival.

See video here: https://youtu.be/Up2txrgKZDc

**Comment by Viralwhite** [comment]
I just completed another flight with nothing in my community folder except the MD11, EFB, and UPS livery. The issue occurred again and in the same spot; however, it only lasted 5 seconds. This leads me to believe the issue is exacerbated by a community folder that has more in it. With that said, I'm unsure what more I can really do.

**Comment by joon44** [comment]
I did the same MKE-SDF flight and it didnt happen to me. We really need tfdi to look into it

**Comment by Viralwhite** [comment]
> I did the same MKE-SDF flight and it didnt happen to me. We really need tfdi to look into it

I agree and thank you for taking the time to do that flight and stream it on Twitch. It's unfortunate that you couldn't reproduce it like I could, which makes it even more aggravating. I plan on doing a flight with the PMDG 737 to see if it has a similar issue. I'm also considering deleting my content.xml and .dat files to let the sim rebuild them and see if that cures any issues.

**Comment by TheFightingRaven** [comment]
as stated by others it's unfortunately out of our control, usually it fixes itself by taking manual control and stabilising the plane

**Comment by Viralwhite** [comment]
> as stated by others it's unfortunately out of our control, usually it fixes itself by taking manual control and stabilising the plane

I want to make sure my reply here is not taken out of context or received as rude or disrespectful, but I really do expect better from you guys. While I understand this bug may not be super widespread to the point that your entire customer base is rioting, I would expect that a bug like this would be left open with attempts to see if maybe it could be minimalized or ongoing work with Asobo could be published here on the issue. 

Several of us spent days trying to help reproduce this bug and we found consistencies. There are other 3rd party devs that are having symptoms, but their AP doesn't go absolutely nuts when it happens, just the MD11, so it's less of an issue. I'm not expecting a resolution today, but closing this bug and giving it a status as "not planned" is really defeating for those of us that spent $80 on this product and have been supporting you guys since day 1. I'm CE #90 and I gave you guys a chance. With that said, if this is the expected support and follow up, I will not be a TFDI customer going forward.

**Comment by turbofandude** [comment]
For anyone reading, I'd like to further clarify our stance here: we're absolutely NOT ignoring the issue. We firmly believe the issue is either with the sim itself, or some, unexplained limitation that Asobo has not communicated with us. We've officially opened up a report with Asobo to get to the bottom of it and that report can be tracked here - https://devsupport.flightsimulator.com/t/simconnect-data-read-rate-suddenly-intermittently-drops/9586

**Comment by Viralwhite** [comment]
Here is a flight that was completed with the PMDG 737. If you compare my earlier videos to this video, you'll see the issue occurs at the exact same point as the MD11. What's interesting with this issue is that it happens right at the DECEL point on the flight. 
https://www.youtube.com/watch?v=bJpxpegsMtg

**Comment by Acktu** [comment]
Just happened to me.  PANC Runway 15 PTERS3 STAR.  Lasted for about 90 seconds before it went back to normal.  Video:
https://youtu.be/yyPuxbH9Mnk

**Comment by zazaboeing** [comment]
And to me again, arriving in LOWW now.
