### ISSUE TITLE
Outer ailerons are not moving

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1552]
### Describe the bug

outer ailerons are not moving

### Expected behaviour

They should be mooving I guess

### Evidence

![au](https://github.com/invernyx/md11-bugs/assets/174654712/9098b1ce-8a0a-4143-87b5-dcd6556bc769)

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
he's not in a clean config, outboard ailerons should not be locked

**Comment by turbofandude** [comment]
Resolved in 1.0.7+
