### ISSUE TITLE
Weird strips on PFD

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1553]
### Describe the bug

Artificial horison and alt/speed tapes have strips

### Expected behaviour

Probably should be without

### Evidence

![2024-7-3_22-55-47-353](https://github.com/invernyx/md11-bugs/assets/174654712/7cdd47a0-9864-4a76-9352-a4ece931893d)

### Simulator

P3Dv4

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
symptom of the CRT effect not being rendered well by P3D
