### ISSUE TITLE
Engine display refresh rate

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1554]
### Describe the bug

Poor engine display refresh rate

### Expected behaviour

Smooth change

### Evidence

https://github.com/invernyx/md11-bugs/assets/174654712/cd7535ed-9614-4b99-9cca-9aa3419c30cd

### Simulator

P3Dv4

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
it's a crt from the late 80's it's not supposed to be smooth
