### ISSUE TITLE
High Intensity (strobe) lights flash time

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1555]
### Describe the bug

In interior (VC) model strobe lights have proper sequence and timing of flash. While looking on the model outside it seems to be slower and a little bit accidental

### Expected behaviour

Same timing and sequence in exterior model as in interior model

### Evidence

https://github.com/invernyx/md11-bugs/assets/174654712/87a0191c-cadc-402b-9b67-0c7c98a4b8f3

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by Mets747** [comment]
The external lights are a joke on the MSFS version too

**Comment by turbofandude** [comment]
This should be resolved in 1.0.5+

**Comment by csb005** [comment]
Still not working correctly
