### ISSUE TITLE
[BUG]  Not all aircraft configurations are detected by FSUIPC

### ISSUE THREAD

**Issue by TheEvilToaster** [invernyx/md11-bugs#1556]
### Describe the bug

The Flap position and the Spoiler ARMED/DISARMED is not able to be detected by FSUIPC.      Apps such as APLv2 use FSUIPC for data inputs for aircraft configurations, these two settings are the only ones not being detected by the apps which reads FSUIPC.

### Steps to reproduce

Using APLv2 as an example, opening 'Raw data' will show the current status of the aircraft.  The majority of the aircraft systems are being detected correctly, down to small things like Parking Brake and External Lights status.  But the 'Flap Position' and 'Spoiler Arm' is always shown as 0 and is not being detected.   

APL devs have explained it can only detect what FSUIPC is detecting and the issue should be reported to you instead.

### Expected behaviour

 Flap positon and Spoiler arm status should be detectable, just as all other system statuses currently are.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
#694

**Comment by CptUnicorn** [comment]
Can confirm. I am loosing points on APLv2 lol
![image](https://github.com/invernyx/md11-bugs/assets/150947401/82310e27-0188-48ce-9c77-a813b3fabcfd)
