### ISSUE TITLE
[BUG] - Logo lights light up inside of Number 2 Eng Intake tunnel

### ISSUE THREAD

**Issue by Drmartin18** [invernyx/md11-bugs#1560]
### Describe the bug

When the Logo lights are turned on, the lights illuminate the inside of the number 2 engine intake tunnel.

### Expected behaviour

When the lights are turned on, the Logo on the tail should be illuminated by the logo lights, whereas the intake tunnel should remain dark since the logo lights cannot get inside the cowling

### Evidence

![Screenshot 2024-07-04 002833](https://github.com/invernyx/md11-bugs/assets/174639628/502d1ce1-4d28-4a51-ac4b-0dadb4bdf4cb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
msfs lighting bug, nothing we can do
