### ISSUE TITLE
[BUG] - SPOILER TOGGLE  control bind only increases spoiler extension on consecutive presses

### ISSUE THREAD

**Issue by JustARaceThing** [invernyx/md11-bugs#1561]
### Describe the bug

Using the default " Spoilers Toggle" bind only increases speed brake extension rather than toggling spoilers full on and off

### Steps to reproduce

- Bind spoilers toggle to a button
- Press that button twice
- Observe spoiler lever

### Expected behaviour

If I press the Spoiler Toggle bind it should go to the fullest possible spoiler position at that time (Full in flight or Ground Spoiler on the ground) and my second press should retract the spoilers

### Evidence

https://github.com/invernyx/md11-bugs/assets/114666086/8db316b4-5701-4dc6-8be0-bb56bf4165cd

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
Resolved in 1.0.7+
