### ISSUE TITLE
[BUG] - Bleed system indication and messaging errors 2 (MD-ECS-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#157]
### Describe the bug

In MANUAL AIR mode, APU Air ON, ISO VLVs OPENED, PACK OFF, AIR SYS 1/2/3 PRES LO messages post, bleed system 1/2/3 pressure is 0 boxed amber, bleed system 1/2/3 temp is ambient (10F) boxed amber

### Steps to reproduce

asdf

### Expected behaviour

S/B BLEED AIR SYS 1/2/3 OFF in amber message, PACK 1/2/3 OFF in amber message

### Evidence

Once PACKS are turned on, each PACK 1/2/3 message should clear

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be correct in the current versions. Manual control of PACK buttons causes the appropriate warning. Manual control of the BLEED system causes that warning.

**Comment by FreakyD777** [comment]
correct... my write up was in error
