### ISSUE TITLE
[BUG] - Static dischargers missing/duplicate

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1571]
### Describe the bug

Static dischargers missing/duplicate

### Expected behaviour

Missing: 
Top of RH winglet x2
Above exhaust no.2 x2
Tailcone x2

Duplicate:
Top of rudder 

### Evidence

![Schermopname (690)](https://github.com/invernyx/md11-bugs/assets/150957609/454f12d8-1681-475f-89a6-7b43b1ff5041)
![Schermopname (687)](https://github.com/invernyx/md11-bugs/assets/150957609/f2db7bfa-61c0-48dc-b568-2244e582f2ef)
![Schermopname (686)](https://github.com/invernyx/md11-bugs/assets/150957609/09aff506-d8ea-4caa-a365-d1606cc9e9aa)

![image](https://github.com/invernyx/md11-bugs/assets/150957609/1c44cddc-b985-4aaa-b520-199625d3a401)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1450
