### ISSUE TITLE
[BUG] - Take-off performance: aircraft freezes

### ISSUE THREAD

**Issue by Swisspilot1986** [invernyx/md11-bugs#1575]
### Describe the bug

Open the take-off performance page in the EFT, fill in the fields with your keyboard, next the aircraft completely freezes

### Expected behaviour

The sim continues to work normally, however. I restarted the flight and the sim: same effect. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
wasm crash, can't reproduce via these steps. Is it happening more than once?
