### ISSUE TITLE
[BUG] - mismatch between speedtarget shown and flow

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#158]
### Describe the bug

prof is climbing in a different speed target than displayed

### Steps to reproduce

depart

### Expected behaviour

fly 250 or vcl below 10.000 then econ climb

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/bcaeb2f9-0e1b-4a49-a64f-7ee32dd38e98)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Pitch

6

### Bank

0

### Heading

-

### Altitude

>0 < 10000

### Departure

eham

### Arrival

egss

### Cruise level

240

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Fixed through PROF rewrite in a previous version
