### ISSUE TITLE
[BUG] - Solid heading bug missing on the ground

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1581]
### Describe the bug

Solid heading bug missing on the ground

### Expected behaviour

-

### Evidence

Ref #1172 not fixed 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The bug is present, but it did not properly follow the aircraft heading. It will as of 1.0.6+
