### ISSUE TITLE
[BUG] - PACK and trim performance - full hot (MD-ECS-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#159]
### Describe the bug

In MANUAL AIR mode, APU Air ON, ISO VLVs OPENED, PACK 1/2/3 ON and temp selectors (all) full hot, PACK outlet temp approx 40F, duct outlet temp approx 57F, actual zone temps 134F after 3 mins

### Steps to reproduce

see description

### Expected behaviour

S/B PACK outlet temps go to 50F initially, duct outlet temps go to 90F initially.  As zone temp approaches target temp, PACK outlet temps stabilize at 80F, duct outlet temps stabilize at 85F

### Evidence

These PACK and trim temp numbers were verified with old flight test data I found in the Air Conditioning system description document for the freighter.  Could not find similar data for PAX.  However, the general characteristics should be similar.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Still not fixed in V0.42.01

**Comment by turbofandude** [comment]
Resolved in 0.55+
