### ISSUE TITLE
[BUG] - IRS Flashing again

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1590]
### Describe the bug

I remember in the early builds that the IRS would flash, and as soon as you start taxing, the screens would go blank. All 3 IRS would be flashing on and off. Now it appears they are just flashing and not going out of alignment. Resetting the IRS and realigning appears to fix this issue.

### Steps to reproduce

Set up any flight C&D as you normally would (I have the Load Last state by default)

### Expected behaviour

Not have my IRS flash and potentially go out of alignment in flight.

### Evidence

![20240707074739_1](https://github.com/invernyx/md11-bugs/assets/150947401/7038c9ae-9f21-4033-8c34-f5522f077eec)
![20240707074739_2](https://github.com/invernyx/md11-bugs/assets/150947401/675ebdde-ffae-457e-aaa8-cf33c8de91db)
Ignore the wonky flight path lol. That is posted in #1550
![20240707074742_1](https://github.com/invernyx/md11-bugs/assets/150947401/8c3a902f-677f-4663-abfa-477744817469)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by 09tir98** [comment]
Have had this as well. It only happens if you do a turn around without restarting the sim, or if you load the latest state.

**Comment by turbofandude** [comment]
All of the behavior described here is correct. The IRS provides some data before it's fully aligned, so it's possible you started moving the aircraft before it was done. The behavior described in the initial report of the screens losing data once you start moving is consistent with this theory.

Regarding flashing during a turn/loading last state, the IRUs have a memory of-sorts that knows where they were last. If the aircraft has moved significantly but the state is the same, it will believe the IRSs have been moved and require re-entry of the position to be sure.

**Comment by joon44** [comment]
> All of the behavior described here is correct. The IRS provides some data before it's fully aligned, so it's possible you started moving the aircraft before it was done. The behavior described in the initial report of the screens losing data once you start moving is consistent with this theory.
> 
> Regarding flashing during a turn/loading last state, the IRUs have a memory of-sorts that knows where they were last. If the aircraft has moved significantly but the state is the same, it will believe the IRSs have been moved and require re-entry of the position to be sure.

Load with the last state. Turn off all 3 IRS and turn them back on. Click initialize irs from CDU and see them flashing after the alignment is complete.

**Comment by jyoonPro** [comment]
This also happens during the following sequence: turn IRS 1 on, press INITIALIZE IRS, and turn IRS 2 and 3 on. IRS 1 will align properly, while 2 and 3 will continue flashing. The CDU will show that the remaining time is negative (incorrect behavior).

![image](https://github.com/user-attachments/assets/5d71a597-865c-4d4c-89ae-dbf2c6da2826)

**Comment by turbofandude** [comment]
Finally found and resolved this in 1.0.31+.
