### ISSUE TITLE
[BUG] - Engine startup possible without APU running or ASU connected

### ISSUE THREAD

**Issue by p919h** [invernyx/md11-bugs#1591]
### Describe the bug

Engine start up is possible without any active air source

### Steps to reproduce

I am on MSFS version 1.37.19 and TFDi MD11 version 1.0.1. I have an empty communy folder with only the MD11 installed, without any extra livery.

1. Start cold and dark at any parking spot
2. Turn on battery
3. Turn on external power
4. Turn on igniter A
5. Pull engine start switches behind throttle livers
6. Observe N2 rise in engine display, on all 3 of the engines
7. Open fuel levers at appropriate N2 value
8. Engine starts up and continues to run.

### Expected behaviour

Without APU air or ASU connected, engine start should not be possible.

### Evidence

https://github.com/invernyx/md11-bugs/assets/174953970/17d0b6b4-6a2b-434b-903d-197ad627612f

I have larger video if needed, but cannot upload to github.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

80Ft

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Also starts with APU running without APU AIR

**Comment by turbofandude** [comment]
Should be resolved in 1.0.6+
