### ISSUE TITLE
[BUG] - Autopilot Go-Around too aggressive.

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1593]
### Describe the bug

(Following the events in #1592) I hit the TOGA button to initiate a go around, and the aircraft pitched up to about 25 degrees nose up. (not sure what the real aircraft does) But this seemed a little bit extreme.

### Steps to reproduce

Fly any ILS approach an initiate a a go around by hitting TOGA with the autopilot engaged.

Note: I was not established on the ILS.

### Expected behaviour

To have a smooth positive climb within reasonable limits.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Pitch

around 25 degrees nose up

### Departure

N/A

### Arrival

RKSI

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

RKSI

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
it will go into pitch speed with full thrust for V2+10 this will be high pitch in any case
