### ISSUE TITLE
[BUG] - AFS does not follow the ILS

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1597]
### Describe the bug

When the ILS frequency and course is manually inserted in the NAV/RAD page, the autopilot fails to capture the localizer but rather turn away and the approach must be flown by hand. When the ILS is autotuned, the capture works correctly

### Steps to reproduce

Tune ils frequency and course by hand. Let autopilot try to capture the localizer and observe the events

### Expected behaviour

Capture and follow the localizer same way whether ils is autotuned or manually inserted.

### Evidence

CRS was 264. On capture the AFS made a hard left turn away from the localizer
![q5b00uBTPg](https://github.com/invernyx/md11-bugs/assets/102414406/8b64516c-2e09-466a-a344-389bff681d5b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

LOWS

### Arrival

LIMW

### Cruise level

FL330

### ZFW

160tn

### CG

28

### Fuel

14900kg

### Cost index

31

### Route

LOWS/15 N0486F320 DETS2B DETSA/N0486F330 DCT ASVUT DCT NAXAV DCT LUSIL DCT SRN/N0411F180 L615 OMETO DCT LIMW/27

### Location

OMETO

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#1592
