### ISSUE TITLE
[BUG] - Wipers

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1610]
### Describe the bug

Wipers

### Steps to reproduce

Put to slow/int 

### Expected behaviour

Wiper motor sound
Wipers to have smaller range when on
Wipers to be horizontal when in int

### Evidence

https://youtu.be/inXCwTp2za0?si=gxvHlIADWyb0bMQr&t=2799
https://youtu.be/inXCwTp2za0?si=41Swn-yBRQq7GOaM&t=2979
https://streamable.com/qrvkb5

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Though I'm not denying there _is_ a motor sound, it's barely audible in those videos. That said, our speed and intermittent behavior were definitely wrong. I've corrected those in 1.0.6+
