### ISSUE TITLE
[BUG] - Bulk cargo door missing

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1614]
### Describe the bug

Even while opened in cockpit menu (and with proper information on display) the bulk cargo door remains closed
Affected passenger as well as cargo version

### Expected behaviour

Bulk cargo opening in exterior model
![4b376a9e-8808-4a83-978d-9fac2d0aa3a7](https://github.com/user-attachments/assets/2ffa848d-29e9-43fe-8e0b-c43ee34688af)

### Evidence

Closed despite being open in EFB
![2024-7-12_1-35-21-1](https://github.com/user-attachments/assets/ffd0c051-daca-420a-8cfc-d15aeb8d8489)

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I'm not sure how you have the bulk door option on the EFB, as we've disabled it. The bulk door is not functional in the P3D version of the aircraft at this time.

**Comment by csb005** [comment]
Well...
Pax:
https://github.com/user-attachments/assets/447e7590-9794-46df-a72d-1af75e084660

Cargo
https://github.com/user-attachments/assets/6fa007d7-ac59-4740-9b2b-9fe7bfccd682
