### ISSUE TITLE
[BUG] - RTE RSV FUEL

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1618]
### Describe the bug

Route reserve fuel % will go nuts if you enter the fuel as weight. If inserted as %, it works correctly

### Steps to reproduce

Enter any weight into RTE RSV, observe %

### Expected behaviour

Both ways should work correctly

### Evidence

Entered /3
![image](https://github.com/user-attachments/assets/e2da5eb9-b7dc-4106-bcaf-09fbaa95c50d)

Entered 3
![image](https://github.com/user-attachments/assets/ae0b93f1-8fad-4c84-a547-e5d7d1ebd038)

Entered 0.5
![image](https://github.com/user-attachments/assets/6c65e69f-bf41-4ebe-8ac1-8ade2dc03283)

![image](https://github.com/user-attachments/assets/46760437-9086-4597-8607-f833cbd58df9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

.

### Arrival

.

### Cruise level

.

### ZFW

.

### CG

.

### Fuel

.

### Cost index

.

### Route

.

### Location

.

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.6+
