### ISSUE TITLE
[BUG] - ECS trim switch inoperative (MD-ECS-7)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#162]
### Describe the bug

In MANUAL AIR mode, APU Air ON, ISO VLVs OPENED, PACK 1/2/3 ON trim air switch is INOP, no TRIM AIR OFF message post

### Steps to reproduce

see descrp

### Expected behaviour

S/B trim air switch functional, TRIM AIR OFF in boxed amber message posts and duct outlet temps should match PACK outlet temp and should not change with change in target temp

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed

**Comment by FreakyD777** [comment]
TRIM AIR button works along with the associated message, but the A/C system does not respond correctly still
