### ISSUE TITLE
[BUG] - Guarded OVH Panel switches working with guard locked

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1621]
### Describe the bug

as on the title and clip

### Expected behaviour

It's obvious I think

### Evidence

https://github.com/user-attachments/assets/379463b5-2c84-43ea-90fc-c89d70ad2bf0

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by csb005** [comment]
Occurs in 1.0.7

**Comment by TheFightingRaven** [comment]
restrictions within p3dv4
