### ISSUE TITLE
[BUG] - Fuel disagreement between EFB and Fuel Display System

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1622]
### Describe the bug

When fully fueled the EFB shows different fuel value than Fuel Display in aircraft - related to both passenger and cargo variants

### Steps to reproduce

Fully load the aircraft with fuel via EFB

### Expected behaviour

The values should match

### Evidence

![2024-7-12_17-18-35-766](https://github.com/user-attachments/assets/13a580d6-a403-49a8-8c54-515919b3caec)

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.6+
