### ISSUE TITLE
[BUG] - Altitude Alert System

### ISSUE THREAD

**Issue by N111MD** [invernyx/md11-bugs#1625]
### Describe the bug

Altitude Alert System needs to be fine tuned

### Steps to reproduce

n/a

### Expected behaviour

#1: Altitude Alert is incorrect when capturing the selected altitude. The tone+voice warning should sound at 1000 feet from the selected altitude and not at +/- 150 ft. Also the altitude box should stay steady amber (not revert to flashing at 150 ft) when capturing the selected altitude. Box should then change to steady white when HOLD mode activated.

#2: There should be no warning when changing the selected altitude on the FCP.

(System behaviour is correct when deviating from the selected altitude)

### Evidence

Fom the system manual:

The altitude alert system automatically alerts the flight crew that the aircraft is approaching the preselected altitude or that the aircraft is deviating from a preselected and acquired altitude.

The altitude alert system is always on except when the FD or AP is engaged in the glideslope mode. In this case, the altitude alert system is inhibited.

The altitude alert activates as follows:

• 1,000 feet from the FCP window altitude - PFD altitude box turns steady amber and optional tone.

• If more than 0.12g required to capture FCP window altitude - Steady amber PFD altitude box and tone. Active only on first approach to the FCP window altitude and is inhibited when aircraft is within 150 feet. If more than 0.12g is required to capture the FCP window altitude and that altitude is more than 1000 feet from the current baro-altitude, the PFD altitude box will be flashing amber. This condition requires an initial vertical speed of more than 5200 fpm and is rare.

• Deviation of 150 feet or more from FCP window altitude - Flashing amber PFD altitude box and tone. The flashing amber altitude box will reset when the aircraft returns to the set altitude or a new altitude is selected.

Altitude alerting is not affected by the AFS OVRD switch on the FCP.

NOTE: The tone consists of a C-chord followed by an optional ALTITUDE voice warning.

As an option the altitude alert system is inhibited if the AFS is in glideslope capture mode or flap setting is more than 31.5 degrees (landing).

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

n/a

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.35+
