### ISSUE TITLE
[BUG] - Brightness knob for FMC not working correctly (both passenger and cargo variants)

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1631]
### Describe the bug

FMC brightness knob is just turning it on/off, not changing FMC brightness at all

### Expected behaviour

Possibility to change brightness

### Evidence

https://github.com/user-attachments/assets/e20ff984-4d8f-4f2e-b184-b4f9792dafc0

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.6+
