### ISSUE TITLE
CPDLC doesn't accept digits in station name

### ISSUE THREAD

**Issue by tabugman** [invernyx/md11-bugs#1632]
### Describe the bug

A format error is given whenever a station name has a digit in it

### Steps to reproduce

Enter a station name with a digit in it.

### Expected behaviour

As many Vatsim controllers have a combination of letters and digits in their station names, digits should be accepted.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0 ft - FL400

### Departure

EFRO

### Arrival

ESSA

### Cruise level

FL400

### ZFW

136,989 kg

### CG

31

### Fuel

20,513 kg

### Cost index

50

### Route

EFRO/03 N0479F400 OLNO3B OLNOP DCT XONTU DCT SIPRI T31 HMR HMR5M ESSA/01L

### Location

EFRO

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@tabugman could you share an example of a VATSIM Controller station name that uses a combination of letters and digits for verification? Thanks.

**Comment by tabugman** [comment]
In my case there were several Swedish centres open on Vatsim where the one I needed to talk to used ESO3. There are more examples on Discord from other users who scratched their heads the same way I did.

**Comment by turbofandude** [comment]
Resolved in 1.0.15+
