### ISSUE TITLE
[BUG] - Various AIR system issues

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1636]
### Describe the bug

Engine bleeds show pressure and high temperatures when engines are turned off.  PAX selector has amber dashes instead of white. EAD showing AIR ISOL ON but the respective button has no ON light when in AIR SYS AUTO mode. Pack and cabin temperatures start at 0c when loading the plane and start slowly increasing to ambient temperature

### Steps to reproduce

Power up the plane by turning on the battery, external power and set emergency power to ARM. Switch to AIR SD and observe readouts. If you do this fast enough, you can see the pressures increasing. Bleed temperatures show 80C despite it being 26C outside.Have only some engines running and notice how ISOL EAD messages dont match with the respective overhead button lights

Observe ISOL lights, pressures, temperatures with engines off and running. 

### Expected behaviour

1) Bleed pressures rise only with engines running
2) Bleed temperatures match the ambient temperature
3) PAX loadout shows white dashes when selected 000
4) ISOL valve button lights reflect the valve status in AUTO mode. In MANUAL mode they work correctly.
5) Pack and cabin temperatures to match the ambient temperature at loading the plane,

### Evidence

All engines off, bleed pressures 33-35 PSI, bleed air temperatures 80-85C
![image](https://github.com/user-attachments/assets/cc8c52cb-49c7-4d99-93df-5c6757e276bb)

All engines running and bleeds turned off --> Pressures correctly drop to zero.
![image](https://github.com/user-attachments/assets/19388ebf-1e48-49b9-ad4e-60a1569aa16f)

![image](https://github.com/user-attachments/assets/201e90ac-5d8d-495b-9f62-2d37a456f63e)

![image](https://github.com/user-attachments/assets/e0587b52-82e6-4ecd-9466-31650816c77e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

200

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.035+. Amber dashes for pax selector are correct per two different documents we have.
