### ISSUE TITLE
[BUG] - IGN A, B and OVRD should all be selectable at the same time

### ISSUE THREAD

**Issue by MCCVeen** [invernyx/md11-bugs#1659]
### Describe the bug

When either Ignition A or B is selected and you select the other, the other gets deselected. This is incorrect. Same goes for selecting the ignition override.

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

![image](https://github.com/user-attachments/assets/37780fec-21a1-4646-996d-795cdabf3354)

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.35+
