### ISSUE TITLE
[BUG] - Autoland FMA modes should not be displayed with AP off

### ISSUE THREAD

**Issue by MCCVeen** [invernyx/md11-bugs#1663]
### Describe the bug

None of the Autoland FMA modes, like DUAL LAND, SINGLE LAND, ALIGN, FLARE, ROLLOUT or LOC and G/S in green will be displayed. Only LOC, G/S and APPR ONLY in white.

### Steps to reproduce

-Set up for an ILS approach with autopilot engaged.

-Disengage AP when any autoland mode is engaged between 1500-400ft RA.

-FMA should revert back to LOC G/S APPR ONLY in white

### Expected behaviour

-

### Evidence

![image](https://github.com/user-attachments/assets/3608608c-520e-4c2c-a76d-4fdc597f912b)

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Landing

### Departure

-

### Arrival

-

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by csb005** [comment]
![2024-10-8_22-23-32-995](https://github.com/user-attachments/assets/46553da2-7e2e-4742-9a1b-e6eab4e861b6)

**Comment by turbofandude** [comment]
Will be resolved in 1.0.34+
