### ISSUE TITLE
[BUG] - Level 2 Alerts text misaligned with box

### ISSUE THREAD

**Issue by MCCVeen** [invernyx/md11-bugs#1669]
### Describe the bug

Level 2 Alerts text are misaligned with the box they're in.

### Expected behaviour

-

### Evidence

![image](https://github.com/user-attachments/assets/0031dbbf-b19e-4028-a1b6-a8c49a8768c6)
![image](https://github.com/user-attachments/assets/d7a2bee7-839f-40ec-b54c-6ea74c9fe0fd)
![image](https://github.com/user-attachments/assets/c9bbcea2-eecc-46c0-bb73-039b26b8e3a0)

### Simulator

P3Dv4

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.25+
