### ISSUE TITLE
[BUG] - Outflow Valve not responsive (MD-ECS-12)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#167]
### Describe the bug

In CABN PRESS MANUAL mode, the outflow valve is unresponsive to cabin press inputs (climb/desc)

### Steps to reproduce

see descrip

### Expected behaviour

S/B in manual mode, the OFV should be controllable via the CLIMB/DESC knob

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.60+
