### ISSUE TITLE
[BUG] - RETRACT SPD BRK alert during derotation

### ISSUE THREAD

**Issue by MCCVeen** [invernyx/md11-bugs#1680]
### Describe the bug

The RETRACT SPD BRK alert is incorrectly shown during derotation and clears up once the nose strut is compressed. This logic is incorrect. RETRACT SPD BRK should only be shown in-flight.

### Steps to reproduce

-Land with spoilers armed

-Touchdown with main gear first

-RETRACT SPD BRK will appear as auto-spoiler extends the spoilers untill nose gear strut is compressed.

### Expected behaviour

-RETRACT SPD BRK will only be shown in-flight. So as soon as the main gear struts are compressed this alert should be inhibited.

### Evidence

![image](https://github.com/user-attachments/assets/53cdcd59-7ab6-4c34-9859-27aef8e0ad35)

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Landing

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.15+
