### ISSUE TITLE
[BUG] - Aileron/Rudder trim indication (MD-FC-9)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#169]
### Describe the bug

When inputting aileron and/or rudder trim, the associated trim indicator does not move.
(see MD-FC-12 and MD-FC-13 for additional trim bugs)

### Steps to reproduce

see descrip

### Expected behaviour

S/B indiator moves right/left as right/left aileron/rudder trim is added

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#14
