### ISSUE TITLE
Pulling HDG SELECT knob deselects PROF mode.

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1690]
### Describe the bug

When in PROF mode, if you pull the HDG KNOB it deselects PROF mode.

### Steps to reproduce

In the climb with NAV and PROF engaged, pull the HDG KNOB and see that PROF mode deselects.

### Expected behaviour

If you go into HDG select, PROF mode should remain engaged.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Pitch

N/A

### Bank

N/A

### Heading

N/A

### Altitude

N/A

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.11+
