### ISSUE TITLE
Pressing PROF mode does not engage FMS SPEED

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1691]
### Describe the bug

After takeoff, if you press the PROF button above 400ft agl, it should also engage FMS SPEED, but the speed mode remains as selected.

### Steps to reproduce

Having taken off without PROFILE armed, press PROF at 500ft agl and note that FMS speed does not engage.

### Expected behaviour

Pressing PROF mode after takeoff >400ft agl should also engage FMS Speed. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Takeoff

### Pitch

N/A

### Bank

N/A

### Heading

N/A

### Altitude

N/A

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.11+
