### ISSUE TITLE
FMS Speed incorrect on ground

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1692]
### Describe the bug

On the ground before engine start, if you complete the FMC setup and then select FMS SPD, the speed on the PFD does not correspond with the FMS speed displayed on the CDU.

### Steps to reproduce

Complete the FMC setup for a flight using FMC computed takeoff speeds and then select FMS SPEED and note the disparity between the magenta V2 speed and the FMS speed. 

### Expected behaviour

I'd expect the FMS SPD to be the FMC V2 speed but cannot find any reference for this but there is still a disparity between the FMS computed V2 speed / the pilot edited V2 speed and the FMS Speed shown on the PFD. In the pictures below, you can see the FMS speed as 159 but the FMC calculated speed is 160kts.

### Evidence

![20240724174709_1](https://github.com/user-attachments/assets/1bf77196-5139-417f-8994-33260d3eee86)
![20240724174712_1](https://github.com/user-attachments/assets/dc077a90-a0bd-42fd-b583-991f86868b0e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Pitch

N/A

### Bank

N/A

### Heading

N/A

### Altitude

N/A

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.11+
