### ISSUE TITLE
[SUGGESTION] - Show physical throttle position on N1 display

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1693]
### Is your feature request related to a problem? Please describe.

Quote directly from Discord user teropa

"This airplane is difficult to land. And it becomes even more difficult when you try to guess your physical thrust lever position before releasing the ATS. Even if it's off by couple of %, speed tends to easily run and then you end up in an unstable approach very very fast. What could alleviate this is if we could see on the N1 indicator where the physical lever is positioned, and then before ATS disconnect the levers could match what the ATS was using. Graphically it could be a small T shaped indicator on blue color."

### Describe the solution you'd like

PMDG has a similar feature with following options: always/never/only when moving.  This can be a togglable option in the EFB. Especially the option to show the throttle position marker only for a brief moment when it is moved is very handy as it doesnt need to be shown all the time. I think it can be a similar T to the plane's own thrust indicator moving along on the same scale. I believe the data can be retrieved directly from the sim. This would be an extremely handy option to match the throttles with the actual thrust before disconnecting the ATS.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by turbofandude** [comment]
Added in 1.0.30+
