### ISSUE TITLE
[BUG] - V1 showing white on PFD despite being FMC computed

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#1694]
### Describe the bug

V1 showing white on PFD despite being FMC computed Changes from magenta to white Reconfirm v1, moment later white again cr.: teropa79 

### Expected behaviour

V1 remains magenta when FMC computed and pilot confirmed

### Evidence

![image](https://github.com/user-attachments/assets/9343a775-9ffb-4463-8f4c-599103c961b5)
![image](https://github.com/user-attachments/assets/7e4dcb7b-63b9-491f-b54b-9cc63672a506)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Appears to only be V1 that does this

**Comment by turbofandude** [comment]
Resolved in 1.0.11+
