### ISSUE TITLE
Shutting down Engine #2 stops APU start.

### ISSUE THREAD

**Issue by omega892** [invernyx/md11-bugs#1695]
### Describe the bug

Having begun APU start up on taxi in, if you then shut down Engine #2, the APU shuts down.

### Steps to reproduce

After landing, on taxiing in, start the APU then when APU N1 is around 45%, shutdown Engine #2 and note that APU also shuts down.

### Expected behaviour

The APU would continue to start up as per normal procedures. From the system description either the 2 have to be separated (you cannot shut down engine number 2 whilst the APU is running up) or there s a problem between the login of AC and DC fuel pumps for the APU and that shutting down engine number 2 turns off the DC fuel pump to fuel tank 2 and this interrupts the start sequence.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Post-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.20+
