### ISSUE TITLE
[BUG] - Collins Weather Radar Pushbutton animations

### ISSUE THREAD

**Issue by BProduction222** [invernyx/md11-bugs#1696]
### Describe the bug

Pushbuttons will stay pressed in when selected. 

### Expected behaviour

1. Selecting a Weather Mode (OFF, TEST, WX/T, WX, MAP) should cause the pushbutton to stay pushed in. Also, whenever you select a new mode, the previously selected Mode should mechanically depress back to OFF. This means only one mode can be selected ON at a time. 
The bug with this is the animation. In order for the pilot to know what mode he is in before Electrical Power Up, he would need to verify that the OFF switch is pressed in. This check is not possible without the animation of the buttons staying pressed in when selected. 

2. SYS and STAB pushbuttons also stay pressed in when selected. This means, it is possible to have SYS AND STAB and a Weather MODE to be selected together. 

3. IDNT is the only pushbutton that I am aware that is a momentary pushbutton. Since its function is to remove clutter, it needs to be held down in order for the clutter to be removed. Release of the pushbutton will springload the button back to the OFF position.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.12+
