### ISSUE TITLE
[BUG] - SEC PROGRESS Page incorrect title

### ISSUE THREAD

**Issue by BProduction222** [invernyx/md11-bugs#1699]
### Describe the bug

The Title of the SEC PROGRESS only displays "PROGRESS"

### Steps to reproduce

Selected the SEC F-PLN Key and then Next page. Observe the TITLE is only PROGRESS, but should be named SEC PROGRESS according to documentation. 

### Expected behaviour

Should display as "SEC PROGRESS"

### Evidence

![FlightSimulator 2024-07-26 02-02-33](https://github.com/user-attachments/assets/6ba51ab4-c6fd-42cf-a740-60ebe1f57f3a)
![Capture](https://github.com/user-attachments/assets/c6f147b7-2193-444b-92a2-defe1e03e066)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

KSDF

### Arrival

KMIA

### Cruise level

Nne

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

NA

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 1.0.11+
