### ISSUE TITLE
[BUG] - AC TIE 1/2/3 ARM indication with APU PWR ON (MD-EPS-19)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#170]
### Describe the bug

In AUTO ELEC mode after engaging APU GEN PWR, AC TIE 1/2/3 buttons remain blank

### Steps to reproduce

Ground
APU ON
APU PWR ON

### Expected behaviour

S/B ARM in blue for AC TIE 1/2/3 overhead buttons

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by Dimples82** [comment]
When APU PWR ON light iluminates:
- AC and DC 1, 2 and 3 OFF lights extinguish.
- AC TIE 1, 2 and 3 ARM lights and GEN 1, 2 and 3 ARM lights will iluminate.

**Comment by turbofandude** [comment]
Resolved as of 0.61+
