### ISSUE TITLE
[BUG] - APU PWR ON message does not post (MD-EPS-20)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#171]
### Describe the bug

In AUTO ELEC mode after engaging APU GEN PWR, APU PWR ON message does not post

### Steps to reproduce

see descrip

### Expected behaviour

S/B APU PWR ON in cyan posted

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.25+
