### ISSUE TITLE
[BUG] - Land armed stays on after turnaround

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1710]
### Describe the bug

After landing and doing a turnaround, LAND ARMED will stay on FMA on the second flight if LOC wasnt captured on approach

### Steps to reproduce

Finish first flight and fly the approach with land armed but without capturing the localizer. Continue on second flight and observe if LAND ARMED is still annunciated on FMA

### Expected behaviour

LAND ARMED to disappear 

### Evidence

![image](https://github.com/user-attachments/assets/0fac2330-80f1-4ead-b053-8ad39f9524fb)

https://discord.com/channels/589851727373795331/1260902839673425922

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.11+
