### ISSUE TITLE
[BUG] - NEXT WPT on LAT REV page not working correctly

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1728]
### Describe the bug

NEXT WPT (4l key) in LAT REV page should create a shortcut of the route from accesing point to desired waypoint, however it destroys the flightplan.

### Steps to reproduce

Enter LAT REV page of waypoint (by clicking in left key). Try to create a shortcut of the route by entering desired waypoint and observe

### Expected behaviour

Proper creating of shortcut

### Evidence

https://github.com/user-attachments/assets/1ecb299e-6dfb-4b8a-b64b-ddd2a9eaa5a7

https://github.com/user-attachments/assets/029374a0-2b80-49f5-b416-98e6c3208cff

https://github.com/user-attachments/assets/141ad0d8-2239-4abe-8add-86fd90c56cb2

![Bez tytułu](https://github.com/user-attachments/assets/d920fcf8-cc53-41cf-a8f1-6270b29c6c7a)

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Cruise

### Departure

.

### Arrival

.

### Cruise level

.

### ZFW

.

### CG

.

### Fuel

.

### Cost index

.

### Route

.

### Location

.

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.15+
