### ISSUE TITLE
[BUG] - RTA PROGRESS

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1736]
### Describe the bug

On RTA PROGRESS page the RETURN TO VERT REV does not work

### Steps to reproduce

1. Insert a route in FMC
2. Enter F-PLN
3. RSK on a waypoint to enter VERT REV
4. Press RSK2 for RTA PROGRESS 
5. Press RETURN TO VERT REV

### Expected behaviour

Return to VERT REV

### Evidence

![image](https://github.com/user-attachments/assets/a2c8e159-96ca-4601-92c6-f45a4f26a2b7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

.

### Arrival

.

### Cruise level

.

### ZFW

.

### CG

.

### Fuel

.

### Cost index

.

### Route

.

### Location

.

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.20+
