### ISSUE TITLE
EIS displays drop to <1fps during approach

### ISSUE THREAD

**Issue by Geargrip** [invernyx/md11-bugs#1738]
### Describe the bug

EIS displays (PFD, ND, EAD, SD) drop to <1 fps during approach 

### Expected behaviour

EIS display fps should remain constant throughout flight - and did prior to recent update

### Evidence

Unable to take video during flight - was busy hand flying at low altitude.

During LOLED1B STAR into SBKP - from approximately 8,000-3,000 feet msl (6,000-1,000 agl) the EIS screen (PFD, ND, EAD, and SD) frame rates dropped to less than 1 fps.  The sim's frame rate remained stable.  The A/P could not keep up with the EIS displays and was moving the aircraft controls wildly in both pitch and roll while attempting to keep the aircraft on the STAR.

Disconnected A/P at approximately 7,000' and hand flew, since the sim's frame rates were as stable as they were during the flight (approximately 100 fps).  Had it been IMC, I would likely not have been able to control the aircraft via reference to the instruments only.

At approximately 3,000', the EIS frame rates appeared normal and subsequent manual final approach and landing were normal.

This was 2nd flight since the update.  It happened as well on the first flight after the update - but during departure from EHAM.  Did not experience this issue prior to update.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Viralwhite** [comment]
Look at this topic. It’s an ongoing issue but they closed the ticket. https://github.com/invernyx/md11-bugs/issues/1551

**Comment by turbofandude** [comment]
It is an ongoing issue but it's not something we can fix. It happens across the board to many developers and we have Asobo involved - https://devsupport.flightsimulator.com/t/simconnect-data-read-rate-suddenly-intermittently-drops/9586.
