### ISSUE TITLE
[BUG] - Engine start ignition channel not selected message {MD-ENG-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#174]
### Describe the bug

When attempting to start engine with no ignition channel selected, no EICAS message posts

### Steps to reproduce

see descrip

### Expected behaviour

S/B ENG IGN NOT ARMED in amber posts

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
does this alert only come on when an engine start is attempted, it currently always posts without a start channel selected

**Comment by GenericNerd** [comment]
This is currently working, so this has been fixed :)
