### ISSUE TITLE
[BUG] - MSFS auto brakes regression after 1.0.10

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#1741]
### Describe the bug

The auto brakes in msfs have a regression bug where they default back to the state where the default MSFS auto brakes are also active on landing resulting in too harsh braking action. In system.cfg auto_braies is set to 4 instead of 0.

### Steps to reproduce

- Fly any flight up to landing in MSFS
- set auto brakes
- land
- observe excessive braking action 
- check systems.cfg and observe that auto_brakes are set to 4

### Expected behaviour

Aircraft does not have excessive braking action on landing and does not use the default MSFS auto brakes.

Auto brakes should have pre-1.0.10 behaviour.

### Evidence

https://cdn.discordapp.com/attachments/1270200856394076213/1270507012601675848/image.png?ex=66b3f35c&is=66b2a1dc&hm=14ee03a12a8186bb11e7ff924eaa178f870635b360adaeab3edbd93687dc7cc3&

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Landing

### Altitude

N/a

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved
