### ISSUE TITLE
[BUG] - ALTN fuel input

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1742]
### Describe the bug

Inputtin ALTN fuel into init 2, it seems that every inserted 1tn will add 0.2tn for the shown value. For example, if you insert 1, it will show 0.2. 2 will show 0.4. 3 will show 0.6. To get my required 5.3 value shown, I need to insert 26 into the field

### Steps to reproduce

Do not insert ALTN airport on init 1 and then try to input the ALTN fuel.

### Expected behaviour

Calculate and show the value that is inserted.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

EGKK

### Arrival

ENBR

### Cruise level

FL360

### ZFW

181.4tn kg

### CG

28%

### Fuel

21900kg

### Cost index

200

### Route

EGKK/26L N0492F350 FRAN1M FRANE M604 LARGA DCT PENUN/N0490F360 DCT ALUVA ALUV2N ENBR/17

### Location

Anywhere

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.20+
