### ISSUE TITLE
[BUG] - Terrain & WX displays not available in VOR & APPR ND mode 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1745]
### Describe the bug

Terrain & WX displays not available in VOR & APPR ND mode 

### Expected behaviour

To show terrain and WX when putting ND display in VOR or APPR mode 

### Evidence

![Schermopname (738)](https://github.com/user-attachments/assets/e6102bb5-9134-4a39-8082-89531320602b)
![Schermopname (739)](https://github.com/user-attachments/assets/e7a3639f-f75f-4cab-96c8-183a3cac3655)
![Schermopname (740)](https://github.com/user-attachments/assets/1ee952b1-7e84-44c3-b59d-c6de6e9c8a71)
Note weather radar display output should be quite sharp on the ND, not blocky like the terrain display atm

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.20+
