### ISSUE TITLE
[BUG] - ELEVATOR TRIM VISUAL ISSUE [In Cruise]

### ISSUE THREAD

**Issue by ktc767** [invernyx/md11-bugs#1747]
### Describe the bug

Elevator trim seems off both aesthetically and systematically

### Expected behaviour

Looking at a few air to air photos it would appear that the angle of the elevator is level to slight trimmed up. In the TFDi version 1.1 the elevator angle is tilted down instead of level to slightly trimmed up. Below are comparison pictures to the real thing in flight.

### Evidence

![IMG_1247](https://github.com/user-attachments/assets/415513c4-2626-4b62-9dc3-5a4c432eb731)
![IMG_1248](https://github.com/user-attachments/assets/b88f8c5c-e63e-4020-9839-35f2dd75b5d3)
![IMG_1246](https://github.com/user-attachments/assets/d5038de8-de5f-48db-957c-261b7572bf9d)
![IMG_1249](https://github.com/user-attachments/assets/bbba264b-0b07-482c-a6b1-ac33d9b8f433)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This is not a visual issue, it's due to the trim being too far forward. We are working on resolving this.
