### ISSUE TITLE
[BUG] - No PACK shutdown during engine start (MD-ENG-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#175]
### Describe the bug

With APU AIR ON, PACKs ON, ISO Valves OPEN, when selecting engine ignition A or B, the PACKs do not shut down. Additionally, the PACKs remain on during the engine start sequence.

### Steps to reproduce

see description

### Expected behaviour

S/B PACKS shut down upon selecting engine ignition channel and should remain off with PACK 1/2/3 OFF messages.  PACK 1/3 will restart once engine 1 and 3 have started.  PACK 2 will restart once APU AIR is OFF (either by closing the APU AIR valve or turning the APU off).

Some additional info: after selecting ignition A or B and the PACKs shut down, after waiting 2 minutes with no additional action, the PACKs will automatically restart.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.25+
