### ISSUE TITLE
[BUG] - Perf factor missing and A/C status text missaligned

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1756]
### Describe the bug

Perf factor missing 
A/C status text missaligned
Dash between the F and PLAN missing
### Steps to reproduce

-

### Expected behaviour

See evidence 

### Evidence
![Schermopname (767)](https://github.com/user-attachments/assets/9a6a5c34-b626-47d9-8e7f-8a40b822365f)
![Schermopname (758)](https://github.com/user-attachments/assets/2fecca23-3a65-4b75-a32b-accdb926c110)
![Schermopname (765)](https://github.com/user-attachments/assets/62299a73-74d4-4fd2-8986-098b5ced679e)
![Schermopname (766)](https://github.com/user-attachments/assets/e68ea37b-e812-40a5-bc0c-3125a8d7d1eb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Departure

-

### Arrival

-

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.20+
