### ISSUE TITLE
[BUG] - REF pages - Missalignments 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1761]
### Describe the bug

REF pages - Missalignments 

### Steps to reproduce

-

### Expected behaviour

Star to be on the right side of inhibit
IRS 2 to have min aligned properly 

### Evidence

![Schermopname (773)](https://github.com/user-attachments/assets/8b48f81e-8d37-4a75-ab2b-c61d50d30105)
![Schermopname (771)](https://github.com/user-attachments/assets/375c2508-2263-4ef6-8721-995d84a7ce78)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Departure

-

### Arrival

-

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.20+
