### ISSUE TITLE
[BUG] - INIT PAGE - LAT arrows missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1762]
### Describe the bug

LAT arrows missing 

### Steps to reproduce

-

### Expected behaviour

Arrows after the LAT text 

### Evidence

![Schermopname (785)](https://github.com/user-attachments/assets/3c2d2153-04b5-4690-8a37-9f12c3ca2029)
![Schermopname (784)](https://github.com/user-attachments/assets/5f0d74ab-908c-45a2-bab0-2644f6924511)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Departure

-

### Arrival

-

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.20+
