### ISSUE TITLE
[BUG] - FMC's, radio, fuel and FCP displays turn on immediatly when powering up 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1767]
### Describe the bug

FMC's, radio, fuel and FCP displays turn on immediatly when powering up 

### Expected behaviour

Take a bit especially the FMC's seem to take their time around 20 seconds after pressing ext power FO FMC starts to slowly turn on 

+ The fuel displays are always on even without power 

### Evidence

https://youtu.be/rjf9sMh-GDY?si=868u2qYE_MXKQ64n&t=93

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Thank you! Fixed in 1.0.24+.
