### ISSUE TITLE
[BUG] - Thousands Drum flickering in turbulence on standby altimeter

### ISSUE THREAD

**Issue by efortier-95** [invernyx/md11-bugs#1772]
### Describe the bug

Thousands drum on standby altimeter flickers aggressively

### Expected behaviour

Smooth movement of the thousands drum between 32,000' and 31980' (linear?)

### Evidence

https://github.com/user-attachments/assets/2c0e125c-0b19-422c-9922-ceb372207a53

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved in 1.0.26+
