### ISSUE TITLE
[BUG] - APPROACHING MINIMUMS Repeatedly annunciating during taxi-out

### ISSUE THREAD

**Issue by efortier-95** [invernyx/md11-bugs#1775]
### Describe the bug

The APPROACHING MINIMUMS repeatedly annunciates during taxi-out

### Steps to reproduce

1. Start in LPPT (stand 412 in my example)
2. Set Baro minimums to 278 (Baro minimums for EGLL ILS 27R)
3. Start taxi-out
4. Note APPROACHING MINIMUMS audio plays frequently

### Expected behaviour

APPROACHING MINIMUMS annunciates once OR not at all (not sure how the actual MD11 does it)

### Evidence

https://youtu.be/0790-108-Y0

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Takeoff

### Altitude

400-ish

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Thank you! We've added a check to require the aircraft to be... you know... airborne for these alerts to play in 1.0.24+.
