### ISSUE TITLE
[BUG] - Total fuel quantity incorrectly sized and tank indications should have jagged edge

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1779]
### Describe the bug

Total fuel quantity incorrect size and tank indication should have jagged edge

### Expected behaviour

Be correctly sized and have a jagged egde on the fuel and hydraulic tank quantities 

### Evidence

https://youtu.be/ZUlmi9XFeIM?si=iU-bH0XYufhtp7YM&t=176
![Schermopname (825)](https://github.com/user-attachments/assets/371d899e-c56e-483c-b9a1-ebfc0107bde1)
![Schermopname (823)](https://github.com/user-attachments/assets/c7a01c5c-357d-4512-aaa9-a6ba12b8c5ad)
![Schermopname (827)](https://github.com/user-attachments/assets/190fbed6-61e4-47d3-9202-ab66e60b50ac)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.24+
