### ISSUE TITLE
[BUG] - Bleed system pressures with engines running and bleed valves closed (MD-ECS-15)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#178]
### Describe the bug

With engines running and ISO valves closed, closing the associated bleed valve has no impact on bleed pressures indication or annunciation

### Steps to reproduce

see descrip

### Expected behaviour

S/B BLEED AIR X OFF amber message posts, AIR SYS X OFF amber message posts, PRESS in amber illuminates on overhead bleed control button, associated PACK FLOW in amber illuminates, bleed pressures should bleed down to zero psi

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in V0.42.01

**Comment by turbofandude** [comment]
Resolved in 0.55+

**Comment by FreakyD777** [comment]
verified fixed
