### ISSUE TITLE
[BUG] - Incorrect TCAS Altitude Displayed

### ISSUE THREAD

**Issue by faulder** [invernyx/md11-bugs#1784]
### Describe the bug

As described in #1496, TCAS target displays the aircraft at a "+" altitude when it is visually below the aircraft. Using vPilot on VATSIM. Doesn't appear fixed on 1.0.19.

### Expected behaviour

TCAS target should display the correct altitude relative to the aircraft.

### Evidence

- Target aircraft visually passed below my aircraft but displayed +10.

![FlightSimulator_2024-10-20_16-27-58](https://github.com/user-attachments/assets/63c8394f-e2d8-4113-a922-67f9e025e4f1)
![SimToolkitPro_2024-10-20_16-28-16](https://github.com/user-attachments/assets/ccb2ee8a-4f43-455d-9f89-2aeb20cab29b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Thank you! We found an issue specifically with display that could cause this and it should be resolved in 1.0.24+
