### ISSUE TITLE
[BUG] - Adjusting right MCDU brightness CTD

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1785]
### Describe the bug

7 hours into an 8 hour flight, I went to adjust the brightness of the number 2 MCDU and it crashed the sim.

### Steps to reproduce

Not sure if it's related to flight time, but adjust the brightness on the FOs MCDU

### Expected behaviour

Not to have a sim crash 7 hours into a long haul flight

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
If the simulator itself crashed, this is likely due to something else with the computer/simulator that happened to occur simultaneously. If this reoccurs and becomes recreatable, please let us know and we will investigate further.
