### ISSUE TITLE
[BUG] - 6R key not working in IRS STATUS (page 3 of POS REF)

### ISSUE THREAD

**Issue by csb005** [invernyx/md11-bugs#1787]
### Describe the bug

As in the title - FMS won't back to F-PLN INIT page while on IRS STATUS page

### Steps to reproduce

Load and prepare FMC -> press INIT -> POS REF menu -> IRS STATUS (page no 3) -> press RETURN TO F-PLN INIT

### Expected behaviour

FMS going back to flight plan initialisation page after pressing proper key

### Evidence

https://github.com/user-attachments/assets/85bc5dd7-ba22-4d5f-be35-5c627d37bd78

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Pre-flight

### Departure

CYUL

### Arrival

KPHL

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by csb005** [comment]
Evidence:


https://github.com/user-attachments/assets/fb3850c6-2aaa-44d5-aa51-b4dcdbfd48a5

**Comment by turbofandude** [comment]
Resolved in the next release
