### ISSUE TITLE
[BUG] - AC Bus Ties with engines running (MD-EPS-21)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#179]
### Describe the bug

With engines running, AC TIE 1/2/3 shows open and white on the ELEC SYN page

### Steps to reproduce

see descrip

### Expected behaviour

S/B closed and green

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in V0.42.01

**Comment by turbofandude** [comment]
Resolved as of 0.61+
