### ISSUE TITLE
[BUG] - IRS alignment of PFD

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1790]
### Describe the bug

IRS alignment of PFD

### Expected behaviour

Red cross to dissapear when IRS is moved to NAV 
Vertical speed tape should appear after full alignment 
Flight director bar should appear after full alignment 
Radio altitude box should be filled in brown unitl artificial horizon is back

### Evidence

https://youtu.be/gsSdTLp1nVI?si=c_PeXK9ER1p-WWBl&t=120
https://youtu.be/gsSdTLp1nVI?si=Qgbp6EKPCqTaqtL3&t=421
https://youtu.be/gsSdTLp1nVI?si=agTM2PL8RVRIM5IU&t=151

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.24+
