### ISSUE TITLE
[BUG] - Cabin smoke not illuminating during cargo fire test 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1791]
### Describe the bug

Cabin smoke not illuminating during cargo fire test 

### Steps to reproduce

#1244 as not fixed 

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This is likely an art issue that will not be fixed until next update, per Ozzy closing the previous one
