### ISSUE TITLE
[BUG] - FMS DONE phase not triggered 5 seconds after shutdown, AC STATUS page not showing in DONE phase

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1794]
### Describe the bug

DONE phase not triggered 5 seconds after shutdown, triggerd correctly when INIT is pressed. AC STATUS page fails to display after DONE pahse is triggered via INIT

### Steps to reproduce

Fly a flight
After landing, **do not press INIT on either MCDU** (this part works correctly)
Shut down engines
Weight min. 5sec, FMS fails to reset unless INIT is pressed

Secondary issue, AC STATUS page does not display after either method of triggering DONE

### Expected behaviour

![{5E9FA4FF-0DAB-42BE-B91F-95D96B605FF8}](https://github.com/user-attachments/assets/df3e5d08-8f38-4e5f-9e17-cac7ee7c5718)

### Evidence

Well after Shutdown
![image](https://github.com/user-attachments/assets/3ea10e04-ab8c-4220-80de-06982bcb7632)

Pressing INIT correctly clears data, but fails to display AC STATUS page
![image](https://github.com/user-attachments/assets/465c6ed3-8fca-4bc7-abb4-512b4f2413fc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Post-flight

### Altitude

-

### Departure

EDDF

### Arrival

KJFK

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.31+
