### ISSUE TITLE
[BUG] - SID & STAR page arrows missing 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1795]
### Describe the bug

SID & STAR page arrows missing 

### Expected behaviour

Show arrow/arrows 

### Evidence

https://youtu.be/wh_zizrth2g?si=h3QghG63mq8em35Z&t=3441

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.31+
