### ISSUE TITLE
[BUG] - MCP altitude cut off

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#18]
### Describe the bug

The MCP altitude window cuts off the value

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
It's correct in P3D, though, so that tells me it's not a code-based rendering issue

**Comment by turbofandude** [comment]
FINALLY resolved as of 0.48+.
