### ISSUE TITLE
[BUG] - Generotor switches inoperative (MD-EPS-22)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#180]
### Describe the bug

ELEC SYS MANUAL, engines running, GEN 1 button has no system response or indication changes

### Steps to reproduce

see descrip

### Expected behaviour

S/B GEN 1/2/3 OFF in amber message posts plus OFF in amber on overhead panel indication and GEN 1 tie open in white on ELEC SYN.  Additionally, when all GEN 1/2/3 are selected to OFF, the GEN ALL OFF amber message should post

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved  in 0.53+
