### ISSUE TITLE
[BUG] - No low fuel warning message posts (MD-FUEL-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#181]
### Describe the bug

No low fuel warning once TANK 1/2/3 goes below 4000 lbs

### Steps to reproduce

see descrip

### Expected behaviour

S/B TNK 1/2/3 FUEL QTY LO in amber posts when associated tank reaches <4000lbs

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37
