### ISSUE TITLE
[BUG] - No ignition bolt when engine anti ice is on 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1814]
### Describe the bug

No ignition bolt when engine anti ice is on 

### Expected behaviour

Ignition bolt to show for 60 seconds after turning engine anti ice on 

### Evidence

![Schermopname (930)](https://github.com/user-attachments/assets/9c4be5f7-b85f-434e-b3ec-6b2b78567d37)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.31+
