### ISSUE TITLE
[BUG] - IRS Panel - Cargo Fire Test 

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#182]
### Describe the bug

Cargo Fire test does not initiate when first IRS switch placed to NAV. Erroneously initiates test when placed in OFF position.

### Steps to reproduce

Cold and Dark
Place IRS switches to NAV position
Observe Cargo Fire test does not initiate
Once alignment is complete, place IRS 1 switch to OFF
Cargo Fire test will begin.

### Expected behaviour

The Cargo Fire test should be performed automatically when the first IRU is turned on.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Confirmed

**Comment by turbofandude** [comment]
Found and resolved. Thank you!
