### ISSUE TITLE
[BUG] - EFB Dispatch Page Airline displaying ICAO Airline length instead of ICAO Airline

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1822]
### Describe the bug

On the Dispatch page, instead of displaying UPS314 it displays 3314, where 3 is the *length* of UPS

### Expected behaviour

To display UPS314

### Evidence

![Screenshot_2024-12-19_17-19-43](https://github.com/user-attachments/assets/d1be32f1-26a5-4887-bfb9-5d01c51af483)

Offending line of code (transpiled JS, but should be obvious in source `src/routes/DispatchPage.tsx`, `FlightPlanViewer` Component
![8F6AA0E8-AD2B-4A9C-8E0C-CC4A3EF1DD9F](https://github.com/user-attachments/assets/eb134435-ae57-4003-83d2-320f6a512bb8)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.35+
