### ISSUE TITLE
[BUG] - FMS Becomes Unresponsive When Inputting ALIGN POS Position

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#184]
### Describe the bug

On initial startup,  'ALIGN POS' displayed and coordinates were not in agreement with GNS position (or accurate to aircraft position)

### Steps to reproduce

Prior to Initializing IRS
Place Latitude in scratchpad (ie. 'N3810.1')
Place coordinate data in 3L
FMS Freezes and becomes unresponsive to any input

### Expected behaviour

Placing a Latitude (or Longitude) in the scratchpad and subsequently the 3L or 3R respective position to update the ALIGN POS prior to initializing the IRS

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

0

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

None

### Location

KSDF Ramp 115

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Verified bug with the following steps:
Cold and dark
External power/battery on
FMC-1
F-PLN INIT
Input latitude to L3

**Comment by GenericNerd** [comment]
Fixed in the next release
