### ISSUE TITLE
[BUG] - FCP Airspeed Knob Is Live, Constantly Changing Cruise Speed Edit

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#185]
### Describe the bug

While at cruise, adjusting the airspeed knob on the FCP constantly changes the CRZ Speed Edit and current FMS SPD target

### Steps to reproduce

Establish at cruise
Select FMS Speed
Adjust FCP speed knob and observe commanded speed change on the PFD and CRZ Edit

### Expected behaviour

Adjusting the  speed knob should only wake the FCP airspeed display
Two options exist to activate that speed as the commanded speed:
1) Pressing FMS SPD within 10s of making an airspeed change will put it in the FMS as a speed EDIT
2) Pulling the knob makes the selected speed the commanded speed.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.17+
