### ISSUE TITLE
[TODO] - MCDU DSPY and OFST lights missing

### ISSUE THREAD

**Issue by turbofandude** [invernyx/md11-bugs#186]
### Describe the bug

These lights are missing on the side of the annunciator

### Steps to reproduce

Look at the MCDU

### Expected behaviour

Exist

### Evidence

n/a

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I will add these lights to the variables/xml I am sending tonight for 0.8.0.1

**Comment by jhattermann** [comment]
Added before CE launch
