### ISSUE TITLE
[BUG] - Analog standby altimeter has no negative symbol

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#187]
### Describe the bug

The analog standby's first scroll wheel  does not have a negative symbol.

### Steps to reproduce

N/A

### Expected behaviour

The analog standby's altimeter is supposed to have a negative symbol. The analog standby altimeter can go as low as -1000 feet.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48654776/f1fe0933-f190-450f-b1b3-42e327f1025c)

### Simulator

P3Dv4, Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Fixed but may need to adjust animation to match
