### ISSUE TITLE
[BUG] - Anti-Ice system operation (MD-ECS-17)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#190]
### Describe the bug

Cannot turn on Anti-Ice system w/out AIR SYS in MANUAL

### Steps to reproduce

see scrip

### Expected behaviour

S/B able to turn on/off all anti-ice with AIR SYS in AUTO

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.28+
