### ISSUE TITLE
[BUG] - Cabin pressure control system (MD-ECS-19)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#192]
### Describe the bug

At FL390, with AIR in MANUAL and CABIN PRESS in MANUAL, when turning off all 3 PACKs, no change in cabin altitude (no change in cabin alt with all 3 bleeds off either) and OFV not controllable (same as MD-ECS-8)

### Steps to reproduce

see descrip

### Expected behaviour

S/B a slow rise in cabin altitude accompanied by decrease in dP and PACK 1/2/3 OFF amber message posts

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
EICAS messages correct.  No change in cabin altitude still. V0.42.01

**Comment by turbofandude** [comment]
Resolved in 0.60+
