### ISSUE TITLE
[BUG] - Anti-Skid system indication (MD-HYD-6)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#193]
### Describe the bug

No indication on Anti-Skid button

### Steps to reproduce

press anti-skid button to OFF

### Expected behaviour

S/B OFF in amber when anti-skid is deactivated.  Blank when anti skid is active.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by Willmus11** [comment]
Anti-Skid should also be in ON (normal position)

**Comment by TheFightingRaven** [comment]
fixed
