### ISSUE TITLE
[BUG] - HStab trim indication on CONFIG SYN page (MD-FC-10)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#194]
### Describe the bug

On the CONFIG SYN page, the HStab green band is located in center of screen (ontop of rudder graphic)

### Steps to reproduce

Pull up CONFIG SYN page after FMS preflight inputs are complete and a HStab trim has been calculated

### Expected behaviour

S/B located along the STAB trim graphic on the top right corner of the synoptic screen

### Evidence

![FlightSimulator_2023_10_27_20_22_02_010](https://github.com/invernyx/md11-bugs/assets/148836830/08baf680-b94a-403d-96cd-c5774955fde4)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Duplicate - fixed in 0.22
