### ISSUE TITLE
[BUG] - Random geometry hanging off the right wingtip

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#195]
### Describe the bug

See picture

### Steps to reproduce

See picture

### Expected behaviour

See Picture

### Evidence

See pic

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
![FlightSimulator_2023_10_27_15_16_04_151](https://github.com/invernyx/md11-bugs/assets/148836830/7bd66c87-bcde-4811-8690-dc45091fd4db)

**Comment by FreakyD777** [comment]
![FlightSimulator_2023_10_27_14_56_37_788](https://github.com/invernyx/md11-bugs/assets/148836830/b17099cf-7cb1-4473-b453-51cff805d33a)

**Comment by jhattermann** [comment]
Fixed by resetting object transforms
