### ISSUE TITLE
[BUG] - First Officer EFIS panel non-functional (MD-AV-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#196]
### Describe the bug

FOs EFIS panel has no influence on FOs ND

### Steps to reproduce

Press various EFIS buttons and observe FOs ND

### Expected behaviour

S/B FOs EFIS panel controls FOs ND

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed
