### ISSUE TITLE
[BUG] - Fix page bearing/distance (MD-AV-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#197]
### Describe the bug

On the FIX page, cannot insert bearing or distance

### Steps to reproduce

Select FIX
Insert bearing/distance in top row

### Expected behaviour

S/B able to insert a bearing and distance and it should draw on the ND

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Long since resolved
