### ISSUE TITLE
[BUG] - FIX identifer draw on ND (MD-AV-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#198]
### Describe the bug

When entering a fix, the ND draws a green circle off center from the fix location

### Steps to reproduce

After inputting a fix on the FIX page, observe the ND identifier draw location

### Expected behaviour

S/B green circle draws centered around the fix location (KGGW is selected in the pic below)

### Evidence

![FlightSimulator_2023_10_27_20_20_47_903](https://github.com/invernyx/md11-bugs/assets/148836830/41cc22fe-f252-4828-b60e-501df493da0e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be long resolved.
