### ISSUE TITLE
[BUG] - Center gear alternate switch indication (MD-HYD-7)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#199]
### Describe the bug

When selecting CTR GEAR UP switch to UP, no backlight indication is present

### Steps to reproduce

see descrip

### Expected behaviour

S/B UP in blue when center gear is commanded to remain up.  Blank when commanded NORM.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
additionally that text floats in space and doesn't move with the button.

**Comment by FreakyD777** [comment]
verified fixed v0.37
