### ISSUE TITLE
[BUG] - Displays reflect off window #1 L and R

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#200]
### Describe the bug

The main DUs reflect off the #1L and #1R windows at night

### Steps to reproduce

Set sim to night, observe reflection on window #1 from both CO and FO seats

### Expected behaviour

S/B not visible on #1 windows

### Evidence

![FlightSimulator_2023_10_27_20_19_28_013](https://github.com/invernyx/md11-bugs/assets/148836830/739006e7-03d9-4576-8832-6ff29adefbb3)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This issue cannot be totally resolved as MSFS uses Screen Space Reflections which is known to be inaccurate. Removal of the window or reduction of reflections is the only way to remove display reflections.
