### ISSUE TITLE
[BUG] - FLT DIR switches inop (MD-AFS-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#201]
### Describe the bug

CO and FOs FLT DIR OFF switch is INOP.  Also, the CO and FO FLT DIR switch is INOP.

### Steps to reproduce

Depress FLT DIR switch and observe PFD

### Expected behaviour

S/B able to turn flight director bars off with FLT DIR OFF switch and use the FLT DIR switch to swap to opposite side FD.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved in 0.25+
