### ISSUE TITLE
[BUG] - Nav Display turn prediction draw (MD-AV-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#202]
### Describe the bug

No green turn prediction on ND in map mode

### Steps to reproduce

Select MAP mode
Initiate turn
Observe no green prediction curve drawn on ND

### Expected behaviour

Green prediction curve drawn on ND as a function of bank angle

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in V0.42.01

**Comment by turbofandude** [comment]
Resolved as of 0.46+
