### ISSUE TITLE
[BUG] - Engine restart at high altitudes (MD-ENG-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#203]
### Describe the bug

At FL390 after cutting fuel to engine #2, the engine was able to restart at that same altitude

### Steps to reproduce

see descrip

### Expected behaviour

S/B unable to restart CF6-80C2 engines above FL300.  Engine restart envelope is as follows:

- WITH STARTER ASSIST: 14k ft up to 120KIAS, then up to FL300 from 160KIAS to 220KIAS (straight line from 120 to 160KIAS on the chart)

- WINDMILL START ONLY: FL300 from 220KIAS to 340KIAS, then down to FL260 at 360KIAS, then down to 10kft at 360KIAS, then down to 0ft at 350KIAS

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL390

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 1.0.35+
