### ISSUE TITLE
[BUG] - VS bug indication when engaging VS mode (MD-AFS-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#206]
### Describe the bug

When initiating a climb/descent from straight and level flight in VS mode, when manipulating the VS knob, the VS bug starts at the previously set VS mode number (ie if my previous climb using VS mode was +2000, the initial VS will be +2000 again, regardless if I'm climbing or descending)

### Steps to reproduce

see descrip

### Expected behaviour

S/B VS bug starts from zero when initiating a VS climb/descent from straight and level flight

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should have long been resolved.

**Comment by FreakyD777** [comment]
Nope, the VS input defaults to the previous setting.  So if you set VS at +2000fpm during climb, then go to use it for descent, it starts at +2000 again.

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37
