### ISSUE TITLE
[BUG] - EFB OPTIONS CHANGING BETWEEN IMPERIAL AND METRIC NOT MATCHING AIRCRAFT

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#209]
### Describe the bug

IN THE OPTIONS IN THE EFB WHEN CHANGING BETWEEN IMPERIAL AND METRIC THE PAYLOAD PAGE DOESNT MATCH AIRCRAFT. IF PAYLOAD PAGE SHOWS LBS THEN AIRCRAFT SHOWS KGS AND VICE VERSA

### Steps to reproduce

SWITCH THE OPTIONS IN THE EFB FROM IMPERIAL OR METRIC AND THE EFB DOESNT MATCH AIRCRAFT 

### Expected behaviour

FOR THE EFB OPTION TO MATCH THE AIRCRAFT 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

940

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This happened when the EFB options were saved and should be fixed in the next update.
