### ISSUE TITLE
[BUG] - CAN NOT CLICK THE A BUTTON ON PILOTS FMS. 

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#210]
### Describe the bug

YOU ARE NOT ABLE TO CLICK THE A BUTTON ON THE PILOTS FMS NO CLICK SPOT FOR IT. 

### Steps to reproduce

TRY CLICKING A ON THE PILOTS FMS

### Expected behaviour

TO BE ABLE TO CLICK A ON THE PILOTS FMS

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

KONT

### Arrival

KOAK

### Cruise level

FL360

### ZFW

353.3

### CG

31

### Fuel

32.0

### Cost index

20

### Route

SNSHN5 COREZ DCT RGOOD EMZOH3

### Location

KONT

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This is a duplicate post of https://github.com/invernyx/md11-bugs/issues/211
