### ISSUE TITLE
[BUG] - CA FCP ARPT Button Has Lost Click Spot

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#212]
### Describe the bug

Unable to click ARPT button on CA FCP

### Steps to reproduce

Try to click ARPT button on FCP
Realize you cant

### Expected behaviour

Be able to click it

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Verified

**Comment by jhattermann** [comment]
Both models have click spots assigned
