### ISSUE TITLE
[BUG] - number scrolling in the analogue standby wrong

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#214]
### Describe the bug

when scrolling down it goes from 1000>0000>0009

### Steps to reproduce

scroll down on the standby instrument

### Expected behaviour

don't do this

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Superseded by #218
