### ISSUE TITLE
[BUG] - Dump Manifold Persistent On Fuel Synoptic Display

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#216]
### Describe the bug

Dump Manifold is always visible on Fuel Synoptic

### Steps to reproduce

Look at Fuel Synoptic Page

### Expected behaviour

Dump manifold should only be visible on the fuel synoptic when fuel dumping is occuring.

### Evidence

Look at fuel synoptic

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Confirmed

**Comment by GenericNerd** [comment]
Verified. Displays Holy Grail page 100.

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37
