### ISSUE TITLE
[BUG] - Aircraft circling waypoint then not picking up magenta line

### ISSUE THREAD

**Issue by lscott122** [invernyx/md11-bugs#217]
### Describe the bug

The aircraft missed a waypoint, circled it then did not pick up the line

### Steps to reproduce

Allow the aircraft to continue its circle without using the MCDU to select the next waypoint and see if it will pick up the line whilst still in NAV mode.

### Expected behaviour

The aircraft should pick the line back up at the waypoint.

### Evidence

![FlightSimulator_3X1tzCn304](https://github.com/invernyx/md11-bugs/assets/41208924/ea4d1af0-a312-4428-ace3-119967e9d62f)
![FlightSimulator_czBwrQj19o](https://github.com/invernyx/md11-bugs/assets/41208924/4df9e5a9-9611-446b-bcf6-c012de9c4deb)
![smartcars3_hETSVlgLHx](https://github.com/invernyx/md11-bugs/assets/41208924/b00f9974-1e5d-4e21-940d-fa698b15fc98)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

EGCC

### Arrival

EIDW

### Cruise level

FL240

### ZFW

150.995KG

### CG

29%

### Fuel

13.0KG

### Cost index

82

### Route

EGCC/23R EKLA1R EKLAD WAL PENIL LELDO BAGSO BAGS1K EIDW/16

### Location

Between at the end of the EKLAD sid

### Agreement

- [X] Yes

**Comment by lscott122** [comment]
![FlightSimulator_wSvs4xrkm6](https://github.com/invernyx/md11-bugs/assets/41208924/9cd27ad5-5bd2-4807-b82f-c77561ba082d)

**Comment by GenericNerd** [comment]
Fixed
