### ISSUE TITLE
[BUG] - Analog Standby ALT reading 0

### ISSUE THREAD

**Issue by lscott122** [invernyx/md11-bugs#218]
### Describe the bug

Analog Standby ALT reading 0

### Steps to reproduce

Take the aircraft into the air to check if the STBY gauge works

### Expected behaviour

The standby guage should read the alt based on the QNH set

### Evidence

![FlightSimulator_wSvs4xrkm6](https://github.com/invernyx/md11-bugs/assets/41208924/d9cdafa2-1552-4379-80c0-666b37cbdde0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Is this still an issue?

**Comment by lscott122** [comment]
Yes, however, it now reads -1000
![Qm3GAqS](https://github.com/invernyx/md11-bugs/assets/41208924/f2e7cc38-e173-42c2-b0da-05e23a685c5a)
