### ISSUE TITLE
[BUG] - lines of text in mcdu don't lineup with action buttons side

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#22]
### Describe the bug

lines of text in the mdcu don't line up the buttons on the side

### Agreement

- [X] Yes

**Comment by AKSledhead** [comment]
This is still an issue

**Comment by jhattermann** [comment]
Gauge can be translated vertically in panel.cfg

**Comment by turbofandude** [comment]
Resolved as of 0.28+
