### ISSUE TITLE
[BUG] - Digital Inclinometer Inop

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#220]
### Describe the bug

Bank Angle Indicator/Inclinometer at top of PFD does not indicate side-slip

### Steps to reproduce

Auto-pilot off, induce side slip on the aircraft
Bank angle/inclinometer triangle remains solid.

### Expected behaviour

When under side slip the bank angle/inclinometer should bisect with the lower half showing the direction and magnitude of the slip.

### Evidence

https://github.com/invernyx/md11-bugs/assets/123108304/f73698b6-169b-4c95-86d2-09a621737e79

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
