### ISSUE TITLE
[BUG] - Loading Approach Mid-Flight Causes Vertical Path and ETA Calculation Errors

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#221]
### Describe the bug

When loading an approach mid-flight, the T/D, est altitude and time at points, and general vertical path turn to dashes

### Steps to reproduce

Depart with SID, route, and STAR loaded
While at cruise, load approach
NAV and PROF will disconnect
FMS seems to lose track of position along vertical and lateral profiles
Have to DIR-TO next point to get NAV back
All estimated times/altitudes at points along route disappear and do not recalculate
Descent calculations now ignore large font altitudes on STAR

### Expected behaviour

When reloading or modifying the existing route, the FMS should take a few seconds to recalculate all of the calculations made on the ground.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL330

### Departure

KSDF

### Arrival

KEWR

### Cruise level

FL330

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

60

### Route

35R CRRGO4.CRRGO GVE.PHLBO3 

### Location

Approaching GVE enroute

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I think this was fixed with the new leg system, please comment if still present
