### ISSUE TITLE
[BUG] - Wind Track Incorrect Direction

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#222]
### Describe the bug

When in Wind Vector mode, the Track crosswind is displayed in the opposite direction

### Steps to reproduce

Set Wind Vector Type to track, observe crosswind displayed from opposite direction.

### Expected behaviour

Wind Vector track should show from correct direction

### Evidence

![windvector](https://github.com/invernyx/md11-bugs/assets/123108304/86a955a1-fdd0-4b9e-8a46-91962f0b69af)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
The X-Axis seems to be flipped. Very easy fix.

**Comment by pburnay-invernyx** [comment]
Tested and confirmed. That is, in vectored mode, the crosswind component (arrow) is flipped.

**Comment by turbofandude** [comment]
Fixed in 0.12+
