### ISSUE TITLE
[BUG] - Transitioning Waypoints Aircraft Turns to Non-Drift-Killed Heading Before Correcting

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#223]
### Describe the bug

When transitioning waypoints with a crosswind, aircraft will turn to planned course before turning back and correcting for drift.

### Steps to reproduce

Transition waypoints at cruise with a >15 knot crosswind

### Expected behaviour

Waypoint transition should be drift-killed to prevent S-turning across transition points

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

0

### Arrival

0

### Cruise level

0

### ZFW

0

### CG

0

### Fuel

0

### Cost index

0

### Route

0

### Location

0

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I think this was fixed as part of the new legs, please comment if still present
