### ISSUE TITLE
[BUG] - Unable to steer during taxi with Nose Wheel Steering Axis and Rudder Axis bound to the same control device

### ISSUE THREAD

**Issue by 717driver** [invernyx/md11-bugs#227]
### Describe the bug

Flying with rudder pedals I had nosewheel and rudder axis bound to steer the airplane during taxi.  When I disabled Rudder Axis I was able to regain steering left ok while taxiing. 

### Steps to reproduce

Bind Rudder Axis and Nose Wheel Axis to same control device axis results in unable to control nosewheel steering on the ground

### Expected behaviour

Should able to control nosewheel steering on the ground independently of rudder. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Takeoff

### Altitude

0 AGL

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Using the same axis on the same device, I was not able to reproduce this issue. Is there any further clarification you can provide?

**Comment by 717driver** [comment]
The most recent build pretty well resolved it and I was able to taxi again. Not sure what changed, or if anything did, but I think this can be closed at this point.

**Comment by GenericNerd** [comment]
No changes were made, but glad to hear it was fixed!
