### ISSUE TITLE
[BUG] - Drift Angle Pointer On Nav Display Frozen At Zero

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#228]
### Describe the bug

The drift angle pointer green diamond is frozen on heading and does not identify drift

### Steps to reproduce

Look at ND

### Expected behaviour

Show aircraft track based on drift.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Both my wind indicators are showing values on the ND. Is this still happening to you?

**Comment by GR1MMly** [comment]
> Both my wind indicators are showing values on the ND. Is this still happening to you?

Sorry I used incorrect terminology that made this unclear. I am referencing the Drift Angle Pointer on the Nav Display. Adjusted title to reflect.

**Comment by turbofandude** [comment]
Resolved in 0.3x+
