### ISSUE TITLE
[BUG] - Extending the centerline on an approach via the direct to page

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#229]
### Describe the bug

When being vectored to final, you should be able the extend the centerline. This should be accomplished via the direct to prompt and entering the inbound course on line 1R

### Steps to reproduce

While being vectored to final, enter “direct to” the IAF or the desired extension point. On FMC line 1R there will be a prompt to enter the inbound course. Ex. NICCO/______* (inb crs)

### Expected behaviour

It is important to be able to extend the inbound course. This will provide you with a distance from centerline and provide the FMC with your desired intercept parameter. I would expect the FMC extended centerline to appear after entering the inbound course.
![image](https://github.com/invernyx/md11-bugs/assets/148719444/6afa2549-fb7d-4737-8bd2-84850f1af32e)

![image](https://github.com/invernyx/md11-bugs/assets/148719444/1fdfc1c3-af30-42ee-b31e-f5a718a461bc)
### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

2000

### Departure

KJFK

### Arrival

KJFK

### Cruise level

2000

### ZFW

400.0

### CG

28.1

### Fuel

59500

### Cost index

50

### Route

KJFK takeoff 31L and returned to ILS 31R

### Location

KJFK vectoring to final, but it happens everywhere 

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
do you happen to have a manual reference for this behaviour?

**Comment by 017941** [comment]
We had a different method in my 1996 FMC software. As you know,  99 percent of real world airline approaches are via an extended centerline as you are vectored. It is obvious that the method that this MD-11 uses is via the DIR key followed by entering the inbound course in 1 R. It is crucial for waypoint sequencing to have that ability to extend centerline if you intend to use NAV on the missed. It also provides you with a distance from centerline.Thank you for all you do. I don’t know what you guys do behind the scenes, but I’m impressed! I wish I could help more.Sent from my iPadOn Nov 9, 2023, at 3:34 PM, TheFightingRaven ***@***.***> wrote:﻿
do you happen to have a manual reference for this behaviour?

**Comment by 017941** [comment]
Hi. Actually, my old manual did have guidance on this issue! Sorry. I have uploaded the pages from the manual. Thanks for everything. Extending the centerline and “cleaning up the flight plan” is central to flying a transport in the pattern. It occurs in just about every flight. Sent from my iPhoneOn Nov 9, 2023, at 3:34 PM, TheFightingRaven ***@***.***> wrote:﻿
do you happen to have a manual reference for this behaviour?

**Comment by 017941** [comment]
I can't wait for this one to be completed. It is huge. It is critical to be able to extend the centerline, as this occurs on almost every flight. It also correctly sequences the active waypoint and subsequently the missed approach.

**Comment by turbofandude** [comment]
This is now implemented as of 0.25+
