### ISSUE TITLE
[BUG] - Aircraft banking to the left straight after takeoff 

### ISSUE THREAD

**Issue by scotsgod** [invernyx/md11-bugs#230]
### Describe the bug

Aircraft banking hard left 

### Steps to reproduce

Engines spooled up , Made V2 , Took off , And then the aircraft veered off to the left aircraft would not level off with maximum right bank applied. 

### Expected behaviour

Unrecoverable left bank angle. 

### Evidence

<img width="1920" alt="Microsoft Flight Simulator Screenshot 2023 10 29 - 14 03 41 75" src="https://github.com/invernyx/md11-bugs/assets/58995308/773036a5-f609-4e36-a4d4-5226258f5ddd">

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
I did have a slight bank to the left on departure with RCWS, but it was not completely unrecoverable. With RCWS disabled, I did not have this bank to the left. Could you try it with RCWS disabled and see if it still does it?

As a side note, there is a bug where RCWS will not allow you to recover the bank angle if it exceeds 30 degrees. This is not the case in the real world (as you can probably imagine).

**Comment by Fly2belgium** [comment]
I encountered the same problem with PAX version. Aileron input makes no difference at all.

**Comment by Fly2belgium** [comment]
Still present in v0.15 when starting flight on the runway. Not a problem when starting cold and dark at the gate.
