### ISSUE TITLE
[BUG] - IRS not aligning 

### ISSUE THREAD

**Issue by scotsgod** [invernyx/md11-bugs#231]
### Describe the bug

IRS not Aligning 

### Steps to reproduce

Turn IRS switch's to NAV

### Expected behaviour

IRS when clicked to NAV do not align at all , The three orange lights just flash constantly but nothing else happens 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Did you initiate IRS allignment in the FMC?

**Comment by turbofandude** [comment]
Found two different issues, one causing NAV OFF flashing for no reason and one preventing the "INITIALIZE IRS*" prompt from disappearing. The IRU _does_ align, but it didn't look like it was. Should be fixed 0.9.0
