### ISSUE TITLE
[BUG] - The letter "A" button on the left FMC does not work

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#232]
### Describe the bug

When entering data on the left FMC, the letter "A" button does not work. All other buttons work on the left FMC, and ALL buttons work on the right FMC.

### Steps to reproduce

Attempt to enter the letter "A" on the left FMC

### Expected behaviour

When pressing the "A" button on the left FMC, the letter "A" should appear in the scratchpad.

### Evidence

https://youtu.be/7V9AEShcoFw

YOUTUBE unlisted link

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Departure

KPAE

### Arrival

KPAE

### Cruise level

3000

### ZFW

0

### CG

0

### Fuel

0

### Cost index

0

### Route

0

### Location

KPAE ramp spot 61

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
confirmed

**Comment by arwasairl** [comment]
This issue has been fixed in v0.9.0
