### ISSUE TITLE
[BUG] - Fuel dump system indication (MD-FUEL-5)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#233]
### Describe the bug

When depressing fuel DUMP switch, no backlight indication illuminates, no EICAS messages post

### Steps to reproduce

see descrip

### Expected behaviour

S/B illuminates ON in amber and FUEL DUMP ON amber message posts

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL300

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37
