### ISSUE TITLE
[BUG] - CDU scratchpad clears (MD-FMS-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#234]
### Describe the bug

When typing on the scratchpad, the input sometimes resets back to blank

### Steps to reproduce

Type in scratchpad... it is intermittant and random as far as I can tell.  However, typing faster seems to induce it more often.

### Expected behaviour

Scratchpad inputs remain

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Departure

07MT

### Arrival

07MT

### Cruise level

FL300

### ZFW

400K

### CG

27

### Fuel

20K

### Cost index

80

### Route

07MT - 07MT

### Location

N/A

### Agreement

- [X] Yes

**Comment by 1stVFW-Phantom** [comment]
To add to this, it appears to be easily repeatable. If you use the CLR button for any reason, the very next button press is deleted. So if I made a typo, (EX: 365 instead of 360) and I hit CLR, the next button press afterwards, in this case '0' will trigger the whole line to be cleared.

**Comment by FreakyD777** [comment]
Agreed.  CLR seems to induce this issue.

**Comment by KJA1582** [comment]
Also, if the bug triggers, the flight plan and init page data gets deleted.

**Comment by turbofandude** [comment]
Resolved in 0.13+.
