### ISSUE TITLE
[BUG] - Revising flex temp on T/O FMS page does not recalculate VSpeeds (MD-FMD-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#236]
### Describe the bug

When changing the FLEX temp from the original input, the V speeds do not recalculate

### Steps to reproduce

Enter initial FLEX TEMP on T/O page
Complete remainder of T/O page
Confirm V Speeds
Enter new FLEX TEMP on T/O page

### Expected behaviour

S/B after changing flex temp, message CHECK/CONFIRM VSPDS should post in the scratchpad and V speeds should change to recalculated numbers and be shown in small font with leading asterisk

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Departure

07MT

### Arrival

07MT

### Cruise level

FL300

### ZFW

400K

### CG

27

### Fuel

20K

### Cost index

80

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
