### ISSUE TITLE
[BUG] - Dial-a-flap setting changes causes flaps to retract (MD-FC-11)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#238]
### Describe the bug

After setting the dial-a-flap to a number and moving the flap lever to the dail-a-flap range, changing the dial-a-flap setting to a number greater then the current setting causes the flaps to retract.  Setting a number less then the current drives the flap to that new setting.

### Steps to reproduce

Set dial a flap to 15
Set flap handle to dial a flap range
Change dial a flap setting to a higher number (say 20)

### Expected behaviour

S/B able to change dial-a-flap setting with flap handle in the dial-a-flap range and the actual flap position will follow.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v0.37
