### ISSUE TITLE
[BUG] - AFS reverts to heading hold mode from NAV mode when approaching a turn (MD-AFS-6)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#240]
### Describe the bug

When in NAV mode, the mode will sometimes switch from NAV to HEAD HOLD as the airplane approaches a waypoint with a turn in it

### Steps to reproduce

Observe AFS mode when NAV is engaged and approaching a turn

### Expected behaviour

S/B NAV mode stays engaged throughout a turn

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

07MT

### Arrival

07MT

### Cruise level

FL300

### ZFW

163k GW

### CG

24.9

### Fuel

20K

### Cost index

80

### Route

 HVR GTF BIL MLS ZITGA ACAKO  DORIA   

### Location

Approaching ZITGA when this happened

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Unfortunately, I do not see this happening. Can you provide a specific example that causes it?
