### ISSUE TITLE
[BUG] - APU start in flight (MD-APU-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#241]
### Describe the bug

At FL390 M0.81, the APU started

### Steps to reproduce

Attempt APU start using START/STOP switch at FL390/M.81

### Expected behaviour

APU has limitations on it's operational and start envelope as follows (hope this makes sense, I'm describing points on the curve, you can draw straight lines between these points to define each envelope):

- OPERATIONAL
- NO OPERATIONAL LIMITS = FL300 from -75C to -35F and -1000ft from -55C to 28C
- 75% GEN LOAD LIMITS = FL300 from -35C to -18C and -1000ft from 28C to 41C
- 50% GEN LOAD LIMITS = FL300 @ -18C, FL2900 @ -5C and -1000ft from 41C to 50C

- START ENVELOPE
- FL250 UP TO 375KIAS
- 375KIAS DOWN TO 10K FT
- 350KIAS AT 0FT

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL390

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in v0.42.01

**Comment by turbofandude** [comment]
Resolved in 1.0.35+
