### ISSUE TITLE
[BUG] - Aircraft wants to turn back to T/C point when T/C point is next on FMS 

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#244]
### Describe the bug

Following flight plan when plane reaches T/C waypoint it acts like T/C is a actual waypoint and does not advance to next waypoint starting turning back towards T/C 

### Steps to reproduce

Fly a flight plan and watch what airplane does when T/C waypoint is reached. 

### Expected behaviour

For the FMS to not act as if the T/C is a actual waypoint in the FMS 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

36000

### Departure

KONT

### Arrival

KOAK

### Cruise level

fl360

### ZFW

353.3

### CG

28

### Fuel

30.4

### Cost index

20

### Route

SNSHN5 COREZ DCT RGOOD EMZOH3

### Location

Reached T/C on FMS

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed as part of the new leg system
