### ISSUE TITLE
[BUG] - APPR/LAND Button instantly Activates LOC mode 

### ISSUE THREAD

**Issue by 717driver** [invernyx/md11-bugs#245]
### Describe the bug

Joining the approach I pressed APPR/LAND to arm the LOC and GS modes to intercept for the approach.  When I pressed it, it instantly went into LOC mod and turned hard to go track the LOC course, even though it was full scale deflection.  LOC should not activate until it is inside of 1/2 dot deflection. 

### Steps to reproduce

Join approach from a heading or connected NAV course and press APPR/LAND.

### Expected behaviour

 LOC should not activate until it is inside of 1/2 dot deflection, it should continue the active NAV/HDG mode instead of instantly activating LOC and tracking it, when at full scale deflection.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Approach

### Heading

300

### Altitude

5000

### Departure

KONT

### Arrival

KOAK

### Cruise level

FL380

### ZFW

305k lbs

### CG

28.6%

### Fuel

57000

### Cost index

35

### Route

SNSHN5 COREZ DCT RGOOD EMZOH3

### Location

Joining ILS 30 KOAK 

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.24+
