### ISSUE TITLE
[BUG] - Air System Controller Requires Reset to Function Properly

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#247]
### Describe the bug

On initial startup, air system is incorrectly configured (packs 1,2,3 off and bleed air 1,2,3, off). Recycling controller resumes correct operation.

### Steps to reproduce

Start cold & dark with no prior saved states
Bat ON
Ext Pwr ON
Pack 1,2,3 erroneously OFF
Bleed Air 1,2,3 erroneously OFF
Cycling system controller correctly turns all on

### Expected behaviour

System controller should assume correct function on initial power-up

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
Resolved with PR 66 (https://github.com/invernyx/md11/pull/66)
