### ISSUE TITLE
[BUG] - Loading RNAV Approach does not prompt transition after MIN PROF entry. 

### ISSUE THREAD

**Issue by 717driver** [invernyx/md11-bugs#249]
### Describe the bug

When loading an RNAV Approach into the FMC during preflight it does not prompt a transition on the approach after prompting for MIN PROF.  When you select the approach, it goes to the MIN PROF, but when you hit insert it goes back to the F-PLAN page and does not allow you to insert an approach transition

### Steps to reproduce

Click last en-route waypoint to LAT-REV and load STAR and desired approach procedure.  I selected the RNAV Z 24R and the RNAV Y 25L at KLAX and they both went to MIN PROF but then did not prompt for VIA waypoint.  For the  RNAV Z 24R transitioning from the IRNMN STAR, I need the DAHJR waypoint for the transition and it did not prompt that.  

### Expected behaviour

After MIN PROF prompt, it should then sequence to which VIA waypoint do you want to transition from?

### Evidence

Loaded in QA chat because file is too large.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0 AGL

### Departure

KOAK

### Arrival

KLAX

### Cruise level

FL410

### ZFW

295.1klbs

### CG

26.1

### Fuel

52000lbs

### Cost index

35

### Route

CNDEL5 SUSEY DCT EBAYE DCT BURGL IRNMN2

### Location

KOAK

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.25+
