### ISSUE TITLE
[BUG] - Engine fire agent low light not illuminating

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#25]
### Describe the bug

When pulling the fire handles and discharging either fire agent 1 or 2, the AGT LOW light does not respond

### Steps to reproduce

1. Load aircraft
2. Pull out any engine fire discharger and twist either left or right
3. Observe ENG FIRE AGENT LO warning
4. Realize that the AGT LOW lights on the overhead panel do not light

### Expected behaviour

The low agent lights must be lit when the aircraft reports a low agent fluid quantity.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48654776/db8ac76d-b141-46a3-866a-09f8a48f3fe7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

None

### Altitude

Not applicable

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed
