### ISSUE TITLE
[BUG] - landing weight incorrect

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#250]
### Describe the bug

the landing weight on the app page always displays in whole pounds

### Steps to reproduce

fly and click the to/app button

### Expected behaviour

follow the system unit and displays in thousands with one decimal

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Approach

### Altitude

-

### Departure

-

### Arrival

-

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Has long since been resolved
