### ISSUE TITLE
[BUG] - Autopilot trips off and aircraft pitches up at 1400 feet on coupled ILS approaches

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#251]
### Describe the bug

During coupled ILS approaches, the aircraft, on 6 of 7 attempted autolands, had the autopilot click off and the aircraft pitch up abruptly at approximately 1400 feet. Only one successful autoland accomplished. 

### Steps to reproduce

Fly a coupled ILS (attempt an autoland) and, before or just after you get a green “dual Land” annunciation (successful auto-land system  test passes), the autopilot will disconnect and the aircraft pitches up.

### Expected behaviour

The MD-11, if it fails an autoland test would fail active and turn to a single land annunciation. The autopilot may click off, but it would not pitch up abruptly. 

### Evidence

https://www.youtube.com/watch?v=0WnGFuo3x9c

Go to the 26:10 mark and play it.

![image](https://github.com/invernyx/md11-bugs/assets/148719444/bc439576-a7e8-4342-bee0-06c0a60472dc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Pitch

4.0 nose up

### Bank

0

### Heading

163

### Altitude

1,500 feet 

### Departure

Kpae

### Arrival

Kpae

### Cruise level

3000

### ZFW

369.1

### CG

28

### Fuel

57

### Cost index

81

### Route

KPAE to kpae

### Location

Ils 16R at KPAE

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
This has happened to me a couple of times.  From my observations, it coincides with DUAL LAND engaging.

**Comment by kdries** [comment]
Happened on the ILS25L approach for EDDF at around the same spot where on previous attempts the low speed protection kicked in. Engines spooled up followed by what appeared like a right wing stall and nose dive. 
Cargo: 22046 lbs
Approx FOB: 55k lbs
![image](https://github.com/invernyx/md11-bugs/assets/6001596/a367d825-2c52-4081-9509-f5325a982c6c)

**Comment by turbofandude** [comment]
This should be long resolved now.
