### ISSUE TITLE
[BUG] - APU Automatically Shuts Down After Engine Start

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#253]
### Describe the bug

After starting engines, APU air will deselect and APU will automatically shut off

### Steps to reproduce

Start engines
Observe Air Sys panel and APU
APU will shut itself off

### Expected behaviour

APU should remain running until APU Air deselected on Air Sys Panel or APU is shutdown via APU Panel ON/OFF switch

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Per FCOM Vol 3

> "When the APU is started through the APU Gen switch on the electrical overhead panel [and] the IDGs are supplying the generator buses, the APU shuts down 90 seconds after APU air is no longer being used."

This is intentional behaviour. If you started the APU differently, you did not indicate as such in the steps to reproduce, and we request that you open up another bug with this issue referenced (#253).
