### ISSUE TITLE
[BUG] - EFB: Unable to scan QR code for Charts

### ISSUE THREAD

**Issue by opticalgenesis** [invernyx/md11-bugs#255]
### Describe the bug

Due to the dark screen the QR code is on, my phone will not scan it, I've seen it on other QR codes on dark/black backgrounds. Additionally, the code for manual connection does not appear

### Steps to reproduce

- Open Charts tab while unauthed with Navigraph
- Try to scan QR code or enter code manually

### Expected behaviour

- The QR code to scan, and the code to show

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This has been fixed with some refactoring of the Charts page UI
