### ISSUE TITLE
[BUG] - The EIS selection button for "DATA" does not cause the data to be displayed under the waypoint on the NAV display

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#256]
### Describe the bug

The EIS selection button for "data" does not cause the data to be displayed under the waypoint on the NAV display

### Steps to reproduce

Press the "DATA" button on the EIS and look at the NAV display. The information from the FMS (time, altitude, airspeed) should be display under the associated waypoint from the FMS. 

### Expected behaviour

I expect that, upon selecting "DATA" on the EIS, that I will be able to see time, altitude and speed under each waypoint on the NAV display.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Departure

KJFK

### Arrival

KJFK

### Cruise level

FL230

### ZFW

359.6

### CG

28

### Fuel

31.2

### Cost index

80

### Route

KJFK MERIT ROBUC3 KBOS

### Location

KJFK

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
confirmed

**Comment by turbofandude** [comment]
Works in 0.16.0+
