### ISSUE TITLE
[BUG] - Cockpit shadow is only the cockpit

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#259]
### Describe the bug

The shadow when in the cockpit is ONLY the cockpit

### Steps to reproduce

Get lighting which shows a shadow in the cockpit camera

### Expected behaviour

The whole airframe should have a visible shadow

### Evidence

https://i.imgur.com/o6Oduwi.jpeg

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
External fuselage and wings added to interior models
