### ISSUE TITLE
[BUG] - FCP HDG & IAS Knob should "wake up" from blank display when spinning knob

### ISSUE THREAD

**Issue by 717driver** [invernyx/md11-bugs#260]
### Describe the bug

When you're in FMS Speed or NAV mode in, the IAS and HDG displays are blanked out, it should not require a click before ability to adjust IAS or HDG is enabled.  You can select a heading or speed before pushing or pulling the knob.

### Steps to reproduce

Engage FMS Speed or NAV mode, then try to spin in an IAS or HDG number into the respective window.

### Expected behaviour

Allow selection of an IAS or HDG choice before required to push or pull the knob.  The pre-select once in HDG and IAS works correctly.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Pitch

+4 degrees

### Bank

0 degrees

### Heading

250

### Altitude

3000 AGL

### Departure

KMDW

### Arrival

KMLI

### Cruise level

FL220

### ZFW

295

### CG

24.8

### Fuel

40

### Cost index

35

### Route

22L PEKUE DCT PIGGG DCT PIPPN RW27

### Location

KMLI ILS 27

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@turbofandude I believe a fix for this issue has already been implemented?

**Comment by turbofandude** [comment]
This now happens as of 0.22+
