### ISSUE TITLE
[BUG] - APU Automatically Shuts Off After Engine Start

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#262]
### Describe the bug

Approximately 90 seconds after starting the third engine, APU Air deselects itself and initiates automatic shutdown of APU

### Steps to reproduce

1. Bat/Ext Power ON
2. Recycle Air controller for proper panel automatic configuration #183 
3. Start APU via ELEC Panel
4. Turn APU Air On (will erroneously do this automatically IAW the above bug)
5. Start engines normally
6. Following third engine start, observe APU Air deselects itself without pilot input approximately 90 seconds after initiating third engine start
7. This deselection of APU Air initiates the auto-shutdown of the APU (correct function)

### Expected behaviour

APU Air should not shut off without direct pilot input. While the FCOM mentions with 3x IDGs powering their respective buses provided APU Air is not being used. This is in reference to the APU Air switch being ON, not if the bleed air is actually required. Therefore so long as the APU Air switch is in the ON position, the APU should continue running.

This feature is designed into the APU for the following scenario:
APU is started via APU START/STOP -- starting the APU this way inhibits the APU Air shutdown logic
APU Air ON for engine start
F/O presses APU Air OFF and does not verify APU shuts down (as it wont based on how it was started) and APU continues to run
After 90 seconds of APU Air OFF and all 3x IDGs powering their buses, system will automatically shut down APU.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Do you have reference for this? The FCOM isn’t necessarily clear (and can be wrong) but I’m curious as to where you have found this information

**Comment by GR1MMly** [comment]
Unfortunately there is no specific reference I am aware of. The best I can do is offer personal experience and describe how "APU air not being used" is interpreted.

**Comment by TheFightingRaven** [comment]
no verification needed, he is the verification and it's in the manual just need to look up the exact logic

**Comment by turbofandude** [comment]
This should be correct now.
