### ISSUE TITLE
[BUG] - Landing gear wheels not animated (MD-GEN-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#264]
### Describe the bug

When in motion, FWD or REV, the landing gear wheels are static

### Steps to reproduce

Move FWD or backwards

### Expected behaviour

Wheels roll as a function of ground speed

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by boomerc154** [comment]
Landing gear not animated. Suspension struts seem to function though.
