### ISSUE TITLE
[BUG] - Climb Performance (MD-PERF-1)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#265]
### Describe the bug

While climbing at CLB LIM of 104.5, fuel 60k lb, GW 400k lb, STD day temps, no winds, the VS at (1)250KIAS and 5k ft is 4,300ft/min, at (2)250KIAS and 10k ft is 3,600ft/min, at (3) 350KIAS and 15k ft is 3,800ft/min, at (4)350KIAS and 20k ft is 3,300ft/min, (5)350KIAS and 25k ft is 2,300ft/min, (6)M0.82 and 30k ft is 2,600ft/min, (7)M0.82 and 35k ft is 1,800ft/min

### Steps to reproduce

see descrip

### Expected behaviour

S/B (1) = 5,000ft/min; (2) = 4,750ft/min; (3) = 4,150ft/min; (4) = 3,250ft/min; (5) = 2,750ft/min; (6) = 			3,000ft/min; (7) = 2,250ft/min

### Evidence

These numbers came from flight test data on a PAX equiped with GE engines

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
I've spoken in great detail with our FDE engineer and he's given me a lot of information which will apply a "wontfix" label. According to him:
> The FDE only allows setup in one flight condition for many of its parameters, and that's the case here. I can therefore define ascent/descent rates based on engine power for all altitudes up to cruise, but only in one condition, in this case MTOW. Once that is set, the MSFS black box will then vary this ascent profile based on aircraft weight. This bug report indicates a specific defined condition set by the user and requires the profile to be corrected, therefore showing a misunderstanding of the way that the FDE system works.
> [If we were to change the performance characteristics to replicate this expected behaviour] there would be no guarantee that the aircraft would achieve the appropriate performance at MTOW, or indeed any other weight
