### ISSUE TITLE
[BUG] - Stall Speeds (MD-PERF-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#267]
### Describe the bug

At 12k ft, GW=420k lb, STD day temp, no wind, the stall speeds at various high lift settings are 
SLAT/FLAP/Vs (KIAS) 		
RET  0	149 		
EXT	0	137 		
EXT	10	133 		
EXT	15	133 		
EXT	20	132 		
EXT	25	130 		
EXT	28	130 		
EXT	35	130 		
EXT	50	130

### Steps to reproduce

Initiate stall at conditions in descrip

### Expected behaviour

S/B	Vs = 155; 127; 125; 121; 119; 118; 118; 116; 112

### Evidence

From AFM

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This issue has been stale for quite some time, and there's been various flight dynamics updates since this issue has been open. Try this again and open up a new issue if it's still incorrect <3
