### ISSUE TITLE
[BUG] - Fuel flow units (MD-AV-5)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#268]
### Describe the bug

With imperial units chosen on the EFB, and shown on the ENGINE SYN page, the EICAS page seems to be showing fuel 	flow in kg/hr

### Steps to reproduce

View EAD page

### Expected behaviour

S/B showing lb/hr to match EFB setting

### Evidence

![FlightSimulator_2023_11_02_20_03_55_476](https://github.com/invernyx/md11-bugs/assets/148836830/8521fc04-577d-45d8-b541-36601c5b948d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL350

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fuel flow units were indeed wrong and have now been corrected in 0.13+
