### ISSUE TITLE
[BUG] - Pitch mode transition from VS to HOLD (MD-AFS-7)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#269]
### Describe the bug

When climbing/descending in VS mode, the pitch control mode switches from VS to HOLD approximately 2k ft from the target altitude and the airplane pitches up/down rapidly until the target altitude nears

### Steps to reproduce

see descrip

### Expected behaviour

S/B VS mode is retained until ALT hold engages and smoothly reduces VS to zero at target altitude

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

Between ground and FL390

### Departure

07MT

### Arrival

07MT

### Cruise level

FL350

### ZFW

340k

### CG

27

### Fuel

60k

### Cost index

80

### Route

N/A

### Location

Montana

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should not be happening anymore
