### ISSUE TITLE
[BUG] - EAD Thrust limit indication color in manual select mode (MD-AV-6)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#271]
### Describe the bug

When manually selecting thrust setting in the FMC, the thrust rating on the EAD remains magenta (see blue highlighted area in pic below)

### Steps to reproduce

Manually select thrust mode in THRUST LIMIT page on FMC and observe the thrust limit indication on the EAD

### Expected behaviour

S/B thrust rating on the EAD turns white when manually selecting an FMS thrust setting

### Evidence

![FlightSimulator_2023_11_03_16_53_46_998](https://github.com/invernyx/md11-bugs/assets/148836830/24c57e6c-4490-471d-8b13-c11a2e688429)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified v.37
