### ISSUE TITLE
[BUG] - After engine start an oil drop of 2 quarts should occur

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#272]
### Describe the bug

The oil does not decrease after engine start

### Steps to reproduce

Start the engine. The engine oil quantity is at 22 quarts and stays at 22 quarts after start. The oil should decrease by 2-3 quarts after start and return to 22 quarts a few minutes after shutdown.

### Expected behaviour

The oil should decrease by 2-3 quarts after start and return to 22 quarts a few minutes after shutdown.

### Evidence

N/A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
already mentioned in previous report

**Comment by FreakyD777** [comment]
I can't find another PR regarding oil qty during engine start.  That said, according to the McD production flight test procedure, the qty should decrease by 4-6 qts/liters on the GEs; 8-16 qts/liters on the PWs
