### ISSUE TITLE
[BUG] - Rudder trim inop (MD-FC-12)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#273]
### Describe the bug

When inputting rudder trim at various altitudes and speeds, no change in yaw or roll is observed.
(see MD-FC-9 for additional trim bug)

### Steps to reproduce

see descrip

### Expected behaviour

S/B airplane attitude changes in yaw and roll with rudder trim input

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

Various

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in V0.42.01

**Comment by GenericNerd** [comment]
This will be resolved in the next version
