### ISSUE TITLE
[BUG] - Aileron trim input (MD-FC-13)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#274]
### Describe the bug

When inputting aileron trim at various altitudes and speeds, no change in roll is observed.  In order for the aileron trim to "kick in", a control wheel input is required, at which point the control wheel jerks to the aileron trim input
(see MD-FC-9 for additional trim bug)

### Steps to reproduce

Straight and level flight
AP OFF
Input aileron trim (right or left)
Observe aileron trim know moving
Observe no roll input/no wheel input
Slightly touch wheel hardware IRL
Observe wheel jerk to AIL input you put in above and airplanes starts to roll

### Expected behaviour

S/B aileron trim input displaces control wheel in real time w/out any additoinal wheel inputs required

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

Various

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in V0.42.01

**Comment by GenericNerd** [comment]
This will be resolved in the next version
