### ISSUE TITLE
[BUG] - Go-around Logic

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#277]
### Describe the bug

The Go-around function (TOGA) is flawed

### Steps to reproduce

Establish the aircraft on an ILS final, fully configured.
Preset the missed approach A/S, HDG and Alt on the FCP.
Upon missed approach, Press the TOGA switch and witness the throttles going from idle to max and back to idle several times, even with the auto-throttles disconnected.

### Expected behaviour

With the "thrust limit" in "auto", and the aircraft established on final and configured, the thrust limit on the N1 gauge should automatically be set to GA. Upon pressing TOGA, the aircraft should exit ILS mode and enter Heading Hold mode. The throttles should advance to GA thrust, and the command bars should pitch up to hold your current airspeed.

### Evidence

https://www.youtube.com/watch?v=fJFgb6XqRSE

18 minute go-around video. Sorry!

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

kjfk

### Arrival

kjfk

### Cruise level

3000

### ZFW

370k

### CG

25

### Fuel

44000

### Cost index

50

### Route

kjfk

### Location

kjfk

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I think you are experiencing a different bug than you think, the ga button doesn't work and then you roll into the low speed protection bug

**Comment by 017941** [comment]
Okay, thank you.Sent from my iPhoneOn Nov 10, 2023, at 3:03 PM, TheFightingRaven ***@***.***> wrote:﻿
I think you are experiencing a different bug than you think, the ga button doesn't work and then you roll into the low speed protection bug

**Comment by turbofandude** [comment]
Please let us know if this is still occuring via a new bug.
