### ISSUE TITLE
[TODO] - Radio frequencies set in Hertz (P3D only)

### ISSUE THREAD

**Issue by pburnay-invernyx** [invernyx/md11-bugs#278]
### Describe the bug

P3D event IDs to set COM frequencies in hertz (for 8.33 kHz) does not match MSFS.

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Simulator

P3Dv4, P3Dv5, P3Dv6

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved in 0.46+
