### ISSUE TITLE
[BUG] - Left main landing gear animation (MD-GEN-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#280]
### Describe the bug

The LEFT main landing gear animation shows the wheels spinning along an axis normal to the truck assembly

### Steps to reproduce

From outside view, raise/lower landing gear

### Expected behaviour

S/B animinated same as RIGHT main gear

### Evidence

![FlightSimulator_2023_11_08_21_02_08_018](https://github.com/invernyx/md11-bugs/assets/148836830/1a7bdadf-e502-4459-a24a-3dbc7f0f2f39)
![FlightSimulator_2023_11_08_21_02_09_654](https://github.com/invernyx/md11-bugs/assets/148836830/11ad5b22-0b3f-4a6f-91dd-77c76798fe71)
![FlightSimulator_2023_11_08_21_02_11_114](https://github.com/invernyx/md11-bugs/assets/148836830/ded0152c-6427-4318-82ec-02049e7cafce)
![FlightSimulator_2023_11_08_21_02_12_725](https://github.com/invernyx/md11-bugs/assets/148836830/13cd9645-6964-4b68-ba17-6ed6d344f4d7)
![FlightSimulator_2023_11_08_21_02_14_197](https://github.com/invernyx/md11-bugs/assets/148836830/621e41bd-4943-4304-b1e5-997c1902b1b6)
![FlightSimulator_2023_11_08_21_02_15_696](https://github.com/invernyx/md11-bugs/assets/148836830/594cb512-3e92-4185-8a7a-33215248edd0)
![FlightSimulator_2023_11_08_21_02_17_316](https://github.com/invernyx/md11-bugs/assets/148836830/bb79a8a3-27be-4d36-a3ad-5e502321a2cc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by SunKing135** [comment]
Had the same issue today. Left main landing gear rotates and the entire animation of the gear system shudders and stutters.

**Comment by turbofandude** [comment]
Resolved in 0.21+
