### ISSUE TITLE
[BUG] - Door 1R modeling issue with door open (MD-GEN-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#281]
### Describe the bug

Door 1R when opened shows a window in space

### Steps to reproduce

Open door 1R

### Expected behaviour

S/B no window

### Evidence

![FlightSimulator_2023_11_08_20_19_41_196](https://github.com/invernyx/md11-bugs/assets/148836830/7a326e2f-9d9e-4d93-b948-2adc07a81fcd)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.22+
