### ISSUE TITLE
[BUG] - Nose wheel light leak when retracted (MD-GEN-5)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#282]
### Describe the bug

Nose wheel taxi and landing light leaks through the nose gear door structure with gear up

### Steps to reproduce

Retract gear at night, turn on taxi or landing lights

### Expected behaviour

S/B no light leak present

### Evidence

![FlightSimulator_2023_11_08_21_01_34_311](https://github.com/invernyx/md11-bugs/assets/148836830/ceb3ba8b-bd2d-4fe5-99eb-772e0e937041)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
Aaron, can you inhibit the nosewheel lights with the gear up?

**Comment by arwasairl** [comment]
> Aaron, can you inhibit the nosewheel lights with the gear up?

I can't control this. This either needs to be inhibited with code or a model change is required to add 2 nodes to the bulbs of the gear so that  it follows the gear's position.

**Comment by sersanchez** [comment]
I have the same behavior

**Comment by GR1MMly** [comment]
Same, taxi and land lights do not animate with the gear (light sources remain in extended position when gear retracted)

**Comment by turbofandude** [comment]
Should be long resolved
