### ISSUE TITLE
[BUG] - Door 3R and 3L does not open (MD-GEN-6)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#283]
### Describe the bug

Door 3R and 3L are not animated (PAX variant)

### Steps to reproduce

Open door 3L and 3R and observe

### Expected behaviour

Door 3L and 3R open on command

### Evidence

N/A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
@FreakyD777 Which variant is this and does it happen in the interior or exterior or both?

**Comment by FreakyD777** [comment]
PAX... revised description to add
