### ISSUE TITLE
[BUG] - Snow through the cockpit

### ISSUE THREAD

**Issue by ericlin26** [invernyx/md11-bugs#285]
### Describe the bug

Snow through the cockpit and cargo deck light

### Steps to reproduce

Adjust weather to snow/rain.The snowflakes/raindrops will through the cockpit, and the cargo deck light is effectived by the outdoor light

### Expected behaviour

The snowflakes/raindrops shouldn't through the cockpit model, and the cargo deck light should be effectived by the cargo door open or not.

### Evidence

1. It's the same situation in the cockpit  
![Screenshot (760)](https://github.com/invernyx/md11-bugs/assets/150325239/133a6d46-a461-42c0-933e-28e4569d8756)  
###
2. Outdoor light effectived cargo deck light
![Screenshot (761)](https://github.com/invernyx/md11-bugs/assets/150325239/2811ef1d-e05f-4f16-aa22-931c641fd876)  
![Screenshot (762)](https://github.com/invernyx/md11-bugs/assets/150325239/540004c0-9f00-48ce-b0c3-7170983ec4ca)  

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
@jhattermann Add a mesh around the interior model that blocks this. Assign it to **EnvironmentOccluder**
