### ISSUE TITLE
[TODO] - Fix missing AFF_FLOOD_67 Node and OVHD flood lights

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#286]
### Describe the bug

Read title

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Evidence

N/A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
AFF_FLOOD065 and AFF_FLOOD064 are the ones you're looking for
