### ISSUE TITLE
[BUG] - Fan Blades Blurr Mesh

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#288]
### Describe the bug

Fan blade blurred mesh visible with engines off

### Steps to reproduce

Spawn

### Expected behaviour

Blurr mesh not loaded during engine off/low speed

### Evidence

![Screenshot (358)](https://github.com/invernyx/md11-bugs/assets/2170028/9445e107-9477-47a1-b635-458c922e98cb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
I seem to have the opposite issue, currently in flight and not seeing a blur mesh
![image](https://github.com/invernyx/md11-bugs/assets/150094502/e6337ba5-f408-48ff-9daa-fef4be30d11d)

**Comment by jason3580** [comment]
I see this as well, the fan blades do not move when the engines are on and running

**Comment by GenericNerd** [comment]
This should be fixed in the next version
