### ISSUE TITLE
[BUG] - EFB(service page) html nodes mess

### ISSUE THREAD

**Issue by ericlin26** [invernyx/md11-bugs#289]
### Describe the bug

The EFB's service page is a bit confusing

### Steps to reproduce

Screen resolution: 2560*1440(2k)
I don't know if it was intentionally designed that way.

### Expected behaviour

if it's not, the service page html nodes should be more flexiable in the different screen resolution.

### Evidence

![Screenshot (763)](https://github.com/invernyx/md11-bugs/assets/150325239/522a4af9-ff93-4dd6-96e5-6ef209a3c788)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
While we do plan to give the services page a redo sooner rather than later, this is expected behaviour and correct.
