### ISSUE TITLE
[BUG] - Rear cargo door on freighter does not open in MSFS

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#290]
### Describe the bug

Animation has not been set in Babylon.js

### Steps to reproduce

Open Max file
Select cargo door
Observe 0 animations set

### Expected behaviour

Animations must be set in order for door to open

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48654776/788f344c-389b-4be3-8463-4e169357c00f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by PointBlank66** [comment]
just to add to this post. It looks like part of the support hinge does fold out but still missing a lot of its model
![image](https://github.com/invernyx/md11-bugs/assets/4239471/12c4ca11-900a-4a85-8763-2d4f1e70b76d)

**Comment by slowreload** [comment]
Can confirm that the rear door still doesnt open in .13

**Comment by turbofandude** [comment]
Resolved in 0.21+
