### ISSUE TITLE
[BUG] - EFB max payload input is limited to maximum KG when inputting LBS

### ISSUE THREAD

**Issue by Benismobil** [invernyx/md11-bugs#291]
### Describe the bug

EFB Cargo refuses to allow a value higher than 91962, which is the maximum KG allowed, not LB

### Steps to reproduce

input a weight higher than 91962kg
select fuel quantity

### Expected behaviour

cargo weight will automatically default to 91962

### Evidence

![1250410_20231108224649_1](https://github.com/invernyx/md11-bugs/assets/149978360/e818dc8b-117b-4f00-95ca-61d696523fbd)
![1250410_20231108224656_1](https://github.com/invernyx/md11-bugs/assets/149978360/3856d606-d2fa-478f-8029-17818d1c56fb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
The entire EFB is a bit odd, because when set to KGs it outputs the payload in what is the LB value. The value is fine on the SD and in the CDU is once again in LBs (on a few pages) but actually with the correct unit.

**Comment by nIn9R** [comment]
confirming occuring for me as well. current workaround: Load with KG values, save payload, switch settings back to LBS.

**Comment by Juanandonly1** [comment]
Also had this issue with the Md-11F

**Comment by TheFightingRaven** [comment]
fixed in 0.15
