### ISSUE TITLE
[BUG] - Selecting FMS LSK on "END OF F-PLN" freezes plane

### ISSUE THREAD

**Issue by cptnuss-ops** [invernyx/md11-bugs#292]
### Describe the bug

I accidently clicked the LSK on the "END OF F-PLN"-Line while creating a flight plan on the F-PLN-Page. This caused the LSK to be stuck and no other button could be pressed.

### Steps to reproduce

1.) Load Plane and power up
2.) Init FLT-PLN and select SID
3.) Continue to enter route with airways
4.) Click on left LSK on the Line that has the "------END OF F-PLN------"
5.) Observe LSK-Button to be stuck down
6.) Verify no other button or switch can be clicked.

### Expected behaviour

LSK-Button should not be stuck and no action should be triggered when selecting this line.
Also the other buttons should work, but I guess this resolves with not stuck anymore :).

### Evidence

![grafik](https://github.com/invernyx/md11-bugs/assets/69425888/225bfd28-bbe2-4441-b042-e62de24c7c85)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

EDDH

### Arrival

EKCH

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

EDDH/23 LUGE2B LUGEG P605 GESKA/N0456F240 Z711 MONAK MONA3C EKCH/22R

### Location

Parked at EDDH on stand.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
has this happened multiple times?

**Comment by tomkaare** [comment]
Similar thing happened to me today also. I was in cruise and pressed the LSK next to the airport (At least that was my intention, could have been the LSK next to end of flt-plan. The screens in the aircraft froze and I could not press anything with the mouse. The aircraft was still flying and continued to responded to joystick inputs.

**Comment by cptnuss-ops** [comment]
> has this happened multiple times?

On my flight after work I did not tried to provoke this. I'll try it later today and keep you updated :).

**Comment by JBPFlight** [comment]
Smilar thing when i accidentally pressed mid flight, airccraft ccontinued in sim but was not controllable vvia the aircrafts own systems, only had basic controls

**Comment by cptnuss-ops** [comment]
I can add no more Information right now, sorry.

**Comment by turbofandude** [comment]
Can confirm this is a bug - tested myself.

**Comment by turbofandude** [comment]
Fixed in my copy and will be fixed in 0.12.0+
