### ISSUE TITLE
[BUG] - FMS erroneously saying "not in database" 

### ISSUE THREAD

**Issue by roesti** [invernyx/md11-bugs#293]
### Describe the bug

Can't enter airways / connected waypoints (not in database)

### Steps to reproduce

AIRAC: 2311 (updated the MD-11 via Navigraph Hub)

Route: LHBP/13L GILE2B GILEP DCT GASNA DCT DITIS DCT RAPET Z93 UNAVI Z715 KULOK L984 SULUS Z12 COSJE T892 RIDSU Z114 DONAB Y180 BITBU Y181 GOPAS N852 GESLO GESL6X EBLG/ALH1A.I22L

When selecting the waypoint RAPET on the "F-PLN"-Page, going to "AIRWAYS", it's not possible to enter the following route via airways.

Entering the airway "Z93" works, but when entering the waypoint UNAVI, the MCDU shows "NOT IN DATABASE". Also tried to fill in airways from a later waypoint onwards like from COSJE (T892 -> RIDSU), still gives the same error.

Entering the complete route manually (waypoint by waypoint without using airways) works fine.

### Expected behaviour

Accepting the correct airway and subsequent waypoint and add it to the Flight Plan in the FMS without getting the error "not in database".

### Evidence

Tried to enter the waypoint "UNAVI" via Airway Z93 from RAPET, same behaviour for following airways (e.g. UNAVI ->Z175 > KULOK also doesn't work and following..)

![AirwaysMD11](https://github.com/invernyx/md11-bugs/assets/287454/f80f235a-1c1c-46a5-95e1-8a6ffabd7d55)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

496 (ground)

### Departure

LHBP

### Arrival

EBLG

### Cruise level

FL400

### ZFW

342.5

### CG

27.8

### Fuel

47.7

### Cost index

125

### Route

LHBP/13L GILE2B GILEP DCT GASNA DCT DITIS DCT RAPET Z93 UNAVI Z715 KULOK L984 SULUS Z12 COSJE T892 RIDSU Z114 DONAB Y180 BITBU Y181 GOPAS N852 GESLO GESL6X EBLG/ALH1A.I22L

### Location

At gate.

### Agreement

- [X] Yes

**Comment by wagoozen1** [comment]
I got the same with my route:

BERGI L602 NALAX L46 GETNO DCT APSOV DCT
SUNOT NATA RIKAL N440A YRI J560 YQB T781 PESAC Q921 SOKYE Q905 AGLUK
Q941 TAMKO Q852 KANUR Q806 TUKIR IMEBA9

Navadata sues 2311

**Comment by ProfessorMadman** [comment]
Same with this route, specifically M197 -> ENHAQ on AIRAC 2311

VALK3S IDRID L980 LAM L179 ICTAM M197 ENHAQ DCT GAJIT DCT GAPLI DCT OMOKO DCT 48N015W 48N020W 47N030W 43N040W 39N045W 34N050W 28N055W 22N060W DCT OBIKE M576 MNOLO ULUBA1

Could not enterENHAQ in LAT REV from M197 - received NOT IN DATABASE message

**Comment by TheFightingRaven** [comment]
this issue I believe comes down to the fms not recognises waypoints that it should

**Comment by wagoozen1** [comment]
Just tested this out route CYYZ - EHAM Q913 TOPPS N917A JOOPY (message: Not in database) let me know if i need to test something out.

**Comment by turbofandude** [comment]
We are now unable to recreate this. We've made some changes to the airways code that will resolve any issues we caused, and it seems the issue with updating the data itself is resolved. We recommend reinstalling the updated nav data via the Navigraph Hub.
