### ISSUE TITLE
[BUG] - External equipment model penetration and wrong position

### ISSUE THREAD

**Issue by ericlin26** [invernyx/md11-bugs#294]
### Describe the bug

Carts and cables model penetration, and chocks floating in the air

### Steps to reproduce

1. The ASU and GPU is sinking way more in the ground.  
2. The GPU’s cabel model is penetration under the ground.
3. Main wheel chocks is floating in the air.

### Expected behaviour

Main wheel chocks should attach to the ground.

### Evidence

1. Current wheel chocks position  
![Screenshot (764)](https://github.com/invernyx/md11-bugs/assets/150325239/9e7061c8-ac33-460e-9ccb-97cd01947d3b)
2. Model penetration  
![Screenshot (766)](https://github.com/invernyx/md11-bugs/assets/150325239/0fada830-e1b5-4d0b-9f23-8b05d99ce10a)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
@SimbiosiGT Add a dummy as a parent object to all ground objects and set it as an animation of the gear compression OR request a new modeldef from Collin

**Comment by arwasairl** [comment]
This has been fixed in the latest model update.
