### ISSUE TITLE
[BUG] - No Button Animation for Misc Button

### ISSUE THREAD

**Issue by firefighter1990** [invernyx/md11-bugs#295]
### Describe the bug

Missing Animation for Misc Button

### Steps to reproduce

When pushing the Misc Button on the pedestral, the Misc Page opens but not Button animation is shown.

### Expected behaviour

The Button should do a pressed animation

### Evidence

<img width="169" alt="FlightSimulator_3C1S65pkN7" src="https://github.com/invernyx/md11-bugs/assets/75794827/1a28c3b5-a4d9-4087-af51-3604726b65f1">

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Button is animated and tagged, but does not animate in sim. Code issue?

**Comment by joon44** [comment]
I programmed this to my Streamdeck with the md11_ped_sd_misc_bt lvar and it is animated when I press the button. So only the mouse clickspot is missing.

**Comment by tebeso** [comment]
@joon44 how do you manage that? do you send a value 1 and then value 0 to that lvar to trigger a button push?

**Comment by joon44** [comment]
> @joon44 how do you manage that? do you send a value 1 and then value 0 to that lvar to trigger a button push?


Yes.

Method 1)
Button press:
Set 1
Pause 100ms
Set 0

Method 2)
Button press
Set 1
Button release 
Set 0

**Comment by turbofandude** [comment]
Duplicate - resolved in 0.25+
