### ISSUE TITLE
[BUG] - Nav Light Display Only When Beacon Lights Are On

### ISSUE THREAD

**Issue by JordxnE** [invernyx/md11-bugs#296]
### Describe the bug

The navigation lights will not display unless the beacon lights are triggered.

### Steps to reproduce

TO REPRODUCE; 

Toggle Navigation Lights via the Navigation light switch in the cockpit. Check exterior to verify there are no navigation lights on.
Toggle Beacon Lights with Navigation light switch on you will now see outside of the cockpit that the beacon lights and nav lights are on 

### Expected behaviour

The expected behaviour is that the navigation lights would turn on via their own switch without the use of the beacon lights.

### Evidence

![FDX4](https://github.com/invernyx/md11-bugs/assets/63637905/03eb546d-5518-4266-834d-53a7dd8343f0)
![FDX5](https://github.com/invernyx/md11-bugs/assets/63637905/30a68beb-1185-4ca8-a0ce-758498701e85)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [x] Yes

**Comment by cptnuss-ops** [comment]
I've observed this as well.

**Comment by JordxnE** [comment]
Adding for further context, After speaking to Mountain Man B in discord, we have discovered that by actually setting a nav light switch via your yoke, you can actually enable the nav light without the use of the beacon light. With that said the nav light will not be turned on via the set binding unless you hold down a button assigned on your joystick. The nav light is also affected by the switch in the cockpit however it is not link.

**Comment by Alex6511** [comment]
Hardware binds always override aircraft behavior in MSFS, the PMDG and Fenix have the same thing where binding the light switches makes them turn on, regardless of aircraft state. On the Fenix you can turn the strobes on if the planes not even connected in the battery.

**Comment by bassplane** [comment]
Can confirm this as well MD-11 pax.

**Comment by turbofandude** [comment]
Fixed in 0.13+
