### ISSUE TITLE
[BUG] - Digital Standby doesn't exist?

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#297]
### Describe the bug

Even though Digital Standby is enabled in the EFB, I retain the analog standby instr.s

### Steps to reproduce

Load plane
See manual standby instruments
in efb settings change from manual to digital (or recycle)
instruments do not change

### Expected behaviour

Instruments should change to digital

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/6ed409ae-0cba-4bfa-96e3-ffee0a750a77)
![image](https://github.com/invernyx/md11-bugs/assets/150094502/abf8327a-1dc8-4745-a8e2-10faaa5ea342)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by kaiguner78** [comment]
I tried it in the freighter model and it worked. Have you saved your config? It only changes after you hit the "SAVE" button.

**Comment by dr71205** [comment]
I'm a moron KEKW
