### ISSUE TITLE
[BUG] - Full / max reverse. Sim freezes

### ISSUE THREAD

**Issue by Morst04** [invernyx/md11-bugs#298]
### Describe the bug

When applying full throttle og full reverse and using brakes - sim freezes

### Steps to reproduce

Using bravo. Configured for 3 throttles. Max trust og max reverse - sim freezes. And have to restart. 

### Expected behaviour

Not freezing. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
haven't observed this myself, can you add more context when it happens again
