### ISSUE TITLE
[BUG] - Transponder box 1 key has no clickspot

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#299]
### Describe the bug

Transponder box 1 key has no clickspot

### Steps to reproduce

Try to click the 1 key on the transponder keypad. I dare you... :P

### Expected behaviour

The 1 key does have a working clickspot

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL340

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Extra inop clickspots on the transponder box: XPNDR systems 1/2 switch and ALT RPTG switch

**Comment by jbinner** [comment]
XPNDR button 1 not clickable, +1

**Comment by CaptainGongShow** [comment]
Still Inop in latest release 0.11

**Comment by DLH9KA** [comment]
+1 here

**Comment by Hawks1326** [comment]
+1

**Comment by Dennis380** [comment]
+1

**Comment by Dennis380** [comment]
+1

**Comment by Jannik1211** [comment]
+1

**Comment by Vekant** [comment]
+1

**Comment by GenericNerd** [comment]
@jhattermann Not yet been fixed in the latest version within the MSFS project.
