### ISSUE TITLE
[BUG] -addon freezes

### ISSUE THREAD

**Issue by henkhugo** [invernyx/md11-bugs#300]
### Describe the bug

Whole MD11 addon freezes

### Steps to reproduce

When entering a flight plan the entire addon freezes. Not MSFS, just the MD11

### Expected behaviour

That it does not crash

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This is not enough information to reproduce the issue, and the FMS issue template should be used instead. Please refile
