### ISSUE TITLE
[BUG] - Battery discharge

### ISSUE THREAD

**Issue by henkhugo** [invernyx/md11-bugs#301]
### Describe the bug

Battery continues to discharge with APU running

### Steps to reproduce

Load aircraft, turn on battery, start APU, cycle systems to fix that bug, APU online but system still says battery discharging
![20231109113823_1](https://github.com/invernyx/md11-bugs/assets/150338137/3fc5b378-3618-4e68-b601-c130dc8ff7aa)
![20231109114928_1](https://github.com/invernyx/md11-bugs/assets/150338137/20dcd81b-886b-4f53-bee6-c59c295bbaaa)

### Expected behaviour

System run off APU power

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

ground

### Agreement

- [X] Yes

**Comment by uwiuke** [comment]
switch it again to ON than OFF and ARM - than every lights are off.

**Comment by TheFightingRaven** [comment]
I think that this is operator error, don't arm emergency power until connecting a powersource (apu or gpu) once tripped into on, emer power doesn't disengage until put physically into the off position. Please refile it that does not fix it
