### ISSUE TITLE
[BUG] - Enroute timer / Chrono does not swap to HH:mm after 60 minutes

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#302]
### Describe the bug

Enroute timer / Chrono does not swap to HH:mm after 60 minutes

### Steps to reproduce

Turn on the timer and leave it running for about 60-100 minutes

### Expected behaviour

after 60 minutes the timer should switch to HH:mm (I think)

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/50d0ecc0-3d9b-43e7-b7d9-315a9a6cb3d2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved in 0.14+
