### ISSUE TITLE
[BUG] - Minimums reset does not function

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#303]
### Describe the bug

Minimums do not disappear from PFD after minimums knob is pushed to reset nor do the minimums actually reset

### Steps to reproduce

Push the minimums knob

### Expected behaviour

minimums should not be visible on the pfd until the knob is rotated again and they should also be reset to a value of 200

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/86cbcb6f-6403-4f32-9968-dc61dc6f2ca4)
result after spamming the push reset about 20 times

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The minimums always display, but you are correct that the reset doesn't work. It will be fixed in 0.13+
