### ISSUE TITLE
[BUG] - Line on ND

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#304]
### Describe the bug

A line on the right side of ND

### Steps to reproduce

No need.

### Expected behaviour

The line should not appear.

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 09 - 17 30 05 00](https://github.com/invernyx/md11-bugs/assets/143886762/2746d4d4-50b7-419b-bdcf-ef931aa8735b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
already filed some time ago
