### ISSUE TITLE
[BUG] - Analog Standby ALT display ALT and QNH not correct

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#305]
### Describe the bug

Analog Standby ALT displays -10000 and it shows 20.00 when 1013hpa

### Steps to reproduce

No need

### Expected behaviour

Normal behaviour.

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 09 - 17 31 40 25](https://github.com/invernyx/md11-bugs/assets/143886762/31531656-a6ad-4d5e-bd5b-401766d2236c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by ProfessorMadman** [comment]
+1.  Used "b" key to set local baro on the ground in AMS if that helps but then attempting to set QNH to std 1013 results in a 20.01 InHG.  I did not check InHG reading prior so could've been bugged on the ground as well.

![Screenshot 2023-11-09 140318](https://github.com/invernyx/md11-bugs/assets/79177080/5477f795-5cb5-4dfc-96aa-f15ef51a1e24)

**Comment by TheFightingRaven** [comment]
I've observed this myself, it's not turning over to the next number correctly, animation needs review

**Comment by sersanchez** [comment]
I can confirm I see the same on the Standby Altimeter

**Comment by turbofandude** [comment]
This should be mostly resolved
