### ISSUE TITLE
[BUG] - no steering keyboard inputs accepted

### ISSUE THREAD

**Issue by JulianTD** [invernyx/md11-bugs#306]
### Describe the bug

No Keyboard Inputs are accepted to steer the plane

### Steps to reproduce

Use a keyboard and try to steer the rudder to the left - or use num 456 etc trying to use the yoke

### Expected behaviour

Correct steering with keyboard should be possible

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
