### ISSUE TITLE
[BUG] - Autopilot points directly toward localizer when in range after pressing APPR/LAND

### ISSUE THREAD

**Issue by PointBlank66** [invernyx/md11-bugs#307]
### Describe the bug

After doing a short flight toward the destination airport it seems that the autopilot is pointing directly towards the runway long before I turn base to final after I populated the ILS/CRS on the NAV/RAD page in the FMS and pressed the APPR/LAND button.

### Steps to reproduce

For reproducing this issue I take the airport OERK and ILS 15L as an example marked between brackets ()
Location: Any airport with an ILS or LOC approach (OERK)
Runway: Any runway with an ILS or LOC approach (ILS 15L with RESUB transition (show as a 20.0 DME ark)
Populate the ILS/CRS on the NAV/RAD page in the FMS (109.5/147°)
Fly approach procedure and arm APPR/LAND at the transition from the end of the STAR to the Approach flightpath.

This should be enough to reproduce the bug.

### Expected behaviour

Normal behavior, as with any plane, should be that the plane flies its flightpath towards the ILS/LOC and should only capture the ILS/LOC when it is close to crossing/intercepting the ILS/LOC course that has been put into the FMS.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

OERK

### Arrival

OERK

### Cruise level

280

### ZFW

227700

### CG

29.4

### Fuel

63792 lb

### Cost index

0

### Route

OERK/15R RESA1H RESAL DCT MUNTO MUNT1A OERK/15L

### Location

idk what to put here. The airport where I first encountered the bug is in the desert, in the middle of Saudi Arabia

### Agreement

- [X] Yes

**Comment by henkhugo** [comment]
Same issue this side. Does not follow the LOC correctly.

**Comment by PointBlank66** [comment]
well it does follow the loc correctly, it just doesn't align correctly on the right course. But I do get what you mean

**Comment by PointBlank66** [comment]
Also an additional note.
This issue is a bit different compared to Issue 245 (https://github.com/invernyx/md11-bugs/issues/245) where in my case it took a little time to capture the loc before I got within it's range. (I guess msfs does simulate localizer transmission range in a way)

**Comment by TheFightingRaven** [comment]
has been filed multiple times will be fixed
