### ISSUE TITLE
[BUG] -PROG missing info

### ISSUE THREAD

**Issue by henkhugo** [invernyx/md11-bugs#310]
### Describe the bug

PROG showing 0 for ETE, DTG, EFOB

### Steps to reproduce

enter a flight plan 

### Expected behaviour

show correct data

### Evidence

![20231109131315_1](https://github.com/invernyx/md11-bugs/assets/150338137/7a657a57-6038-41db-aada-e6c4d0ba20c6)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

FALe

### Arrival

FACT

### Cruise level

FL340

### ZFW

n/a

### CG

n/a

### Fuel

n/a

### Cost index

n/a

### Route

n/a

### Location

n/a

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
+1 
![image](https://github.com/invernyx/md11-bugs/assets/150094502/9e45e93e-aa2e-49f7-a11e-c734ad813d19)

**Comment by ProfessorMadman** [comment]
+1.

Simbrief route: 

ROUTE ID: DEFRTE
EHAM/24 VALKO3S IDRID L980 LAM L179 ICTAM M197 ENHAQ DCT GAJIT DCT
GAPLI DCT OMOKO DCT 48N015W 48N020W 47N030W 43N040W 39N045W 34N050W
28N055W 22N060W DCT OBIKE M576 MNOLO ULUBA1 TNCM/10

Loaded 84.5 tons of fuel.

![Screenshot 2023-11-09 143136](https://github.com/invernyx/md11-bugs/assets/79177080/76568001-3fae-4144-b611-776717f4db56)
![Screenshot 2023-11-09 140318](https://github.com/invernyx/md11-bugs/assets/79177080/c4ca80e1-b826-48de-a12f-cffa846e106d)

**Comment by dr71205** [comment]
Also also, seems the ETA for waypoints does work fine on F-PLN page, even being affected by the wind. Not sure why it doesn't work on PROG page then, that's for Collin to find out i suppose :D

**Comment by turbofandude** [comment]
Fixed in 0.16+
