### ISSUE TITLE
[BUG] - ND Magenta Line shows loop around waypoint while plane goes straight like usual

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#311]
### Describe the bug

ND Magenta Line shows loop around waypoint while plane goes straight like usual

### Steps to reproduce

Make a route - in my case one via 6620N

### Expected behaviour

The magenta line to not make a loop and to actually show what the plane is going to do

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/2b1fdd9a-bbfd-4b5f-8855-e04925a598ba)
photo for illustration, not the same waypoint
it also only happens for certain waypoints, not sure what's special about them

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
can you list some waypoint this happens on so we can troubleshoot?

**Comment by dr71205** [comment]
EHAM/24 BERG2S BERGI DCT ROKAN DCT NAVEL DCT DENOG DCT KESEG DCT 6210N DCT 6620N DCT 68N027W DCT 7040N DCT 7160N DCT NADMA DCT 71N070W DCT 7078N DCT 68N090W 66N098W 64N104W DCT YSM J528 YQU DCT BOOTH COLMB2 CYVR/08R was the full routing, had it happen around AFAIR 6620N, 6698N and either YSM or YQU vor

**Comment by ProfessorMadman** [comment]
> can you list some waypoint this happens on so we can troubleshoot?

Same on routing TNCM - TNCB as KL763

TNCM RWY10 MULLET2 SID DANDE transition M576  MILOK DCT ACORA 

Had a loop drawn on the ND at DANDE but the aircraft continued the route straight on as expected.

https://cdn.discordapp.com/attachments/869142214406725692/1172498651436826684/Microsoft_Flight_Simulator_-_1.35.14.0_10_11_2023_11_22_35.png?ex=65608976&is=654e1476&hm=d200d9a4b0396485c099e2d9fe22e06ce516671b43a44e4c08e660824c33636f&
