### ISSUE TITLE
[BUG] - Pressing the FCP knob does not work. Need to click continuously to press it successfully.

### ISSUE THREAD

**Issue by ericjeppesen** [invernyx/md11-bugs#312]
### Describe the bug

Pressing the FCP SPD / HDG / ALT knob once with the left mouse button does not work. You need to click the left mouse button several times in succession before the game can recognize it as a successful press.

### Steps to reproduce

1. Use A/P to maintain a certain stable speed and heading.
2. Select a new target speed or heading on the FCP.
3. In order for the A/P to maintain the new speed or heading, you need to press the knob with the left mouse button.
**BUT Clicking once does not implement a press action in the MSFS - _the aircraft will still maintain its original speed or heading, and the FMA will NOT change._**
4. After continuously clicking the knob with the left mouse button, the aircraft correctly recognized the pressing operation.  **The number of consecutive mouse clicks is NOT a certain number.**

### Expected behaviour

The FCP knob can respond immediately after pressing it once with the left mouse button.

### Evidence

P.S. At the bottom of the table, it asks "Phase of flight" - This problem can be reproduced at any stage after leaving the ground.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

Any

### Bank

Any

### Heading

Any

### Altitude

Any

### Departure

Any

### Arrival

Any

### Cruise level

Any

### ZFW

Any

### CG

Any

### Fuel

Any

### Cost index

Any

### Route

Any Route.

### Location

Any location.

### Agreement

- [X] Yes

**Comment by ericjeppesen** [comment]
When using the mouse to click the FCP knob several times, the icon of the cursor has changed, and the cursor pattern has shown the change of pressing. But the press operation was not recognized by the aircraft.

**Comment by TheFightingRaven** [comment]
You need to click and drag, this is the way the interaction currently works and therefor not a bug

**Comment by ericjeppesen** [comment]
Got it! Thanks for your reply!

**Comment by ericjeppesen** [comment]
> You need to click and drag, this is the way the interaction currently works and therefor not a bug

Got it, thanks for your reply!
