### ISSUE TITLE
[BUG] - Aileron + Spoiler mismatch

### ISSUE THREAD

**Issue by cptnuss-ops** [invernyx/md11-bugs#313]
### Describe the bug

In the external view, the aileron and spoilers are inverse with full left or right deflection. CONFIG-SD seems fine 

### Steps to reproduce

1.) Load plane & power up
2.) Give HYD pressure
3.) Do full left or right yoke input.
4.) Observe flight-controls from the outside and do sanity check
5.) Verify flight-control state from the CONFIG-SD in the Cockpit

### Expected behaviour

When commencing left turn, aileron should lift up on the left wing and spoilers should extend at full deflection.
Vice versa for a right turn.

### Evidence

All pics taken with full left deflection on yoke:
![grafik](https://github.com/invernyx/md11-bugs/assets/69425888/6b25e861-41de-4d8b-9e8e-6bf9c50b47f9)
Ailerons should be up, according to the spoilers:
![Screenshot 2023-11-09 135225](https://github.com/invernyx/md11-bugs/assets/69425888/283e1fd1-8335-4c97-9e3a-d03817958dfb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by cptnuss-ops** [comment]
EDIT: Flight controls can be moved without HYD-power so step 2.) can be skipped :)

**Comment by turbofandude** [comment]
Fixed in 0.16+
