### ISSUE TITLE
[BUG] - FLOOD light position doesn't match

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#315]
### Describe the bug

FLOOD OFF-the light goes to bright and goes off at BRT position

### Steps to reproduce

No need

### Expected behaviour

FLOOD OFF-the light goes to off and goes bright at BRT position

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 09 - 21 03 28 14](https://github.com/invernyx/md11-bugs/assets/143886762/71e82454-29d8-4e95-9fbb-21a047e122fb)
![Microsoft Flight Simulator Screenshot 2023 11 09 - 21 03 33 36](https://github.com/invernyx/md11-bugs/assets/143886762/e04639c2-528c-4b99-acb4-670ceb8cd55c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
To clarify this is the FLOOR light not FLOOD light.
