### ISSUE TITLE
[BUG] - Can't stop TIMER on ND

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#316]
### Describe the bug

The TIMER button and UP/DN switch doesn't work and the TIMER on ND start when the ACFT is loaded into MSFS

### Steps to reproduce

No need

### Expected behaviour

TIMER button and UP/DN switch works properly

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 09 - 21 08 30 58](https://github.com/invernyx/md11-bugs/assets/143886762/fb66276b-4330-467f-982b-0e7c128ddcd0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
filed multiple times, will be addressed
