### ISSUE TITLE
[BUG] - Digital standby instrument has no function 

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#318]
### Describe the bug

Can't change QNH or brightness or IN/HPA via buttons on them

### Steps to reproduce

No need

### Expected behaviour

The buttons on it can be assigned to the correct behaviour.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

every

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Need variables from Collin to tag these

**Comment by turbofandude** [comment]
Resolved in 0.54+
