### ISSUE TITLE
[BUG] - FCP displays offset

### ISSUE THREAD

**Issue by Riiiiin3180** [invernyx/md11-bugs#319]
### Describe the bug

The displays on FCP looks have some offset ( MACH TRK and ALT window)

### Steps to reproduce

No need

### Expected behaviour

Have a proper display.

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 09 - 21 29 30 10](https://github.com/invernyx/md11-bugs/assets/143886762/fc8f43f7-f224-4573-9ffa-4e51e1bc5606)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
filed multiple times, will be addressed
