### ISSUE TITLE
[BUG] - Yoke slightly offset at neutral

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#32]
### Describe the bug

When the physical controller is at it's neutral position, the yoke is still slightly rotated

### Steps to reproduce

1. Load aircraft
2. Move physical controller then move it back to neutral
3. Realize the yoke is slightly offset

### Expected behaviour

The yoke is supposed to be completely straight and level when the physical controller is at it's neutral position

The top photo is the MD-11, showing the offset yoke. The bottom is the default C208 with no offset yoke. The physical controller has not been touched at all in these two photos, and has remained at the same position.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48654776/9f733644-c8b7-4923-b807-89c7709d7440)
![image](https://github.com/invernyx/md11-bugs/assets/48654776/86036725-0cd2-47f6-948a-8af106f6d78c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
tested and is a deadzone issue, offset is rather quickly noticeable even with a very small input
