### ISSUE TITLE
[BUG] - Cruize level doesn't update

### ISSUE THREAD

**Issue by ElPadre85** [invernyx/md11-bugs#323]
### Describe the bug

After changing the CRZ level on F-Plan INIT page,the level doesn't change on F-plan page.It only changes when a new waypoint is added or a SID is selected.

### Steps to reproduce

-Enter crz level on F-PLAN INIT page
-check F-PLAN page
-enter different FL on F-PLAN INIT page
-Note on F-PLAN page that it still has the 1st FL in it
-enter SID and the FL changes

### Expected behaviour

Updated flightlevel

### Evidence

![FlightSimulator 2023-11-09 14-57-44](https://github.com/invernyx/md11-bugs/assets/150356530/c6d5d91b-61c5-487d-bd37-dfa703ba26cb)
![FlightSimulator 2023-11-09 14-57-49](https://github.com/invernyx/md11-bugs/assets/150356530/2f81d999-3580-4135-a083-60aeeac802a6)
![FlightSimulator 2023-11-09 15-01-13](https://github.com/invernyx/md11-bugs/assets/150356530/d1a9f560-3dad-44c0-a97b-1c9d9b10ed1a)
![FlightSimulator 2023-11-09 14-58-09](https://github.com/invernyx/md11-bugs/assets/150356530/9b84ad41-899c-4c13-8bf7-7210164ec931)
![FlightSimulator 2023-11-09 14-59-37](https://github.com/invernyx/md11-bugs/assets/150356530/ceaf6652-8455-4a8a-a71c-b3006770aa05)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

ground

### Departure

LOWW

### Arrival

EBBR

### Cruise level

Init FL400 then changed to FL360

### ZFW

139400kg

### CG

26.1

### Fuel

25000kg

### Cost index

80

### Route

LOWW/16 N0472F400 BUWU1B BUWUT DCT DITIS DCT OKG DCT KOMIB DCT ESAMA T880 BATTY BATY6A EBBR/19

### Location

LOWW ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should have long been resolved
