### ISSUE TITLE
[BUG] - No ARPT on ND+ no clickspot

### ISSUE THREAD

**Issue by ElPadre85** [invernyx/md11-bugs#324]
### Describe the bug

When selecting ARPT on the MCP,no indication on ND

### Steps to reproduce

-power up
-press ARPT on MCP
-Note no ARPT indicated on ND or in lower left box.
-Also no clickspot for ARPTS

### Expected behaviour

ARPTS shown on map and in lower left corner.

### Evidence

![FlightSimulator 2023-11-09 15-08-21](https://github.com/invernyx/md11-bugs/assets/150356530/43fab53a-684a-4af5-b924-a4183b8b5762)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
With the LVAR:CEVENT through spad.next, the ARPT works correctly, just missing the clickspot and the animation.

![image](https://github.com/invernyx/md11-bugs/assets/102414406/e4de5b08-184c-4460-a2fb-c1887d05d293)
