### ISSUE TITLE
[BUG] - Cannot Use EMR LT & Smoke/Belt Switches

### ISSUE THREAD

**Issue by TheAlphaFlyer** [invernyx/md11-bugs#325]
### Describe the bug

Cannot Use EMR LT & Smoke/Belt Switches

### Steps to reproduce

1. Load in Cold & Dark
2. Start-Up per the pre-flight checklist
3. Attempt to manipulate EMER LT position, NO SMOKE position, SEAT BELT position

### Expected behaviour

Switches function

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Scroll up to move them down

**Comment by TheFightingRaven** [comment]
try the above fix, refile if the problem persists
