### ISSUE TITLE
[BUG] - Dial a flap setting mismatch on PFD

### ISSUE THREAD

**Issue by ElPadre85** [invernyx/md11-bugs#326]
### Describe the bug

When selecting a dial a flap,the number mismatches on the PFD.

### Steps to reproduce

-select flaps 15 with dial a flap wheel
-see on PFD that is says flaps 14
-select flaps 17 on dial a flap
-see flaps 16 on PFD

### Expected behaviour

Correct flap setting on PFD

### Evidence

![FlightSimulator 2023-11-09 15-43-41](https://github.com/invernyx/md11-bugs/assets/150356530/ca155904-9721-4234-b28b-1b28ea5c7e2b)
![FlightSimulator 2023-11-09 15-43-52](https://github.com/invernyx/md11-bugs/assets/150356530/ad97f824-29af-42b9-98a6-0f3745c656bf)
![FlightSimulator 2023-11-09 15-44-19](https://github.com/invernyx/md11-bugs/assets/150356530/463ec53f-0cb0-4ce4-b0fc-784795ad286e)
![FlightSimulator 2023-11-09 15-44-25](https://github.com/invernyx/md11-bugs/assets/150356530/a45770ba-f725-4e11-983c-2a5a2c19a7a7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by mclovin90** [comment]
Same issue here.

**Comment by TheFightingRaven** [comment]
it is currently adhering to logic use flaps x when >=x instead of rounding, will be fixed

**Comment by TheFightingRaven** [comment]
for now, set it to just beyond the line, should work then

**Comment by turbofandude** [comment]
Fixed in 0.13+
