### ISSUE TITLE
[BUG] - Manually entering waypoint into F-PLAN page resets page back to top

### ISSUE THREAD

**Issue by PointBlank66** [invernyx/md11-bugs#327]
### Describe the bug

After entering a waypoint into the NEXT WPT box on the LAT REV from [waypoint], the F-Plan page resets back to the top. Very annoying when you have to input a lot of waypoints by hand that don't follow an airway.

### Steps to reproduce

Set up FMS as normal, including departure and destination airport. Than add the first waypoint you go to after departing, or use a SID (faster imo to get to the bug)

Select the latest waypoint on the F-PLAN page to open LAT REV from [waypoint], Type in the waypoint that follows after and place that into the NEXT WPT box.
This add the inserted waypoint to the flightplan, brings you back to the F-PLAN page and scrolls you back to the top of the F-PLAN page

### Expected behaviour

The page shouldn't be reset back to the top I think. Instead the page should be show in a way where the last waypoint should be seen at the bottom, without having to scroll all the way down to the latest waypoint. (if that makes sense)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

EHAM

### Arrival

EHAM

### Cruise level

FL240

### ZFW

356993

### CG

28.9

### Fuel

76078

### Cost index

0

### Route

EHAM/24 BERG2S BERGI DCT GIKOV DCT PEROR DCT NEXAR DCT GIKOV DCT VALAM DCT VAPEX DCT GRONY DCT TOLKO DCT GETSI DCT GG740 DCT GG741 DCT GG742 DCT GG512 DCT LARBO DCT GRO DCT GG529 DCT GG533 DCT GG535 DCT EEL DCT FRO DCT PAM DCT SPY DCT HDR DCT PETCA DCT ALINA EHAM/18C

### Location

Loaded into the sim with the MD-11 PAX on stand E24 at EHAM

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This has been resolved in 0.12
