### ISSUE TITLE
[BUG] - Annun LT doesn't trigger OVERSPEED Alarm & AIR SYS TEST

### ISSUE THREAD

**Issue by ValkyPouet** [invernyx/md11-bugs#328]
### Describe the bug

Click and maintain the Annun LT button on the overhead panel doesn't trigger the overspeed alarm and the air system test.

### Steps to reproduce

Start the aircraft with battery ON and ground power or APU to provide electricity.
Click on the Annun LT button on the bottom right part of the overhead panel to verify if all the lights on the panels are working.
The lights are ON, but that's all.

### Expected behaviour

By clicking the Annun LT button you should trigger the overspeed test too by hearing something like "tiktiktiktiktiktiktiktik...overspeed......tiktiktiktiktiktik....overspeed"
Then if you maintain the button long enough to hear the overspeed test 5 times, it should trigger the AIR SYS TEST (display in blue on the ECAM, like other tests for example hydraulics).

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
filed multiple times, will be addressed
