### ISSUE TITLE
[BUG] - manually inserting the same waypoint more than once removes the previous instance of said waypoint

### ISSUE THREAD

**Issue by PointBlank66** [invernyx/md11-bugs#329]
### Describe the bug

Adding the same way point more than once into the flightplan manually remove the previous instance of said waypoint. This could be a very frustrating bug for flightplans that contain two of the same waypoint names if following a custom route

### Steps to reproduce

Set up FMS as normal, including departure and destination airport. Than add the first waypoint you go to after departing, or use a SID (faster imo to get to the bug).

Insert a row of waypoints manually via LAT REV from [waypoint]. There after add one of the waypoint from said row again via LAT REV from [waypoint].

In my case the row of waypoints are GIKOV DCT PEROR DCT NEXAR DCT GIKOV. Waypoint GIKOV at the start of the row gets removed and replaced with the waypoint GIKOV at the end of the row. All waypoints in between get removed as well.

### Expected behaviour

Being able to have multiple instances of the same waypoint to create a custom holding pattern for example

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

EHAM

### Arrival

EHAM

### Cruise level

FL280

### ZFW

356993

### CG

28.9

### Fuel

76078

### Cost index

0

### Route

EHAM/24 BERG2S BERGI DCT GIKOV DCT PEROR DCT NEXAR DCT GIKOV DCT VALAM DCT VAPEX DCT GRONY DCT TOLKO DCT GETSI DCT GG740 DCT GG741 DCT GG742 DCT GG512 DCT LARBO DCT GRO DCT GG529 DCT GG533 DCT GG535 DCT EEL DCT FRO DCT PAM DCT SPY DCT HDR DCT PETCA DCT ALINA EHAM/18C

### Location

Loaded into the sim with the MD-11 PAX on stand E24 at EHAM

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I believe this has been fixed already
