### ISSUE TITLE
[BUG] - EFB not releasing mouse/keyboard control after using text box

### ISSUE THREAD

**Issue by cvanallen99** [invernyx/md11-bugs#330]
### Describe the bug

After entering a simbrief username on the options page of the EFB, the EFB does not return keyboard and mouse control/focus to the user.  Cant change camera views with keyboard or mouse commands

### Steps to reproduce

1) Set one or more custom camera views
2) on the options tab of the EFB, click in the Simbrief username box and enter a username.  Save changes.
3) attempt to change camera view either with mouse drag, hotkey or even the default "F" to return to the home position.  None will work.  

### Expected behaviour

After saving the username entry, Mouse and keyboard focus should be returned to the user and not remain within the EFB. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
+1

**Comment by JSpectre15Q** [comment]
+1

**Comment by uwiuke** [comment]
+1

**Comment by TheFightingRaven** [comment]
@GenericNerd can we lock the keyboard using when using the efb?

**Comment by shipbiulder101** [comment]
I don't know if this is intended behaivour or related to the bug but going back to the options tab after changing clears the username. Also the keyboard is partially released as you can still use ESC to get to the menu but this could also be MSFS not letting any addon use the ESC key.

**Comment by alxcpt** [comment]
Happen in Navigraph as well, type icao code hit search. Panning with standard cockpit camera not possible. When selecting any chart it works randomly

**Comment by GenericNerd** [comment]
This is deeper than just the simBrief username. This is with any text box. I'll try my best to look into this for the next update as soon as I can.

**Comment by GenericNerd** [comment]
This has been fixed in the next version
