### ISSUE TITLE
[BUG] - Wingview cabin

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#331]
### Describe the bug

Cabin floor bugging/no wingviews in cabin

### Steps to reproduce

When going inside the cabin to try to make some wingviews there is no wing moddeld in the cabin model. Is this coming?

Also the floor in the cabin is buggy as f

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by icecube919** [comment]
To complete this:
It seems like the whole exterior model is not showing from the internal view.

See the attached screenshot.

![Screenshot (321)](https://github.com/invernyx/md11-bugs/assets/115575827/2fab7265-ec03-4eb5-9159-a7c73542f640)

And that's why the wings are missing.

**Comment by TheFightingRaven** [comment]
this is a known issue and will be fixed

**Comment by jhattermann** [comment]
Wings added to interior models
