### ISSUE TITLE
[BUG] - Installer is blank and will not do anything

### ISSUE THREAD

**Issue by HalfBakedAvatar** [invernyx/md11-bugs#332]
### Describe the bug

Installer downloads fine, when opened, it is blank and will not load or continue from a blank state

### Steps to reproduce

Download and open installer

![image](https://github.com/invernyx/md11-bugs/assets/108910476/475c645e-ab21-4835-9f5f-b01c350b893b)

### Expected behaviour

Installer does nothing

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/108910476/78aeb611-dcda-4335-bb72-1694279ed92f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Can you try running the installer from the command line with these arguments? 

`"path/to/installer.exe" /L*V "md11install.log"` and send us the log file it creates?

**Comment by GenericNerd** [comment]
We will be using a new installer system rather soon, so no further action is needed on this issue for now.
