### ISSUE TITLE
[BUG] - Input Controls

### ISSUE THREAD

**Issue by JBPFlight** [invernyx/md11-bugs#333]
### Describe the bug

Only basic input controls working

### Steps to reproduce

My input controllers, such as throttles, yoke rudder and tiller are working, but the parking brake and autopilot rotaries of my bravo aren't causing change in the simulator and control the autopilot.

edit: Also affects lights switches such as landing, taxi, nav, beacon, Hi-Intensity (strobe)

### Expected behaviour

ability to change, IAS, heading, altitude and vertical speed autopilot inputs and set/realese parking brake

edit: switch lights on/off

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by ValkyPouet** [comment]
Same problem with the parking brake input

**Comment by TheFightingRaven** [comment]
these have not been mapped, they will be (however parking brake works for me)

**Comment by turbofandude** [comment]
Lights cannot work due to event flooding from the Honeycomb (we have to just ignore them or it'll TANK the performance). That said, we'll get the default AP events/variables in.

**Comment by GenericNerd** [comment]
This will be resolved in the next version (🎉)
