### ISSUE TITLE
[BUG] - Landing gear traps doesnt open

### ISSUE THREAD

**Issue by AlexDeSevran** [invernyx/md11-bugs#334]
### Describe the bug

When i select gear up or gear down, the gear traps does not open

### Steps to reproduce

Select gear up

### Expected behaviour

Gear open when we select gear up or down

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 09 - 16 22 58 98](https://github.com/invernyx/md11-bugs/assets/150366345/e62ce592-8995-48dc-abd6-d0d43f2eedd3)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by PatrickChai** [comment]
Same here but only on the freighter version.

**Comment by turbofandude** [comment]
Resolved in 0.21+
