### ISSUE TITLE
[BUG] - FMS vs Clock mismatch

### ISSUE THREAD

**Issue by henkhugo** [invernyx/md11-bugs#335]
### Describe the bug

FMS in Flightplan not keeping correct time

### Steps to reproduce

Waypoints in the FPLN has an ETO time which does not match with system and aircraft times. Note the system time vs the FMS ETO for RESNO on the attached screenshot. 

### Expected behaviour

Correct ETOs

### Evidence

![20231109173533_1](https://github.com/invernyx/md11-bugs/assets/150338137/4cfa4b7e-5986-4fde-abe2-4d8447084937)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL360

### Departure

EHAM

### Arrival

KBOS

### Cruise level

FL360

### ZFW

n/a

### CG

n/a

### Fuel

n/a

### Cost index

n/a

### Route

EHAM/24 N0480F360 BERG2S BERGI L602 SUPUR L60 PENIL M144 BAGSO DCT RESNO/M083F370 NATD ALLRY/N0475F380 N360A TOPPS DCT SEAER DCT AJJAY OOSHN5 KBOS/22L

### Location

RESNO

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This was before various ETE fixes
