### ISSUE TITLE
[BUG] - Spoiler Operation Endless Cycle Using Scroll Wheel, Up Scrolling Not Working

### ISSUE THREAD

**Issue by timv217** [invernyx/md11-bugs#336]
### Describe the bug

Spoiler Operation Endless Cycle Using Scroll Wheel, Up Scrolling Not Working MD11 & MD11F.

### Steps to reproduce

Using the scroll wheel, scrolling down on the spoiler lever

On the Ground - Stowed, Armed, Extended 1/3, Extended 2/3, Extended Full, Ground Spoiler, Stowed, Armed, Extended 1/3, Extended 2/3, Extended Full, Ground Spoiler etc...

In the Air - Stowed, , Extended 1/3, Extended 2/3, Extended Full, Stowed, , Extended 1/3, Extended 2/3, Extended Full etc...

Scrolling up using the mouse wheel on the Spoiler Lever does not work and the lever does not move

### Expected behaviour

Would expect scrolling down to stop at Maximum Spoiler Extension for phase of flight,

i.e. n the Ground at Ground Spoiler
In the Air at Full Extension.

Scrolling Up would expect lever to go back up the level it has come from, i.e. Full Extension, 2/3, 1/3, Stowed. 'Up'  Scroll only works from Ground Spoiler position back to stowed on MD11 pax. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
+1 Lever also "misses" the gate notches. Notch is aligned with the lever, not the lever catch

**Comment by cvanallen99** [comment]
If this issue is corrected it may invalidate/fix another potential issue of no click-spot to arm the spoilers. (IE instead of click, you mouse-cycle through the options.)

**Comment by slowreload** [comment]
Can also confirm

**Comment by turbofandude** [comment]
Resolved in 0.55+
