### ISSUE TITLE
VOR OSN is missing in fms/its not in the data base

### ISSUE THREAD

**Issue by LucaSklenar** [invernyx/md11-bugs#337]
### Describe the bug

Cant put VOR OSN into fms

### Steps to reproduce

Start a flight from EHAM arnem3s dep 24. Then try the following routing: L620 SUVOX Z718 OSN in the airways section. 
Edit:
It also does this with UPDAT and SAS when trying to connect to a route. Can put it in as a standalone.

### Expected behaviour

It should state that the VOR waypoint is not in the data base

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

-20

### Departure

eham

### Arrival

eddp

### Cruise level

fl330

### ZFW

cold and dark

### CG

cold and dark

### Fuel

cold and dark

### Cost index

cold and dark

### Route

EHAM/24 ARNEM3S ARNEM L620 SUVOX Z718 OSN L980 SAS Z88 UPDAT T236
ADMOS T959 KOJEC KOJEC1V EDDP/26R

### Location

EHAM Ground gate E17

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
part of a larger issue filed elsewhere, will be addressed
