### ISSUE TITLE
[BUG] - Fun with weights

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#338]
### Describe the bug

The MD-11 has a 103-ton empty weight, which is inaccurate

### Steps to reproduce

In the EFB, load the plane with 0 payload. ZFW should be the empty weight.
Alternatively in ZFW tab the plane defaults to min. ZFW (OEW)

### Expected behaviour

https://www.boeing.com/resources/boeingdotcom/company/about_bca/startup/pdf/historical/md11-passenger.pdf

The OEW for the passenger plane (GE Variant) should be ~129 T
The OEW for the freighter variant should be ~112 T
![image](https://github.com/invernyx/md11-bugs/assets/150094502/a38f0040-cbc2-4a7f-95d3-a6b92be205dd)
https://www.boeing.com/resources/boeingdotcom/commercial/airports/acaps/MD11.pdf

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/bd2d77fe-780e-4544-975b-9bec40d7b4d6)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
According to simvarwatcher (thanks joona_) the weights of the aircraft _are_ accurate, but not in the EFB nor FMS
![image](https://github.com/invernyx/md11-bugs/assets/150094502/9bb9cdef-3fec-48e1-9944-eaad7a20f725)
That checks out with my ZFW value changing over the flight

**Comment by mclovin90** [comment]
Same issue as seen above, Also the MZFW in the EFB is much lower than listed above and the FMC warnings
![FlightSimulator_PUejNqnrOb](https://github.com/invernyx/md11-bugs/assets/97921311/2fb67587-cbd3-4038-aa70-e7a8bf817e16)

**Comment by joon44** [comment]
Also fuel seems to be set correctly (at least when KG in use) on both pax & cargo and zfw pages.

**Comment by dr71205** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/150094502/5413de24-3dbe-4339-93bb-e3a731a58cf0)
weights are still wrong in 12.0

**Comment by dr71205** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/150094502/c875c0cb-ed7d-4e82-a452-cf672537de5f)
also, the plane is completely empty and still the WBS reads 155.9 ???  (Pax variant)

**Comment by dr71205** [comment]
Okay, when ZFW is set to minimum in the EFB, it does work, but when you set payload by pax and cargo all zeroes it doesn't

**Comment by dr71205** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/150094502/7964c7e4-da2a-498c-a652-4dbc97e2a768)
it does also not stop you from loading the aircraft with a load >100%
which leads to funny moments

**Comment by dr71205** [comment]
There's no limit to pax weight lol you can load 410 people each weighing 999 kilograms and then another 91 tons of cargo as well

**Comment by dr71205** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/150094502/585010a3-6c3d-4d41-9b9d-d29b8aafa23c)
it's given up now that i've also maxed the fuel

**Comment by GenericNerd** [comment]
This should be fixed as of the last EFB update. The weights are not yet perfectly accurate, but this will be fixed in the next EFB update
