### ISSUE TITLE
[BUG] - EFB - Tabs to change during cruise

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#339]
### Describe the bug

Tabs to modificate during cruise

### Steps to reproduce

You can change the Weight and Balance during flight. 

### Expected behaviour

The Tab Payload should be disabled during flight like the Tab Services.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
Thiên can you please block inputs on the payload page in flight, like the ground equipment page is?

**Comment by Dennis380** [comment]
> Thiên can you please block inputs on the payload page in flight, like the ground equipment page is?

I dont know, what you mean with with Thiên. And how can I block Inputs on an EFB?

**Comment by Thien42** [comment]
Will be fixed in the next update
