### ISSUE TITLE
[BUG] - Waypoints in STARs not displayed

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#340]
### Describe the bug

Waypoints in STARs not displayed

### Steps to reproduce

Missing Transitions and correct Waypoints for STAR
Exp: EDDF RWY25L
ROLIS 2D - You can choose MTR as Transition but after ROLIS there is directly MTR without all the DFxxx Points in between.

This is just an example. I witnessed this also during my Approah Briefing for EDDL.
![FMS_MissingPointsinSTAR](https://github.com/invernyx/md11-bugs/assets/150371828/479b6980-7bcf-4765-b72f-9c81e404a1b4)

### Expected behaviour

You should have all the DFxxx Points between ROLIS and MTR. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

17000

### Departure

EDDL

### Arrival

EDDF

### Cruise level

17000

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

COL5T T911 ROLIS

### Location

Already starting at DUS or during flight. No location needed. The Aircraft doesnt load any STAR

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This is because of a mismatch in your navigation data and the chart you're looking at. I just verified against cycle 2311 and our approach matched the chart perfectly.
