### ISSUE TITLE
[BUG] - {{LNAV skipping a waypoint}}

### ISSUE THREAD

**Issue by Jannik1211** [invernyx/md11-bugs#341]
### Describe the bug

While flying on a SID the LNAV system skipped a waypoint and flew to one one after that.

### Steps to reproduce

Depart EVRA out of runway 18 on the VALED2F departure and follow the LNAV with autoflight activated.

### Expected behaviour

It would not skip the waypoint RA432.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150371257/512b9520-c245-4654-90d6-dd4f133cb077)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

6000ft / FL60

### Departure

EVRA

### Arrival

EDDH

### Cruise level

FL400

### ZFW

152T

### CG

24.8

### Fuel

20000KGS

### Cost index

20

### Route

VALED2F/18 VALED DCT ADAXA DCT NINTA DCT MATEK DCT BAGOS N850 MICOS N850 BOGMU BOGMU2D/23

### Location

After RA431 it flew directly to RA434 instead of RA432.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is expected behaviour it projects not being able to make that waypoint and correctly skips it. 
The logic that determines if it can make turns should be tuned though

**Comment by Jannik1211** [comment]
> The logic that determines if it can make turns should be tuned though

That will likely fix it then. The aircraft should be able to make that waypoint from my judging of the handling due to the change of course from RA430-RA431 (216) to RA431-432 (220) being very minor.

If it doesn't get "fixed" thanks for clarifying. 

![image](https://github.com/invernyx/md11-bugs/assets/150371257/605f8647-ce24-4ad1-ab7c-6ef5071389bc)
