### ISSUE TITLE
[BUG] - Wrong ToD Calculation

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#342]
### Describe the bug

Wrong ToD Calculation

### Steps to reproduce

VNAV is receiving wrong information and putting the ToD way to late. In general, you will overshoot the LOC / the initial Fix for the final.

### Expected behaviour

A correct calculated VNAV which guides perfectly to the Approach. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Pitch

-

### Bank

-

### Heading

-

### Altitude

-

### Departure

EDDL

### Arrival

EDDF

### Cruise level

FL170

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

COL5T T911 ROLIS

### Location

No Location needed. VNAV is not calculating right.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the vnav still needs tuning as does the flight model, expect iterative progress

**Comment by turbofandude** [comment]
This should be improved in the coming builds and has likely been improved since this report.
