### ISSUE TITLE
[BUG] - waypoints from an airway are inserted behind destination airport instead of previously selected waypoint

### ISSUE THREAD

**Issue by kaiguner78** [invernyx/md11-bugs#343]
### Describe the bug

waypoints from an airway are inserted behind destination airport instead of previously selected waypoint

### Steps to reproduce

Started flight at LIPE
manually entering the flightplan

Up to waypoint ERNAS everything works.

LSK to open wyp ERNAS, select AIRWAYS, T161 on the left DEBHI on the rigth, then Insert, Result is picture 3 and 4

### Expected behaviour

Waypoints from airway insertet after ERNAS

### Evidence

AIRAC 2311

![001_VfNlfpCaSauBTHjpKqWx_g](https://github.com/invernyx/md11-bugs/assets/148564149/40454b8a-b175-42fb-bb8d-c94fa9c27144)
![002_h4SquD1PTHSw5Ory_BCaYQ](https://github.com/invernyx/md11-bugs/assets/148564149/edcf1051-f249-4ca4-abbb-4beec9943511)
![003_F7O2TjMcQY6nltqvBUp3Fw](https://github.com/invernyx/md11-bugs/assets/148564149/624a1c31-33db-4e9f-9006-fceae229daee)
![004_YNSYfxK4TNOFMvq8m8K-MA](https://github.com/invernyx/md11-bugs/assets/148564149/26b83ef2-db16-4007-b3d5-0bcc0db71f45)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

120 feet, Airport Elevation

### Departure

LIPE

### Arrival

EDDF

### Cruise level

FL300

### ZFW

415511 LBS

### CG

22

### Fuel

48000 LBS 

### Cost index

150

### Route

LIPE/12 LUMAV1K LUMAV L12 VIC DCT ROKIB DCT GIKEB DCT EKPEB DCT BRENO DCT KONIN DCT ERNAS T161 DEBHI DEBHI1A EDDF/25L

### Location

LIPE Stand 302  N4432.1E0116.9

### Agreement

- [X] Yes

**Comment by ElPadre85** [comment]
I have the same issue.Also once if this happens,the destination airport at the end dissappears.
If you delete the DES airport in the FP. it re-appears at the end.

**Comment by uwiuke** [comment]
... same issue here. Thank you for the possible workaround (ElPadre85) - i will test it.

**Comment by turbofandude** [comment]
Can confirm this was a bug. It will be fixed in 0.12.0+. Thank you!
