### ISSUE TITLE
[BUG] - The Minus in Vertical Speed isnt shown correctly

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#344]
### Describe the bug

The Minus in Vertical Speed isnt shown correctly

### Steps to reproduce

Just set a negative VS and you will see, that the Minus is at the Bottom of the Display
![Minusnotcorrectdisplayed](https://github.com/invernyx/md11-bugs/assets/150371828/e93e2639-c50f-4a8a-a270-b17aedb0acfb)

### Expected behaviour

Minus should be in the middle

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
