### ISSUE TITLE
[BUG] - FMS reads altitude contraints incorrectly

### ISSUE THREAD

**Issue by Jannik1211** [invernyx/md11-bugs#345]
### Describe the bug

The FMS reads the altitude contraint for the EDDH arrival as at or above FL110 and at or below 4000ft, when it should be at or above 4000ft and at or below FL110.

### Steps to reproduce

Fly into EDDH from the north east using the BOGMU2D arrival which leads to runway 23.

### Expected behaviour

FMS reads correct altitude contraint information, in this case at or below FL110 and at or above 4000ft as the charts suggest as well.

![image](https://github.com/invernyx/md11-bugs/assets/150371257/34a45065-c20f-482b-b59b-49e6e01c81a0)

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150371257/34d48852-13c0-4155-9346-e1a65c63f011)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

EVRA

### Arrival

EDDH

### Cruise level

FL400

### ZFW

152T

### CG

24.8

### Fuel

20000KGS

### Cost index

20

### Route

VALED2F/18 VALED DCT ADAXA DCT NINTA DCT MATEK DCT BAGOS N850 MICOS N850 BOGMU BOGMU2D/23

### Location

At the waypoint BOGMU this happened for me after inserting the STAR.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
known issue with the fms

**Comment by GenericNerd** [comment]
This should be fixed in the next update
