### ISSUE TITLE
[BUG] - Navigraph not staying linked through EFB

### ISSUE THREAD

**Issue by JSpectre15Q** [invernyx/md11-bugs#346]
### Describe the bug

Navigraph connection resetting every time you close and reopen sim

### Steps to reproduce

Launch MSFS, load into the MD-11, connect your navigraph account on the EFB, close the sim, reopen the sim, load into the MD-11, navigraph account is unlinked again and you have to relink it.

### Expected behaviour

Navigraph to stay logged in through the EFB

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by JSpectre15Q** [comment]
Since I am an idiot and can't figure out how to change my username, I am "Stringsly" in discord.

**Comment by uwiuke** [comment]
That's correct - same issue by me.

**Comment by TheFightingRaven** [comment]
Thien can you make the efb remember the navigraph login?

**Comment by JSpectre15Q** [comment]
Not 100% sure, but I think the entire EFB doesn't save any settings at all through flights. Or at least it did not for me. I keep having to redo simbrief username and the various settings. I have not seen that listed anywhere as WIP or bugged, but I noticed it earlier.

**Comment by GenericNerd** [comment]
> Not 100% sure, but I think the entire EFB doesn't save any settings at all through flights. Or at least it did not for me. I keep having to redo simbrief username and the various settings. I have not seen that listed anywhere as WIP or bugged, but I noticed it earlier.

This was a separate bug that should have been fixed.

**Comment by turbofandude** [comment]
This should already be resolved
