### ISSUE TITLE
[BUG] - Timer runnig after AC has been loaded

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#348]
### Describe the bug

Timer runnig after AC has been loaded

### Steps to reproduce

The Timer is already running after loading the AC into the Sim
![clock](https://github.com/invernyx/md11-bugs/assets/150371828/77ab4278-57eb-43e3-90fc-9880f74d56c7)

### Expected behaviour

Timer must be on 00:00 until you are pressing the button to start the Timer

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by mclovin90** [comment]
Same! Timer starts when AC loaded not on takeoff.

**Comment by TheFightingRaven** [comment]
automatic ET start misfiring at load instead of takeoff

**Comment by turbofandude** [comment]
Should be resolved in 0.14+
