### ISSUE TITLE
[BUG] Cabin Interior

### ISSUE THREAD

**Issue by captJojo11** [invernyx/md11-bugs#349]
### Describe the bug

Cabin Ground flickers

### Steps to reproduce

Just loaded into the Sim

### Expected behaviour

No flickering

### Evidence

![20231109180616_1](https://github.com/invernyx/md11-bugs/assets/150375285/09ea40d2-ce90-4466-9800-98c594f273c7)
![20231109180620_1](https://github.com/invernyx/md11-bugs/assets/150375285/cc912616-b352-45ea-b329-ac5068151f1c)
![20231109180625_1](https://github.com/invernyx/md11-bugs/assets/150375285/cf25b99e-4617-40b5-a5ff-12e3c30a6267)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
@jhattermann Can you confirm there aren't two copies of the floor model z-fighting?

**Comment by jhattermann** [comment]
> @jhattermann Can you confirm there aren't two copies of the floor model z-fighting?

The occluder material outside the cabin was double sided and doesn't need to be, so I switched it back to one sided

**Comment by alxcpt** [comment]
@jhattermann 
are those two cabins needed? I took a look inside the exterior and interior models both have polygons for interior (the exterior model a more basic one). Performance is great even with the high detail pax cabin. You could consider deleting the cabin from the exterior model completely and add LODs instead. Attached the model folder of PMDGs 737 (the cabin is inside PMDG_738NG3_BW_LOD0, the PMDG_737-800NG_VC is the cockpit only) and Fenix (cabin + VC is inside the fnx320_Interior, fnx320 is the exterior model only) to give you an idea, what I mean.
![image](https://github.com/invernyx/md11-bugs/assets/150608109/babb41f0-e9df-40dc-a025-882223cf4264)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/6696d16a-0479-4e60-ac7b-d7d37062b192)

**Comment by arwasairl** [comment]
@alxcpt Because the 3d cabin has blocked out windows, this will prevent the window alpha mask from working properly. The cabin model in the exterior is meant to have a configurable window mask for a livery maker to use, but if we use the high poly cabin, this will not work.

**Comment by alxcpt** [comment]
> @alxcpt Because the 3d cabin has blocked out windows, this will prevent the window alpha mask from working properly. The cabin model in the exterior is meant to have a configurable window mask for a livery maker to use, but if we use the high poly cabin, this will not work.

Understood, that's great news. I am not aware of any addon plane featuring configurable windows. Thanks for this. Keep up your great work!
