### ISSUE TITLE
[BUG] - NM Distances not shown or staying at 0.0

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#350]
### Describe the bug

NM Distances not shown or staying at 0.0

### Steps to reproduce

Sometimes Distances to the Waypoints are not shown. Or shown as 0.0

![Distances](https://github.com/invernyx/md11-bugs/assets/150371828/25b9d291-882d-4685-b4ac-58dce522f270)

### Expected behaviour

After passing Waypoint X the NM until the next Waypoint has to be displayed and not shown as 0.0

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by mclovin90** [comment]
Have this as well.

**Comment by TheFightingRaven** [comment]
nown issue, placeholder data
