### ISSUE TITLE
[BUG] - Reverser not shown

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#352]
### Describe the bug

Reverser not shown

### Steps to reproduce

When Reverser are deployed they are not shown in the Model

### Expected behaviour

Reverser should be seen when deplpyed

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
+1 for the Cargo model only it seems.

**Comment by TheFightingRaven** [comment]
> ### Describe the bug
> Reverser not shown
> 
> ### Steps to reproduce
> When Reverser are deployed they are not shown in the Model
> 
> ### Expected behaviour
> Reverser should be seen when deplpyed
> 
> ### Evidence
> 
> ### Simulator
> Microsoft Flight Simulator 2020 (MSFS)
> 
> ### Agreement
> * [x]  Yes

can you confirm this only happens in the freighter model?

**Comment by PatrickChai** [comment]
Same here.

**Comment by KJA1582** [comment]
![Screenshot (359)](https://github.com/invernyx/md11-bugs/assets/2170028/3e7c62a6-8559-49b6-88cf-a6d496b736a1)
![Screenshot (360)](https://github.com/invernyx/md11-bugs/assets/2170028/a7c595b5-72f8-445c-bc56-19f2d5b942bf)
![Screenshot (362)](https://github.com/invernyx/md11-bugs/assets/2170028/de9e8c60-67ab-4ea3-a152-14e5c83f5698)

**Comment by mclovin90** [comment]
Same, PAX is fine, Cargo no reverse outside.

**Comment by Dennis380** [comment]
> > ### Describe the bug
> > Reverser not shown
> > ### Steps to reproduce
> > When Reverser are deployed they are not shown in the Model
> > ### Expected behaviour
> > Reverser should be seen when deplpyed
> > ### Evidence
> > ### Simulator
> > Microsoft Flight Simulator 2020 (MSFS)
> > ### Agreement
> > 
> > * [x]   Yes
> 
> can you confirm this only happens in the freighter model?

Confirmed. Only happen to Cargo, Pax is fine

**Comment by PatrickChai** [comment]
Confirm this too. Pax ok, cargo not visible.

**Comment by turbofandude** [comment]
Resolved in 0.22+
