### ISSUE TITLE
[BUG] - {MD-11F Cannot set ZFW/Cargo in EFB}

### ISSUE THREAD

**Issue by mclovin90** [invernyx/md11-bugs#353]
### Describe the bug

Cannot set ZFW/Cargo via EFB in the MD-11F

### Steps to reproduce

Try and set the weight via EFB, It does not change in the MSFS menu or in the FMC etc even though it says changed.

Fuel is loaded correctly

You also cannot unload the aircraft by putting lower numbers in the EFB

Im on SU14, Fuel is loaded correctly via EFB and shows correct in MSFS menu, Payload does not, However if I change payload via MSFS menu it shows correct in FMC

### Expected behaviour

FMC/MSFS Menu should show updated values based on EFB Input

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [x] Yes

**Comment by cvanallen99** [comment]
I'm able to set cargo weight but the limits are wrong. Its capping at 91962# of cargo.  Whatever number used over that just stays 91962.  If I input values for cargo weight under that, I do see the GW and ZFW values adjust on the next page.

**Comment by mclovin90** [comment]
![281792642-a38f0040-cbc2-4a7f-95d3-a6b92be205dd](https://github.com/invernyx/md11-bugs/assets/97921311/b280be65-ffb5-46bd-968b-889b4bb20a19)
Also the MZFW in the EFB is much lower than listed above and the FMC warnings
Maxes out in the EFB at 343,500 LBS when it should be 451,300 LBS
Pax is the same way, EFB allows much less MZFW then what is listed in the chart above.
![FlightSimulator_PUejNqnrOb](https://github.com/invernyx/md11-bugs/assets/97921311/2fb67587-cbd3-4038-aa70-e7a8bf817e16)

**Comment by turbofandude** [comment]
Resolved in 0.12.

**Comment by mclovin90** [comment]
MZFW Numbers are now the Combi numbers and not the -F Numbers in the EFB... 

See chart above and set numbers to that please.
