### ISSUE TITLE
[BUG] - Clickspots

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#354]
### Describe the bug

Clickspots

### Steps to reproduce

Working with the Nousewheel to set lights , Speedbrake / Spoilers etc is annoying and unpractible. 

### Expected behaviour

Clickspots with Up and down Arrows etc would be more comfortable

### Evidence

Just have a look at PMDG or FBW.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
not a bug, currently working as intended, however improvements are wanted

**Comment by mclovin90** [comment]
Using the mousewheel is fine however a lot of the switches are opposite of the mouse wheel direction which seems super weird,
Landing lights should be mousewheel down to turn on and mousewheel up to turn off etc. Right now it seems lots of them are flipped so coming from any other payware dev it feels broken.

**Comment by Dennis380** [comment]
> Using the mousewheel is fine however a lot of the switches are opposite of the mouse wheel direction which seems super weird, Landing lights should be mousewheel down to turn on and mousewheel up to turn off etc. Right now it seems lots of them are flipped so coming from any other payware dev it feels broken.

thanks for the addition. Totally forgot about that!
