### ISSUE TITLE
[BUG] - Reflection in displays

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#356]
### Describe the bug

Reflection in displays

### Steps to reproduce

Having the reflection are nice, but kinda strange when you see Pilots using a Sidestick and you are flying an Aircraft with a Yoke! :D

### Expected behaviour

Delete the Relections or replace them with an Pilot using an MD 11 Yoke

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
MSFS issue, it's either this or no reflections at all

**Comment by TheFightingRaven** [comment]
art team is this something fixable?

**Comment by arwasairl** [comment]
This is not fixable. This is a limitation of MSFS as stated by the SDK's Glass Material specification. 

> _The environment bitmap used for reflections is not configurable and the value only has an influence on this default cockpit reflection..._
