### ISSUE TITLE
[BUG] - After annunciator light test numerous lights stay on

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#357]
### Describe the bug

After annunciator light test numerous lights stay on

### Steps to reproduce

Press the annunciator light button. after the test the dump light and MANIF light remain on as well as ALL of the selcal lights on the radio panels, galley buses, trim air, fuyel low etc.avionics fan, 

### Expected behaviour

After the annunciator test all lights should return to their pre-test condition

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/148719444/138c23ad-0c44-4d8e-9261-2eb57e15ecc9)
![image](https://github.com/invernyx/md11-bugs/assets/148719444/34c5bb66-188d-48cc-b5ef-7f42e7093e25)
![image](https://github.com/invernyx/md11-bugs/assets/148719444/52743111-76fb-4667-8e8e-f30b118b6ed9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.24+
