### ISSUE TITLE
[BUG] - F-PLN INIT says CRZ LEVELS -99/-99 etc.

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#358]
### Describe the bug

F-PLN INIT says CRZ LEVELS -99/-99 etc.

### Steps to reproduce

Honestly I have no idea what happened, I started my descent but I'm not sure that's related

### Expected behaviour

This does not happen

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/ad73712e-e5ee-418c-b57c-a0116cf2830b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

passing FL215

### Departure

EHAM

### Arrival

CYVR

### Cruise level

FL340

### ZFW

155 T (metric) however I did change midflight

### CG

25.6%

### Fuel

20 T

### Cost index

50

### Route

EHAM/24 N0480F320 BERG2S BERGI DCT ROKAN DCT NAVEL DCT DENOG DCT KESEG/M083F320 DCT 6210N DCT 6620N DCT 68N027W DCT 7040N/M083F340 DCT 7160N DCT NADMA/N0480F340 DCT 71N070W DCT 7078N DCT 68N090W 66N098W/N0473F360 64N104W DCT YSM J528 YQU DCT BOOTH COLMB2 CYVR/08R

### Location

just past YQU VOR

### Agreement

- [X] Yes

**Comment by KJA1582** [comment]
Simillar issue, but I had no FPLN loaded.
FMS believed me to be in DES mode after reaching FL310

**Comment by TheFightingRaven** [comment]
were you able to continue flying or did you lose all guidance?

**Comment by 017941** [comment]
I had the same issue: The cruise level went to -99 in all levels. I was able to re-enter the current level on the INIT page 1. It kept flying.

**Comment by KJA1582** [comment]
Guidance was still present for me.
Entered a FPLN, could then set a valid CRZ level.
Upon reaching the first STAR WPT, FMS switched to DES mode, -99 CRZ LVLs and had a major HIGH VERT DEV on the Indicator.
