### ISSUE TITLE
[BUG] - SE and GE speed shown in cruise at high speeds

### ISSUE THREAD

**Issue by cptnuss-ops** [invernyx/md11-bugs#360]
### Describe the bug

SE and GE label on PFD speed tape shown

### Steps to reproduce

1.) Prepare aircraft for flight with flight plan and perf setup
2.) Depart and climb
3.) Observe "GE" and "SE" markers shown on PDF speed tape even in higher mach speeds and flightlevels

### Expected behaviour

The markers should at least mark the right speeds, I've never seen them during cruise on the pfd (at least can't remember)

### Evidence

![grafik](https://github.com/invernyx/md11-bugs/assets/69425888/94fa5558-cb52-404b-a147-c312a3a6fc58)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
need to make sure the gear and flap speeds are shown in ias or mach whichever is lower

**Comment by turbofandude** [comment]
Resolved in 0.13+
