### ISSUE TITLE
[BUG] - ENG IGN "MANUAL" is displayed always

### ISSUE THREAD

**Issue by cptnuss-ops** [invernyx/md11-bugs#362]
### Describe the bug

When selecting IGN mode the blue "MANUAL" lights on the button

### Steps to reproduce

1.) Power up plane
2.) Select IGN channel A or B
3.) Observe blue "MANUAL" illuminating together with the respective channel on the push button

### Expected behaviour

As from a technical manual:

> MANUAL illuminates blue to indicate that power is being supplied continuously
>to the selected ignition. This occurs when the ignition has reverted to the
>manual mode (auto-ignition failure), ln this case the ignition system will remain
>powered until the pilot turns it off by pushing ENG lGN switch.

### Evidence

![grafik](https://github.com/invernyx/md11-bugs/assets/69425888/db84bb06-c340-4dfa-90b9-0d149e123fe0)
![grafik](https://github.com/invernyx/md11-bugs/assets/69425888/b50e6a73-f4cb-4673-8419-80aef003742e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Ozzy, this is my fault - I only gave you one tag for these lights. I just sent you a second set of tags on Teams for the MANUAL light (as the A/B and MANUAL lights are all separate)
