### ISSUE TITLE
[BUG] - The PROF Vertical Track Indicator (VTI) on the NAV Display does not work

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#363]
### Describe the bug

Vertical Track Indicator (VTI) on the NAV Display does not work

### Steps to reproduce

Fly a PROF Descent and the VTI does not indicate correctly. It flew a perfect arrival into KLAS on the STAR, but the VTI never worked.

### Expected behaviour

When you fly a PROF descent the VTI should correctly depict your current vertical track.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/148719444/c495cd47-8e2e-4840-b06e-7623fcbf308d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Approach

### Departure

klgb

### Arrival

klas

### Cruise level

fl340

### ZFW

360.0

### CG

25

### Fuel

43000

### Cost index

67

### Route

x

### Location

x

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
have had similar desyncs myself with restrictions in the flightplan

**Comment by dr71205** [comment]
Yep it's a bit odd, was continuously on 'slightly' too high even though i was like... 13000ft below profile at one point (operator error)

**Comment by turbofandude** [comment]
Long since resolved
