### ISSUE TITLE
[BUG] - T/D is displayed with distance and time to on the ND

### ISSUE THREAD

**Issue by cptnuss-ops** [invernyx/md11-bugs#364]
### Describe the bug

T/D is displayed as a waypoint on the ND in the upper right corner

### Steps to reproduce

1.) Prepare plane with flight plan and perf setup.
2.) Climb to T/C
3.) After T/C select a direct to to a waypoint that is after the T/D
4.) Observe T/D beeing "treated" as a waypoint as in attached screenshot

### Expected behaviour

Showing the waypoint the airplane is actually directing to.

### Evidence

![grafik](https://github.com/invernyx/md11-bugs/assets/69425888/80304697-8f29-4224-a829-1fb8041649a2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by cptnuss-ops** [comment]
Route in FMS:
EDDH BASUM OSN NVO LIMGO SUTAL POGOL GILIR GVA INCUS BALSI UN852 VERSO UL129 LUNIK LUNI2K LEPA
After GILIR direct to LUNIK with T/D before LUNIK

**Comment by cptnuss-ops** [comment]
EDIT: Only the T/D label is wrong. Distance and time seem to be linked to the correct waypoint 👍🏼 
![Screenshot 2023-11-09 201510](https://github.com/invernyx/md11-bugs/assets/69425888/0a4a8403-f14f-4072-957d-48e14abdaf37)

![Screenshot 2023-11-09 201525](https://github.com/invernyx/md11-bugs/assets/69425888/f8afd5eb-27bc-4489-9fad-df9dda950c7a)

**Comment by turbofandude** [comment]
Resolved
