### ISSUE TITLE
Autobrake not moving

### ISSUE THREAD

**Issue by PatrickChai** [invernyx/md11-bugs#365]
### Describe the bug

The autobrake knob is not moving in my case. I see the hand symbol when going to the autobrake but I can not rotate the knob. 

### Steps to reproduce

Tried with mouse wheel or mouse clicks. The Autobrake always remain in the same postion.
I also get a warning on the screen that autobrakes are not set.

### Expected behaviour

The knob should be moving around. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I've not had this problem myself, have you tried restarting the sim and or reinstalling?

**Comment by PatrickChai** [comment]
Restarting yes, uninstalling no. I will do it later today or in the next few days.

**Comment by PatrickChai** [comment]
Uninstalled and re-installed. The autobrake, in my case is not working or I'm doing it wrong.
How do you switch the knob?
I tried with both, left and right mouseclick and also turning the mousewhile while the handsymbol is over the autobrake knob.

**Comment by PatrickChai** [comment]
Ticket can be closed. Beside the Saitek throttles, I also use the thrustmaster A320 Trottles. There I had to set the AUTO BRK knob to disarm and then I was able to move the switch.
