### ISSUE TITLE
Pull or push HDG or ALT not working

### ISSUE THREAD

**Issue by PatrickChai** [invernyx/md11-bugs#367]
### Describe the bug

When changing the ALT, HDG or SPD, the plane will not follow the new entered datas. I have the hand symbol over the HDG, ALT or Spd selector but I can not push or pull it.

### Steps to reproduce

When changing the ALT, HDG or SPD, the plane will not follow the new entered datas. I have the hand symbol over the HDG, ALT or Spd selector but I can not push or pull it.

### Expected behaviour

I don't know how to set the AP correctly to fly the new entered HDG, ALT or SPD.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

.

### Arrival

.

### Cruise level

.

### ZFW

.

### CG

.

### Fuel

.

### Cost index

.

### Route

.

### Location

.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
click and drag the mouse, refile if that doesn't work please

**Comment by PatrickChai** [comment]
How? I pushed the right and the left mouse button.
