### ISSUE TITLE
[BUG] - Center Gear chocks

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#368]
### Describe the bug

Center Gear Chocked

### Steps to reproduce

Current version has chocks on Center Gear

### Expected behaviour

The MD11 should never have the center gear chocked as the shifting mechanism could damage the gear during loading/unloading.

### Evidence

During those operations we have to make sure that parking brake is released and that there are no chock on center gear. 
Part of safety inspection

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
there shouldn't be chocks on the center gear

**Comment by arwasairl** [comment]
@SimbiosiGT Delete chocks on the center gear. Leave the UVs and textures unchanged, as the chocks took relatively small amounts of space in the Tx and Ty direction.

**Comment by turbofandude** [comment]
Resolved in 0.21+

**Comment by arwasairl** [comment]
Reclosing
