### ISSUE TITLE
[BUG] - MCDU Final Time

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#370]
### Describe the bug

Cannot modify Final Time on INIT page 2

### Steps to reproduce

Modifying final time from /0030 to any other value is impossible

### Expected behaviour

You should be able to modify final time by inserting any value in minute like: 
/0045 or /45 (for 45min)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

KEDW

### Arrival

KLGB

### Cruise level

FL320

### ZFW

128.8t

### CG

25

### Fuel

20000Kg

### Cost index

80

### Route

DCT

### Location

Ground

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Entire INIT Page 2 fuel section besides block fuel is inop as is

**Comment by turbofandude** [comment]
Resolved in 0.56+
