### ISSUE TITLE
[BUG] - Weather Radar Annunciator Display

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#372]
### Describe the bug

Weather Radar Annunciator Display mssing

### Steps to reproduce

Nav display has the Weather Radar Annunciator Display missing

Weather Radar Annunciator Display:
Weather radar data consisting of range, tilt angle, and fault or warning 
messages are displayed in this area. Maximum range of weather radar display 
is 320 NM. Tilt angle is controlled from the weather radar control panel 
located on the pedestal. When weather radar display is disabled, WX OFF is 
displayed in this area.

### Expected behaviour

Weather Radar Annunciator Display is always displayed as shown below (number 8)

### Evidence

<img width="329" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/19e1ffa4-70eb-4390-8268-c57f354c1d4d">

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
The weather radar is not implemented or currently planned, this therefor is not a bug

**Comment by Willmus11** [comment]
even with WX radar not implemented, the bottom right box should display WX OFF if weather displayed or Terrain info if ND is in Terrain mode (I'll show you on the plane tomorrow)

**Comment by cnorm91** [comment]
Regardless, the box should still be there. Even the PMDG MD-11 had the box.

**Comment by Willmus11** [comment]
This topic shouldn't be closed, here are the two possible display from the lower right corner, regardless WX radar inop or not, this box cannot be removed
Here are reference I made today


<img width="431" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/2c835ac3-445f-4c5c-a191-6c978ba54c9f">
<img width="436" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/fb0da2b0-bebf-41d1-ad8a-7dc579b796c2">

**Comment by Willmus11** [comment]
Thanks for latest update, the box should still display WXR OFF or RNG xx / TERRAIN depending of the mode selected on the WX pushbutton located on ECP 
And there should be an exclusion to not see data from map (APT, VOR, WPT etc) within those 2 displays

<img width="562" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/1f9f0651-b2f5-4bef-889f-70079303799d">

**Comment by turbofandude** [comment]
The WXR/TERR buttons have been implemented, as have their modes. The WXR/TERR do not actually function, but the workflow can be simulated.

**Comment by Willmus11** [comment]
@turbofandude 
 latest build I see that the RNG shows 640, it actually only shows up to 320 even when arc is at 640, because that's the RNG of TERRAIN or WX 
Additionaly my references were from an outdated sim, on the real ones with the actual database the RNG is now also displaying when on WX
