### ISSUE TITLE
[BUG] - Auto Anti Ice Selection

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#373]
### Describe the bug

Auto Anti Ice triggers even though not selected in EFB

### Steps to reproduce

- Select Cargo variant
- Disable Auto Anti Ice
- Fly into icing and observe auto anti ice system toggling

### Expected behaviour

No Auto Anti Ice if disabled in EFB

### Evidence

![Screenshot (365)](https://github.com/invernyx/md11-bugs/assets/2170028/30a5eec2-e3ed-4323-8d9a-f3c7f473a783)
![Screenshot (366)](https://github.com/invernyx/md11-bugs/assets/2170028/d647c12f-98a5-4d1a-8fe3-d65e036e277b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

FL200

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Yep, had this happening to me too.

**Comment by 017941** [comment]
Same with me. Auto-anti ice disabled, but all eng, wing and tail ON at FL380. Unable to turn off. As an aside, I think, that when the ice is on, the N1 gauge should haave an eng ice annunciation, but I'll have to look that up
![Screenshot 2023-12-17 062847](https://github.com/invernyx/md11-bugs/assets/148719444/bb609c9c-0d27-4bb1-865f-ecaef16b7c73)
![Screenshot 2023-12-17 062809](https://github.com/invernyx/md11-bugs/assets/148719444/2bc7cdd7-0d4d-418c-a64d-692f95b13b47)
![Screenshot 2023-12-17 062737](https://github.com/invernyx/md11-bugs/assets/148719444/49b76931-0dc5-4cb5-aab5-afe10292348b)

**Comment by turbofandude** [comment]
Resolved in 0.28+
