### ISSUE TITLE
[BUG] - Setting 'Ready to Fly' in the EFB Panel state retains cautions

### ISSUE THREAD

**Issue by AJArkley** [invernyx/md11-bugs#374]
### Describe the bug

Selecting the 'Ready to Fly' panel state on the EFB does not allow the aircraft to be flown immediately - a series of cautions remain

### Steps to reproduce

* Install the aircraft from scratch
* Load into the aircraft
* Select 'Ready to Fly' from the EFB Panel States
* Cautions

### Expected behaviour

I expect that selecting 'Ready to Fly' would leave me in a position ready to advance the throttles and fly without further work on the systems.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/10499361/cc406b15-0b76-407c-a5f5-879f1087a340)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
