### ISSUE TITLE
[BUG] - Trim Air Not in correct position

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#376]
### Describe the bug

Trim air is off when Air in auto during startup

### Steps to reproduce

Trim air position is in OFF during cold and dark startup with Air panel in auto mode

### Expected behaviour

normal Trim air position should be ON in auto mode

### Evidence

TRIM AIR Switch - amber
The TRIM AIR switch is an alternate action switch that opens/closes the trim 
air pressure regulator valves when the system is in manual mode. When on, 
hot air tempers the air conditioning system cold air output. When off, hot air 
is prevented from entering the trim air manifold. The switch has no effect in 
auto mode.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Are you referring to the trim switch being depressed to the OFF position when starting cold/dark?

**Comment by Willmus11** [comment]
Affirm the trim should be on in normal operation

**Comment by turbofandude** [comment]
Resolved in 0.19+
