### ISSUE TITLE
[BUG] - Wind input goes in as speed/altitude restrictions

### ISSUE THREAD

**Issue by MagicEagles** [invernyx/md11-bugs#377]
### Describe the bug

When inputting wind in to F-PLN Page 2, information is entered as speed/altitude restrictions in F-PLN Page 1

### Steps to reproduce

During cruise, go to F-PLN Page 2
Attempt to enter wind data
Wind data remains as dashed lines
Go back to F-PLN Page 1
See wind has been entered as speed/altitude restriction

In this example I tried entering a wind of 273/38 on to waypoint BEALE, this was instead entered as a speed restriction of 273 knots, and altitude restriction of 3800ft

### Expected behaviour

Input should replace dashed lines on F-PLN Page 2.
If not yet implemented, should not appear on F-PLN Page 1 as speed/altitude restriction

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

41.000ft

### Departure

KONT

### Arrival

KDEN

### Cruise level

FL410

### ZFW

332.0LBS

### CG

40%

### Fuel

36.0LB

### Cost index

31

### Route

SNSHN5 LAS J146 DICEE DCT BUMMP SSKII3

### Location

Just before reaching LAS VOR

### Agreement

- [X] Yes

**Comment by mclovin90** [comment]
Can confirm this, Messed up my flight but I wanted to check!

**Comment by turbofandude** [comment]
Resolved (this is actually not an editable field, and is instead a function of the existing wind entries)
