### ISSUE TITLE
[BUG] - Flight Number Logic

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#378]
### Describe the bug

FLT NO should only support 7 digit entry

### Steps to reproduce

On Flight Plan INIT page one the FLT NO format accept anything from 1 to 7 digit flight number
the real one can only accept 7 digits

### Expected behaviour

eg: KLM671 or KL671 would result in FORMAT ERROR on the real MCDU, you need to type KLM0671 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

KEDW

### Arrival

KLGB

### Cruise level

FL320

### ZFW

128.8 KGS

### CG

25

### Fuel

20000Kg

### Cost index

80

### Route

DCT

### Location

preflight

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
do you have any reference for this?

**Comment by Willmus11** [comment]
I crosschecked and it seems that honeywell improved the MCDU since,
The  Operating program -913 has this limitation, but the latest MCDU updates (-923 or -924 or don't remeber) can finally allow different flight number lengh

**Comment by GenericNerd** [comment]
According to KLM FCOM 2B, page 51:
> "Flight number may be entered in the form of three alpha, four numeric and then an optional alpha character. A four-digit number without alpha characters may also be entered."

This means that the original report as given is incorrect. However, after some discussion within the team, we also do not feel like adding these restrictions would be doing overall good. While it would be more realistic, it may create more confusion (considering the current system already allows this behaviour) as well as potentially having compatibility issues with other software or servers down the line.

For these reasons, this issue has been given a `wontfix` label.
