### ISSUE TITLE
[BUG] - Spoiler cannot be armed with mouseclick

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#38]
### Describe the bug

When trying to arm the spoilers with a mouse click, it will not arm regardless of right or left click, position of camera, and position of mouse cursor.

### Steps to reproduce

1. Load aircraft
2. Attempt to arm spoiler with mouse click
3. Realize it doesn't do anything

### Expected behaviour

The spoiler is supposed to arm when clicked upon.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48654776/e8f172cc-95a7-424d-9274-9e8a7df2b242)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Fixed
