### ISSUE TITLE
[BUG] - Visual bug. Wing disappear (MD11)

### ISSUE THREAD

**Issue by Lion2604** [invernyx/md11-bugs#380]
### Describe the bug

3D Model/Wing disappear in showcase

### Steps to reproduce

Got to Camera -> Showcase -> Fixed Camera -> Switch to external 15-17.
If you switch from a external camera 1-14 to 15-17 you can see a blink of the wing and than the wings disappear.

### Expected behaviour

The 3D model should not disappear

### Evidence

https://github.com/invernyx/md11-bugs/assets/89660548/b2e04b24-7939-4d0b-9832-849898b1717d

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
filed multiple times, comes down to another issue, will be addressed soon
