### ISSUE TITLE
[BUG] - Cargo Fire test

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#381]
### Describe the bug

Cargo Fire should only auto test once 

### Steps to reproduce

Cycling IRU from OFF to ON will always start the auto test

### Expected behaviour

Only ONE auto test by switching IRU to NAV is performed by the aircraft when powered up
thus during transit if IRU are turned off and back to NAV without aircraft electrical shutdown the autotest won't run a second time

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by Willmus11** [comment]
correction, the condition tu run the cargo auto fire test during transit is if a cargo door is openned or closed (yet to be confirmed)

**Comment by AllanBurek** [comment]
For the -F, The cargo fire test is performed automatically when the first IRU is turned on after landing.  Cargo doors open  or closed do not force the MSC to reset the test logic.

**Comment by Willmus11** [comment]
My bad, it is indeed landing that trigger it, but only one auto test is performed for each landing (unless full reset of the plane)

**Comment by turbofandude** [comment]
Resolved as of 0.48+
