### ISSUE TITLE
[BUG] - FCP IAS windows during startup

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#382]
### Describe the bug

IAS windows displays 110

### Steps to reproduce

Cold and dark: FCP speed windows displays 110

### Expected behaviour

FCP normal readout during power up is: IAS 250, HDG 000, ALT 10000

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Pitch

0

### Bank

0

### Heading

006

### Altitude

0

### Departure

KEDW

### Arrival

KLGB

### Cruise level

FL320

### ZFW

128.8t

### CG

25

### Fuel

20000Kg

### Cost index

80

### Route

DCT

### Location

preflight

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
no longer true
