### ISSUE TITLE
[BUG] - Missing bulk door, ports, outflow valves etc

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#383]
### Describe the bug

right hand bulk door, outflow valve are missing and more

### Steps to reproduce

Important parts of the aircraft texturing are missing 

### Expected behaviour

Those are missing parts that are included in aircraft walkaround

Aft Bulk Cargo Door (left side next to aft pax door)
outflow valve on left side
pressure relief valves aft of fwd cargo door
adg door
air start connection (between Pack 1 and 2 doors)
TAT probes forward of Packs intakes
Air Conditioning Connections
Runway turnoff lights
Wings Lights
Access Panels on Engines
Cargo doors controls
Cargo Doors Lock Indicators
Elevator trim marks (3 degree on right side and 0 on left side)
beacon should be painted red
APU intake
APU and Engine 2 Access doors
APU exaust protection

### Evidence

can provide pictures for reference via private message if required

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by Willmus11** [comment]
I would also suggest to lower the bump map by somewhere around at least 50%, skin looks too wrinkled (I know it's a 30 years old bird but still I think it's too much)

And do the same for "wing reinforcement" which is way too thick 
pictures below:
<img width="908" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/248968de-5cb4-4833-b631-969e7044ed92">
<img width="935" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/dd6029bd-c2d1-42da-930e-5cebd273b196">


Plus would be nice to have also the single grey color wing version within the paintkit (if not yet inclueded)

<img width="693" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/9a5890a1-7a55-47b9-a594-24b0f410024f">

**Comment by arwasairl** [comment]
The items you have mentioned in the title have been fixed. Items within your report's description have also been implemented but some of them are just panel lines and are not openable.
