### ISSUE TITLE
[TODO] - Hardware switches do not do anything (LVARs, SimConnect/MSFS events)

### ISSUE THREAD

**Issue by InceptorOne** [invernyx/md11-bugs#384]
### Describe the bug

Using inputs from hardware, like stick, throttle, yoke, button box, etc... for basic checklist items don't do anything.

### Steps to reproduce

Use the aircraft with any basic MSFS/SimConnect binding (like BATTERY or TAXI/LANDING LT events for example) on your hardware (anything thats available under Control Options). Only basic control inputs like tiller, flaps, throttle, elevator, ailerons etc work.

AND/OR

If you use Spad or AAO: Try binding the LVAR's. The buttons will move but not do anything. There's also no xml available to view the behaviours and track down events while in Debug Mode.

### Expected behaviour

ALL basic switches noted in the checklists to work with hardware buttons using SimConnect events and/or LVAR's. It doesnt have to be 100% for both, but a mix of the two at the very least to be able to accomplish a whole flight via hardware controls. And please. no BVAR's.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by tebeso** [comment]
also it would be nice to have all the states (for example autopilot engaged/disengaged and so on)
