### ISSUE TITLE
[BUG] - rudder and flight controls with keyboard

### ISSUE THREAD

**Issue by StevenSilvaB767** [invernyx/md11-bugs#385]
### Describe the bug

keyboard controls have bugs or have issues. 1. In taxi mode or moving the plane on the ground, it turns only to one side by pressing the keys on the numeric keypad. 0 (zero) left, ENTER right, 5 to center. For example. When you press the "ENTER" key, the wheel rotates only clockwise in slow mode. When you press the 0 (ZERO) key, which is supposed to turn the wheel to the left, it does so to the right in fast mode. In the simulator everything is correct. The other controls work but at a slow pace. The reverses work with F2 but they are not animated yet. Below I will leave the main controls for ground flight control as MSFS sets them by default.

### Steps to reproduce

using only mouse and keyboard. whether the aircraft is active on the runway or with any EFB aircraft status. try to turn the plane with any key on the numeric keypad 0 (zero) left, 5 (five) center, ENTER right and the plane does not respond to this.

### Expected behaviour

issues

### Evidence

![Captura9](https://github.com/invernyx/md11-bugs/assets/132271106/fa20f6a9-32fd-49cf-81fe-ca122084e8a7)
![Captura10](https://github.com/invernyx/md11-bugs/assets/132271106/5d945be2-dd21-4d6d-967c-6aa47beb1ead)
![Captura11](https://github.com/invernyx/md11-bugs/assets/132271106/8cb69625-a903-4fd3-9408-0f008918228e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
We will most likely not be prioritizing fixing issues on keyboard controllers, as it is a very small portion of the userbase. @turbofandude can clarify further if needed.

**Comment by StevenSilvaB767** [comment]
For some reason the problem also occurs in virtual controls and USB controls

**Comment by StevenSilvaB767** [comment]
I know that the team is not interested in this for now, but... making one last attempt to make the MD-11 maneuverable on the ground, they found something very particular and I think that the error is not that difficult to calculate or redesign. As everyone knows, I am the typical simmer who uses the keyboard and mouse to fly for many reasons already mentioned here. as I mentioned at the beginning of this text. I turned on the simulator and selected MD11. I did some checks with the keyboard and the flight controls and some other things don't work. I turned on the VJOY, with the engines on I gave them a little power and the plane moved from left to right and vice versa. It worked but not very realistic, since the yoke moves to the sides (ailerons) and the nose wheel moved . but the Rudder (YAW) does not move on the ground, on takeoff, in flight and on approach. For now we will have to wait

**Comment by StevenSilvaB767** [comment]
I completed my first flight of 2 hours and 20 minutes. from YBAS to YSSY. a fantastic experience. In this error I saw something very strange. As mentioned in the previous message, the yaw rudder moves with the VJOY and selected in assistance option/ piloting, everything is easy. It is the only way that half solves the problem but it is not 100%.

**Comment by OD-Emperor** [comment]
I'm having this issue as well on MSFS. Think this should be higher up on the list because a lot of MS players still play with a controller and don't have a full peripheral setup or one that works entirely for them. I have a yoke and throttle quadrant, but that takes up a ton of space in a corner of my house which is pretty valuable space these days. Same with my X56, takes up a lot of desk space when I work from home and need to not have it in front of my face. On top of this, I don't have rudder pedals (waiting on Charlie) so the solutions for trying to use a rudder with a yoke or X56 still aren't great.

At the very least getting this fixed for using a controller would be welcome. A lot of customers use a controller and I like to a lot for casual flying anyways as I can quickly hop in, fly around or fly a route, and end it without a massive amount of cleanup or reorganizing of a corner of our house.

**Comment by StevenSilvaB767** [comment]
The bug continues in Version 0.41.0-alpha

**Comment by FarmerJon1066** [comment]
This bud is still present on a xbox controller, cant turn the rudder

**Comment by StevenSilvaB767** [comment]
The TFDI team is already aware of this error. The temporary solution is in the options section - assistance options - piloting is set to easy so that the aircraft systems work from 100 to 50... let's hope this is resolved after the launch to the general public

**Comment by StevenSilvaB767** [comment]
The bug continues in version 0.44.0-alpha.

**Comment by GenericNerd** [comment]
This will be fixed in the next version
