### ISSUE TITLE
[SUGGESTION] - EFB brightness option

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#386]
### Describe the bug

EFB Brightness Option would be sick to reduce the brightness during night flights

### Steps to reproduce

Would like to see this feauture in upcoming EFB updates!

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be added in the next version of the EFB
