### ISSUE TITLE
[BUG] - Landing Light Extension

### ISSUE THREAD

**Issue by JBPFlight** [invernyx/md11-bugs#387]
### Describe the bug

Landing Light not appearing to extend

### Steps to reproduce

when set to extended the landing lights on the forward fuselage side are not extended

### Expected behaviour

landing light units to stick out

### Evidence

![Screenshot 2023-11-09 222839](https://github.com/invernyx/md11-bugs/assets/150365728/fabc97e5-acd0-4c0c-b060-ee22364c2070)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Found and fixed in 0.13+

**Comment by turbofandude** [comment]
There was a code issue prior to version 0.13+ as well that has been resolved. @SimbiosiGT please check the animation itself in the model

**Comment by turbofandude** [comment]
Resolved in 0.21+
