### ISSUE TITLE
[BUG] - Left roll on TO

### ISSUE THREAD

**Issue by Herrick25** [invernyx/md11-bugs#388]
### Describe the bug

when i try to fly the md 11 it just turns to the left and rolls over

### Steps to reproduce

whenever i run a flight 

### Expected behaviour

the behavior i would expect is for it to fly on 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by flymypi** [comment]
Are you flying fast enough?

I just had my instruments and flaps freeze as described in #369 and when eyeballing it I got to low, stalling the left wing just like you describe.

**Comment by TheFightingRaven** [comment]
does this problem persist? I have not been able to recreate this

**Comment by alxcpt** [comment]
To help reproduce: Spawn midflight, aircraft banks to the left and goes down quickly. The only way I could get back to a proper flying condition is pause, toggle start state in efb, wait a few seconds, unpause. It takes some time until the engines come to life and flight controls are available

**Comment by tebeso** [comment]
I have the same issue

**Comment by tebeso** [comment]
I think this is fixed. No rolls for me anymore since last update
