### ISSUE TITLE
[BUG] - Some AIR panel emissives dont match albedo

### ISSUE THREAD

**Issue by flymypi** [invernyx/md11-bugs#390]
### Describe the bug

The emissive light textures for AFT CAB and ECON in the AIR panel are offset from their albedo counterparts

### Steps to reproduce

Power up plane and turn on overhead panel backlight

### Expected behaviour

Emissive should match normal textures

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/72461857/4975bf68-2a4c-40f1-910d-3d06968da547)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Fixed in last release
