### ISSUE TITLE
[BUG] - Initial INTCPT Point Drawn Several Hundred NM Away from SID

### ISSUE THREAD

**Issue by Wuyaxian1447** [invernyx/md11-bugs#391]
### Describe the bug

Planning Route from KMEM with the GOETZ7 dep DIYAB transition, the initial intercept point is drawn 854 NM from JAAXX on the 090 heading from KMEM. 

### Steps to reproduce

Set flight plan (ex. KMEM/KIAD). Inserted waypoints as follows: 

GOETZ7 DIYAB DCT HITMN Q34 NEALS DCT BKW GIBBZ4

But with direct entry (no airways used): DIYAB HITMN SWAPP GHATS FOUNT TONIO KONGO NEALS BKW. 

Used GOETZ7 departure (from either 36L, 36C, or 36R) but each different runway confers a slightly different distance - all several hundred miles to the east. 

### Expected behaviour

Prescribed climbout from 36L: climb on heading 360 to intercept course 035 to JAAXX, then on depicted route to GOETZ. 
Prescribed climbout from 36C/R: climb on heading 360 to intercept course 032 to JAAXX, then on depicted route to GOETZ. 

GOETZ7 is an RNAV departure with no vector component. 

### Evidence

![INTCPT from 36L](https://github.com/invernyx/md11-bugs/assets/150399506/170221b7-5a38-4dfa-bd63-d4a5b71ac34f)
![INTCPT from 36R](https://github.com/invernyx/md11-bugs/assets/150399506/d3e5f716-10f8-4c39-a03d-3ceee1067483)
![INTCPT from 36C](https://github.com/invernyx/md11-bugs/assets/150399506/d0940dae-3585-4b33-9c7e-e09fe28fa3a5)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

340 (airport elev)

### Departure

KMEM

### Arrival

KIAD

### Cruise level

350

### ZFW

321262 lbs

### CG

22.4 TOCG

### Fuel

55000 lbs

### Cost index

20

### Route

GOETZ7 DIYAB HITMN SWAPP GHATS FOUNT TONIO KONGO NEALS BKW GIBBZ4

### Location

KMEM. on airfield. Planned INTCPT persists after takeoff and until a DIR INTC to an RNAV waypoint is input. 

### Agreement

- [X] Yes

**Comment by FelixFeltersnatch** [comment]
Can confirm this bug also. STREP5 35L out of SDF.
![image](https://github.com/invernyx/md11-bugs/assets/50430284/c9a8e8ad-b4aa-41ad-9f90-b2995d4bd2c4)

**Comment by turbofandude** [comment]
This will be resolved as of 0.30+
