### ISSUE TITLE
[BUG] - {{Brief Description}}

### ISSUE THREAD

**Issue by aingramncl** [invernyx/md11-bugs#392]
### Describe the bug

Transponder numbers not selectable

### Steps to reproduce

the number one button on the transponder keypad is inop

### Expected behaviour

inop on number one button

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by flymypi** [comment]
can you rename the issue to include the problem in the title please?

**Comment by TheFightingRaven** [comment]
already filed
