### ISSUE TITLE
[BUG] - "Decrease Throttle" / "Decrease throttle {X}" has inconsistent / incorrect behavior

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#393]
### Describe the bug

The bind for "decrease throttle" produces inconsistent reverser behavior. Sometimes 1 and 3 deploy, then 2 fails to deploy, sometimes 2 deploys, then 1 and 3 later. Sometimes all 3 deploy. Additionally, binding "decrease throttle 1" "decrease Throttle 2" or "Decrease throttle 3" does not deploy the reverse for the respective engine, for 1 and 3 there is no obvious effect while for 2 it only unlocks the reverser.

### Steps to reproduce

1) Pressurize the hydraulics through aux pumps 1 and 2 and RMP's 2-3 and 1-3, which will pressurize all 3 hydraulic systems
2) Bind "Decrease Throttle" (default F2) and "Decrease Throttle {X}" (1-3 no default). I tested using F5 and binding them individually while testing
3) Decrease the throttle using "decrease throttle" Observe 1 and 3 deploy only, or some variation. Multiple attempts could produce multiple and consistent results
4) Repeat for 1-3 bindings

### Expected behaviour

When the decrease throttle is pressed, all three throttles should move back to reverse, eventually reaching 100% reverse. The same should be true for throttles 1-3, except it should only happen on the respective throttle. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The middle reverser actually doesn't unlock the same way, so it can seem a little weird. Do all three reversers work as expected if you give them time to deploy?

**Comment by Alex6511** [comment]
> The middle reverser actually doesn't unlock the same way, so it can seem a little weird. Do all three reversers work as expected if you give them time to deploy?

I just tested this and it's still happening in some capacity, though not in the same capacity. I'm looking exclusively at the levers in the cockpit, and I would say about 50% of the time the center lever goes up first before the wing reversers, while the other 50% of the time they all deploy together.

**Comment by dr71205** [comment]
Happened to me on 0.41

**Comment by Alex6511** [comment]
Video of the problem where I use decrease throttle {X}:
https://youtu.be/HDcHEqCGR8k

Video of the problem where I use the F2 key:
https://youtu.be/dTQIob_SvF4

**Comment by turbofandude** [comment]
Just reviewed these videos again. Video 1 shows reverser 2's handle working (as described) because it is not mechanically locked. Handle 1 and 3 are locked until the reversers are fully unlocked, which cannot happen with no electrical or hydraulic (or pneumatic, depending on engine) power.

Video 2 shows the center reverse handle opening sooner, again, as it doesn't require unlock. Handle 1 and 3 wait for the reversers to be unlocked, then deploy as commanded. This is not a bug.
