### ISSUE TITLE
[BUG] - Flap detent positions are not linear

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#394]
### Describe the bug

This may need to be an option/feature request. The flap positions are not linear, which means people using physical detents cannot enter them

### Steps to reproduce

Move the flap axis to 0/20/40/60/80/100 percent. This should be in the same order 50/35/28/Dial/0/UP. This will allow people with physical detents to bind them correctly without screwing with the axis.

### Expected behaviour

Either there should be an option or the flap axis should be linear to match other addons (PMDG, rotate, as well as other aircraft).

### Evidence

See L-Axis Z:
![image](https://github.com/invernyx/md11-bugs/assets/7919184/855c7af3-9723-4c8c-8515-63d6c3770619)
This position would be dial, as it's 60%
![image](https://github.com/invernyx/md11-bugs/assets/7919184/b0d3cd35-dd88-46a4-8f4a-3fe61a4795f3)
It's however 28 in the plane.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Alex6511** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/7919184/13bfcd89-8451-48ee-8d1b-f12b6837ac29)
In case anyone wants a workaround this appears to work

**Comment by TheFightingRaven** [comment]
this is intentional future features will allow calibration
