### ISSUE TITLE
[BUG] - VR Mouse cursor not aligned

### ISSUE THREAD

**Issue by nickjzx** [invernyx/md11-bugs#395]
### Describe the bug

VR mouse position misaligned, hard to use

### Steps to reproduce

When in VR and using the mouse to try to manipulate switches, or to use the keypad on the FMC, the right eye image mouse and the left eye image mouse seem to misalign. It's difficult to operate in VR as your eye struggles to figure out which one to use. The left eye image appears to be the correct placement, the right eye is typically quite a bit over. For example, in the image below I'm on the "F" key and if I press the LMB it will use the F key, but I also see the mouse over the G key but it's not pressing that.

### Expected behaviour

Mouse cursor position in VR should be the same

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/80855520/5fff3816-63fb-4b00-a6ee-17c83d2f9bcd)
This works correctly in several 3rd party planes and majority of the default aircraft as well.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by nickjzx** [comment]
I should also add, the issue does not occur on the EFB. The EFB the cursors are aligned perfectly

**Comment by TheFightingRaven** [comment]
this is out of our control
