### ISSUE TITLE
[BUG] - MCP panel flood light (MD-LIGHTS-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#396]
### Describe the bug

MCP flood light does not function unless the backlight is first turned on

### Steps to reproduce

Rotate backlight reostat to full
Rotate flood light reostat to full
Rotate backlight reostat to off
Flood light will extinguish
OR
Rotate flood light reostat to full, no flood light illuminates

### Expected behaviour

S/B flood light and backlight function independantly of eachother

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This has been resolved
