### ISSUE TITLE
[BUG] - Thunderstorm switch inop (MD-LIGHTS-3)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#397]
### Describe the bug

Thunderstorm light switch inop

### Steps to reproduce

Turn thunderstorm light switch to ON

### Expected behaviour

S/B dome light and all panel flood lights illuminate when thunderstorm switch in ON position

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by steve-jacko444** [comment]
SAME IN p3d v5     thunder storm light inop

**Comment by turbofandude** [comment]
Added as of 0.310+
