### ISSUE TITLE
[BUG] - Overhead flood light inop (MD-LIGHTS-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#398]
### Describe the bug

When rotating OVRHD FLOOD light reostat, no flood lights illuminate

### Steps to reproduce

Rotate OVRHD flood light reostat to full

### Expected behaviour

S/B flood lighting, eminating from OVHRD flood lights above and OTBD of the pilot seats, turn on and illuminate the OVRHD panel

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This is a duplicate, this has already been reported.
