### ISSUE TITLE
[BUG] - Pedastal flood light splash area (MD-LIGHTS-5)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#399]
### Describe the bug

Pedastal flood light illuminates radio stack only

### Steps to reproduce

Rotate PED flood light to full

### Expected behaviour

S/B PED flood light illuminates radio stack, throttle quadrant, CDU area and DU flood lighting

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Light has been illuminating the pedestal properly for as long as I can recall, so I am calling this fixed
