### ISSUE TITLE
[BUG] - Pedestal flood light and overhead flood light linkage (MD-LIGHTS-6)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#400]
### Describe the bug

With the pedastal flood light ON, the OVRHD flood light illuminates the DU flood light

### Steps to reproduce

see descrip

### Expected behaviour

S/B OVRHD flood light has no control over DU flood light.  DU flood lights are controlled with the pedastal flood lights only

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
The overhead flood lighting is not implemented yet, so please clarify as to what "S/B OVRHD flood lights" means.

**Comment by turbofandude** [comment]
Resolved as of 0.60+
