### ISSUE TITLE
[BUG] - Jetway connects at incorrect location

### ISSUE THREAD

**Issue by GmanPilot** [invernyx/md11-bugs#401]
### Describe the bug

Jetway does not connect to correct location on aircraft

### Steps to reproduce

1) Connect to ground services and request the jet way to be connected to the aircraft.
2) After jetway connection, walk into passenger cabin.
3) The jetway is connected in the rear of business class and the start of economy class. with it showing on the interior of the aircraft.
![JetwayConnection](https://github.com/invernyx/md11-bugs/assets/101133387/6c142087-5a40-435b-baa4-7e7cf35d97d4)

### Expected behaviour

The jetway should connect to the location where an entry door is located and should not be shown on the interior of the aircraft.

### Evidence

I have attached a screen shot of the jetway location within the interior of the aircraft.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by microlight2010** [comment]
Fixed.
