### ISSUE TITLE
[BUG] - Rudder/Tiller not bound on Xbox Controller

### ISSUE THREAD

**Issue by jason3580** [invernyx/md11-bugs#402]
### Describe the bug

Pressing LT and RT should turn the rudde/tiller but its not bound

### Steps to reproduce

The plane does not have rudder/tiller inputs when using Xbox Controller by default while the other controls seem to be mapped correctly.

### Expected behaviour

The default rudder/tiller inputs for all other planes in MSFS is LT/RT. The plane's rudder and tiller should be moving when using RT and LT on the Xbox Controller.

### Evidence

N/A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
inputs are not plane specific, what binding do you have for these buttons that should be affecting the rudder?

**Comment by jason3580** [comment]
> inputs are not plane specific, what binding do you have for these buttons that should be affecting the rudder?

The default bindings for rudder on Xbox controller which are LT (left trigger) and RT(right trigger). This binding works for all other planes out of the box but seems to be bugged on the MD-11. If I recall correctly, the plane does react to the buttons since the nose wheel animation has a bugged animation when LT and RT are pressed but this does not turn the plane.

**Comment by turbofandude** [comment]
Resolved as of 0.55+
