### ISSUE TITLE
[BUG] - Installation issue with long path

### ISSUE THREAD

**Issue by EngineIgnition** [invernyx/md11-bugs#403]
### Describe the bug

Installation fails when installing to the Community Folder

### Steps to reproduce

Execute Client Installer with MSFS Microsoft Store Edition installed
LongPath behaviour as instructed by Microsoft in the registry activated

### Expected behaviour

Install fails

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150428341/1ab47ca1-0f45-4f8a-b48e-fd42758003c5)

Installing the MD-11 to a custom, shorter directory works well, copying the folders manually to the Community folder then works flawlessly, even without shortening the paths

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should not be possible with our new installer
