### ISSUE TITLE
[IDEA] - External PAX model - Ability to plug individual cabin windows

### ISSUE THREAD

**Issue by ProfessorMadman** [invernyx/md11-bugs#404]
### Describe the bug

Add a method to control individual cabin window plugs to match IRL operator configurations

### Steps to reproduce

A new object with mesh over cabin windows can be added and controlled via alpha channel.  This will allow repainters to customise the external pax window configurations to match IRL operator configurations.  The current model does not allow this and cabin window configuration is baked into the model.

### Expected behaviour

A new DDS texture file is added to the external model for common window areas that can be customised with alpha channel and painted to plug out specific cabin windows on the external model.

### Evidence

Specific operators have custom cabin configurations where specific windows are plugged - see KLM as an example where the windows between L1 and L2 and R1 and R2 are plugged due to the presence of galley.

https://flickr.com/photos/ramonkok/30807944584/
https://flickr.com/photos/101074061@N04/15207516308/

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This is already possible in the 3D model, however, because we don't have a paintkit, new liveries "technically" don't have the ability to do this. However, the 3D model and current liveries already use this technique.
