### ISSUE TITLE
[BUG] - External model - Cabin windows lack metallic frames

### ISSUE THREAD

**Issue by ProfessorMadman** [invernyx/md11-bugs#405]
### Describe the bug

External model lacks metallic window frames around pax windows

### Steps to reproduce

N/A - visual bug with external model

### Expected behaviour

Pax cabin windows should have a metallic frame on the outer borders of the glass

### Evidence

TFDI model: 

![Microsoft Flight Simulator - 1 35 14 0 09_11_2023 13_59_31](https://github.com/invernyx/md11-bugs/assets/79177080/79ad924a-83ed-43ed-ad4f-164c53bbdcba)

Real MD-11:

https://flickr.com/photos/yyztc/36407572752/

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been resolved.
