### ISSUE TITLE
[BUG] - External model (pax + freighter) - Exaggerated pressurisation cycle normal maps on fuselage

### ISSUE THREAD

**Issue by ProfessorMadman** [invernyx/md11-bugs#406]
### Describe the bug

Fuselage normal maps indicating pressurisation cycles are exaggerated

### Steps to reproduce

N/A - Visual bug with normal maps

### Expected behaviour

Less pronounced panelling on the normal maps indicating expansion/contraction due to pressurisation cycles

https://live.staticflickr.com/65535/49160280713_2533485515_o.jpg
https://flickr.com/photos/manlezl/28572214240/

### Evidence

![Microsoft Flight Simulator - 1 35 14 0 09_11_2023 16_39_39](https://github.com/invernyx/md11-bugs/assets/79177080/7d4a7db8-16ee-47cd-8f9f-2af8d9675aa9)

<img width="1920" alt="Microsoft_Flight_Simulator_Screenshot_2023 11 09_-_16 10 01 15" src="https://github.com/invernyx/md11-bugs/assets/79177080/e70bad5d-17a3-404b-b7b0-7935ecb709ca">

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been fixed in the latest texture update.
