### ISSUE TITLE
[BUG] - APU exterior sounds missing

### ISSUE THREAD

**Issue by EngineIgnition** [invernyx/md11-bugs#407]
### Describe the bug

Exterior APU sounds missing

### Steps to reproduce

Start APU

### Expected behaviour

APU sounds in exterior noticeable

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.66+ fully (P3D + MSFS)

**Comment by EngineIgnition** [comment]
Still no external APU sounds for me and I am on the latest version.
