### ISSUE TITLE
[BUG] - No wing flex

### ISSUE THREAD

**Issue by EngineIgnition** [invernyx/md11-bugs#408]
### Describe the bug

No wing flex visible

### Steps to reproduce

Taxi, Takeoff, sudden pitch changes

### Expected behaviour

Wing flex during pitch changes, turbulence, taxi

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Wingflex rigging and animation is complete; needs to be merged with Aaron's exterior model changes prior to the artwork update
