### ISSUE TITLE
[BUG] - {{UPS Livery has incorrect UPS logo on tail}}

### ISSUE THREAD

**Issue by stevedra** [invernyx/md11-bugs#409]
### Describe the bug

The TFDI livery is depicted as the old UPS livery with the "Synchronizing..." on the fuse.  However, the logo on the horiz. stab is the new UPS logo.  Note the differences in logo in the expected behavior section 

### Steps to reproduce

None.  See expected behavior section.

### Expected behaviour

Note the picture of the UPS logos.  The new one (depicted in the TFDI UPS livery), is in the center, whereas the old one that should be associated with the livery is in the lower right corner of the picture.
![chrome_9lG6Paf33y](https://github.com/invernyx/md11-bugs/assets/150442893/6180677b-f49c-45d5-8616-c5f48d484305)

### Evidence

See Expected behavior box (this screen would not let me drag and drop the screen into this section, but it would in the expected behavior section so I placed the data there.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
someone can make a custom livery that does this
