### ISSUE TITLE
[BUG] - Premature descent at -500fpm from calculated TD

### ISSUE THREAD

**Issue by ProfessorMadman** [invernyx/md11-bugs#410]
### Describe the bug

Aircraft descends 200+nm from dest even though calculated TD was way later in the route

### Steps to reproduce

This is a relatively short hop so should be easy to reproduce:

TNCM RWY10 MULLET2 DANDE M576 MILOK DCT ACORA ACORA1N RNAV RWY 10 TNCB

Climb and cruise phase was fine - FMS calculated TD approx 1/2 way between MILOK and ACORA

I dailled in lower alt in FCP but didn't pull the knob to descend during descent planning.

Prior to reaching MILOK, at FL400, the aircraft decided to initiate an auto-descent around 200NM from EOD at a -500FPM rate and autopilot commanded 200KIAS at FL400 on this descent.  200KIAS is not a speed restriction at ACORE so no idea where the FMS got that from.

I set manual thrust to M.81 whilst the aircraft continued on a slow descent to 2500 ft alt at -500FPM.  The aircraft eventually caught the vertical descent profile at around FL230 and 44NM prior to reaching ROGNA.  ND VTI magenta dot remained on the top end of the scale for the duration of the descent until it caught up with the descent profile at this point and the commanded vertical speed increased to > -2000fpm

Remainder of arrival and approach was without issue.

### Expected behaviour

Aircraft should not descent prior to calculated TD at a reduced rate.

### Evidence

See FMA and CDU here:
https://i.imgur.com/TdJYeeP.jpg

State when catching up with vertical descent profile (ignore overspeed, I forgot to use spoilers while writing this bug report :))
https://i.imgur.com/7K6SNDd.jpg

Volanta tracking showing slow -500fpm descent and then catching up with vertical descent profile:
<img width="835" alt="Screenshot 2023-11-10 121838" src="https://github.com/invernyx/md11-bugs/assets/79177080/b4901504-85a4-4d1e-b2ee-34a83a27ba25">

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Bank

0 degrees

### Heading

240

### Altitude

FL400

### Departure

TNCM

### Arrival

TNCB

### Cruise level

FL400

### ZFW

159341

### CG

34.8 ZFWCG

### Fuel

17000kgs

### Cost index

50

### Route

TNCM10 MULLET2 DANDE M576 MILOK DCT ACORA ACORA1N TNCB10 (RNP)

### Location

Issue occurred prior to reachng MILOK

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I think this comes down to the decent being triggered on the leg T/D is on instead of at T/D

**Comment by turbofandude** [comment]
This should be resolved by improvements in 0.30+
