### ISSUE TITLE
[BUG] - FMC Coordinate Entry Producing Duplicate Fix Page

### ISSUE THREAD

**Issue by timv217** [invernyx/md11-bugs#411]
### Describe the bug

Enterting Coordinates Brings Up Duplicate Waypoints 

### Steps to reproduce

Enter a coordinate i.e. 7020N into Legs Page

### Expected behaviour

Coordinate Entry, not a duplicate page

### Evidence

![Microsoft Flight Simulator 10_11_2023 12_22_34](https://github.com/invernyx/md11-bugs/assets/33424163/12b9945d-e316-4ca3-a7d2-5b4bdbb540c2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

EHAM

### Arrival

CYVR

### Cruise level

360

### ZFW

155.9 Tons KG

### CG

22

### Fuel

70500kg

### Cost index

75

### Route

BERG2S BERGI DCT AMGOD DCT GODOS P1 ROKAN DCT
           TINDI/N0483F360 P1 ROLUM P13 ASKAM L7 TIMUP DCT SOSAR DCT
           66N010W/M083F340 70N020W 73N040W/M083F360 74N060W DCT DAPAK DCT
           72N080W/N0482F380 6930N09000W 65N100W 58N110W/N0471F400 DCT YMM J527
           YZU DCT 51N120W DCT MERYT T713 SPUZZ/N0432A160 T713 BOOTH

### Location

EHAM, Gate F8

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.30+
