### ISSUE TITLE
Tires moving around while gear up/down

### ISSUE THREAD

**Issue by PatrickChai** [invernyx/md11-bugs#412]
### Describe the bug

While gear go up or down, the tires on the main gear are moving/turning around as well. 

### Steps to reproduce

Move gear up or down.

### Expected behaviour

They should not move/flip around.

### Evidence

None

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
known

**Comment by FreakyD777** [comment]
There is already a bug write up for this

**Comment by PatrickChai** [comment]
Just updated to the latest version but in my case it's not fixed.
