### ISSUE TITLE
[BUG] - TFDi MD11 AA livery, 2 issues with tail logo

### ISSUE THREAD

**Issue by stevedra** [invernyx/md11-bugs#413]
### Describe the bug

The AA TFDI livery is depicted with the AA's backwards on the left side, and with the eagle backwards on both sides.   Note the differences in logo in the evidence section 

### Steps to reproduce

None.

### Expected behaviour

None.

### Evidence

Note on the left side...the Blue A is forward...it should be aft on the left side.  Also...the stylized eagle should face forward on both sides.  As someone who's painted this livery many times, I know these are easy mistakes to overlook, and AA fanatic fans will call you out on it every time (been there, LOL).
![paintdotnet_qI2U1DjXE3](https://github.com/invernyx/md11-bugs/assets/150442893/fa6287e9-0380-49f1-9476-1beee0b8ba77)

![chrome_08C82AiuAJ](https://github.com/invernyx/md11-bugs/assets/150442893/2768c714-3de7-4ab6-bc02-f1c8eea19155)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by ElMikey70** [comment]
It's been fixed!
![image](https://github.com/invernyx/md11-bugs/assets/91681107/553b2b67-6697-458e-8da1-61e56303472e)
