### ISSUE TITLE
[BUG] - VOR and ADF static

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#414]
### Describe the bug

VOR and ADF static

### Steps to reproduce

When activating VOR and ADF it stays static. 
![StaticVOR_ADF](https://github.com/invernyx/md11-bugs/assets/150371828/a461b340-8f58-44af-8c34-fa7f1f52a234)
![StaticVOR_ADF2](https://github.com/invernyx/md11-bugs/assets/150371828/245e7d53-2def-4976-aea9-3d033cb44682)

### Expected behaviour

VOR and ADF should show the Distance to the next VOR / ADF / NDB

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by PatrickChai** [comment]
Same here.

**Comment by PatrickChai** [comment]
Not sure but with the latest update, I understood in the secret-dev-updates, that this is now fixed.
FIXED: GNS NAV Text on ND not changing to reflect navigation mode
However in my case with the latest update it's still not fixed and remains static.

**Comment by Dennis380** [comment]
> Not sure but with the latest update, I understood in the secret-dev-updates, that this is now fixed. FIXED: GNS NAV Text on ND not changing to reflect navigation mode However in my case with the latest update it's still not fixed and remains static.

Still the same. VOR and ADF static. It says: 272/23NM PBO

**Comment by PatrickChai** [comment]
> says: 272/23NM PBO

Exactly what I see too.

**Comment by PatrickChai** [comment]
Any news on when this will be fixed? I thing VOR/DME is important.

**Comment by turbofandude** [comment]
Resolved in 0.30+
