### ISSUE TITLE
[BUG] - FPL disappearing after pulling the route in the FMS and clicking  on INIT

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#415]
### Describe the bug

Whole FMS resets after pulled the FPL in and going to INIT page

### Steps to reproduce

When I filed my FPL in the FMS and went back to the INIT page the page is resetting and I have to re do everything and this happends now twice

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

0

### Departure

TNCM

### Arrival

TTPP

### Cruise level

0

### ZFW

0

### CG

0

### Fuel

0

### Cost index

0

### Route

-

### Location

TNCM

### Agreement

- [X] Yes

**Comment by nIn9R** [comment]
Confirming happened to me twice today on the F model.

**Comment by KJA1582** [comment]
Possible correlation:
I noted that the aircraft briefly displayed the VDEV. Afterwards, the plan was deleted.
It could be the aircraft erroneusly enters descent mode. Since it is on the ground with engines off, the plan gets cleared.
For reference: Altimeter was set to STD, METAR said 1001 hPa

**Comment by turbofandude** [comment]
This should be resolved with 0.36+.
