### ISSUE TITLE
[BUG] - ProgressPage with no Progress

### ISSUE THREAD

**Issue by Dennis380** [invernyx/md11-bugs#416]
### Describe the bug

ProgressPage with no Progress

### Steps to reproduce

![PROGRESSPage](https://github.com/invernyx/md11-bugs/assets/150371828/7a448eb5-ff1f-4598-9126-557f2a856398)

The Progress Page doesnt show any Times to the next Waypoint.

### Expected behaviour

Times have to be shown until next Waypoint. 

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

-

### Departure

-

### Arrival

-

### Cruise level

-

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.30+
