### ISSUE TITLE
[BUG] - GW on SD not updating with fuel burn

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#417]
### Describe the bug

The gross weight on the SD does not update throughout a flight as fuel burns

### Steps to reproduce

Load payload and fuel and note the GW and FUEL on the SD. Fly for a while and note that the GW does not decrease, but the FUEL does.

### Expected behaviour

The GW should decrease as the fuel level decreases.

### Evidence

![FlightSimulator_gqh3JaDjhj](https://github.com/invernyx/md11-bugs/assets/95483637/6b094373-68db-46f8-8bd4-cc61acd7f7aa)
![FlightSimulator_TnISv14JuX](https://github.com/invernyx/md11-bugs/assets/95483637/39a2c819-a379-4d08-af44-0da8343306d8)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

39000

### Agreement

- [X] Yes

**Comment by 09tir98** [comment]
Just noticed the same behavior regarding the CG on the SD. Only displays the CG that was entered on the weight init page of the FMC before departure, but does not update during the flight.

**Comment by nIn9R** [comment]
+1

**Comment by TheFightingRaven** [comment]
will be fixed in 0.13
