### ISSUE TITLE
[BUG] - add a onscreen keyboard to the efb

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#419]
### Describe the bug

EFB stucck and ruins flight 

### Steps to reproduce

Stuck in EFB

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
The keyboard being stuck should no longer happen since 0.15.0-alpha (24 November 2023). At this moment in time, we do not feel like adding an on-screen keyboard would be a worthwhile enhancement when the feature is readily available and works well.
