### ISSUE TITLE
[BUG] - Radio Frequency change

### ISSUE THREAD

**Issue by JBPFlight** [invernyx/md11-bugs#422]
### Describe the bug

FSHUD unable to change Radio frequency automatically

### Steps to reproduce

When using FSHUD for ATC, the aircraft doesn't automatically change frequency as others does when requested/required (for want of better words) by FSHUD

### Expected behaviour

Ability for external programmes to change radio frequency automatically

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Is this native to Microsoft Flight Simulator? If not, it may not be something we integrate with

**Comment by GenericNerd** [comment]
As this is an external program, it is likely that we have not integrated with it. We have an update coming that sends the frequencies to other programs like vPilot better, which may help with your issue. With that being said, please keep in mind that we are only looking for bugs related to the aircraft itself at this stage, not third-party software integration.
