### ISSUE TITLE
[BUG] - Fuel Usage with no engines/apu

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#423]
### Describe the bug

Fuel usage withut engines or apu running

### Steps to reproduce

- Spawn
- Observer ENG FUEL FLOW PPH:index SimVar for index = 1 to 3

### Expected behaviour

No Fuel Flow when nothing draws fuel

### Evidence

![Screenshot (368)](https://github.com/invernyx/md11-bugs/assets/2170028/7684c910-2f92-4f1c-a3c2-7d610b289005)
![Screenshot (369)](https://github.com/invernyx/md11-bugs/assets/2170028/2f207228-1785-4701-8dab-fe0657bce2cf)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
pretty sure we override this so it does not effect our actual fuel on board, please refile if you observe an actual reduction in fuel on board
