### ISSUE TITLE
[BUG] - Vr button push ignored until 3rd try

### ISSUE THREAD

**Issue by flymypi** [invernyx/md11-bugs#424]
### Describe the bug

When trying to accept Vr, the FMS returns "BUTTON PUSH IGNORED" twice before the V speed is accepted on the third try.

### Steps to reproduce

Set up FMS and try to accept V Speeds

### Expected behaviour

Should accept Vr on the first click, like it does for V1 and V2

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

EDFH

### Arrival

EHAM

### Cruise level

FL210

### ZFW

284k lbs

### CG

24.9

### Fuel

44.7k lbs

### Cost index

200

### Route

EDFH/21 N0450F210 RUDO1S RUDOT Q762 LULAT/N0458F220 Z104 RITAX M624 BUB Y28 HELEN HELE2A EHAM/27

### Location

Apron EDFH

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
you are pressing the buttons too quickly after each other, we need to make the interval a bit shorter but this is as intended

**Comment by flymypi** [comment]
Copy thatOn Nov 10, 2023 23:25, TheFightingRaven ***@***.***> wrote:
you are pressing the buttons too quickly after each other, we need to make the interval a bit shorter but this is as intended
