### ISSUE TITLE
[BUG] - {{Autothrottle not holding FMS commanded speed}}

### ISSUE THREAD

**Issue by JBPFlight** [invernyx/md11-bugs#425]
### Describe the bug

Autothrottle didn't roll back to commanded cruize speed at top of climb

### Steps to reproduce

After climbing direct to FL410, in FMS SPD mode the autothrottle wouldn't set back to hold the cruise speed

### Expected behaviour

Autothrottle to rollback and then hold to achieve cruise speed

### Evidence

![Screenshot 2023-11-10 153512](https://github.com/invernyx/md11-bugs/assets/150365728/8e5f3243-6c52-49f4-b8b4-1b7b2b6cf7c9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Pitch

2.5

### Bank

0

### Heading

64

### Altitude

41000

### Departure

EGFF

### Arrival

LEAL

### Cruise level

41000

### ZFW

320.9 lbs

### CG

25

### Fuel

33000lbs

### Cost index

20

### Route

EGFF/30 N0470F410 EXMO1A EXMOR DCT SKESO DCT OTOFE DCT PERDU UN862 MLA UN860 VLC VLC3N LEAL/28

### Location

Top of climb, northern france SKESO to OTOFE

### Agreement

- [X] Yes

**Comment by flymypi** [comment]
can confirm, constantly running into high speed protection when that happens for me

**Comment by turbofandude** [comment]
Please re-open this if it happens again.
