### ISSUE TITLE
[BUG] - flight Director button on the left isn`t working correctly

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#426]
### Describe the bug

The FD off button on the left of the captain specific isn`t working correctly. You havr to keep push the button to get the FD off and you cant just click on it you need to press and hold the button

### Steps to reproduce

Hope this will be fixed. Believe the other buttons underneath it has the same issue

### Expected behaviour

Fixing

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Landing

### Altitude

1600FT

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
@jhattermann the captains FD button is momentary but it should be latching

**Comment by turbofandude** [comment]
Resolved in 0.25+
