### ISSUE TITLE
[BUG] - EFB Payload page open in PAX config when loading in freighter

### ISSUE THREAD

**Issue by nIn9R** [invernyx/md11-bugs#427]
### Describe the bug

EFB has PAYLOAD Page open with the PAX options when spawning into the freighter.

### Steps to reproduce

With Cold & Dark selected default, load into the freighter model and look at the EFB. Page will switch to freighter config when selecting different EFB Page and then switching back.

### Expected behaviour

Display payload page with freighter config. 

### Evidence

chickened out to make a screenshot I'm sorry.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
already filed
