### ISSUE TITLE
[BUG] - Mismatched Panel Lighting

### ISSUE THREAD

**Issue by aaronwmg** [invernyx/md11-bugs#428]
### Describe the bug

Mismatched Backlight Lighting

### Steps to reproduce

Turn on the overhead panel lights

### Expected behaviour

Lighting will overwrite textures but instead will show twice (once lit and once unlit)

### Evidence

![20231110181632_1](https://github.com/invernyx/md11-bugs/assets/150463635/905957f2-14e6-44c0-b2a5-60070478c678)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
already filed
