### ISSUE TITLE
[BUG] - related to #415: Unable to select SID after entering FPLN

### ISSUE THREAD

**Issue by nIn9R** [invernyx/md11-bugs#429]
### Describe the bug

After typing in flightplan, then pressing LSK at departure airport, selection shows "STAR >" and no "< SID" option. Tried to go out of FPLN via INIT and then experience bug #415 that FPLN is deleted.

### Steps to reproduce

Load freighter model, cold & dark, BATT ON, GPU ON, select IRS TO NAV, DESELECT IRS TO OFF, IRS TO NAV AGAIN, wait, enter FPLN KMEM/PHNL, delete FLT PLN DISCONT's, select LSK on KMEM, observe.

### Expected behaviour

As its the defined departure airport in the FLTPLN there should be a SID-Option when pressing LSK, not a STAR.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

KMEM

### Arrival

PHNL

### Cruise level

FL340

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

194

### Route

DUCKZ5 HELAR KM30G KF30C KA30Y IMMAS KA27Q NABOB KA24M CABIC SXC C1177 FICKY R578 FIZEL R578 FITES LNY SHLAE1

### Location

KMEM stand 801

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should have been resolved a while back
