### ISSUE TITLE
[BUG] - XPDR ALT RPTG no clickspot, doesn't communicate XPDR State outside MSFS (e.g. vPilot)

### ISSUE THREAD

**Issue by nIn9R** [invernyx/md11-bugs#430]
### Describe the bug

Transponder ALT RPTG OFF/ON has no clickspot. Switching Transponder states (SBY/XPDR/TA/TARA) doesn't communicate outside for e.g. vPilot to feel.

### Steps to reproduce

Load in, try to manipulate the ALT RPTG knob. Open vPilot, switch transponder modes.

### Expected behaviour

XPDR should communicate Mode C on state change to one of the active modes.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0-34000

### Agreement

- [X] Yes

**Comment by Hawks1326** [comment]
+1

**Comment by TheFightingRaven** [comment]
two issues,
@turbofandude the transponder doesn't communicate with the outside
@jhattermann no clickspot for some buttons on the transponder

**Comment by turbofandude** [comment]
Resolved
