### ISSUE TITLE
[BUG] - Landing weight increase after 08:00 hour flight

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#431]
### Describe the bug

Landing weight on the TO/APPR site increase after more then 8 hours flight

### Steps to reproduce

see the pictures below I make in short times:

1.picture: time: 19:07     LW: 560288  lbs
2.picture: time: 19:08     LW: 560322  lbs
3.picture: time: 19:11     LW: 560381  lbs

### Expected behaviour

LW has to decrease every seconds, not in the other direction.

### Evidence

![MD11_LW_time_1907](https://github.com/invernyx/md11-bugs/assets/83859593/429ca4a5-f892-4d07-ac74-ce937345e74e)
![MD11_LW_time_1908](https://github.com/invernyx/md11-bugs/assets/83859593/e79fb281-bc1f-484a-aaf8-8b0301a39f42)
![MD11_LW_time_1911](https://github.com/invernyx/md11-bugs/assets/83859593/573d27f3-216e-4e75-8f0a-83b0f29da21a)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL330

### Departure

LIMC

### Arrival

WSSS

### Cruise level

FL330

### ZFW

343500 lbs (Maximum)

### CG

20

### Fuel

256000 lbs

### Cost index

85

### Route

LIMC/35R N0485F290 VAK9Q VAKON Q702 OTKEK DCT LABIN/N0484F310 DCT SONIK DCT NISVA/K0900F310 Q13 UDROS/N0485F310 UM859 KARDE UN644 ZERGE/N0484F330 UN644 ROLIN N644 LAGAS M747 SUBUT T923 ERLEV M11 RODAR A909 TUNEK B143 KRS A240 INRAK B449 RANAH L750 DUDEG/N0484F350 L750 ZB G201 BINDO L750 MERUN L333 KKJ L759 MABUR/N0487F370 L759 PUT W14 HTY A334 PASVA Y514 NUFFA DCT PIBAP DCT PASPU DCT NYLON DCT WSSS/20R

### Location

between India and Malasia
Waypoint  LAMBU to MABUR

### Agreement

- [X] Yes

**Comment by nIn9R** [comment]
can confirm bug happening to me on KMEM - PHNL. Weight on CTR RIGHT DISPLAY doesnt change, TO/APPR LW increases; checked with SIM PYLD which decreases realistically. Possibly related to trim calculations being off in approach

**Comment by dr71205** [comment]
I expect this to also be related to the flawed/nonexistent fuel prediction

**Comment by TheFightingRaven** [comment]
this I think mostly has to do with the low fuelburn

**Comment by Juanandonly1** [comment]
4 hour Flight SDF-KTUS LW slowly keeps creeping up 
![image](https://github.com/invernyx/md11-bugs/assets/150832144/519865e3-ccbb-4892-ab62-7b10d7202337)
Total Gross is below LW

**Comment by TheFightingRaven** [comment]
will be fixed in 0.13
