### ISSUE TITLE
Altitude, VS and overheard fuel windows displayed values are cropped [BUG] - {{Brief Description}}

### ISSUE THREAD

**Issue by sersanchez** [invernyx/md11-bugs#432]
### Describe the bug

Looking at the windows where this information is displayed, the values are cropped

### Steps to reproduce

When in the plane, look at the windows for the Altitude and VS in the GCP or the fuel displays on the overhead, the values are cropped. They need to be moved a bit to display complete

### Expected behaviour

The values should display complete

### Evidence

![Windows](https://github.com/invernyx/md11-bugs/assets/11690639/05e2a98e-c848-4871-be19-1c4603d99d6f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
already filed
