### ISSUE TITLE
[BUG] - Descend meatball does not update until waypoint is reached

### ISSUE THREAD

**Issue by sersanchez** [invernyx/md11-bugs#433]
### Describe the bug

The meatball commanding the descend does not update continuosly

### Steps to reproduce

Start a descend. The meatball starts in the middle as expected, but as the plane descends, the meatball starts going up as if you needed to stop the descent, but when you reach the next waypoint, the meatball jumps to the bottom of the line, commanding you to drop the plane like a rock.

I tried using the profile descend and that seems to work, but is confusing if you are trying to monitor to reach the next waypoint as scheduled in the Flight Plan

### Expected behaviour

The meatball should stay in the center of the descend line as you pass through all waypoints and update as you descend and get closer to the waypoint, giving you clues as if you need a steeper descend or need to use drag.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Pitch

15 degrees

### Bank

No bank

### Heading

030

### Altitude

from 37000 to 24000

### Departure

KDFW 

### Arrival

KBOS

### Cruise level

FL390

### ZFW

373.0

### CG

21.2

### Fuel

17.0

### Cost index

20

### Route

KDFW/36R N0467F390 AKUNA9 MLC DCT KM36G DCT KENBE DCT VHP DCT DJB DCT JHW Q82 PONCT JFUND2 KBOS/22L

### Location

PONCT

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved by improvements in 0.30+
