### ISSUE TITLE
[BUG] - Erratic control inputs after winds (aloft) update

### ISSUE THREAD

**Issue by nIn9R** [invernyx/md11-bugs#434]
### Describe the bug

Autoflight starts turning left/right erratically, when AP disconnect continues to do so with inboard ailerons. Also continuous loss of airspeed although maintaining altitude.

### Steps to reproduce

Climb to cruise level with live weather (in this case left front w/ 40KTS), wait for winds to update (if significant change) or : DESELECT live weather having preset "clear skies" selected and observe.

### Expected behaviour

realign itself on lateral nav path after adjusting to new winds.

### Evidence

[https://youtu.be/JhweHlvv9BM?si=ZLSe82VfsA1Lnf1G](url)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

KMEM

### Arrival

PHNL

### Cruise level

340

### ZFW

364250

### CG

25.8

### Fuel

138000

### Cost index

194

### Route

DUCKZ5 HELAR DCT KM30G DCT KF30C DCT KA30Y DCT IMMAS DCT KA27Q DCT NABOB DCT KA24M/N0489F320 DCT CABIC DCT SXC C1177 FICKY R578 FIZEL/N0492F340 R578 FITES DCT LNY SHLAE1

### Location

FIX "FOOTS"

### Agreement

- [X] Yes

**Comment by nIn9R** [comment]
same situation occuring again after FMS drew a circle around enroute waypoint FLITTY. My guess is AP tried to execute the turn, then disconnected due to being unable to follow magenta line (which explains why I found the aircraft crashed on the ground on the last two flight attempts). on AP reconnect aircraft rejoins behavior shown in video. Will open another bug report for circling waypoint

**Comment by turbofandude** [comment]
This should have long since been resolved.
