### ISSUE TITLE
[BUG] - Bracket Altitude Constraints

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#435]
### Describe the bug

Bracket altitude constraints when manually entered will chnage to ABV -9999 if enetered with the ABV befor the BEL

### Steps to reproduce

At any given waypoint, enter bracket altitude constraint starting with  AT OR ABOVE and then AT OR BELOW
Observe AT OR ABOVE change to -9999

When entered AT OR BELOW and the AT OR ABOVE, works as excpected.

Secondary bug: Scratchpad does not cleat on AT OR BELOW entry

### Expected behaviour

Regardless of which way aroun, both constraints shall be entered

### Evidence

![Screenshot (374)](https://github.com/invernyx/md11-bugs/assets/2170028/91c80193-9466-497a-a79d-c886fab0e9dd)
![Screenshot (375)](https://github.com/invernyx/md11-bugs/assets/2170028/01698d12-2eb0-4e53-a441-075054cad884)
![Screenshot (376)](https://github.com/invernyx/md11-bugs/assets/2170028/27517f14-d430-4f22-85fe-e2d1de371243)
![Screenshot (377)](https://github.com/invernyx/md11-bugs/assets/2170028/644dd178-2b66-42fc-afc9-c8718179d99c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

EDDP

### Arrival

EHAM

### Cruise level

230

### ZFW

433.4 Lbs

### CG

29.7

### Fuel

37.3 Lbs

### Cost index

80

### Route

EDDP/26L N0446F230 PENE1S PENEM Y233 ODLUN Z207 MAG M736 SOGMA M748 RARUP RARU2D EDDH/15

### Location

RARUP constraints, EDDH Chart 10-2L, 5 AUG 22

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.19+
