### ISSUE TITLE
[BUG] - Random circle on waypoint enroute causes AP disconnect and aircraft spinning into crash

### ISSUE THREAD

**Issue by nIn9R** [invernyx/md11-bugs#436]
### Describe the bug

similar to already fixed bug the FMS puts a tight magenta circle randomly on waypoints enroute. On trying to execute said turn AP disconnects, aircraft flies in steep bank into ground,

### Steps to reproduce

Fly KMEM -> PHNL with route DUCKZ5 HELAR DCT KM30G DCT KF30C DCT KA30Y DCT IMMAS DCT KA27Q DCT NABOB DCT KA24M/N0489F320 DCT CABIC DCT SXC C1177 FICKY R578 FIZEL/N0492F340 R578 FITES DCT LNY SHLAE1 PHNL. Climb to cruise level and wait.
Happened on 3 out of 3 tries. Once around waypoint KF30C, once before waypoint FLITY, once between FLITY and FIZEL.

### Expected behaviour

Aircraft not trying to kill me... jokes aside, to be longhaul capable it should be expected to follow lateral and vertical guidance without catastrophic misinterpretations.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Departure

KMEM

### Arrival

PHNL

### Cruise level

FL340

### ZFW

364250

### CG

28

### Fuel

183000

### Cost index

194

### Route

DUCKZ5 HELAR DCT KM30G DCT KF30C DCT KA30Y DCT IMMAS DCT KA27Q DCT NABOB DCT KA24M/N0489F320 DCT CABIC DCT SXC C1177 FICKY R578 FIZEL/N0492F340 R578 FITES DCT LNY SHLAE1 PHNL/04L

### Location

KF30C, FLITY, FIZEL

### Agreement

- [X] Yes

**Comment by dodoactual** [comment]
Also happened during standard SID-ENR-STAR flight plan from KDEN-KOMA. Clockwise circles depicted on flight path magenta line around random waypoints/fixes from the flight plan. Potentially related, while direct to an IF on an RNAV GPS (RNAV GPS Y 14L (KOMA) from BOYSS), autoflight executed a right turn in the opposite direction upon activating DIR and exceeded 30 degrees bank with erratic lateral/vertical movements, thus disconnecting the autopilot.

**Comment by Thunderbird1337** [comment]
+1
![2](https://github.com/invernyx/md11-bugs/assets/150375986/c0a68e3a-309f-4f06-bd95-9f787305c8ec)

**Comment by cvanallen99** [comment]
Also happens if you reach the end of your flight plan and havent descended. Instead of just maintaining level flight, it'll spiral down.

**Comment by nIn9R** [comment]
Problem persists in current version. Happened on straight line between waypoints ECIGE and ICT on FL340.

**Comment by Thunderbird1337** [comment]
also in the current version existent
![Uploading 3.jpg…]()

**Comment by TheFightingRaven** [comment]
fixed in .30
