### ISSUE TITLE
[BUG] - blue no smoking on center display should be at the bottom instead of the top

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#437]
### Describe the bug

The “NO SMOKING” blue message at the center display is placed at the top of the menu, but according to IRL pictures and a good friend of mine his dad worked as a maintenance on the MD11 its at the bottom, could this be fixed!

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.13+
