### ISSUE TITLE
[BUG] - Missing CAWS sounds after second session

### ISSUE THREAD

**Issue by aurumusagi** [invernyx/md11-bugs#438]
### Describe the bug

CAWS does not sound after starting flight for the second time

### Steps to reproduce

Start MSFS and flight after the first one with the MD-11

### Expected behaviour

CAWS should sound when there's a warning that has an aural (eg, "AUTOPILOT" after autopilot disengage)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
already filed
