### ISSUE TITLE
[SUGGESTION] - Couple LastState to aircraft Registration

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#440]
### Describe the bug

Akin to how the options are saved, I propose a change to handle LastState the same way. This would further enhance immersion as currently, all aircraft share the same last state.

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Done as of 0.13+
