### ISSUE TITLE
[BUG] - Cargo Flow position and color

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#441]
### Describe the bug

incorrect cargo flow position and light

### Steps to reproduce

Cargo flow on Cargo Fire Panel is off and off light is cyan

### Expected behaviour

normal position should be on (no light) and the off light should be amber instead of cyan as it's an abnormal position 

### Evidence

<img width="673" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/70bce8cf-f295-4883-8e28-75e040c7e83d">

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
@jhattermann can we get the color of the off light changed?
