### ISSUE TITLE
[BUG] - GW display on SD ignores zero

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#442]
### Describe the bug

If the 4th number of the gross weight is a zero it will be ignored on the GW display on the SD. A GW of 241055 kg for example will be displayed as 24155 kg. It only happens if the 4th number is a zero, all other positions can have a zero.

### Steps to reproduce

Load the aircraft so that the 4th number (hundreds) of the gross weight is a zero (ex 241055 kg) and press line select 2R on init page 2 in the FMC. Check the GW on the SD is missing a zero.

### Expected behaviour

The GW should be displayed correctly.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/95483637/726ea062-eeb8-4b85-8d23-cc59aaf76b86)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by 09tir98** [comment]
If both the 4th and 5th numbers (hundreds and tenths) are zero both zeros will be skipped. So 242005 kg GW will be displayed as 2425 kg GW

**Comment by TheFightingRaven** [comment]
fixed in 0.13
