### ISSUE TITLE
[BUG] - STBY Analog IAS incorrect

### ISSUE THREAD

**Issue by bassplane** [invernyx/md11-bugs#443]
### Describe the bug

In flight the STBY analog airspeed reads 450 KTS instead of current IAS.

### Steps to reproduce

Take-off, climb/cruise - read the stby analog airspeed.

### Expected behaviour

Should indicate the current IAS.

### Evidence

![Screenshot 2023-11-10 233953](https://github.com/invernyx/md11-bugs/assets/150367558/71851f4c-4dbf-4ced-8757-1959119f8a36)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.13+
