### ISSUE TITLE
[BUG] - Fuel Usage with no engines/apu

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#444]
### Describe the bug

Fuel usage without engines or apu running.
First noticed in my VAs ACARS

### Steps to reproduce

Spawn
Observer ENG FUEL FLOW PPH:index SimVar for index = 1 to 3
Observe TOTAL FUEL QUANTITY Simvar over a short span of time (10 min for the pics below)

### Expected behaviour

No Fuel Flow when nothing draws fuel

### Evidence

See images in https://github.com/invernyx/md11-bugs/issues/423
Additionally:

![Screenshot (379)](https://github.com/invernyx/md11-bugs/assets/2170028/f5b0c0fd-9a2e-4a0b-99e2-16ea2845e5d1)
![Screenshot (380)](https://github.com/invernyx/md11-bugs/assets/2170028/6e27958e-8e76-48b3-9973-a3e307c42447)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
