### ISSUE TITLE
[BUG] - Aircraft Not showing up in simulator after install

### ISSUE THREAD

**Issue by avmetroman** [invernyx/md11-bugs#446]
### Describe the bug

When installing the Aircraft to a folder on another drive it will not show up in the simulator

### Steps to reproduce

Run the TFDI install. 
Install the aircraft on another drive
Install completes with out issue
Run MSFS
Aircraft is not showing in the Aircraft Menu.

### Expected behaviour

Aircraft should be show up in the simulator. Or the installer should indicate there is a specific folder that you need to target. 

Workaround:
Copy the installation files from the folder where they were installed. To the MSFS community folder
`AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community` 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is not a bug, the aircraft NEEDS to be installed into the the community folder, we will put a label in the installer
