### ISSUE TITLE
[BUG] - No Main cargo door on the EFB with the MD11F version

### ISSUE THREAD

**Issue by Vekant** [invernyx/md11-bugs#447]
### Describe the bug

No Main cargo door on the EFB with the MD11F version

### Steps to reproduce

I no longer have a Main cargo door on the EFB with the MD11F version. The first day of release it was there, but I launched the tfdi update and since then it has disappeared. To see the photo

### Expected behaviour

impossible to open the cargo door

### Evidence

![FlightSimulator_rXyxkssJSf](https://github.com/invernyx/md11-bugs/assets/96705804/06236f31-582d-4343-ba82-e38f133ba0e5)
![FlightSimulator_6GQIsqu0kw](https://github.com/invernyx/md11-bugs/assets/96705804/b5e04437-948e-42f2-bc43-0f41881cac24)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
did this problem persist? never seen it myself

**Comment by Vekant** [comment]
with the last update it came back correctly thank you!
![FlightSimulator_5EPfWOu8ZV](https://github.com/invernyx/md11-bugs/assets/96705804/fbf31fa3-b6a1-4dd5-830e-b830d85af98b)
![FlightSimulator_G3SLhwhSxe](https://github.com/invernyx/md11-bugs/assets/96705804/0077ea66-adb1-41d5-b303-b3d040639d0c)
