### ISSUE TITLE
[BUG] - wingtip front dual strobes (HI-INT) missing

### ISSUE THREAD

**Issue by ihulsbus** [invernyx/md11-bugs#448]
### Describe the bug

the double flash strobes on the front side of the wing tips are missing 

### Steps to reproduce

1. load aircraft at any location, perferably at night for easier visibility
2. turn on HI-INT lights
3. Observe missing front double flash strobes 

### Expected behaviour

Correct strobe simulation and sequence is expected. Based on the video evidence provided below, the first flash of the front strobe is simultanious with the aft wingtip strobe flash. The second flash follows shortly after. 

### Evidence

Sequence best visible at 0:40 at 0.25 speed 
https://www.youtube.com/watch?v=0IaoBmr7lL0

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Fixed in internal build. Will be released on next artwork update.
