### ISSUE TITLE
[BUG] - GPWS Test switch not working

### ISSUE THREAD

**Issue by sersanchez** [invernyx/md11-bugs#449]
### Describe the bug

When you click the GPWS TEST switch, it goes to FLAP OVRD when guarded

### Steps to reproduce

On the overhead, top right, click the GPWS Test switch. It moves "up". 

### Expected behaviour

This should not be possible as the guard is on. It should move "down" to perform the test.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

600ft

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This was fixed in 0.39.0-alpha
