### ISSUE TITLE
[BUG] - strobe (HI-INT) light points not visible on aircraft

### ISSUE THREAD

**Issue by ihulsbus** [invernyx/md11-bugs#450]
### Describe the bug

There are no visible strobe light points on the aircraft. Only the ground illumination

### Steps to reproduce

1. Load aircraft into any location, preferably at night
2. Turn on HI-INT lights
3. Observe HI-INT illumination on ground
4. Observe missing light sources on wingtips

### Expected behaviour

Strobe lights have their light sources modeled just as the NAV lights. 

### Evidence

the video is taken AFT of the aircraft looking forward. You can see the illumination of the strobe on the winglets, but the lack of light source.
https://github.com/invernyx/md11-bugs/assets/11390889/af6ef9bd-7c9b-43cd-b257-4c8b72d8fab3

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by HV7572KC** [comment]
Next to this, the MD11 has 2 points of strobe-lights. The first in front of the winglet, it's flashing more or less like Airbus, 2 flashes after each other. The second all the way at the end behind the winglet, this is flashing like Boeing, just 1 flash.
Check this Youtube clip for how it lookslike in real
https://youtu.be/6fyMpOwS45M?si=wQ3DTvOg5a_1fLrR

**Comment by ihulsbus** [comment]
> Next to this, the MD11 has 2 points of strobe-lights. The first in front of the winglet, it's flashing more or less like Airbus, 2 flashes after each other. The second all the way at the end behind the winglet, this is flashing like Boeing, just 1 flash. Check this Youtube clip for how it lookslike in real https://youtu.be/6fyMpOwS45M?si=wQ3DTvOg5a_1fLrR

@HV7572KC  Also noted in https://github.com/invernyx/md11-bugs/issues/448 😄

**Comment by arwasairl** [comment]
Fixed in internal build. Will be released on next artwork update.
