### ISSUE TITLE
[BUG] - MCP and PFD selected ALT disagreement

### ISSUE THREAD

**Issue by ihulsbus** [invernyx/md11-bugs#453]
### Describe the bug

When using step climb. the MCP and PFD are in disagreement of the selected altitude.

### Steps to reproduce

1. Fly a route utilising step climbs
2. Perform the step climb via the MCP
3. Plane climbs to new commanded cruise altitude. PFD altitude tape, MCP and FMS are correct, but the FMA and notion below the altitude tape disagree with the altitude selected in the MCP

### Expected behaviour

all systems are in full agreement of the selected and present altitude. 

### Evidence

![Screenshot 2023-11-11 150048](https://github.com/invernyx/md11-bugs/assets/11390889/fcd98e72-eba4-46ab-add2-46a630475b66)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by ihulsbus** [comment]
with some more flights I get the idea this might be more towards the FMC not managing the step climbs correctly. I'd have to look into the FCOM to see if I can find more information on this.

**Comment by TheFightingRaven** [comment]
stepclimbs are not finished
