### ISSUE TITLE
[BUG] - cabin alt issues from high elevation fields

### ISSUE THREAD

**Issue by henkhugo** [invernyx/md11-bugs#454]
### Describe the bug

Getting cabin alt warnings 

### Steps to reproduce

Took off from Johannesburg and on the climb out I get cabin alt warnings. See attached screenshots

### Expected behaviour

Proper pressurization 

### Evidence

![20231111170242_1](https://github.com/invernyx/md11-bugs/assets/150338137/a985c0af-24b3-4fa7-a4a1-c1e3995dca57)
![20231111170251_1](https://github.com/invernyx/md11-bugs/assets/150338137/dccc5c2b-6a27-49c1-bda1-758e7e95620f)
![20231111170300_1](https://github.com/invernyx/md11-bugs/assets/150338137/070d4fd6-d7b9-4231-a1d0-68f9202757df)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

FL200

### Agreement

- [X] Yes

**Comment by henkhugo** [comment]
Replicated the issue climbing out of Denver passing FL300

![20231111183724_1](https://github.com/invernyx/md11-bugs/assets/150338137/23bc083c-e4a2-49e2-a70d-0fada14d5c1d)
![20231111183727_1](https://github.com/invernyx/md11-bugs/assets/150338137/dc9be370-a90a-47e3-a06d-eeae6e14a9bc)
![20231111183729_1](https://github.com/invernyx/md11-bugs/assets/150338137/b777f288-53b7-44a0-92db-f9e228ac6144)

**Comment by henkhugo** [comment]
Replicated again out of Nairobi in the F

**Comment by cvanallen99** [comment]
+1 Can confirm on KDEN.  Triggered sometime between FL300 and FL350

**Comment by turbofandude** [comment]
Resolved in 0.29+
