### ISSUE TITLE
[BUG] - Entire Flight Deck will freeze when using FMC

### ISSUE THREAD

**Issue by avmetroman** [invernyx/md11-bugs#456]
### Describe the bug

It seem that if you double press a buttons in the FMC from time to time it will cause the entire flight deck to Freeze

### Steps to reproduce

1. Plan a flight
2. Take off and start making change to the FMC
3. Try push buttons twice or scroll up and down the flight plan page. 
4. The aircraft will continue to fly but all buttons will be come unresponsive as well as gauges which will freeze on their last input.
![tfdi_freeze_flightdeck](https://github.com/invernyx/md11-bugs/assets/19178971/f1e5bd70-408c-401f-ba6c-d316f3ae0587)

Note:
I had made a mistake with the flight plan prior to departure and was trying to correct it mid flight. However this did happen to me before on a previous flight. 

### Expected behaviour

FMC should not cause the the flight deck to freeze

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

24400

### Departure

KLGB

### Arrival

KPHX

### Cruise level

410

### ZFW

unknown 

### CG

unknown 

### Fuel

31,079 lbs

### Cost index

37

### Route

KLGB/30 N0472F410 FRITR3 CNERY DCT BLH HYDRR1 KPHX/08

### Location

I was able to make a landing at Palm Springs, the Aircraft would still fly but had no instruments. 

### Agreement

- [X] Yes

**Comment by avmetroman** [comment]
The screen shot provide shows how the AH is level while the aircraft is in a left turn.

**Comment by crazyforiphone** [comment]
I had this issue when trying to put coordinates into a flight plan. Unfortunately I did not get a screenshot prior to closing the sim.

**Comment by TheFightingRaven** [comment]
this is a wasm crash, hard to diagnose and not necessarily connected to the fms

**Comment by turbofandude** [comment]
Without EXACT steps, this is hard to resolve. We have also fixed several things since this that could have caused it, so I am going to close this out.

**Comment by avmetroman** [comment]
@turbofandude Last time I had this issue was scrolling through the flight plan, I did see in the last patch that this was fixed. If I can reproduce it in another situation I'll let you know.
