### ISSUE TITLE
[TODO] - Overall improvements to the external model & issues noticed

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#458]
### Describe the bug

See below 

### Steps to reproduce

- Overall the external model does look good however i feel it could do with some definition to it. At the moment it feels "flat". I'd love to see all the bolts and metal look amazing. That said, i have found some issues that could do with some improvement if not already added to the to do list. 

-  Engine heat blur doesn't exist. 
- The strobe lights are really dim & hard to see.
- There's no actual bulbs in the nav lights & strobe lights. 
- No pilots in the flightdeck in the external view.

### Expected behaviour

As i understand this is an alpha & of course things are to be fixed & improved however thought i'd send over my thoughts & finds in case you hadn't noticed them already. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the model isn't finished

**Comment by arwasairl** [comment]
All items except the last one have been implemented. That said, this bug will be closed as completed.
