### ISSUE TITLE
Flap selector doesn't correspond with PFD indication

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#460]
### Describe the bug

Dialed flap 15, displayed 14

### Steps to reproduce

As described. 

### Expected behaviour

Display dial-flap degree

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by joon44** [comment]
It works when you select right below the indicator line. Like there would a small offset. For flaps 15, select 15.1. For flaps 20, select 20.1.

**Comment by TheFightingRaven** [comment]
already written up, will be fixed
