### ISSUE TITLE
10K Acceleration 

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#461]
### Describe the bug

After passing FL100, the AC accelerates to climb performance speed. VNAV picthes for +500 ft/pm, should probably we around +1000 during acceleration

### Steps to reproduce

Pass FL100 during VNAV-climb

### Expected behaviour

Would assume +1000 is more appropriate. Please double check with real world performance. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

DNMM

### Arrival

FGSL

### Cruise level

100

### ZFW

.

### CG

14.1

### Fuel

0

### Cost index

30

### Route

.

### Location

.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I've been told by a md11 pilot this is not the case
