### ISSUE TITLE
[BUG] - No CAWS

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#463]
### Describe the bug

Betty didn't join me for this flight: the CAWS was only audible for GPWS.

### Steps to reproduce

Unknown, install specific? 

### Expected behaviour

Migraine-inducing female voice bitching at you. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

A

### Arrival

A

### Cruise level

A

### ZFW

A

### CG

A

### Fuel

A

### Cost index

A

### Route

A

### Location

A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
no callouts whatsoever? It's not completely implemented, something you SHOULD have is: radio altimeter callouts

**Comment by GenericNerd** [comment]
Since the required information was not provided, we will not be accepting this report. Please refile with the information we request.
