### ISSUE TITLE
[BUG] - FMS related. Performance speeds resetting during flight

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#466]
### Describe the bug

Manually inputted cruise and descent speeds in the FMS reset during flight

### Steps to reproduce

Prior to departure I selected .80 for cruise and /300 kts for descent. Upon reaching cruise, performance values were reset to ECON. 

### Expected behaviour

Should maintain selected speeds during FMS Speed and VNAV

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

a

### Arrival

a

### Cruise level

370

### ZFW

0

### CG

14.1

### Fuel

0

### Cost index

30

### Route

0

### Location

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved
