### ISSUE TITLE
[TODO] - PAX Air Selector not available

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#469]
### Describe the bug

Unable to operate the pax amount selector on the overhead AIR system

### Steps to reproduce

Check overhead panel 

### Expected behaviour

Able to select number of passengers for the AIR system. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by PointBlank66** [comment]
I can confirm that the passenger counter on the overhead is non functional atm bc it is the missing clickspots, even tho the mouse icon is changing

**Comment by turbofandude** [comment]
Resolved in 0.54+
