### ISSUE TITLE
[TODO] - Parking brake indicator light not illuminating

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#470]
### Describe the bug

As per title 

### Steps to reproduce

Engage parking brake, light doesn't illuminate 

### Expected behaviour

Illumination 

### Evidence

0

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved in 0.46+
