### ISSUE TITLE
[BUG] - Ballast fuel in LBS while on KG

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#472]
### Describe the bug

The ballast fuel is displayed in LBS, while performing in KG. 

### Steps to reproduce

Load ac

### Expected behaviour

Seeing KG 

### Evidence

![FlightSimulator 2023-11-11 13-24-54](https://github.com/invernyx/md11-bugs/assets/134083402/a9b5439c-c832-4faf-8bb7-2765bc05bc4f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
