### ISSUE TITLE
[BUG] - MD11F torch clipping through wall

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#473]
### Describe the bug

Seems half of the torch is inside a black wall/texture

### Steps to reproduce

Load up F go inside the cabin by D1L & see the red torch 

### Expected behaviour

To be aligned properly on the wall 

### Evidence

![Screenshot_9](https://github.com/invernyx/md11-bugs/assets/70169249/6acd6bd4-3580-45d9-af76-860531cec22b)
![Screenshot_10](https://github.com/invernyx/md11-bugs/assets/70169249/00e8b70d-0b43-43ca-a2ab-d29a2d98a1c0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been resolved in the latest model update.
