### ISSUE TITLE
[TODO] - Minimums selector doesn't switch between RA and Baro

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#476]
### Describe the bug

Minimums selector doesn't switch between RA and Baro. Reset doesn't reset too 200 DH

### Steps to reproduce

Operate the minimums-knob(s)

### Expected behaviour

0

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

FL180

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@turbofandude I believe this is closed?

**Comment by joon44** [comment]
I concur. Minimums work as expected.

**Comment by pburnay-invernyx** [comment]
Resolved in 0.13+
