### ISSUE TITLE
[TODO] - Heading selector does not display on the ND

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#477]
### Describe the bug

When turning the heading select bug, there is no dotted white line moving over the ND to indicate the selected heading. 

### Steps to reproduce

0

### Expected behaviour

A dotted white line would be visible on the ND to indicate the selected heading, the line would turn solid white upon pulling the heading knob, switching to heading mode. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

a

### Arrival

a

### Cruise level

a

### ZFW

a

### CG

a

### Fuel

a

### Cost index

a

### Route

a

### Location

a

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
