### ISSUE TITLE
Texturing of the AIR panel at overhead panel is off

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#481]
### Describe the bug

See photo 

### Steps to reproduce

Look at packs 3 temp selector and ECON mode selector switches at overhead panel 

### Expected behaviour

0

### Evidence

![FlightSimulator 2023-11-11 14-03-01](https://github.com/invernyx/md11-bugs/assets/134083402/38627b06-4652-49f5-b9ea-5b9081b5c09e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
![FlightSimulator_2023_11_10_19_47_51_426](https://github.com/invernyx/md11-bugs/assets/148836830/dbfa6f3e-9da3-49d0-99fc-11676079fee4)
