### ISSUE TITLE
[BUG] - [  ] overlapping INSERT text when airways page becomes full

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#484]
### Describe the bug

[  ] overlapping INSERT text when airways page becomes full

### Steps to reproduce

Fill Airways page with airways. 

### Expected behaviour

[  ] should not overlap INSERT when page becomes full.

### Evidence

![Näyttökuva 2023-11-11 131708](https://github.com/invernyx/md11-bugs/assets/150369113/71dade5d-9e41-4447-8b7e-5cd56b666b9c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.13+
