### ISSUE TITLE
[BUG] - Failure at capturing an ILS using the letter identifier.

### ISSUE THREAD

**Issue by shinkicker444** [invernyx/md11-bugs#486]
### Describe the bug

Loaded ILS Y for 26L at Las Vegas using IRLE/259, approach mode failed to capture glide slope and localiser despite displaying the diamonds for them on the PFD.

### Steps to reproduce

After selecting the ILS approach on the RAD/NAV enter the ILS/CRS using the identifier rather then the frequency, when on approach activate Approach/Land.

### Expected behaviour

Activating the Approach/Land mode using the above method of frequency tuning (learnt this in the beta tutorial video from Father Time) it should capture the ILS as per a regular ILS.

### Evidence

Did not get a screenshot sorry.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Landing

### Heading

259

### Altitude

5000-1500ft

### Departure

KLGB

### Arrival

KLAS

### Cruise level

FL250

### ZFW

352,667 lbs

### CG

Unknown

### Fuel

34,480 lbs

### Cost index

120

### Route

KLGB/30 N0476F250 ZOOMM3 MISEN RNDRZ2 KLAS/26L
SID:  ZOOM3 via CAHIL
STAR: RNDRZ2 via MISEN
APPR: ILS Y 26L via BERBN

### Location

Near HUXAR or RELIN on final approach.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
unable to reproduce, did an autoland with the steps above
