### ISSUE TITLE
[BUG] - PFD visual inaccuracies

### ISSUE THREAD

**Issue by Octal450** [invernyx/md11-bugs#487]
### Describe the bug

The AI on the PFD is does not match the real plane, and other small alignment issues

### Steps to reproduce

Launch the plane and look at the PFD. The AI especially the pitch ladder is wrongly sized, similar to how it is on the later Honeywell LCD displays (717/MD-10), not how the earlier CRT's used on the MD-11 displayed it. You can also notice some text is not positioned correctly.

### Expected behaviour

The AI should be drawn according to the older MD-11 style

### Evidence
The pitch ladder text/lines are too wide:
![image](https://github.com/invernyx/md11-bugs/assets/25598604/460ea884-d2e1-42c0-b18f-8726ed558cfe)

Certain text objects are misaligned
![image](https://github.com/invernyx/md11-bugs/assets/25598604/d254d17c-cbb1-4069-9861-f955fd737e83)

Real:
![image](https://github.com/invernyx/md11-bugs/assets/25598604/d120a3d0-28e9-49ec-a1b6-88368db55dd7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The majority of these will be resolved in the next release.

**Comment by Octal450** [comment]
Awesome!
