### ISSUE TITLE
[BUG] - Frequency numbers missing

### ISSUE THREAD

**Issue by Urbanfox35** [invernyx/md11-bugs#488]
### Describe the bug

I don't use Vatsim atm, i use ProATC SR, I wasn't able to contact Manchester Radar on 118.770, due following frequency numbers being missing: .020, .045, .070, .095, this is all the same throughout the frequency cycle up to .995

### Steps to reproduce

on-going

### Expected behaviour

N/A

### Evidence

N/A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/138527559/8c781cf1-5251-4405-8204-2df0051bbc5a)
those frequencies don't exist, this is part of the 8.33 khz spacing atc should not be using these either
