### ISSUE TITLE
[BUG] - Poor texturing quality

### ISSUE THREAD

**Issue by mkonareff** [invernyx/md11-bugs#490]
### Describe the bug

Texturing quality could be improved a lot

### Steps to reproduce

Current issues:
- Unsmooth jagged fuselage/tail/engine panel lines and passenger windows
- Flat fuselage/tail/wing/engine panel lines and rivets
- Tail panel lines too much visible
These are visible on every liveries but especially noticable on white paints

- Poor external texture resolution (visible on small painted details)
- Very poor texture compression : they are compressed in the very old and bad quality DXT1 format which cannot contain alpha channel

### Expected behaviour

- Better overall quality
- Smoothened lines (depends on photoshop settings or program used for texturing)
- "3D feeling" added to panel lines and rivets with bevel and amboss effects
- Reduced opacity for some panel lines, using normal maps instead will bring a more realistic effects
- Higher resolution for better quality close up (would probably require an uv remapping)
- Less compression quality loss by using DXT5

### Evidence

![TFDi Jagged lines 1](https://github.com/invernyx/md11-bugs/assets/150543492/1eb38286-e93c-4891-9f0b-c0a8ac4e7d0a)
![TFDi Jagged lines 2](https://github.com/invernyx/md11-bugs/assets/150543492/d2dea554-e2ee-467e-bd3d-514347581e0d)
![TFDi Jagged lines 3](https://github.com/invernyx/md11-bugs/assets/150543492/0e70494e-6426-4e37-b4b2-fc58fb3063d0)
![TFDi Flat lines](https://github.com/invernyx/md11-bugs/assets/150543492/3d0fe6aa-32ba-44dd-95f2-8b15d74306f7)
![TFDi Panel lines opacity](https://github.com/invernyx/md11-bugs/assets/150543492/cda67105-7585-4913-afe1-cba63f28976e)
![TFDi low resolution](https://github.com/invernyx/md11-bugs/assets/150543492/124d7a65-e8d3-4a41-8fb0-dedafba71cf1)
![TFDi Compression](https://github.com/invernyx/md11-bugs/assets/150543492/e9aea639-74bc-443b-a7f8-cbf44dc7ca06)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by mkonareff** [comment]
An also: true for all liveries I have tested: panel lines and rivets color should merge with paint color. This is possible by using the "Multiply" setting on a photoshop layer as an example.

**Comment by EngineIgnition** [comment]
+1 The quality of the external model isn't up to par. I really hope this will be improved in future updates.

**Comment by ProfessorMadman** [comment]
+1.  Compared to the 717 release the MD-11 external texturing leaves a lot to be desired, especially with the PBR and hi fidelity capabilities of MSFS; TFDI you can do better!  Another suggestion would be to add decal mappings for smaller parts of the external model (static ports, cargo door texts, etc) so that they don't blur when getting up close.

**Comment by arwasairl** [comment]
The textures are already using DXT5. Various other things have been modified now, however, panel lines and small screws cannot be improved unless we use 8K texturesets, which is not as easy as changing the dropdown from 4K to 8K. Many liveries will have to be redone. Height maps are already being used to accomplish a 3D effect on panel lines.

**Comment by mkonareff** [comment]
> The textures are compressed via MSFS and not by us. We use 48-bit depth PNG and the simulator will convert it to DDS, so whatever DDS format it uses is not controlled by us. Various other things have been modified now, however, panel lines and small screws cannot be improved unless we use 8K texturesets, which is not as easy as changing the dropdown from 4K to 8K. Many liveries will have to be redone. Height maps are already being used to accomplish a 3D effect on panel lines.

Roger that for the MSFS compression. However I strongly disagree about panel lines and screws. I was not talking about resolution, there are many techniques to improve the look of these without changing the resolution. About the liveries... Well, may be completing the texturing before doing others would be the best idea?

**Comment by arwasairl** [comment]
Feedback has been noted and most if not all features requested have been implemented.
