### ISSUE TITLE
[IDEA] - External Model - Production Lifecycle Differences

### ISSUE THREAD

**Issue by ProfessorMadman** [invernyx/md11-bugs#491]
### Describe the bug

Ability to have multiple models with various configurations based on production changes in MD-11 production run

### Steps to reproduce

The MD-11 underwent a number of changes during production other than the PIP modifications.  All citations from link in "Evidence" section.

The main visual differences were:

- Long vs short exhaust spike on GE-CF6-80C2
- Enlarged aft cargo door
- Number 2 engine intake
- Flap fairing extension on outboard wings

**Long vs short exhaust spike on GE-CF6-80C2**

"First seen on PH-KCA, MD-11 #557
KLM’s MD-11’s introduced several new features on the MD-11. The first is the new exhaust spike. This only applies to those with GE engines, but is on every GE-powered MD-11 from this point on."

Short spike:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image072.jpg

Longer spike:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image074.jpg

**Later MD-11s had a larger aft cargo door that protruded into the wingbox fairing - this started with PH-KCA.**

Old smaller aft cargo door:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image076.jpg

New larger aft cargo door:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image078.jpg

**Number 2 engine intake**

"PH-KCE, MD-11 #575
Only one thing introduced here, but it’s an important one, and probably the least obvious/understood of all MD-11 changes. The new number 2 intake. Pics first, then explanation."

Old intake:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image080.jpg

New intake:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image082.jpg

Both intakes in one shot:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image088.jpg

**Flap fairing extension on outboard wings**

"HZ-ANA, MD-11 #609
This introduces the easiest to spot difference–new flap-track hinge fairings. All DC-10s, and all MD-11s up to this point have flap hinges like this:"

Old flap fairing:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image090.jpg

New flap fairing:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image092.jpg

Comparison between both:
https://airlinercafe.com/wp-content/uploads/2022/04/clip_image094.jpg

### Expected behaviour

External models cover all configuration options for MD-11s over the production lifespan.

### Evidence

https://airlinercafe.com/aviation-articles/ultimate-dc-10-md-11-guide-178410/

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the flap fairing is planned the others are not
