### ISSUE TITLE
[BUG] - APU AIR ELEC/ON message does not post (MD-ECS-21)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#493]
### Describe the bug

With APU running and APU GEN ON, when selecting APU AIR ON, no APU AIR/ELEC ON cyan alert posts

### Steps to reproduce

see descrip

### Expected behaviour

S/B with APU GEN and APU AIR ON, the cyan APU AIR/ALEC ON message posts

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by joon44** [comment]
We now get the APU AIR ON message. Is it supposed to post after engine start when the engines are providing electricity but the engine bleeds are off and APU is only providing bleed air?

![image](https://github.com/invernyx/md11-bugs/assets/102414406/95bf7fdf-b2f4-45e1-a0df-bded2f6bf498)

**Comment by turbofandude** [comment]
Resolved in 0.25+
