### ISSUE TITLE
[BUG] - APU shutdown timing (MD-APU-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#494]
### Describe the bug

The APU spools down immiedately following shut-down command on the ground

### Steps to reproduce

shut down APU, start timer

### Expected behaviour

S/B the APU continues to operate for 2 minutes after shut down command initiated

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This has been corrected in the next build :)

**Comment by FreakyD777** [comment]
Not fixed in V0.37. APU start to shut down immiedately after pushing START/STOP button.  Not fixed in V0.37
