### ISSUE TITLE
[BUG] - Annunciater test switch, abnormal conditions (MD-LIGHTS-9)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#498]
### Describe the bug

With BAT ON, EXT and APU PWR OFF, EMER PWR set to ON, all OVRHD lights illuminate when depressing the annunciator light test switch

### Steps to reproduce

see descrip

### Expected behaviour

S/B the following illuminate only in this non-normal power configuration: All cargo fire switches, IRU NAV OFF, GEN BUS FAULT reset, GALLEY BUS OFF, all ignition control switches, ENG 2 AGT 1 and AGT LOW; all ELEC panel switches, CABIN SMOKE AIR switchlight (frieghter only); PA IN USE switch, APU CONTROL panel switches, LSAS LEFT INBD OFF, CABIN PRESS MANUAL; all 7 SD cue switches, CALL and MECH lights on captain's audio panel

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed
