### ISSUE TITLE
[BUG] - Center gear clipping

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#5]
### Describe the bug

The center gear clips into the ground

### Steps to reproduce

1. Go to the exterior camera while the centre camera is down

### Expected behaviour

The center gear should remain firm on the ground

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by nIn9R** [comment]
confirming occuring for me on CE release on cargo variant only.

**Comment by TheFightingRaven** [comment]
fixed in coming artwork update
