### ISSUE TITLE
[BUG] - 2 Cargo Decks MD-11F

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#500]
### Describe the bug

2 Cargo Decks MD-11F

### Steps to reproduce

Load up any freighter livery. Use Drone Camera to go just ahead of the rear cargo window (at the end of the wing) and pan sidewards. Panning from outside first the more basic interior is visible. Somewhere closer to the middle of the compartment the more detailed interior appear.

### Expected behaviour

You should only see the more detailed interior. 

### Evidence

https://github.com/invernyx/md11-bugs/assets/150608109/a4cf4e62-92e1-4ef7-9138-798611fb6c6f

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
needs title

**Comment by arwasairl** [comment]
This bug will not be fixed in order to keep feature parity with P3D.

**Comment by alxcpt** [comment]
Just like the pax version #700 the basic textures for the cargo deck should be visible from the outside, the more detailed deck should be visible only from the inside or near the main cargo door. However the transition between those two isn't made well right now. If you are only able to see the details interior if you are droning in the middle of the cargo deck, you could just implement the basic decks, saves some polygons. Also in P3D you aren't even able to move the camera as free as in MSFS.
