### ISSUE TITLE
[BUG] - Altitide/Speed Constraints Not Visible on ND Next To Points

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#504]
### Describe the bug

Constrained altitudes and speeds on a STAR are not displaying below the associated point on the ND

### Steps to reproduce

Load a STAR with speed and/or altitude constraints
Constraints are correctly accounted for in FMS
Observe points on ND, only point name is displayed.

### Expected behaviour

Waypoints with speed and/or altitude constraints in large font should have those displayed appropriately below the waypoint name on the ND.

In example photo below (KMCO GRNCH5 arrival), GTRNG should display as follows:

GTRNG
-17000
290KT

### Evidence

![STAR](https://github.com/invernyx/md11-bugs/assets/123108304/b7aeef74-ccb6-45f5-8ed7-dfdd25eace29)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@turbofandude I believe this issue has been resolved?

**Comment by turbofandude** [comment]
This is now resolved
