### ISSUE TITLE
[BUG] - ATS Does Not Retard To Idle at 50 Feet

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#506]
### Describe the bug

During approach, ATS does not retard to idle and continues to attempt to maintain vApp throughout rollout.

### Steps to reproduce

Fly approach with ATS on.
At 50 feet and throughout touchdown, ATS appears to attempt to maintain vApp

### Expected behaviour

At 50 feet, ATS should retard to idle (regardless of external conditions).

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Landing

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

50ft prior to touchdown during approach to any runway

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
additionally it tries to gain speed back after touchdown

**Comment by turbofandude** [comment]
This was caused by the RETARD mode logic happening too early and being overwritten by later logic. Code to prevent such reversion has been added and RETARD should work properly in 0.12+.
