### ISSUE TITLE
[BUG] - airway to waypoint doesn’t work

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#508]
### Describe the bug

When you go to a waypoint -> airway page and fill your airway in there and thereafter the waypoint it doesnt want to implement the waypoint bcs it says “not in database” but instead of filling the waypoint after the airway but as a direct from the prev waypoint it works? So the database isnt working correctly 

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

0

### Departure

EHAM

### Arrival

TNCM

### Cruise level

370

### ZFW

0

### CG

0

### Fuel

0

### Cost index

100

### Route

-

### Location

EHAM

### Agreement

- [X] Yes

**Comment by 017941** [comment]
Yes, I have had this occur many times. However, it seems to occur EVERY time there are multiple airway points to choose from. Ex. J174 selected with a lateral revision, but when you type in TCH there are several TCH points, including two TCH of the same LAT/LONG. I have never had it accept the airway "to" point in this case. Overall, the program seems to have extensive NAV data base issues, that are likely causing difficulties with PROF, CAT III, Manual FMS loading etc. At times the aircraft location is not accurate. I have flown several perfect CAT III landings 1000 feet short of the runway threshold.

**Comment by wagoozen1** [comment]
I tested this today after the fixes applied to this logic. It seems to work better but got the same issue when the following route:
EHAM/24 BERGI2S BERGI L602 NALAX L46 ODNEK N110 ERKIT
L602 TLA DCT ETILO NATB IRLOK N580A YBC DCT POLTY IMEBA9 CYYZ/23

The second L602 -> TLA is not in database
