### ISSUE TITLE
[BUG] - Cockpit entirely frozen

### ISSUE THREAD

**Issue by Fauzy125** [invernyx/md11-bugs#509]
### Describe the bug

I was departing Memphis for Toronto, as i was on the climb out i wanted to setup my arrival into Toronto, clicked on the button for CYYZ on the FMS and everything in the cockpit froze.  My flight is continuing and sim has not crashed, and i am not paussed.

### Steps to reproduce

This is my route:

KMEM/09 N0473F370 GENEH7 NUYID DCT MYS DCT RID DCT JECKA DCT QWERI NUBER6 CYYZ/05

On the departure, all was normal, climbing out, at around 20000ft, i decided to enter the arrival info for YYZ and everything in the cockpit froze.  I cannot click or do anything.  My sim has not crashed, the plane is still moving and flying to Toronto, but everything is frozen, i cannot click a switch or push any buttons.  Looking out the windows i can see i am still moving

### Expected behaviour

Allow me to select my SID and runway for arrival into YYZ

### Evidence

https://github.com/invernyx/md11-bugs/assets/150632755/71622114-5ee6-4c16-9332-7355cb518e7a

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
WASM crash

**Comment by pierrewanga** [comment]
[MSFS]
Same thing happened to me but on approach.
Flying from MHTG to MKJS, was on descent and I entered a waypoint into the FMS and everything froze.

My route: MHTG/02 BTO1 BTO DCT CORAL DCT BIRLO UZ894 PESTO UL349 GADIM DCT
LENAR LENAR7 MKJS/07.

Sim didn't crash, aircraft keeps flying but just everything in the cockpit is frozen.

**Comment by turbofandude** [comment]
This has likely been fixed with other improvements. Please re-open if needed.
