### ISSUE TITLE
[BUG] - Main Gear Textures

### ISSUE THREAD

**Issue by robcarlyh** [invernyx/md11-bugs#511]
### Describe the bug

Incorrect textures

### Steps to reproduce

The current CE model does not have MD11 gear textures. It has the DC10 gear. Please see below pics for reference 

### Expected behaviour

Incorrect textures 

### Evidence

![McDonnell_Douglas_MD-11(F),_Ethiopian_Airlines_Cargo_AN1526947](https://github.com/invernyx/md11-bugs/assets/150735875/8d6bc15d-84fa-4ed2-a406-c3e505571d57) - MD11 Gear

![MSFS_2023-11-13-153905_Belgium-Flemish_Brabant-Halle-Vilvoorde-Steenokkerzeel-Melsbroek](https://github.com/invernyx/md11-bugs/assets/150735875/01e7aeee-6a9d-4e70-833b-6f5661e15f67) - CE edition gear in the sim

![7658106526_e80c0a60dd_b](https://github.com/invernyx/md11-bugs/assets/150735875/82ee4e40-b74d-4df3-9b44-5096d2e7b931) - DC10 gear 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been fixed in the latest texture update.
