### ISSUE TITLE
[BUG] - Rudder axis does not work with buttons

### ISSUE THREAD

**Issue by franliner** [invernyx/md11-bugs#512]
### Describe the bug

When I move the rudder with joystick or keyboard buttons, the rudder moves to the right and stays there

### Steps to reproduce

1. Assign "Rudder Axis Right" and "Rudder Axis Left" and/or  "Rudder Right (Yaw right) and "Rudder Left (Yaw Left)" to a keyboard button or joystick button
2. Load aircraft
3. Move the rudder with the keys

### Expected behaviour

The rudder should move and return to its initial position, And it should move in both directions, not stay stuck to the right.

### Evidence

![MD11 (3)](https://github.com/invernyx/md11-bugs/assets/150391624/e4fd50cb-f83d-4dec-8441-53e68d8df24f)
![MD11 (2)](https://github.com/invernyx/md11-bugs/assets/150391624/c7e4345d-585b-4bf3-b533-e566c02a22ca)
![MD11 (1)](https://github.com/invernyx/md11-bugs/assets/150391624/58ac18cb-253b-4a26-bc12-2a08a9375340)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by StevenSilvaB767** [comment]
Have you managed to fix this error?
