### ISSUE TITLE
[BUG] - APU air inflight

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#513]
### Describe the bug

No use ENG AIR display with APU AIR on inflight

### Steps to reproduce

APU Air is avaible inflight while it shoudn't

### Expected behaviour

"USE ENG AIR" Illuminates amber when the APU air switch is on and cabin differential pressure is more than 1.3 psi.

### Evidence

FCOM III APU 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

5000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.25+
