### ISSUE TITLE
[BUG] - ISOL valves logic

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#515]
### Describe the bug

ISOL valves open during incorrect phase of flight

### Steps to reproduce

Turn environmental system Controller in manual: ISOL are commanded open
With environmental System in Auto: ISOL remain open

### Expected behaviour

ISOL valves should remain closed while switching ESC to manual

in auto mode ISOL valves never interconnect two or more active engine pneumatic supply systems. 
With one or more engine bleed off or APU operation, the ESC will open the 1-2 ISOL valve and/or 1-3 ISOL valve but will not allow interconnection to an pneumatic system where engine bleed is already operative 

### Evidence

FCOM VOL III:

A Pressure Regulator Valve (PRV) on each engine pneumatic system controls 
bleed air from that engine. With engines running, only one bleed system may feed 
a single pneumatic manifold.
The ESC normally keeps all pneumatic systems isolated. However, when one or 
more systems are tied together, the PSC closes the high stage valve. If the ESC is 
also in auto, the PRV closes to prevent reverse flow.
With pneumatic supply from the APU or from a ground external source, the ESC 
opens the isolation valves to allow pressure into all three manifolds.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

0-18000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should have long been resolved.
