### ISSUE TITLE
[BUG] - Fuel system indication (MD-FUEL-6)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#518]
### Describe the bug

In manual fuel mode, when commanding tanks 1/2/3 pumps to OFF, no EICAS messages post

### Steps to reproduce

see descrip

### Expected behaviour

S/B TANK 1/2/3 PUMPS OFF in amber posts

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+

**Comment by FreakyD777** [comment]
verified 0.37
