### ISSUE TITLE
[BUG] - Cloud haze entering flight deck (MD-GEN-6) (and snow too)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#520]
### Describe the bug

When flying through certain types of clouds, the cloud "fog" enters the flight deck (gray haze visible).  This doesn't happen 100% of the time

### Steps to reproduce

Fly through various cloud types

### Expected behaviour

S/B no fog inside airplane when flying in clouds

### Evidence

N/A

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
EDIT 11/22/23 - Snow was also seen flying through the flight deck.

**Comment by jhattermann** [comment]
Added environment occluder around the interior model, this may have also been mentioned in another bug report
