### ISSUE TITLE
[BUG] - Speed protection when extending gear in flight (MD-AFS-9)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#522]
### Describe the bug

Extending gear at 260KIAS FL250 (GW350k lb), the AFS and ATS go into speed protection, pitching the airplane up and decreasing throttle.  This happens at speeds as low as 232KIAS.  Also happened at 15k ft

### Steps to reproduce

Set speed 260KIAS
Extend gear
Observe AFS and ATS kick into speed protect mode by decreasing throttle and raising nose

### Expected behaviour

S/B able to extend gear up to 260KIAS/M0.7 with out speed protection engaging

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

Various

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
