### ISSUE TITLE
[BUG] - Flap blow-down not operational (MD-FC-16)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#523]
### Describe the bug

While accelerating past flap retract speed with F50, the flaps do not auto retract from 50 to 35

### Steps to reproduce

Set F50, speed as required
Accelerate to above F50 max speed
Observe F50 setting remain

### Expected behaviour

S/B flap blow down occurs at approximately 180KIAS with F50

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

Various

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in V0.42.01

**Comment by GenericNerd** [comment]
This will be resolved in the next version

**Comment by FreakyD777** [comment]
Not acting correctly in V0.56

**Comment by GenericNerd** [comment]
This is fixed
