### ISSUE TITLE
[BUG] - Secondary flight control modes not operational (MD-FC-17)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#524]
### Describe the bug

Secondary flight control modes (FLAP LIMIT, ELEV FEEL, YAW DAMP OFF, LSAS OFF) do not function

### Steps to reproduce

see descrip

### Expected behaviour

S/B functional via flight control panel on overhead.  Probably haven't gotten around to modeling this yet, but just thought I'd add this in for record keeping.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

Various

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in V0.42.01

**Comment by GenericNerd** [comment]
This will be resolved in the next version
