### ISSUE TITLE
[BUG] - Auto seat belt logic (MD-AV-8)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#527]
### Describe the bug

With the seat belt switch set to auto and While descending thru 15k ft, seat belts message does not post

### Steps to reproduce

Set seat belt switch to AUTO
Descent thru 15k ft

### Expected behaviour

S/B SEAT BELTS in cyan posts with seat belt switch in auto abd descending thru 15k ft

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

15,000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Although I certainly trust your background, I found directly conflicting information in the FCOM: 
![image](https://github.com/invernyx/md11-bugs/assets/3858710/568a8861-48b4-46d1-a4a3-84aff1892e47)

What do you think?

**Comment by FreakyD777** [comment]
OK, I see what's happening.  The logic you provide above is correct.  However, there was an optional AUTO SEAT BELT SIGN function that airlines could order on PAX airplanes.  So maybe this is something you can add in the future as an EFB option?

**Comment by turbofandude** [comment]
@GenericNerd can I get a new EFB option, please? This seems like a cool little detail to add.

**Comment by turbofandude** [comment]
Will be implemented as a setting in 0.25+
