### ISSUE TITLE
[BUG] - MD-11F UPS

### ISSUE THREAD

**Issue by Juanandonly1** [invernyx/md11-bugs#529]
### Describe the bug

Md-11F UPS Livery 

### Steps to reproduce

Looking at current MD-1F  in Sim with UPS Livery
![74985_1476809306](https://github.com/invernyx/md11-bugs/assets/150832144/b34498bd-4b1b-4d4c-a795-cfad7c81f31a)

### Expected behaviour

Current Day MD-11's With the model interior after the LUFT birds are N261UP-N265UP, tail number on current livery is wrong to match this (although 260 is still a GE tail), Also the Modern UPS planes only say Worldwide services, WE no longer have "Synchronizing the world of commerce" on our planes.

### Evidence

![99043_1604756116](https://github.com/invernyx/md11-bugs/assets/150832144/5a4af49a-66b2-4c94-a8e8-d441284a1f56)
![90968_1537818118](https://github.com/invernyx/md11-bugs/assets/150832144/15bed552-dd64-4bce-9f13-fb816adcec69)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The current livery, although from a different era, is not "incorrect". There will be a paintkit that will allow more liveries to be developed.
