### ISSUE TITLE
[BUG] - CVR Buttons Not mapped

### ISSUE THREAD

**Issue by turbofandude** [invernyx/md11-bugs#532]
### Describe the bug

The CVR controls and lights are not mapped

### Steps to reproduce

Observe controls

### Expected behaviour

They should be mapped

### Evidence

Visual inspection in sim

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Buttons tagged
