### ISSUE TITLE
[BUG] - Fuel burn too low

### ISSUE THREAD

**Issue by turbofandude** [invernyx/md11-bugs#533]
### Describe the bug

Fuel burn too low

### Steps to reproduce

Fuel burn is currently too low as it was tuned while bug #266 was a factor.

### Expected behaviour

Fuel burn should match real aircraft

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by microlight2010** [comment]
Fixed.
