### ISSUE TITLE
Autopilot conflict with x-56 stick

### ISSUE THREAD

**Issue by elf8324** [invernyx/md11-bugs#535]
### Describe the bug

When press Autoflight airplane's yoke start shaking which makes autopilot disconect. Autopilot too sensetive to x-56 input fluctuation

### Steps to reproduce

During flight press Autoflight button

### Expected behaviour

When press Autoflight airplane's yoke start shaking which makes autopilot disconect. Autopilot too sensetive to x-56 input fluctuation

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Takeoff

### Departure

any

### Arrival

any

### Cruise level

any

### ZFW

any

### CG

any

### Fuel

any

### Cost index

any

### Route

any

### Location

any

### Agreement

- [X] Yes

**Comment by wagoozen1** [comment]
I got this with the X-55 to, i add dead zone but thats not enough. It might be the case this is caused due ghost inputs.

**Comment by kdries** [comment]
I have the X56 and don't have this issue

**Comment by TheFightingRaven** [comment]
we are probably going to add a feature to prevent hardware inputs overriding the autopilot

**Comment by wagoozen1** [comment]
That would be an awesome option then, i haven't made any flight because of
this issue.
Still I am not sure what is causing this. If you want me to perform some
tests let me know

Andres van Goozen

Op wo 15 nov 2023 om 22:24 schreef TheFightingRaven <
***@***.***>:

**Comment by elf8324** [comment]
Thank you! It will help a lot

**Comment by TheFightingRaven** [comment]
fixed with hardware override
