### ISSUE TITLE
[BUG] - REPLACE ME

### ISSUE THREAD

**Issue by elf8324** [invernyx/md11-bugs#536]
### Describe the bug

Autopilot Knobs: Speed, Heading, Altitude can't be pushed or pulled  

### Steps to reproduce

Autopilot Knobs: Speed, Heading, Altitude can't be pushed or pulled

### Expected behaviour

Autopilot Knobs: Speed, Heading, Altitude can't be pushed or pulled

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
what are you trying to tell me?

**Comment by elf8324** [comment]
I can't pull or push those knobs as result can't command speed, heading, altitude to autopilot. Another issue transponder button "1" doesn't work.

**Comment by TheFightingRaven** [comment]
you need to left click and move the mouse in or out to push it in or pull out

**Comment by TheFightingRaven** [comment]
insufficient information provided
