### ISSUE TITLE
[BUG] - Installer will not install to Community Folder

### ISSUE THREAD

**Issue by avmetroman** [invernyx/md11-bugs#537]
### Describe the bug

When trying to install directly into the MSFS Community Folder an error is encounted.

### Steps to reproduce

1. Download the installer
2. Run installer as admin, when prompted select C:\Users\{username}\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community as the install folder.
3. After some time an error is encountered See screenshot. 
![tfdi_install_fail2](https://github.com/invernyx/md11-bugs/assets/19178971/71ae8901-355f-4b54-98b9-5a4942f8e6f8)
![tfdi_install_fail](https://github.com/invernyx/md11-bugs/assets/19178971/4f12a64d-685d-47d5-bfad-415d3b63dda7)

### Expected behaviour

Should be able to install the the MSFS community folder with no issues.

### Evidence

see Screenshot attached

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
We are replacing the installer as of 0.13+ and this will be implicitly resolved.
