### ISSUE TITLE
[BUG] - MAX LW 195.0 message

### ISSUE THREAD

**Issue by wagoozen1** [invernyx/md11-bugs#542]
### Describe the bug

LW is not calculated correctly

### Steps to reproduce

Focus in this case is the LW

On WEIGHT INIT 2/3
- BLOCK: 48.1 (see number 1 on OFP)
- TOGW: 212.8 (See number 2 on OFP)
- ZFW: 164.9 (165.6 is expected see number 3 on OFP/however bug is about LW)
- LW: 213 (171.7 is expected see number 4 on OFP).

Scenario 2:
Start with ZFW then with Block this gives very stange numbers.

### Expected behaviour

BLOCK: 48.1
TOGW: 212.8
ZFW: 165.6
LW: 171.7

### Evidence

Scenario 1:
![2023-11-15 11_15_07-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/a3c5ef78-a367-4b4b-bd94-24dd1a129997)
![2023-11-15 11_15_39-CYULEHAM_PDF_1700042756 pdf and 8 more pages - Personal - Microsoft​ Edge](https://github.com/invernyx/md11-bugs/assets/114499693/21c0eb18-5b0f-40c6-97a3-ccf3adb87b7f)

Scenario 2:
![2023-11-15 11_20_36-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/160ade4f-fc22-4eec-95c1-dfbac1d0a92e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

CYUL

### Arrival

EHAM

### Cruise level

FL000

### ZFW

171.7

### CG

n.a

### Fuel

48.1

### Cost index

100

### Route

CYUL/24L DCT ANTEG DCT OBRON DCT MOBUB DCT EBMOS DCT YQB
DCT CEFOU N333B ELSIR DCT 50N050W 52N040W 53N030W 54N020W DCT DOGAL
DCT BEXET DCT INKUR DCT LIFFY UL975 WAL M16 DOLAS L603 LAMSO LAMSO2A
EHAM/18C

### Location

CYUL

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should not happen anymore
