### ISSUE TITLE
[BUG] - Installer not behaving as it should

### ISSUE THREAD

**Issue by Masuli97** [invernyx/md11-bugs#543]
### Describe the bug

Won't let erase or add any credentials

### Steps to reproduce

Ran installer. After accepting ToS it lead into customer information page. It has already autofilled my Windows e-mail address as User Name (which btw I don't use). It won't let me to erase e-mail address or add anything in to other fields (organization, serial)

### Expected behaviour

To work obviously. Only way I could get around this issue is to run installer in Windows 8 compatibility mode. Thing is though, it works only with full installer. If I knew where updater downloads updated installer, then I could use this workaround. From general perspective, this type of installer which I've seen before to be used by other developers, is total trash and no saint person should never use it (you know, we have a lot more normal and idiot proof installers available as well). For now I can't update my TFDi MD11 until it gets resolved/get to know where downloads via updater end up to. Tried to dig some files if they help you

+ Admin rights didn't solve issue

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/73132122/2bb1bc7b-3bf7-49fb-b44e-8d95f6b3f607)
[cv_debug.log](https://github.com/invernyx/md11-bugs/files/13363471/cv_debug.log)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
we are replacing the installer soon(tm)
