### ISSUE TITLE
[BUG] - Mode C doesn't work through vPilot anymore

### ISSUE THREAD

**Issue by AronBjarki00** [invernyx/md11-bugs#544]
### Describe the bug

before the latest update you could use vPilot to put mode Charlie on the transponder but with the latest update that isn't possible anymore so that makes the MD-11 non flyable on Vatsim

### Steps to reproduce

connect up to vatsim through vPilot and click mode C on the vPilot client, I've tried messing with the planes transponder as well but that doesn't change anything.

### Expected behaviour

clicking the vPilot mode C button should put the transponder in mode C mode.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Sam-Yeager** [comment]
I can verify this. It doesnt work for me either.

**Comment by joon44** [comment]
For me neither. Pressing MODE C from vPilot, it flashes and is forced off.

**Comment by CptUnicorn** [comment]
Can confirm. Even pushing Mode C in the client will not work. Flights on VATSIM not recommended.
