### ISSUE TITLE
[BUG] - Massive Pitch-Up After Takeoff

### ISSUE THREAD

**Issue by Sam-Yeager** [invernyx/md11-bugs#545]
### Describe the bug

After takeoff and activating the vertical PROF the aircraft will pitch up to 35 degrees or more. It almost causes a stall.

### Steps to reproduce

Takeoff then activate autopilot and then vertical PROF.

### Expected behaviour

Im expecting it to climb without going almost straight up.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Pitch

35 degrees (or more) up

### Departure

KALT

### Arrival

KMIA

### Cruise level

FL400

### ZFW

61.2

### CG

24

### Fuel

12.2

### Cost index

82

### Route

N/A

### Location

Just left ATL from 8R

### Agreement

- [X] Yes

**Comment by joon44** [comment]
The FD is commanding ridiculously high pitch angle after takeoff.

**Comment by TheFightingRaven** [comment]
this is surpass it's speed target (magenta dot) this might not be an actual bug but a symptom of the unfinished flightmodel
