### ISSUE TITLE
[BUG] - efb states do not save

### ISSUE THREAD

**Issue by AlexXx88** [invernyx/md11-bugs#546]
### Is your feature request related to a problem? Please describe.

hi, preferences in efb does not save for next flight, example i have choose electronic standby instruments and on restart i see on cockpit analogic ones with on tablet green evidence on electronic one.

### Describe the solution you'd like

hi, preferences in efb does not save for next flight, sxample i have choose electronic standby instruments and on restart i see on cockpit analogic ones with on tablet green evidence on 

### Describe alternatives you've considered

see electronic one on cockpiy

### Additional context

![image](https://github.com/invernyx/md11-bugs/assets/104494440/12ef1507-2a29-4ed2-b39b-943d8b34e27a)

**Comment by turbofandude** [comment]
Resolved in 0.13+
