### ISSUE TITLE
[BUG] - Flaps 28 Takeoff

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#548]
### Describe the bug

MCDU says Entry out of range for flaps 28 takeoff

### Steps to reproduce

enter 28 on TO page for flaps setting

### Expected behaviour

Flaps 28 should be avaible for takeoff

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

SEQU

### Arrival

SEQU

### Cruise level

180

### ZFW

155t

### CG

24

### Fuel

40t

### Cost index

0

### Route

DCT

### Location

Preflight

### Agreement

- [X] Yes

**Comment by Willmus11** [comment]
Update: I just realized that the MD11 simulated is a non deflected ailerons version, so max flaps setting is indeed 25
28 is with DEF Ailerons only

**Comment by TheFightingRaven** [comment]
deflected ailerons will be added as an option

**Comment by turbofandude** [comment]
Resolved as of 0.47+
