### ISSUE TITLE
[BUG] - Removing MD11 through installer doesn't remove all files

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#549]
### Describe the bug

Running the installer available on the Client Area to uninstall the MD-11 does not remove all installed files. \tfdidesign-aircraft-md11\Data\Primary remains with files cycle.json, cycle_info.txt and folder ProcedureLegs (and its files).

### Steps to reproduce

Run the installer and select the remove option.

### Expected behaviour

All installed files are removed.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/6001596/7aa2c779-8737-48db-bee6-cfcb3259f253)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the installer will be completely replaced, additionally, these are navigraph files
