### ISSUE TITLE
[BUG] - Incorrect package_version in manifest.json

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#550]
### Describe the bug

package_version in manifest.json is not updated and still shows 0.1.0

### Steps to reproduce

Open manifest.json in tfdidesign-aircraft-md11, check package_version value

### Expected behaviour

package_version is corectly updated wich each new build

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/6001596/89c65f3a-cda1-4845-aed3-1c0e5206ff90)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the installer is being replaced, this bug should not persist after this
