### ISSUE TITLE
[BUG] - AIR panel backlighting not working

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#553]
### Describe the bug

backlighting on the fuel panel on the overhead does not work.

### Expected behaviour

When turning on the overhead panel backlighting, the AIR panel section does not light up

### Evidence

https://imgur.com/9sjLNI2

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by MikeA34** [comment]
Looks like AIR panel to me. But I can confirm this happens in my MD-11F. Additionally AUX FUEL panel lights not working. My picture is from -11F.
![Näyttökuva 2023-11-15 220441](https://github.com/invernyx/md11-bugs/assets/150369113/04b1b273-4ce4-441a-b5cb-1efaaca5c1d5)

**Comment by CptUnicorn** [comment]
> Looks like AIR panel to me. But I can confirm this happens in my MD-11F. Additionally AUX FUEL panel lights not working. My picture is from -11F. ![Näyttökuva 2023-11-15 220441](https://user-images.githubusercontent.com/150369113/283243652-04b1b273-4ce4-441a-b5cb-1efaaca5c1d5.png)

My mistake. I meant to put AIR panel. I'll make the appropriate edits to the post.

**Comment by CptUnicorn** [comment]
The EVAC panel also has no backlighting.
https://imgur.com/OCfNW3N
