### ISSUE TITLE
Spoilers not deploying when armed after main landing gear touch down 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#556]
### Describe the bug

Spoilers not deploying when armed after main landing gear touch down only when nose landing gear is down 

### Steps to reproduce

Land with the spoilers armed

### Expected behaviour

When the spoilers are armed the spoilers and lever should deploy to the full flight detend position on main landing gear touch down and then to the ground detend on nose gear contact.

### Evidence

https://youtu.be/agxUSVQMISw?si=mivoAValBG4ThURA&t=153 
https://youtu.be/dbXoFFBxglY?si=KcXi5s1q1YvPHYpm&t=8015

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.13+
