### ISSUE TITLE
[BUG] -Navdata Interpolation Problem

### ISSUE THREAD

**Issue by Masher76** [invernyx/md11-bugs#558]
### Describe the bug

Space inbetween 2 waypoints goes off out of range

### Steps to reproduce

Flight Plan- KTPA/19R GANDY8 SABEE FROGZ4 KMIA/09
Bug between ASPPN and PBJAY on the FROGZ4 STAR. Any entry into this space leads to multiple turns and a point way off to the east. 

### Expected behaviour

Correct waypoint logic between ASPPN and PBJAY as demonstrated in the Fenix A320 screenshots. 

### Evidence

<img width="831" alt="1" src="https://github.com/invernyx/md11-bugs/assets/76084648/018e907f-b2e4-44e3-9f4e-264536124355">
<img width="799" alt="2" src="https://github.com/invernyx/md11-bugs/assets/76084648/30d56a55-9918-4064-acce-8f537136e3d1">
<img width="446" alt="3" src="https://github.com/invernyx/md11-bugs/assets/76084648/3a82f257-b556-41ad-a721-e8e67720791d">
<img width="299" alt="Fenix1" src="https://github.com/invernyx/md11-bugs/assets/76084648/9533750a-a993-4525-a1ac-60a452be7149">
<img width="742" alt="Fenix2" src="https://github.com/invernyx/md11-bugs/assets/76084648/f804cbde-5110-4a69-8c5c-32296ac0ecba">
[KTPAKMIA_PDF_1700070903.pdf](https://github.com/invernyx/md11-bugs/files/13368894/KTPAKMIA_PDF_1700070903.pdf)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

KTPA

### Arrival

KMIA

### Cruise level

290

### ZFW

418.2

### CG

27

### Fuel

37200

### Cost index

135

### Route

 KTPA/19R GANDY8 SABEE FROGZ4 KMIA/09

### Location

KTPA Cargo Dock 54 using Vertical Sim scenery. Same location used with MD11F and A320

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.30+
