### ISSUE TITLE
[BUG] - Cannot reinstall Navigraph data after updating the plane

### ISSUE THREAD

**Issue by simplequark** [invernyx/md11-bugs#559]
### Describe the bug

After installing the latest version of the MD-11, the Navigraph Hub app shows a green “Update” button for the navdata. When I press it, the Navigraph Hub hangs and needs to be force quit. 

### Steps to reproduce

1. Install first alpha of the MD-11
2. Install Navigraph data
3. Update MD-11
4. Try to reinstall Navigraph data

### Expected behaviour

The update should install. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
The misfunctioning of the navigraph hub is not our bug, take it up with navigraph
