### ISSUE TITLE
[BUG] - Missing lightbulbs for nav and high intensity lights

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#561]
### Describe the bug

Light bulbs are missing for nav and high intensity lights

### Expected behaviour

Look from the outside at the nav and high intensity lights, bulbs are missing

### Evidence

Screenshots from right wing, same behaviour on left wing:
![1250410_20231115214429_1](https://github.com/invernyx/md11-bugs/assets/6001596/d9d596ae-015c-45bb-a153-3ec734da88c2)
![1250410_20231115214436_1](https://github.com/invernyx/md11-bugs/assets/6001596/a9d3409b-815a-4fb2-a1f2-60a9b33424e7)
![1250410_20231115214525_1](https://github.com/invernyx/md11-bugs/assets/6001596/04f3f576-1d02-4e60-abd1-d98c9e46c9e6)

Reference:
![image](https://github.com/invernyx/md11-bugs/assets/6001596/6a2dc214-ce63-4968-97c3-3bd811848f69)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been added in the latest model update.
