### ISSUE TITLE
[BUG] - Standby analog instruments became black

### ISSUE THREAD

**Issue by Stationair** [invernyx/md11-bugs#562]
### Describe the bug

Standby analog instruments became black squares after using slew mode and selecting "ready to fly" state

### Expected behaviour

Standby instruments visible

### Evidence

![screenshot](https://github.com/invernyx/md11-bugs/assets/150976371/2aafcd32-92c5-4eff-a5ad-002c0d3e272e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is a symptom of bug #546 and therefor duplicate
