### ISSUE TITLE
[BUG] - RNAV magenta line issues

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#564]
### Describe the bug

Magenta line not tracking the waypoints and creates its own flight path

### Expected behaviour

I found the JTEEE5 RNAV SID out of Memphis runway 18C ODALE transition to have some issues with the magenta line not lining up with waypoints. The RNAV STAR KERAX4A for the 25s at Frankfurt Main had some serious issues tracking the waypoints. Not sure if this would fall under Autoflight.

### Evidence

https://imgur.com/bzu2WpJ

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed as of 0.30+
