### ISSUE TITLE
[BUG] - Lazy Localizer

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#566]
### Describe the bug

Aircraft will lazily drift off the localizer and will not correct

### Steps to reproduce

Set up a standard ILS, (there does appear to be a bug with it trying to fly the LOC right after you engage APPR/LAND).

### Expected behaviour

As you join the localizer, the aircraft will lazily drift off to the left (in my case) and make No attempt to correct the divation.

### Evidence

https://imgur.com/0yHXkmR
https://imgur.com/vxeDnIP

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

EFHK

### Arrival

EDDF

### Cruise level

FL320

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

200

### Route

N/A

### Location

Frankfurt Main ILSZ runway 25R DF425 Transition from the KERAX4A STAR
Guangzhou ILSZ 02R GG408 Transition from the IGONO2A STAR

### Agreement

- [X] Yes

**Comment by JimmyKudo1015** [comment]
me tooooooooooo

**Comment by mclovin90** [comment]
Still an issue in Alpha .22

**Comment by turbofandude** [comment]
Should long be resolved
