### ISSUE TITLE
[BUG] translucent Radio Volume knobs

### ISSUE THREAD

**Issue by PointBlank66** [invernyx/md11-bugs#568]
### Describe the bug

Radio Volume knobs seem to be missing the right textures and thus making them translucent

### Expected behaviour

Having the right textures applied so that they aren't translucent

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/4239471/58e0fc5f-e397-4834-b713-9d4ecf5a46cf)
![image](https://github.com/invernyx/md11-bugs/assets/4239471/6a685e86-5fb1-454f-99d3-d557ff70ee06)
![image](https://github.com/invernyx/md11-bugs/assets/4239471/b088b2b6-97ee-49e2-ba9c-73cdf0dad62b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
The real knobs are actually transparent, but these will indeed require some adjustment

**Comment by PointBlank66** [comment]
Yea, I looked it up just to be sure and while the real knobs are translucent, I don't believe its they are as translucent as the knobs are in the tfdi md-11. But thanks anyway for adjusting it some
