### ISSUE TITLE
[BUG] - Aircraft went in to descent phase after takeoff on short flight

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#569]
### Describe the bug

Was doing a flight from EGSS-EBOS and soon after takeoff the aircraft went in to descent phase in the FMC and put the thrust to idle. Re-inserting the cruise altitude on the init page did not fix the issue.

### Steps to reproduce

Depart EGSS and fly to EBOS with the route CLN5S CLN M84 KONAN L607 KOK with a cruising altitude of 17000 ft. Only an approach was entered (ILS 08), but no STAR so there was a discontinuity between KOK and the ILS.

### Expected behaviour

The aircraft should not enter descent phase directly after takeoff, and reinsterting the cruise flight level on the init page should make the aircraft recalculate the vertical profile and go in to the correct phase.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

2000

### Departure

EGSS

### Arrival

EBOS

### Cruise level

FL170

### ZFW

312000 LBS

### CG

28%

### Fuel

27000 LBS

### Cost index

100

### Route

CLN5S CLN M84 KONAN L607 KOK (discontinuity) ILS 08

### Location

Before initial turn on the CLN5S departure. 

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved with 0.36+.
