### ISSUE TITLE
[BUG] - bank angle rotary always point at auto

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#57]
### Describe the bug

the rotary to set bank angle always displays "auto" when clicking it it does move but snaps back to "auto" clicking it does change autopilot behaviour

### Expected behaviour

to indicate the max autopilot bank angle selected

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
See issue #74
