### ISSUE TITLE
[BUG] - Inaccurate TO Vspds

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#572]
### Describe the bug

FCU provides inaccurate, lower speeds than required

### Steps to reproduce

Fill out the TO/APPR during the pre-flight flow as you normally would. The speeds generated far not accurate.

### Expected behaviour

The speed the aircraft thinks you need are not correct. I use TOPCAT for my performance and those I consider more accurate even tho it's based off the old PMDG MD-11.

My takeoff weight was just shy of MTOW at 613.2lbs

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150947401/9963fc6d-303c-4c7d-961c-baa7cea99ae7)
![image](https://github.com/invernyx/md11-bugs/assets/150947401/a0951e0d-2ed2-4408-8a8a-8e1a6baac287)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
it says on the takeoff page the plane believes it's current GW is 405255lbs. In addition I reject the notion that topcat has "more accurate" vspeeds since we have modelled the vspeeds of the manuals of the real plane they should match to the exact knot

**Comment by CptUnicorn** [comment]
> it says on the takeoff page the plane believes it's current GW is 405255lbs. In addition I reject the notion that topcat has "more accurate" vspeeds since we have modelled the vspeeds of the manuals of the real plane they should match to the exact knot

Well that’s good to hear! However, my flight plan calls for 613.2 lbs for my TOW I load all that in, but gives me a lower number?
