### ISSUE TITLE
[BUG] - F/D Commanding level flight in a climb

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#573]
### Describe the bug

When doing a step climb, the pitch bar will level off while the aircraft is climbing

### Steps to reproduce

Initiate step climb.

### Expected behaviour

Once you are settled in the climb, you will see the pitch bar command level flight

### Evidence

![20231116135341_1](https://github.com/invernyx/md11-bugs/assets/150947401/8c0bd993-485c-4ef9-b636-42c09226e314)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

5-7 degrees

### Bank

0

### Heading

081M

### Altitude

FL290 climbing FL310

### Departure

N/A

### Arrival

N.A

### Cruise level

FL290 climbing FL310

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the flightdirector is not finished
