### ISSUE TITLE
[TODO] - Forward pedestal clickspots

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#576]
### Describe the bug

AUX HYD PUMP 1 and ANTI-SKID button clickspots work only in certain camera angles

### Steps to reproduce

Try to push either button from default pilot view (basically sitting on the captains chair)

### Expected behaviour

Should work from default angle and basically any angle that you are able to see the buttons and click them

### Evidence

In this first picture both HYD AUX PUMP 1 + ANTI-SKID buttons are unclickable. This is zoomed from default pilot view.

![FlightSimulator_LQk5WpzGeB](https://github.com/invernyx/md11-bugs/assets/102414406/e48cb422-0d92-43df-9564-97dea94299c8)

In this second picture from a different angle the buttons are clickable
![FlightSimulator_8u0vdlvk2B](https://github.com/invernyx/md11-bugs/assets/102414406/1c5ad682-5371-4c79-9386-7d9907b8bb00)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by alxcpt** [comment]
The speed brake lever blocks the view + functionality of the two buttons as well as the auto brake switch. Try selecting the autobrakes with mouse from the default seat position, either speedbrakes get deployed or armed.

**Comment by joon44** [comment]
> The speed brake lever blocks the view + functionality of the two buttons as well as the auto brake switch. Try selecting the autobrakes with mouse from the default seat position, either speedbrakes get deployed or armed.

So the speedbrake is taking a too big area then

**Comment by alxcpt** [comment]
> > The speed brake lever blocks the view + functionality of the two buttons as well as the auto brake switch. Try selecting the autobrakes with mouse from the default seat position, either speedbrakes get deployed or armed.
> 
> So the speedbrake is taking a too big area then

Kind of, it seems clicking next to the speedbrake e.g. on the two buttons, interacts with the speedbrake, as if there is a invisible area around the speedbrake where mouse interaction are assigned to the brake and not to the buttons/auto brake switch.

**Comment by TheFightingRaven** [comment]
@jhattermann can we improve the size of the spoiler occlusion box?
