### ISSUE TITLE
[BUG] - Fuel Temperature in tank seems to cool too quickly

### ISSUE THREAD

**Issue by timv217** [invernyx/md11-bugs#577]
### Describe the bug

Fuel Temperature in tank seems to cool too quickly considering the volume of liquid that requires cooling

### Steps to reproduce

Just fly with lots of fuel.

### Expected behaviour

Would expect longer fuel cool down when large volume of liquid is present.

Chatting with ChatGPT, we've looked at breaking down the factors that might affect fuel temperature change in the hope this might help represent a realistic model of fuel cooling (and heating?).

1. Input Parameters:
   - Outside Air Temperature at Flight Level
   - Aircraft Speed
   - Specific Heat Capacity of Jet A-1 Fuel (e.g., 2.05 J/g°C)
   - Mass of Fuel in the Wing Tank
   - Surface Area of the Fuel Tank
   - Heat Transfer Coefficient (depends on the material and design of the tank)
   - Heating Factor from Fuel Pump Heat Exchanger
   - Solar Heating Factor (additional heat from the sun) / angle of sun on aircraft   
   - Time (for calculating the rate)

<details>
  <summary>Click to reveal additional information about solar heating</summary>

  The angle of the sun towards the aircraft is factored in, as we did at Flightsimlabs. We found it aided representation, i.e. when sat on the ground in the blaring sun midday heat, the fuel would heat up quite quickly, compared to dusk as the sun sets and the direct heating factor is reducing.

</details>

2. Calculate Temperature Difference:
   - Determine the temperature difference between the fuel and the surrounding air.
     - Temperature Difference = OAT + (Heating Factor from Pump Heat Exchanger, if any) + Solar Heating Factor - (Temperature of the fuel due to aircraft speed)

3. Calculate Heat Transfer from Aircraft Speed:
   - Use the temperature difference, surface area, and heat transfer coefficient to calculate the rate of heat transfer due to the aircraft speed.

4. Calculate Heat Transfer from Pump Heat Exchanger:
   - Incorporate the heating factor from the pump heat exchanger into the calculation.

5. Calculate Total Heat Transfer:
   - Sum up the heat transfer from the aircraft speed, the pump heat exchanger, and the solar heating factor to get the total heat transfer rate.

6. Calculate Fuel Cooling Rate:
   - Use the specific heat capacity of Jet A-1 fuel to convert the total heat transfer rate into a change in temperature or cooling rate.
     - Fuel Cooling Rate = Total Heat Transfer / (Mass of Fuel * Specific Heat Capacity)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

360

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
