### ISSUE TITLE
[TODO] - IN/HPa transfer button is not mapped, unable to fly in HPa

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#58]
### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

None

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is fixed for the captainside, but like all other buttons on the FO efis, clickable but nothing happens

**Comment by GenericNerd** [comment]
@jhattermann Is this resolved?

**Comment by GenericNerd** [comment]
@turbofandude This has been fixed in the model, may require a change on your side.
