### ISSUE TITLE
[BUG] - Magenta Line Tracking too wide

### ISSUE THREAD

**Issue by turbodeas** [invernyx/md11-bugs#580]
### Describe the bug

On approach to LEIB via CORD3V, it seemed like the autopilot was not able to turn fast enough to meet the navigation requirements.

### Steps to reproduce

Descending (PROF) FL390 to 4000, via CORD3V to LEIB. Cost index of 150.

### Expected behaviour

I would expect the autopilot should predict the turns and make the turns correctly.

### Evidence

![cord3v](https://github.com/invernyx/md11-bugs/assets/133995384/f3146a44-4ecd-4533-9285-8485b5c9bc3a)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Departure

EGCC

### Arrival

LEIB

### Cruise level

FL390

### ZFW

147.9KG

### CG

30

### Fuel

21.0 KG

### Cost index

150

### Route

23R SANB1R SANBA N859 HON UN859 SOPIL DCT BALAN DCT EVPOK DCT NARAK DCT GAI DCT LOMRA DCT ROCAN DCT PUMAL UN859 BCN UZ174 CORDA CORD3V 06

### Location

CORD3V STAR, DEGEV TRANSITION TO LEIB. APPROACHING ADX.

### Agreement

- [X] Yes

**Comment by CptUnicorn** [comment]
Did the magenta line up with the waypoints? I have issues with complex RNAV STARs where the line just ignores the waypoints and does its own thing.

**Comment by turbodeas** [comment]
No, it didn't line up with the waypoints. It's almost like the turn
prediction predicted it would be too wide, and the plane followed it.

**Comment by CptUnicorn** [comment]
Check out #564 that I posted a few days ago.
