### ISSUE TITLE
Weather Radar Annunciator Display missing (from a closed issue)

### ISSUE THREAD

**Issue by Willmus11** [invernyx/md11-bugs#581]
This topic shouldn't be closed, here are the two possible display from the lower right corner, regardless WX radar inop or not, this box cannot be removed
Here are reference I made today

<img width="431" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/2c835ac3-445f-4c5c-a191-6c978ba54c9f">
<img width="436" alt="image" src="https://github.com/invernyx/md11-bugs/assets/150386027/fb0da2b0-bebf-41d1-ad8a-7dc579b796c2">

_Originally posted by @Willmus11 in https://github.com/invernyx/md11-bugs/issues/372#issuecomment-1806486169_

**Comment by TheFightingRaven** [comment]
original issue reopened
