### ISSUE TITLE
[BUG] - Nav light leak onto lateral trailing edges (MD-GEN-8)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#583]
### Describe the bug

At night, the red and green nav lights leak onto the lateral trailing edge surfaces

### Expected behaviour

no leak

### Evidence

![FlightSimulator_2023_11_17_19_42_07_026](https://github.com/invernyx/md11-bugs/assets/148836830/e97ef8fa-9935-49ea-a350-a1c7e73878c4)
![FlightSimulator_2023_11_17_19_42_10_793](https://github.com/invernyx/md11-bugs/assets/148836830/27eb8bcd-603c-48dd-8ab0-5a617f3a478a)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This bug is similar to https://github.com/invernyx/md11-bugs/issues/1252 and thus this particular report will be closed.
