### ISSUE TITLE
[BUG] - Outboard ailerons do not move at low speeds 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#585]
### Describe the bug

The outboard ailerons do not move the moment you get airbourne 

### Steps to reproduce

Takeoff and fly at low speeds 

### Expected behaviour

To have the ailerons moving at low speeds 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
FYI they do move when the autopilot is engaged at low speeds, but when you're hand flying it they stop moving

**Comment by Willmus11** [comment]
FCOM:

When the flaps, slats, and landing gear are retracted, a lockout mechanism keeps 
the outboard ailerons faired (neutral) to avoid wing twist. In this case lateral 
control is provided by the inboard ailerons and the lateral function of the spoilers. 
As the airplane slows down, the outboard ailerons unlock with flaps extended to 
15 degrees, or with slats extended, or with landing gear down and locked.

**Comment by fugotaro** [comment]
*With flaps and gear down*

**Comment by turbofandude** [comment]
This is intended behavior as per the FCOM. The autopilot has no bearing on the outboard ailerons - only slats/flaps and gear do.

**Comment by fugotaro** [comment]
I think you may have misunderstood what I meant: https://streamable.com/jlxp69

It's only for the pax variant the freighter works as it should
