### ISSUE TITLE
[BUG] - ARPT on ND inop 

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#588]
### Describe the bug

Hope to see this feauture coming ;)

### Expected behaviour

-

### Evidence

-
![Schermafbeelding 2023-11-18 132026](https://github.com/invernyx/md11-bugs/assets/71586114/b6ddad2a-2525-4d86-921f-607df57ee389)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by Daniz010** [comment]
It doesn`t cause a crash, sorry ;)

**Comment by mclovin90** [comment]
Still broken in .22 Alpha on Captain Side
