### ISSUE TITLE
[BUG] - Unable to Interact With HDG Knob In NAV Mode

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#590]
### Describe the bug

While in NAV mode, pushing, pulling, or rotating the HDG knob as no effect

### Steps to reproduce

During climb and cruise, while A/P is on and NAV is the selected lateral mode, interacting with the HDG knob has no effect.

### Expected behaviour

Spinning the heading knob should wake up the display #260 
Waking up the display should also enable the heading bug and line on the ND
Pushing the knob should switch the lateral mode to HEADING and command present heading
Pulling the knob should command lateral mode to HEADING and initiate a turn toward commanded heading in FCP

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

10k +

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

NA

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved
