### ISSUE TITLE
PROF doesnt respect altitude window

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#594]
### Describe the bug

On a flight OEDF-OTHH I have cruise level 150 and HAYYA 1V star into OTHH. The star has altitude constraints of +FL210 and +FL190. After I leveled off at FL150, I got PROF to 19000 and 21000 annunciations on FMA and the plane started climbing itself even that I had 15000 set in the altitude window on FCP. Also on F-PLN INIT page the cruise level line showd 99/99/99/99...

### Steps to reproduce

Fly at cruise level which is lower than altitude constraint on the STAR. In this case OTHH HAYYA 1V STAR with initial altitude constraint of FL210 or above.

### Expected behaviour

The value set in the altitude window MUST be respected

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/00e94758-8ab7-4c1d-b2d2-f750c527be33)
![FlightSimulator_i8zUurRQ0c](https://github.com/invernyx/md11-bugs/assets/102414406/a804c542-1f50-4abe-8720-a84f2ec819f9)
![FlightSimulator_eeaIq7MvTA](https://github.com/invernyx/md11-bugs/assets/102414406/43aa2642-9a15-4655-88b4-44ffcdef730b)
![FlightSimulator_8bwADcoDX7](https://github.com/invernyx/md11-bugs/assets/102414406/69b393ca-4325-40df-a1d6-7b0eaee3661c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

15000

### Departure

oedf

### Arrival

othh

### Cruise level

FL150

### ZFW

158.2 kg

### CG

27.7

### Fuel

12500 kg

### Cost index

100

### Route

OEDF34R LADN1F LADNA N318 HAYYA HAYA1V OTHH34R

### Location

After DF516 waypoint on SID

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Also clearing the altitude constraints from the star, the AP returned to holding 15000

**Comment by crazyforiphone** [comment]
I had this happen to me, where the CRZ sets itself to -99 and prof goes insane 2 builds ago, but it only happened once as I did something weird in the FMS.

**Comment by joon44** [comment]
![Screenshot_2023-11-19-12-09-19-27_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/invernyx/md11-bugs/assets/102414406/4d9ec204-f9be-4a5d-b481-a88310cba6d8)

**Comment by turbofandude** [comment]
The problem is unrelated to the FCP window - it was because the altitude restrictions existed above the cruise level. I've added code to exclude restrictions that exist above your current cruise from PROF altitude targets.
