### ISSUE TITLE
[BUG] - Misc SD selector button is not animated

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#6]
### Describe the bug

The MISC SD selector button is not animated

### Steps to reproduce

1. Press the MISC SD selector button

### Expected behaviour

The button should be animated

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by joon44** [comment]
I programmed this to my Streamdeck with the md11_ped_sd_misc_bt lvar and it is animated when I press the button. So only the mouse clickspot is missing.

**Comment by turbofandude** [comment]
Resolved in 0.25+
