### ISSUE TITLE
[BUG] - No “Green Box” for landing

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#600]
### Describe the bug

When fully configured you should have a green box, not a white box.

### Expected behaviour

There is a “Green Box” for takeoff, but there is a white box when fully configured with gear, landing flaps in agreement with APP page, auto brakes and spoilers armed.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This is resolved in 0.23+
