### ISSUE TITLE
[BUG] - Still increasing LW on long flights

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#602]
### Describe the bug

The LW is increasing during the flight

### Steps to reproduce

Still it's a bug that the LW is increasing during longer flights instead of decreasing.
Therefore it's hard to land that airplane due to max. landing weights because the behaviour of the airplane is that he seems to be so heavy.

### Expected behaviour

Reducing the LW continousely during the flight.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

Every flight level

### Departure

SBGR

### Arrival

KAUS

### Cruise level

FL380

### ZFW

273397

### CG

23,8

### Fuel

17100

### Cost index

25

### Route

ZORZ2A ZORZA GERTU LONAL CIA MULIP ABIDE MTU UW89 VVC ISVAT RNG SPP UA552 PZA CTM UJ61 CPE ULUMA BALLO

### Location

Golf of Mexico

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
will be fixed in 0.16

**Comment by uwiuke** [comment]
it's not fixed - even in the actual version 0.18 it's still the behaviour that the LW is higher than TOW.
It's not possible to do really LongHaul-Testflights.
