### ISSUE TITLE
Throttles Oscillating

### ISSUE THREAD

**Issue by Gazguzzler** [invernyx/md11-bugs#604]
### Describe the bug

When in the cruise the throttles keep advancing to 93% N1 then decreasing to 81% N1 constantly.

### Steps to reproduce

Auto flight conditions are set and level flight whilst in cruise.

### Expected behaviour

Stable throttles, very little movement expected.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Pitch

Zero pitch

### Bank

Zero bank

### Heading

216

### Altitude

FL360

### Departure

EFHK

### Arrival

EDDK

### Cruise level

FL360

### ZFW

405.6 lbs

### CG

26.8%

### Fuel

44800 lbs

### Cost index

117

### Route

EFHK/15 N0474F360 VALO3D VALOX Y117 ROSAX DCT PIMEX P739 DEREX DCT PENOR DCT BODLA DCT KOSIX DCT NIMAB T171 MAIXE/N0481F300 T171 LASTO T178 ROBEL/N0463F240 T178 DEMAB T842 EBANA T841 BATEB/N0382F120 T841 ERNEP ERNE1C EDDK/24

### Location

Once established in the cruise, currently between DEREX and PENOR way points.

### Agreement

- [X] Yes

**Comment by Gazguzzler** [comment]
No crash of the SIM or aircraft is experienced with this issue.

**Comment by slowreload** [comment]
Can confirm

**Comment by TheFightingRaven** [comment]
was this in gusty conditions?

**Comment by Gazguzzler** [comment]
Yes, there was strong gusting headwinds. Recent flights with moderate winds have been OK with the throttles hardly moving.
