### ISSUE TITLE
[BUG] - Autopilot Disconnects

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#605]
### Describe the bug

Autopilot Disconnects at radom times during flight

### Steps to reproduce

Load flight with at least waypoints and fly.

### Expected behaviour

Loaded flight-plan KSAN/KPHX and KPDX/KBOI on at least 2 occasions each. About 15 - 30 minutes after departure I get the AUTOPILOT warning. I am unable to simply reset the AP to continue flight.  

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

normal

### Bank

none

### Heading

variable

### Altitude

variable at differrent altitudes

### Departure

KSAN and KPDX

### Arrival

KPHX and KBOI

### Cruise level

Varible

### ZFW

Varible

### CG

Varible

### Fuel

Varible

### Cost index

Varible

### Route

KPDX/28L N0462F390 WHAMY4 IMB DCT DEVLE KYAAN4 KBOI/28R

KSAN/27 N0469F410 ZZOOO3 IPL J18 BZA DCT HOGGZ HYDRR1 KPHX/07L

### Location

Warning comes around IMB and IPL

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Works for me. Try incrreasing your deadzones. Ap warnibg can be reset from the yoke button or with the correct bind.
