### ISSUE TITLE
[BUG] - PROG Does not show Distant to GO

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#606]
### Describe the bug

PROH Page does not show distance to destination

### Steps to reproduce

Load Flight plan and look at PROG Page

### Expected behaviour

N/A

### Evidence

![MD11FMS](https://github.com/invernyx/md11-bugs/assets/150555279/8a6bf0cf-1496-468a-9afd-caa403ab06bd)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

NA

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

On Ramp and in the air.

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.30+. ALTN flight plan calculations are not yet implemented.
