### ISSUE TITLE
[BUG] - Landing Gear Handle Translucent 

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#607]
### Describe the bug

Landing Gear Handle Translucent 

### Expected behaviour

See screenshot

### Evidence

![MD11Land gear handle](https://github.com/invernyx/md11-bugs/assets/150555279/2932a133-20cd-4587-82b2-3519e7d36e0d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by MountainManB** [comment]
This is how it is in the actual plane IRL

**Comment by rsmith6621a** [comment]
I think it could be a bit less translucent when looking at images of the
real thing. You can read through this knob. It almost looks white in color.

**Comment by GR1MMly** [comment]
Understanding the limits of modelling, I think its as close to the real knob as you'll get. It's essentially clear acrylic.

**Comment by rsmith6621a** [comment]
As a user I would be happier if it were modeled in an off white slightly
worn look. The clear looks awkward.
Randy

**Comment by MountainManB** [comment]
Yeah I am around these all the time and it actually looks pretty spot on to the real thing.Seeing pictures don't do it justice. I think the art team nailed it with this
