### ISSUE TITLE
[BUG] - PACK LIGHTS ON IN Ready To Take Off Mode

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#609]
### Describe the bug

The pack lights are on when you start the aircraft with engines running and ready to takeoff

### Steps to reproduce

Start MSFS up with MD-11 in the ready to take-off mode and look at overhead.

### Expected behaviour

NA

### Evidence

![MD11UpperPanel](https://github.com/invernyx/md11-bugs/assets/150555279/f10d243a-3efb-4396-9ae1-3ee7a5adcedc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

NA

### Agreement

- [X] Yes

**Comment by 017941** [comment]
Just another tester here, not a developer. Question: Did you turn on the packs on the Takeoff page? For whatever reason it is preset to packs off. I have 21,000 hours flying big jets, and I've probably done 40 packs off takeoffs in my life. They should be spawning with the packs on. Just my two cents.
