### ISSUE TITLE
250 KIAS Below 10,000 is not inputting to FMC

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#611]
### Describe the bug

250 KIAS Below 10,000 is not inputting to FMC

### Steps to reproduce

Load a STAR into the FMC and then check the speeds below 10,000'. This was the ROBUC3 Arrival into KBOS, but it seems to be occurring on every STAR. 

### Expected behaviour

When you load a STAR into the FMC, I would expect the arrival speeds, including the speeds below 10,000', to be honored and displayed.

### Evidence

N

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL240

### Departure

KJFK

### Arrival

KBOS

### Cruise level

FL240

### ZFW

370,000

### CG

27%

### Fuel

40.0

### Cost index

41

### Route

KJFK SCORRS3 YANKEE TRANSITION MERIT ROBUC3 MERIT TRTANSITION ILS 4R KBOS

### Location

NOTICED AT CRUISE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
should be fixed in 0.16
