### ISSUE TITLE
[TODO] - SimBrief Integration

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#612]
### Describe the bug

SimBrief Integration

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

P3Dv4, P3Dv5, P3Dv6, Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Add a page to the EFB to show the OFP and buttons to scroll up and down or bind mouse wheel for it.

**Comment by GenericNerd** [comment]
This will be added in the next update
