### ISSUE TITLE
[BUG] - FMC sid differ from the charts

### ISSUE THREAD

**Issue by wagoozen1** [invernyx/md11-bugs#616]
### Describe the bug

When selecting a SID the draw line differ from the real world.

### Steps to reproduce

EHAM - Runway 24 - BERG2S

The charts SID difffer from the FMS SID
see schreenshot for proof

### Expected behaviour

After take fly to AM001, then slightly left to AM051 then go to AM009

### Evidence
This is what we would like to see
![2023-11-20 21_19_38-Navigraph Charts](https://github.com/invernyx/md11-bugs/assets/114499693/71b347f5-99a9-4395-86cf-fffc4eb1b0b1)

This is how its been drawn:
![2023-11-20 21_31_49-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/7aec21ed-b669-4752-a3be-6ae57fb6316b)
![2023-11-20 21_16_51-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/6b4a0f9f-e293-4f86-ad11-6a2f703d2a5a)

![2023-11-20 21_18_24-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/41b33c5d-4fc0-4e0f-80e8-5ce4c9fd0146)
![2023-11-20 21_17_15-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/f00440df-0e29-4195-80c1-23916eadf25f)
![2023-11-20 21_19_52-Navigraph Charts](https://github.com/invernyx/md11-bugs/assets/114499693/f95f2830-9f22-4494-9a42-7b56757517e8)
![2023-11-20 21_17_41-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/0c8e4c18-b5cc-4bfa-8ff3-65311b16a901)
![2023-11-20 21_20_01-Navigraph Charts](https://github.com/invernyx/md11-bugs/assets/114499693/192ba15d-9342-4aa3-a27d-131639e3765e)
![2023-11-20 21_18_16-Microsoft Flight Simulator - 1 34 16 0](https://github.com/invernyx/md11-bugs/assets/114499693/35464dcd-2657-48d4-b1ab-54664064a0d9)
![2023-11-20 21_20_12-Navigraph Charts](https://github.com/invernyx/md11-bugs/assets/114499693/bb24c6f3-0c84-4aba-92cf-906e717e94c2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On ground

### Departure

EHAM

### Arrival

CYYZ

### Cruise level

FL000

### ZFW

N/A

### CG

n/A

### Fuel

N/A

### Cost index

N/A

### Route

EHAM/24 BERGI2S BERGI L602 SUPUR L60 PENIL M144 BAGSO DCT
DOGAL NATB HOIST N600A YBC DCT POLTY IMEBA9 CYYZ/05

### Location

EHAM - runway 24

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Same issue on many places and STARs too.

**Comment by slowreload** [comment]
Same issue KONT ziggy STAR had it today

**Comment by turbofandude** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/3858710/e2cb08cb-1615-4326-9f3c-ccd282c0b9b1)
Fixed as of 0.30+
