### ISSUE TITLE
[BUG] - Main Middle Gear Through The Ground

### ISSUE THREAD

**Issue by bassplane** [invernyx/md11-bugs#617]
### Describe the bug

The main middle gear goes through the surface.

### Expected behaviour

The main middle gear should be, just like the left and right main gears, just on the surface.

### Evidence

![Screenshot 2023-11-20 215425](https://github.com/invernyx/md11-bugs/assets/150367558/55ae9503-c81f-44cf-aac6-ed22066cf128)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by CptUnicorn** [comment]
This may just be a freighter version issue. I'm not seeing it on the passenger variant.

**Comment by TheFightingRaven** [comment]
#5
