### ISSUE TITLE
[BUG] - "Holding" paths over waypoints

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#619]
### Describe the bug

There are a few waypoints that have circles around them that looks like an active flight path.

### Expected behaviour

I expect to see a consistent magenta line with out "holding" patterns around waypoints

### Evidence

![20231121080706_1](https://github.com/invernyx/md11-bugs/assets/150947401/1512cb78-f7e0-4d3b-81a6-e447c39a16ad)
![20231121080712_1](https://github.com/invernyx/md11-bugs/assets/150947401/28f8bf57-a982-4dfb-becd-ef2f896b70fd)
![20231121080713_1](https://github.com/invernyx/md11-bugs/assets/150947401/7e040c73-bfeb-49e5-99b2-f9223ee971e6)
![20231121080719_1](https://github.com/invernyx/md11-bugs/assets/150947401/a6a5c8d7-2273-4932-b613-fe61fc2ca039)
![20231121080720_1](https://github.com/invernyx/md11-bugs/assets/150947401/6812a9ca-01d5-45be-a34e-6822c35d5042)
![20231121080723_1](https://github.com/invernyx/md11-bugs/assets/150947401/c78be01e-ce13-4531-9a10-d147570080c8)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#436
