### ISSUE TITLE
[BUG] - procedure messing up nav

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#62]
### Describe the bug

plane turns around and flies wrong direction

### Steps to reproduce

fly the luni2k star into LEPA the leg Pollensa>bavum

### Crash

None

### Phase of flight

Approach

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed

**Comment by NorcalBear** [comment]
0.44.0-alpha.  Descending into EGNX, landing runway 27.  Selected HEMEL 1E arrival, PIGOT transition.  Upon reaching waypoint UPDUK, plane turned to the right and intercepted PIGOT and continued with the transition to RWY 27.  According to the chart, the airplane should have continued a left turn upon passing UPDUK, then continued to PIGOT.  After PIGOT, the airplane would make a left turn and continue to track the route to intercept RWY 27.
