### ISSUE TITLE
[BUG] - PFD incorrect VS on PFD

### ISSUE THREAD

**Issue by slowreload** [invernyx/md11-bugs#622]
### Describe the bug

PFD text is wrong sellected 1800vs displays as 8100 on pfd

### Expected behaviour

Correct VS in box on PFD

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/5056361/e5ed0511-46fc-4769-bbbe-a4678c704d73)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
that is the altitude target, the VS target says 1.8 (as in 1.8 x 1000fpm=1800fpm)
