### ISSUE TITLE
[BUG] - Partial power loss on engine start

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#624]
### Describe the bug

Occasionally I will lose power during engine start. It doesn't happen every time, but often enough to be annoying.

### Steps to reproduce

Set up the aircraft as you normally would. Start engines as you normally would. As soon as fuel is introduced, the captains side goes black.

### Expected behaviour

I expect to not have to reset the EMER PWR switch in order to regain power.

### Evidence

https://medal.tv/games/microsoft-flight-simulator/clips/1F55UBqIqudjQU/d1337USNAWNH?invite=cr-MSwyWncsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
could not recreate and evidence linked is to flickering textures
