### ISSUE TITLE
[BUG] - Stall protection system not doing as intended

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#625]
### Describe the bug

I stepped away for a few minutes to tend to my dogs needs and when I came back I was in a nose dive. I looked back at the footage on my recording software and it appears the aircraft stalled. Unfortunately my software only records the last 2 minutes so I am not sure what caused the aircraft to get so slow so quickly. But as you can see, the aircraft is at a dangerously slow speed as the aircraft begins to oculate left and right eventually leading to a wing stalling and entering what looked like a fully developed flat spin.

### Steps to reproduce

Enter a stall at altitude with autopilot engaged.

### Expected behaviour

I hope to see the stall prevention system kick in.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150947401/cb4957c9-9033-49a6-b0d4-eb170b4771dd)

https://medal.tv/games/microsoft-flight-simulator/clips/1F5NWd3zc-tbya/d1337lsxw27E?invite=cr-MSx6cWksMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

5 degrees

### Bank

0

### Heading

N/A

### Altitude

FL360

### Departure

EHAM

### Arrival

CYVR

### Cruise level

FL360

### ZFW

155.7

### CG

25.6

### Fuel

N/A

### Cost index

200

### Route

EHAM/09 N0487F340 BERG3N BERGI DCT ROKAN DCT NAVEL DCT DENOG DCT KESEG/M084F340 DCT 6210N DCT 6620N DCT 68N027W DCT 7040N DCT 7160N DCT NADMA/N0473F340 DCT 71N070W DCT 7078N DCT 68N090W 66N098W 64N104W DCT YSM J528 YQU DCT BOOTH LIONN2 CYVR/08L

### Location

Over Northern mainland Canada near Igloolik

### Agreement

- [X] Yes

**Comment by 017941** [comment]
I'm not a developer. Just a tester. I tried doing a stall series and I do not believe that the stall logic is implemented. Other than amber A/S at the foot Vss and red airspeed at Vs, I never got the stick nudge approaching Vss nor the autoslats at Vss. I was watching your video, and that was some weird stuff. 94 percent power and it was behaving as though all three engines had flamed out. I'm not sure what a stick nudge would do for that BUG,as you were letting the dog out. The autoslats never deployed, but I don't think that would have helped. Definitely a BUG. Weird one. I have not seen that happen before.

![IMG_2273](https://github.com/invernyx/md11-bugs/assets/148719444/96931fe1-80c9-477c-b8ac-abcb1f2efdf4)

**Comment by CptUnicorn** [comment]
> I'm not a developer. Just a tester. I tried doing a stall series and I do not believe that the stall logic is implemented. Other than amber A/S at the foot Vss and red airspeed at Vs, I never got the stick nudge approaching Vss nor the autoslats at Vss. I was watching your video, and that was some weird stuff. 94 percent power and it was behaving as though all three engines had flamed out. I'm not sure what a stick nudge would do for that BUG,as you were letting the dog out. The autoslats never deployed, but I don't think that would have helped. Definitely a BUG. Weird one. I have not seen that happen before.
> 
> ![IMG_2273](https://user-images.githubusercontent.com/148719444/284901685-96931fe1-80c9-477c-b8ac-abcb1f2efdf4.jpg)

That manual page was a great read!

It was really weird. I genuinely thought I bumped my joystick setting my headset down until I watched the footage. I remember during my early stages of flight training my instructor told me to never use alerion when in a stall because it could exacerbate the stall. There is so much alerion movement in the video lol. If I had been maybe 30 seconds earlier I probably could have saved the plane, but it is what it is.

**Comment by FreakyD777** [comment]
I already wrote up two PRs on stall indication and performance.  See #279 and #267
