### ISSUE TITLE
[BUG] - Inaccurate GPWS callouts

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#629]
### Describe the bug

the GPWS appears to be going off of the barometric altimeter instead of the radio altimeter

### Steps to reproduce

Shoot an approach and monitor the GPWS callouts. Make sure your altimeter is set correctly.

### Expected behaviour

To have accurate callouts at each altitude.

### Evidence

https://medal.tv/games/microsoft-flight-simulator/clips/1F7E7u7hPGvZAc/d1337B8o44wN?invite=cr-MSxxSHMsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by joon44** [comment]
If you are parked on the ground or taxiing at exactly the callout altitude, say at 50ft BARO, the callout keeps repeating.

**Comment by joon44** [comment]
> > If you are parked on the ground or taxiing at exactly the callout altitude, say at 50ft BARO, the callout keeps repeating.
> 
> I personally haven't had that issue, but seen the reports on it.

I think the issue is exactly what you reported also. Callouts come from baro, not RA. Therefore it gives you continuous callouts even on the ground. If the taxiway is at 40ft, you get a repeating 40 callout.

**Comment by 017941** [comment]
I had this last night. On taxi in I kept getting the 50' callout until I ran the "BARO" up a few feet. It was definitely off the baro.

**Comment by joon44** [comment]
> I had this last night. On taxi in I kept getting the 50' callout until I ran the "BARO" up a few feet. It was definitely off the baro.

I also  dial the baro lower so im taxiing below sea level so it silences.
