### ISSUE TITLE
[BUG] - Missing waypoints on approach

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#630]
### Describe the bug

Waypoints are missing from the final approach course

### Steps to reproduce

Set up any approach to any runway

### Expected behaviour

To have waypoints as well as the MAP.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150947401/e5a88ae4-b43e-483f-b5f3-f4e16b6f6e79)

![20231122085934_1](https://github.com/invernyx/md11-bugs/assets/150947401/090e9eb7-43c8-4757-9db7-7e15e1c5923d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Departure

KMEM

### Arrival

KBOS

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

KMEM/36C N0479F350 GOETZ7 DIYAB DCT BNA DCT SWAPP Q34 RBV Q419 JFK ROBUC3 KBOS/22L

### Location

Boston Logan International Airport

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should have long since been resolved
