### ISSUE TITLE
[BUG] - Trouble maintaining cruise altitude

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#634]
### Describe the bug

Occasionally the aircraft will blow passed the selected altitude and fly about 300-400 feet above. If you manually descend with the V/S it wont level off at the assigned altitude. Selecting PROF will momentarily put the aircraft into a 5 degree nose down descent before achieving positive rate of climb. It will then continue climbing above the selected. It appears to have correlation with the altimeter and selecting the altitude of the current altitude. It is as if it is trying to maintain the pressure altitude above transition level. A quick fix is to just reset the altimeter from STD to a random setting, back to STD

### Steps to reproduce

Fly at cruise level, monitor altitude. Make sure altimeter is set to STD.

### Expected behaviour

To maintain altitude when standard pressure is set.

### Evidence

https://medal.tv/games/microsoft-flight-simulator/clips/1Ffzg4Mbp-o-Qp/d1337ylMULRS?invite=cr-MSxnNzQsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

N/A

### Bank

N/A

### Heading

N/A

### Altitude

N/A

### Departure

N/A

### Arrival

N/A

### Cruise level

FL320

### ZFW

N?A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved
