### ISSUE TITLE
T/O Page should spawn with Packs ON not OFF

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#635]
### Describe the bug

T/O Page should spawn with Packs ON not OFF

### Steps to reproduce

Select T/O page of FMC and note the packs are pre-selected OFF. I have 21,000 hours and I have done perhaps 30 Packs OFF takeoffs. 

### Expected behaviour

I would definitely have the T?O Page default to Packs ON. Is this what is causing the Packs to be off on spawn? Someone GITHUB'd the Pack being off, and I imagine it's from the PACKS OFF setting on the T/O page.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

n

### Departure

n

### Arrival

n

### Cruise level

n

### ZFW

n

### CG

n

### Fuel

n

### Cost index

n

### Route

n

### Location

n

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/138527559/203b0186-9121-4f49-ac06-c5de6c818d25)
according to the KLM fcom, this is not correct. Unless you can show it to be a company option, the manuals support the way it works currently

**Comment by 017941** [comment]
Sent from my iPhoneOn Nov 28, 2023, at 3:57 PM, Jeffrey Richard ***@***.***> wrote:﻿I’m sorry. I just looked it up in the FOM, and you are absolutely correct. The TO/APP page does spawn with the packs off. They must be toggled on at 2L. Very sorry.On Tue, Nov 28, 2023 at 3:37 PM TheFightingRaven ***@***.***> wrote:
image.png (view on web)
according to the KLM fcom, this is not correct. Unless you can show it to be a company option, the manuals support the way it works currently

**Comment by 017941** [comment]
Sent from my iPhoneOn Nov 28, 2023, at 4:01 PM, Jeffrey Richard ***@***.***> wrote:﻿<IMG_2294.jpeg>Sent from my iPhoneOn Nov 28, 2023, at 3:57 PM, Jeffrey Richard ***@***.***> wrote:﻿I’m sorry. I just looked it up in the FOM, and you are absolutely correct. The TO/APP page does spawn with the packs off. They must be toggled on at 2L. Very sorry.On Tue, Nov 28, 2023 at 3:37 PM TheFightingRaven ***@***.***> wrote:
image.png (view on web)
according to the KLM fcom, this is not correct. Unless you can show it to be a company option, the manuals support the way it works currently
