### ISSUE TITLE
Cargo FWD and AFT flow illuminate on spawn

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#636]
### Describe the bug

Cargo FWD and AFT flow switches should spawn in the on position.

### Expected behaviour

The Cargo panel FWD and AFT flow lights are never touched in normal procedures, and they should not be defaulted to the off position upon pre-flight spawn.

We do shut both Cargo Heat switches off in the shutdown checklist, but not the Cargo Flows. Maybe it's a KLM thing.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [x] Yes

**Comment by GR1MMly** [comment]
I would recommend clarification: The switches are defaulted to the OFF position and should not be (as opposed to an errant illumination of the switch).

**Comment by 017941** [comment]
Great point!

**Comment by 017941** [comment]
I made those changes to the report. Thank you.

**Comment by turbofandude** [comment]
Fixed in 0.26+
