### ISSUE TITLE
Flight director bars need to be desensitized.

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#637]
### Describe the bug

The flight director bars are too abrupt

### Expected behaviour

This is one great flying model.  It flies very smoothly, but the bars are way too abrupt leaving the pilot feeling spastic even though they are flying a smooth airplane. Maybe just desensitize them a tad.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved with 0.36+.
