### ISSUE TITLE
[BUG] - Engine Reverse animation not corrected.

### ISSUE THREAD

**Issue by loveyuikr** [invernyx/md11-bugs#639]
### Describe the bug

Engine Reverse animation not corrected.

### Expected behaviour

I check my throttle setting. is ok.

so, set engine 1 thruset to reverse. Engine 3 reverser is on. and Engine 3 is same behavior. set engine 3 thrust to reverse, engine 1 reverser is on.

### Evidence

![Microsoft Flight Simulator - 1 34 16 0 2023-11-24 오전 1_23_04](https://github.com/invernyx/md11-bugs/assets/151863696/ef035009-adcd-4bb3-8b5c-c8d59e0c4e0e)
![Microsoft Flight Simulator - 1 34 16 0 2023-11-24 오전 1_23_08](https://github.com/invernyx/md11-bugs/assets/151863696/b20831d4-9ff0-4503-a9ae-36f718328db0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by 017941** [comment]
> ### Describe the bug
> 
> Engine Reverse animation not corrected.
> 
> ### Expected behaviour
> 
> I check my throttle setting. is ok.
> 
> 
> 
> so, set engine 1 thruset to reverse. Engine 3 reverser is on. and Engine 3 is same behavior. set engine 3 thrust to reverse, engine 1 reverser is on.
> 
> 
> 
> ### Evidence
> 
> ![Microsoft Flight Simulator - 1 34 16 0 2023-11-24 오전 1_23_04](https://github.com/invernyx/md11-bugs/assets/151863696/ef035009-adcd-4bb3-8b5c-c8d59e0c4e0e)
> 
> ![Microsoft Flight Simulator - 1 34 16 0 2023-11-24 오전 1_23_08](https://github.com/invernyx/md11-bugs/assets/151863696/b20831d4-9ff0-4503-a9ae-36f718328db0)
> 
> 
> 
> ### Simulator
> 
> Microsoft Flight Simulator 2020 (MSFS)
> 
> ### Aircraft Type
> 
> Passenger GE
> 
> ### Agreement
> 
> - [X] Yes

I too experienced this. When you place engine 3 in reverse the N1 gauge for the number three engine shows Rev, but the exterior animation instead has no reverse on number 3 but reverse exterior animation in number 1. The same holds true for the number 1 engine ie. Rev displayed on the number 1 Eng, no exterior reversed animation on number 1, but instead in number 3.

**Comment by 017941** [comment]
> ### Describe the bug
> 
> Engine Reverse animation not corrected.
> 
> ### Expected behaviour
> 
> I check my throttle setting. is ok.
> 
> 
> 
> so, set engine 1 thruset to reverse. Engine 3 reverser is on. and Engine 3 is same behavior. set engine 3 thrust to reverse, engine 1 reverser is on.
> 
> 
> 
> ### Evidence
> 
> ![Microsoft Flight Simulator - 1 34 16 0 2023-11-24 오전 1_23_04](https://github.com/invernyx/md11-bugs/assets/151863696/ef035009-adcd-4bb3-8b5c-c8d59e0c4e0e)
> 
> ![Microsoft Flight Simulator - 1 34 16 0 2023-11-24 오전 1_23_08](https://github.com/invernyx/md11-bugs/assets/151863696/b20831d4-9ff0-4503-a9ae-36f718328db0)
> 
> 
> 
> ### Simulator
> 
> Microsoft Flight Simulator 2020 (MSFS)
> 
> ### Aircraft Type
> 
> Passenger GE
> 
> ### Agreement
> 
> - [X] Yes

Reference this video from 1:28:00 to 1:30:00 

Take the full-flight challenge from  KLGB (RWY 30) - KLAS  (ILS RWY 26L) and search for GITHUB bugs!
https://youtu.be/xdFm6Mslit4
