### ISSUE TITLE
[BUG] - EFB calculated CG does not match FMS autopopulate CG (MD-FMS-4)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#640]
### Describe the bug

The CG data calculated in the EFB does not match the autofill CGs values in the WEIGHT INIT page on the FMS

### Steps to reproduce

Set ZFW and FUEL load in EFB
Note the ZFW and Current CG numbers
In the FMS, autopopulate the TOCG and ZFWCG values
Note the difference

### Expected behaviour

S/B same or within 0.1

### Evidence

![FlightSimulator_2023_11_23_09_10_28_091](https://github.com/invernyx/md11-bugs/assets/148836830/d184e955-c97d-412a-88f3-f2e71f299be0)
![FlightSimulator_2023_11_23_09_10_30_407](https://github.com/invernyx/md11-bugs/assets/148836830/7f023b56-d287-4682-8ffd-86027b263391)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Departure

07MT

### Arrival

07MT

### Cruise level

FL300

### ZFW

320k lb

### CG

n/a

### Fuel

40k lb

### Cost index

55

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
In future update, the EFB will not provide CG
