### ISSUE TITLE
[BUG] - AFS unable to hit and maintain target IAS (MD-AFS-10)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#641]
### Describe the bug

At various flight levels, standard day temp, no wind, A/T system unable to meet selected target speed when in MACH select (IAS select works as indended).  In MACH select, the A/T maintains 0.1M less then target.  This issue happens both in speed override mode, FMS SPD mode (ECON or EDIT FMS select)

### Steps to reproduce

see descrip

### Expected behaviour

S/B A/T hits and maintains target speed in MACH

### Evidence

![FlightSimulator_2023_11_23_10_01_08_361](https://github.com/invernyx/md11-bugs/assets/148836830/b70cb449-ad16-4605-86c5-6a77f27bffe0)
![FlightSimulator_2023_11_23_10_02_14_251](https://github.com/invernyx/md11-bugs/assets/148836830/21bc10d6-f314-49ff-9da3-84bce5410f44)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

07MT

### Arrival

07MT

### Cruise level

FL300

### ZFW

n/a

### CG

n/a

### Fuel

n/a

### Cost index

n/a

### Route

n/a

### Location

n/a

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved

**Comment by FreakyD777** [comment]
verified
