### ISSUE TITLE
Curved Heading Trend Vector Missing

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#642]
### Describe the bug

The curved heading trend vector arc is not present

### Expected behaviour

When the aircraft is turning, a curved trend vector arc should appear to display where your heading will be in 30, 60 or 90 seconds depending on your range display. Manual reference attached.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/148719444/28a9d06f-b062-4ae9-b562-ba7556c4a8e7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this, correct me if I am wrong, is an option, and will be added as such

**Comment by 017941** [comment]
I didn’t know that it was a customer option. Sorry again. I just know that we had it in the MD-11. Great job as always. Sent from my iPhoneOn Nov 28, 2023, at 3:51 PM, TheFightingRaven ***@***.***> wrote:﻿
this, correct me if I am wrong, is an option, and will be added as such

**Comment by turbofandude** [comment]
Resolved as of 0.47+
