### ISSUE TITLE
[BUG] - EFB Simbrief Set Payload when in LBS

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#643]
### Describe the bug

Set payload errors out due to receiving strings and not numbers

### Steps to reproduce

Load a Flightplan
Set Payload

### Expected behaviour

Payload to be set, no error

### Evidence

`{first: "ArgumentType", second: "Wrong type - expected Number, got String while converting argument 1 for setValueReg_Number"}`

![Screenshot (408)](https://github.com/invernyx/md11-bugs/assets/2170028/aed25398-c88a-4a71-b92e-34e023f0cc7d)
![Screenshot (409)](https://github.com/invernyx/md11-bugs/assets/2170028/5179b88a-5415-4ff0-8d55-2e1e35094762)
![Screenshot (410)](https://github.com/invernyx/md11-bugs/assets/2170028/ab4c9cf1-e5d2-46cb-8559-ce466fbeacf8)
![Screenshot (412)](https://github.com/invernyx/md11-bugs/assets/2170028/b098de60-29d4-4b87-8f8f-edb52d66ef02)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by uwiuke** [comment]
how could you dispatch ? Simbrief username will not be saved - therefore no dispatch possible

**Comment by KJA1582** [comment]
It does save the username.
What happens on a reload that makes it appear it didn’t save is a quirk of CommBus. You solve it by navigating to any other page, I typically use the options page, then navigating back to the dispatch page. It should allow the import then

**Comment by KJA1582** [comment]
Further:

`%appdata%\Microsoft Flight Simulator\Packages\tfdidesign-aircraft-md11\work`

The options files are the save files where your simbrief name is stored as well
