### ISSUE TITLE
[BUG] - EFB Payload page showing Passenger Config in the F model

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#646]
### Describe the bug

EFB Payload page shows passenger and cargo but services show cargo config

### Steps to reproduce

load in to the F model click on payload in the efb it shows passenger and cargo then click on services and and it shows cargo config

### Expected behaviour

For the EFB payload page to show cargo configuration

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 25 - 04 00 45 83](https://github.com/invernyx/md11-bugs/assets/148557328/2dab52f9-f7ea-487f-8c0f-b95853e016b2)
![Microsoft Flight Simulator Screenshot 2023 11 25 - 04 02 03 98](https://github.com/invernyx/md11-bugs/assets/148557328/222fab10-035a-4150-93ba-d5e12c610ffb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

940

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next version
