### ISSUE TITLE
[BUG] - EFB is not saving Simbrief username.

### ISSUE THREAD

**Issue by PBCool1** [invernyx/md11-bugs#647]
### Describe the bug

EFB is not saving Simbrief username.

### Steps to reproduce

After adding my simbrief username then clicking save, "Options Saved!" does show but dispatch page still shows Username is not set.

### Expected behaviour

Simbrief username saves.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by mclovin90** [comment]
Same issue here on the -F

**Comment by shipbiulder101** [comment]
This is data is stored per livery but the saving does not seem to be working correctly anyway as I have a file for OY-KHG when I so far have only used N260UP.

**Comment by mrdyer10** [comment]
agreed, after pressing save and leaving the screen going back and its empty

**Comment by GenericNerd** [comment]
When the next update releases, I will likely need more information about this issue, but for now I believe it may be resolved.

**Comment by Oliverx79** [comment]
v18.0.1 Simbrief Username will not be saved when click the Save boutton in the Options Menu. And in the Dispatch is the Message Username not Set.

**Comment by turbofandude** [comment]
This should be resolved
