### ISSUE TITLE
[BUG] - Cant load state

### ISSUE THREAD

**Issue by tebeso** [invernyx/md11-bugs#648]
### Describe the bug

No matter what state i click on, it will not load any state. If i remember correctly, this worked before the last update (cant say for sure). 

ps: it would be good, if we could manually select, which version we want to install. This way, we could figure it out on our own.

### Steps to reproduce

Load plane, go to EFB and click on any state

### Expected behaviour

State should load for example cold and dark

### Evidence

https://www.youtube.com/watch?v=q3XmNTnJTvw (you can see me clicking cold and dark at 0:16, but nothing happens)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by shipbiulder101** [comment]
Same happening here looks to also be ignoring default state, but that could be because MSFS decided to load me in at the RWY when I selected the ramp.

**Comment by mrdyer10** [comment]
agree nothing happens on selecting a state

**Comment by turbofandude** [comment]
Will be resolved in 0.16+.
