### ISSUE TITLE
[BUG] - EFB MZFW/Empty Weights are still Wrong

### ISSUE THREAD

**Issue by mclovin90** [invernyx/md11-bugs#649]
### Describe the bug

MD-11F MZFW/Empty Weights are still wrong

### Steps to reproduce

Go into EFB and load after Alpha 0.15

They are set to the Combi Weights and not the Freighter weights
MZFW is currently 430,000lbs and not 451,300LBS
Operating weight is set to 283,975LBS when it should be 248,567LBS

### Expected behaviour

Empty weight should be 248,567LBS and MZFW should be 451,300LBS

![281848731-b280be65-ffb5-46bd-968b-889b4bb20a19](https://github.com/invernyx/md11-bugs/assets/97921311/515dad53-4de3-46ea-976c-ee9877c191b6)

### Evidence

![281848731-b280be65-ffb5-46bd-968b-889b4bb20a19](https://github.com/invernyx/md11-bugs/assets/97921311/63f7397a-4ccc-4d43-80cb-c35347718e0f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by Thien42** [comment]
Will be fixed in the next release
