### ISSUE TITLE
[BUG] - Oscillation during climb

### ISSUE THREAD

**Issue by PointBlank66** [invernyx/md11-bugs#651]
### Describe the bug

The plane seems to be fighting between wanting to keep the assigned climbing speed and the assigned thrust setting

### Steps to reproduce

Set up your CDU as normal. Depart via the SID. Make sure autoflight it turned on with nav and prof armed and climb to your assigned flightlevel or TOC

### Expected behaviour

I expect the plane to be keeping the assigned speed _AND_ thrust setting instead of trying to fight and overpower one or the other.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Bank

None

### Heading

Southward following KUDAD2V

### Altitude

Climbing to FL330

### Departure

EHAM

### Arrival

DGAA

### Cruise level

330

### ZFW

192044 KG

### CG

7.9

### Fuel

60281 KG

### Cost index

100

### Route

EHAM/36L KUD2V WOODY N872 MEDIL UN872 LESDO UM728 KETEX DCT KOTIS DCT KUKOR DCT ADEKA DCT MOKDI DCT MEN DCT BADAM DCT KANIG UN855 GENIO UN859 MOGIL UB31 ZEM/N0483F340 UB726 NSL UG859 BAKAB UA603 LITEX LIT1B DGAA/ILS21

### Location

Happened during climb, I think it was noticeable the most around FL160 and past waypoint AM072

### Agreement

- [X] Yes

**Comment by Zeflyingfrog** [comment]
I had the same issue. Freighter version, weight around 265t. Similar issue in the lower FL (below FL200), quite a pronounced oscillation when the AP slightly overshoots the FD pitch commands (visible on the controls too. AP commands large up then down pitch inputs.). It seem to stabilize (or be less noticeable) as the climb carries on.
