### ISSUE TITLE
[BUG] - Hydraulic test don't work since update 0.15.01

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#652]
### Describe the bug

Hydraulic test isn't working anymore

### Steps to reproduce

I try it with several liveries and with both versions of the airplane (PAX and Cargo) - same behaviour

### Expected behaviour

after starting the airplane and connected to the GPU and/or APU the hydraulic test should start with cklick the corresponding button on the overhead panel.

### Evidence

not avialable (I just could show the overhead panel without the blue test light on the button)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

n/a

### Agreement

- [X] Yes

**Comment by tomkaare** [comment]
I have the same issue. 
I'm unable to set the hydraulic panel out of manual and I'm therefore unable to run the hydraulic test. 
After engines are running the hydraulic panel can be switched out of manual as normal.

**Comment by TheFightingRaven** [comment]
this is not this bug, the bug is the panelstates are broken, which spawns you with the engines off but fuelcutoff to run which trips the hydraulic system to manual.
