### ISSUE TITLE
[BUG] - Slams back to runway after rotate en Hard right to end 

### ISSUE THREAD

**Issue by KevMD11** [invernyx/md11-bugs#653]
### Describe the bug

Plane falls down back to the runway after rotation and ends up going hard right

### Steps to reproduce

- Starts plane up in Cold and dark stage
- Loading the plane as before
- Startup, push back and taxi works fine
- Takeoff power is set on runway as before, working for me 
- initial Rotation works at VR speeds
- But slams down nose up back to the runway 
- Recovering seems to work at first but slams back down and goes hard right without any reaction to your input
* Using a Boeing yoke en throttle/ and tried different weights and balances  

### Expected behaviour

Before the latest update 0.15 it worked fine for me  

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by skipz3r** [comment]
I am getting the same issue in 0.15, left wing dip right after rotation requires full defection of the right aileron to prevent roll, tried it with 2 diffrent controllers.

**Comment by joon44** [comment]
This is fixed
