### ISSUE TITLE
[BUG] - LNAV skpis last SID waypoint 

### ISSUE THREAD

**Issue by zulugolfalpha** [invernyx/md11-bugs#654]
### Describe the bug

After depature in Frankfurt a/c followed depature route as planned. However the FMS computed the flight path without to pass the last SID waypoint MARUN. Instead i got a direct from LORPA to UVANO. The FMS display showed the waypoint MARUN.

### Steps to reproduce

Depature EDDF RWY 25C SID: MARUN7M

### Expected behaviour

The aircraft should follow all waypoints and not skip any of them. 

### Evidence

![Microsoft Flight Simulator Screenshot 2023 11 25 - 14 15 14 79](https://github.com/invernyx/md11-bugs/assets/118537653/d8082776-6039-4ab7-a9eb-ecd9919c973f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

FL247

### Departure

EDDF

### Arrival

EKCH

### Cruise level

FL330

### ZFW

204,022 kg

### CG

%

### Fuel

18,835 kg

### Cost index

176

### Route

EDDF/25C N0484F330 MARU7M MARUN Y150 TOLGI DCT ELKIM DCT MAKEL N851 GESKA Z711 MONAK MONA3A EKCH/04

### Location

Germany, next to the city of Marburg. 

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved, and if not, will be by new updates
