### ISSUE TITLE
[SUGGESTION] - Engine sounds

### ISSUE THREAD

**Issue by Pilot777x** [invernyx/md11-bugs#655]
### Is your feature request related to a problem? Please describe.

The engine sounds outside are spot on for the GE's but in the cockpit it really doesnt give me the feeling of flying an md11 nor a powerfull machine.. 

### Describe the solution you'd like

Better cockpit engine sounds to immerse the pilot enough to sit an enjoy sounds on long hauls. The longer the airplane can fly the better the sounds should be :)

### Describe alternatives you've considered

None

### Additional context

https://youtu.be/VT5SZS7ejI0?si=TfDrGm7yFWPSz_FW

**Comment by Pilot777x** [comment]
Well, i must disagree with you there. The only difference would be tone. The sounds like they are now are completely different of what it should be. Ive flown jumpseat alot. This is not what it sounds like.

**Comment by turbodeas** [comment]
I would also add here that the GE engine sounds need some work.

For context, I am a former studio engineer/record producer who used to pax up front on MD11's from AMS-MSP a lot in the early 00's - I am fortunate enough to have a studio grade monitoring setup that I can listen on, and a good memory for how these birds should sound. Unfortunately, I wish I took some high quality recordings back in the day - so Youtube will have to do, much as it's not the best quality. I'm also aware that cockpit sounds are not exactly the same, but having jumpseated on a couple of smaller jets, I'd say that a 'forward of the wing' sound but with a slightly lower level than in the cabin would create a great impression.

- The CF6 is a big, powerful engine, and at the moment the TFDI internal sounds just sound a bit weak and indistinct. Here's a clip of a similar CF6 engine on a 767, which captures the essence of what i'm talking about: [LINK](https://www.youtube.com/watch?v=fLSP3saDpGk&t=89s)

- Here's a rare clip of an MD11 taken from the cabin - you can hear the powerful engine sound with clear buzzsaw on takeoff, as well as the loudness of the A/C Packs throughout the cabin: [LINK](https://www.youtube.com/watch?v=o-xGz4MCuWw)

- IRL, the vibrations from the engines travel through most of the fuselage, creating the sensation of a lot of low end/bass, especially during startup and TO power settings: [LINK](https://youtube.com/clip/Ugkx9PeIBT_3bYnwvfVB23IXPt0B1qVC69-N?si=m25_C8b_RpIy38Iw)

- Behind the wing, the buzzsaw sound should not be as audible, but there should be a loud, bassy 'roar', as can be evidenced here. The MD11 is of course slightly different, as everyone is always in front of ENG2, meaning there should always be a little foward engine sound audible.:[LINK](https://youtube.com/clip/UgkxkVvG2SoaFNWwqaT-C9nPWqg-zvy3YQhV?si=SIM36-DIKqjdbP2x)

- The engine sounds should have a Lowpass filter applied with increasing TAS and alt - above FL250, with TAS of >300, all that should be heard of the engines is <200hz, with the rest of the soundscape being taken up with airflow around the fuselage.

**Comment by Pilot777x** [comment]
Thank you turbodeas!

**Comment by HV7572KC** [comment]
Goodday, turbodeas added some really good points, and I like to add some additional stuff (mainly from the cabin from some recordings I made on Finnair and KLM MD11s. Just to contribute, in case you might update the soundpack someday :-)

I'm very satisfied so far, the 11 is getting better every week! I'd say keep up the excellent work and let's all contribute to the best FS aircraft of the future!

[https://youtu.be/3DlbcP58OXg?si=sphiGcp-FpuXhged](url) the very slow taxiing of the plane starting around 1:10 .

And this from just behind the wing during taxi [https://youtu.be/owsRhU_nq8Y?si=obu1oy72G7hAmOCR](url) even if it is to update the sound from inside the cabin as more realistic. I don't want to compare different Aircraft but this is a job FSLabs has done great in P3D on their aircraft, I'd say challenge accepted ;-) The sound I mean starts around 1:30.

As you can here from business class I think I was in row 4 if I remind correctly, this sounds different, so getting closer to the cockpit sound you now profided [https://youtu.be/EYDShxSBVrw?si=KTDsT2IM7jixp7Lq](url) starting at 3:30.

Takeoff from the same seat starting at 0:55 [https://youtu.be/yq8lC6V6maw?si=oG23lOxxIPv_7Qkv](url)

Then the engine-start, very specific sound for the CF6s at 3:55 [https://youtu.be/QSBlWi6fnOs?si=o8pUksBlBbuNvCFN](url) and its takeoff roll from 5:22 I've been flying on the flightdeck on some takeoffs and landings as well. This sound is the same in front, its a bit more silent as you are further away from the engines, but the sound doesnt change. Mostly some more noise of the air-circulation up front. But yes, this is my best MD-11 takeoff-recording, followed by this one [https://youtu.be/RMR8--WCKZg?si=4F9NPBh1kmrM-9Vq](url)

A Lufthansa-Cargo takeoff from the cockpit in where you can hear the same [https://youtu.be/I1hababCY18?si=m0d_8Kri1llzv8b7](url)

Then I flew into Quito on high altitude which quite some full throttle to idle moments in this movie [https://youtu.be/lEi6qaDF44o?si=G03ow4V3LaTlx7As](url)

Then there is this howling sound I heard on most of my landings. Maybe its the activation of the thrust-reverser Im not sure. At exactly 4:39 [https://youtu.be/kw9QnuNgQPg?si=1z2kIPDlMcSzrSGn](url)

From the exterior I say its almost there, only when engines run idle you should hear the howly just a little better, I can hear it on the TFDI, but its a little to weak I think, on 1:55 [https://youtu.be/3hQRlpSLUrM?si=982fMcxnQS_7IxfG](url)

**Comment by GenericNerd** [comment]
The sounds have been updated rather extensively since this issue has been open. As new builds come out, have a new listen :)
