### ISSUE TITLE
[BUG] - V-15  Ready To Fly Mode

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#656]
### Describe the bug

There are still a number of lights on the overhead that are not extiguished when you are in READY TO FLY mode in the tablet

### Steps to reproduce

Load up MD-11 in Ready to Fly Mode

### Expected behaviour

EMER PWR light is on
IRS NAV lights are OFF
ENG Ignition Not Armed
ATT Fail on on the EHSI
Cargo Flow
(See Attached Photo)

### Evidence

![Panel](https://github.com/invernyx/md11-bugs/assets/150555279/3bf75862-70b5-4e13-a477-4f6c25f85598)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

On Ground

### Agreement

- [X] Yes

**Comment by tebeso** [comment]
I do have the same problem

**Comment by TheFightingRaven** [comment]
#648
