### ISSUE TITLE
[SUGGESTION] - Change colors on service tab for doors

### ISSUE THREAD

**Issue by crazyforiphone** [invernyx/md11-bugs#657]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Instead of the doors being red for closed, I think red should be for open like we have with the ground services being connected. 

### Describe alternatives you've considered

n/a

### Additional context

having the doors as green for being open and the ground services as green for being disconnected is confusing. Green should mean safe for flight while red should mean it is not safe. Either way, the coloring on the ground services status should match the coloring on the door status in terms of if the plane is ready for pushback (all green) or not (red)

**Comment by GenericNerd** [comment]
Will be changed in the next version of the EFB
