### ISSUE TITLE
[BUG] - EFB text Resolution

### ISSUE THREAD

**Issue by mrdyer10** [invernyx/md11-bugs#658]
### Describe the bug

EFB text unreadable small at 4K monitor resolution

### Steps to reproduce

every time I load the MD-11, have reinstalled in every build from zero

### Expected behaviour

expecting text size to be bigger matching the EFB pictures TFDI shared.

### Evidence

![Microsoft Flight Simulator - 1 34 16 0 11_26_2023 5_02_48 PM_resized](https://github.com/invernyx/md11-bugs/assets/152104889/2df11253-83d7-4001-af48-8e67305fcd2b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Thien42** [comment]
The next EFB update will bring some UI improvements that should mitigate this problem.

If the issue persists, feel free to re-open it with more information.
