### ISSUE TITLE
[BUG] - GEN DRIVE DISC overlaps text on ELEC display

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#66]
### Describe the bug

When disconnecting a generator drive and going to the ELEC display, it will overlap DISC text over the numbers.

### Steps to reproduce

1. Load aircraft
2. Disconnect a generator drive with engines running
3. Go to ELEC display
4. Observe overlap

### Expected behaviour

Text on the ELEC panel when disconnecting a generator drive is not supposed to overlap.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48654776/a3c1b8c9-a3a0-4bd6-9f14-2953a1d1a204)

### Simulator

P3Dv4

### Crash

None

### Agreement

- [ ] Yes

**Comment by TheFightingRaven** [comment]
fixed
