### ISSUE TITLE
NEW annunciator light test issues

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#661]
### Describe the bug

Errant lights after Annunciator light test

### Expected behaviour

After the annunciator light test there should be no residual and inaccurate lights left on. However, the following lights are now illuminated:
![image](https://github.com/invernyx/md11-bugs/assets/148719444/75b15d33-17b0-431f-9860-46aae58fd878)

![image](https://github.com/invernyx/md11-bugs/assets/148719444/dfe47f0c-d1f4-48d8-a733-58dae4c97619)

### Evidence

https://clipchamp.com/watch/M88qZSZvZDx

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.24+
