### ISSUE TITLE
Voice recorder should test in the green band

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#663]
### Describe the bug

Voice Recorder test button does not test in the green band

### Expected behaviour

When pressing the voice recorder test button the voice recorder should test in the green band,

### Evidence
![image](https://github.com/invernyx/md11-bugs/assets/148719444/512cd20d-85f5-4532-a0e7-6e9338a8facc)

![image](https://github.com/invernyx/md11-bugs/assets/148719444/d8cf1cda-90bc-43ae-88ee-6cd2bcd0cb87)
_No response_

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by Willmus11** [comment]
this CVR works by doing 4 voice channels test, by pressing and holding the test button you should see te needle up for approx 2sec then down for 2sec doing it 4 times

**Comment by 017941** [comment]
> this CVR works by doing 4 voice channels test, by pressing and holding the test button you should see te needle up for approx 2sec then down for 2sec doing it 4 times

![image](https://github.com/invernyx/md11-bugs/assets/148719444/8caf38eb-0261-425d-99fc-616dccb6fe42)

**Comment by 017941** [comment]
> this CVR works by doing 4 voice channels test, by pressing and holding the test button you should see te needle up for approx 2sec then down for 2sec doing it 4 times

![image](https://github.com/invernyx/md11-bugs/assets/148719444/092a1a37-7d00-480b-822d-b0324b755c8a)

**Comment by 017941** [comment]
> this CVR works by doing 4 voice channels test, by pressing and holding the test button you should see te needle up for approx 2sec then down for 2sec doing it 4 times

Thank you!!!! I think you're right. Here are my references

**Comment by turbofandude** [comment]
@jhattermann This is coded now and I've sent you the tags.

**Comment by turbofandude** [comment]
Long since resolved
