### ISSUE TITLE
GPWS guarded cover does not move.

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#664]
### Describe the bug

The GPWS red-guarded cover does not move

### Expected behaviour

When moving the GPWS to flap OVRD, you must first move the red guard. At the moment, you can only move the switch and the cover remains stationary.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Dimples82** [comment]
![FLAP OVRD](https://github.com/invernyx/md11-bugs/assets/153389460/670b086b-505c-47ed-bd71-0cc96fc235d6)

**Comment by GenericNerd** [comment]
This will be fixed in the next version
