### ISSUE TITLE
Fuel quantity test inop

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#665]
### Describe the bug

the fuel quantity test does not work

### Expected behaviour

I have attached a photo of the FOM Normal procedures for the Fuel System Test. 
With the FUEL SYSTEM IN AUTO (not manual), when pressed, each gage should initially read 188880 followed by 10500 in each gage. Totalizer on SD should read 52400.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
