### ISSUE TITLE
[BUG] - EFB doesn't save digital standby option to options.livery.json

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#667]
### Describe the bug

Selecting the desired option for the digital standby on the EFB doesn't save the value to options.livery.json and always reverts back to the default selection of the digital version even if the analog was selected and saved.

### Expected behaviour

Selecting the analog version and reloading the aircraft should keep the selected options.

### Evidence

{
	"options": {
		"simBriefUsername": "xxx",
		"fuelDipstickEnabled": true,
		"wbsInstalled": true,
		"showRadioAltitude": true,
		"rcwsEnabled": true,
		"tapeDisplays": false,
		"singleCueFD": false,
		"highDecelRateAbs": false,
		"inhibitTireFailureDuringToLdg": true,
		"autoAntiIce": false,
		"extendedRange": false,
		"hardwareOverforce": false,
		"fuelCgControlPct": 3.0,
		"to1Derate": 10,
		"to2Derate": 20,
		"clb1Derate": 10,
		"clb2Derate": 20,
		"ga1Derate": 10,
		"ga2Derate": 20,
		"ndObjectRange": 4,
		"defaultState": "ColdAndDark",
		"irsAlignTime": "Realistic",
		"tempUnit": "Celsius",
		"weightUnit": "Metric",
		"windVectorType": "Track"
	}
}

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.16.0.1+
