### ISSUE TITLE
[BUG] - Panel Resets after entering data in FMC

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#668]
### Describe the bug

Panel Resets

### Steps to reproduce

Start flight with the MD-11F. in Ready To Fly Mode. EHSI goes back to ATT FAIL and Upper Panel Resets to the Start up Ready To Fly mode after Programing FMC and MCP when you advance throttles. 

### Expected behaviour

.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Takeoff

### Altitude

on runway

### Agreement

- [X] Yes

**Comment by tebeso** [comment]
Have the same when advancing throttles (you can see it in my video here https://www.youtube.com/watch?v=q3XmNTnJTvw )

**Comment by rsmith6621a** [comment]
tesbo. I am glad I am not the only one with this issue.

**Comment by TheFightingRaven** [comment]
this is not the issue you think it is, the "NAV" IRS lights are on, denoting they aren't fully aligned, it's erroneously displaying "taxi" on the speedtape. This all is a symptom of the panelstates not working anymore

**Comment by rsmith6621a** [comment]
Version 15.

I have my panel state set to READY TO FLY, and the IRS setting in the
tablet to instant.

When I go to the overhead the IRS knobs are turned OFF. With the RTF state
set shouldn't those knobs and IRS alignment be completed instantly?

Regards
Randall

**Comment by rsmith6621a** [comment]
With the RTF state set shouldn't those knobs be in NAV position and IRS
alignment be completed.

**Comment by GenericNerd** [comment]
I've not been able to reproduce this issue. Has it been fixed already?
