### ISSUE TITLE
[BUG] - PFD ND and EAD displays are all shrunk in P3D

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#67]
### Describe the bug

When using P3D, the PFD, ND and EAD all appear to be smaller than in MSFS.

### Steps to reproduce

1. Load the aircraft in P3D
2. Observe smaller display screens

### Expected behaviour

The display screens are supposed to be the same size as MSFS.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/48654776/c933f55f-29d3-4352-b14a-716ee9110abc)
![image](https://github.com/invernyx/md11-bugs/assets/48654776/538fe9ee-0edf-4b2d-a786-f30cda10ca6b)

### Simulator

P3Dv4

### Crash

None

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
This is a panel.cfg issue, the screens are mapped identically in both sims

**Comment by turbofandude** [comment]
Resolved in 0.28+
