### ISSUE TITLE
[BUG] - AUTO IGN behavior

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#671]
### Describe the bug

With ENG IGN A/B engaged, the blue MANUAL light is shown all the time indicating that the automatic ignition has failed.

### Expected behaviour

Only A or B shown in normal mode.

### Evidence

![Screenshot_2023-11-30-08-21-18-46_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/invernyx/md11-bugs/assets/102414406/6c453ffa-3fbd-4e94-aa65-60534ebc3906)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Also the cyan lightning symbol on the EGT display lights up only during engine start. It should light up always when the automatic ignition is on.
![image](https://github.com/invernyx/md11-bugs/assets/102414406/2624b411-d2e5-45d6-92a6-1e88f659a8e8)

I do not know if it should light up always with the ignition on manual mode but that would make sense.

**Comment by turbofandude** [comment]
The auto-ignition behavior will be correct in 0.24+
