### ISSUE TITLE
[BUG] - no path error values during descent

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#673]
### Describe the bug

no values for the path error on the DES PAGE

### Steps to reproduce

no values during the last 3 flights during the descent phase.

### Expected behaviour

If the VNAV profile shows a deviation on the PD there is no corresponding value on the DES PAGE for the path errors.

### Evidence

![Screenshot 2023-11-30 184339](https://github.com/invernyx/md11-bugs/assets/83859593/3ea4f441-d1b1-43e1-b4b2-903e7a6521ea)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

n/a

### Departure

KOMA

### Arrival

KCLT

### Cruise level

FL410

### ZFW

166900 kg

### CG

30

### Fuel

20500

### Cost index

55

### Route

KOMA SID VECT1 DCT LMN DCT SPI DCT IIU DCT TAFTT DCT KCLT

### Location

n/a

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.63+
