### ISSUE TITLE
[BUG] - ILS Approach ends in Crash on Ground

### ISSUE THREAD

**Issue by Oliverx79** [invernyx/md11-bugs#675]
### Describe the bug

ILS Approach Ends in Crash MD11 will be Unflyable in Final Sector

### Steps to reproduce

Flying ILS Approach on Rwy 26L at EDDM, in Final sector approx 2000ft high the AP disconected and the Plane dives and turn hard right. And is manual not recoverbel. 
Plane set in Landing Config, Flaps 50 Speed 10 kts over Appr. Speed (157kn) 
I had this problem in earlier versions too but with 15.0.1 it was left and is now back aggain. 

### Expected behaviour

Normaly await that the Plane follows the ILS for an Autoland Appr. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Pitch

5 or 7 

### Bank

0

### Heading

261

### Altitude

2000ft

### Departure

LEMG

### Arrival

EDDM

### Cruise level

380

### ZFW

141.3 tons

### CG

25

### Fuel

24.2 tons

### Cost index

25

### Route

BLN4H BLN UL27 YAKXU UN871 TOPTU TOU GAI MEN NINUN UN871 OMASI N871 DITON T103 BETOS BETO1B with Rnav Bet26 transition

### Location

3 miles Final Rwy 26R EDDM

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#366
