### ISSUE TITLE
Sim freeze when selecting DIRECT TO a waypoint in flightplan

### ISSUE THREAD

**Issue by tomkaare** [invernyx/md11-bugs#676]
### Describe the bug

When selecting DIRECT TO on a waypoint in the flight plan the entire simulator froze. Unlike previous bug in FMS when the WASM would crash this caused the whole simulator to freeze and become unresponsive. Normally when selecting DIRECT TO a waypoint the magenta line will disappear for a moment, it was on this moment the simulator froze.

### Steps to reproduce

Fly a route with multiple waypoints and go DIRECT TO.

In this route i went DIRECT TO from ARGES to BEGLA
LUBET1E LUBET L934 DAVUS L602 TASMI UL602 GADSI UM860 ODALI UL852 NEGEM/K0906F320 T746 ARGES/N0489F320 DCT DEGET DCT VEBOS DCT BEGLA DCT DITIS DCT RAPET T170 VAGAB/N0477F240 T170 GAPLA T178 KERAX KERAX4C

### Expected behaviour

Not freeze the simulator.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/71843153/e7ede5b5-4ea3-4d4d-b8d7-a939fffb37a5)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

FL320

### Departure

OTHH

### Arrival

EDDF

### Cruise level

FL320

### ZFW

206.5t

### CG

17.6

### Fuel

27.5t

### Cost index

200

### Route

LUBET1E LUBET L934 DAVUS L602 TASMI UL602 GADSI UM860 ODALI UL852 NEGEM/K0906F320 T746 ARGES/N0489F320 DCT DEGET DCT VEBOS DCT BEGLA DCT DITIS DCT RAPET T170 VAGAB/N0477F240 T170 GAPLA T178 KERAX KERAX4C

### Location

Between ARGES and BEGLA

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
has this happened more than once?

**Comment by tomkaare** [comment]
I completed a flight on 0.18 this weekend and i didnt experience the same issue.
Altough this was not the same route, i did a direct and didnt get a freeze.
