### ISSUE TITLE
[BUG] - engines forced on when starting on the runway disregarding the panelstate

### ISSUE THREAD

**Issue by tebeso** [invernyx/md11-bugs#677]
### Describe the bug

Loading Cold and Dark State starts several systems

### Steps to reproduce

When clicking on Cold and Dark, the aircraft goes dark for a few seconds and then proceeds to start up several systems. This usually happens, when loading the sim (and the fact that cold and dark is my default) and when clicking on the cold and dark state. If i click on something else (like ready to fly) and then go back to cold and dark, it sometimes works as expected.

### Expected behaviour

Everything should be still dark

### Evidence

https://youtu.be/Ct3SzxdiEYQ

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is not the issue you think it is, starting on the runway forces the engines on, which then drives the generators etc.
