### ISSUE TITLE
[BUG] - Ready to Fly state has several amber systems

### ISSUE THREAD

**Issue by tebeso** [invernyx/md11-bugs#678]
### Describe the bug

Ready to Fly state has several amber systems like "TRIM AIR OFF", "EMER PWR ON" (despite having all engines on and Emer Pwr Switch to ARM -> switching this off and arm again fixes this), whole ELEC pannel is off (going to manual and back fixes this)

### Steps to reproduce

Click on "Ready to Fly"

### Expected behaviour

Every system should be ready to fly and no amber messages should appear

### Evidence

https://youtu.be/u5U9ilcNqCg

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.41+.
