### ISSUE TITLE
[SUGGESTION] - The uninstall function in the updater should have a confirmation dialog

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#679]
### Is your feature request related to a problem? Please describe.

Permanent actions with 1 click are a bad idea.

### Describe the solution you'd like

![th](https://github.com/invernyx/md11-bugs/assets/7919184/f0170ce8-d01d-45a0-811a-42dcc75d2fb9)

### Describe alternatives you've considered

![confirmation](https://github.com/invernyx/md11-bugs/assets/7919184/b63fa39e-4f29-4d57-9820-c92589c0f570)

### Additional context

![th](https://github.com/invernyx/md11-bugs/assets/7919184/443ebb9e-90d0-404d-b390-08a65a2c6a00)

**Comment by turbofandude** [comment]
This is now in the installer.
