### ISSUE TITLE
[BUG] - AIR System Controller Requires Reset To Function Properly

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#681]
### Describe the bug

On initial start-up, if you do not re-cycle the Air System Controller, the panel will not function properly in the automatic setting.

### Steps to reproduce

1. Cold and Dark
2. Complete normal preflight through Starting Engines (APU Air ON without cycling APU Sys Controller).
3. Pull Engine 3 (or 1/2) Starter
4. Observe no N2 on applicable engine
5. Re-cycle Air System Controller
6. Engine starter now as proper air and begins to turn

### Expected behaviour

The Air System Controller should function in the automatic mode upon power-up without intervention. It should open the 1-2 and 1-3 ISOL valves to provide air to all three packs (something else it does not do unless cycled).

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

NA

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@turbofandude believe this is a redundant issue and no longer the case as of v0.22+

**Comment by turbofandude** [comment]
Resolved in 0.25+
