### ISSUE TITLE
[BUG] - No CARGO DOOR Test (-11F)

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#682]
### Describe the bug

Cargo Door test should initiate when the first fuel switch is placed to ON

### Steps to reproduce

1. Cold and Dark
2. Initiate all checklists up to Starting Engines
3. When placing first fuel switch to ON, observe no CARGO DOOR TEST

### Expected behaviour

The CARGO DOOR Test is automatically performed when the first fuel switch is placed in the ON position.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved
