### ISSUE TITLE
[BUG] - Aux Hydraulic Pump Remains ON After Engine Start

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#683]
### Describe the bug

After starting engines, the Aux Hydraulic Pump should turn off once the engine-driven pumps generate enough pressure.

### Steps to reproduce

1. Cold and Dark
2. Turn Aux Hyd Pump ON as part of Before Starting Engine procedure
3. Start engines normally
4. Observe Aux Hyd Pump remains ON

### Expected behaviour

After starting engines and engine-driven hydraulic pumps supplying system pressure, Aux Hydraulic pump should be automatically turned off.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

NA

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.23+
