### ISSUE TITLE
[BUG] - Unable to Overwrite Transponder Code

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#684]
### Describe the bug

Unable to put in a new transponder code without first clearing the existing code

### Steps to reproduce

Transponder on, TA/RA
Attempt to type in new code, ie. "3333".
Transponder will continue to display default code "2000".
Pressing CLR and clearing the code will then allow new code entry.

### Expected behaviour

Beginning to type in a new transponder code at any point should clear the display and begin accepting new digits.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by SamuelSamouris** [comment]
I am also experiencing this issue.

**Comment by GenericNerd** [comment]
This will be fixed in the next version
