### ISSUE TITLE
[BUG] - PROG page WIND is wrong

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#685]
### Describe the bug

PROG page shows wind direction but not speed

### Steps to reproduce

Check the actual wind vs PROG page wind values

### Expected behaviour

Wind speed must be shown

### Evidence

![FlightSimulator_UrH4Ua0vqA](https://github.com/invernyx/md11-bugs/assets/102414406/3b1f6964-9757-4906-932a-21dcfc3db235)

Notice the difference between the actual wind shown on the ND and on the PROG page.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

EFHK

### Arrival

EDDF

### Cruise level

FL360

### ZFW

195.0 tn

### CG

12.5%

### Fuel

22000KG

### Cost index

70

### Route

EFHK04R NUNT4C NUNTO Y369 REKDO KOSKA REMSA SALLO ROSOK T906 RARUP RARU5A EDDH05

### Location

Over the Baltic sea

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.30+
