### ISSUE TITLE
[BUG] DTG PROG FMS Page

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#686]
### Describe the bug

The DTG starts and stops counting down the miles to go.

### Steps to reproduce

Load up flightplan and go fly.  It does not countdown the miles left in route from time to time. It seems like it sticks

### Expected behaviour

NA

### Evidence

![DTG](https://github.com/invernyx/md11-bugs/assets/150555279/45f7030e-cf82-4e79-9116-bdad71260d68)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Departure

EDDM

### Arrival

KLAX

### Cruise level

FL340

### ZFW

294.7

### CG

NA

### Fuel

234.0

### Cost index

20

### Route

EDDM/08R N0482F340 INPU3E INPUD Y102 ALIBU L604 RELBI L602 RKN L980 TENLI L602 SUPUR P1 GODOS M981 NATEB N97 TLA L602 GOW DCT ERAKA/M082F360 NATA URTAK/N0473F360 DCT LAKES DCT DUSMA/N0476F380 DCT ELVEL DCT VBI/N0475F400 DCT KP09A DCT DPR DCT RAP DCT KU54Q DCT BAWER DCT LAKRR Q98 HAKMN ANJLL4 KLAX/25R

### Location

On the AnJLL4 Arrival into KLAX

### Agreement

- [X] Yes

**Comment by nickjzx** [comment]
I'm not sure why but I notice that it will update for several seconds and then freeze. I'm not touching anything in the cockpit and it will randomly come alive.

**Comment by turbofandude** [comment]
This was a symptom of another bug in leg progress detection. Resolved in 0.30+
