### ISSUE TITLE
Nose wheel steering going wild

### ISSUE THREAD

**Issue by LucaSklenar** [invernyx/md11-bugs#687]
### Describe the bug

The nose wheel steering interrupts when steering left.

### Steps to reproduce

Try steering left with a Thrustmaster Airbus Sidestick.

### Expected behaviour

The nose wheel steering will interrupt. 

### Evidence

The video is to large to attach it. Can send it via email.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

ground (240ft)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
can you maybe upload it to youtube and send a link of it?

**Comment by TheFightingRaven** [comment]
did you command that left right left right nose input? Have you tried a different axis? Might be a hardware issue
