### ISSUE TITLE
[BUG] - T/C Prediction Significantly Off

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#689]
### Describe the bug

The Top of Climb prediction point is significantly off from actual performance,  aircraft reaches planned level between 15-25 miles ahead of FMS-predicted point.

### Steps to reproduce

Observe aircraft actual level-off vs T/C prediction point

### Expected behaviour

FMS T/C calculations are very accurate in the aircraft, the actual top of climb and the FMS-predicted T/C should be coincident.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved with 0.36+. We will continue to refine performance predictions over the coming weeks.
