### ISSUE TITLE
[BUG]  DTG displays -NAN on PRG Page

### ISSUE THREAD

**Issue by rsmith6621a** [invernyx/md11-bugs#690]
### Describe the bug

Instead of a number underneath the DTG display. It shows -NAN on PRG Page

### Steps to reproduce

Enter flight plan and go fly. The DTG seems to be a generally buggy feature. 

### Expected behaviour

It shows -NAN

### Evidence

![NNAN](https://github.com/invernyx/md11-bugs/assets/150555279/b74ac65b-fc17-4c27-8ac5-9e9f9d9077d1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

380

### Departure

VHHH

### Arrival

ZULS

### Cruise level

FL380

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

VHHH/07R K0913S1160 DCT TAMOT DCT POU A599 LBN/K0904S1220 A599 SGM DCT DCH W9 DUMIX DCT UGOVA DCT DM DCT LXA DCT ZULS/27R

### Location

In flight the entire route

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.30+
