### ISSUE TITLE
[BUG] - Waypoint ETAs Displayed Below Points On ND

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#691]
### Describe the bug

On the ground, waypoint ETEs are displayed below each waypoint on the ND. Once in the air, these switch to ETAs. They should not be present at all.

### Steps to reproduce

Observe ND once a flightplan is loaded and IRUs are aligned.

### Expected behaviour

Waypoint data on ND should include Name, Altitude Constraint (as required), Speed constraint (as required) with no additional data. It appears altitude/speed was added, as well as ETA/ETE.

### Evidence

![ETA](https://github.com/invernyx/md11-bugs/assets/123108304/70377a79-83f3-490c-95a3-81d507c5db01)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved with 0.36+.
