### ISSUE TITLE
[BUG] - PROF Descent Not Maintaining Within 20 Knots

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#693]
### Describe the bug

When descending in PROF, aircraft prioritizes profile above any airspeed

### Steps to reproduce

Adjust descent speed lower (ie 300 kts) to induce  profile overshoot
Descent at T/D in PROF
Observe aircraft maintain PROF despite going well beyond 20 knots of selected descent speed

### Expected behaviour

In PROF, aircraft should prioritize profile within 20 knots of FMS speed. Once it reaches that threshold, aircraft should adjust pitch to remain within 20kt threshold.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be resolved with 0.36+.
