### ISSUE TITLE
[BUG] - Stepclimbs enroute is not working appropriate

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#696]
### Describe the bug

New flight level (stepclimb) - rate to rise is too high

### Steps to reproduce

If you do a stepclimb enroute (e.g. FL310 to FL330) the airplane climb with a rate of more than 2000 ft/min. Therefore the speed decrease permanently.

### Expected behaviour

The climbing rate during a step climb enroute should  be as low as the actual speed doesn't decrease during the climb phase.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

6 degree up

### Bank

0

### Heading

083

### Altitude

31000

### Departure

KDFW

### Arrival

EDDS

### Cruise level

FL310

### ZFW

186000 kg

### CG

22

### Fuel

55000 kg

### Cost index

85

### Route

KDFW/18L N0489F310 AKUNA9 MLC DCT FAM DCT VHP DCT DJB/N0486F330 DCT JHW DCT KB78A DCT EBONY DCT NICSO/M083F350 NATU GISTI/N0471F350 DCT BAKUR/N0471F370 DCT OKSAW DCT KONAN UL607 KOK M150 KRH T128 BADSO BADS2A EDDS/07

### Location

north atlantic

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is because stepclimbs are not modelled, you can see it instantly triggers hold mode not climb mode therefor normal climb performance isn't followed

**Comment by turbofandude** [comment]
Should be resolved in 0.46+
