### ISSUE TITLE
[BUG] - Duplicate Key Name on file panel engine cfg

### ISSUE THREAD

**Issue by SimbiosiGT** [invernyx/md11-bugs#697]
### Describe the bug

while compile from 3ds max got this error

### Steps to reproduce

Found Duplicate Key Name
File:file:///C:/GitHub/md11-msfs-project/PackageSources/SimObjects/Airplanes/TFDi_Design_MD-11_GE/engines.cfg
Section:GENERALENGINEDATA
Key:ThrustAnglesPitchHeading.0

Duplicate Section Name
File: file:///C:/GitHub/md11-msfs-project/PackageSources/SimObjects/Airplanes/TFDi_Design_MD-11_GE/panel/panel.CFG
Section : Color

Found Duplicate Key Name
File:file:///C:/GitHub/md11-msfs-project/PackageSources/SimObjects/Airplanes/TFDi_Design_MD-11F_GE/engines.cfg
Section:GENERALENGINEDATA
Key:ThrustAnglesPitchHeading.0

Duplicate Section Name
File: file:///C:/GitHub/md11-msfs-project/PackageSources/SimObjects/Airplanes/TFDi_Design_MD-11F_GE/panel/panel.CFG
Section : Color

### Expected behaviour

while compile from 3ds max

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [x] Yes

**Comment by turbofandude** [comment]
Fixed
