### ISSUE TITLE
[BUG] - PERF DES PAGE - Transition Level not editable

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#698]
### Describe the bug

Not able to input a different transition level in the DES PAGE

### Steps to reproduce

It's not able to input another value for the transition level instead of the existing one 

### Expected behaviour

input the transition level value like indicated from ATIS of the destination airport

### Evidence

n/a

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

370

### Departure

KDFW

### Arrival

EDDS

### Cruise level

FL370

### ZFW

186000 kg

### CG

22

### Fuel

9,3

### Cost index

75

### Route

KDFW/18L N0489F310 AKUNA9 MLC DCT FAM DCT VHP DCT DJB/N0486F330 DCT JHW DCT KB78A DCT EBONY DCT NICSO/M083F350 NATU GISTI/N0471F350 DCT BAKUR/N0471F370 DCT OKSAW DCT KONAN UL607 KOK M150 KRH T128 BADSO BADS2A EDDS/07

### Location

short of Top of Descent

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@GenericNerd 
FCOM: "The transition altitude of the destination (from the nav database) is displayed at lower left and **is not editable**. If a value is not available from the nav database, then 18000 ft. is displayed"
