### ISSUE TITLE
[BUG] Circular bump on right side front fuselage

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#699]
### Describe the bug

Due to a coloured area on the F1 NORM file a circular bump appears on the front fuselage (PAX only)

### Expected behaviour

no circular bump on forward fuselage

### Evidence

Best visible with fading sun light 

![image](https://github.com/invernyx/md11-bugs/assets/150608109/1b699e2d-cfbd-4877-827b-2d9f6f0be266)
![image](https://github.com/invernyx/md11-bugs/assets/150608109/355f47b3-9b9f-45a5-be7a-92cb86cfb882)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been fixed in the latest texture update.
