### ISSUE TITLE
[TODO] - Terminal Leg Support

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/md11-bugs#7]
### Describe the bug

Terminal Leg Support

### Expected behaviour

The following terminal legs need to be supported:
- [x] ArcToFix (AF)
- [x] ProcedureTurnToIntercept (PI)
- [x] RadiusToFix (RF)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
All terminal leg types are now supported
