### ISSUE TITLE
[BUG] - Button guards do not work in P3Dv4

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#70]
### Describe the bug

When using P3Dv4, button guards do not work as intended. Buttons behind a guard can be pushed even when the button guard is down.

### Steps to reproduce

1. Load the aircraft in P3Dv4.
2. Attempt to push a button through a guard
3. Observe that you are able to push a button through a guard.

### Expected behaviour

Just like in P3D v5, button guards are supposed to work. They are supposed to block input.

### Evidence

https://github.com/invernyx/md11-bugs/assets/48654776/657728bb-2909-48d6-af8b-6a5992b4ffb2

### Simulator

P3Dv4

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is a p3d bug
