### ISSUE TITLE
[BUG] Cabin partly untextured

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#700]
### Describe the bug

The front galley, large parts of the first class, economy class (just after the mid lavatory) and aft galley aren't properly displayed. 

### Expected behaviour

The cabin should be visible from outside and inside in all its glory.

### Evidence

https://github.com/invernyx/md11-bugs/assets/150608109/a2ca97c0-70a0-4ea0-8f8e-3b6f6da269f9

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
The original high resolution 3d cabin seen from the interior view is not being used when being rendered from the exterior view as it collides/clashes/clips through the exterior. It is meant to be viewed only through the interior. With that said, the textures within the low resolution exterior view cabin will have redone global illumination ambient occlusion maps to make them appear less dark.

**Comment by alxcpt** [comment]
As long as it doesn't look this on the final version, i'm fine with that. There should be a transition/barrier at the door step or so from the exterior low res cabin, to the interior hi res cabin. As you said the high res cabin shouldn't be visual from the outside, but the low res cabin shouldn't be visible from the inside as well.
