### ISSUE TITLE
[SUGGESTION] - Simconnect Events documentation

### ISSUE THREAD

**Issue by tebeso** [invernyx/md11-bugs#701]
### Is your feature request related to a problem? Please describe.

It would be nice to have events documented. I want to create a TFDI MD11 profile for spad.next, but i dont have events/states for the autopilot

### Describe the solution you'd like

as above

### Describe alternatives you've considered

-

### Additional context

-

**Comment by turbofandude** [comment]
We've started doing this here: https://docs.invernyx.com/en/md11/integration

The autopilot readouts will be available in the next version
