### ISSUE TITLE
[BUG] Systems failed to initiate (start on the runway)

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#702]
### Describe the bug

If started on the runway the electrics panel and emergency power show error messages

### Steps to reproduce

Start flight on the runway with panel state 'Ready to fly'
Eicas shows Bleed air 1, 2, 3 off; Trim air off and emer pwr on; bat discharging (after some wait)

### Expected behaviour

plane should show no error message

### Evidence

https://github.com/invernyx/md11-bugs/assets/150608109/5cb9e16e-7e80-4c5c-b422-40e7457ee079

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Takeoff

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#678
