### ISSUE TITLE
[BUG] Fuel flow values not clearly seperated

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#703]
### Describe the bug

Once the FF values exceeds 9999 the three values appear as one on the display, there should be more seperation between the values.  

### Expected behaviour

You should be able to read the indivual engine FF values clearly to notice abnormalities. For default cockpit view the appear as one value (above 10000)

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150608109/e1e2bfd8-b231-4980-9223-3c5948dd252f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.23+
