### ISSUE TITLE
[BUG] - During the approach, the aircraft deviated from the LOC signal and did not automatically correct it.

### ISSUE THREAD

**Issue by JimmyKudo1015** [invernyx/md11-bugs#705]
### Describe the bug

During the approach, the aircraft deviated from the LOC signal and did not automatically correct it.

### Steps to reproduce

Every APPR

### Expected behaviour

Automatically correct the position of the aircraft relative to the LOC signal

### Evidence

![IMG_0421](https://github.com/invernyx/md11-bugs/assets/66729933/7bf4408a-8dfa-44b5-b975-0ecb9859aceb)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Landing

### Pitch

-

### Bank

-

### Heading

-

### Altitude

-

### Departure

-

### Arrival

-

### Cruise level

FL290

### ZFW

-

### CG

-

### Fuel

-

### Cost index

-

### Route

-

### Location

-

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#566
