### ISSUE TITLE
[BUG] - GNS/ IRS NAV Indications

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#706]
### Describe the bug

GNS NAV Incorrect

### Steps to reproduce

Align ADIRU

### Expected behaviour

With GPS working and IRUs aligned, lower left of ND should show G/I NAV.  Presently it shows GNS NAV.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by AllanBurek** [comment]
With GNS NAV inhibited on POS REF PG 1, it shows (I) over the FMC LAT LONG, and with it enabled it shows G/I which is correct.  Just needs to be reflected on the ND.

**Comment by turbofandude** [comment]
Resolved in 0.22+
