### ISSUE TITLE
[BUG] - GE OIL PRESSURE TOO HIGH

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#707]
### Describe the bug

Oil pressure is too high

### Steps to reproduce

Start engines

### Expected behaviour

GE oil pressure is rarely more than 80 PSI.  Min for engine operation is 10.  Current values reflect more of the PW pressure values.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
