### ISSUE TITLE
[BUG] - EMERGENCY LIGHTS

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#708]
### Describe the bug

Emergency Lights in Flight Deck Do Not Illuminate

### Steps to reproduce

Turn on emergency lights

### Expected behaviour

With emergency lights on, there are 2 small emergency lights on in the dome light.  

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Is the emergency light any different from the dome light (in terms of brightness, light falloff, coning or omnidirectional?).

**Comment by AllanBurek** [comment]
EMER LT TEST Button
When this button is pushed:
• Emergency lights illuminate
• Integral batteries are tested under load
• EMER LTS TEST PASS alert is displayed on EAD when all circuits
and batteries are satisfactory.
If EMER LTS TST PASS does not appear, batteries with abnormal voltage can be identified on the SD STATUS page MAINT column by pushing the button again.

**Comment by turbofandude** [comment]
@AllanBurek @arwasairl Just a bump on this. Thank you!

**Comment by AllanBurek** [comment]
Hi All. ![image](https://github.com/invernyx/md11-bugs/assets/152933757/de164141-c32f-4b87-bdaf-d82d15e1cd74)

**Comment by AllanBurek** [comment]
https://github.com/invernyx/md11-bugs/assets/152933757/b294510d-6daa-4941-8970-c9d3af25c7aa

**Comment by AllanBurek** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/152933757/2708d50c-f59d-4e92-b15a-2430f8535cbb)

**Comment by AllanBurek** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/152933757/8fa6f347-937e-4d58-b2cc-848c4fe1eb2f)

**Comment by AllanBurek** [comment]
The video is what happens during the emergency light test.  If all lights work, you get an EMER LTS TST PASS or EMER LTS TST FAIL if any of the lights fail.

**Comment by arwasairl** [comment]
@turbofandude Need to add behavior for the button to do this.
@jhattermann Need to create a new cockpit sprite for low intensity dome.

**Comment by jhattermann** [comment]
Geometry has been created and vis tagged as "MD11_AOVHD_EMER_LT"
