### ISSUE TITLE
[BUG] - Emergency Light Test 

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#709]
### Describe the bug

Emergency light test does not work

### Steps to reproduce

Push emergency light test button.

### Expected behaviour

emergency light test should briefly test the integrity of all the lights.  CYAN EMER LT TEST should be displayed while test is in progress.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Does the test trigger the lights?

**Comment by AllanBurek** [comment]
EMER LT TEST Button
When this button is pushed:
• Emergency lights illuminate
• Integral batteries are tested under load
• EMER LTS TEST PASS alert is displayed on EAD when all circuits
and batteries are satisfactory.
If EMER LTS TST PASS does not appear, batteries with abnormal voltage can be identified on the SD STATUS page MAINT column by pushing the button again.

**Comment by joon44** [comment]
This should work

**Comment by turbofandude** [comment]
Long since resolved
