### ISSUE TITLE
[BUG] - Forward Fuel Pumps

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#711]
### Describe the bug

Forward Fuel Pumps Not Working

### Steps to reproduce

Start engines.  Only aft boost pumps operate.

### Expected behaviour

Tanks 1/2/3 should have all main fuel pumps on during engine operation.  

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by AllanBurek** [comment]
I was wrong about the forward fuel pumps.  From the AMM as there are still issues regarding the logic.
[MD-11_AMMFX1_28_08_00_0_0.pdf](https://github.com/invernyx/md11-bugs/files/13624982/MD-11_AMMFX1_28_08_00_0_0.pdf)

**Comment by turbofandude** [comment]
Resolved in 0.37+
