### ISSUE TITLE
[BUG] - Fuel Spigots

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#712]
### Describe the bug

Displayed in White at all times on Fuel SD.

### Steps to reproduce

Look at fuel synoptic.

### Expected behaviour

White spigot designates armed.  When they arent armed they arent displayed.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.23+
