### ISSUE TITLE
[BUG] - Tail Fuel Management

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#713]
### Describe the bug

Fuel not going to tail tank.

### Steps to reproduce

Fly with FSC in AUTO.

### Expected behaviour

Should be putting fuel in the tail tank to adjust CG for desired range.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
erroneously marked duplicate

**Comment by AllanBurek** [comment]
AB.Tail fuel management is specified as the movement of fuel to and from the tail tank. These functions are used for:
•Fuel availability
•Prevention of cold fuel from freezing
•Fuel scheduling
•Water Scavenge (To prevent too much water accumulation)
•The maintenance of the correct aircraft CG.
AC.The primary function of tail fuel management is aircraft CG control. The FSC uses aircraft gross weight and CG data from the FUEL QUANTITY GAGING SYSTEM (FQGS) to do the CG control function. The FSC keeps ZERO FUEL WEIGHT (ZFW) and Longitudinal CG (ZFWCG) data input from the FLIGHT MANAGEMENT COMPUTERS (FMCs) when flight phase changes from TAXI to TAKEOFF/LAND. If this input is not correct or not available when this flight phase changes, the FSC will not do tail fuel management for that flight.
AD.When the flight status is ground and the starter shutoff valve (commanded state), of an engine shows OPEN, the FSC does a check of the total fuel quantity. If the total quantity of available fuel is more than 60,000 lb (27215.5 kg), then the FSC will do CG management during that flight. If the total available fuel quantity is 60,000 lb (27215.5 kg) or less, the FSC will not transfer fuel to the tail for CG management during that flight. If tail fuel management is on and the No. 2 engine is not on, then the limit on tail tank fuel is 5,000 lb (2268 kg).
AE.When the flight phase is CLIMB, the FSC starts to control aircraft CG and keeps a constant moment margin away from the aircraft aft CG limit. When aircraft gross weight is 560,000 lb (254011.5 kg) or less, the aircraft aft CG limit is a constant 34% of MAC. When aircraft gross weight is more than 560,000 lb (254011.5 kg), the aft CG limit changes as a function of gross weight and is calculated internally by the FSC.
AF.The FSC transfers fuel from any main tank that no longer supplies an engine. This is done to keep equal fuel levels in all three main tanks. This function is done by the wing fuel unbalance program in the FSC. Tail fuel is not transferred into a main tank (that does not supply an engine), even if the fuel level in that tank causes tail fuel to be sent forward for engine use. If the engine starts while fuel is transferred from the tail for engine use, the FSC will start the tail fuel transfer to the tank with the restarted engine if the quantity in that tank is sufficiently low. This will make sure that the applicable main tank has sufficient fuel to supply engine operation.
AG.All the fuel in a tank that supplies fuel to a shutdown engine will be transferred to tanks that supply engines that are in operation. This fuel will be transferred if:
•The quantity in the inboard compartments of tank No. 1 or tank No. 2 is 3,000 lb (1369.8 kg)
•The total fuel quantity in tank No. 2 is 3,000 lb (1369.8 kg).
AH.The FSC uses the status of its FM input power–monitor discrete to identify fuel system components that do not electrically operate. When there is a failure of electrical power, the FSC starts alternate procedures, but will not write a component as unserviceable in the maintenance memory. The FSC will go back to its primary procedure if electrical power is supplied to the components again.
AI.The FSC also monitors the FSCP switch wiring to verify the continuity of all momentary switches and most alternate position switches plus their associated wiring.
With the FSC in AUTO mode, the normally-closed momentary switches on the FSCP do not control fuel system components. If a switch circuit is detected as open by the FSC, the AUTO/MANUAL switch annunciator will flash MANUAL for approximately 2 minutes. If the switch is still determined to be open, an internal (FSCP) failure will be recorded to the fault memory.

**Comment by turbofandude** [comment]
Resolved in 0.37+
