### ISSUE TITLE
[BUG] - Freighter AFT cargo door missing

### ISSUE THREAD

**Issue by pburnay-invernyx** [invernyx/md11-bugs#715]
### Describe the bug

The AFT right-hand side cargo door on the freighter seems to be missing. The same might be true for the PAX version but was not checked.

### Expected behaviour

N/A

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/126467452/4a56163c-8c03-4dd6-84db-81622358365b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Duplicate of #290
