### ISSUE TITLE
[BUG] - Bouncy Nose-Gear

### ISSUE THREAD

**Issue by nIn9R** [invernyx/md11-bugs#717]
### Describe the bug

Nosewheel bouncing all the way during taxi, TO & landing 

### Expected behaviour

be a wheel

### Evidence

https://youtu.be/yE-CRH4q4PM

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Bug aside, the video is hilarious!

**Comment by CptUnicorn** [comment]
In addition to this on the PAX version, the nose bounces considerably during the initial takeoff roll.
https://medal.tv/games/microsoft-flight-simulator/clips/1J8lYXecuPs3Zf/d1337bN49iNt?invite=cr-MSxxSHksMTkzNzg2ODc5LA

**Comment by AllanBurek** [comment]
I have tire failure inhibited.  It seems to be high gross weights that activate it

**Comment by CptUnicorn** [comment]
> I have tire failure inhibited. It seems to be high gross weights that activate it

I think it has an issue with the weight changing. If you look at the fuel display on the FUEL page the number bounces around.

**Comment by crazyforiphone** [comment]
> > I have tire failure inhibited. It seems to be high gross weights that activate it
> 
> I think it has an issue with the weight changing. If you look at the fuel display on the FUEL page the number bounces around.

this seems right, I am about to do a 10 hour flight and have this same issue, i took out the payload and dropped the fuel significantly just to see if it would fix it and it did, when I added the payload and fuel back in I got the bouncing and the numbers for fuel/GW going crazy

**Comment by microlight2010** [comment]
This was an issue with weight distribution by the EFB, on specifying pax and cargo weights. This has been corrected in the latest version of the EFB.
