### ISSUE TITLE
[BUG] - Engine Nacelle Temperature

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#722]
### Describe the bug

Engine Nacelle Temperature Way High

### Steps to reproduce

Run engines

### Expected behaviour

Should be be between 60-80 typically.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by AllanBurek** [comment]
nacelle temp display is an option.   FDX does not display.

**Comment by turbofandude** [comment]
Resolved in 0.54+ (simulation is limited, but brought back into a valid range)
