### ISSUE TITLE
[BUG] - Pulling Gear Handle

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#723]
### Describe the bug

Pulling Gear Handle Tests LG Prox Sensors

### Steps to reproduce

Preflight check - pull gear handle out 

### Expected behaviour

Preflight check - pull gear handle out (not up , just out) and all gear indication should turn red on the EAD CONFIG page and the lights above the gear handle.  This tests the gear extension #2 system.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Long since resolved
