### ISSUE TITLE
[BUG] - 2L Pax Door

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#725]
### Describe the bug

Door is Removed (maybe)

### Expected behaviour

For aircraft built as freighters from MCD, the 2L door is there (although deactivated). Converted aircraft from pax service, the door is removed when the main deck cargo door is installed. In all cases, the window plugs are there.

### Evidence

Built as a freighter:
https://www.planespotters.net/photo/1373554/n601fe-fedex-express-mcdonnell-douglas-md-11f

Converted
https://www.planespotters.net/photo/1237186/n523fe-fedex-express-mcdonnell-douglas-md-11f

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I don't see an issue here, we simulate the factory freighter, the door is present, so it's accurate

**Comment by AllanBurek** [comment]
Precisely my point.  The current FedEx repaint is N595FE.  It's a converted American Airlines aircraft.  It doesn't have the door on the real aircraft but the repaint does.
