### ISSUE TITLE
[BUG] - Air ISOL Valves

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#728]
### Describe the bug

AIR ISOL Valve Open With Engs Running

### Steps to reproduce

Start all 3 engines, provide bleed from engines.

### Expected behaviour

All 3 engines running and providing air, the 1-2 and 1-3 ISO valves should be closed.  ESC in AUTO.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

35000

### Agreement

- [X] Yes

**Comment by GR1MMly** [comment]
To add, the cyan alerts indicating the valves are open are missing

**Comment by AllanBurek** [comment]
AMM info.
[MD-11_AMMFX1_21_08_00_0_0.pdf](https://github.com/invernyx/md11-bugs/files/13624986/MD-11_AMMFX1_21_08_00_0_0.pdf)

**Comment by turbofandude** [comment]
Resolved in 0.25+
