### ISSUE TITLE
[BUG] - APU Air Pressure

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#729]
### Describe the bug

APU bleed pressure should be reflected on the Air synoptic.

### Steps to reproduce

APU air on

### Expected behaviour

All 3 bleed pressure indications should be reading what the APU is putting out.  Currently they read 0 when APU air is on.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.25+
