### ISSUE TITLE
[BUG] - Yaw Damper and LSAS panel does not light indicator lights during automatic electrical operation

### ISSUE THREAD

**Issue by arwasairl** [invernyx/md11-bugs#73]
### Describe the bug

When flying the electrical system in AUTO mode, turning off any of the yaw damper, LSAS or FEEL knobs do not affect the indicator lights. Only when the electrical system is switched to MANUAL will the indicator lights correctly illuminate.

### Steps to reproduce

1. Load the aircraft
2. Attempt to push any buttons, in this case, switch ELEV FEEL out of AUTO
3. Observe no indicator lights for MANUAL ELEV FEEL
4. Switch ELEC SYSTEM to MANUAL
5. Observe all indicator lights on the yaw damper panel.

### Expected behaviour

Regardless of electrical mode, AT LEAST when the ELEV FEEL and FLAP LIMIT knobs are moved outside of AUTO, the MANUAL indicator lights must light up. Refer to this reference: https://youtu.be/iXuqFbVzDeI?si=2aNxtPXeARxfxWRl&t=1533
(Notice how the electrical system is still in AUTO)

### Evidence

https://github.com/invernyx/md11-bugs/assets/48654776/0c6f84b8-b499-4f4c-95d5-15ac3b61d2a5

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Cruise

### Altitude

Not applicable

### Agreement

- [X] Yes

**Comment by joon44** [comment]
LSAS lights work correctly.

**Comment by TheFightingRaven** [comment]
flap limit/elev feel "manual" lights don't light up, lsas lights now fixed
