### ISSUE TITLE
 Tires moving around while gear up/down #412 [BUG] 

### ISSUE THREAD

**Issue by PatrickChai** [invernyx/md11-bugs#731]
### Describe the bug

Tires still moving while going up or down.

### Expected behaviour

No tire movements.

### Evidence

Sorry for duplicating my old post but I could not find out how to re-open a closed ticket. I thought with the latest update this is fixed but my tires on the left main gear still moving while going up or down.
This is with both, PAX and F version.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by PatrickChai** [comment]
With the newest update, indeed the wheels are not moving anymore BUT now the jittering is back.
During Gear up or down, the movements are like jittering/flickering even the gear door.

**Comment by PatrickChai** [comment]
With the latest update, indeed the wheels are now not moving anymore BUT the jittering is back. While gear are going up or down, there is a jittering/flickering effect on the gear and gear doors.

**Comment by arwasairl** [comment]
Please report the jittering animation as a separate bug report. This one will be closed as it has been fixed.
