### ISSUE TITLE
[BUG] - Minimums Knob In Baro Only Adjusts In Increments of 10

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#732]
### Describe the bug

With Minimums Knob Set to Baro, only adjusts in increments of 10

### Steps to reproduce

Set Minimums Knob to Baro and adjust via mousewheel

### Expected behaviour

Barometric minimums should be adjustable in increments of 1

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.22+
