### ISSUE TITLE
[BUG] - Inserted Runway Not Displayed On ND While Alignment In Progress

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#733]
### Describe the bug

If a departure runway is selected in the FMS, the ND only shows aircraft symbol, no runway or runway identifier. NOTE: Runway symbology also missing after alignment

### Expected behaviour

If a departure runway is selected in the FMS, the ND should show runway symbology and identifier, regardless of IRS alignment status.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
what exactly does it show in the alignment phase, just a runway or the entire plan? and with what map alignment?

**Comment by GR1MMly** [comment]
> what exactly does it show in the alignment phase, just a runway or the entire plan? and with what map alignment?

Once a runway is input in the FMS the ND will display two parallel lines and the runway identifier.

**Comment by turbofandude** [comment]
The runway symbol is drawn correctly with alignment on both MAP and PLAN mode. The runway symbol is drawn in PLAN mode even while aligning. Our current behavior matches what you're describing it should be.
