### ISSUE TITLE
[BUG] - Generator Arming Display Inconsistencies On Startup

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#734]
### Describe the bug

With the electric system in auto, the GEN 1/2/3 and AC TIE 1/2/3 switches are not set to ARM. Furthermore, several inconsistencies on the electric SD with regards to actual system status

### Steps to reproduce

Cold and Dark
During engine start, observe GEN1/2/3 and AC TIE1/2/3 lights are off (should be ARM)

Starting  Engine 3 First (starting only Engine 2 presents the same way):
-- When No3 generator is on speed, No3 APU PWR turns white however generator 3 relay does not show closed on SD. (Removed all other electrical power and confirmed relay is closed and providing power, just not reflecting on SD).

Starting Engine 1 First:
-- When #1 generator is on speed, No1 APU PWR turns white and 1/2/3 Gen relays close on SD (should be AC TIE relays that close)

### Expected behaviour

On engine start, GEN 1/2/3 and AC TIE 1/2/3 switches should indicate ARM on the overhead panel with ELEC Sys in AUTO
With respective generator on speed, GCU should close respective generator relay and AC tie relay (unless external power is in use).

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
I've written many PR regarding the EPS system back when it was a closed QA test period.  Probably alot of overlap with this write up.  (see all MD-EPS-XX)

**Comment by turbofandude** [comment]
Between fixes to arming and existing reports, I am going to close this one
