### ISSUE TITLE
[BUG] - Pitch Change During Acceleration Too Aggressive

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#735]
### Describe the bug

During acceleration on initial takeoff, flight director noses down aggressively

### Steps to reproduce

Takeoff and engage autopilot, observe aggressive pitch down when passing acceleration altitude.

### Expected behaviour

In recent real flight observations during the transition to acceleration, the smooth flight logic commands the nose down to acceleration attitude at a rate of about 100fpm to a final rate of 500-1000fpm.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

NA

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be since resolved
