### ISSUE TITLE
[BUG] - ALT Miscompare Missing

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#736]
### Describe the bug

When altimeter miscompare criteria are met, ALT miscompare does not display on PFD

### Expected behaviour

When altimeter miscompare criteria are met, amber ALT miscompare alert should display on PFD

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.48+
