### ISSUE TITLE
[BUG] - Primary flight control surface droop (MD-FC-18)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#738]
### Describe the bug

With HYD OFF, the primary flight control surfaces (AIL & ELEV) are energized to the neutral position.  The load screen with the cinematic fly-by properly shows them drooped.

### Steps to reproduce

Load up a flight.

### Expected behaviour

S/B AIL and ELEV are drooped when no HYD power is applied.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
Not fixed in v0.42.01

**Comment by GenericNerd** [comment]
This will be resolved in the next version
