### ISSUE TITLE
[BUG] - FCP altitude window not respected

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#740]
### Describe the bug

Cruising at FL330, I made a step climb to FL350 by replacing 330 with 350 on FMS F-PLN INIT page. With 33000 still set on the FCP, the plane started an immediate climb to FL350 disregarding the altitude window setting. I made a test and set 300 onto the INIT page and the plane went to immediate descent.

### Steps to reproduce

At level flight change cruise level on F-PLN INIT page and observe the plane climbing/descending immediately.

### Expected behaviour

The climb or descend does not start until the new value is set in the FCP. 

I guess this is related to the closed issue #594

### Evidence

In this picture FCP showing 33000, INIT 350 and FMA showing 35000 and plane climbing without permission.
![FlightSimulator_0TgBrFQQvM](https://github.com/invernyx/md11-bugs/assets/102414406/84e74be7-8df6-41f2-848d-f1890d3235e7)

From AOM
![image](https://github.com/invernyx/md11-bugs/assets/102414406/cce4a138-c9bd-486c-a51d-2e3bb617b48f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

EGKK

### Arrival

OTHH

### Cruise level

FL330

### ZFW

195.0 tn

### CG

8.1

### Fuel

34000 kg

### Cost index

100

### Route

EGKK26L MIMFO1M MIMFO Y312 DVR UL9 KONAN UL607 MATUG DCT BOMBI DCT TENLO DCT DEXIT DCT PESAT DCT NEKUL DCT RONBU/K0891F330 P975 ARTAT/N0480F330 UP975 ORMAN/N0485F350 UP975 LESRI P975 SIDNA UP975 NOLDO/N0466F230 P975 LONOS L703 HAYYA HAYYA1V OTHH34R

### Location

At waypoint ERGUN in Turkish airspace.

### Agreement

- [X] Yes

**Comment by joon44** [comment]
![Screenshot_2023-12-11-23-23-29-13_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/invernyx/md11-bugs/assets/102414406/952e4f0a-af94-414e-bd60-32767ab448bc)

**Comment by TheFightingRaven** [comment]
the entire stepclimb logic is not implemented yet

**Comment by joon44** [comment]
> the entire stepclimb logic is not implemented yet

But the climb/descent should not occur past the altitude window setting as it is the limit.

**Comment by turbofandude** [comment]
The violation of the FCP will be resolved in 0.24+. AFS will select the lower of cruise altitude OR FCP altitude.
