### ISSUE TITLE
[BUG] - PROG shows TAT

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#741]
### Describe the bug

PROG page shows TAT temperature. It should show SAT.

### Steps to reproduce

Look at PROG page on the flight

### Expected behaviour

Show current temperature.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/30d1a6ba-438e-4fdb-8453-1d74588ce3e9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

EGKK

### Arrival

OTHH

### Cruise level

FL350

### ZFW

195.0 tn

### CG

8.1

### Fuel

31300

### Cost index

100

### Route

EGKK26L MIMFO1M MIMFO Y312 DVR UL9 KONAN UL607 MATUG DCT BOMBI DCT TENLO DCT DEXIT DCT PESAT DCT NEKUL DCT RONBU/K0891F330 P975 ARTAT/N0480F330 UP975 ORMAN/N0485F350 UP975 LESRI P975 SIDNA UP975 NOLDO/N0466F230 P975 LONOS L703 HAYYA HAYYA1V OTHH34R

### Location

In Turkish airspace at NUNTU

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.24+
