### ISSUE TITLE
[BUG] - FUEL panel lights

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#742]
### Describe the bug

The LOW light overlaps with the OFF light on 1/2/3 PUMPS buttons. FILL buttons do not show the ARM light

### Expected behaviour

Texts aligned and shown correctly

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/66c80eea-3774-40c2-ae25-192378a52711)

![image](https://github.com/invernyx/md11-bugs/assets/102414406/bb8a81dd-6ce6-4ec5-a669-1f9aaf3bd8f7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Will try a reset xform on these, the issue is only present in MSFS
