### ISSUE TITLE
[BUG] - Nose dive when reconnecting AT 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#743]
### Describe the bug

Nose dive when reconnecting AT 

### Steps to reproduce

Fly plane with AT and AP on, disconnect AT, reconnect AT with auto flight button, witness impending death 

### Expected behaviour

To not pitch down 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Approach

### Departure

EKCH

### Arrival

EHAM

### Cruise level

380

### ZFW

160kg

### CG

30%

### Fuel

16000

### Cost index

94

### Route

EKCH/04R LANGO2A LANGO P999 ALS N872 EEL EEL1A EHAM/18R

### Location

Around SPY VOR 

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This is likely related to the nosedive issue we just fixed. Please try again with 0.22+.
