### ISSUE TITLE
Excessive Cruise Fuel Burn vs. SimBrief

### ISSUE THREAD

**Issue by 017941** [invernyx/md11-bugs#744]
### Describe the bug

Cruise fuel burn is too high. Approx 1.38 times SimBrief predicted cruise burn rate.

### Steps to reproduce

Climb to altitude and note FF. Crosscheck Actual vs. Planned from SIM Brief. Keep a fuel log.

### Expected behaviour

I would expect to operate at or near the planned SimBrief fuel at each checkpoint. At the request of Luke I did JFK-LAX on consecutive days. The first day was using Lbs. and the second was KGs. The same result. 1.38  times the predicted cruise fuel burn rate versus SimBrief.

### Evidence

![Screenshot 2023-12-10 080123](https://github.com/invernyx/md11-bugs/assets/148719444/17de144f-69b3-4bc6-96eb-0d2fdc3e6d76)
![Screenshot 2023-12-10 082755](https://github.com/invernyx/md11-bugs/assets/148719444/47f863cd-7bdc-48fb-ae3a-be9a96671682)
![Screenshot 2023-12-10 084154](https://github.com/invernyx/md11-bugs/assets/148719444/61365d2b-cd67-43f9-8c3e-22e8962d6416)
![Screenshot 2023-12-11 075934](https://github.com/invernyx/md11-bugs/assets/148719444/a1b70822-f560-4338-8417-9689639a4fd0)

![Screenshot 2023-12-11 080527](https://github.com/invernyx/md11-bugs/assets/148719444/de63ec81-00d3-491d-98ee-4fc96307d2b4)

![Screenshot 2023-12-11 080510](https://github.com/invernyx/md11-bugs/assets/148719444/7d27ab36-81a7-41ea-bd78-e0498d1cc23b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

FL380

### Agreement

- [X] Yes

**Comment by joon44** [comment]
I think we need to wait for a good simbrief profile

**Comment by 017941** [comment]
> I think we need to wait for a good simbrief profile

Yes, but 1,7 times the SimBrief burn rate at cruise is excessive. The FFs appear normal. I did JF-LAX day 1 in pounds and Day 2 in KGs. Same burn rate. 1.7 times the predicted SimBrief.

**Comment by joon44** [comment]
> Yes, but 1,38 times the SimBrief cruise burn rate at cruise is excessive. The FFs appear normal. I did JFK-LAX day 1 in pounds and Day 2 in KGs. Same burn rate. 1.7 times the predicted SimBrief.

I use P08 for fuel burn in the simbrief profile and it seems to match pretty well. Anyway we just have to wait that TFDi will create a matching simbrief profile for us. If the actual fuel flow is correct, then we need a matching profile. Otherwise we try to match a working plane against non-working profile.

**Comment by 017941** [comment]
I didn’t know that you could put in P08. I’ll try now.Sent from my iPhoneOn Dec 11, 2023, at 9:56 AM, joona ***@***.***> wrote:﻿

Yes, but 1,38 times the SimBrief cruise burn rate at cruise is excessive. The FFs appear normal. I did JFK-LAX day 1 in pounds and Day 2 in KGs. Same burn rate. 1.7 times the predicted SimBrief.

I use P08 for fuel burn in the simbrief profile and it seems to match pretty well. Anyway we just have to wait that TFDi will create a matching simbrief profile for us. If the actual fuel flow is correct, then we need a matching profile. Otherwise we try to match a working plane against non-working profile.

**Comment by FreakyD777** [comment]
https://github.com/invernyx/md11-bugs/issues/266

**Comment by FreakyD777** [comment]
Actual fuel burn values provided in above PR

**Comment by 017941** [comment]
That helps a lot. Thank you Mike. Mine were very similar, so the problem may lie with the SimBrief software. 

As Joona said; “ I use P08 for fuel burn in the simbrief profile and it seems to match pretty well. Anyway we just have to wait that TFDi will create a matching simbrief profile for us. If the actual fuel flow is correct, then we need a matching profile. Otherwise we try to match a working plane against non-working profile.”

Raven asked me to rein these flights after his next performance update.

**Comment by TheFightingRaven** [comment]
fixed 0.23+
