### ISSUE TITLE
[BUG] - HYD Pressure too high on direct reading Gauge

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#745]
### Describe the bug

HYD Pressure too high on direct reading Gauge

### Steps to reproduce

After engine start gauge on upper pedestal reads nearly 3500 for both systems.

### Expected behaviour

3500 is way too high, 3100 is even a stretch.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
What is a reasonable value?

**Comment by AllanBurek** [comment]
2900-3000 is max with elec pumps.  The gauge will just read whatever the pressure is on the synoptic for the 1 and 3 systems.  Currently with the engines running they show 3000 psi, but the gauge reads almost 3500.

**Comment by turbofandude** [comment]
Resolved in 0.24+
