### ISSUE TITLE
[BUG] - Nose gear tyres + left main gear tyres reversed

### ISSUE THREAD

**Issue by ElPadre85** [invernyx/md11-bugs#746]
### Describe the bug

The animation of the tyres on the nose gear and left main gear are reversed.If you move forward,they turn aft.

### Expected behaviour

reverse the animation

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.25+

**Comment by timv217** [comment]
This bug has has re-occurred in the last few builds

**Comment by arwasairl** [comment]
fixed in latest indev version
