### ISSUE TITLE
[BUG] - Spoilers cannot arm when binded to axis

### ISSUE THREAD

**Issue by slowreload** [invernyx/md11-bugs#747]
### Describe the bug

Unable to arm spoilers when spoilers are mapped to axis on honeycomb bravo

### Steps to reproduce

Happens all the time with axis mapped

### Expected behaviour

Able to arm spoilers with a click spot or have a point on the axis where spoiler arm. See pmdg 737 spoiler axis thats how it should work 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Any

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
they can be armed by scrolling up on the spoiler handle
