### ISSUE TITLE
[BUG] - Engines 2 and 3 stop very quick and weird flickering of Engine 1&3

### ISSUE THREAD

**Issue by tebeso** [invernyx/md11-bugs#748]
### Describe the bug

When engines run, there is a weird flickering and also when turning off all engines, engines 2 and 3 stops much quicker than engine 1. I also noticed, that engine 1 starts much quicker than the others

### Expected behaviour

No flickering, engines should stop with the same speed

### Evidence

Version 0.22.0-alpha

Engine 3 suddenly stopping at around 46 seconds into the video
https://www.youtube.com/watch?v=_wrxS0D2NBI

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by tebeso** [comment]
I also noticed, that engine 1 starts much quicker than the others

**Comment by arwasairl** [comment]
Fixed a while ago.
