### ISSUE TITLE
[BUG] - Plane inop/doesn't compile completly after update/WASM issue

### ISSUE THREAD

**Issue by ElPadre85** [invernyx/md11-bugs#749]
### Describe the bug

After updating and launching into the sim,the plane is not functional.Yoke is 90° offset and none of the buttons work.Workaround is deleting the 4 files in the TFDI folder in User/appdata/roaming/msfs/packages

### Steps to reproduce

-update through the manager
-load into the sim/3D world in the MD-11

workaround
-exit sim
-go to above mentioned folder and delete the 4 files (not the Work folder)
-reload into the sim and everything works

### Expected behaviour

correct WASM compiling after updating

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150356530/ae8b1834-c0cb-490b-9f23-6c6c71f1d3e1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
No other users are reporting this and I am not sure what files you are deleting. Please completely uninstall and clean out any files you have from the aircraft and try again.
