### ISSUE TITLE
[TODO] - AIR packs off departure

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#75]
### Describe the bug

packs off departure needs to be coded

### Expected behaviour

![image](https://github.com/invernyx/md11-bugs/assets/138527559/73e0ea9f-407d-4018-90d9-632485b6823b)

### Crash

None

### Phase of flight

None

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This image is no longer available. What did the contents show?
