### ISSUE TITLE
Hydraulic pump or flaps moving cycling sound after engine start

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#750]
### Describe the bug

After engine start there is a sound very similar to the hydraulic pumps cycling or flaps moving. The sound persisted until 3000' and clean.

### Expected behaviour

After engine start you should not hear the hydraulic pumps. The cycling sound persists until after takeoff. Evidence forthcoming 

### Evidence

https://clipchamp.com/watch/i7KxjGTQYW5

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by 017941** [comment]
I was the original poster of this item. This bug is no longer present. It has been resolved evidently. I had it on htree flight, and I believe Raven forwarded it to the sound people. It is corrected.
