### ISSUE TITLE
Runway turnoff lights source or bulb not visible

### ISSUE THREAD

**Issue by EngineIgnition** [invernyx/md11-bugs#754]
### Describe the bug

Runway turnoff lights source not visible

### Expected behaviour

Runway turnoff lights source or bulb visible

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been fixed in the latest texture/model update.
