### ISSUE TITLE
[BUG] - Fuel Synoptic Green Lines Missing

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#757]
### Describe the bug

Fuel Synoptic Green Lines Missing between fuel pumps and fill valves

### Steps to reproduce

Cruise with more fuel in #2 thank 1 and 3.

### Expected behaviour

Green lines should connect between fuel pumps and fill valves

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

35000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
