### ISSUE TITLE
[BUG] - MD-11 Wont Maintain Speed

### ISSUE THREAD

**Issue by mclovin90** [invernyx/md11-bugs#758]
![FlightSimulator_mITKAbYTH4](https://github.com/invernyx/md11-bugs/assets/97921311/9f57a75e-080b-4cb4-82a4-9d66594ef07e)

### Describe the bug

Md-11 Wont keep speed thats on the FMC

### Steps to reproduce

Flying from KDEN-KMEM
in Pounds

FDX0001   13DEC2023    KDEN-KMEM   MD11 N116SB  RELEASE 1830 13DEC23
OFP 1           DENVER INTL-MEMPHIS INTL
                         WX PROG 1318 1321 1400   OBS 1312 1312 1312
	
  ATC C/S   FDX1         KDEN/DEN   KMEM/MEM      CRZ SYS      CI 92
13DEC2023   N116SB       1900/1920  2107/2115     GND DIST       805
MD-11F / CF6-80C2D1F                STA  2115     AIR DIST       748
                         CTOT:....                G/C DIST       757
                                                  AVG WIND   245/046
MAXIMUM    TOW 602500  LAW 471500  ZFW 451300     AVG W/C       P032
ESTIMATED  TOW 477134  LAW 445792  ZFW 425000     AVG ISA       M002
                                                  AVG FF LB/HR 17424
                                                  FUEL BIAS    P07.0
ALTN KSTL                                         TKOF ALTN  .......
FL STEPS KDEN/0350/
--------------------------------------------------------------------
DISP RMKS   NIL

--------------------------------------------------------------------
         PLANNED FUEL
---------------------------------
FUEL           ARPT   FUEL   TIME
---------------------------------
TRIP            MEM  31342   0147
CONT 0%                  0   0000
ALTN            STL  13812   0045
FINRES                6980   0030
---------------------------------
MINIMUM T/OFF FUEL   52134   0303
---------------------------------
EXTRA                    0   0000
---------------------------------
T/OFF FUEL           52134   0303
TAXI            DEN   2000   0020
---------------------------------
BLOCK FUEL      DEN  54134
PIC EXTRA            .....
TOTAL FUEL           .....
REASON FOR PIC EXTRA ............
--------------------------------------------------------------------
FMC INFO:
FINRES+ALTN          20792
TRIP+TAXI            33342
--------------------------------------------------------------------
NO TANKERING RECOMMENDED (P)
--------------------------------------------------------------------
I HEREWITH CONFIRM THAT I HAVE PERFORMED A THOROUGH SELF BRIEFING
ABOUT THE DESTINATION AND ALTERNATE AIRPORTS OF THIS FLIGHT 
INCLUDING THE APPLICABLE INSTRUMENT APPROACH PROCEDURES, AIRPORT 
FACILITIES, NOTAMS AND ALL OTHER RELEVANT PARTICULAR INFORMATION.

DISPATCHER: OSCAR WALL                  PIC NAME: ROBERTS, MARK

TEL: +1 800 555 0199               PIC SIGNATURE: ...............
 

ALTERNATE ROUTE TO:                                    FINRES   6980
APT      TRK DST              VIA                 FL  WC  TIME  FUEL
--------------------------------------------------------------------
KSTL/12L 355 246  JTEEE5 ODATE DCT BOOSH BOOSH3  360 M005 0045 13812
--------------------------------------------------------------------

MEL/CDL ITEMS DESCRIPTION
------------- -----------

--------------------------------------------------------------------

ROUTING:

ROUTE ID: DEFRTE
KDEN/35L EPKEE7 DUUZE DCT ICT DCT RZC BRBBQ3 KMEM/36L

### Expected behaviour

Md-11 Will keep Speed

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

2.5-3 deg nose up

### Bank

None

### Heading

106

### Altitude

35000

### Departure

KDEN

### Arrival

KMEM

### Cruise level

350

### ZFW

425000LBs

### CG

37.5

### Fuel

42700

### Cost index

25

### Route

KDEN/35L EPKEE7 DUUZE DCT ICT DCT RZC BRBBQ3 KMEM/36L

### Location

Just anytime after TOC

### Agreement

- [X] Yes

**Comment by opticalgenesis** [comment]
Same here, not quite to the same degree but it's a solid 0.04-0.06 mach off target, the engines aren't exceeding fadec limits either so there should be plenty of thrust available to chase those last few digits.

FPLN: ZSPD/17L K0915S1070 HSN81D HSN W13 TOGUG/K0915S1100 W13 BEGMO W117 DST B221 LJG A470 BEBEM/N0494F361 A470 DOTMI/N0495F360 A470 MAGOG MAGO31 VHHX/31

CRZ: FL351 (thanks metric system)
TOW: about 210 kgs - can see the bug at all phases of cruise so GW is likely not the main factor
CG: again seen this over a range, but around the 11 ANU mark
CI: 200
Fuel: 26.1 t
ZFW: 186.8 t

**Comment by FreakyD777** [comment]
Duplicate to #641
