### ISSUE TITLE
[BUG] - ETA Disappears off the ND

### ISSUE THREAD

**Issue by mclovin90** [invernyx/md11-bugs#759]
### Describe the bug

ETA Disappears off the ND goes from Distance/Time to just 0.00/0.00

### Steps to reproduce

Flew from KDEN-KMEM,

Upon passing random waypoints the ETA goes to 0.00/0.00

The waypoint is listed, It can be fixed if you use direct to the same waypoint, Otherwise it might update when passing the next waypoint or might not.
![FlightSimulator_95UrGpQjfo](https://github.com/invernyx/md11-bugs/assets/97921311/8d119002-0b1c-4351-ace4-df8c44d2f6f2)

### Expected behaviour

Each waypoints ETA updates as you pass the last waypoint.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

35000

### Departure

KDEN

### Arrival

KMEM

### Cruise level

350

### ZFW

425000LBs

### CG

37.5

### Fuel

42700

### Cost index

25

### Route

KDEN/35L EPKEE7 DUUZE DCT ICT DCT RZC BRBBQ3 KMEM/36L

### Location

At Cruise on my way to ICT waypoint

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
I think this is _also_ related to #755

**Comment by FreakyD777** [comment]
I have seen this many times.  It's random and cannot be induced.

**Comment by turbofandude** [comment]
Resolved in 0.30+
