### ISSUE TITLE
[TODO] - Missing Model Texturing

### ISSUE THREAD

**Issue by ElMikey70** [invernyx/md11-bugs#76]
### Describe the bug

Missing model texturing. FUSE_01 (left section)

### Steps to reproduce

![image](https://github.com/invernyx/md11-bugs/assets/91681107/a65bcd04-cf04-42eb-9155-603881410f3a)
![image](https://github.com/invernyx/md11-bugs/assets/91681107/bab630d8-f9e6-4778-8e98-072bb631719b)
![image](https://github.com/invernyx/md11-bugs/assets/91681107/f3f638a6-b116-4e29-8872-ee2564993629)

On the front left side of the fuselage, there's two missing static ports. The main cargo door is missing some circled texturing.
Also some extra doors above the landing gear are missing along with small details.

### Simulator

P3Dv5

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Reportedly fixed in the next update

**Comment by boomerc154** [comment]
Tires need realistic "weathering"
