### ISSUE TITLE
[BUG] - VHF3 Data

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#760]
### Describe the bug

VHF 3 should have a DATA option

### Steps to reproduce

Selecting the VHF3 frequency to the lowest limit should show "data".

### Expected behaviour

Selecting the VHF3 frequency to the lowest limit should show "data".

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.56+
