### ISSUE TITLE
[BUG] - Ice Detection System

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#764]
### Describe the bug

Not Currently Active

### Steps to reproduce

Should be active

### Expected behaviour

ICE DETECTION SYSTEM
The ice detection system enables the flight crew to accurately determine
when the wing, tail, and engine ice protection systems should be turned on or
off based on indication signals instead of anticipation of the icing conditions.
The ice detection system is a dual detector system (left and right). Each detector system has an independent failure monitoring system. For the ice detection system to be considered the primary indicator of an aircraft-in-ice
condition, both left and right ice detector systems must be operative.
Both left and right systems consist of a sensor in each wing engine cowl and
a controller in the leading edge of the wing near the engine pylon area.
Both left and right ice detector controllers interface with the ESC. The system operates using 115-volt ac power.
The secondary method of detecting ice buildup on the aircraft is the monitoring of Outside Air Temperature (OAT) and humidity combined with visual inspection of the aircraft windshield wipers and window frames during flight.
This method is used when both left and right ice detector systems are operative.
If one of the two systems fails, the flight crew must act based on the following:
• A single operative ice detector may be used for advisory information
only.
• Monitoring of OAT and humidity.
• Visual inspection of windshield wipers and window frames.

If both left and right ice detector systems fail, the flight crew must rely entirely on the following:
• Monitoring of OAT and humidity.
• Visual inspection of windshield wipers and window frames.
In icing conditions, ice builds up on the sensing probe. The resonant frequency of the probe then decreases due to the added mass of the ice. When this
frequency shift is sensed by the controller, an ICE DETECTED alert is displayed if any airfoil or engine anti-ice switch is not on. Simultaneously, the
probe starts to deice itself in preparation for the next ice detection cycle.
Heaters in the probe are powered for about ten seconds to melt the ice buildup. If during the next cycle, no ice is detected, a NO ICE DETECTED alert is
displayed if the anti-ice system is commanded on.
An ICE DET SINGLE alert will warn the crew that one of the 2 systems has
failed. An ICE DETECTOR FAIL alert will warn the crew that both ice detection systems have failed.
Ice detector system faults are stored in the ESC fault review.
When electrical power is on, the ice detection system is operative. Powerup
of the aircraft electrical system will automatically initiate a system powerup
test. This test checks the system interface signals, the heater, and the software memory. If no faults are detected during the powerup test, the ice detection system begins normal operation for the detection of ice. If a fault is
detected during the test, the ICE DET SINGLE or ICE DETECTOR FAIL alert
will be displayed and the ESC will store the fault in fault review.
The ice detection system is operational on the ground. The system alerts are
inhibited from display during takeoff and landing.
During normal operation, if an ice signal is transmitted from either the left or
right ice detector controllers, the ICE DETECTED alert will be displayed if
any airfoil or engine anti-ice switch has not been turned on. As each ice protection system is selected on, a corresponding alert will be displayed showing status of the respective ANTI-ICE switch (this is in addition to switch
illumination). When all the ice protection systems have been selected on, the
individual alerts are replaced by a single alert, A-ICE ALL ON.
As the ice protection systems are operating, the sensor probe continuously
cycles through the test for the detection of ice. If during the next cycle no ice
is detected, a NO ICE DETECTED alert appears after the 60 second ICE signal timer has elapsed. This informs the flight crew that the ice protection systems may be selected off. This alert will stay on until all of the ice protection
systems have been selected off.

If a single ice detection system fails, the ICE DET SINGLE alert is displayed.
This tells the flight crew that the ice detection system is now an advisory system only and observation of windshields and window frames is also  #required
to detect icing conditions. At the same time the fault is detected, the ICE and
NO ICE alerts from the faulty controller are inhibited.
If both ice detector systems fail, the ICE DETECTOR FAIL alert informs the
flight crew that observation of windshields and window frames is required to
detect icing conditions. When this alert is displayed the ICE and NO ICE
alerts are inhibited.
If the ESC loses both digital data buses that transmit the ICE, NO ICE, and
FAIL signals to the Display Electronic Units (DEU), an AIR ALERTS alert is
displayed. In this case, the ice detection system cannot be used to determine if the aircraft is in icing conditions.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by joon44** [comment]
With air system in manual, the anti-ice system also goes manual and there is sometimes the ICE DETECTED message showing on the EAD if anti-ice is off and in icing conditions.

**Comment by turbofandude** [comment]
Resolved in 0.28+
