### ISSUE TITLE
[BUG] - Distance/Time to Go Off Center

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#765]
### Describe the bug

Waypoint name needs to be centered between MAG/TRU and Distance

### Steps to reproduce

Fly

### Expected behaviour

Waypoint name needs to be centered on ND between MAG and Distance.  Also Distance needs NM.  For example:
NULUK          70.5NM/10.5

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

35000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.25+
