### ISSUE TITLE
Flashing CDU MSG and MAX LW 195.0 flashing

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#766]
### Describe the bug

CDU MSG is flashing on to ND and MAX LW 195.0 cannot be cleared until airborne

### Expected behaviour

To not see flashing messages on my displays

### Evidence

https://medal.tv/games/microsoft-flight-simulator/clips/1J8fD3pRZiwKia/d1337VvfAsLM?invite=cr-MSxKQlQsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should already be resolved, please re-open if not
