### ISSUE TITLE
[BUG] - Ballast Fuel Indicated in Tank 2

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#767]
### Describe the bug

Ballast fuel indicated on fuel SD.  No ballast selected in FMS

### Steps to reproduce

Look at fuel synoptic.

### Expected behaviour

should only be indicating ballast fuel if selected in INIT page 3.  Also, if no ballast is needed, it should not be zero.  It should clear and show [ . ]

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
purely visual, is placeholder data
