### ISSUE TITLE
[BUG] - CG disagree

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#768]
### Describe the bug

CG on Engine Display and Fuel Display Are different

### Steps to reproduce

Look at both

### Expected behaviour

They should match.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.28+
