### ISSUE TITLE
[BUG] - Door Alerts Missing

### ISSUE THREAD

**Issue by AllanBurek** [invernyx/md11-bugs#769]
### Describe the bug

All door alerts missing.  DOOR OPEN is not valid for the MD11

### Steps to reproduce

Open a door

### Expected behaviour

AMBER BOXED ALERTS (LEVEL 2)
CARGO DOOR AFT A (MISC) - Aft cargo door is not closed and locked
or cockpit call switch is activated.
CARGO DOOR AFT B (MISC) - Aft cargo door not locked.
CARGO DOOR CTR A (MISC) - Center cargo door is not closed and
locked or cockpit call switch is activated.
CARGO DOOR CTR B (MISC) - Center cargo door not locked.
CARGO DOOR FWD A (MISC) - Forward cargo door is not closed and
locked or cockpit call switch is activated. 
CARGO DOOR FWD B (MISC) - Forward cargo door not locked.
CARGO DOOR UPR A (MISC) - Upper forward or aft cargo door closed/
locked is open.
CARGO DOOR UPR B (MISC) - Upper forward or aft cargo door not
locked.
TAIL CONE UNLOCK (MISC) - Tail cone is unlocked. 
AMBER ALERTS (LEVEL 1)
AIR COND DOOR (MISC) - One or more air conditioning pack access
doors not closed and latched.
AVNCS EXT ACC DR (MISC) - Avionics external access door not
closed/locked.
AVNCS NOSE WHL DR (MISC) - Avionics nose wheel door not closed/
locked.

CABIN DOOR AFT L (MISC) - Left aft cabin door is not closed or armed.
Applies only if aircraft capable of aft door 4L/4R activation.
CABIN DOOR AFT R (MISC) - Right aft cabin door is not closed or
armed. Applies only if aircraft capable of aft door 4L/4R activation.
CABIN DOOR FWD L (MISC) - Left forward cabin door is not closed or
armed.
CABIN DOOR FWD R (MISC) - Right forward cabin door is not closed or
armed.
CAC DOOR (MISC) - Center accessory compartment door is not closed
and latched.
CREW REST OPEN (MISC) - The expandable crew rest module is not
properly stowed and latched. This alert is not displayed when the aircraft
is above 17,750 feet. Applies only if expandable crew rest is installed.
CRG DOOR TST FAIL (MISC) - Cargo door test has failed.
CRG DR (FWD, AFT, CTR, UPR) DISAG (MISC) - A disagree condition
exists between systems A and B of the respective cargo door warning
system.
DOOR OPEN (MISC) - One or more aircraft cabin doors are not closed
and armed, or one or more cargo or external access doors are not closed
and latched.
CYAN ALERTS (LEVEL 0)
CABIN DOORS OPEN - All cabin door emergency slides are disarmed.
CARGO DOOR TEST - MSC cargo door test is in progress.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The L2 alerts are missing, but DOOR OPEN is valid.
![image](https://github.com/invernyx/md11-bugs/assets/3858710/0da28494-5db4-4be9-926c-81caf5189f02)

**Comment by turbofandude** [comment]
Resolved as of 0.310+
