### ISSUE TITLE
[BUG] - Changing SIM RATE does not effect time dependant sub-systems

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#770]
### Describe the bug

When increasing or decreasing sim rate from 1X, time dependant systems like the chrono or fuel used do not match the new sim rate.  Example, say FF is 4500lb/hr and you increase sim rate to 8X, the fuel used will be calculated to the system time, not the sim time such that after an hour of real world time, 4500 lb will be used, not 4500 x 8.

### Steps to reproduce

Note fuel remaining and fuel flow
Accelerate sim rate
Allow 30 mins of real time to elapse
Note fuel remaining - it will be as if the sim was running at normal rate (you can also watch the chrono stop watch)

### Expected behaviour

Time dependant systems will accelerate according to sim rate.  I think this needs to be moved to the top of the fix it list as this is a long haul airplane and many people will utilize accelerated sim rates when flying.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Time acceleration is only supported up to a maximum of 4x. That is factored in, but beyond 4x we cannot detect.
