### ISSUE TITLE
[BUG] - When pushing the ANNUN LT TEST button, not all lights should light up

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#773]
### Describe the bug

When pushing the ANNUN LT TEST button, the IDENT Switch should not light up, except if the IDENT Switch was previously ON

### Steps to reproduce

- Set IDENT Switch OFF
- Push the ANNUN LT TEST button

### Expected behaviour

The IDENT Switch should not illuminate.

### Evidence

![IDENT switch not light up](https://github.com/invernyx/md11-bugs/assets/153389460/274bdd79-199d-4b51-bcee-177c0ab52dc0)

The correct display is according the uploaded photo.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next version
