### ISSUE TITLE
[BUG] - Incorrect SID EGLL DET2G

### ISSUE THREAD

**Issue by falcon71** [invernyx/md11-bugs#774]
### Describe the bug

The SID EGLL DET2G is incorrectly drawn near EPM.

### Steps to reproduce

Enter the following flightplan into the FMC:
`EGLL/27L DET2G DET Q70 ITVIP L10 RINTI UL10 LESDO UL15 BEGAR DCT GIPOL DCT LSZH/GIP14.I14`
Then check the route in plan mode. An unexpected long line will be drawn to the south at EPM.

### Expected behaviour

I would expect a left turn at D161J/EPM direct to DET32.

### Evidence

![md11_DET2G](https://github.com/invernyx/md11-bugs/assets/3109174/510c303d-5993-4b6e-baff-0e46525d580d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

EGLL

### Arrival

LSZH

### Cruise level

FL350

### ZFW

128,8 Tonnes

### CG

26.7

### Fuel

20 Tonnes

### Cost index

30

### Route

EGLL/27L DET2G DET Q70 ITVIP L10 RINTI UL10 LESDO UL15 BEGAR DCT GIPOL DCT LSZH/GIP14.I14

### Location

EPM

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This is resolved as of 0.30+
