### ISSUE TITLE
[BUG] - Incorrect VNAV altitude at LSZH GIP14

### ISSUE THREAD

**Issue by falcon71** [invernyx/md11-bugs#775]
### Describe the bug

VNAV is too high at LSZH

### Steps to reproduce

Enter the following route:
`EGLL/27L DET2G DET Q70 ITVIP L10 RINTI UL10 LESDO UL15 BEGAR DCT GIPOL DCT LSZH/GIP14.I14`

Then check the calculated altitudes. The FMC calculates FL171 at ZH408. This is way to high. VNAV did actually try to fly that STAR that high and I did not end up anywhere near the ILS.

When changing the altitude restriction at ZH410 to `AT 6000`, the FMC will calculate a way more plausible FL91 at ZH408.

### Expected behaviour

I would expect a more plausible altitude at ZH408, like below FL100.

### Evidence

The STAR as it is defined in the Navigraph Database:
![md11_gi14_before_at](https://github.com/invernyx/md11-bugs/assets/3109174/eb790fcb-3f24-420b-ba38-2a3785967bee)
A more plausible calculation, when chaning ZH408 to AT 6000:
![md11_gi14_after_at](https://github.com/invernyx/md11-bugs/assets/3109174/c2aa9747-5b65-4766-9266-60d5f9c90a97)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Altitude

FL171

### Departure

EGLL

### Arrival

LSZH

### Cruise level

FL350

### ZFW

128,8 Tonnes

### CG

26.7

### Fuel

20 Tonnes

### Cost index

30

### Route

EGLL/27L DET2G DET Q70 ITVIP L10 RINTI UL10 LESDO UL15 BEGAR DCT GIPOL DCT LSZH/GIP14.I14

### Location

ZH408

### Agreement

- [X] Yes

**Comment by CptUnicorn** [comment]
Can confirm. I flew into ZUR ILS34 a few says ago and the VNAV altitudes were way off. I was above FL150 when i should have been at FL70 and lower.

**Comment by turbofandude** [comment]
I have made some changes to improve excessive predictions - it will be further improved by refined prediction data
