### ISSUE TITLE
[BUG] - Engine fan blades not visible when looking thru rear of engine

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#776]
### Describe the bug

When looking through the rear of engine, the fan blades are not visible

### Expected behaviour

Fan blades visible

### Evidence

![FlightSimulator_2023_12_14_16_48_36_333](https://github.com/invernyx/md11-bugs/assets/148836830/1dd0f16b-5755-45f2-adce-a66dc00c9e1b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been fixed in the latest model update.
