### ISSUE TITLE
[BUG] - Degrees symbol placement on PROG page

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#777]
### Describe the bug

The degrees symbol on the PROG page of the FMC is not in the correct place.

### Steps to reproduce

In cruise, pull up PROG page.

### Expected behaviour

Degree symbol placed after the second temp digit

### Evidence

![FlightSimulator_2023_12_14_17_31_34_556](https://github.com/invernyx/md11-bugs/assets/148836830/551b9461-ff57-4377-94a0-3bb3d5190519)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.29+
