### ISSUE TITLE
[BUG] - Nosedive on final after Autopilot disconnect

### ISSUE THREAD

**Issue by Thunderbird1337** [invernyx/md11-bugs#780]
### Describe the bug

Plane wants to kill me if i disengage the AP

### Steps to reproduce

-Fly an unspecified route
-go to final approach
-disconnect AP at 500 call
-enjoy nose going down to the ground

Elev trim went in the final app phase every 1-2sec  in .1 steps higher (startet at 8 and when i disconnected the AP it was 10.2 or so. CG=25.xy). When i disconnected the AP, the nose went down and i wasnt able to bring her back in a safe flightposition, till i hit the ground. 

### Expected behaviour

I dont wanna die :(

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [x] Yes

**Comment by Leemazz** [comment]
Had the same thing again after the latest update , it seems to me it is the Low Speed Protection putting the plane in a dive . Increasing thrust manually seemed to pull it out of the dive .

**Comment by kdries** [comment]
Same thing happened to me landing ILS27 at EGNX. Nose dive on short final after disconnecting the AP resulting in the obvious crash.

Stab trim: 15.7 (as set by the automation)
CG: 38.2 (as set by the dispatcher)

**Comment by turbofandude** [comment]
This should be resolved in 0.25+
