### ISSUE TITLE
[BUG] - bumping speed on the PFD

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#782]
### Describe the bug

Speed bug jumps permanently 

### Steps to reproduce

this happens, if I fly a longhaul flight (more than 7 or 8 hours).
After a few hours of flying this issue will disappear.

### Expected behaviour

no jumging speed bugs on the PFD

### Evidence

https://github.com/invernyx/md11-bugs/assets/83859593/1a925678-91ce-4b0f-b80d-46ff731df797

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

4 degrees up

### Bank

0 degree

### Heading

286°

### Altitude

28000

### Departure

rjbb

### Arrival

LGAV

### Cruise level

FL280ß

### ZFW

360,6

### CG

25

### Fuel

245000

### Cost index

15

### Route

RJBB/24R N0495F260 HELEN2 OYE Y39 MIHOU Y38 SAPRA Y685 BULGA G585 SEL G597 GOGET Y697 NOPIK G597 BINIL/N0506F280 Y697 ANSIM G597 AGAVO/K0932S0840 A591 IKEKA W4 HCH W200 DOVIV W55 CG W34 VYK B215 LUVES/K0893S0980 B215 YHD W199 YBL V67 CHW W619 BILDA W112 PURPA/N0478F320 G206 TAPIS P173 DAVET B475 DOLOS B449 MAMED P130 ARBAT/N0470F340 P130 REBLO UB111 KAR UW27 ERZ UA4 SIV UA285 GEM UW705 BADOX/N0470F360 UW705 HAY UT54 IMR UR32 RIPLI UL995 VARIX VARI3C LGAV/03R

### Location

between Japan and South-Korea

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
does this consistently happen? And does it happen at a consistent time?

**Comment by uwiuke** [comment]
This happens at the beginning of the flight constantly - on very long flights it disappears after a few hoursit seems it has something to do with the weight balance if the plane goes to maximum weights
    Gesendet von Outlook für iOS
  

 Von: TheFightingRaven ***@***.***>Gesendet: Dienstag, Dezember 19, 2023 8:54 PMAn: invernyx/md11-bugs ***@***.***>Cc: uwiuke ***@***.***>; Author ***@***.***>Betreff: Re: [invernyx/md11-bugs] [BUG] - bumping speed on the PFD (Issue #782) 
does this consistently happen? And does it happen at a consistent time?

**Comment by turbofandude** [comment]
This should have been resolved by now.
