### ISSUE TITLE
[SUGGESTION] - Engine animations need "smoothing" out & fan blades texture looks flat 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#784]
### Is your feature request related to a problem? Please describe.

Animations look weird when looking at them & the fan blades look flat

### Describe the solution you'd like

For the animations to be smoother and not jittery & abit more texturing to the blades when spinning 

### Describe alternatives you've considered

Take a look at PMDGs engine animations. Looks alot more realistic 

### Additional context

https://prnt.sc/maQN91NIr-Ew

**Comment by TheFightingRaven** [comment]
0.3x will have new spinner animations
