### ISSUE TITLE
[BUG] - Gross weight and fuel changing rapidly

### ISSUE THREAD

**Issue by SamuelSamouris** [invernyx/md11-bugs#785]
### Describe the bug

The fuel and gross weight change erraticly

### Expected behaviour

Upon starting the engines the gross weight and fuel values shown on the engine page were rapidly changing.

### Evidence

Interestingly the issue stopped after roughly 25 minutes of flight.

Unfortunately due to this I didn’t get a chance to video the issue.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by uwiuke** [comment]
... could confirm this behaviour - see the short videos

https://github.com/invernyx/md11-bugs/assets/83859593/0ddae4c1-f99b-4987-891a-ef6fc6295f58


https://github.com/invernyx/md11-bugs/assets/83859593/f8a67fc1-a8b5-452f-ae52-ece257367bd2

... stopped after 22 min of flight-time

**Comment by JohnWilkins82** [comment]
Occurs to me when loaded with lots of fuel(278K LBS). Using the pax ER version.

**Comment by JohnWilkins82** [comment]
Interestingly this occurs with a GW of  505.9 and above.  Tested by adjusting the fuel in the tablet fuel loading page with the engs  on while parked at the gate.  Can confirm fuel burn will resolve this issue. 
Also it seems whatever ZFW i input in the EFB load (zfw) page it stays stuck at 291.1 Found issue 353 but it still occurs. Using the ER option.

**Comment by dr71205** [comment]
Issue persists on 29.0 (MSFS), and also yeah i did notice that when i input ZFW directly it stayed at empty weight.

**Comment by turbofandude** [comment]
Resolved in 0.37+
