### ISSUE TITLE
[SUGGESTION] -Make MD11F cargo lights come on 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#786]
### Is your feature request related to a problem? Please describe.

Cargo hold is abit dark & needs some lighting 

### Describe the solution you'd like

Cargo lights to be modelled & controlled by using the EFB 

### Describe alternatives you've considered

.

### Additional context

.

**Comment by TheFightingRaven** [comment]
this would cause weird artefacts with the msfs lighting system
