### ISSUE TITLE
[BUG] - MD11F Low FPS on doors animation 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#788]
### Describe the bug

cargo doors have low fps animations 

### Expected behaviour

Smoother animations 

### Evidence

Load up MD11F & open cargo doors 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.48+
