### ISSUE TITLE
[BUG] - VERY ANGRY - NOSE DIVING STILL HAPPENS DURING APPROACH

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#789]
### Describe the bug

Nose diving on the ILS path

### Steps to reproduce

I'm not very amused, but after a 14 hours flight the airplane still do this nose diving on the last 400 ft above ground during ILS approach. Sorry that I'm quite angry - you have no chance to correct without crashing on the ground.

### Expected behaviour

NO NOSE DIVING

### Evidence

not possible - no chance to make a video sequence of this.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by Oliverx79** [comment]
Nose Diving on Final Approach at HECA Rwy. 05L CG arround 31, Trim bewtwenn 5 and 7. Flaps Set to 50 and Speed set to 146kts as Calculated by FMC for an Flaps 50 Appr. 
Flying manuall and arroud 5 miles final the Plane dives over the nose like a Stuka, Pull Joystick full back but the Plane will not react and dive in the ground. 
On board 8tons of Fuel and 32t of Cargo.

Yesterday on a Flight to LLBG with more Cargo and Fuel on Final an Flying with a higher Speed than Calc. from the FMC the Plane wants also dive but can be bring aggain in a Stable Flying with Joystik.
