### ISSUE TITLE
[BUG] - Pushback causes ground speed to increase beyond reasonable amount

### ISSUE THREAD

**Issue by lscott122** [invernyx/md11-bugs#79]
### Describe the bug

Using GSX for pushback causes the ground speed readout to go nuts

### Steps to reproduce

Push the aircraft back with GSX, watch the ground speed

### Expected behaviour

The aircraft should not exceed the pushback speed 10-25kts on the ground.

### Evidence

![Lscw2la](https://github.com/invernyx/md11-bugs/assets/41208924/434ac647-dfa0-41ff-b07f-97caa526e512)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
With around 60 to 70 pushbacks with the GSX, I haven't had this behavior
