### ISSUE TITLE
[BUG] - Elevator trim setting on takeoff from the CDU is widely off

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#791]
### Describe the bug

The CG is accurate, however, the required trim vs the actual trim is horrendously out of whack. On takeoff the required trim needed is almost fully aft. ie. 7.2 on the CDU, but in actual fact, I need 10+ units of trim to maintain stable flight.

### Steps to reproduce

Just set up a regular flight and set up the CDU trim as per the CG onboard. Take off and trim until back pressure is released.

### Expected behaviour

To not back to have back pressure on the yoke on takeoff.

### Evidence

May be related to #771 which was tagged as a bug.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be long since resolved
