### ISSUE TITLE
[BUG] - REPLACE ME

### ISSUE THREAD

**Issue by skyvagrant4490** [invernyx/md11-bugs#792]
### Describe the bug

Landing lights are both bound to L-switch

### Expected behaviour

Controlling the landing lights doesn't work well yet. Both lights extend/retract via the left-landing light switch. The r-switch doesn't seem to do anything. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
The title was not correctly formatted. Resubmit with the title as described when you submit a new issue, the format should be "[BUG] - Bug description"
