### ISSUE TITLE
[BUG] - REPLACE ME

### ISSUE THREAD

**Issue by Nighthwk4922** [invernyx/md11-bugs#793]
### Describe the bug

Circuit breakers missing amperage labels 

### Expected behaviour

Compared with the real flight deck, all of the circuit breaker barrels should have an amperage label present. Currently, the tops of the barrels are blank. 

### Evidence

![missing labels 3](https://github.com/invernyx/md11-bugs/assets/112587069/c2f1a713-8106-4f91-b719-a5bf17686905)
![missing labels 2](https://github.com/invernyx/md11-bugs/assets/112587069/d4e7f686-a4e5-4202-85b7-c7477ffdc550)
![missing labels 1](https://github.com/invernyx/md11-bugs/assets/112587069/0a47a2b0-c421-498c-8448-ea645e4f2541)
![example of labels](https://github.com/invernyx/md11-bugs/assets/112587069/56afddfb-68dc-4e2d-8519-65437be9cf5d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
The title was not correctly formatted. Resubmit with the title as described when you submit a new issue, the format should be "[BUG] - Bug description"
