### ISSUE TITLE
Nose dive on final (I know, too many posts)

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#794]
### Describe the bug

I am definitely beating a dead horse on this, but I noticed something this time around. On the CONFIG page, when I disconnected the AP I noticed the autopilot had been holding quiet a bit of back pressure. As soon as I moved my joystick the yoke centered and the nose tried to dip. In the video, (please excuse the erratic controls. It's difficult to handle a "nose heavy plane") But as soon as I moved the throttled forward and at basically 20 feet the nose went down even with full back pressure and good speed. If you look at the CONFIG page on the right side of the screen in the video, you can see my control inputs. I apply full back pressure but the nose falls and. Not sure if this specific thing has already been noted, but I thought you guys would like a good laugh nonetheless. 

### Steps to reproduce

Just like any other nose dive post.

### Expected behaviour

...

### Evidence

https://medal.tv/games/microsoft-flight-simulator/clips/1K8o6MwYGIL3tl/d1337nemDoNy?invite=cr-MSxJRlYsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
The title was not correctly formatted. Resubmit with the title as described when you submit a new issue, the format should be "[BUG] - Bug description"
