### ISSUE TITLE
[BUG] - Pitch trim excessive nose up with flaps 50

### ISSUE THREAD

**Issue by nickjzx** [invernyx/md11-bugs#795]
### Describe the bug

Nose up trim when using f laps 50 is basically full nose up

### Steps to reproduce

Fly approach at Flaps 50, somewhere around 450000lb+ area

### Expected behaviour

Not going from 9.0 on trim to 15.5 and still requiring lots of back pressure to keep the nose up.

### Evidence

![FS2020_20231219_213536_R](https://github.com/invernyx/md11-bugs/assets/80855520/7b8aa020-ff2e-49c1-8bcc-3a40dbe8b0bc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by nickjzx** [comment]
Looks like 771 makes mention of this as well, although it's more manageable at flaps 35.

**Comment by CptUnicorn** [comment]
> Looks like 771 makes mention of this as well, although it's more manageable at flaps 35.

That was my post. I usually land with flaps 50, but if its better at flaps 35, I will definitely try that and see what happens.

**Comment by CptUnicorn** [comment]
I have also, if you see post #794, that the autopilot has quite a bit of back pressure when on the glideslope. The nose dive only happens once you manipulate the elevator axis.

**Comment by nickjzx** [comment]
Flew flaps 50 on .26 last night at nearly max ZFW and this seemed to be fixed. Great work guys!
