### ISSUE TITLE
[BUG] - Analog standby arrow flickering 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#798]
### Describe the bug

When in cruise, arrow keeps flickering/jumping

### Expected behaviour

Not to flicker 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.55+
