### ISSUE TITLE
[BUG] - Pitch seems abit too sensitive 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#799]
### Describe the bug

Pitch seems to aggressive/sensitive  

### Steps to reproduce

Handfly the aircraft on takeoff 

### Expected behaviour

Less aggressive/smoother 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Agreed, it's very easy to overrotate. Roll is fine, just pitch is a bit screwed up ATM

**Comment by TheFightingRaven** [comment]
all the real pilots disagree with you
