### ISSUE TITLE
[BUG] - Error 44 message downloading to community folder

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#80]
### Describe the bug

I GET A ERROR 44 MESSAGE WHEN TRYING TO DOWNLOAD INTO COMMUNITY FOLDER DOWNLOADING OUTSIDE OF COMMUNITY FOLDER THEN COPYING AND PASTING INTO COMMUNITY FOLDER WORKED. BUT THE DIRECT PATH INTO COMMUNITY FOLDER DID NOT AND IT SHOWED ERROR 44 MESSAGE. 

### Steps to reproduce

WHEN IN THE INSTALLOR CHOOSING THE COMMUNITY FOLDER ROUTE TO DOWNLOAD IN 

### Expected behaviour

TO DOWNLOAD INTO COMMUNITY FOLDER WITH NO ISSUE. 

### Evidence

![TFDI](https://github.com/invernyx/md11-bugs/assets/148557328/124a1f17-9200-4916-a571-523e6517c01b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Where is your Microsoft Community folder located?

**Comment by MountainManB** [comment]
C:\Users\username\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community

**Comment by MountainManB** [comment]
Here is a update I believe is the issue. I have my sim downloaded and installed on my D drive. I have the MS Store version of the sim. My community folder is in c drive under app data and that whole path.

**Comment by GenericNerd** [comment]
I've applied a "wontfix" and I'll close this issue for now. Though this *did* in fact happen, I'm not entirely sure there's anything we can do until we have a machine that is affected by it to investigate it further. Even then, it could be something to do with Advanced Installer which we may have to report.
