### ISSUE TITLE
[BUG] - Aircraft symbol doesn't line up with magenta line 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#801]
### Describe the bug

Aircraft symbol doesn't line up with magenta line  when fully zoomed in 

### Expected behaviour

To be properly aligned 

### Evidence

![Screenshot_1](https://github.com/invernyx/md11-bugs/assets/70169249/dac21a6f-4dde-4972-a093-1fe475e0c328)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
In the picture it shows below the aircraft symbol L0.2 which means you are 0.2 miles left of the magenta, thus behaving correctly. Also nose pointing to the left due to crosswind.
