### ISSUE TITLE
[BUG] - Random 360 flying on NAT

### ISSUE THREAD

**Issue by nickjzx** [invernyx/md11-bugs#804]
### Describe the bug

Plane did a random 360 on the NAT eastbound.

### Steps to reproduce

Fly transatlantic, plane may or may not try to do a 360. 

### Expected behaviour

Plane to fly the track as laid out and not perform 360's.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/80855520/6a6c6cd9-0e62-4142-adbf-b1b9fcebe178)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

KMEM

### Arrival

EHAM

### Cruise level

FL340

### ZFW

438,000

### CG

28.4

### Fuel

86000lbs

### Cost index

20

### Route

[KMEM GOETZ7 DIYAB DCT BNA Q32 SWAPP Q34 RBV Q430 ACK DCT TUSKY N321A ELSIR NATS SOVED DCT KUGUR DCT BELZU DCT MASOP DCT BELOX L603 LAMSO LAMS2A EHAM]

### Location

Over the atlantic started at/just after 53N 040W

### Agreement

- [X] Yes

**Comment by nickjzx** [comment]
I did a Direct to to the next NAT waypoint, it showed a left 360 on the waypoint so I've done a direct to the next waypoint just before SOVED.

**Comment by CptUnicorn** [comment]
I've noticed this on non NAT routes. Had a few over Japan on a previous build.

**Comment by turbofandude** [comment]
We solved a few scenarios that could cause weird behavior like this in 0.30+. Please re-test and re-open if it continues.
