### ISSUE TITLE
[BUG] - EFB View DEP/ARR charts buttons broken

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#805]
### Describe the bug

As of the latest 0.26 version, on the Dispatch page in the EFB the view departure and arrival airport charts buttons don't work anymore. Arrival button does nothing and the departure button just switches to the charts page. If you go to charts page yourself and type in any icao, then the departure button will take you to that same page. It's same as pressing the charts button on the top.

### Steps to reproduce

Import simbrief flight plan and press the dep/arr charts buttons.

### Expected behaviour

Revert to the working buttons as before the 0.26 release

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next EFB version
