### ISSUE TITLE
[BUG] - Annunciator Light Bright/Dim Switch Inop

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#807]
### Describe the bug

The annunciator light bright/dim switch does not change brightness of annunciator lights

### Steps to reproduce

Press ANNUN LT BRT/DIM switch, observe intensity of annunciator lights does not change

### Expected behaviour

Switches between bright and dim settings

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
@jhattermann What do you think? Once we get the annunciators finished, how can we best solve this?

**Comment by jhattermann** [comment]
For MSFS we may be able to do it with XML behavior entries, basically assign every annunciator a condition for half and full brightness based on the brt/dim variable state. For P3D we could just have duplicate meshes that move forward from behind the buttons to multiply the brightness

**Comment by jhattermann** [comment]
We're going to need another variable for the state of BRT/DIM

**Comment by TheFightingRaven** [comment]
fixed 0.66
