### ISSUE TITLE
[BUG] - Annunciator Lights That Remain On Following Annun Lt Test (0.26.1)

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#808]
### Describe the bug

Some annunciator lights remain illuminated after completing the annunciator light test (FUEL DUMP EMER STOP, LWR YAW DAMP B - OFF)

### Expected behaviour

Described lights should extinguish following release of the annunciator light test button.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.27+
