### ISSUE TITLE
Feauture - Please add left/right mouseclick support in the whole cockpit

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#809]
### Describe the bug

All knobs ae based on functional with mouse scroll, thats something I dislike in this plane atm. Left/right mousecllick support will be amazing

### Steps to reproduce

-

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by Nighthwk4922** [comment]
Seconded. All of the other payware airliners support this interaction method, so it'd be great if the MD-11 could too.
