### ISSUE TITLE
[BUG] - Approach Selection in LATREV is missing the L or R runway indentifier

### ISSUE THREAD

**Issue by 717driver** [invernyx/md11-bugs#81]
### Describe the bug

When selecting and arrival and approach when LatRev'ing off of the last waypoint on your FP, there are approaches that have a Y, X, Z type identifier such as ILSZ22R at KDTW.  This is shown in the FMS as ILSZ22 and is missing the "R" designator

### Steps to reproduce

Whenever I select the last waypoint to load the STAR and APPR for the leg, I am trying to select the ILS Z 22R at KDTW and it only shows as "ILSZ22" instead of "ILSZ22R".  It loads the correct approach, but doesn't display which runway 22L or 22R (there is no ILS Z 22L, so it's an easy deduction, but still is not correct).  

### Expected behaviour

FMS should show the entire runway identifier and not just the numerical identifier.

### Evidence

![ilsz22r](https://github.com/invernyx/md11-bugs/assets/49132291/cb867e2c-4f57-462d-8553-cff370d21dc0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0AGL

### Departure

KMEM

### Arrival

KDTW

### Cruise level

FL410

### ZFW

346.6k

### CG

34%

### Fuel

50600lbs

### Cost index

99

### Route

CRSON7 HUMMS TINGS PXV WWODD HANBL3

### Location

On ground at KMEM loading the FMC for flight.

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.7.0.1+
