### ISSUE TITLE
[BUG] - Displays reflection on outside windows is to much and annoyinf during night operations

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#810]
### Describe the bug

Possible to remove this reflection and place the reflection in the side window like PMDG? During night operation its a bit annoying

### Expected behaviour

-

### Evidence

-
![Screenshot 2023-12-25 164625](https://github.com/invernyx/md11-bugs/assets/71586114/26cae4f4-2c75-4098-826a-9df528b16410)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by JDTiger** [comment]
Also it shouldn't be there either way, since the is this thing called a glareshield between the flight instruments and the window

**Comment by Daniz010** [comment]
Not planned? It shut be planned since this is first unrealistic and second
freaking anoyoing during night operations

Op wo 27 dec 2023 om 20:27 schreef TheFightingRaven <
***@***.***>

**Comment by arwasairl** [comment]
This was already fixed in an internal build this month. This was closed as not planned because you had opened a duplicate bug report. In any case, it has already been fixed but has not been released to the public as of yet.
