### ISSUE TITLE
[BUG] - GSX auto door configuration 

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#816]
### Describe the bug

Would love to see that the GSX profile maker for the TFDi MD11 makes a option to have automatic door operation since its anoying to check outside if they are done (de)boarding or etc

### Expected behaviour

-

### Evidence

-

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is not for us to do
