### ISSUE TITLE
[BUG] - decrease thrust power during stepclimb

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#819]
### Describe the bug

too low thrust power during stepclimb

### Steps to reproduce

After setting the new Flightlevel (from 290 - 310) thrust power decrease from 88 % to 84 %.
That makes no sense. It seems that after press the PROF button thrust power will set for the new flight level but not for climbing.
(climbing rate is very low - between 100 - 400 ft/min)

### Expected behaviour

Increasing thrust power for stepclimb with constant speed.

### Evidence

https://github.com/invernyx/md11-bugs/assets/83859593/588a3f74-7921-4cd5-a46b-d3e74e77bebc

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

KLAS

### Arrival

EGLL

### Cruise level

FL310

### ZFW

408700

### CG

31

### Fuel

200000

### Cost index

35

### Route

KLAS SID TUKRR DCT DVC J146 GLD DCT DSM DCT BAE DCT PECOK DCT NOTAP DCT YYB DCT YBC DCT RIKAL DCT 53N050W DCT 53N040W DCT 53N030W DCT 53N020W DCT MALOT DCT GISTI DCT EVRIN DCT JETZI DCT AMFUL DCT OCTIZ P2 SIRIC DCT EGLL

### Location

20 min after take-off in Las Vegas

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
step climbs are not properly implemented yet, additionally, you've turned all vertical modes off, indicated by the lack of a displayed mode next to the altitude on the FMA. This in an of itself is not a bug, and the stepclimbs are already reported
