### ISSUE TITLE
[BUG] - red speed

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#82]
### Describe the bug

speed shown as read outside redspeed tape

### Steps to reproduce

fly departure in nav+prof

### Expected behaviour

not do this

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/0ccea455-2aea-4d96-9ccf-ce05130edad3)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Fixed in next version
