### ISSUE TITLE
[BUG] - no correct pitch during landing

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#820]
### Describe the bug

ptich is not correct during approach

### Steps to reproduce

pitch is between 2-4 degrees down in full configuration

### Expected behaviour

pitch slightly up during landing speed in full configuration (gear down flaps full)

### Evidence

Uploading 20231229_MD11FER_05.mp4…

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
the video is not showing up, try uploading it to youtube and sending a link

**Comment by uwiuke** [comment]
https://youtu.be/FlLMYmnh51w

**Comment by TheFightingRaven** [comment]
I can't reproduce this, are you positive you had the correct weight configured in the MCDU, it looks like it's having you fly unnecessarily fast which causes the nose down attitude

**Comment by CptUnicorn** [comment]
I might be a bit late on this one, but I had the same issue just now landing in Boeing Field. My VREF was 151 with flaps 50, and when I was established on the ILS for 14R, the aircraft needed a heavy nose down attitude. I had to slow down to 130ish, well into the amber bar, to maintain the glide and a proper angle. The speed protection kicking in throughout the entire approach.



![20240125165238_1](https://github.com/invernyx/md11-bugs/assets/150947401/d164605e-71a3-48ed-80ba-b261dedc68bd)
![20240125165236_1](https://github.com/invernyx/md11-bugs/assets/150947401/ed8f523d-cbd3-4990-8ca0-d09dcb7b251a)
