### ISSUE TITLE
[BUG] - P3Dv5 cant chance fuel Weight

### ISSUE THREAD

**Issue by Mike230296** [invernyx/md11-bugs#824]
### Describe the bug

reinstalled the thing that is event viewer is saying is the crashing item but still crashing when trying to change fuel weight on EFB

### Steps to reproduce

click on Weight for fuel to change it and crashes 

### Expected behaviour

to change fuel weight

### Simulator

P3Dv5

### Crash

Yes

### Phase of flight

Pre-flight

### Departure

kmem

### Arrival

kind

### Cruise level

fl370

### ZFW

370.5

### CG

idk

### Fuel

40.3

### Cost index

51

### Route

CRSON7 HUMMS DCT PXV DCT EMBRR SMUKE2

### Location

kmem

### Agreement

- [X] Yes

**Comment by Delta064** [comment]
I've had this issue as well.

**Comment by balint221** [comment]
Same here.

**Comment by turbofandude** [comment]
Will be resolved in 0.28+
