### ISSUE TITLE
[BUG] - P3D5 - No Pull function available on the FCU dials

### ISSUE THREAD

**Issue by balint221** [invernyx/md11-bugs#828]
### Describe the bug

No Pull function available on the FCU dials

### Steps to reproduce

Try to pull any dials on the FCU.

### Expected behaviour

Should be able to pull any FCU dials.

### Simulator

P3Dv5

### Crash

No

### Phase of flight

Pre-flight

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
You need to click and drag up/down to push/pull.
