### ISSUE TITLE
[TODO] - Can not insert hold into flight plan

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#83]
### Describe the bug

Can not insert hold into flight plan. You can fill out the hold section but when you go and click insert it does not insert into the flight plan

### Steps to reproduce

FFL Plan From KONT to KOAK. Arrival was EMZOH 3. Tried to insert a hold at waypoint MYJAW. Filled out hold page and went to click insert and it did not insert into flight plan

### Expected behaviour

For the hold to be inserted into flight plan

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

KONT

### Arrival

KOAK

### Cruise level

FL380

### ZFW

356.8

### CG

31

### Fuel

30.7

### Cost index

20

### Route

KONT SNSHN5 COREZ DCT RGOOD EMZHOH3 ILS RWY 30 KOAK

### Location

Tried durning preflight and in the air and unable to insert hold

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Holds will be fully and properly supported in 0.30+
