### ISSUE TITLE
[BUG] - LSAS makes pitch trim ineffective

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#830]
### Describe the bug

With LSAS operative, pitch trim is overriden by pitch hold. If LSAS is overriden in an out of trim situatation, pihct response is either exagerated or dampened

### Steps to reproduce

Take aircraft up to altitude and speed, trim for level flight (without LSAS).
Engage LSAS, trim full up. Upon LSAS override obersve:
- If LSAS overridden with yoke pitch down, airplane first pitches up until enough pitch down is achieved
- If LSAS overridden with yoke pitch up, pitch response is violent

### Expected behaviour

Unsure what to expect due to my limited knowledge on LSAS.
However, such a scenario, as seen in the video, feels wrong.

### Evidence

https://youtu.be/7LEpvViNJGQ

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
lsas pitchhold should overwrite an out of trim situation, that's its job.

**Comment by KJA1582** [comment]
It should, and it does, _mostly_.

In fact, in the clip linked, LSAS trimmed backwards to what it should. If time permits, give it a whirl. Put the aircraft up at altitude, manually trim all the way back. Then observe the elevator trim simvar value stay put, or even return to full ANU if you manually trim back to AND
