### ISSUE TITLE
[BUG] - Center gear floats

### ISSUE THREAD

**Issue by Mike230296** [invernyx/md11-bugs#831]
### Describe the bug

Main center gear floats when on ground

### Expected behaviour

no floaty mode

### Evidence

https://drive.google.com/file/d/1k5SjHkFS_SPL-P6asJ-3N57lNa7EilCN/view?usp=sharing

### Simulator

P3Dv5

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed in 0.3x
