### ISSUE TITLE
[BUG] - Airplane systems crash/freeze after accidentally inputting wrong FMS input (MD-AV-5)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#832]
### Describe the bug

At cruise FL300 M0.815, the airplane's system simulation freezes immediately after inputting a SPD/ALT into the FPLN page on the FMC.  The caveat here is I accidentally swapped the format and entered ALT/SPD.  The sim itself plus NAVIGRAPH plus FSLTL continued to function normally.
UPDATE: The sim freezes everytime when entering/overriding existing speed/altitude on the FPLN page.

### Steps to reproduce

Input a ALT/SPD into the FLPLN page on a waypoint line
NOTE: the waypoint I inserted on was SASIE on the TRUUK2 STAR into KAFW

### Expected behaviour

S/B FMC shows FORMAT ERROR

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

FL300

### Departure

KMEM

### Arrival

KAFW

### Cruise level

FL300

### ZFW

N/A

### CG

39.6

### Fuel

42.2k lb

### Cost index

80

### Route

CHLDR5 ANSWA  LIT  PONYY TRUUK2  

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
We resolved a scenario in 0.41 that could cause this sort of behavior. Please let us know if it reoccurs with 0.41 or above.
