### ISSUE TITLE
[SUGGESTION] - Requesting lower Texture Graphics for Prepar3D variant

### ISSUE THREAD

**Issue by LislerUsernamewastooshort** [invernyx/md11-bugs#833]
### Is your feature request related to a problem? Please describe.

Hello, I'd like to request a lowered Texture variant of the MD-11 for Prepar3D if not even available to all Installers. 
I have the issue that i quickly run out of Vram in Prepar3Dv5 that no matter where i go i wont get very far. Some people like me may run into performance issues du to their system limitations (I.e. in my case only a 3070TI with 8GB Vram and a 11Gen CPU ) where usually they don't have an issue due to other developers not including 4k only/mostly (as said per Aaron in the collectors-chat). 

Screenshots Added
234902 - load into Default RAF Ascension [FHAW] with high Vram load
235317 - relocated to AS Frankfurt prof. [EDDF] immediately ran out of memory 
235757 - Load into AS Frankfurt prof. [EDDF] after a Simulator restart and lowering settings to medium (where possible)

![Screenshot 2024-01-01 234902](https://github.com/invernyx/md11-bugs/assets/150436818/9beaa27e-34eb-4c08-bc1d-c6cc6d448b81)
![Screenshot 2024-01-01 235317](https://github.com/invernyx/md11-bugs/assets/150436818/80e5db32-a295-44ba-9095-ef6a4d564cbd)
![Screenshot 2024-01-01 235757](https://github.com/invernyx/md11-bugs/assets/150436818/7de9425d-d958-4eeb-bb29-a4c43b22391c)

### Describe the solution you'd like

I would like the solution to be the availability of a 2k and a 1080p option in the EFB or during installation.

### Describe alternatives you've considered

I currently to be honest cant think of an alternative.

### Additional context

I hope you can make this possible, Thank you!

LislerUsernamewastooshort

**Comment by alxcpt** [comment]
Hi, do you get the the vram outage in the TFDi House Livery as well? As you used one of my converted liveries from MSFS: I have now included a variant with 4K texture. The original has 8K, I forgot P3D is such a vram hungry monstrosity. You could try if you get better performance with this.

**Comment by LislerUsernamewastooshort** [comment]
> Hi, do you get the the vram outage in the TFDi House Livery as well? As you used one of my converted liveries from MSFS: I have now included a variant with 4K texture. The original has 8K, I forgot P3D is such a vram hungry monstrosity. You could try if you get better performance with this.

Yes it sadly is the same with the house livery.

![Screenshot 2024-01-04 150027](https://github.com/invernyx/md11-bugs/assets/150436818/19ee543c-7e1d-40f6-a465-15ed271034e5)
![Screenshot 2024-01-04 145959](https://github.com/invernyx/md11-bugs/assets/150436818/b767eb72-6633-45eb-a321-4d27cec1cd47)
