### ISSUE TITLE
[BUG] - Dome lights are functional without power 

### ISSUE THREAD

**Issue by Nighthwk4922** [invernyx/md11-bugs#834]
### Describe the bug

When the aircraft is cold and dark with the battery off, pressing the DOME light button on the overhead results in the dome lights turning on. 

### Steps to reproduce

1. Load the airplane in the cold and dark state.
2. Verify battery is off and emergency lights are disarmed.
3. Press the DOME light button.
4. Observe dome lights illuminating. 

### Expected behaviour

Without any electrical power, they should not illuminate. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by Douglas-McCormick** [comment]
Meanwhile, On P3D version, The Dome light is not functioning at all.

**Comment by steve-jacko444** [comment]
agree with D Mc  Dome light fails to operate in p3d v5 regardless of power state.

**Comment by GenericNerd** [comment]
The dome light not working without power in MSFS will be resolved. Please file a different bug for the P3D version, as that is a different issue
