### ISSUE TITLE
[BUG] - CTD when inserting Airway  FP

### ISSUE THREAD

**Issue by Mike230296** [invernyx/md11-bugs#835]
### Describe the bug

put in the airways to the bit i exit it then hit insert the fmc goes off and the CTD tried with just one and it crashed

### Steps to reproduce

put in airway hit insert and then ctd

### Expected behaviour

fmc to work that i can insert airway tracks

### Simulator

P3Dv5

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

0

### Departure

rctp

### Arrival

vhhh

### Cruise level

360

### ZFW

175.1

### CG

idk

### Fuel

22700

### Cost index

35

### Route

CHAL1A CHALI T3 MKG A1 ELATO V522 ABBEY ABEY2B

### Location

C8 RCTP

### Agreement

- [X] Yes

**Comment by A320vlg** [comment]
able to reproduce when i fill in the first airway T3 to MKG CTD here the windows application log from event viewer 

Faulting application name: Prepar3D.exe, version: 5.3.17.28160, time stamp: 0x61e6ab02
Faulting module name: md11.dll, version: 0.28.0.0, time stamp: 0x6594a66b
Exception code: 0xc0000005
Fault offset: 0x00000000001c9dea
Faulting process ID: 0x681c
Faulting application start time: 0x01da3e1558af0229
Faulting application path: E:\Games\Prepar3DV5\Prepar3D.exe
Faulting module path: E:\Games\Prepar3DV5\SimObjects\Airplanes\TFDi_Design_MD-11\Panel\md11.dll
Report ID: f70bdd79-022c-479d-b14e-71020b5d4e1c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by GeneralenKenobi** [comment]
Same issue here.

https://github.com/invernyx/md11-bugs/assets/33937950/cc0ba677-1094-467e-9146-638f2073087a

**Comment by turbofandude** [comment]
Resolved in 0.29+
