### ISSUE TITLE
[BUG] - P3DV5.4 TFDI MD11 CRASH

### ISSUE THREAD

**Issue by DLHICE** [invernyx/md11-bugs#836]
### Describe the bug

P3DV5.4 TFDI MD11 CRASH

### Steps to reproduce

Faulting application name: Prepar3D.exe，version:  5.4.9.28482，time stamp: 0x6463925f
Faulting module name: ucrtbase.dll，version:  10.0.22621.2506，time stamp: 0x097c794c
Exception code:0x40000015
Fault offset:0x000000000007f62f
Faulting process ID: 0x0x36D8
Faulting application start time: 0x0x1DA3E26EF823750
Faulting application path:F:\Program Files\Lockheed Martin\Prepar3D v5\Prepar3D.exe
Faulting module path:  C:\WINDOWS\System32\ucrtbase.dll

### Expected behaviour

can fix bug or change running code,thx

### Simulator

P3Dv5

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Please resubmit with steps to reproduce.
