### ISSUE TITLE
[BUG] - Flying SID Incorrect

### ISSUE THREAD

**Issue by captJojo11** [invernyx/md11-bugs#838]
### Describe the bug

Flying EDDM INPU2S incorrect

### Steps to reproduce

![20240103161318_1](https://github.com/invernyx/md11-bugs/assets/150375285/0662b91c-1541-494b-a8cc-b9e2ace43da6)

### Expected behaviour

Following the SID

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Takeoff

### Departure

EDDM

### Arrival

EDDP

### Cruise level

FL040-FL050

### ZFW

151.1t

### CG

N/A

### Fuel

19.5t

### Cost index

140

### Route

EDDM/26L N0483F300 INPU2S INPUD Y102 UPALA M726 LASGA T953 VOCIM/N0483F290 T954 GOXLI GOXL1V EDDP/26L

### Location

DM051 to DM 056

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This is resolved in 0.30+
