### ISSUE TITLE
[BUG] - Bleed Panel

### ISSUE THREAD

**Issue by captJojo11** [invernyx/md11-bugs#839]
### Describe the bug

Bleed Panel not completely illuminated

### Expected behaviour

Correct illuminated Bleed Panel

### Evidence

![20240103162000_1](https://github.com/invernyx/md11-bugs/assets/150375285/d2210632-28ac-426a-b87e-d1166f61290e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#553
