### ISSUE TITLE
[BUG] - IRS not aligning to correct position

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#84]
### Describe the bug

IRS is not aligning me to correct position.  

### Steps to reproduce

Sitting on the ground at KONT gate 2c at UPS ramp. Tried to align the IRS and it thinks i am about 100 nm away from the airport. Tried to realign 3 times same situation happens. 

### Expected behaviour

For the IRS to correctly align to correct position on airport 

### Evidence

![Desktop Screenshot 2023 10 21 - 04 50 44 56](https://github.com/invernyx/md11-bugs/assets/148557328/a797e9c2-0242-4e34-adf8-7caffd89964e)
![Microsoft Flight Simulator Screenshot 2023 10 21 - 04 52 10 53](https://github.com/invernyx/md11-bugs/assets/148557328/ed551622-79b8-4f33-84f2-b0e4afb8ccde)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

940

### Agreement

- [X] Yes

**Comment by MountainManB** [comment]
![Microsoft Flight Simulator Screenshot 2023 10 21 - 05 52 38 40](https://github.com/invernyx/md11-bugs/assets/148557328/41956da9-9680-437e-ad14-248e097944a3)

**Comment by turbofandude** [comment]
This should be resolved in 0.7.0.1.
