### ISSUE TITLE
[BUG] - Langing Gear animation

### ISSUE THREAD

**Issue by captJojo11** [invernyx/md11-bugs#840]
### Describe the bug

Stuttering animation

### Expected behaviour

Smooth Animation

### Evidence

https://github.com/invernyx/md11-bugs/assets/150375285/e33dec4a-dd57-4844-ad1e-a3b32a5f3355

https://github.com/invernyx/md11-bugs/assets/150375285/85083188-7451-4c11-a2e3-8938acc93c7e

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by Mike230296** [comment]
same on p3d version

**Comment by turbofandude** [comment]
This will be resolved in the art update.
