### ISSUE TITLE
[BUG] - P3D Doors animation too fast

### ISSUE THREAD

**Issue by GeneralenKenobi** [invernyx/md11-bugs#841]
### Describe the bug

Passenger and cargo doors animation is too fast. When u click button to open doors on EFB they are instanlty opened.

### Expected behaviour

Slower door opening / closing animation.

### Evidence

https://github.com/invernyx/md11-bugs/assets/33937950/7b410504-b8a4-412e-a4ef-8313622d554f

### Simulator

P3Dv5

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved as of 0.48+
