### ISSUE TITLE
[BUG] -Nose Landing Lights Illuminate the Cockpit

### ISSUE THREAD

**Issue by Douglas-McCormick** [invernyx/md11-bugs#843]
### Describe the bug

The cockpit would be illuminated by the nose gear landing light while raising and lowering the landing gears.

### Expected behaviour

The cockpit would be illuminated by the nose gear landing light while raising and lowering the landing gears, suggesting the nose gear landing light not being automatically turned off during the raising process. 
The bug always occurs on both the GE_PAX and GE_F version

### Evidence

![2024-1-1_18-17-31-255](https://github.com/invernyx/md11-bugs/assets/104307400/8d0eacdc-a7ef-4643-aca0-acc12a7579cf)

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
