### ISSUE TITLE
[SUGGESTION] - Enable keyboard for the MCDU

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#844]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

PMDG 777 had a brilliant way to use the keyboard to type in the MCDU. When you press and hold TAB key on your keyboard, you can type in it. I would like to see this implemented. Another method would be a clickspot to enable keyboard but with this you always need to click the spot to enable or disable keyboard typing. Instant typing while holding a button down would be the best.

### Describe alternatives you've considered

Useing mouse

### Additional context

Nothing else

**Comment by StevenSilvaB767** [comment]
+1 Please!!

**Comment by Flyfoxswiss** [comment]
+1! And please add mouse wheel zooming and mouse moving of the charts.
And the zoom buttons (+ and -) are currently too small. If mouse wheel zooming is possible, they are actually not required at at.
