### ISSUE TITLE
[BUG] - P3DV5.4 TFDI MD11 CRASH

### ISSUE THREAD

**Issue by DLHICE** [invernyx/md11-bugs#845]
### Describe the bug

Loading TFDI MD11 CRASH(P3D version: 5.4.9.28482)

### Steps to reproduce

Normal loading  TFDI MD11 to cockpit and wait

### Expected behaviour

Fixed and able to run normally

### Evidence

Faulting application name: Prepar3D.exe，version: 5.4.9.28482，time stamp: 0x6463925f
Faulting module name: ucrtbase.dll，version: 10.0.22621.2506，time stamp: 0x097c794c
Exception code:0x40000015
Fault offset:0x000000000007f62f
Faulting process ID: 0x0x36D8
Faulting application start time: 0x0x1DA3E26EF823750
Faulting application path:F:\Program Files\Lockheed Martin\Prepar3D v5\Prepar3D.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll

### Simulator

P3Dv5

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This report does not contain enough information to reproduce this, as it does not happen to me.

**Comment by joon44** [comment]
P3D seems to be installed in the Program Files folder. This might create issues with addons

**Comment by ZZZXR200** [comment]
I use P3D5.4 too，I have this CRASH too
