### ISSUE TITLE
[BUG] - None useable SID & STARs in P3Dv4 version

### ISSUE THREAD

**Issue by Douglas-McCormick** [invernyx/md11-bugs#846]
### Describe the bug

None useable SID & STAR in Flightplan pages

### Steps to reproduce

Just prepare a normal flight, when entering SID for departure, almost none of the SID showed correct.

### Expected behaviour

Wrong SID & STAR database, maybe, please verify the default navdata provided during download, as none of the SID & STARs make sense. For example, at manila airport RPLL, using runway 06 ALPA2R for departure (pic1), after entered ALPA2R 06 (pic2), no waypoints showed in legs page (pic3). Meanwhile, I entered ALPA2V instead (pic4), the waypoints in legs page has nothing to do with the SID ALPA2V (pic5). The problems is exact the same in entering STARs
The same error have occurred in every airport I've tried, including: ZSSS, ZSNJ, ZSHC, KLGA, RPLL, KJFK, ZSPD, RCTP, suggesting a total wrong in SID & STAR database.

### Evidence

![屏幕截图 2024-01-06 192910](https://github.com/invernyx/md11-bugs/assets/104307400/6544928c-fc62-4a8e-a2a5-4055805fcd25)
![2024-1-6_19-28-37-849](https://github.com/invernyx/md11-bugs/assets/104307400/237349a6-1ad3-4234-b1e5-15e4dac6c5e4)
![2024-1-6_19-29-22-982](https://github.com/invernyx/md11-bugs/assets/104307400/d8d0a65c-4c69-4b65-b16b-94122d8c951a)
![屏幕截图 2024-01-06 193020](https://github.com/invernyx/md11-bugs/assets/104307400/bb3029e4-cb5a-489f-868f-5d93761207d1)
![2024-1-6_19-29-45-390](https://github.com/invernyx/md11-bugs/assets/104307400/24f5fb99-dc8f-4e5f-8dbf-2b3d382c02bf)

### Simulator

P3Dv4

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Departure

RPLL

### Arrival

RCTP

### Cruise level

FL250

### ZFW

not related

### CG

not related

### Fuel

not related

### Cost index

not related

### Route

SID ALPA2V
SID ALPA2R
and so on, All of the SIDs and STARs involved in my flights

### Location

In every airport I have tested, including ZSSS, ZSNJ, ZSHC, KLGA, RPLL, KJFK, ZSPD, RCTP

### Agreement

- [X] Yes

**Comment by steve-jacko444** [comment]
P3D V5 similar issue with the freighter seen planning stars into RJBB , alternate stars attempted , gave up in the end and flew a manual ILS from manually inputting waypoints from Navi graph to line me up.
ZGGG/20R K0896S1070 LMN3D LMN G471 EGEDA/K0896S1100 G471 PLT/K0891S1070 A599 ELNEX G204 MULOV V73 SUPAR B221 GOVNI/K0885S1130 B221 NINAS G327 LASAN W114 DUMET A593 AKARA/K0883S1130 A593 LAMEN/N0477F370 A593 SADLI Y590 BEDAR Y591 FUE Y35 BERTH BERTHC RJBB/24R

**Comment by Flyfoxswiss** [comment]
I noticed the same problem in P3Dv5; the navigation data base is more than three years old. Navigraph will only provide a data updater once the MD-11 is released. I tried a temporary solution by using the Navigraph data of the Boeing 717, but with no success. Either it is not compatible or I didn‘t put in in the correct folder.

**Comment by steve-jacko444** [comment]
there is a work around, from Raven.  he sugested taking the Nav data from the MSFS version and dropping it into the p3d files.   if you have the msfs version, this might be worth a try.   I have now re installed MSFS and the MD-11, i will give this a try as time permits.

**Comment by steve-jacko444** [comment]
quick note.   finding the files isnt hard. 
getting windows to move them, is another storey.   Sadly drag and drop of the folders doesn't work, there is an encryption on the MSFS files. resultant: Win 11 reads all the files.
 Procedure Legs is over 95K+ files. M11 measures them, this took a day, (Nope, I'm not running a Raspberry Pi). Today it asked if I wanted to move the files , SSD - SSD, yes. that'll be another day.   
Are the Procedure legs required? 
![Picture1](https://github.com/invernyx/md11-bugs/assets/156470813/b7ce4823-020b-40a4-b11f-aa44269f9b99)

**Comment by steve-jacko444** [comment]
THE SYSTEM IS SHOWING THE LATEST NAV DATA BASE. I'LL TRY IT TOMORROW.  Procedure legs move cancelled for now.

**Comment by turbofandude** [comment]
Navigraph has stated that they will not support the MD-11 in P3D until version 1.0. Unfortunately, this means you will have to copy the data from the MSFS version if you have it.
