### ISSUE TITLE
[BUG] - WASM Crashes on Departure

### ISSUE THREAD

**Issue by crazyforiphone** [invernyx/md11-bugs#847]
### Describe the bug

When flying the ALISS5 WASM is crashing

### Steps to reproduce

Fly the departure, WASM will crash somewhere around 30,000 feet. The full route was KSAT/31L N0484F400 ALISS5 FST J2 ELP ZONNA2 KTUS/12

I tried to fly this route twice and recieved a WASM crash for the MD11host.wasm module.

### Expected behaviour

WASM should not crash

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/10215076/0cbc1f20-d413-4e3e-97ba-3cad3155e945)
![image](https://github.com/invernyx/md11-bugs/assets/10215076/5c5fa8aa-2e5a-46c8-9a0f-e06da3ccfaa3)
![image](https://github.com/invernyx/md11-bugs/assets/10215076/7f32fbd1-0f4f-42a3-b06b-5eb8be974256)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by blacksheep57** [comment]
From my little tests, it seems it does crash with the PROFILE mode on the Autopilot, when it reaches TOC or right after it. A workaround for now is to use the Alt mode.

**Comment by cvanallen99** [comment]
I've encountered this twice as well.  KDTW/KMEM both flights.  Cruise was FL280  Happened sometime after I leveled off. EFB was fine but everything else was non responsive.  No warning/error messages.  I was in profile mode as well.  .29  Didnt encounter in previous release.

**Comment by TheFightingRaven** [comment]
I always fly in prof (today included) and never had this

**Comment by JF1997** [comment]
Hello, adding on a report for this. Flew from Memphis to Oakland tabbed into the simulator but not actively touching anything as I was using my work laptop at the time and looked over to see the aircraft in a right bank and descending but the aircraft displays were frozen showing straight and level flight at cruise and the ND was stable. Autopilot no longer worked so I quit the flight. Route was: ZUMIT5 FOXOM DCT TUL/N0479F400 DCT KK42C DCT KK45A DCT KD48Y DCT PUB DCT KD51U DCT BUGGG DCT KU51O DCT KU51M DCT KU51K DCT JSICA DCT MONOH OAKES2 and the OFP can be found here: https://www.simbrief.com/ofp/flightplans/KMEMKOAK_PDF_1706300831.pdf

**Comment by SunCountry737** [comment]
Had this same issue on the following routing:

KONT RAJEE3 AVRRY DCT NICKT J74 NABOB DCT KA33W DCT KK39A DCT
KK48G DCT STL DCT DORET J190 ZORBO J584 SLT FQM3 KEWR

After passing STL at FL350 in PROF could not click anything in the VC other than the EFB.

**Comment by crazyforiphone** [comment]
I just had another WASM crash in 0.36. I did not get a chance to get a screenshot but you can see where things went off course in Volanta. 
![image](https://github.com/invernyx/md11-bugs/assets/10215076/aabc3ff9-2e9e-4783-be4e-48da87b8337b)

**Comment by cvanallen99** [comment]
Can confirm, still exists in .36.  Is there anything those of us that encounter this regularly can do to assist in debugging it?  I know MSFS native logging is somewhat lacking but...

**Comment by turbofandude** [comment]
Should be long resolved
