### ISSUE TITLE
[BUG] - EFB simbrief load setting doesn't work for LBs unless you view settings first

### ISSUE THREAD

**Issue by crazyforiphone** [invernyx/md11-bugs#848]
### Describe the bug

When setting the weights from the EFB for simbrief, it says the plane is not set for the correct units despite it being accurate.

### Steps to reproduce

- Load in with EFB set to LBs but don't go to the settings page
- Import the simbrief plann and try to set the weight and you will get an error.

Workaround:

- after importing the plan, click settings, the go back to the dispatch page and you will be able to import the weights with no issue

### Expected behaviour

to not have to click the settings tab to set weights

### Evidence

https://youtu.be/tndS9bOMCM0

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
it doesn't have to be the settings page, can be any other page, it's difficult to fix because of the way the settings are loaded

**Comment by GenericNerd** [comment]
This will be resolved with the next update
