### ISSUE TITLE
[BUG] - Can not enter Fix data into FMS

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#85]
### Describe the bug

Clicked on FIX page entered waypoint into fix but can not enter degrees or distance into fix page. No inputs show up and does not show on ND.

### Steps to reproduce

Sitting at KONT on the ground. Entered DINNK into fix info was able to input waypoint. Was UNABLE to put in a degree and distance to fix. does not paste into DNTKFX section. Tried to enter another waypoint of COREZ into FIX INFO and having same issue. 

### Expected behaviour

Be able to input a degree and distance into the DNTKFX section of the fix info page. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

KONT

### Arrival

KOAK

### Cruise level

940

### ZFW

356.8

### CG

35

### Fuel

30.7

### Cost index

20

### Route

KONT SNSHN 5 EMZOH3 ILS RWY 30 KOAK

### Location

Sitting at gate 2C at UPS ramp in KONT

### Agreement

- [X] Yes

**Comment by MountainManB** [comment]
You can enter a waypoint in the FIX page you just cant input the degrees or distance. When you insert a way point into the fix page It draws a green circle around the waypoint you just cant change the degree or distance for the fix.

**Comment by GenericNerd** [comment]
Added in the next version
