### ISSUE TITLE
[BUG] - cannot adjust digital standby altimeter 

### ISSUE THREAD

**Issue by cvanallen99** [invernyx/md11-bugs#854]
### Describe the bug

there is no click/scroll location for the standby altimeter

### Steps to reproduce

Only noticed this when I used "B" to set my altimeter.  B does change all 3 altimeters but when you set the captain and FO altimeters to STD, the digital standby remains on whatever it was set to with "B".  There is no click spot on it to set it to standard either with a push/pull or scroll. 

### Expected behaviour

should be able to set the standby altimeter pressure

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Altitude

FL200

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#738
