### ISSUE TITLE
[SUGGESTION] - Miscellaneous Ground

### ISSUE THREAD

**Issue by StevenSilvaB767** [invernyx/md11-bugs#855]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Additional context

Add please!!

1. It would be great to see an air conditioning unit for operations in hot airports in the Caribbean, deserts with high temperatures or situations that require it

2. maintenance and service vehicles, stairs (for places far from the airport) etc.

**Comment by GenericNerd** [comment]
Please follow the format for submitting suggestions.
