### ISSUE TITLE
controller noise causes disconnect of Auto flight. 

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#857]
### Describe the bug

controller value fluctuations of approx. 10-15 units, cause movement of the control column forcing an exit from Auto flight. 

### Steps to reproduce

close Spadnext, issue stops.   Reopen spad next, issue persists. 
within Spad Next open and add controller A/C specific profile damping to prevent this occurring. both in elevator and roll moments.  this hasn't been an issue for the 717 or my PMDG & FSLabs products. 

### Expected behaviour

is this the right box for this comment? 
can input sensitivity for controllers be reduced prevent this?  currently have 75 units of deadzone dialled in for this airplane. 

### Simulator

P3Dv5

### Crash

No

### Phase of flight

Pre-flight

### Pitch

10degrees climb, level, and in decent.

### Bank

-/+ 20 degrees in climbout

### Heading

all

### Altitude

4000+

### Departure

ZGGG

### Arrival

RJBB

### Cruise level

fl350

### ZFW

185.600lbs

### CG

31

### Fuel

35.800lbs

### Cost index

20

### Route

ZGGG/20R K0896S1070 LMN3D LMN G471 EGEDA/K0896S1100 G471 PLT/K0891S1070 A599 ELNEX G204 MULOV V73 SUPAR B221 GOVNI/K0885S1130 B221 NINAS G327 LASAN W114 DUMET A593 AKARA/K0883S1130 A593 LAMEN/N0477F370 A593 SADLI Y590 BEDAR Y591 FUE Y35 BERTH BERTHC RJBB/24R

### Location

throughout flight.

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
we have an overforce disable option to prevent this, can be found in the EFB settings

**Comment by steve-jacko444** [comment]
thanks FightingRaven I'll look it up.
