### ISSUE TITLE
SUGESTION - provide a key board in the efb for data entry

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#859]
### Is your feature request related to a problem? Please describe.

provide a key board in the efb for data entry, wouldn't this be a feature for a real life EFB tablet. 

### Describe the solution you'd like

for the data entry pages for fuel, payload etc, please can we have a clickable keyboard to input this data? 

### Describe alternatives you've considered

entry directly to the fmc? 

### Additional context

![Picture1](https://github.com/invernyx/md11-bugs/assets/156470813/99f12945-dc07-4b50-9d9f-861e3e7e2545)

**Comment by GenericNerd** [comment]
Entry in to the EFB is already possible, and we do not think that this would be a feature that most users would benefit from.
