### ISSUE TITLE
[BUG] - Unable to maintain CRZ speed with high headwind component

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#861]
### Describe the bug

Autoflight is unable to maintain speed during cruise with a high headwind component

### Steps to reproduce

![image](https://github.com/invernyx/md11-bugs/assets/6001596/59f2eace-5bd4-499e-b6a0-21a3bc4f61f4)

### Expected behaviour

Autoflight is able to maintain speed in any condition.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/6001596/59f2eace-5bd4-499e-b6a0-21a3bc4f61f4)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Pitch

4°

### Bank

0

### Heading

225

### Altitude

41000

### Departure

EDDL

### Arrival

LEMG

### Cruise level

FL410

### ZFW

152.0

### CG

32.0

### Fuel

12200kg

### Cost index

124

### Route

EDDL/23L N0464F240 MODR1K MODRU Z717 MAS UM617 SISGA/N0473F400 UM617 CIV/N0472F410 N872 MEDIL UN872 KOVIN UM728 RESMI UN857 DISAK DCT ARKIP DCT ARNAV DCT LMG DCT UVELI DCT OSMOB DCT ARVID UT424 PPN UN10 CJN UL27 BLN BLN1A LEMG/12

### Location

Leg between CJN and INTAX

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
thrust and drag profiles adjusted in new flightmodel
