### ISSUE TITLE
[BUG] Potential Memory Leak/Very High VRAM Use P3D V5

### ISSUE THREAD

**Issue by KBUFAviator** [invernyx/md11-bugs#862]
### Describe the bug

Upon loading the product, VRAM usage begins at 8.3GB while at default scenery. Through powering the aircraft up and flying, the VRAM continues to climb to a high point of 16,9 GB prior to crashing the sim. 

### Steps to reproduce

Ran test 3 times. Loaded aircraft in default freighter livery, then proceeded to run through start process. Upon starting the engines, I departed and proceeded to fly a standard traffic pattern around KRND. In all 3 instances, VRAM spiked to 16,9GB and crashed the sim. 
Hardware utilized: RX6800XT with 16 GB of VRAM available. 

### Expected behaviour

I would expect VRAM use to be in line with (or slightly higher than) other in-depth simulations of transport category aircraft. 

### Evidence

![Inital load](https://github.com/invernyx/md11-bugs/assets/156609186/97f0ecf7-c4d1-4690-bc7a-f8488e9cdb29)
![Before Crash](https://github.com/invernyx/md11-bugs/assets/156609186/63c7f18d-8d48-4617-b6d9-927baea3ab86)

### Simulator

P3Dv5

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I'm seeing 7.0GB usage with the aircraft running. P3D is not known for its fantastic VRAM efficiency - please adjust your settings and repeat.
