### ISSUE TITLE
[BUG] - °/ missing on wind vector display

### ISSUE THREAD

**Issue by 09tir98** [invernyx/md11-bugs#868]
### Describe the bug

The °/ symbols are missing on the wind vector display

### Expected behaviour

When using the wind vector the format should be XXX°/ YY. Currently it just says XXX YY.

### Evidence

![oWdbU3E](https://github.com/invernyx/md11-bugs/assets/95483637/faccd23a-3c6f-4c98-8b60-197875f22f07)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [x] Yes

**Comment by turbofandude** [comment]
This will be resolved in 0.30+
