### ISSUE TITLE
[BUG] - Brakes

### ISSUE THREAD

**Issue by AlexXx88** [invernyx/md11-bugs#869]
### Describe the bug

brakes

### Steps to reproduce

brake with te plane

### Expected behaviour

Hydraulic brake gauge on green and a much powerful brake

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/104494440/2b28367b-7dff-4150-bc1c-2ed48e7890ab)
![image](https://github.com/invernyx/md11-bugs/assets/104494440/c9ea5b0d-7ba2-410d-8c4d-a0a80d885455)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
unclear
