### ISSUE TITLE
[SUGGESTION] - Working Inflight entertainment

### ISSUE THREAD

**Issue by captJojo11** [invernyx/md11-bugs#870]
### Is your feature request related to a problem? Please describe.

Since I like to fly the PAX variant and like to be in the cabin I would be happy about a change to the otherwise black screens

### Describe the solution you'd like

An IFE compareable with the iniBuilds A310, with the ability to make a custom IFE for Liveries, for example with .gif videos.
- Creative Input: A map on which the route is drawn and the current position is located

### Describe alternatives you've considered

An IFE compareable with the iniBuilds A310 without the ability to make a custom IFE for liveries

### Additional context

![md11_history_24](https://github.com/invernyx/md11-bugs/assets/150375285/08b070d5-c575-4528-bcde-679f7829f2e0)
![Finnair_MD-11_Economy_class_cabin](https://github.com/invernyx/md11-bugs/assets/150375285/b094337c-9b0a-4357-9f4b-97a1336ad2f4)
![0134131](https://github.com/invernyx/md11-bugs/assets/150375285/471727f7-08c2-4c2e-ad3a-3e3339bd429a)

**Comment by arwasairl** [comment]
While we may add a custom texture that has the ability to change, GIFs are not supported in either MSFS or P3D as both simulators require the texture to be in Direct Draw Surface format; which does not support videos. While MSFS does support animated materials, this feature is primarily used to animate material properties and not material maps.
