### ISSUE TITLE
[BUG] - Nav doesn't recognise passing of Poles

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#871]
### Describe the bug

LNAV doesn't recognise passing NOPOL and turns to circle back to NOPOL after passing NOPOL. Similar behaviour passing SOPOL or when passing near either NOPOL or SOPOL.

### Steps to reproduce

- Enter a route passing either Pole.
- Aircraft is in true heading, nav and profile modes are engaged
- After passing the Pole polar waypoint isn't cleared and aircraft circles back

DCT tot next waypoint gets the aircraft back on track.
Good to know: MSFS doesn't handle passing Poles very well and becomes extramely laggy.

### Expected behaviour

LNAV is able to follow a polar route without issue

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Pitch

4°

### Altitude

35000

### Departure

ENEV

### Arrival

PANC

### Cruise level

FL350

### ZFW

187460 kg

### CG

36.6

### Fuel

41750 kg

### Cost index

189

### Route

ENEV/17 N0477F320 EVAN2E EVANI DCT ORTEN DCT 81N000E/N0477F340 DCT NOPOL DCT 89N141W/N0472F350 80N140W 79N141W/N0479F360 DCT SCC/N0490F370 J115 CQR J155 ENN DCT PUYVO KROTO4 PANC/07R

### Location

At NOPOL

### Agreement

- [X] Yes

**Comment by Alex6511** [comment]
From the FCOM:

> Within 2 NMs prior to and 10 NMs after the pole, the FMS transitions to a wings level mode of flight while it transitions the immediate polar region.

**Comment by turbofandude** [comment]
As of 0.45+ polar mode will behave as described in the FCOM
