### ISSUE TITLE
[SUGGESTION] - Pause at TOD

### ISSUE THREAD

**Issue by turbodeas** [invernyx/md11-bugs#872]
### Is your feature request related to a problem? Please describe.

When performing a long flight, I often need to attend to other duties at home, and so can't always be near the computer.

### Describe the solution you'd like

As an MD-11 user, I'd like to ability to toggle "Pause at TOD" in the EFB or MCDU.

Intended behaviour: When I'm 20nm from the computed TOD, the simulator should fully pause, and a prompt should appear informing me of what's happened. Once I decide to unpause, the simulation should allow me to complete my flight uneventfully.

### Describe alternatives you've considered

Some other products include a "PAUSE AT TOD" and "PAUSE/UNPAUSE" toggle as an MCDU LSK selection, within a settings/config menu - this could be a good place to let the user action the unpause. It also allows the user to "properly" pause the sim at their convenience at any point in flight.

### Additional context

None at this point.

**Comment by JohnWilkins82** [comment]
I would also use this feature.

**Comment by slowreload** [comment]
I would like to third this and ability to do time acceleration would be a great addition too

**Comment by turbodeas** [comment]
Is this considered a release necessary feature?

**Comment by joon44** [comment]
This is added

**Comment by turbofandude** [comment]
Long since resolved
