### ISSUE TITLE
Cockpit freezing 

### ISSUE THREAD

**Issue by Mulder884** [invernyx/md11-bugs#873]
### Describe the bug

No more entries can be made after about 15-20 minutes. Lever/switch no longer operable. The ND display also does not move any further

### Steps to reproduce

Reproduction is difficult. I didn't make any entries for 15 minutes. Suddenly frozen

### Expected behaviour

Windows 11
64GB RAM 
DX 12
Intel i12900k
Rtx 4090

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
this is a wasm crash, we would need more information to diagnose
