### ISSUE TITLE
APU Starter sound bug

### ISSUE THREAD

**Issue by DuskyIsBored** [invernyx/md11-bugs#874]
### Describe the bug

APU Starter and Engine starter sounds play on loop.

### Steps to reproduce

Bind switch or button with APU starter.

### Expected behaviour

Starter sounds will loop.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
When you say "bind switch to APU starter", what do you mean?

**Comment by DuskyIsBored** [comment]
On my hotas throttle I had a switch set to the apu starter. Since unbinding that switch I no longer have the issue. 
![17168605480264059978052508788302](https://github.com/invernyx/md11-bugs/assets/110954428/20ad2f12-3c1e-4264-9412-0ddef2ffb1eb)

**Comment by turbofandude** [comment]
I am going to close this as this is not an issue with the MD per-se, as it is a hardware binding conflict.
