### ISSUE TITLE
[BUG] - auto anitice switch wrong label

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#875]
### Describe the bug

the button for the automatic antiice says "ON"

### Expected behaviour

when pressed it should say "manual" in amber

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/5765e450-07d4-4fc6-86b0-2711ddbef2c0)

### Simulator

P3Dv4, P3Dv5, P3Dv6, Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@turbofandude 
Issue reported in: https://github.com/invernyx/md11-bugs/issues/821
