### ISSUE TITLE
[SUGGESTION] - EFB Charts Handling in P3DV5

### ISSUE THREAD

**Issue by Flyfoxswiss** [invernyx/md11-bugs#878]
### Is your feature request related to a problem? Please describe.

Zooming charts on the EFB is currently a pain, as the zoom buttons and click spots (+ and -) are too small.

### Describe the solution you'd like

Please add mouse wheel zooming and mouse moving feature.

In addition, reducing the tilt angle of the EFB would ease its usage.

### Describe alternatives you've considered

Alternatively (but much less convenient) would be larger zoom buttons and click spots.

### Additional context

none

**Comment by GenericNerd** [comment]
P3D is likely not going to have charts on the EFB in the first place. If you meant the Microsoft Flight Simulator version, there is already a bug open regarding the behaviour and we may look and tweaking it to improve the user experience.
