### ISSUE TITLE
BUG - VISUAL- P3D V5 LANDING LIGHT ILLUMINATES COCKPIT

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#879]
### Describe the bug

FWD GEAR LIGHTS ILLUMINATED COCKPIT ON GEAR RETRACTION IN DEARK ON TAKE OFF. 

### Expected behaviour

Landing gear lighting should not illuminate cockpit. 717 does not have this issue, or with the red beacon, maybe a copy and paste to resolve? 

### Simulator

P3Dv5

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by steve-jacko444** [comment]
LIGHT MASK VALUES?

**Comment by GenericNerd** [comment]
This will be fixed in the next releease.
