### ISSUE TITLE
BUG - THRUST NOT REDUCED ON LEVELING OFF AT CRUISE.

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#880]
### Describe the bug

Thrust is held on auto throttle at max N1 after leveling off , causing an overspeed. 

### Steps to reproduce

several flights have shown this behaviour, different airfields routes and alt's. 
image taken just after auto throttle rolled back to reduce the speed. 
![image](https://github.com/invernyx/md11-bugs/assets/156470813/4ccca4d4-70a9-4586-9eb1-99ae5270c8fe)
i'll repeat it and make a note of the time taken to roll back, speed attained . please let me know what else you need data wise to add to the info. 

### Expected behaviour

throttle should roll back under auto throttle to reduce from climb power to cruise power. 

### Simulator

P3Dv5

### Crash

No

### Phase of flight

Cruise

### Pitch

0

### Bank

0

### Heading

155

### Altitude

37000

### Departure

PANC

### Arrival

CJJY

### Cruise level

FL370

### ZFW

202.8 KG

### CG

34

### Fuel

28.8

### Cost index

200

### Route

PANC/07L DCT YAK J541 BERGS DCT SQM DCT PR DCT KEINN APASS7 CYYJ/09

### Location

TOP OF CLIMB

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Insert [BUG] into topic  so it wont be closed.

**Comment by steve-jacko444** [comment]
[Presentation1.pdf](https://github.com/invernyx/md11-bugs/files/14323051/Presentation1.pdf)

**Comment by TheFightingRaven** [comment]
plane is reducing thrust, seems a sim big it kept accelerating
