### ISSUE TITLE
BUG - UNuseable SID & STARs in p3d v5

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#881]
### Describe the bug

transition from last flight WP to first in STAR routes to to unknown location

### Steps to reproduce

updated nav data as per "Thefightingraven" instructions, route plots ok in FMS, except time from last WP to first on the STAR is 7 hrs.  
![Picture1](https://github.com/invernyx/md11-bugs/assets/156470813/687e6b3d-13f6-4fcd-9637-9217227fe53d)
![Picture2](https://github.com/invernyx/md11-bugs/assets/156470813/05b16754-667a-44fa-ada1-0715d53b8da2)
![Picture3](https://github.com/invernyx/md11-bugs/assets/156470813/aff8fb71-0225-44f9-8ed6-8938e22042b9)

### Expected behaviour

To complete the flight route direct to the first wp of a STAR.

### Evidence

images as above 
[PANCCYYJ_PDF_1708019771.pdf](https://github.com/invernyx/md11-bugs/files/14313928/PANCCYYJ_PDF_1708019771.pdf)

### Simulator

P3Dv5

### Crash

No

### Phase of flight

Cruise

### Altitude

37000

### Departure

PANC

### Arrival

CYYJ

### Cruise level

FL370

### ZFW

202.8 KG

### CG

34

### Fuel

28.8 KG

### Cost index

200

### Route

PANC/07L DCT YAK J541 BERGS DCT SQM DCT PR DCT KEINN APASS7 CYYJ/09

### Location

KEINN TO BAGMI (APASS7)CYYJ

### Agreement

- [X] Yes

**Comment by steve-jacko444** [comment]
![Picture2](https://github.com/invernyx/md11-bugs/assets/156470813/ce2f3a60-60f5-4c87-9951-af827dd2441c)
![Picture1](https://github.com/invernyx/md11-bugs/assets/156470813/9155048d-8b1c-448c-8a89-0762265647d7)

**Comment by TheFightingRaven** [comment]
fixed in 0.36
