### ISSUE TITLE
[BUG] - TCAS TEST , DISPLAY OF OTHER A/C NOT IMPLEMENTED

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#884]
### Describe the bug

TRANSPONDER , AND TCAS NOT SHOWING TRAFFIC OR TEST DISPLAY. 

### Steps to reproduce

EVERY FLIGHT WITH TRAFFIC, NEVER ANYTHING ON THE DISPLAY. 

### Expected behaviour

RADAR DISPLAY TO DISPLAY OTHER TRAFFIC, ALERTS, AND PRODUCE TEST DISPLAY 

### Simulator

P3Dv5

### Agreement

- [X] Yes

**Comment by steve-jacko444** [comment]
![Picture2](https://github.com/invernyx/md11-bugs/assets/156470813/0cb1d930-5820-4e13-806d-864b7d93c585)

**Comment by TheFightingRaven** [comment]
#276
