### ISSUE TITLE
[BUG] - Anti ice lights on OH  panel do not illuminate P3D V5

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#885]
### Describe the bug

Activating ENG 1. 2 . 3 WING / TAIL  de ice does not illuminate switches on OH Panel. 

### Expected behaviour

both multi panel annunciation and and OH panel switch illumination expected 
windshield switch lights do work. only once the RH window switch is pressed. 
![Picture3](https://github.com/invernyx/md11-bugs/assets/156470813/befbd4f1-b541-4dbe-860e-1b67f311dc5a)

### Simulator

P3Dv5

### Crash

No

### Agreement

- [X] Yes

**Comment by steve-jacko444** [comment]
![Uploading Picture1.png…]()

**Comment by steve-jacko444** [comment]
![Picture1](https://github.com/invernyx/md11-bugs/assets/156470813/419ea88b-577f-4627-a7df-860c313c8a42)

**Comment by GenericNerd** [comment]
@arwasairl Has this been fixed in the latest version?

**Comment by arwasairl** [comment]
@GenericNerd I don't believe so, not for P3D specifically

**Comment by turbofandude** [comment]
Since resolved
