### ISSUE TITLE
[BUG] -Estimated time to go for waypoints on FMS & PFD

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#886]
### Describe the bug

time for wp eta should display time to go , not same time per each wp t, not show as the same time across the route. 

### Steps to reproduce

I will run other flights on other routes to re validate this, PSA picture. 6 way point showing same eta. 
When it updates subsequent WP ETA  all update to the same eta. 
![Picture1](https://github.com/invernyx/md11-bugs/assets/156470813/472c03aa-ab82-482b-900a-c331f3a058ed)

### Expected behaviour

should display time to go from current position, to the WP, this should update relative to the WP as position changes. and should be different at each WP

### Evidence

please see image at steps to  &
![Picture1](https://github.com/invernyx/md11-bugs/assets/156470813/f105775a-de01-4640-88d2-f4b8776b0d5c)

### Simulator

P3Dv5

### Crash

No

### Phase of flight

Cruise

### Altitude

350

### Departure

PANC

### Arrival

KOAK

### Cruise level

FL350

### ZFW

198,300 kg

### CG

36

### Fuel

39,687 kg

### Cost index

20

### Route

PANC/07L N0479F350 DCT MDO B453 BOXER DCT SPAMY AANET1 KOAK/12

### Location

METPA TO NAKABI

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed in 0.36
