### ISSUE TITLE
[MSFS] [BUG] - Engine fire extinguish guards phasing/seen through the handles

### ISSUE THREAD

**Issue by PointBlank66** [invernyx/md11-bugs#888]
### Describe the bug

it looks like the engine fire extinguisher handle are weirdly transparent to where they don't look transparent in the first place but the handle guards are seen through it/phasing through it

### Expected behaviour

not seen through it/phase through it

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/4239471/00c08564-29bc-4120-9aed-e4b84e0f022f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
Removed transparency from fire light material
