### ISSUE TITLE
[BUG] - VOR pointer color

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#889]
### Describe the bug

Both VOR pointers are cyan

### Expected behaviour

VOR2 pointer should be green

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/9cf5fd5e-bb74-46e6-86b1-51000d0a4139)
![image](https://github.com/invernyx/md11-bugs/assets/102414406/e0a9e9b1-b0f1-404d-8d3d-990b895e2b2f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
