### ISSUE TITLE
[BUG] - Navigraph login status is not preserved

### ISSUE THREAD

**Issue by AJArkley** [invernyx/md11-bugs#890]
### Describe the bug

Every 'launch' of the aircraft requires me to log in to Navigraph in the EFB 

### Steps to reproduce

Start the sim
Load the aircraft
In the EFB, select the Navigraph tab
Log in using the code method
Close the sim (Alt + F4)
Start the sim
Load the aircraft
In the EFB, select the Navigraph tab
Navigraph will not be authenticated 

### Expected behaviour

I expect authentication to be preserved across aircraft loads

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next version
