### ISSUE TITLE
[BUG] - Wing leading edge strake missing inboard of nav light 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#892]
### Describe the bug

Wing leading edge strake missing inboard of nav light 

### Expected behaviour

It to be there 

### Evidence

![clip_image112](https://github.com/invernyx/md11-bugs/assets/150957609/281d1c4b-7f42-4097-82e0-1c6477361e3b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has already been mentioned in a previous bug report and has already been fixed in the in-development version.

**Comment by fugotaro** [comment]
Just to confirm here, as in the latest model the strake is not visible yet, will it be added later on? And just to clear up it's not the strobe light
