### ISSUE TITLE
[BUG] - Engine pre cooler vents missing on engine #2

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#893]
### Describe the bug

Engine pre cooler vents missing on engine #2 Also to note there was an option to not have vents at all on engine 1 & 3, that  probably being a pip option
### Expected behaviour

.

### Evidence

![1894655](https://github.com/invernyx/md11-bugs/assets/150957609/3d560663-3452-4d15-aef9-5bd9a4bceff1)
![4822030410_31493928ae_b](https://github.com/invernyx/md11-bugs/assets/150957609/30bd287c-56c5-452e-a16c-fca552879637)
![e8cb609733bc82aa8438f6de220c3993](https://github.com/invernyx/md11-bugs/assets/150957609/99cbb83b-eeaf-40f0-9c34-1ccf8c7400d3)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
The ones on the tail are actually see through ![1604340](https://github.com/invernyx/md11-bugs/assets/150957609/dc582227-f081-4c20-aca3-111bf1d99fda)

**Comment by arwasairl** [comment]
this has been added in an in-dev version for both GE and PW
