### ISSUE TITLE
[BUG] - CDU MSG shown

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#895]
### Describe the bug

CDU MSG shows on ND and both MCDUs show the MSG light but there is no message

### Steps to reproduce

This started when I switched to the last state panel save so it might be related to that. The annunciators are there from initial sim load.

Steps: after flight select last state panel save and restart the sim and start a flight.

### Expected behaviour

Show annunciators only when there is a CDU message shown on the MCDU.

### Evidence

![FlightSimulator_52tknwotrf](https://github.com/invernyx/md11-bugs/assets/102414406/54c64fbc-9660-4125-ae47-71757fd9409e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

33000

### Departure

KLAX

### Arrival

MMMX

### Cruise level

FL330

### ZFW

209.2tn

### CG

41%

### Fuel

19000kg

### Cost index

200

### Route

25L PNDAH2 TCATE DCT PPE UJ7 HMO UT18 NABAS UT49 DGO UJ5 ZCL UT130 DARAN DARAN2A 05R

### Location

Whole flight

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
