### ISSUE TITLE
[BUG] - Autopilot altitude window can be set up to 99500

### ISSUE THREAD

**Issue by Nighthwk4922** [invernyx/md11-bugs#896]
### Describe the bug

Currently, you're able to dial in an altitude up to 99,500. 

### Expected behaviour

The value should be clamped at the top end.

### Evidence

I wasn't able to find an exact number in the (albeit limited) documentation that I have, but other airliner addons have this value limited to below 50,000 feet, depending on the plane. 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
@turbofandude this bug can be considered closed

**Comment by turbofandude** [comment]
Resolved in 0.37+
