### ISSUE TITLE
[BUG] - Speed input into FMS freezed sim 

### ISSUE THREAD

**Issue by FightiMT** [invernyx/md11-bugs#898]
### Describe the bug

Wrong speed in the COMIX2 arrival into KSAN at LNTRN, correction led to crash to desktop

### Steps to reproduce

On arrival, went thru the waypoints to check for correct heigths and speeds. Saw that at LNTRN instead of 230, it was 250. Changed it to 230. Sim froze on click of speed input.

### Expected behaviour

230 set and go on with my flight. 

### Evidence

https://clips.twitch.tv/ReliableAdorableMartenPMSTwin-BUOJmvI4xUBo4BUJ

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

FL310

### Departure

KSFO

### Arrival

KSAN

### Cruise level

FL310

### ZFW

198100 kg

### CG

44.2

### Fuel

19900 kg on pushback

### Cost index

24

### Route

KSFO COAST9 MCKEY LAX COMIX2 KSAN, with RNAV Z 27 into KSAN from KLOMN

### Location

14.5 miles from MCKEY

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
We resolved a scenario in 0.41 that could cause this sort of behavior. Please let us know if it reoccurs with 0.41 or above.
