### ISSUE TITLE
[BUG] - destination EFOB is negative

### ISSUE THREAD

**Issue by dr71205** [invernyx/md11-bugs#899]
### Describe the bug

EFOB at destination is negative, which I'm fairly certain it should not be

### Steps to reproduce

Insert any route, ideally a long route and begin the flight with the required block fuel.
Go to PROG page and see EFOB at DEST being negative.
Also, this bug means LW calculations are incorrect.

### Expected behaviour

EFOB should not be negative, but accurately reflect the amount of fuel on board at the destination airport.

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/150094502/1ae814f6-f0c9-40ca-b3c9-33e075eb5310)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL320

### Departure

EHAM

### Arrival

TNCM

### Cruise level

FL320

### ZFW

170167 kg

### CG

27.1

### Fuel

78000 kgs during report, 88500 on departure

### Cost index

100

### Route

EHAM/18L N0478F320 VALK5E IDRID L980 LAM L179 ICTAM M197 ENHAQ DCT GAJIT DCT GAPLI/M084F340 DCT TAMEL DCT 47N015W 45N020W 41N030W 38N035W/M084F360 34N040W 27N050W/M084F380 20N060W DCT OBIKE/N0489F380 M576 MNOLO ULUBA1 TNCM/10

### Location

65 NM east of GAPLI

### Agreement

- [X] Yes

**Comment by kdries** [comment]
Similar behaviour encountered when entering arrival/approach when en-route.
Route: CYVR/08R N0484F350 DCT GARRE DCT YQU J526 YZF DCT CYZF/34
ILS34 entered during cruise and EFOB became -2175 and ETO went from 1132 to 0638

**Comment by kdries** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/6001596/ad3fd986-dbeb-46e5-b145-ee67f5af0e02)
EHAM/18L N0486F320 BERG4E BERGI L602 SUPUR L60 PENIL M144 BAGSO DCT NEBIN/M084F320 DCT 53N020W 50N030W 44N040W 38N045W 33N050W 27N055W DCT RKDIA M576 OBIKE/N0502F320 M576 MNOLO ULUBA1 TNCM/10

**Comment by JeffRichard1958** [comment]
![Screenshot 2024-04-21 195837](https://github.com/invernyx/md11-bugs/assets/148719444/9cf52370-a4e5-4c93-9d70-e5878a060fc9)

**Comment by turbofandude** [comment]
Negative EFOB is valid for a flight with too little fuel. That said, we've now corrected the EFOB/fuel burn logic and values should make sense in 0.54+.
