### ISSUE TITLE
[BUG] - Build 0.36 - No freighter in P3Dv5

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#901]
### Describe the bug

after running the installer again to update to 0.36, there is no freighter option in P3DV5

### Expected behaviour

THE F version to be available with the bug fixes across both airframes

### Evidence

@GOAROUND  on discord suggested the files are still there but the house livery has disappeared. He suggested uploading liveries to populate the f version, the freighter in P3D had a plain white livery, looking at the TFDI downloads section for P3d there are no liveries to download.
Can we have our plain white one back please, or provide the Tfdi house scheme from MSFS?  if i download this will it work in P3d?
![image](https://github.com/invernyx/md11-bugs/assets/156470813/0ace4c2f-6083-476b-8085-1e9addeda873)

### Simulator

P3Dv5

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved now, please update
