### ISSUE TITLE
[BUG] - PROG DTG + NO IRS

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#903]
### Describe the bug

PROG page shows DTG instantly after DEP/ARR is inserted on INIT 1 page even if IRS is not aligned yet.

### Steps to reproduce

Turn IRS to NAV, enter DEP/ARR codes to  INIT 1 page and check PROG page

### Expected behaviour

Show DTG after IRS is aligned

### Evidence

From AOM
![image](https://github.com/invernyx/md11-bugs/assets/102414406/8849f6d1-0268-457f-b18a-0f24bf188f45)

![rSP5oijXqP](https://github.com/invernyx/md11-bugs/assets/102414406/9b36cf02-8fef-45d2-8e83-768409cafb22)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Departure

VIDP

### Arrival

OTHH

### Cruise level

FL280

### ZFW

208.4 tn

### CG

38%

### Fuel

51000kg

### Cost index

200

### Route

29R SURAM6C SURAM G333 MERUN G202 RK G452 SOKIR/N0500F300 G452 ZDN A453 LVA L721 ALKAN ALKAN1R 34L

### Location

VIDP apron

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This has been corrected in the next version
