### ISSUE TITLE
[BUG] - CG on ENG screen shows actual CG

### ISSUE THREAD

**Issue by falcon71** [invernyx/md11-bugs#904]
### Describe the bug

The CG on the ENG screen displays the actual CG instead of a calculated CG

### Expected behaviour

Load the aircraft in the simulator. Make sure the W&B system is not installed. Apply electrical power to the aircraft and observe the CG value on the secondary engine screen. It displays the actual CG from the simulator. Without a weight and balance system, I would expect this value to be calculated based on the weights and ZFWCG entered in the FMC.

### Evidence

CG available directly after electrical power up. No WBS is installed and no values have been entered in the FMC:
![cg](https://github.com/invernyx/md11-bugs/assets/3109174/32d15592-5b08-423c-9c5c-707d3e749bfc)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by falcon71** [comment]
I do not have any reference for this.
How would the aircraft know it's actual CG without a WBS? On airbus aircraft, the CG is calculated from the pilot entered ZFWCG and the fuel, I would expect the MD-11 to work similar.

**Comment by joon44** [comment]
I found this saying that the FMS calculates the CG thats shown on the SD 
![Screenshot_20240407_005753_Drive](https://github.com/invernyx/md11-bugs/assets/102414406/b892eca6-9bc4-4367-a03e-160a2aa143f0)

**Comment by TheFightingRaven** [comment]
currently beyond the scope of our simulation, would take prohibatively long to develop for an edgecase
