### ISSUE TITLE
[BUG] - EFB Payload displays NaN

### ISSUE THREAD

**Issue by falcon71** [invernyx/md11-bugs#905]
### Describe the bug

EFB: Empty payload values are displayed as NaN

### Expected behaviour

Go to the Payload page in the EFB and switch to the ZFW tab. Click into the ZFW field and press backspace to clear the 0 in order to enter a new value. The field now displays NaN which can only be removed by leaving the field.

### Evidence

![NaN](https://github.com/invernyx/md11-bugs/assets/3109174/a0224577-395b-4d93-ab8a-6b15f0d07e6d)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next version of the EFB.
