### ISSUE TITLE
[BUG] - EFB: Loading by ZFW not working

### ISSUE THREAD

**Issue by falcon71** [invernyx/md11-bugs#906]
### Describe the bug

EFB: Aircraft does not load ZFW

### Steps to reproduce

Go to the payload page on the EFB and switch to the ZFW tab. Enter a ZFW of 178100kg and a fuel of 30000kg. Press set payload and observe the loaded ZFW.

### Expected behaviour

I would expect the aircraft to load a ZFW of 178.1 tons + 30 tons fuel = GW 208.1 tons.
Instead it loaded a ZFW of 128.8 tons (=DOW). 
Fuel was correct.

### Evidence

The values I entered:
![zfw1](https://github.com/invernyx/md11-bugs/assets/3109174/564c873d-2fda-4786-a6b1-e02b7e13b315)
The screen after set payload was pressed and the internal weights from the simulator (only for verification, I did not change any values in this screen):
![zfw2](https://github.com/invernyx/md11-bugs/assets/3109174/844bfb8b-2645-475a-a071-1bf03909a729)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be fixed in the next version of the EFB.
