### ISSUE TITLE
[BUG] - AP box on PFD

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#907]
### Describe the bug

The AP box turns white with the ATS box on engine start

### Expected behaviour

AP box turns white with V-speeds entered

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/7a50240b-3771-4a4d-9efa-8be7893518d3)
![FlightSimulator_OMy4c7nElZ](https://github.com/invernyx/md11-bugs/assets/102414406/deb3d5d2-a859-43c3-873c-c626053b54d3)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
