### ISSUE TITLE
[BUG] - Simcrash when entering TOGW on turnaround

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#908]
### Describe the bug

Sim freezes and enters unrecoverable unresponsive state upon entering TOGW when doing a turnaround.

### Steps to reproduce

- Fly into any airport
- Park and shut down aircraft
- Set up the aircraft for a new flight
- Enter TOGW on INIT2 page
- Sim freezes and becomes unresponsive which won't recover

### Expected behaviour

Aircraft is able to do a turnaround without issues.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Departure

n/a

### Arrival

n/a

### Cruise level

n/a

### ZFW

n/a

### CG

n/a

### Fuel

n/a

### Cost index

200

### Route

Arrival: SEQM - MHTG
Departure: MHTG - KAUS

### Location

On stand

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
We resolved a scenario that could have caused a freeze in 0.41. Please let us know if the issue happens with 0.41 or above.
