### ISSUE TITLE
[BUG] - NAV skipping a waypoint

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#909]
### Describe the bug

Nav skipping waypoint NIK

### Steps to reproduce

Load in this flightplan taking off from RWY18L KUDA2E WOODY N872 NIK M624 DIK M150 KRH T128 BADSO BADS2A

### Expected behaviour

To not skip it

### Evidence

![Schermopname (335)](https://github.com/invernyx/md11-bugs/assets/150957609/9ad52248-87fe-4049-a52e-7266e884a2d0)
![Schermopname (336)](https://github.com/invernyx/md11-bugs/assets/150957609/cea667ba-48e0-43a7-926f-ac822491c116)
(Me correcting it after not noticing it beforehand xD)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

EHAM

### Arrival

EDDS

### Cruise level

330

### ZFW

160kg

### CG

35%

### Fuel

16000KG

### Cost index

109

### Route

KUDA2E WOODY N872 NIK M624 DIK M150 KRH T128 BADSO BADS2A

### Location

NIK waypoint 

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
leg skipping was improved
