### ISSUE TITLE
[BUG] - infinite loop sim freeze when activating DCT

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#910]
### Describe the bug

WASM crashes and sim freezes to an unrecoverable state after activiting DCT in FMC.

### Steps to reproduce

- Select waypoint DBOYS in DIR INTC page
- Activate DIR TO
- WASM crashes and sim freezes completely to an unrecoverable state

### Expected behaviour

DIR TO can be entered without issues.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

FL 300

### Departure

MHTG

### Arrival

KAUS

### Cruise level

FL 300

### ZFW

209181

### CG

-

### Fuel

20100 kg

### Cost index

200

### Route

MHTG/02 N0507F300 DCT SAP UB753 MID UL208 DUTNA L208 SBI DCT DBOYS WLEEE7 KAUS/18R

### Location

30nm inbound SBI

### Agreement

- [X] Yes

**Comment by kdries** [comment]
Same crash upon departure out of KAUS.
Route: KAUS/18R N0506F320 DCT MUCKY DCT JCT Q20 CNX DCT ZUN DCT HAHAA DCT KLAS/26L
Departure: MUCKY3
Take-off on runway heading, then WASM crash after activating DCT PAYDA

**Comment by kdries** [comment]
Onother crash upon departure out of BGTL.
Route: BGTL/26 M084F410 WENSA2 WENSA DCT QQ DCT 7960N DCT 80N051W 81N030W DCT 8120N DCT 8000E/N0478F410 DCT NYA DCT NESAS DCT ENSB/27
13nm from WENSA DCT QQ received from ATC, sim freezes to an urecoverable state upan activating the direct to QQ

**Comment by turbofandude** [comment]
We resolved a scenario in 0.41 that could cause this sort of behavior. Please let us know if it reoccurs with 0.41 or above.
