### ISSUE TITLE
[BUG] - Freeze during cruise

### ISSUE THREAD

**Issue by falcon71** [invernyx/md11-bugs#913]
### Describe the bug

The entire simulator froze during flight

### Steps to reproduce

Not sure if it's random or can be reproduced. I followed the 2nd tutorial flight of an FSX based MD-11 simulation step by step.
The flight was:
Route: KORD/10L DCT DUFEE DCT ELX DCT HAAKK DCT DOXXY DCT SOSIC DCT JHW J70 LVZ LENDY8 KJFK/S13L
Altitude: FL350
ZFW: 430000 lbs
CG: 41.8 (was set by the simbrief import)
Fuel: 56410 lbs
CI: 80
During cruise, I modified JUNNO to AT FL230 and LENDY to 250 knots AT FL190.
The flight was done with clear skies, no wind was entered in the FMC.

I did not do anything for a while and kept the view focused on the screens. Eventually, the entire simulator froze. The task manager showed CPU activity for MSFS, but no GPU activity. There are no relevant entries in the event viewer.

Apart from some loading errors with the iniBuild A300, the simulator usually runs rock solid for me.

### Expected behaviour

I would prefer my sim not to freeze.

### Evidence

This was the view when the simulator was frozen:
![freeze](https://github.com/invernyx/md11-bugs/assets/3109174/b675920b-3c13-4b10-ac89-81ba9462b171)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by shinkicker444** [comment]
For what its worth I've had the same issue happen twice. LAX to JFK, same LENDY8 arrival, editing the same waypoints. Sim hard locked near SPI and MCI for the two flights. Live weather, FL350, CI20.

KLAX/25R DOTSS2 CLEEE DCT PKE DCT DRK J96 SLN J24 MCI J80 SAAGS/N0465F370 J80 SPI DCT WWODD DCT RINTE DCT KLYNE Q29 WWSHR DCT JHW J70 LVZ LENDY8 KJFK/22L

**Comment by FightiMT** [comment]
This is the same that happened to me COMIX2 to KSAN. Except I had the Sim Freeze immediately: https://github.com/invernyx/md11-bugs/issues/898

**Comment by turbofandude** [comment]
We resolved a scenario in 0.41 that could cause this sort of behavior. Please let us know if it reoccurs with 0.41 or above.
