### ISSUE TITLE
[BUG] - bitchin betty ABSENT P3D

### ISSUE THREAD

**Issue by steve-jacko444** [invernyx/md11-bugs#914]
### Describe the bug

femALE VOICE FOR COCKPIT ALERTS IS AWOL

### Steps to reproduce

MSFS I HAVE BEEN ABLE TO PROVOKE HER DULCET TONES, I THINK.  BUT NOT IN P3D. 

### Expected behaviour

FLAPS SPOILER, STABILISER MOTION ECT, NOT HEARD. 

### Simulator

P3Dv5

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
These sounds do work in my current build.
