### ISSUE TITLE
[BUG] - Stab trim text anomalies

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#917]
### Describe the bug

Stab trim amber box missing around the value and ANU text not in amber or green

### Expected behaviour

When stab trim is out of green band amber box should come around the stab trim value and ANU text should light up amber 
When stab trim is in green band ANU text should light up green

### Evidence

![Schermopname (339)](https://github.com/invernyx/md11-bugs/assets/150957609/526ee11c-7ee4-4b48-89ae-77e7709fe47e)
![Schermopname (337)](https://github.com/invernyx/md11-bugs/assets/150957609/cf3892c4-8dc7-4f22-b0f2-f57cd2176a4f)
![Schermopname (340)](https://github.com/invernyx/md11-bugs/assets/150957609/7853390e-3d2f-45ef-ba12-8365606aacb7)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.37+
