### ISSUE TITLE
[BUG] - WASM crash after changing view from internal camera to external drone cam.

### ISSUE THREAD

**Issue by shinkicker444** [invernyx/md11-bugs#918]
### Describe the bug

Went to an external view for a screenshot, and back into cockpit to discover none of the avionics systems could be interacted with.

### Steps to reproduce

Was flying about ~35nm west of WWODD (which is just north of KIND).
Went to external drone camera (END key)
Took screenshot via Steam (F12 key)
Rotated camera around having a look for a few moments with the mouse
Returned to cockpit view (END key)

### Expected behaviour

Not having a crash when taking a screenshot.

### Evidence

![2024-02-28](https://github.com/invernyx/md11-bugs/assets/150448167/24cf1fee-078f-4d2d-8c66-8ee169905e8b)
It could have been a coincidence or a combination of things, since as you can see in the screenshot on the right side of the screen my system was under some load, presumably loading in the KIND scenery. Where as for the rest of the flight, once out of LAX, it was running about 40% GPU and 50/70% CPU, RAM was at 19GB the whole flight.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Cruise

### Altitude

35000

### Departure

KLAX

### Arrival

KJFK

### Cruise level

FL350

### ZFW

168.2

### CG

36.6

### Fuel

18.8

### Cost index

20

### Route

KLAX/25R DOTSS2 CLEEE DCT PKE DCT DRK J96 SLN J24 MCI J80 SAAGS/N0465F370 J80 SPI DCT WWODD DCT RINTE DCT KLYNE Q29 WWSHR DCT JHW J70 LVZ LENDY8 KJFK/22L

### Location

About 35nm west of WWODD (just north of KIND)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
If this reoccurs, please let us know. Otherwise, there is unfortunately not much we can do as these functions do work under normal conditions.
