### ISSUE TITLE
[BUG] - Fuel switches are on the one position after cold and dark state 

### ISSUE THREAD

**Issue by MountainManB** [invernyx/md11-bugs#92]
### Describe the bug

AFTER SELECTING COLD AND DARK STATE THE FUEL SWITCHES ARE IN THE ON POSITION 

### Steps to reproduce

LOAD COLD AND DARK STATE AND FUEL SWITCHES ARE ALREADY IN THE ON POSITION 

### Expected behaviour

FUEL LEVERS TO BE IN THE OFF POSITION 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The panel state system was very broken but should be fixed in 0.7.0,1.
