### ISSUE TITLE
[SUGGESTION] - Add variables for COM1/2 + XPDR

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#920]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Request variables for the COM1 active and standby frequencies. Active can be pulled from the sim but standby not so while using external hardware to tune the radios, it is mandatory to point the camera towards the pedestal to see the value tuned. Obviously request variables for COM2 too but COM1 being priority.

Also XPDR code can be pulled from sim but it only updates when there are 4 digits inserted so if you clear the code and insert new code, it wont be shown "on the go" but only after the whole code is inserted.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by GenericNerd** [comment]
This was added as of 0.40.0-alpha
