### ISSUE TITLE
[BUG] - Too much negative pitch during landing with Flaps 50

### ISSUE THREAD

**Issue by uwiuke** [invernyx/md11-bugs#921]
### Describe the bug

Wrong pitch during landing with Flaps 50

### Steps to reproduce

With Flaps 35 the airplane has a pitch of 0°-1° - that's fine
With Flaps 50 the airplane goes into a negative pitch (nose down) of -2° - -3° (see picture)
(this is not correct)

### Expected behaviour

With Flaps 50 the airplane should have a pitch of 0°-1° - (similar to Flaps 35)

### Evidence

![20240229_MD11_001](https://github.com/invernyx/md11-bugs/assets/83859593/f3d143d6-4c0b-46b3-a1ea-c3f397293680)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by uwiuke** [comment]
this issue is with both versions (Passenger and Cargo)

**Comment by joon44** [comment]
No, flaps 35 pitch isnt fine at all. It is incorrect.
![Screenshot_20240329_035653_Drive](https://github.com/invernyx/md11-bugs/assets/102414406/598353c8-e58b-4fea-aa75-b818c4ce2731)
![Screenshot_20240329_035608_Drive](https://github.com/invernyx/md11-bugs/assets/102414406/8f4e6f04-3d3d-4861-a499-fbc656ace5c4)

**Comment by joon44** [comment]
Apparently 34% is the max CG. We are currently seeing 40-45% with the freighter all the time. Is this the reason for the pitch angle?

**Comment by OD-Emperor** [comment]
> Apparently 34% is the max CG. We are currently seeing 40-45% with the freighter all the time. Is this the reason for the pitch angle?

I don't think so, I just had a CG of 28.9 and this was still happening, it was maybe 2-3 degrees nose below the horizon on approach which definitely isn't correct.

**Comment by uwiuke** [comment]
Still the same issue - not possible to sell this product with this behaviour. (if you disengaged the autopilot the result is an immediately deep dive and you have to correct it with massive controll motions.

**Comment by joon44** [comment]
> Still the same issue - not possible to sell this product with this behaviour. (if you disengaged the autopilot the result is an immediately deep dive and you have to correct it with massive controll motions (v.0.41.0.1)

Obviously still the same as it hasnt been marked closed 😂

**Comment by TheFightingRaven** [comment]
fixed
