### ISSUE TITLE
[BUG] - Transponder IDENT not transmitted through simconnect

### ISSUE THREAD

**Issue by kdries** [invernyx/md11-bugs#922]
### Describe the bug

Transponder IDENT action is not shared to online networks like vatsim when pressing the ident button on the transponder.

### Steps to reproduce

- Upon ATC request, send transponder IDENT 
- (Vatsim) ATC responds some time later that no IDENT was observed.

Workaround: send ident through network client (vpilot)

### Expected behaviour

Transponder IDENT is sent to networks by pressing the ident button on the transponder.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
tested this recently and Vpilot ident light came on and atc identified after
