### ISSUE TITLE
[BUG] - Elevator is too sensitive

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#925]
### Describe the bug

giving the slightest bit of back or forward pressure causes as huge change in pitch. Not ideal for landing or taking off.

### Steps to reproduce

Just operate as normal.

### Expected behaviour

To not risk a massive tail strike during every takeoff or landing

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by OD-Emperor** [comment]
I agree with this one, aileron control is fine and heavy as expected but pitch change is waaaay too drastic.

**Comment by joon44** [comment]
I also have this now.
