### ISSUE TITLE
[BUG] - FMA wrong altitude shown

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#927]
### Describe the bug

During descend while switching from PROF to FLCH (alt pull), the target altitude above the altitude tape doesnt show the FCP set altitude but the next altitude constraint.

### Expected behaviour

Show the correct target altitude 

### Evidence

I was descending on PROF mode to 3000ft. When I pulled the alt selector to descend in level change mode, FMA switched to IDLE 4000 showing the altitude constraint from AA418. After passing AA418, it switched to 3000.
![image](https://github.com/invernyx/md11-bugs/assets/102414406/38a7083a-b192-4e09-81f1-218f7b0a68ff)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
Probably related to this issue, in this picture PROF altitude is 33000. After climbing with level change to 34000 as shown on the FCP, FMA keeps showing HOLD 33000
![FlightSimulator_BaZdmxlgrj](https://github.com/invernyx/md11-bugs/assets/102414406/4f46f12b-6e3b-4ad2-ae18-43ff81dc5356)

**Comment by turbofandude** [comment]
Resolved in 0.39+
