### ISSUE TITLE
[BUG] - Complete cockpit freeze

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#928]
### Describe the bug

Not sure if this is related to the whole simulator freeze issue which is being addressed, but I just ran into a total cockpit shutdown of everything. Nothing would work when you click on it. No change of altitude, or even flight controls. If I move the controls, it would affect the aircraft, but no animations what so ever

### Steps to reproduce

Not really sure. Just set up a normal flight I guess.

### Expected behaviour

I'd like to not have things freeze up on me.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
This is the earlier reported wasm crash. Everything besides the controls just freeze.
