### ISSUE TITLE
[BUG] - Climbout Profile Incorrect (FD commands erratic during manual flight)

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#93]
### Describe the bug

On takeoff, FD commands level-off, V2 highlighted as magenta speed. FD will not pick up correct climbout targets until after reaching altitude in FCP

### Steps to reproduce

Nav (or HDG) and PROF armed for Takeoff
Set thrust towards takeoff, select AUTOFLIGHT
Upon rotation, flight director commands nose down to level flight
"V2" appears in magenta on the speed tape
Once initial FCP altitude is captured/passed, FD will command correct speed-on-pitch to next altitude, FMS speed corrects to charted speed
When engaging autopilot, FD changes to appropriate charted climbout flight path.

### Expected behavior

On rotation, FMS speed should be V2+10, FD in speed-on-pitch to maintain (works with AP-coupled)
Reach ACCEL altitude, FMS speed should be 250 (below 10,000)
Reaching 10,000ft, FMS speed should be charted CLIMB speed

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Climb

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

NA

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I have modified the climbout behavior to match the logic described in the FCOM. I believe this should be resolved in the next build.
