### ISSUE TITLE
[BUG] - Overhead flight control panel lights

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#930]
### Describe the bug

FLAP LIMIT and ELEV FEEL show MANUAL lights incorrectly

### Expected behaviour

Lights are supposed to be in the center, not at the bottom

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/0645c011-bffc-4053-a24c-edf7aeaf3473)
![image](https://github.com/invernyx/md11-bugs/assets/102414406/aa3ac18d-122a-4c7c-a443-ebe068f8ef68)

Compared to the HYD and ELEC panels, which use the same component, the text is shown in the center
![image](https://github.com/invernyx/md11-bugs/assets/102414406/1c64f0ca-78ca-4c7e-a8f2-8cd3fc2d6942)

Real aircraft
![image](https://github.com/invernyx/md11-bugs/assets/102414406/8beaa34e-beeb-4653-a354-82ec22f34eb0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/105667840/9997e125-8626-40be-83b5-a4c4f65ad379)
