### ISSUE TITLE
[BUG] - FMS Data lost on display units after turning display brightness down fully (MD-AV-6)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#931]
### Describe the bug

When turning down the display brightness of the ND to the fully off position, then turning it back on, all NAV data is lost.  Same happens with the main EICAS DU, SYS DU and FO ND.  It is possible to recover by turning all displays off, then turning on each on again one at at time.

### Steps to reproduce

Turn CO PFD DU to OFF, then ON
Turn CO ND DU to OFF, then ON
Turn EICAS DU to OFF, then ON
Turn SYS DU to OFF, then ON
Turn FO ND DU to OFF, then ON
Turn FO PFD DU to OFF, then ON
Note loss of CO and FO ND data, engine data, systems data
Turn all DUs off
Turn on each DU one at at a time starting with CO PFD and work your way across again to recover data

### Expected behaviour

Able to turn off each individual DU in any sequence w/out losing NAV, engine or SYS data

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Departure

N/A

### Arrival

N/A

### Cruise level

N/A

### ZFW

N/A

### CG

n/a

### Fuel

n/a

### Cost index

n/a

### Route

NA

### Location

KOAK

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I am not seeing this behavior even following the exact steps.

**Comment by GenericNerd** [comment]
#1034 possibly duplicated this bug?

**Comment by turbofandude** [comment]
I believe this will be resolved in 0.65+
