### ISSUE TITLE
[BUG] - ADF pointers

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#934]
### Describe the bug

ADF1/ADF2 buttons on the EIS panels show and hide VOR1/VOR2 respectively instead of ADF

### Expected behaviour

ADF buttons show and hide ADF pointers and data
VOR buttons show and hide VOR pointers and data

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.62+
