### ISSUE TITLE
[BUG] - APU Not Initiating Automatic Shut Down

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#935]
### Describe the bug

When APU started via the electrical panel, deselecting APU AIR should initiate automatic shutdown of the APU.

### Steps to reproduce

Start APU via the electrical panel
Select APU AIR ON
-- Start Engines Normally --
Deselect APU AIR
Observe APU remains ON

### Expected behaviour

When deselecting APU AIR, "OFF" should illuminate on the APU panel and the APU should initiate an automatic shutdown.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by joon44** [comment]
After engines are started, i press apu air and ead shows apu power avail, apu start/stop button shows off and the apu shuts down. This was fixed a long time ago . What version are you on?

**Comment by GR1MMly** [comment]
Agreed it was fixed a while ago, but I have noticed recently it has stopped functioning for a while (at least for me). v0.36.0.1

**Comment by GR1MMly** [comment]
https://github.com/invernyx/md11-bugs/assets/123108304/c3ea3c4c-b3bc-4768-9560-4ed012e70f9b

**Comment by joon44** [comment]
I have to try this later today and record a video also. I just always press APU AIR button and the APU goes off without having to press anything else.

**Comment by joon44** [comment]
I tried this today. After the engine start I deselected the APU AIR. After ~45 seconds, the APU initiated shutdown and the AVAIL light on the ELEC panel turned off and the APU panel switched from ON to OFF.

**Comment by GR1MMly** [comment]
> I tried this today. After the engine start I deselected the APU AIR. After ~45 seconds, the APU initiated shutdown and the AVAIL light on the ELEC panel turned off and the APU panel switched from ON to OFF.

The APU automatic shutdown initiation should coincide with the APU AIR turning off.

The sim will auto-shutdown the APU a minute or so after engine start regardless if you turn off the APU AIR or not. Unknown if this is realistic behavior; however I think this is what you may have experienced.

**Comment by joon44** [comment]
> > I tried this today. After the engine start I deselected the APU AIR. After ~45 seconds, the APU initiated shutdown and the AVAIL light on the ELEC panel turned off and the APU panel switched from ON to OFF.
> 
> The APU automatic shutdown initiation should coincide with the APU AIR turning off.
> 
> The sim will auto-shutdown the APU a minute or so after engine start regardless if you turn off the APU AIR or not. Unknown if this is realistic behavior; however I think this is what you may have experienced.

Yes, I confirm. Deselecting apu air doesnt initiate shut down. I control the apu from a streamdeck without looking at the overhead so I was mislead on this as I only see the apu shut down after all.

**Comment by GR1MMly** [comment]
@TheFightingRaven this issue still appears in 0.41

**Comment by GR1MMly** [comment]
Issue still appears in 0.66

**Comment by GR1MMly** [comment]
Still exists in 1.0.16.0
