### ISSUE TITLE
[BUG] - Analog Standby Altimeter Needle Animation  Spins 360deg Passing Each 1000ft

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#938]
### Describe the bug

During climb, when passing each 1000ft, the analog standby altimeter needle does an instantaneous full 360 spin.

### Expected behaviour

Not that

### Evidence

https://github.com/invernyx/md11-bugs/assets/123108304/226770b2-01af-4708-8f5d-99f4b847a919

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
#798
