### ISSUE TITLE
[BUG] - Opening Airspeed Window On FCP Does Not Display Preselected Bowtie On PFD

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#939]
https://github.com/invernyx/md11-bugs/assets/123108304/25f277a2-9312-465f-b2ca-9adb4b52473e

https://github.com/invernyx/md11-bugs/assets/123108304/b239e1e5-15a6-49b8-b441-ab2e80c92896

### Describe the bug

When opening the airpseed window on the FCP, a hollow bowtie does not appear on the PFD indicating a new preselected speed.

### Expected behaviour

When 'opening' the airspeed window on the FCP, a hollow bowtie (or circle depending on if FMS SPD is selected) should appear indicating the new 'preselected' speed currently displayed in the FCP window

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
I see the preselected and selected bowties as expected. Can you clarify the behavior you're seeing and under what circumstances?

**Comment by GR1MMly** [comment]
> I see the preselected and selected bowties as expected. Can you clarify the behavior you're seeing and under what circumstances?

Tested in climb and cruise, no bowties or meatballs, added video to initial bug report.

**Comment by turbofandude** [comment]
I see what you mean - this is resolved in 0.42+.
