### ISSUE TITLE
[BUG] - FMS SPD Edit Not Functioning in Cruise

### ISSUE THREAD

**Issue by GR1MMly** [invernyx/md11-bugs#940]
### Describe the bug

When preselecting a speed on the FCP and hitting FMS SPD within 10 seconds, a speed edit is not entered

### Steps to reproduce

With FMS speed engaged, preselect a different speed and press the FMS SPD button within 10 seconds. Observe no change in commanded FMS speed.

### Expected behaviour

When preselecting a speed via the FCP and pressing FMS SPD w/in 10s, that speed should then be entered into the respective performance (CLIMB/CRUISE/DESC) page as an EDIT speed and subsequently automatically commanded.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Departure

NA

### Arrival

NA

### Cruise level

NA

### ZFW

NA

### CG

NA

### Fuel

NA

### Cost index

NA

### Route

NA

### Location

NA

### Agreement

- [X] Yes

**Comment by joon44** [comment]
I use this feature on nearly every flight. It works?

**Comment by joon44** [comment]
I checked the FMS. Flying 310kt in climb mode. I set .833 on the FCP and hit FMS SPD. PERF CLB page updated correctly to show EDIT .833 and .833 became the FMS speed.

![kuva](https://github.com/invernyx/md11-bugs/assets/102414406/b61669ad-4015-4b5f-a0db-f5cbbaaa29e2)

**Comment by GR1MMly** [comment]
I did not test it in the climb, but it was not working for me at all in cruise, v 0.36.0.1

**Comment by joon44** [comment]
> I did not test it in the climb, but it was not working for me at all in cruise, v 0.36.0.1

I'm also on 0.36.0.1 and just confirmed that the speed edit works on cruise mode also. Don't know what's creating a different behavior for us
![kuva](https://github.com/invernyx/md11-bugs/assets/102414406/c5bbff7b-c623-4375-9ae4-47fce4ee3dfe)

**Comment by GR1MMly** [comment]
While it hasnt been working for a while, speed edits appear to be working now in all phases.

**Comment by GR1MMly** [comment]
Appears to have resurfaced as of 1.0.1.0, unable to make FMS Speed edits

**Comment by joon44** [comment]
> Appears to have resurfaced as of 1.0.1.0, unable to make FMS Speed edits

Interesting. Works for me..
![image](https://github.com/invernyx/md11-bugs/assets/102414406/1f3ef496-7cd5-440f-9148-12dc0cf54f46)
