### ISSUE TITLE
[BUG] - Tape display anomalies

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#941]
### Describe the bug

Tape display shows no grey box for n1 and EPR as well I guess 

Also the limits for N1, N2 and EGT aren't showing when the engines are off 

### Expected behaviour

To see a grey box and to have limits for N1, N2 and EGT when engines are off

### Evidence

![Schermopname (353)](https://github.com/invernyx/md11-bugs/assets/150957609/51604cb9-80c6-428d-8d57-c39d84e55241)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
Same goes for dial ones, in that the limits are missing when engines are off

**Comment by turbofandude** [comment]
Resolved in 0.37+
