### ISSUE TITLE
[BUG] - Hydraulic tanks don't show any pre charge pressure 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#943]
### Describe the bug

Hydraulic tanks don't show any pre charge pressure 

### Expected behaviour

To have some pressure in the tanks while the pumps are off 

### Evidence

![Schermopname (353)](https://github.com/invernyx/md11-bugs/assets/150957609/e8e504cc-cbfe-4e3d-bd07-00c7169feba8)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
duplicate of #117

**Comment by fugotaro** [comment]
Atleast we have a reference now
