### ISSUE TITLE
[BUG] - Annunciator light test illuminates engine and APU fire handles  

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#944]
### Describe the bug

Annunciator light test illuminates engine and APU fire handles  

### Steps to reproduce

Push the annunciator light test switch 

### Expected behaviour

To have the fire handles not go on 

### Evidence

![Schermopname (356)](https://github.com/invernyx/md11-bugs/assets/150957609/5e40818a-410d-496f-8057-e9b7f6ae1069)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

0

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.37+
