### ISSUE TITLE
[SUGGESTION] - Add in a cockpit entry video system 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#946]
### Is your feature request related to a problem? Please describe.

No 

### Describe the solution you'd like

Would love to see us have the option to get a cevs unit in the cockpit, so we can keep those guys in the back in check while chilling in the cockpit 

### Describe alternatives you've considered

No I haven't lol 

### Additional context

![Schermopname (359)](https://github.com/invernyx/md11-bugs/assets/150957609/839cbdb3-3cb1-4e4a-bcb3-b426b5e5b75e)
![Schermopname (360)](https://github.com/invernyx/md11-bugs/assets/150957609/982d99c1-8313-4dcd-aca2-1bc934e7d7af)
![Schermopname (361)](https://github.com/invernyx/md11-bugs/assets/150957609/bd18df87-249c-4475-8d94-de92fb5276fd)

**Comment by arwasairl** [comment]
Cameras in general are not possible in MSFS with the current SDK. This is also why Blackbird Simulations simply cannot do targetting cameras/FLIR cameras as the possibility to do so is nil until Asobo/MS opens up this features to 3PD developers.
