### ISSUE TITLE
[BUG] - VOR beacons shown incorrectly on the ND 

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#948]
### Describe the bug

Tuned VOR beacons are shown incorrectly in cyan or not at all

### Expected behaviour

A tuned beacon is always shown in white irrespective of the VOR NDB switch.

### Evidence

Without VOR/NDB selected, the tuned MAR VOR is not shown at all.
![kuva](https://github.com/invernyx/md11-bugs/assets/102414406/3372443d-e6ea-4ed4-93a7-4057b426d418)

With VOR/NDB selected, the tuned MAR VOR is shown in cyan.
![kuva](https://github.com/invernyx/md11-bugs/assets/102414406/9ae2dd36-4600-4458-af2c-b03a00332d2a)

Tuned VORs are shown in white and to my interpretation, can not be switched off with the VOR/NDB switchl
![kuva](https://github.com/invernyx/md11-bugs/assets/102414406/75c241af-56e2-4403-a847-f42b31398698)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.39+
