### ISSUE TITLE
[BUG] - fuel burn roughly 2 times what it should be

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#95]
### Describe the bug

the fuel burn is way to high

### Steps to reproduce

fly

### Expected behaviour

be less

### Evidence

it burns roughly 7500pounds per engine per hour, it should be 1500kgs per engine per hour in cruise

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

FL410

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
This should be fixed in 0.8 and above
