### ISSUE TITLE
[BUG] - Engine FAIL, BELLOW G/S and G/S INHIBIT light not going on when pressing annunciator test switch 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#950]
### Describe the bug

Engine FAIL, BELLOW G/S and G/S INHIBIT light not going on when pressing annunciator test switch 

### Expected behaviour

For it to go on

### Evidence

![Schermopname (362)](https://github.com/invernyx/md11-bugs/assets/150957609/cc21b23b-c38f-4109-93aa-e1b108973a74)
rnyx/md11-bugs/assets/150957609/a545f502-fdb3-4251-8ae3-5ccf91fde879)

![Schermopname (364)](https://github.com/invernyx/md11-bugs/assets/150957609/ecea1bc1-16de-4140-bc37-d507844d4f6a)
![24230_1301691610](https://github.com/invernyx/md11-bugs/assets/150957609/a9f461b0-1b8f-4c77-97ed-2bc53b4e74ba)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The BELOW G/S and G/S INHIBIT lights do not seem to be mapped. Tagging Ozzy. The ENGINE FAIL light is not coded but will be for the next update.
