### ISSUE TITLE
[BUG] - Master warning light not flashing during annunciator test 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#951]
### Describe the bug

Master warning light not flashing during annunciator test 

### Steps to reproduce

Push and hold the annunciator test switch 

### Expected behaviour

For it to flash like the video https://youtu.be/rjf9sMh-GDY?si=neP7VAPiZU_0UME-&t=138

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Fixed in 0.39+
