### ISSUE TITLE
[BUG] - IDLE CLAMP mode missing

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#952]
### Describe the bug

The level change descend doesnt work correctly. ATS doesnt go to IDLE CLAMP mode and the FMA annunciation is thus incorrect

### Steps to reproduce

While flying, switch to level change descend mode by pulling the alt selecor. Notice FMA showing IDLE + altitude in white

### Expected behaviour

FMA annunciation  IDLE CLAMP + altitude in white and the autothrottle servos to disconnect so thrust levers can be manually controlled while in CLAMP mode.

### Evidence

Only white IDLE shown without CLAMP
![kuva](https://github.com/invernyx/md11-bugs/assets/102414406/1ecd5737-029b-43b0-97b1-5195e0fb6784)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Descent

### Departure

LSZH

### Arrival

EBBR

### Cruise level

FL300

### ZFW

209.2tn

### CG

41%

### Fuel

18.5tn

### Cost index

20

### Route

LSZH/28 N0467F300 VEBI4W VEBIT T51 LASUN T14 LUMEL T10 TORPA DCT EDOPI DCT GIVOR DCT SORAL DCT IBERA DCT DIK Y37 BATTY BATY6A EBBR/25R

### Location

Anywhere in the air

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.42+
