### ISSUE TITLE
[BUG] - Engine start switch always show manual

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#953]
### Describe the bug

both start systems always show manual

### Steps to reproduce

boot up the plane

### Expected behaviour

neither button should show manual unless auto ignition has failed, then manual should show only on the selected system(s) 

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/60278d69-5211-4946-bfb5-57d3fd9964bf)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/80b2146f-4f7c-4412-9215-d047f084919b)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/4819fb9f-de20-45d8-b8dd-15aacbb6a2f2)

### Simulator

P3Dv4, P3Dv5, P3Dv6, Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

n/a

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
I might add this is technically regression as manual would previously only illuminate on a selected system, which wasn't right either but the current way is more wrong

**Comment by TheFightingRaven** [comment]
![image](https://github.com/invernyx/md11-bugs/assets/138527559/7e52516a-818a-4188-a2ed-767f3b035dd0)
it shows correctly on the pax

**Comment by slowreload** [comment]
Can also confirm that this is happening

**Comment by kdries** [comment]
On MD11F GE 
Build 0.41.0.1
![image](https://github.com/invernyx/md11-bugs/assets/6001596/e9b14926-195e-4102-9254-f9b374449832)

**Comment by jhattermann** [comment]
This was fixed in the last branch merge.
