### ISSUE TITLE
[BUG] - right wing dented freighter

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#954]
### Describe the bug

near the wing tip of the right wing of the freighter there is a big dent in the model

### Expected behaviour

no dent

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/2da3eb73-02a3-4189-8f56-47b51a886d29)![image](https://github.com/invernyx/md11-bugs/assets/138527559/a8317409-2659-4cb5-b065-8cb5b65000c0)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Fixed
