### ISSUE TITLE
[BUG] - The N1 power settings on final, with flaps 35 are still high

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#957]
### Describe the bug

The N1's appear to be about 10 percent high.

### Steps to reproduce

configure to landing configuration and reference the CG.

### Expected behavior

I may be mistaken on this one, or it may have to do with the CG issues, but the N1's are about 10 percent high. However, if the aircraft is fighting an extremely aft CG, that would increase the AOA and would make the N1's higher.

### Evidence

![Screenshot 2024-03-31 064817](https://github.com/invernyx/md11-bugs/assets/148719444/fe09658e-2fbd-4ff4-a825-98d3a8deae81)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved
