### ISSUE TITLE
[BUG] - GE dials

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#958]
### Describe the bug

ge dials ranges need a bit of adjustment

### Expected behaviour

have correct range

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/1bdc02d6-6bed-4a68-9857-51b5cecc38c4)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/2e68a006-cf18-4b03-a979-baacb54bed16)
N2 need slightly more range (see red tick)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/07e7d94d-64a3-4815-beec-63f0491ff3bf)
![image](https://github.com/invernyx/md11-bugs/assets/138527559/00da698a-9b0e-4137-a6bd-bf9c6c77930d)
oil temp needs slightly less range (see amber and red ticks)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.310+
