### ISSUE TITLE
[BUG] - dial engine SD text alignment

### ISSUE THREAD

**Issue by TheFightingRaven** [invernyx/md11-bugs#959]
### Describe the bug

EVM text missaligned on the dial engine SD

### Expected behaviour

be aligned

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/138527559/a0d89e23-b0c4-408a-8662-7a2826c287fa)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.310+
