### ISSUE TITLE
Parking Brakes

### ISSUE THREAD

**Issue by dc10boy** [invernyx/md11-bugs#960]
### Is your feature request related to a problem? Please describe.

An unknown binding from a peripheral, (Honeycomb Bravo) prevented the parking brake from being released.

### Describe the solution you'd like

Could we slave the parking break lever to the in sim position, that way if a device is forcing the parking brake on the lever will also show as set and when you unset it in the virtual cockpit and it shoots back you know something is overforcing it

### Describe alternatives you've considered

None

### Additional context

None

**Comment by turbofandude** [comment]
It actually does honor the bui;t-in parking brake set/release event. If you have a binding on the Honeycomb that constantly sets the parking brake to on, our code will be unable to set it.

In this case, did the MD-11's parking brake lever show released? i.e. Was there a mismatch between the visual model and the actual brake?

**Comment by dc10boy** [comment]
Yes, the Parking Brake lever showed off, The message was cleared from the screen, but no pushback was possible as the  utilities showed brakes set. after clearing the PB binding problem resolved.

**Comment by TheFightingRaven** [comment]
this is most likely then a brakes binding, having 100% brakes set is treated as parking brake
