### ISSUE TITLE
[BUG] - ATS box goes red instead of amber using reversers when ATS is in use 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#963]
### Describe the bug

ATS box goes red instead of amber using reversers when ATS is in use 

### Expected behaviour

To have the ATS box go amber instead of red when reversers are selected 

### Evidence

![Schermopname (367)](https://github.com/invernyx/md11-bugs/assets/150957609/92517536-fc1d-41e2-befb-ad94f66a402d)

![Schermopname (368)](https://github.com/invernyx/md11-bugs/assets/150957609/86b75bb9-20a7-4b25-ba72-d7f3eab7edb9)

https://youtu.be/hWMQ156rJK4?si=ui32ADzSXofNNgmy&t=615

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
The retard text should pop on and off acc this 
https://youtu.be/3wzS6fn8BA8?si=RuE64RI4KgFO7OKC&t=8217

**Comment by turbofandude** [comment]
The flashing red box is fixed in 0.39+ - I see the flashing in the video but have zero reference on when/why it flashes other than that video.
