### ISSUE TITLE
After Annunciator Test, galley power pushbutton remains illuminated

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#965]
### Describe the bug

After Annunciator Test, galley power pushbutton remains illuminated

### Expected behaviour

Following the Annunciator Lights Test, all pushbutton lights should return to the pre-test state.

### Evidence

![Screenshot 2024-04-01 070428](https://github.com/invernyx/md11-bugs/assets/148719444/4da61fe6-d430-4a67-8df2-63b774cb8fd5)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.39+
