### ISSUE TITLE
Approaching Altitude incorrectly has an aural tone

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#966]
### Describe the bug

Approaching Altitude incorrectly has an aural tone when it should just have a solid amber box on the altitude on the PFD and no aural.

### Expected behaviour

When climbing or descending to an altitude on the FCP, there is an aural tone. That tone is only for deviations from an assigned altitude once level and is also accompanied by a flashing amber box around the altitude on the PFD. 

The only indication that changes when climbing or descending to an altitude on the FCP is the altitude on the PFD has a solid/steady amber box. There is no aural tone. 

I am attaching the FOM reference, but it should be verified with Nick.

### Evidence

![IMG_2778](https://github.com/invernyx/md11-bugs/assets/148719444/525df33f-2c02-49a7-93d3-71c07bf80b7b)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
Looks like it was a customer option, as KLM had the chord activated but not the voice for approaching the selected altitude 
![Schermopname (420)](https://github.com/invernyx/md11-bugs/assets/150957609/530580ce-1390-47fa-88cb-f808bf856149)

**Comment by JeffRichard1958** [comment]
Thank you!!!

**Comment by turbofandude** [comment]
This will be an option and the other missing functionality (amber within 1000 feet, etc.) has been added as of the next release.
