### ISSUE TITLE
Cargo Fire Test should have accompanying EAD messages and a Master Warning Light.

### ISSUE THREAD

**Issue by JeffRichard1958** [invernyx/md11-bugs#967]
### Describe the bug

Cargo Fire Test should have accompanying EAD messages and a Master Warning Light.

### Expected behaviour

When conducting the Cargo Fire manual test, there should be a Master Warning light and corresponding EAD Messages. 

### Evidence

![IMG_2779 2](https://github.com/invernyx/md11-bugs/assets/148719444/67c9c31f-d654-4efd-aaba-f0c328722f66)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The behavior outlined in the manual is exactly how ours behaves.

**Comment by JeffRichard1958** [comment]
There is no MW light on the glareshield nor an accompanying EAD warning for a Cargo Fire? Wow. All fires are accompanied by a MW light and EAD warning message on all AAL aircraft. Okay. Thanks Collin.Sent from my iPadOn Apr 4, 2024, at 2:11 PM, Collin Biedenkapp ***@***.***> wrote:﻿
The behavior outlined in the manual is exactly how ours behaves.
