### ISSUE TITLE
[BUG] - ELEC page anomalies 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#969]
### Describe the bug

ELEC page anomalies 

### Expected behaviour

The G should be green in normal ops 
The the DISC text should be amber when disconnected
Text is misagligned when gen is disconnected 

### Evidence

![Schermopname (443)](https://github.com/invernyx/md11-bugs/assets/150957609/866b7e32-fb55-4594-bf4c-177676a83126)
![Schermopname (444)](https://github.com/invernyx/md11-bugs/assets/150957609/b19ef98d-fc63-4f1a-9a6b-5033fee0cb01)
![Schermopname (445)](https://github.com/invernyx/md11-bugs/assets/150957609/ae55122a-f561-43f0-8f6f-447fc22dca65)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.310+

**Comment by fugotaro** [comment]
Can this issue be reopened, as the G isn't green in normal ops still  
![Schermopname (469)](https://github.com/invernyx/md11-bugs/assets/150957609/5e4df676-eeec-479e-9c66-702807ed69f3)

**Comment by turbofandude** [comment]
Resolved in 0.42+

**Comment by fugotaro** [comment]
Still not fixed

**Comment by fugotaro** [comment]
Fixed since 0.52
