### ISSUE TITLE
No lights from the bulbs 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#972]
### Describe the bug

No light is showing from the bulb. Instead it's reflecting off the ground 

### Expected behaviour

Bulbs should light up 

### Evidence

![FlightSimulator 2024-04-05 00-41-56](https://github.com/invernyx/md11-bugs/assets/70169249/de94e70d-e92d-40c4-a39d-ca6a71f91ea3)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Resolved
