### ISSUE TITLE
Nose wheel moves wrong direction

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#973]
### Describe the bug

When moving, Nosewheel moves in the opposite direction to the main landing gear

### Expected behaviour

Move in the correct direction 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
Same for the left hand main gear

**Comment by arwasairl** [comment]
This bug has already been reported. See: https://github.com/invernyx/md11-bugs/issues/746
