### ISSUE TITLE
[BUG] - Lights stay on C&D

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#974]
### Describe the bug

Lights on when power off

### Expected behaviour

Lights should go off

### Evidence

![FlightSimulator 2024-04-05 00-02-23](https://github.com/invernyx/md11-bugs/assets/70169249/3edf9c2f-7287-4b67-bc89-9b287b778854)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Resolved
