### ISSUE TITLE
Engine fans animation needs tweaking

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#975]
### Describe the bug

Fans spin due to animation issue. Should move smoothly etc (look at FENIX's for ref) 

### Expected behaviour

Look at FENIX's for ref 

### Evidence

Videos too big, pls see discord channel 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Fenix uses a custom engine RPM variable, while we use the default MSFS one. @turbofandude Is it too much trouble to create a custom animation tag for engine blade spinning?

**Comment by arwasairl** [comment]
Resolved
