### ISSUE TITLE
No flap noise 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#976]
### Describe the bug

No flap sounds when lowering/stowing flaps n slats 

### Steps to reproduce

Move flaps down, Wing view 

### Expected behaviour

Flap sounds to be present 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.60+
