### ISSUE TITLE
Nav lights beam radius is far too big & no strobe pulse/flicker

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#977]
### Describe the bug

Nav lights beam way too far around the wings & you can't see the strobes flickering 

### Expected behaviour

Strobe flickering & less nav beam radius 

### Evidence

![FlightSimulator 2024-04-05 01-02-50](https://github.com/invernyx/md11-bugs/assets/70169249/7b2d3c35-1419-4e71-b2d5-f720be691ee6)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has already been reported. See: https://github.com/invernyx/md11-bugs/issues/583
