### ISSUE TITLE
Can't set STD or move the STD knob on digital standby display 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#978]
### Describe the bug

Can't set STD or move the STD knob on digital standby display 

### Expected behaviour

Knob should be modelled to set STD & change BARO pressure 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by jhattermann** [comment]
We do not have tags for any of the ISFD interactions yet

**Comment by arwasairl** [comment]
@turbofandude See above
