### ISSUE TITLE
Chair quality is low res 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#979]
### Describe the bug

See photo

### Expected behaviour

Increase the resolution to make it look crisper 

### Evidence

![FlightSimulator 2024-04-05 01-32-44](https://github.com/invernyx/md11-bugs/assets/70169249/3f1f519a-4696-48c5-b5d5-eeb2095f74b2)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has been previously reported by you: https://github.com/invernyx/md11-bugs/issues/465
Please check to see whether the same bug is open or still in progress before making a new one.
