### ISSUE TITLE
[BUG] - ANNUN LT test triggers TERRAIN OVRD

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#980]
### Describe the bug

Pressing the ANNUN LT test button enables TERRAIN OVRD from GPWS panel and it must be turned off manually.

### Steps to reproduce

Do the lights test. This happens at least in the air. I don't recall if I saw this on the ground during preflight.

### Expected behaviour

Enable TERRAIN OVRD only when pressed from the correct button

### Evidence

ANNUN LT test pressed
![FlightSimulator_323Z0nU5n6](https://github.com/invernyx/md11-bugs/assets/102414406/85d04f4c-4e0c-4d51-b36f-4401d505bf24)

After ANNUN LT test released
![image](https://github.com/invernyx/md11-bugs/assets/102414406/59081be8-a533-4e8f-82c2-a44dd5ad5b44)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.310+
