### ISSUE TITLE
[BUG] - KLM Livery logo reversed

### ISSUE THREAD

**Issue by FoxxenD** [invernyx/md11-bugs#983]
### Describe the bug

The KLM logo on the tail on the right side is inversed

### Expected behaviour

The logo should not be inversed

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/32935159/36632ca9-4edd-46f9-95e1-2631eaac9fce)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by ElMikey70** [comment]
The tail has been fixed.
