### ISSUE TITLE
[BUG] - Fuel Used Reset

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#984]
### Describe the bug

Fuel used reset button doesn't do anything anymore.

### Steps to reproduce

Press the fuel used reset after burning some fuel. Notice that it doesnt reset on the FUEL SD page. I noticed this after a turnaround on a second flight. It might work on the first flight. I don't know.

### Expected behaviour

Fuel used reset button to reset used fuel to zero on all 3 engines.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

32000

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
The button does work but all 3 engines must be off.
