### ISSUE TITLE
[BUG] - Partly missing cockpit sounds

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#985]
### Describe the bug

Spoiler and flap handles do not make sounds

### Steps to reproduce

Move both levers. Notice no sounds. Not even with using lvars to move them.

### Expected behaviour

Sounds when moving the levers.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Duplicate
