### ISSUE TITLE
[BUG] - Empty Amber Box

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#986]
### Describe the bug

Empty amber Box in first Warning Column on the rightmost CPT DU

### Expected behaviour

No Box

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/9b44230e-0a8a-443a-b13b-d25245ed8559)
SaveState (MENU>DEV): [EMPTYAMBER.json](https://github.com/invernyx/md11-bugs/files/14887301/EMPTYAMBER.json)

The Box appeared after cycling the Fuel Sys to MAN thrice (accompanied with a cargo fire test)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Resolved in 0.310+
