### ISSUE TITLE
Pitch degree numbers disappear on takeoff 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#988]
### Describe the bug

See above 

### Expected behaviour

Numbers to show on PFD

### Evidence

![FlightSimulator 2024-04-05 21-17-39](https://github.com/invernyx/md11-bugs/assets/70169249/5fec3109-bd71-4b88-a1f5-8d8b4c587546)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by joon44** [comment]
The 20 digits are blinking for me

![image](https://github.com/invernyx/md11-bugs/assets/102414406/6e50c720-e912-47a8-aa2e-73e67dfdbf7a)
![image](https://github.com/invernyx/md11-bugs/assets/102414406/f5ad1f27-f339-48ea-bf02-b5a5d073fa04)

**Comment by fugotaro** [comment]
So if you go above 5 degrees pitch up the 20 disappears and above 15 the 10 goes

**Comment by joon44** [comment]
> So if you go above 5 degrees pitch up the 20 disappears and above 15 the 10 goes

I only had the 20 digits disappearing but its happened  only once

**Comment by joon44** [comment]
OK I can verify now that going above 5 degrees nose up, 20 digits disappear and going above 15 degrees nose up, 10 digits disappear. Going below 5 and 15 degrees the digits return respectively.

**Comment by turbofandude** [comment]
Should be resolved in 0.41+
