### ISSUE TITLE
Beacon light needs tweaking 

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#989]
### Describe the bug

Beacon like seems unnatural & doesn't give off any real ambiance 

### Expected behaviour

Light to look more natural 

### Evidence

![FlightSimulator 2024-04-05 21-03-58](https://github.com/invernyx/md11-bugs/assets/70169249/75333bfe-d96c-4477-91c1-7dfb3364d2ee)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Please describe what exactly could make the beacon more natural. Is the halo affect simply too bright during the day, or is the light source itself (not the halo) too minor during the day?

**Comment by davidnorfolk96** [comment]
I'd say the light source itself. It's quite hard to describe. I've noticed the reflection at night isn't that bright either

**Comment by joon44** [comment]
Id like to see a big reflection on the lower fuselage and engines
