### ISSUE TITLE
[BUG] - Sluggish turning whilst taxiing 

### ISSUE THREAD

**Issue by scotsgod** [invernyx/md11-bugs#99]
### Describe the bug

Very sluggish turning whilst taxiing 

### Steps to reproduce

Honestly just spawn in and try and taxi to any runway.

### Expected behaviour

3knt seems to be the fastest you can turn in the aircraft even in shallow turns 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
fixed with correct CG
