### ISSUE TITLE
[BUG] - Missing HI-INT lights

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#990]
### Describe the bug

The double flash in front of the wing is missing. The single flash behind the wing is there. Also the light bulb doesnt flash but it can be seen only at the ground.

### Expected behaviour

Show both double and single strobes and also the flashes at the wingtip light bulbs.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
Resolved
