### ISSUE TITLE
[BUG] - Some textures are flickering

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#992]
### Describe the bug

Cockpit window frame textures are flickering. There is flickering "ghost" window next to R3 door. The flickering happens regardless of zoom or point of view.

### Expected behaviour

The textures should not be flickering

### Evidence

https://github.com/invernyx/md11-bugs/assets/150369113/a211ba8d-9cd3-4794-9b58-07e2642bddc1

https://github.com/invernyx/md11-bugs/assets/150369113/2a96b6dc-7fc5-4030-b9fe-b1cf62276555

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
@jhattermann There is some Z-fighting along the cockpit window borders, can you confirm if you have a mesh like that in the cockpit model? otherwise it will clash with the exterior

**Comment by jhattermann** [comment]
There was geometry there, it has since been removed
