### ISSUE TITLE
[BUG] -  Engine textures while spinning

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#994]
### Describe the bug

Engine textures are weird and look really, as well with the landing gear

### Expected behaviour

Are there any plans to imrpove the simulation of the engine since its glitching out now while spnning? 

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This has already been reported. See: https://github.com/invernyx/md11-bugs/issues/975
and: https://github.com/invernyx/md11-bugs/issues/746

In the future, please check by using the search bar if your bug has already been reported. Do not open duplicate reports.
