### ISSUE TITLE
[Feauture req] - Animated cockpit doors and windows

### ISSUE THREAD

**Issue by Daniz010** [invernyx/md11-bugs#995]
### Describe the bug

Cockpti door and animated windows inside the cockpit

### Expected behaviour

Are there any plans for addin this into the plane?

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Freighter GE

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Please use the correct template for suggestions
