### ISSUE TITLE
[BUG] - HYD PRES TST FAIL

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#997]
### Describe the bug

Hydraulic pressure test fails every time now but the hydraulics work correctly on the flight

### Steps to reproduce

Load cold & dark panel state and after the electrics are turned on, do the test. I dont know if this is related to the panel state. It started with the 0.39 version.

### Expected behaviour

Test to pass when the hydraulics system works correctly.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

50

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
This will be resolved in the next update.
