### ISSUE TITLE
[BUG] - Various false EAD messages

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#998]
### Describe the bug

EAD is showing lots of false messages. This came with the latest 0.40 version and using cold & dark panel state.

### Expected behaviour

Show only relevant messages as before

### Evidence

Situation after engine start. EAD is showing lots of messages. Overhead shows everything is as supposed to.
![FlightSimulator_B0hvWqsXvL](https://github.com/invernyx/md11-bugs/assets/102414406/9473e11b-1306-40d5-bafa-960b82d6c628)

![FlightSimulator_gv4Y8ea47D](https://github.com/invernyx/md11-bugs/assets/102414406/2fcba01b-8773-415a-8186-7807eb68051a)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by MikeA34** [comment]
Same happened to me with Cold & Dark state. There appears to be same kind of issues with other states (Ready to start #999 )

**Comment by JohnWilkins82** [comment]
Also have this issue from Cold and dark
![md11coution](https://github.com/invernyx/md11-bugs/assets/58406371/35115d9b-5c3f-4fac-96eb-23a20802f5a8)

**Comment by wagoozen1** [comment]
I got the same behaviour as mentioned here, with build 0.40.0-alpha

**Comment by uwiuke** [comment]
Same for me :-(

**Comment by turbofandude** [comment]
Should be resolved in 0.41+
