### ISSUE TITLE
[BUG] - False Indications on EAD

### ISSUE THREAD

**Issue by MikeA34** [invernyx/md11-bugs#999]
### Describe the bug

There are false indications on the EAD

### Expected behaviour

The indications should not be shown. 

### Evidence

There are false indications on the EAD, including APU AIR/ELEC showing 'ON' while the APU is off, AIR 1-3 ISOL ON  shown , PARK BRAKE ON when the parking brake is OFF, and displaying the PARK BRAKE indication twice when the Parking Brake is ON. Additionally, in-flight, the NO SMOKING and SEAT BELTS messages persist even with selectors in the OFF position.

At EFHK holding point WG with Parking Brake ON:
![Näyttökuva 2024-04-06 113459](https://github.com/invernyx/md11-bugs/assets/150369113/0638700f-7bcf-417f-b9ea-e8e121feb288)
![Näyttökuva 2024-04-06 113542](https://github.com/invernyx/md11-bugs/assets/150369113/1c635c99-839f-43f4-bbfa-1addddfa8a23)

Parking Brake OFF:
![Näyttökuva 2024-04-06 114038](https://github.com/invernyx/md11-bugs/assets/150369113/89f7bc8b-4ba9-4df2-92e8-58e493688373)

Airborne, SEATBELTS & NO SMOKING selectors OFF (No change with AUTO):
![Näyttökuva 2024-04-06 121425](https://github.com/invernyx/md11-bugs/assets/150369113/3b29192c-bc6d-4dba-bf12-461c5870ddc1)
![Näyttökuva 2024-04-06 121458](https://github.com/invernyx/md11-bugs/assets/150369113/e11035f6-6d77-469e-acd4-e5e04d5a6424)

For reference, the flight was initiated from the 'ready to start' state and version is 0.40.0.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Should be resolved in 0.41+
